### ISSUE TITLE
Provide user-level commands to replicate workflow on complicated pipelines

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1008]
The more complicated pipelines, such as WFSS, involve a specific order of execution of both level2 and level3 pipelines. The current process is optimized for SDP. However, for a user to replicate the process, this would currently involve running up to four calibration pipelines, in a specific order, on different sets of associations.

Will need to provide uber-scripts/commands that will encapsulate these flows to make these processes user-friendly.

**Comment by melanieclarke** [comment]
Closing as won't do - I think this kind of high-level user support is generally provided via example notebooks now.  Please reopen if higher level uber-pipelines are still desirable.
