### ISSUE TITLE
Some PEP8 clean-up needed in fits_generator

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#1037]
You have done it to my Emacs... 👏 

This is only from `fits_generator/pyparsing.py`:
```
Warning (flycheck): Syntax checker python-flake8 reported
too many errors (705) and is disabled.
```

**Comment by pllim** [comment]
These PEP8 violations actually affect all the modules, not just `fits_generator`. In #1377 , I was very lenient and added a lot of warnings to be ignored by `flake8`. However, there are still hundreds (better than thousands...) of warnings that would be wrong to ignore. For example, but not limited to:

* Undefined variables
* Redefinition of previously defined functions
* Not using `is not`, `is`, etc when appropriate

**Comment by jdavies-st** [comment]
I would propose a mini-sprint one of these afternoons after the dust settles on build 7.1.  A couple hours with everyone taking a chunk could repair these.  And once they're repaired, we can enforce more strict checking in our Travis CI flake8 tests.

**Comment by pllim** [comment]
For those not familiar with `flake8`, please note that `flake8` tied to your editor (e.g., Emacs) would be smart enough to also ignore the `ignore=` and `exclude=` stuff set in `setup.cfg`. So when you get to the fun sprint, remember to remove the warning(s) you would like to tackle in `setup.cfg`.

**Comment by pllim** [comment]
There is also tools like [autopep8](https://pypi.python.org/pypi/autopep8) that you can use to help speed up the editing, though you would want to double check the `diff`.

**Comment by jdavies-st** [comment]
This is actually not done, as `fits_generator` is currently being ignored:

https://github.com/spacetelescope/jwst/blob/4285c4efb95bc368f36456e9e106e6aba6abd597/pyproject.toml#L18

**Comment by hbushouse** [comment]
When I just manually ran `ruff` on the fits_generator package it did return some warnings, but not that many and none that are serious (e.g. undeclared variables). They were all just annoyances, like formatting or unused imports. Granted it could still be cleaned up sometime, but it's currently no worse than fluff warnings we get from the rest of the jwst package.
