### ISSUE TITLE
Convert Level2 pipeline association processing loop to a separate step

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1096]
Currently the Level 2 pipelines loop over a call to a method. Instead, convert the method to another Pipeline. This will allow the method to take advantage of the Step architecture, in particular, centralizing any teardown processing that may need done, as the Step architecture already does.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1580](https://jira.stsci.edu/browse/JP-1580)._

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1580?focusedCommentId=474060#comment-474060):_

Given that a level 2 association only ever has 1 product, couldn't the loop just be removed?

Also, the capturing of errors and tossing them into the log output needs to be fix (i.e. not done)

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1580](https://jira.stsci.edu/browse/JP-1580)._

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1580?focusedCommentId=474060#comment-474060):_

Given that a level 2 association only ever has 1 product, couldn't the loop just be removed?

Also, the capturing of errors and tossing them into the log output needs to be fix (i.e. not done)

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-1580?focusedCommentId=690064#comment-690064):_

Closing as this doesn't seem particularly relevant any longer, but please reopen if it still needs to be given attention.
