### ISSUE TITLE
calspec2 background subtraction needs to check GWA tilt

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#1149]
The direct image-to-image background subtraction method implemented in calspec2, which uses either dithered/nodded exposures of the science source or exposures obtained on a dedicated background target, needs to have a check added to it the verifies the exposures to be used as background have the same NIRSpec GWA tilt values as the science exposures. Exclude any background exposures that don't have the same tilt and if there aren't any useable background exposures left, then skip the background subtraction step.

**Comment by jemorrison** [comment]
Should I update #3252 so that if a list of background images are giving and some of the same gwa_xtilt, gwa_ytitl it pulls out the good ones and uses those for the background ?
Currently it will just skip the background step if any of the background images do not have the same gwa values

**Comment by hbushouse** [comment]
I think that would complicate it too much and could lead to variable results from one source exposure to another. I would leave it as all or nothing. From my understanding of the way the GWA is commanded, that's the way the data will appear (i.e. all source exposures will have identical values and all backgrounds would also have the same value - but possibly different from the source value).
