### ISSUE TITLE
Allow NIRSpec imprint subtraction step to use a user-supplied imprint image

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#1150]
The calspec2 imprint subtraction step - which is only used for NIRSpec MSA and IFU exposures - currently relies on dedicated imprint exposures that were taken along with the science exposures and having those imprint exposures identified in the ASN table that drives calspec2. The NIRSpec team would like this step (at some point in the future) to also allow a user to supply an imprint image of their own, without having it listed or identified in the ASN table.

**Comment by melanieclarke** [comment]
@hayescr - do you know if this is still desirable, or if adding the imprint image to the ASN is sufficient?

**Comment by hayescr** [comment]
I'm inclined to say that the ability to add custom imprint images to the ASN is sufficient, but I'm checking with the NIRSpec Team to confirm.

**Comment by hayescr** [comment]
I confirmed that, yes, adding the imprint images to the ASN is sufficient.  

It might be nice, though, to update the imprint step documentation to describe how users should include imprint exposures in their processing, as is done for the backgrounds in the Image-from-Image background subtraction page (https://jwst-pipeline.readthedocs.io/en/latest/jwst/background_subtraction/main.html#image-from-image-subtraction).  Currently the documentation for the imprint step doesn't mention that leakcal exposures should be added to ASNs as "imprint" members.

**Comment by melanieclarke** [comment]
Excellent, thank you.  I will close this old ticket and file a new one for the documentation update.

**Comment by hayescr** [comment]
Thanks @melanieclarke!
