### ISSUE TITLE
exposures that get Level 2b processing

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1188]
Prompted by [this comment](https://github.com/STScI-JWST/jwst/issues/735#issuecomment-292226126), this issue documents exactly which exposures will go through any type of Level 2b processing, such as Spec2Pipeline or Image2Pipeline.  Please review, update, and if updated, leave a comment that one has done so. Questions in following comments.

EXP_TYPE | Association Exposure Type | Specials | Level2b?
---------- | --------------------------- | --------- | ---------
NRC_IMAGE | science | n/a | YES
NRC_GRISM/NRC_WFSS | science | n/a | YES
NRC_TACQ | target_acquisition | n/a | YES
NRC_TACONFIRM | target_acquisition | n/a | YES
NRC_CORON | science | n/a | YES
NRC_CORON | psf | PSF | YES
NRC_TSIMAGE | science | n/a | YES
NRC_TSGRISM | science | n/a | YES
NRC_FOCUS | science | n/a/ | YES
NRC_DARK | dark | n/a | NO
NRC_FLAT | flat | n/a | NO
NRC_LED | science | n/a | NO
 | | |
MIR_IMAGE | science | n/a | YES
MIR_TACQ | target_acquisition | n/a | YES
MIR_LYOT | science | n/a | YES
MIR_LYOT | psf | PSF | YES
MIR_4QPM | science | n/a | YES
MIR_4QPM | psf | PSF | YES
MIR_LRS-FIXEDSLIT | science | n/a | YES
MIR_LRS-FIXEDSLIT | background | BACKGROUND | YES
MIR_LRS-SLITLESS | science | n/a | YES
MIR_LRS-SLITLESS | background | BACKGROUND | YES
MIR_MRS | science | n/a | YES
MIR_MRS | background | BACKGROUND | YES
MIR_DARKIMG | dark | n/a | NO
MIR_DARKMRS | dark | n/a | NO
MIR_FLATIMAGE | flat | n/a | NO
MIR_FLATIMAGE-EXT | flat | n/a | NO
MIR_FLATMRS | flat | n/a | NO
MIR_FLATMRS-EXT | flat | n/a | NO
MIR_CORONCAL | science | n/a | YES
 | | | 
NRS_WATA | target_acquisition | n/a | YES
NRS_MSATA | target_acquisition | n/a | YES
NRS_TACONFIRM | target_acquisition | n/a | YES
NRS_CONFIRM | science | n/a | YES
NRS_FIXEDSLIT | science | n/a | YES
NRS_FIXEDSLIT | background | BACKGROUND | YES
NRS_AUTOWAVE | nrs_autowave | n/a | YES
NRS_IFU | science | n/a | YES
NRS_IFU | imprint | IMPRINT | YES
NRS_IFU | background | BACKGROUND | YES
NRS_IMAGE | science | n/a | YES
NRS_MSASPEC | science | n/a | YES
NRS_MSASPEC | imprint | IMPRINT | YES
NRS_AUTOFLAT | nrs_autoflat | n/a | YES
NRS_FOCUS | science | n/a | YES
NRS_DARK | dark | n/a | NO
NRS_LAMP | science | n/a | YES<sup>1</sup>
NRS_BRIGHTOBJ | science | n/a | YES
NRS_MIMF | science | n/a | YES
NRS_VERIFY | science | n/a | YES<sup>1</sup>
 | | | 
NIS_IMAGE | science | n/a | YES
NIS_WFSS | science | n/a | YES
NIS_TACQ | target_acquisition | n/a | YES
NIS_TACONFIRM | target_acquisition | n/a | YES
NIS_SOSS | science | n/a | YES
NIS_AMI | science | n/a | YES
NIS_AMI | psf | PSF | YES
NIS_FOCUS | science | n/a | YES
NIS_DARK | science | n/a | NO
NIS_LAMP | science | n/a | NO
NIS_EXTCAL | science | n/a | NO
 | | | 
FGS_IMAGE | science | n/a | YES
FGS_FOCUS | science | n/a | YES
FGS_SKYFLAT | flat | n/a | NO
FGS_INTFLAT | flat | n/a | NO
FGS_DARK | dark | n/a | NO
FGS_ID-STACK | tracking | n/a | NO
FGS_ID-IMAGE | tracking | n/a | NO
FGS_ACQ1 | tracking | n/a | NO
FGS_ACQ2 | tracking | n/a | NO
FGS_TRACK | tracking | n/a | NO
FGS_FINEGUIDE | tracking | n/a | NO

## Notes
<sup>1</sup> Custom Level2 processing

**Comment by stscieisenhamer** [comment]
# Questions

1. For the specials, BACKGROUND/PSF/IMPRINT, do these exposures also, independently, get processed through Level 2b? Previous discussions on backgrounds imply that they do. What about the others?

2. The NRS AUTOxxx do not. What about the other *calibration* exposures, such as the various DARK/FOCUS/FLAT exposures. Will they go all the way through 2b also?

**Comment by hbushouse** [comment]
The teams (and users) want to have all flavors of target-acq processed up through level-2b as regular images, but the question is where/when should that processing occur? We also have a requirement to list the targ-acq exposures in the ASN file that contains their related science exposures, so if they're going to be listed there, should they also be processed at the same time (that assumes of course they've already gone through level-2a on their own)? Or should they go through level-2b processing on their own, in which case their entries in the ASN file with their associated science exposures is purely for information only and calimage2/calspec2 do absolutely nothing with them when they show up in an ASN with their science exposures?

The decision is likely up to us, because we control how/which exposures show up in an ASN from the pools and also how the calimage2/calspec2 pipelines handle things, and hence we could decide that because we're putting them in the ASN with their science exposures already anyway, we might as well use those entries to also do level-2b processing on them, rather than creating a separate ASN just for the targ-acqs in order to go through level-2b on their own. So in that case they would end up being handled just like background exposures (process them through level-2b at the same time as associated science exposures).

**Comment by hbushouse** [comment]
Darks only receive partial level-2a (level-2aa?) processing via the dedicated calwebb_dark pipeline. Flats only go through the regular complete level-2a (calwebb_sloper) processing; no level-2b. Focus are to be treated like regular images and hence go all the way through level-2b. We've haven't yet received definitive info on how to treat WAVE/AUTOWAVE. I would assume they'd at least get level-2a processing, but not sure about anything beyond that yet.

**Comment by stscieisenhamer** [comment]
With respect to how processing occurs: Currently each exposure is handled as its own product. If an exposure appears as non-science for some other exposure, such as BACKGROUND or TARGET_ACQUISITION, it does not go through 2b processing at that time; these will have their own product, modulo its appearance in the above list.

Referring to the [recently discussed clarification](https://github.com/STScI-JWST/jwst/issues/1168#issuecomment-327824227), one sees that that background exposure is processed as "science", i.e. go through 2b processing, in its own product. The background's 2a form is used as "background" for the first exposure.

The reason for this is the one product == one product philosophy. This helps keep things segregated. Also, logic such as what this issue is discussing does not have to be implemented in the software. Hence, for anything in the above list that should not go through 2b processing, there simply will not be a 2b product for that exposure, regardless of whether the 2a version appears as a support member in another association/product.

Of course, this can be changed if so desired.

About the list: I'll modify as appropriate, and for anything that is unsure, we'll put it through 2b until further notice.

With regard to the "informational listing" of the target acqs and autowaves: This was all in relation to the Level3 associations; I had no plans on doing this mickey-mouse, sorry, informational listing in Level2. Unless one thinks the DMS requirement pertains to both. I recall it was just a Level3 requirement.

**Comment by stscieisenhamer** [comment]
# Question
Do we see any of the FGS exposures?

**Comment by hbushouse** [comment]
So regarding target-acqs in level-2 ASN files, we could potentially take the same approach as we do with background and imprint exposures. Which is to have them appear as members of the level-2b product for the science exposure(s) - they just wouldn't get used at all in creating that product, and at the same time have them appear again in the level-2 ASN file as their own product, which would trigger calimage2/calspec2 into processing them on their own through level-2b calibration. That way we wouldn't have to create separate ASN's containing just the target-acqs in order to get level-2b products for them.

**Comment by stscieisenhamer** [comment]
Except for the `combine_wfs` special pipeline, the two others mentioned currently do no use associations, so there is no need to create or include such exposures in any association?

- calwebb_guider
- calwebb_dark

**Comment by hbushouse** [comment]
Correct. Darks and guiding data will not form associations.

**Comment by nden** [comment]
@hbushouse Si this the table you were talking about today?

**Comment by hbushouse** [comment]
Need to add a caveat for `NRS_MSASPEC` mode: When `MSASTATE` is set to either `ALLOPEN` or `ALLCOSED`, level-2b processing is NOT to be applied. There is no MSA configuration information for these types of exposures and hence level-2b processing can not be applied.

**Comment by nden** [comment]
@hbushouse Should there be a check for this in assign_wcs?

**Comment by hbushouse** [comment]
@nden It couldn't hurt, just in case someone ever tries to pass in an exposure like this to calspec2. Of course it may already be covered indirectly by checks for a non-existent MSA metadata file and/or config ID.

**Comment by stscieisenhamer** [comment]
Just for completeness: Would `ALLOPEN`/`ALLCLOSED` get 2b image processing?

**Comment by stscieisenhamer** [comment]
# Implementation Update
- [ ] Modify 2b/3 associations to not generate associations when `MSASTATE`in [`ALLOPEN`|`ALLCLOSED`]
- [ ] File issue against SDP to include `MSASTATE` in the association pool.

**Comment by stscieisenhamer** [comment]
# Question
According to the keyword dictionary, the possible values of `MSASTATE` are:
- `LAUNCHLOCK_ALLCLOSED`
- `PRIMARYPARK_ALLOPEN`
- `PRIMARYPARK_ALLCLOSED`
- `PRIMARYPARK_CONFIGURED`

First, are these really the values as opposed to the simple values that have been used?

Second, I presume the only case where associations are to be created is `PRIMARYPARK_CONFIGURED`. Also, what is this value if the short-form is actually in use. Is it `CONFIGURED`?

**Comment by hbushouse** [comment]
Regarding level-2b **image** processing (as opposed to cal**spec**2 processing) for `ALLOPEN` and `ALLCLOSED` exposures, that's certainly a possibility. Calimage2 processing would attempt to apply `assign_wcs`, `flatfield`, and `photom`. Not sure what, if any, WCS-related reference data would be of use to `assign_wcs`. And if there happened to be a grating in the optical path (as opposed to just a filter), `flatfield` would not find a reference image to work with. Same for `photom`. So very little might actually succeed even if they were sent through `calwebb_image2`. I will add this question to the one already sent to the instrument team about these exposures.

**Comment by hbushouse** [comment]
NRS_AUTOFLAT: James Muzerolle indicates that the only level-2b steps they would want applied by the baseline pipeline are `assign_wcs` and `extract_2d`. Other special off-line processing then needs to be applied by the team to get the calibration information they need. Given that special processing is needed anyway, it seems to me that we can just not apply any level-2b processing in the automated pipeline and let the instrument scientists do whatever's necessary (e.g. running `calwebb_spec2` with only `assign_wcs` and `extract_2d` turned on).

E-mail from James (5/1/2018):
```
AUTOFLAT is a bit more complicated since it is tied to a separate processing path that is an "optimal" pipeline implementation.  Tim Rawle presented the recommended flow for this to the Cal WG last year; his slides are attached.  A new step will need to be added that divides the intrinsic lamp spectrum from the autocal data.  For now, I suggest doing the following steps for NRS_AUTOFLAT, which do not require new code:
-assign_wcs
-extract_2d

Once you get to the point of being able to tackle optimal content, the lamp spectrum division will need to be included.  The result essentially takes the place of the D- and S-flats normally derived from reference files; it then needs to be multiplied by the F-flat (derived from the relevant reference file) to create the master flat that is divided from the associated science data.  Also note that when an autoflat is used, the bar shadow correction should be turned off for the science data processing since the shadow has not been removed from the autoflat (whereas it has been removed from the S-flat reference file).  See the slides for more details, but let us know if anything is unclear.
```

**Comment by nden** [comment]
@hbushouse Currently autoflat is turned off in assign_wcs and extract_2d. How should it be processed in assign_wcs? Is `NRS_AUTOFLAT` sufficient to determine which mode of assign_wcs to run or is it necessary to have additional info? What I mean is could we get exposures for IFU, FS and MSA, all having EXP_TYPE=NRS_AUTOFLAT?

**Comment by hbushouse** [comment]
James agrees that restricting AUTOFLAT to just level-2a processing is OK for now. Once we do want to activate a few steps of level-2b processing, including assign_wcs and extract_2d, they are to be processed as MOS (MSA) mode exposures. They will always be obtained along with a regular science exposure and will use the same MSA configuration as the associated science exposure. So there will be MSA meta data available to process them as MOS mode.

**Comment by stscieisenhamer** [comment]
Both the MSASTATE and NRS_AUTOFLAT issues are being tracked separately. The following conditions are true as of this comment:
- The table represents the desired state
- The rules implement the table
As such, this issue is closed until the next table update.

**Comment by stscieisenhamer** [comment]
Re-opening to satisfy a new requirement #2174 from #1782. `NRS_LAMP` now gets processing.

**Comment by hbushouse** [comment]
Edited the summary table at the top for the following recent changes to allowed EXP_TYPEs:

1. Replace MIR_DARK with MIR_DARKIMG and MIR_DARKMRS
2. Add MIR_FLATIMAGE-EXT and MIR_FLATMRS-EXT
3. Remove NRS_TASLIT, NRS_TACQ, and NRS_BOTA and replace with NRS_WATA and NRS_MSATA

**Comment by hbushouse** [comment]
Updated the summary table above to indicate that (as of DMS B7.6) NRS_AUTOWAVE and NRS_AUTOFLAT exposures do receive (custom) level-2b processing.

**Comment by stscieisenhamer** [comment]
Updated to include NRS_VERIFY.

**Comment by stscieisenhamer** [comment]
The content of this issue has now moved permanently into the JWST documentation via PR #5496
