### ISSUE TITLE
silence asdf warnings

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#1215]
ASDF introduced two new flags with defaults:
`ignore_version_mismatch=True, ignore_unrecognized_tag=False`. 
These flags should be added to calls to `AsdfFile` to provide more flexible control over warnings coming from, e.g., reference files.

**Comment by bernie-simon** [comment]
@nden has a good point. I will also need to modify from_asdf to take the new aguments. After that works, the change can be merged.
