### ISSUE TITLE
Fix file naming in outlier_detection

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1223]
Currently in `outlier_detection`, the writing out of intermediate files is handled by subroutines or subroutines of subroutines.  Ideally, this should happen in the `OutlierDetectionStep.process` method at the top level and be done using the standard `Step.save_model` methods.

This will require a significant refactor of where most of the logic of the step happens.  Currently it happens in the `OutlierDetection` class, but it really should be happening in the `OutlierDetectionStep` class.

**Comment by melanieclarke** [comment]
Closing - this ticket is overtaken by events.
