### ISSUE TITLE
Remove the schema from ModelContainer

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1251]
`ModelContainer` currently has schema entries that correspond to some items found in Level 3 association tables.  These should be removed, and any code that relies on them should switch to using the `ModelContainer.asn_table` attribute to gather this information.

**Comment by jdavies-st** [comment]
After discussion with @nden today, it's clear that `ModelContainer` should not have a schema, as it does not correspond to a FITS file and thus does not need the schema mapping for serialization.  As long as its members have schemas, the members can be serialized each to its own file.

Updating this issue to remove the schema completely.  Any metadata that `ModelContainer` needs to carry along with it can be stored in instance attributes or properties.

**Comment by nden** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2040](https://jira.stsci.edu/browse/JP-2040)._
