### ISSUE TITLE
update core schema to reference individual schemas

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#1273]

**Comment by melanieclarke** [comment]
@emolter - do you know if there is still work that needs to be done to refactor the core schema? If so, this ticket should be moved to stdatamodels.  If not, we should close it.

**Comment by nden** [comment]
This was created a long time ago and was meant to update the core schema to point to individual `keyword_*` schemas, to avoid updates in two places. I'm OK with closing it as it seems everyone is used to the current state.

**Comment by melanieclarke** [comment]
Okay, thanks @nden.  I will close.
