### ISSUE TITLE
sphinx_automodapi and rtd theme need to be requirements

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1276]
To build the docs, the following need be added to the package dependencies:
- sphinx
- sphinx_automodapi
- sphinx_rtd_theme

**Comment by stscicrawford** [comment]
Linking to #2453 and #1508

**Comment by stscieisenhamer** [comment]
This has been resolved by use of the command `python setup.py build_sphinx`. Documentation on how to build docs manually need be written, but there is no need to add as requirements.
