### ISSUE TITLE
warning: invalid value encountered in gwcs.selector.py

### ISSUE THREAD

**Issue by baileyji** [spacetelescope/jwst#1302]
```
2017-10-12 10:22:48,280 - stpipe.MRSCubePipeline.cube_build - WARNING - /Users/one/anaconda2/envs/jwst/lib/python2.7/site-packages/gwcs/selector.py:433: RuntimeWarning: invalid value encountered in less_equal
  temp = np.where(np.logical_or(temp <= val_range[0],

2017-10-12 10:22:48,281 - stpipe.MRSCubePipeline.cube_build - WARNING - /Users/one/anaconda2/envs/jwst/lib/python2.7/site-packages/gwcs/selector.py:434: RuntimeWarning: invalid value encountered in greater_equal
  temp >= val_range[1]),
```

**Comment by jdavies-st** [comment]
It would be good to have the full traceback and the dataset name that is being processed in order to troubleshoot this.

**Comment by baileyji** [comment]
How should I configure the pipeline do generate and save debugging info for you?

**Comment by jdavies-st** [comment]
Just the full traceback would be useful.  It looks like you just clipped the last two above.  Also, it would be good to know what file was being run on `cube_build` and how it was called, i.e. and the code and data that generated this error.

**Comment by baileyji** [comment]
There was no traceback because the pipeline didn't crash. I'm getting this when running reduction of MIRI MRS data using a meta pipeline that just follows the official steps to get from lvl1 to lvl3. The dataset is quite large so I'll need to spend some time working on that.

**Comment by nden** [comment]
I don't think this is a problem in this case. Some of the values are NaNs because, for example,  the pixels are between slices, or outside the valid wavelength range. The warning is raised because of the logical operation when the input is NaN. I will have to redo this part of the code or silence the warning but I think it's benign.
