### ISSUE TITLE
Remove extra_fits as a public property

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1308]
Datamodels has the private property `_extra_fits` which stores the FITS keywords that are not in the datamodel schema, but it also has an `extra_fits` property which is public.  One is a copy of the other it seems.
```
In [3]: model.extra_fits
Out[3]: <jwst.datamodels.properties.ObjectNode at 0x10c3d6710>

In [4]: model._extra_fits
Out[4]: <jwst.datamodels.properties.ObjectNode at 0x10c32dd68>

In [7]: model.extra_fits == model._extra_fits
Out[7]: True

In [8]: model.extra_fits is model._extra_fits
Out[8]: False
```
It would be good to remove the public one, i.e. `model.extra_fits`, as it probably should not be part of the public interface for datamodels.

Thoughts?

**Comment by jdavies-st** [comment]
From what I can tell, the `_load_extra_fits` [method](https://github.com/STScI-JWST/jwst/blob/master/jwst/datamodels/fits_support.py#L559) takes FITS keywords not found in the schema and dumps them into the `extra_fits` part of the tree.  Then `model_base.py` defines a [property](https://github.com/STScI-JWST/jwst/blob/master/jwst/datamodels/model_base.py#L757) `_extra_fits` that returns the former.

So it is backwards to what I thought.  Anyway, I suspect that `_extra_fits` should be like `_instance` and `_schema`, i.e. private properties that are not part of the public interface.

**Comment by philhodge** [comment]
I don't see the point of trying to hide `extra_fits`.  The info is plainly visible in the FITS file (fortunately).  But as long as the step code can easily access `extra_fits` (for reading and writing), I don't really care whether you call it hidden or not.

**Comment by hbushouse** [comment]
I'm also not sure I see the point of hiding it. The reason it was put in there in the first place was to accommodate FITS files from the instrument teams - either from ground test or simulated - that might have extra keywords in them that are not used/useful to the DMS pipelines, but are useful to the original "owners" and hence we don't want them disappearing when loaded into a data model. Those owners may also want to access them, which I guess can be done via either a public or non-public attribute, but I'm not sure it needs to be non-public.

**Comment by jdavies-st** [comment]
Ok, then maybe we just need to decide whether it should be public or non-public.  Right now, it is both, and the example in the documentation shows accessing the non-public `_extra_fits` property.

**Comment by hbushouse** [comment]
Has anyone looked to see how many instances we have within the entire jwst package of either form of this actually being used (i.e. NOT in the datamodel modules where it's defined and handled)? Is there a tendency, for example, for it to be used most often in the private or public form? I still don't see the harm in keeping the public version available. The documentation is still correct, in that you can access the private version if you want to.

**Comment by bernie-simon** [comment]
I've looked and no code outside of datamodels is using extra_fits except for three tests in crds which use _extra_fits. I'm going to remove extra_fits. It's not supposed to be public (I say) and is best not accessed by code outside datamodels.

**Comment by philhodge** [comment]
Just because it isn't currently used doesn't mean it never should be.  I think it should be public.

**Comment by bernie-simon** [comment]
Okay, we can discuss this at the Monday meeting if there's time. Maybe take a vote.
