### ISSUE TITLE
Make wcs bounding_box edges consistent across JWST detectors

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1319]
The `gwcs.WCS` attribute `bounding_box` defines the rectangular region on each detector within which the WCS transform can be valid.  The WCS for a particular pixel is the mapping of the center of the pixel to world coordinates.  So if I want the WCS of the pixel `[0, 0]`, it is going to return to me the world coordinates of the center of the pixel.

If I were to define a bounding box just for that pixel, it would be `[[-0.5, 0.5], [-0.5, 0.5]]`.

At the moment, NIRCam imaging uses this convention, but NIRSpec and some other instruments do not.  They use the `[[0, 1], [0, 1]]` convention.

1. Is the former convention the one we want to use?  I think so.
2. We should check through all our bounding box computations and make sure we are computing them consistently.

**Comment by nden** [comment]
This has been resolved in various PRs.
