### ISSUE TITLE
redo grism transform models to make method to lookup the polynomial

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#1330]
The current model transforms for the grism modes use a tuple lookup based on the input order that the user specified. This makes it unpleasant for array inputs. I can get around it with list comprehensions, but the better solution for  7.1 is to continue letting extract1D  use a loop to access multiple pixels. I'll rework the models to add a model_lookup method that will take the order at hand and return the model that will do the correct calculation instead.  I'll add this to the next delivery, and leave the looping in place with single value model inputs for now.

**Comment by sosey** [comment]
@nden we had decided to table this thinking the gwcs update would allow us to carry multiple models IIRC

**Comment by sosey** [comment]
@philhodge I think you were also asking about this recently?

the transform/models for grism need to take in the order for the calculation, this is an integer value that is used to look up the polynomial to use for the rest of the calculations. When users put arrays into the model, modeling converts them to ndarray floats and also expects all inputs to be the same length for broadcasting. This breaks the tuple lookup for the model.  you  were getting around this for extract1D by making a loop to access the model in the wcs. Nadia suggests that I can change it to be more like nirspec, where we add a model_lookup method that will take the order at hand and return the model that will do the correct calculation.  I'll add this to the next delivery, and leave the looping in place with single inputs for now. See  class Gwa2Slit(Model):  in transforms/models and the nirspec/nrs_wcs_set_input in assign_wcs for the example

**Comment by philhodge** [comment]
Thanks, @sosey !

**Comment by nden** [comment]
Transforms now work with array inputs.
