### ISSUE TITLE
Update ASN processing workflow for WFSS in documentation

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#1344]
Not urgent, just noting the documentation here has fallen out of date, it just needs to be updated to reflect the fact that we no longer take the segment image into the WFSS, the source_catalog step generates the bounding box information that we need and we can just read it from the catalog.

see https://github.com/STScI-JWST/jwst/issues/739

**Comment by stscieisenhamer** [comment]
Just to be clear: The fix is to replace the phrase "Catalogs & Source Images" with just the phrase "Catalog"?

**Comment by sosey** [comment]
about that, I included the test updates in this ticket: https://github.com/spacetelescope/jwst/pull/2538, we just need to update the image so that it no longer shows the sementation image being passed with the association

**Comment by sosey** [comment]
fixed in #2534
