### ISSUE TITLE
Cube_Build tasks for Build 7.1.3 and 7.2 

### ISSUE THREAD

**Issue by jemorrison** [spacetelescope/jwst#1350]
Below are the remaining tasks cube_build needs for processing MIRI and NIRSPEC data for build 7.2.
Some of these topics have been pulled out of #614.
- [x] Build 7.1.3: The model blender routines needs to work with IFUCubes. This involves two steps:
- [x]  1. Review blend_rules for all IFU cube header parameters that need to be in final IFU header and update if needed. 
- [x] 2. call the model blender with the input being input images and output being IFUcube model 
 FINISHED  for Build 7.1.3 #1955 
- [x] Build 7.2:Add the option to create a non-linear wavelength dimension. This involves two steps:
   [ X]  1. Create a wavelength reference table that would be the default wavelength sampling to use to build cubes when more than 1 band or 1 file (dithered data) is used to construct the IFUCube. This could be an extension table to the existing cubepars reference files.  One table would be needed for each instrument (MIRI and NIRSPEC) covering the entire wavelength range of the instrument. Whenever more than 1 band is used to create an IFUCube then this table would be used. #1817 
 [ X] 2. The wavelength axis of the IFUCube needs to be able to the have a non-linear sampling. This could be in the form of wavetable which requires an update to gwcs. - this has been moved to #2235 

- [ ] Build 7.3: Besides the default ROI size provided in the cubepars reference file we might want to be able to adapt the rio size when building the cube based on a cloud density of points. 

- [x] Build 7.2: Add a set of definitions for the DQ flags of an IFUCube and implement these rules when building a cube.  We could use this information to provide  diagnostic information  about holes that exist in the IFUcube (we are not interested in holes at the edges of the IFUCube, but holes inside a valid region of the IFUCube) 
- [x] Build 7.3: A feature that the MIRI instrument team would like is create IFUCubes in the alpha-beta coordinate system from dithered data. 
-[ ] Build 7.2 NIRSPEC would like to be able to build alpha-beta type cubes.

**Comment by astroolivine** [comment]
I wrote Python code that identifies holes in cubes (ignoring holes on the edges of the cube but identifying holes within where the IFU observes).  It sounds like the code needs to be part of cube_build rather than a separate pipeline step.

**Comment by jemorrison** [comment]
Ben send me the code and I will see how to incorporate it into cube_build.

**Comment by hbushouse** [comment]
@jemorrison can you confirm whether all of the items listed above have been completed for `cube_build` or are no longer needed?

**Comment by jemorrison** [comment]
@drlaw1558 This list of cube_build tasks were put together a while ago. I think we have implemented about all of them. We don't change the size of the roi based on the density of the cloud points. Do you think this is something we might want. If so I will file a single ticket it for it and close this one. If you don't think we want to do that, I will just close this ticket

**Comment by drlaw1558** [comment]
@jemorrison I agree the above look taken care of.  We may want to revisit the issue of roi size based on density in the future, so please do file a ticket for it just to keep it on our radar.  We can deprioritize the ticket though and punt it to potential future development pending more details.

**Comment by jemorrison** [comment]
Closing ticket. Openning JP-1997 ticket to track future enhancement of cube_build to adapt roi size based on density of point cloud elements.
