### ISSUE TITLE
Update MIRI last frame correction 

### ISSUE THREAD

**Issue by jemorrison** [spacetelescope/jwst#1361]
The last frame correction algorithm supplied by the MIRI team (Mike Ressler) needs to be folded into the pipeline

**Comment by jemorrison** [comment]
@melanieclarke The MIRI team at STScI has been working on a correction rather than just dropping the last frame.
This has taken a back seat to other issues. Let me check with the team and see if they plan on continuing with this or if it is on hold indefinitely

**Comment by melanieclarke** [comment]
Okay, thanks.  If they don't plan to address this, we can just close this ticket.  If they might eventually want it, we should track this in a JIRA ticket.

**Comment by mengesser** [comment]
Hi all - we recently got some data to finally try and correct this properly, but there is still a lot of work between us and a pipeline step update. I recommend closing this for now and we will open a new one when we are ready.

**Comment by melanieclarke** [comment]
Great, thanks for following up.  I will close this issue now.
