### ISSUE TITLE
Fix Sphinx build warnings

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#1382]
I couldn't get Travis to fail when Sphinx build warnings are detected in #1377 without basically porting over part of `astropy-helpers`, which I don't want to do. However, in that process, I see hundreds of warnings when documentation is built.  These warnings should be fixed.

**Comment by stscieisenhamer** [comment]
Related:
- #1344 
- #1276 
- #168

**Comment by hbushouse** [comment]
Do all of the steps/packages referenced in the issues listed in the comment by @stscieisenhamer cause Sphinx build warnings, or are they just generic issues related to doing something with documentation?

**Comment by pllim** [comment]
I would say https://github.com/STScI-JWST/jwst/issues/1382#issuecomment-339811361 is a subset of the bigger problem.

**Comment by hbushouse** [comment]
Fixed by #3048.
