### ISSUE TITLE
Minor fits_generator issues

### ISSUE THREAD

**Issue by stscirij** [spacetelescope/jwst#1387]
When the subarray parameters of the input file don't match those of known subarrays (specified in a dictionary in create_dms_data.py), the name 'UNKNOWN' is used for the SUBARRAY keyword.  This is not a valid subarray name, change it to 'GENERIC' which is.

Also if the GWA_TTIL keyword in the raw data isn't a float, we should force it to make a float GWA_TILT keyword.

If the proposal file prefix is not 5 characters, the code can fail.  Force the proposal number (usually the part of the proposal file before .prop) to either truncate or pad to exactly 5 characters.

**Comment by melanieclarke** [comment]
Closing, since the fits_generator is no longer used.
