### ISSUE TITLE
Possible MIRI/MRS world 2 detector bug.  

### ISSUE THREAD

**Issue by baileyji** [spacetelescope/jwst#1406]
Hi Folks, 
   I'm seeing very unexpected behavior in the world to detector transform as captured in this gist (note you will need to contact me for the supporting fits files). 

The short of it is that computing a set of x,y pixel coordinates from a mesh of ra, dec, and lambda yields regions on the detector that are outside (If I'm using the code properly) of the slices on on the detector.

<img width="500" alt="screen shot 2017-11-01 at 6 01 51 pm" src="https://user-images.githubusercontent.com/579941/32286739-c7857afc-bf2e-11e7-84c9-4cc9c4a0e869.png">

https://gist.github.com/baileyji/1a1c4762bbc303f9f0a3a10503a5da64

**Comment by nden** [comment]
After offline discussions, I think there's no bug. The reason for seeing values between slices is that the regions mask is not applied to output values of the inverse transform. I'm closing this but two new issues cam out of the discussions - #1427 and #1428

**Comment by nden** [comment]
After much back and forth I think I understand the issue now.
When going from alpha, beta to detector, the beta value alone is used to determine which slice the (alpha, beta) value belongs to. Instead, it is necessary to also look at the range of alpha values for each slice.
Here's an example for a 12SHORT exposure:

alpha, beta = ( 3.19529725,  2.0776295)

Based on beta only this point belongs to slice  216. However, the alpha range for slice 216 is  
(-2.17462231,  2.13811708). Based on the alpha value this point should have a value of NaN on the detector, while now it goes through the "alpha_beta to detector" transform and has a real value on the detector. Looking at the pixel location on the detector and using the forward transform, it actually belongs to slice 207 (another indication it's wrong).

**Comment by hbushouse** [comment]
Can this be retested to see if it's still a problem in B7.8?

**Comment by melanieclarke** [comment]
@nden @drlaw1558 - do you know if there is still an issue with MIRI MRS WCS world to detector transforms?  If so, this should be tracked in a JIRA ticket.

**Comment by drlaw1558** [comment]
I'm not currently aware of any other reports of this issue in the last few years, so I'd chalk it up to problems with the early pre-flight reference files.
