### ISSUE TITLE
test MRS inverse transforms

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#1428]
Devise a test which confirms that there's no mix-up of slice transforms when going from `alpha_beta` to `detector` and using arbitrary values of alpha, beta, lambda.
note, there's no evidence now that there's a problem, this is a testing issue.
This is a result of offline discussions on #1406 .

**Comment by hbushouse** [comment]
@nden does this still need testing?

**Comment by melanieclarke** [comment]
Closing, since triggering ticket #1406 is closed.  Please file a new ticket if there are remaining issues.
