### ISSUE TITLE
NIRCam distortion reffile doesn't roundtrip well away from CRPIX

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1444]
The distortion reference files for NIRCam were built from the 2D polynomials from the NIRCam SIAF.  The forward and backward transforms
```
detector --> v2,v3
detector <-- v2,v3
```
do not round trip correctly far away from CRPIX.  This is a known issue according to the Telescope branch and NIRCam team.  But there might be a way to fix this?

I'm starting the issue here, because if there's a way to fix it, perhaps it might be good to include this fix in a new batch of distortion reference files for the instrument at some point.

An example below for the A chips:
```
In [14]: files = glob('*dither1*_cal.fits')

In [15]: files
Out[15]: 
['nrca1_47Tuc_subpix_dither1_newpos_cal.fits',
 'nrca2_47Tuc_subpix_dither1_newpos_cal.fits',
 'nrca3_47Tuc_subpix_dither1_newpos_cal.fits',
 'nrca4_47Tuc_subpix_dither1_newpos_cal.fits',
 'nrca5_47Tuc_subpix_dither1_newpos_cal.fits']

In [20]: for file in files:
    ...:     dm = datamodels.open(file)
    ...:     crpix1 = dm.meta.wcsinfo.crpix1 - 1
    ...:     crpix2 = dm.meta.wcsinfo.crpix2 - 1
    ...:     x, y = crpix1, crpix2
    ...:     print((x, y), dm.meta.wcs.backward_transform(*dm.meta.wcs(x, y)))
    ...:     x, y = crpix1 - 500, crpix2 - 500
    ...:     print((x, y), dm.meta.wcs.backward_transform(*dm.meta.wcs(x, y)))
    ...:     x, y = crpix1 - 1000, crpix2 - 1000
    ...:     print((x, y), dm.meta.wcs.backward_transform(*dm.meta.wcs(x, y)))
    ...:     
(1023.5, 1023.5) (1023.5000000000348, 1023.499999999678)
(523.5, 523.5) (532.0062690220968, 520.0917146281871)
(23.5, 23.5) (43.416651987077216, 18.26893061809426)

(1023.5, 1023.5) (1023.5000000000612, 1023.5000000000962)
(523.5, 523.5) (526.846517709356, 521.8242131194439)
(23.5, 23.5) (31.605935390088007, 20.58347013872958)

(1023.5, 1023.5) (1023.4999999999905, 1023.5000000001589)
(523.5, 523.5) (522.0975510287103, 525.3400048302237)
(23.5, 23.5) (21.225630634117692, 27.61411192828575)

(1023.5, 1023.5) (1023.49999999998, 1023.5000000000387)
(523.5, 523.5) (523.040387163534, 524.019307198773)
(23.5, 23.5) (22.64775597877542, 24.51776232646671)

(1023.5, 1023.5) (1023.5000000000243, 1023.4999999997642)
(523.5, 523.5) (525.113884369709, 523.0627544900891)
(23.5, 23.5) (29.720105748682272, 24.379739502087432)
```
Tagging @bhilbert4 here as he's aware of this and might have a workaround?

**Comment by bhilbert4** [comment]
Here is the code I use to perform an exact inverse transform. I left the paths to the distortion reference file and SIAF blank before uploading. You can fill those in with your favorite copies. Right now the aperture is set to detector A1. In my tests, the difference between the initial pixel location and the round tripped pixel location is insignificant (0.000000000001 pixels)
[coord_transforms.py.txt](https://github.com/STScI-JWST/jwst/files/1459244/coord_transforms.py.txt)

**Comment by jdavies-st** [comment]
Indeed Mihai!

It looks like Bryan's method (from Colin) is to use Newton's method to fit a polynomial to the deltas.  Once fit, it seems like it could be just another polynomial in the GWCS object.

A further complication is that in the SIAF, the reference point around which the polynomials are symmetric are generally at the center of the aperture.  But the distortion is actually quite asymmetric on all the JWST detectors, so the SIAF aperture reference point (CRPIX) is perhaps not the best location to use for a reference point for a polynomial distortion model

MIRI gets around this by using their own reference pixel location for the distortion model.

**Comment by mcara** [comment]
@jdavies-st 
> It looks like Bryan's method (from Colin) is to use Newton's method to fit a polynomial to the deltas. Once fit, it seems like it could be just another polynomial in the GWCS object.

Newton method is a root-finding method. Essentially @bhilbert4 is solving the equation `y=p(x)`: find `x` ("root") such that `y==p(x)` for a *given* value of `y`. This method does not approximate deltas with polynomials. If it were, then @bhilbert4 wouldn't be any better than the original polynomial approach (unless it were to use higher degree polynomials).

**Comment by bernie-simon** [comment]
Numpy has a polynomial least squares fitting function, numpy.polyfit.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.polyfit.html

**Comment by nden** [comment]
While debugging a problem reported by an user I found that this is still an issue. NIRCAM reference files do not roundtrip and anything using the inverse WCS transform (like resample or grism) will not work. This is strictly a reference file problem, not an issue with the pipeline.

**Comment by mcara** [comment]
@nden Does this mean that inverse `WCS` transformation is not computed numerically and that instead it uses some transformations from the reference file? If that is the case, is there any hope to get better reference files?

**Comment by sosey** [comment]
Yup, I spent yesterday working up a notebook with the full examples comparing the pipeline, distortion reference file, and Bryan/Colins SIAF scripts to make sure I understood what was going on for nircam.  The nircam wfss simulation images were created using the translation from the secondary method (not included in the distortion model that's been delivered to CRDS) and hence and pixel locations I compute coming through the distortion (which enables me to calculate the starting point for the WFSS bounding boxes for grism exctraction) will be incorrect until the distortion reference file is updated.

**Comment by mcara** [comment]
🚀 🎆

**Comment by jdavies-st** [comment]
I guess this is a nice "feature" of the forward and inverse transforms taken from the SIAFs last year when the reffiles were delivered.  As you can see above, they do round-trip, but they're off by up to 20 pixels near the edge of the detector.

Has there been any movement on the part of the Telescopes branch in making more accurate SIAF files available that have higher order polynomials?  Bryan's code for generating new distortion reference files 

https://github.com/spacetelescope/jwreftools/tree/master/jwreftools/nircam

could easily be modified and run to generate new distortion reference files I suspect.

**Comment by mcara** [comment]
Only `0013` and `0023`` are "good enough", IMO. `0004` is particularly "interesting".

**Comment by sosey** [comment]
0004 can be ignored (anything before 0011 can actually according to the rmap)

**Comment by stscicrawford** [comment]
Please open a ticket in the CRDS Jira project especially if you need input from other groups to request these reference files.

**Comment by sosey** [comment]
I'm working on one, just need to get my examples finished...

**Comment by sosey** [comment]
For completeness, the other ticket referencing this: https://jira.stsci.edu/browse/JP-304

**Comment by stscicrawford** [comment]
@sosey Can you update this ticket?  Has this been addressed with the delivery of new reference files?

**Comment by bhilbert4** [comment]
The new SIAF coefficients are not yet in the PRD, so updated reference files have not been created yet.

**Comment by sosey** [comment]
It's up to the science team to deliver the new distortion reference files, these are seperate from the wavelengthrange and specwcs files that I delivered (though the team now should be in charge of updating them). however, I put in a test for wfss that checks the distortion roundtrip, it's currently set to xfail for nircam, when the new one gets delivered and the crds context is updated it should pass ;) https://github.com/spacetelescope/jwst/blob/master/jwst/assign_wcs/tests/test_nircam.py#L190

**Comment by jdavies-st** [comment]
This was fixed in

https://jira.stsci.edu/browse/RFD-296

and the resulting rmap

https://jwst-crds.stsci.edu/browse/jwst_nircam_distortion_0022.rmap

became operational on 1 Nov 2019.

Closing.
