### ISSUE TITLE
The persistence step needs the flags set by the jump step

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#1477]
Currently, the jump step follows the persistence step.  The persistence step needs the locations of the jumps, however.  We need to find some way to get the information about jumps when computing the persistence.

**Comment by hbushouse** [comment]
Could the order of the steps just be reversed? Not sure how having the persistence signal still contained in the data when input to the jump step would affect its algorithms. It could potentially make the ramps look non-linear, which then makes the jump detection difficult.

**Comment by melanieclarke** [comment]
@drlaw1558 - do you know if there is any current interest in changing how jump and persistence steps interact?

**Comment by drlaw1558** [comment]
Not something we've particularly considered; I'd be inclined to close this ticket and if it's something that seems necessary in future we can track via JP.
