### ISSUE TITLE
Spectral contamination information for WFSS pipelines

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#1487]
The algorithms for WFSS processing page describes the need for a contamination model applied to each spectral object that is extracted. Specifically it states: 

 Each sub-window must have:
- sufficient WCS information to enable cube building.
- A contamination model.  Store it in a separate extension of the output file.

**Contamination model:  aXe offers three contamination models:**

1.  The first merely flags pixels that are contaminated by the spectra of other objects.  It uses the the shape information for each object (A_IMAGE, B_IMAGE, THETA_IMAGE) to estimate where flux will fall in each spectral order.  The output is an image with the same dimensions as the sub-window.  Pixel values are set to the number of objects whose spectra contaminate that pixel.  **We will use this scheme for the _Vanilla Pipeline._**

2.  The second estimates the degree of contamination using the shape information for each object (A_IMAGE, B_IMAGE, THETA_IMAGE) and magnitudes taken from the source catalog.

3.  The third estimates the degree of contamination using the flux cube model.  **We will use this scheme for the _Optimal Pipeline._**

---
Q: is the contamination extension for each object added to the level2 or level3 processing products?  I think cube creation is part of the level3 pipeline

Q: The page mentions possibly saving two contamination images one that includes the source object and one that just includes the  contaminating objects. Which is preferred?

Q: We can construct a contamination image using the catalog for the entire grism image, then make cutouts from this around each object. Is there value in saving the large image as well as the extracted images around each source?

Q: For 1 and 2, assuming the bounding boxes we've created already will suffice for defining the contamination areas?

Q: I'd like to discuss more thoroughly with someone what additional contamination estimates are done in case 3. Does this relate to the fraction of the total observed flux that is due to contamination as a function of location and wavelength?

**Comment by sosey** [comment]
@npirzkal @gbrammer :8ball:

**Comment by npirzkal** [comment]
I think neither of the approcahes from aXe are really good. It would make more sense to use the footprint of the objects produced by the photutil step to compute realistic models/contaminations. This is something that has been done by most people extracting data lately.
Contamination needs to be computed for each observation, i.e. Stage 2. This is because contamination can vary between two dithered observations as some sources drop off the pick up mirror. Also, these proper simulated images would then be useful to perform weighted extraction ad well as computing the proper sensitivity for each source. This is explained in the last FIGS paper, http://adsabs.harvard.edu/abs/2017ApJ...846...84P

**Comment by sosey** [comment]
Right, so the bounding boxes that we have now are made from the footprints of the objects produced by the photutil step. My thought was that we could define contamination in the areas of overlap in these bounding boxes.

what form should that take in the actual extension - a flagged image that details which objects are contaminating the pixels for the source or some other measure?

**Comment by npirzkal** [comment]
That is one way to go but this is more “qualitative” than “quantitative” contamination. It will give some ideas of whether contamination is possible but will not allow to estimate how important it is.

**Comment by gbrammer** [comment]
I think a quantitative image based on the direct image thumbnail and an assumed/derived source spectrum is useful and feasible.  That's what grizli and I think also FIGS do.

**Comment by sosey** [comment]
This is an effort to summarize what @gbrammer  and I discussed yesterday for implementing the contamination estimate for each observation, to make sure I understand what should be implemented and that we all agree on at least a subset of how :smiley: 

@npirzkal will you comment on whether you think this will work for NIRCAM as well, or if the method should be different for each instrument or a modification that would work for both teams?  Checkmark the items that everyone agrees on?

- [ ] We will add a contamination extension (CONTAM - name?) to the extract2D products, each object will have an estimate for contamination by other sources and this will be a 2D extension. 

- [ ] Calculating/creating the contamination rather feels like a separate step to me, @hbushouse can we make it a separate step in actuality? We'll also need to update the datamodels for the new extension.

- [ ] Add code that determines which objects are contaminating for the main source using the  bounding boxes of the spectra as a first cut.

- [ ] Using the measured flux from the direct image, convolved with the throughput for the filter that was used as part of the grism observation, create a model spectrum for each pixel in the direct image that falls in the same space as the 2D cutout for the object in the grism image. 

   - [ ] The filter transmission at each wavelength allows the flux estimate for the model trace
   - [ ] Don't include the source object in the contamination extension
   - **Question**: Should we add another extension that *only* has the flux model for the source object, this can be used in conjunction with the CONTAM image to estimate the contamination for the source object
   - **Question**: if the direct image is actually some optimal combination from multiple observations in multiple filters, is there some other scaling of the flux from the direct image that should be done before the model is made?

**Comment by npirzkal** [comment]
Yes, this closely follows what has been done with ACS and WFC3 observations.
One extension could contain the contamination from other sources. Another extension could contain the model of the source. This is needed to perform   more complicated 2D to 1D conversion as well as to properly flux calibrate extended sources observed at different PAs.

**Comment by hbushouse** [comment]
Everything related to WFSS contamination correction is now being tracked by [JP-897](https://jira.stsci.edu/browse/JP-897) and associated child tickets, so I'm closing this one.
