### ISSUE TITLE
prevent merging PRs if tests fail

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#1504]
I suggest configuring github to prevent merging PRs into master unless Travis tests pass.
The reason is we sometimes overlook the test results and then loose more time checking why every PR failed. Also the code is so complex by now that a small change (especially in datamodels or stpipe) can have unexpected consequences.
@STScI-JWST/maintainers Any opinions on this?

**Comment by nden** [comment]
I know sometimes Travis can be a problem but in these cases we can uncheck the option and merge any way. At least it'd be a conscious decision.

**Comment by stscieisenhamer** [comment]
Some suggestions on process (presuming we have standardized on `pytest`):
- In general, only merge when the test failure is a Travis/CI issue AND one has run the test suite locally successfully. Make sure a comment to this effect is added to the PR.
- If a test (or two) is failing, but a merge is required, do the following:
    - Create an issue about the failing test(s)
    - Mark the test as expected-to-fail with
    ```
    @pytest.mark.xfail(
        reason='Such and such is broke. See issue #XXXX',
        run=False
    )
    ```
- Presuming `pytest` is the test runner, add the option `-rsx` to the runner command. This will explicitly print out the `xfail` and `skip` reasons for all marked tests.

**Comment by philhodge** [comment]
I submitted a PR, and Travis does not seem to be running.  It's checked in my settings under Integrations & services.  Has it been disabled?

**Comment by nden** [comment]
not relevant any more
