### ISSUE TITLE
Task: Verify level-2b and level-3 ASN creation for WFS&C exposures

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#1614]
Processing of WaveFront Sensing & Control (WFS&C) exposures is critical for commissioning. We must therefore be able to construct level-2b ASN's of all WFS&C exposures so that they can be run through the calwebb_image2 pipeline, and we must construct level-3 ASN's of all dither pairs of WFS&C exposures, so that they can be processed with wfs_combine.

Using OTB test data generated in early 2018 we must test the ability of the asn_generator rules to create the necessary ASN's and make any updates as necessary.

**Comment by stscicrawford** [comment]
Closing issue
