### ISSUE TITLE
Quaternion handling with incomplete quaternion data

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1658]
# Issue
Better handling of quaternion calculation when some/all of the quaternion information is not with the exposure period.

# Resources
- [DR #4622](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/dr.4622)

**Comment by stscieisenhamer** [comment]
As per the DR, current approach is to ensure that the engineering db is self-consistent. Until the DR itself is resolved, no code changes are desired.

**Comment by stscieisenhamer** [comment]
Closing this because, as per the DR, this is not `set_telescope_pointing` responsibility.

**Comment by stscieisenhamer** [comment]
Though not responsibility, the error situation needs to be handled more gracefully.  In particular, 
https://github.com/spacetelescope/jwst/blob/200642764bff554b0f5f06234bed47a980d52e67/jwst/lib/set_telescope_pointing.py#L947-L950 
should be in a `try` block, with the exception being reported, break out of the loop, and continue.

**Comment by hbushouse** [comment]
@stscirij I'm guessing this was fixed as a by-product of #5540. Can you confirm?

**Comment by stscirij** [comment]
> @stscirij I'm guessing this was fixed as a by-product of #5540. Can you confirm?

I believe so, although the link to the original issue in the PR system is now stale so it's hard to tell what the exact issue raised was

**Comment by hbushouse** [comment]
The part of the code referenced above doesn't even exist anymore and is now part of larger sections that check for zero-valued entries and raise an error when found. So I'm going to assume this has been handled and if anything bad shows up in the future, a new ticket can be created. Closing.
