### ISSUE TITLE
MIRI FirstFrame and LastFrame minimum number of groups

### ISSUE THREAD

**Issue by karllark** [spacetelescope/jwst#1681]
Currently the first and last frame steps only flag groups if there are at least 2 groups.  Now that we have both corrections, this can result in both groups in a 2 group integration being flagged as bad.  This is not what should happen.

The best solution would be to reorder the steps to have the LastFrame run before the FirstFrame.  And have the LastFrame check that there are at least 3 good groups and the FirstFrame that there are least 3 good groups.  This will have the effect of running the LastFrame step for 3 group integrations *but* not the FirstFrame step.  The LastFrame step is more important, especially as most 3 group integrations will be for bright sources.  In summary:

run LastFrame before FirstFrame
Have both steps check the number of good groups, not just number of groups as currently written.

2 groups: Neither LastFrame or FirstFrame run.
3 groups: LastFrame run, but not FirstFrame.
4+ groups: LastFrame and FirstFrame run.

I could add this to the pull request #1327.  Or this could be a separate pull request depending on what makes the most sense.

**Comment by jemorrison** [comment]
Why is the last frame rejection more important than the first frame rejection ?  In the first integration for bright data the frame that is more incorrect is the last frame, however I think the opposite is true for the
second integration where the first frame is affected by the additional reset switch charge decay.
I am not following why we would want to switch the order ? 

As it is currently written what happens if there are 3 groups in the integration and the first and last are rejected - so there is only one valid group. Does the pipeline fail ? How does it give a slope for 1 point ?
@mwregan2 
@karllark 
@hbushouse

**Comment by hbushouse** [comment]
The ramp_fit step is already capable of handling cases where you only have 1 group to work with. It'll simply use the value of that group and divide it by the group integration time to produce a slope value.

**Comment by mwregan2** [comment]
That one-group method doesn’t work for MIRI since there is no super bias subtraction for MIRI.

**Comment by hbushouse** [comment]
Ah, right. I don't think anyone thought of that until now. So that suggests anything in ramp_fit always needs a minimum of 2 groups when working with MIRI data. For 2 groups, it just computes (group2 - group1) / group_time.

**Comment by dmggh** [comment]
I'll add that to the list of ramp_fitting updates.

________________________________

**Comment by karllark** [comment]
@jemorrison : I thought I had addressed the issue of making sure there were 2 *good* groups after both steps had run by emphasizing that the steps should check for good groups, not just the number of groups.   Hence, if the total number of groups is 3 before either step, after the 1st step runs there will only be 2 good groups and the 2nd step would not be run.

As for the ordering of the steps, I had thought that the LastFrame effect was larger for *bright* targets.  Given that groups with 3 frames would be more likely to be for bright sources, then the logic would be to do the LastFrame correction and not the FirstFrame.  If this is not the case, then the ordering should be reversed.  Either way, we should make a conscious decision on the ordering.  We should write both steps to be agnostic on ordering and to make sure that 2 groups are good after both steps are run.

**Comment by jemorrison** [comment]
Let me look at some bright data and get back to you. My memory is that the last frame effect may be larger than the first frame effect for the first integration but that is not true for integrations > 1.  I was thinking for bright short integrations most people will be doing multiple integrations in an exposure.

On the issue of the number of good groups and if a step is run or not. It seems we need to provide information to the user that there were not enough groups in the integration to reject a group we know
is "not ideal" so the slopes are "not ideal". At a minimum we should set a DQ flag ? But those may not be looked at in practice - but it is something

**Comment by hbushouse** [comment]
Log warning messages can be used to indicate when one of the steps gets skipped due to insufficient ngroups. We already do that in the lastframe step when that step gets skipped for ngroups=1 exposures.

**Comment by hbushouse** [comment]
Oh, and of course the step status keyword in the product header (S_FRSTFR, S_LASTFR) will tell you if the step was skipped.

**Comment by jemorrison** [comment]
I took some very bright JPL data that was taken with multiple integrations and only 5 to 6 frames. I rejected frame 1 and the last frame.  For all the integrations the last frame was farther off from the linear fit than the first frame. So I was remembering wrong. The last frame effect does lead to a larger error than the first frame. So I agree we should re-order the steps and first reject the last frame 
and if there are enough frames (groups) in the integration then also reject the first frame.

**Comment by jemorrison** [comment]
I will document why we have prioritized last frame correction over first frame correction on the MIRI RTS web page do we do not lose track of this. If you want more from the MIRI team let me know and  I can provide a short report.

**Comment by karllark** [comment]
@jemorrison - thanks for looking into this and clearly stating that the change is justified by the data.  Most excellent!

**Comment by hbushouse** [comment]
#1925 fixed changes needed in ramp_fit step only. Other updates to `calwebb_detector1` and possibly the `firstframe` and `lastframe` steps are still needed.

**Comment by hbushouse** [comment]
OK, so to summarize, the last frame effect is worse, regardless of source brightness, so when there are only 3 groups to start with, we apply the last frame flagging (which nixes group 3), but do not apply the first frame flagging, leaving groups 1 and 2 for ramp fitting. We don't actually need to reorder the steps to accomplish this, it could just be built into the logic based on the value of NGROUPS, e.g.:

- NGROUPS>=4: Apply first frame and apply last frame
- NGROUPS = 3: Do **not** apply first frame; do apply last frame
- NGROUPS < 3: Do not apply first frame; do not apply last frame

@karllark @jemorrison Does that sound right?

**Comment by hbushouse** [comment]
OK, we'll have @dmggh make these updates as part of the fixes for #2035.

**Comment by stscicrawford** [comment]
Closing as issues has been fixed in #2040.  Please re-open or create a new issue if there is still outstanding work that needs to be done.
