### ISSUE TITLE
Pipeline modules need to update FILETYPE keyword

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#1699]
SDP populates the FILETYPE keyword with 'uncalibrated' when it creates level-2b (_uncal.fits) files. That value is currently retained throughout all levels of cal pipeline processing. Each pipeline module should update the value in its output product(s) at the end of its processing, with a list of appropriate values that are still TBD.

**Comment by jdavies-st** [comment]
Another option here would be to remove the FILETYPE keyword, as it is redundant to the filenames `_uncal`, `_cal`, `_s2d`, `_s3d`.  And keywords such as `S_DARK`, `S_JUMP`, `S_RESAMP`, etc. give a much more granular information on exactly what steps have been applied for calibration.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1743](https://jira.stsci.edu/browse/JP-1743)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1743?focusedCommentId=502282#comment-502282):_

Fixed by #5585
