### ISSUE TITLE
Process off-target background observations as science

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1728]
# Issue
Off-target background observations are exactly that: Fully qualified observations of a target. As such, they can be fully calibrated.  Create the necessary associations for such calibration.

# Resources
- Result of [discussion](https://github.com/STScI-JWST/jwst/issues/1716#issuecomment-364178136) in #1716 and [discussion](https://outerspace.stsci.edu/display/JWSTCC/CALSPEC2?focusedCommentId=13498175#comment-13498175) the the JWST Calibration Working Group discussion of `calwebb_spec2`.

**Comment by hbushouse** [comment]
We essentially need to back out #2096 so that backgrounds are NOT filtered out of level-3 ASN's.

**Comment by stscieisenhamer** [comment]
Handled by PR #3469.
