### ISSUE TITLE
Distortion solution should return v2,v3 in arcsec

### ISSUE THREAD

**Issue by drlaw1558** [spacetelescope/jwst#1735]
Known issue based on discussion with Nadia; to be addressed after NIRSpec moves unit conversion to reference files

**Comment by hbushouse** [comment]
Does this apply to all instruments?

**Comment by drlaw1558** [comment]
I believe so; Nadia and I have been discussing this for a year or so.  The issue as I recall is that for compatibility with NIRSpec assign_wcs is currently returning v2,v3 in degrees instead of arsec (the defined unit for V2,V3).  This is currently worked around in a few places, but the plan was to have assign_wcs properly use arcsec as soon as NIRSpec was ready for it this Spring (and integrate that work with the bounding box changes).

I don't think there was formally a ticket on this yet; apologies if it's a duplication.

**Comment by nden** [comment]
@hbushouse Yes, it applies to all instruments. The numbers in V2, V3 look much better in arcsec than in deg. And all instruments agreed to do this. NIRSPEC is a little tricky but there's a way to do it. #1603 is related.

**Comment by nden** [comment]
This was fixed in #1911, #1931 and by delivering a new Nirspec `ote` reference file.
