### ISSUE TITLE
pipeline/data model convention: apply blendmodel inherently

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1753]
# Proposal
Now that there is a proper `blendmodels` function, consider making this a "highly suggested component" in any multi-model calculation. Especially so if those calculations are implements as `Step`s. If each `Step` handles its own `blendmodels`, then the standard `Step` saving mechanisms can be used without explicit calls to `Step.save_model`. This will also clean up the enclosing `Pipeline`/`Step`.

Example is with `calwebb_ami3`. After calls to the sub-steps `ami_average` and `ami_normalize`, the pipeline makes the calls to `blendmodels`, and then has to explicitly save the results. If the two steps handled this themselves, then the steps could be run alone and save their results consistently. The pipeline code itself cleans up considerably.

And finally, with an eye to the future, where users will be using the steps in their own code, implementing this encapsulation will make a much cleaner api for user to grasp.

Discuss among yourselves...

**Comment by melanieclarke** [comment]
@emolter @braingram - do you know if there is still a need/desire to extend the model blender beyond the places it is currently used?

**Comment by braingram** [comment]
Unfortunately I do not. I am not familiar enough with other steps/pipelines to know which combine models and if they use (or could use) ModelBlender. My vote is to close this issue and reopen one if there is a specific use case identified.

**Comment by melanieclarke** [comment]
Agreed -- I'll close now.  

Please open new tickets as needed, if there are places the ModelBlender should be used and isn't yet.

**Comment by melanieclarke** [comment]
I don't see anything particularly wrong about the save_model usage in ami3, if it's saving the intended products to the intended names.  There are various other places in the pipeline where save_model is directly called, for various purposes.
