### ISSUE TITLE
Update docs explaining FITS vs ASDF in data products

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#1757]
The other week, someone asked something like, "I thought the pipeline produces ASDF, but I only see FITS files." It is not the first time someone got confused.

**Comment by sosey** [comment]
except it's usu, "I thought the pipeline produced FITS, what's ASDF",  +1 for ASDF ;)

**Comment by melanieclarke** [comment]
Closing, since we don't produce ASDF output data products.

**Comment by braingram** [comment]
The pipeline/stpipe infrastructure supports saving both fits and asdf (by providing an `output_ext` argument to strun).
```
>>> strun resample my_asn.json --output_ext=".asdf"
...
stpipe.resample - INFO - Saved model in my_asn_resample.asdf
```

**Comment by braingram** [comment]
Thanks. I think it's undocumented and can't find any in jwst or stpipe (I only know of it because of the different defaults in jwst and romancal).

**Comment by melanieclarke** [comment]
Ticket is here: https://jira.stsci.edu/browse/JP-3812
