### ISSUE TITLE
Add the option to use a reference image for extract_1d

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#1777]
The `extract_1d` step has two different options for specifying the extraction region:  (1) a rectangular box; (2) polynomial coefficients for the lower and upper limits in the cross-dispersion direction.  The latter option is needed if the spectrum is tilted or curved, but it can be time-consuming to determine the coefficients, and they can't easily be compared with the science data.  A third option has been proposed:  the reference file could be an image with pixel values -1, 0, or 1.  A pixel in the science file would be included when accumulating the sum along a column if the corresponding pixel in the reference file had the value 1.  Values of -1 in the reference file could be used to indicate background regions.  The image in the reference file should be close to the same size in each axis as the image in the science file.  If they differ, they should be aligned at pixel [0, 0], and the reference image should either be truncated or padded with zeros to match the science image.

One advantage of the reference image for extraction is that it will be easy to compare with the science data:  Display the science data, display the reference image, and blink between them.  Another advantage is that an image can easily be shifted and/or rotated to align with the science data, although such adjustments are not planned for the `extract_1d` step itself.

**Comment by philhodge** [comment]
If the data were taken with a nod offset, and if a reference image is used to specify the extraction and possibly background regions for `extract_1d`, the reference image should be shifted by the amount of the nod offset.

**Comment by stscicrawford** [comment]
Closing due to #1783 implementing this feature.   Please re-open or open a new issue if there is more work to do here.
