### ISSUE TITLE
Process Nirspec observations with `filter=OPAQUE`

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#1782]
From the Nirspec INS team:

Nirspec has a mode of operation where FILTER=OPAQUE and an internal lamp is used.
In this case the WCS pipeline should stop at the MSA coordinate frame. The calspec2 pipeline should include the following steps (this needs to be confirmed by INS/IDT teams):

- assign_wcs (stop at the MSA) (This is implemented as expected.)
- background subtraction (if there is an associated background exposure, relevant mainly for IFU)
- extract_2d
- msaflagging
- barshadow
- resample_spec
- extract_1d

The last two steps are probably only useful for the LINE lamps (needs confirmation by the IDT team).

**Comment by nden** [comment]
I have ran the pipeline on a FS observation with filter=OPAQUE and get the following error in flatfield:

```
 File "/internal/1/astropy/jwst/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/internal/1/astropy/jwst/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'sflat'  =   No match found.

```

The INS team may need to add filter OPAQUE with values of `N/A` to the flatfield rmap.

**Comment by stscieisenhamer** [comment]
A philosophical FYI: If all that is of concern is SDP, since this is `calspec2`, associations can handle this by creating a different association that tells SDP to run a different `calspec2` config file that skips the offending steps. No judgement on what is the best solution, just offering another one.

**Comment by nden** [comment]
I think this should be done on 2 levels. First, handle this through the association and a different config file as @stscieisenhamer suggests. And second, have the INS team change the rmap to include `filter: " OPAQUE": N/A` for the case when individual steps are run. This will prevent, for example, flatfield from crashing.

**Comment by stscicrawford** [comment]
@stscieisenhamer Please take a look at updating the associations for this.   Steps may be need to be confirmed with the INS and IDT teams (might be easiest to add them here to comment)

**Comment by stscicrawford** [comment]
@nden Please create a jira ticket for the updates to the rmap

**Comment by hbushouse** [comment]
Only the NIRSpec f-flat and s-flat ref files are selected by FILTER, so if we were to only update the rmaps to include an N/A entry for this filter value, and we update the flat_field step to skip application of any flat for which the ref file is N/A, the d-flat would still get applied if the flat_field step executed. It appears that the team does not want any flat-fielding applied to these exposures. Hence logic would need to be added to the flat_field step to completely skip processing when FILTER='OPAQUE', or we would need to setup a special calspec2 cfg for these exposures that skips the flat_field step. I'm not sure I like the idea of a special calwebb_spec2.cfg just for these (relatively rare) exposures, but it is doable. The SDP workflow manager would need logic added to use this particular calspec2.cfg when FILTER='OPAQUE'.

**Comment by hbushouse** [comment]
calspec2 currently executes the following steps for regular NIRSpec spectroscopic exposures:
-  assign_wcs
-  background subtraction (if background target exposures exist)
-  msa flagging (MOS, IFU)
-  extract_2d
-  flat_field
-  source type
-  pathloss (MOS, IFU, FS)
-  bar shadow (MOS)
-  photom
-  resample_spec
-  extract_1d
So even if flat_field gets skipped automatically by setting all the ref files to 'N/A', we still also need to skip pathloss and photom (and theoretically also source_type, but it doesn't hurt anything to apply it). So this does suggest that we probably need a dedicated calspec2 cfg file, in order to skip all the unnecessary steps.

**Comment by stscieisenhamer** [comment]
Anyone know how to setup a calibration proposal in APT? Not immediately obvious or its not implemented yet.

**Comment by hbushouse** [comment]
Do you mean an instrument "calibration" mode, like taking darks, flats, or lamp exposures? If so, you have to check the box on the front window of APT that says something like "Enable engineering modes" (or something like that). You will then get calibration-related observing templates in the templates drop-down menu.

**Comment by stscieisenhamer** [comment]
# Question
`OPAQUE` is not a valid value currently in the keyword database. Will this be rectified or is the value actually something else?

**Comment by hbushouse** [comment]
It's slated to be added in https://jira.stsci.edu/browse/JWSTKD-229. I believe it's already in our yaml schemas.

**Comment by stscicrawford** [comment]
Was also being tracked by [JP-282](https://jira.stsci.edu/browse/JP-282).
