### ISSUE TITLE
Migrate to spacetelescope repositories

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#1784]
The JWST pipeline code should be migrated under the https://github.com/spacetelescope/.   This is an issue opened to catch any aspects required for that move.

**Comment by stscicrawford** [comment]
@nden @jhunkeler @rendinam  -- here is a issue for migrating the spacetelescope repositories.  I will add a checklist of items to it, but please  add any other items that you think would be good to check

**Comment by stscicrawford** [comment]
@sosey -- to answer your question, this repository will disappear from here after the migration and if we want it to still appear here, we will have to fork it back.

**Comment by sosey** [comment]
@stscicrawford I was thinking more along the lines of, should we recreate an empty one, not a fork, that points to the new one at spacetelescope (with a readme) in case we miss someone, or something, that references this site?

**Comment by stscicrawford** [comment]
Currently, we will plan to migrate the repository on Wednesday, 27 June 2018.   The follow items will need to be checked in order to migrate the repository:

- [ ] Notify the users (DMS-WG, DMD, others?) via email that we are planning to move the repository
- [ ] Notify the users via slack
- [ ] Notify the users via Github issue
- [ ] Merge any remaining pull requests that might need to be merged.  
- [ ] Tag the repository
- [ ] Migrate the repository
- [ ] Possible Tag the new repository 
- [ ] Update read the docs if needed
- [ ] Update jenkins to the new repo
- [ ] Update astroconda to the new repo
- [ ] Update jirahub for linking issues with jira to the new repository
- [ ]  Update the README 
- [ ] Update the documentation to the new repository
- [ ] Notify the users of the new repo location

Anything else that I forgot?

**Comment by stscicrawford** [comment]
@sosey How about combining the two ideas:  a fork with the main branch being an empty except a README back to the main branch?   My only concern with a new repositories is that users might mistakenly open issues (which can't be done with a fork) or pull requests there (only solution in that case is no repository at all).

**Comment by sosey** [comment]
It's also possible to turn off issues in the repository settings, but not pull requests. Whatever you decide is fine with me.

**Comment by jhunkeler** [comment]
Deleting `stsci-jwst/jwst.git`, recreating it, turning off the issue tracker, and leaving behind two files makes sense to me (`README` and `setup.py`)
## README

```
This repository is deprecated.

- The new URL is:
    https://github.com/spacetelescope/jwst.git

- To replace the URL inside of an existing clone:
    git remote set-url origin https://github.com/spacetelescope/jwst.git

- If you have a personal fork of this repository please delete your 
fork of stsci-jwst/jwst.git, then fork spacetelescope/jwst.git

- yadda-yadda
```

## setup.py
```python
# A meaningful failure message for any scripts/crons left behind...
with open('README') as readme:
    print(readme.read())
exit(1)
```

**Comment by stscicrawford** [comment]
The repository has been merged.  The old URL redirects to here, so I think it is actually best not to create a fork but just allow it to redirect.    I've given permission to the JWST calibration team to the repository as admin for right now, but let me know if I need to update anything else.

**Comment by sosey** [comment]
The upline html link shows no repositories as well, so maybe this is enough. (https://github.com/STScI-jwst). Interestingly enough, I can still git clone the old url to `jwst` and it clones it and attaches the old url as the remote. Hopefully anyone interacting with github mostly over the terminal, who we didn't notify,  will eventually notice the remote address change.

**Comment by stscicrawford** [comment]
Closing this as the repository has been migrating!   

Opening another issue for the JDOCs migration as that is currently being updated and under review
