### ISSUE TITLE
intermediate results not in same format as original input

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#1795]
Noticed in this [section of code for outlier detection,](https://github.com/STScI-JWST/jwst/blob/master/jwst/outlier_detection/outlier_detection.py#L277) the blot intermediate results end up in a `ModelContainer`. When written out, this will create `n` files where it should really be repackaged back into the format of the input: I.e. if the input was a single cube, the blot images should be repacked into a cube and written out as such.

**Comment by hbushouse** [comment]
@stscieisenhamer Given the age of this ticket and the amount of changes that've happened in outlier_detection, is this still an issue?

**Comment by stscieisenhamer** [comment]
If there have been no issues/complaints with actual data and latest revs of the code, I call this defunct.
