### ISSUE TITLE
DOC: Is your ASDF format of different levels documented for user somewhere?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#1806]
Is there some kind of data handbook where a GO can refer to to understand ASDF/FITS layout at different product levels?

For example, in HST-land, if I wanted to see where AMP A data is in the FLT file, I refer to ACS Data Handbook. Is there such a thing yet for your pipeline products? Thanks.

**Comment by hbushouse** [comment]
The closest thing so far is the JDox stuff on file names and formats here: https://jwst-docs.stsci.edu/display/JDAT/JWST+File+Names%2C+Formats%2C+and+Data+Structures

which has some fleeting references here and there to ASDF extensions/files, but some of them are incorrect, and others so brief that they don't really convey the true purpose and content of the ASDF extensions in science products. So the docs do need some work yet.

**Comment by melanieclarke** [comment]
Closing, since documentation has evolved quite a bit since this issue was filed.  If there are still issues with documenting output data, please file a new ticket.
