### ISSUE TITLE
DataModel mocking

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#182]
It would be nice, if it doesn't already exist, to have some function that will create a DataModel that has data (by default arrays of 1 or some such), keywords (with basic values matching their types), etc. Such a function may look like:

```
model = jwst.datamodels.mock(DataModel, data_shape=a_shape, data_fill=some_fill)
```

**Comment by nden** [comment]
Agreed in general. However, would a general model without the instrument/mode context be useful?
The `assign_wcs` tests create a default model object and populate the interesting parts of the meta structure. But maybe other steps don't care that much about specific info and any general model will do.

**Comment by melanieclarke** [comment]
Tests for jwst now mock DataModels in many different ways, depending on needs.  It's not clear that a general function to provide mocking is necessary, or would be worth developing at this point.  I will close this issue, but feel free to reopen if more discussion is needed.
