### ISSUE TITLE
Updating install_requires

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#1861]
I was trying to install the pipeline from a fresh environment and there were a number of packages that were not included in the setup.py install_requires.

**Comment by stscicrawford** [comment]
In particular, it was the line in setup.py:

    from numpy import get_include as np_include

If numpy is not yet installed, this will cause setup.py to fail.   While this is easy to fix for the user, this might cause problems for a novice and should be addressed.

**Comment by nden** [comment]
#1508 is related.
