### ISSUE TITLE
Update the refpix step to set the DQ bits of reference pixels in science data

### ISSUE THREAD

**Issue by stscirij** [spacetelescope/jwst#1880]
This will identify reference pixels as such for future steps (e.g. RSCD).  The DQ value to set is from dqflags.py: pixel['REFERENCE_PIXEL'] and currently has the value 2147483648 (2**31).

**Comment by hbushouse** [comment]
The instrument teams are on the hook to deliver updated MASK reference files with reference pixels flagged with the new REFERENCE_PIXEL flag, so we shouldn't need to set these in the code. See the JCCWG meeting notes from 15-Aug-2017: https://outerspace.stsci.edu/display/JWSTCC/2017-08-15+Meeting+notes

**Comment by stscirij** [comment]
New mask reference files are either delivered or are in the process of being created, so this can be closed
