### ISSUE TITLE
For extract_1d, find nod/dither offset from the WCS

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#1894]
A spectrum can be intentionally offset in the cross-dispersion direction due to nod and/or dither offsets.  This is currently accounted for in `extract_1d` by reading the offset amplitude from the reference file, and multiplying that amplitude by an integer expression that depends on the position number of the current exposure within a pattern.  This approach only works for certain limited cases.  For some modes, for example, the nod offset has different amplitudes in different directions.

We rely on the world coordinate system (WCS) for many things in the JWST pipeline; we should use the WCS for nod/dither offsets as well.  The `extract_1d` reference file specifies the location of the extraction region in the absence of offsets.  The WCS, together with the target location as specified in the metadata, will then give the actual cross-dispersion location of the spectrum  The difference between those two tell us how much and in which direction to shift the extraction region.

**Comment by stscicrawford** [comment]
Closing as this appears to be resolved in #1894, please re-open or create a new issue if this is not the case with the work that still needs to be done.
