### ISSUE TITLE
make_header missing keywords for imaging pipelines

### ISSUE THREAD

**Issue by aliciacanipe** [spacetelescope/jwst#1957]
Hello,

I've done some preliminary tests on the make_header script for NIRCam imaging (level 1, 2, and 3) data. I was trying to add simulated data to the output FITS file and run it through the pipeline, but so far have been unsuccessful. Here is a list of missing keywords I noticed when comparing it to other exposures, though some keywords are known already, e.g., FILTER, READPATT, etc. Here is my list (most are probably not used by the pipeline algorithms):

(PRIMARY extension)
FASTAXIS
SLOWAXIS
FILTER
PUPIL
PATTTYPE
PATT_NUM
NUMDTHPT
PATTSIZE
SUBPXTYP
SUBPXNUM
SUBPXPNS
XOFFSET
YOFFSET
READPATT
TSAMPLE
EFFINTTM
EFFEXPTM
EXPEND
EXPMID
DURATION

(SCI extension)
NAXIS3
NAXIS4
BUNIT
BSCALE
BZERO
RA_V1
DEC_V1
PA_V3
RADESYS
ASNPOOL

**Comment by stscicrawford** [comment]
Thanks for the list -- can you make the data file you used available along with the command you used to run it through the pipeline so we are able to reproduce the results and test it ourselves?

**Comment by aliciacanipe** [comment]
Sure. My files are here:

/grp/jwst/wit/nircam/canipe/make_header_testing/

In this directory you have baseline_*_header.fits files, which are the outputs from make_header. NOTES.txt has the commands I used to create them. I also included the simulated image exposure I used to compare the headers. The *.dat tables are just lists of headers I noticed were missing.

**Comment by aliciacanipe** [comment]
Thanks, Bernie. I assumed most of the headers were not necessary for the specific pipelines, it was just faster to make a table of all the missing headers rather than searching individually through the pipeline source code to see which ones are required. I am working on testing the spec2 pipeline headers, but will also let you all know about progress with running the make_header outputs through the pipeline. I'll put all the files in the same directory mentioned above (/grp/jwst/wit/nircam/canipe/make_header_testing/), with an explanation of the files in NOTES.txt.
