### ISSUE TITLE
Add datamodels .validate() method for advanced model-specific checks

### ISSUE THREAD

**Issue by jaytmiller** [spacetelescope/jwst#1965]
Discussing WCS file checking with @nden revealed that advanced checks exist implemented in a .validate() method.   This suggested invoking .validate() during CRDS certify checking to ensure the advanced checks are satisfied in addition to ASDF schema,  etc.

@bernie-simon and I discussed the possibility of making .validate() a standard models method, an  interface which defaults to doing nothing and requires no parameters.   @nden 's implementation would override it and check advanced properties.    Future models desiring their own application specific advanced checks would implement .validate() as a standard approach. 

Next we realized that .validate() could possibly be folded into the existing data models checks and be called automatically during model checking.   This raised secondary issues:

1.  Can/should @nden's .validate() be automatically called by the data models as part of normal models checking (i.e. schema validation)?   Or should CRDS certify call it directly instead?  (Further,  is @nden already automatically invoking her .validate() when appropriate?   Is it invoked whenever datamodels.open() is called?)

2. When should .validate() be enforced,  during model creation,  or model output?   Should it be just the same as schema checks with STRICT and PASS_INVALID_VALUES?

3. What should be done when .validate() fails?

**Comment by jaytmiller** [comment]
Reading through datamodels code I think .validate() is called automatically during DataModel.__init__() already.   That appears to do schema validation for dataset models.    However,  while ReferenceFileModel is derived from DataModel,  it overrides validate() without calling super().   Consequently, Models derived from ReferenceFileModel may be skipping schema validation intentionally or unintentionally.   Possibly this relates to ASDF validation.

**Comment by hbushouse** [comment]
@jaytmiller @nden The only place in the entire repo that I see `ReferenceFileModel` being used appears to be in conjunction with WCS-related reference files that are in ASDF format (e.g. RegionsModel, FPAModel, IFUPostModel, FilteroffsetModel, ...). So I assume this is a schema that only applies to ASDF formatted ref files? 

I don't see the similar models like `ReferenceImageModel`, `ReferenceCubeModel`, etc. used anywhere. What were those intended for?

**Comment by nden** [comment]
I think I was not aware of `DataModel.validate` when I wrote `ReferenceFileModel.validate` and so `super` was not called. Looking at this more closely, currently the transform is set at the same level as the  `meta` object which means the parent class validation for the WCS reference file models fails. It will be good to fix this in the future by moving the transform in the wcs reference files schemas under `meta` which will allow validating the parent class schema. This will require also changes to the scripts that create the reference files. However, no changes to the cal pipeline code are necessary.

**Comment by nden** [comment]
@hbushouse Yes, ReferenceFileModel is used only for WCS reference files in asdf format.
Perhaps @bernie-simon knows what the rest of the schemas/models are for.

**Comment by bernie-simon** [comment]
> I don't see the similar models like ReferenceImageModel, ReferenceCubeModel, etc. used anywhere. What were those intended for?

These model types are used by the generic datamodels open function. If a fits file has the REFTYPE keyword, but not the DATAMODL keyword, it's opened as a *File, *Image, *Cube depending on the dimensionality of the fits file.

**Comment by jaytmiller** [comment]
As far as I know this is now working fairly well on all sides and reference file model sub-classes are calling the super-class .validate() where applicable.

Checking with @bernie-simon  our carefully nuanced model "read" behavior seems optimal for this point in time.    Invalid keyword values result in warnings;  this means that backward incompatible schema changes are not intrinsically fatal to now non-compliant references;  this prevents the need for infeasible re-deliveries of large numbers of files for superficial reasons.  Invalid values are are not accessible to CAL code by default,  they are effectively replaced with None;  this means that if they are important to processing, CAL code either needs to handle None or will just fail,  while if they are unimportant (HISTORY, TELESCOP, PEDIGREE, ...),  CAL processing will not be impacted.

Since it is not relevant to reference files,  we did not do a full review of "write" behavior.   One concern here is the behavior of the system when propagating files with invalid values to products of a new type.   There is potential to replace invalid values with valid default values...  which may be worse than propagating the invalid value;  the reason is that for later products it won't be clear that the default was not specified at the outset and may be incorrect.   This is mitigated some because the primary use of defaults is the creation of arrays

In general the behavior of datamodels.open() has improved and now announces when a sub-par model is being guessed because DATAMODL is missing.  validate() with a nicely specialized model is generally called automatically so this is working well for the CRDS certify use case.
