### ISSUE TITLE
Output files have wrong name for Cube_build

### ISSUE THREAD

**Issue by jemorrison** [spacetelescope/jwst#1978]
# Issue
When running cube_build and providing an output name with --output_file 
the resulting MIRI IFUCubes have numbers inserted in the names instead of
the channel number.
For example:
```
strun cube_build.cfg MIRM103-Q0-SHORT_495.fits --output_file=test
```
produces `test_0_s3d.fits` and `test_1_s3d.fits`.
But it should produce `test_ch1_s3d.fits` and `test_ch2_s3d.fits` 

The files names are being set by the step class function I believe. 
@stscieisenhamer 

# Implementation
- [x] bump version
- [x] documentation
- [x] tests
- [x] code
- [x] tests
- [x] documentation
- [x] bump version

**Comment by jemorrison** [comment]
Is it time for me to remove from cube_build it forming the filename ?

**Comment by stscieisenhamer** [comment]
@jemorrison No, it still needs to be there, because only cube_build knows what the names should be. Also, I (think) I have already modified cube_build to use a more generic api to do the naming, so, at the moment, all is good.
