### ISSUE TITLE
Secondary reference files not tracked by pipeline

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/jwst#1981]
The term 'secondary reference files' in this context refers to any data-specific product which is needed in order to calibrate or otherwise process the input data that can not be managed by CRDS.  Examples of these type of files would be the MSA Shutter file for an NRS MSA exposure as recorded in the `meta.instrument.msa_metadata_file` metadata keyword.

Regression testing using pytest and Jenkins demonstrated that as the tests are run in their current (tmp) directory, the code expects to find those files in the current directory since no path is associated with the filename as read in from the metadata.  

For example, the NRS_MSA_SPEC2 test (test_nrs_msa_spec2.py) has an input file of `F170LP-G235M_MOS_observation-6-c0e0_001_DN_NRS1_mod.fits` which references the `msa_metadata_file` of 'jw95065006001_0_short_msa.fits'.  Note the lack of path associated with this file.  

The desired behavior would be one where this file has a path automatically prepended so that subsequent references to this file will actually find the file regardless of the current working directory.

**Comment by jaytmiller** [comment]
Let me know if you view this as a closely related CRDS function and want more of my input. 

One possibility would be to invent a new URI (products://) which translates to "wherever these are going".   That could probably be added to stpipe similar to crds:// and translated as needed similar to crds://.

**Comment by hbushouse** [comment]
I suppose there are several possible ways to have this function:

1) treat the value in the `meta.instrument.msa_metadata_file` as complete and literal, such that if no path is included, use the working directory. And if the file is in another directory, that path must be included in the keyword value

2) always assume that "secondary" files like this are in the same directory as the input science data files (whatever ASN or individual FITS file name was specified via `input`)

What is `stpipe` currently doing in terms of ASN vs member locations? If the ASN file is in another directory and the path to that is included as part of `input`, do the science FITS files need to be in that same directory and/or do the science file names listed in the ASN file need to include the path to that directory?

**Comment by nden** [comment]
Also #940

**Comment by stscicrawford** [comment]
Closing as said to be resolved by #2073, but please re-open if that is not the case with the specific work that still needs to be done.
