### ISSUE TITLE
Numpy 1.13 vs 1.14 differences in numerical results

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1988]
Our nightly regression tests show differences in numerical results between numpy 1.13 and numpy 1.14.  This issue is to track those and determine if they're important or not.  We discuss these at length in https://github.com/STScI-JWST/jwst/pull/1888#issuecomment-386433739.

The nightly regression tests affected are:

- [x] niriss.test_ami_analyze.test_ami_analyze
- [x] niriss.test_ami_pipeline.test_ami_pipeline
- [x] pipelines.test_coron3_1.test_coron3_pipeline1
- [ ] pipelines.test_nrc_image3_1.test_image3_pipeline1

We need to

1. Figure out which common numpy function or computation(s) are causing this.
2. Reproduce with a simple test case.
3. Figure out if this is a numpy issue or an Anaconda issue.
4. Decide if we need to fix it, or if we're OK with the differences.

**Comment by jdavies-st** [comment]
Interesting discussion of these issue here

https://sinews.siam.org/Details-Page/reproducible-blas-make-addition-associative-again

ht: @pllim

**Comment by pllim** [comment]
At some point, maybe this 1.13 vs 1.14 won't be relevant anymore because 1.15.3 is out. :grimacing:

**Comment by jdavies-st** [comment]
Yeah, maybe this issue should be a catch-all for BLAS differences between different versions and builds of `numpy`.  😬
