### ISSUE TITLE
Pathloss correction for NIRISS-SOSS

### ISSUE THREAD

**Issue by stscirij** [spacetelescope/jwst#2042]
After a discussion between Howard Bushouse, Kevin Volk and Robert Jedrzejewski:

Implement pathloss correction for NIROSS-SOSS.  This is to be done when  EXP_TYPE == NIS_SOSS and TSO flag is not set.  Reference file will be selected by SUBARRAY.  Will have an initial reference file for SUBSTRIP96, will probably also add SUBSTRIP256.  Pathloss correction compensates for the outer parts of the trace falling outside the subarray.  Depends on wavelength and on the FILTER encoder setting for rotation angle.  Reference file will be a 2-d array with wavelength in 1 dimension and rotation angle in the other, angle will be obtained from science data header.  Pathloss task will interpolate along the rotation angle and produce a 1-d array of correction vs. wavelength.  The correction will typically be a factor <1 that the data are divided by to give what the flux would have been if the subarray were large enough to include all the flux.  1-d correction will be attached to data along with the wavelengths.

**Comment by KevinVolkSTScI** [comment]
The path loss function that was provided was made by taking the SUBSTRIP96 part of the rotated SUBSTRIP256 array and forming the ratio of values line by line.  Robert pointed out the presence of lines in the ratio values for the different orientations.  It looks like these are due to hot pixels and the the like in the sub-array.  I should replace the straight quotient by a smooth function that rejects outlier values to get rid of these artifacts.  I will work on this and give Robert the "cleaned up" functions. as soon as possible.

**Comment by KevinVolkSTScI** [comment]
A cleaned up image is found at /ifs/jwst/wit/niriss/niriss_pl_cleaned.  Robert should be able to see the file, but if not let me know and I can e-mail the fits file as an attachment.

**Comment by stscirij** [comment]
I got it, thanks

**Comment by KevinVolkSTScI** [comment]
There is some CV3 data taken with the external tungsten lamp that may be suitable for testing the correction.  For example file 

NIST79-G-256-150-6004122853_1_496_SE_2016-01-04T12h38m38.fits

and file

NIST79-G-96-150-6004123932_1_496_SE_2016-01-04T12h49m28.fits

are in the SUBSTRIP256 and SUBSTRIP96 arrays with the external tungsten lamp set at the same setting.  The files can be found at

/ifs/jwst/wit/witserv/data13/CV3/NIS/10_NIRISS_PerfVer/OTP79/raw/

I have not tried running either of these files through the pipeline so I cannot tell you whether they actually can be processed properly or not.  We just have to try the files and see if the corrected spectrum in the SUBSTRIP96 case looks OK compared to the spectrum from the SUBSTRIP256 case.

**Comment by stscirij** [comment]
Hi Kevin, I had a question about how the pathloss correction is to be applied at the time of 1-d extraction.  I anticipate passing a 1-d array of corrections to the extraction step, with one number for each column of data.  In the extraction step, flux is summed in a range of rows for the source, and the flux in a background range of rows is calculated as well.  Is it your understanding that the gross counts in the source aperture should be corrected by the pathloss correction, but the background counts should not be corrected?  The uncorrected background counts are then subtracted from the corrected source counts to get the net counts.  Is that correct?  Also, the correction is not 1.00 anywhere in your reference file, and yet I think the extraction aperture is fully within the 256 height subarray for at least some of the columns.  Is there another factor included in your reference file other than just correction for flux that is inside the extraction aperture but outside the subarray?  Thanks,  Robert J.

**Comment by hbushouse** [comment]
Fixed by #2588
