### ISSUE TITLE
Should there be an order to our FITS files?

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2057]
Discussion about whether the calibration software should use a certain pattern to sorting the extensions of a FITS file before writing it out?

**Comment by jdavies-st** [comment]
This becomes an issue when generating a dictionary of slits and then writing them out.  In python 3.6+, the insertion order is preserved, but in earlier versions it is not.  This means that a multislit FITS file could have 10 slits, and they would be in a different order each time it is written out.  This makes testing using `fitsdiff` a bit difficult.
