### ISSUE TITLE
tweakreg_catalog DQ rejection

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2062]
INS B7 testing of the `tweakreg_catalog` step on MIRI images resulted in several issues of concern, which are documented in https://jira.stsci.edu/browse/JP-164.
```
During Build 7 testing the MIRI team found that the Tweakreg Catalog does not work for MIRI data.

This information is in the MIRI Test report:
"The low-level structure in MIRI images may be affecting the source threshold determination. 
SSB is still investigating the details here, but they did get it to work manually. 
Second, the sources in this image are extremely sharp. The DAOfind algorithm rejects stars based
on a roundness and sharpness criteria and their default values are rejecting MIRI PSF-like objects.
To fix this, SSB would need to add instrument-dependent parameters for this step in pipeline.
The roundness and sharpness parameters were not exposed to the user/pipeline in the initial
implementation, but by relaxing the sharpness SSB got good source detections ...
Finally, the initial implementation of tweakreg_catalog did not include the exclusion of pixels or
regions based on the DQ arrays. Currently the entire image is being used (i.e. not excluding the
left-hand third of the image). That will need to be fixed. The false sources on the detector images
should hopefully be (mostly) cleaned up by applying a DQ mask."
```

**Comment by stscicrawford** [comment]
@stsci-hack @mcara Any comment on this issue?

**Comment by stscicrawford** [comment]
Or an update from @larrybradley ?

**Comment by jdavies-st** [comment]
We changed the threshold in #2510.  This was based on MIRI imaging testing we did during the image registration hack day with the MIRI instrument team.  So I think that resolves that issue.

The area used to find sources and also the area resampled to the output frame is not controlled by the DQ array currently, but by the bounding box set in the DISTORTION reference file. Currently the bounding box for MIRI imaging mode is the full detector.

**Comment by jdavies-st** [comment]
It's possible you could use a DQ array to control where sources are detected by using a mask.  That makes sense.  But one still needs a bounding box for determining which rectangular area gets used to compute the output frame.  And again, currently that is the whole detector, including the coronographic area in the upper left.  See https://jwst-docs.stsci.edu/display/JTI/MIRI+Imaging

**Comment by larrybradley** [comment]
Is the MIRI team working on a solution for specifying the imaging area?  `tweakreg` needs some way of knowing where to look (or exclude) when finding sources.

**Comment by jdavies-st** [comment]
Currently the DQ array gives the usable imaging area, i.e. areas outside the imaging area are flagged with 'NON_SCIENCE' or 'REFERENCE_PIXEL', or some other value if the data is bad.  I don't know exactly what those should be.  The list of possible flags are in datamodels:
```
In [1]: from jwst import datamodels

In [2]: datamodels.dqflags.pixel
Out[2]: 
{'GOOD': 0,
 'DO_NOT_USE': 1,
 'SATURATED': 2,
 'JUMP_DET': 4,
 'DROPOUT': 8,
 'RESERVED_1': 16,
 'RESERVED_2': 32,
 'RESERVED_3': 64,
 'RESERVED_4': 128,
 'UNRELIABLE_ERROR': 256,
 'NON_SCIENCE': 512,
 'DEAD': 1024,
 'HOT': 2048,
 'WARM': 4096,
 'LOW_QE': 8192,
 'RC': 16384,
 'TELEGRAPH': 32768,
 'NONLINEAR': 65536,
 'BAD_REF_PIXEL': 131072,
 'NO_FLAT_FIELD': 262144,
 'NO_GAIN_VALUE': 524288,
 'NO_LIN_CORR': 1048576,
 'NO_SAT_CHECK': 2097152,
 'UNRELIABLE_BIAS': 4194304,
 'UNRELIABLE_DARK': 8388608,
 'UNRELIABLE_SLOPE': 16777216,
 'UNRELIABLE_FLAT': 33554432,
 'OPEN': 67108864,
 'ADJ_OPEN': 134217728,
 'UNRELIABLE_RESET': 268435456,
 'MSA_FAILED_OPEN': 536870912,
 'OTHER_BAD_PIXEL': 1073741824,
 'REFERENCE_PIXEL': 2147483648}
```
In `resample`, I use data that is 'GOOD' and 'JUMP_DET' by default.  One can make a mask:
```
In [67]: flags = datamodels.dqflags.pixel

In [68]: mask = (im.dq != flags['GOOD']) & (im.dq != flags['JUMP_DET'])
```
And plot it up.
<img width="462" alt="screen shot 2018-10-08 at 2 43 22 pm" src="https://user-images.githubusercontent.com/17088869/46627835-b9f84580-cb09-11e8-87f5-990ea8519aa6.png">

**Comment by jdavies-st** [comment]
It would be good to get feedback from the teams on which big flags to ignore for certain steps.  But perhaps one can just be conservative and mask out 'NON_SCIENCE' for now:
```
mask = flags['NON_SCIENCE'] & im.dq
```
<img width="460" alt="screen shot 2018-10-08 at 3 32 22 pm" src="https://user-images.githubusercontent.com/17088869/46629583-5e30bb00-cb0f-11e8-8fa4-a78c4d3bba32.png">

**Comment by hbushouse** [comment]
Using DQ flags such as "NON_SCIENCE" is one way to handle this, but that would require separate MASK reference files in CRDS for each different observing mode that uses the Imager detector, so that different regions would be flagged as good vs bad depending on whether the exposure is normal direct imaging, coronagraphic imaging (and which coron mask is in use: Lyot vs 4QPMs), LRS fixed-slit spectroscopy, or LRS slitless spectroscopy. They all use different regions within the detector. Right now there's just 1 generic MASK file for the whole Imager detector. The example shown above is not appropriate for any single exposure type, because it has both the direct imaging and coronagraphic Lyot areas flagged as good.

**Comment by jdavies-st** [comment]
So should we kick this up the line to the instrument teams and ask if they would like to delivery new reference files for the various modes?  Or are they happy with the current mask as shown above for imaging mode?

**Comment by hbushouse** [comment]
Yes, we should raise this with the MIRI team, or at least the MIRI reps that are part of the DMS WG in INS. I don't think that even the mask shown above is correct for imaging modes, because it includes both the imager and Lyot areas of the field. I would think you'd want just the imager part by itself. This is assuming I'm reading the picture correctly - the yellow area is where the NON_SCIENCE flags are set, right? Which means the dark (non-yellow) areas would be considered good.

**Comment by jdavies-st** [comment]
Yes, that's exactly the interpretation of the colors.  Agree that the mask file would have to be selected on not just `detector` but also `exposure_type` or obs mode.

I'll add that the current MIRI mask reference file for the imaging detector has nothing flagged NON_SCIENCE, so I actually do not know where the NON_SCIENCE flags are creeping in.  The images above are from MIRI simulated images.

**Comment by jdavies-st** [comment]
Btw, here's the current MIRI imaging MASK reffile:
```
In [1]: from jwst import datamodels                                                                                                      

In [2]: mask = datamodels.MaskModel('/grp/crds/jwst/references/jwst/jwst_miri_mask_0023.fits')                                           

In [4]: dqflags = datamodels.dqflags.pixel                                                                                               

In [25]: (dqflags['NON_SCIENCE'] & mask.dq).astype(np.bool).any()                                                                        
Out[25]: False

In [12]: mask.dq_def                                                                                                                     
Out[12]: 
FITS_rec([(0,  1, 'DO_NOT_USE', 'Bad Pixel do not use'),
          (1,  2, 'DEAD', 'Dead Pixel'), (2,  4, 'HOT', 'Hot Pixel'),
          (3,  8, 'UNRELIABLE_SLOPE', 'Large Slope Variance'),
          (4, 16, 'RC', 'RC pixel'),
          (5, 32, 'REFERENCE_PIXEL', 'Reference Pixel')],
         dtype=[('BIT', '<i4'), ('VALUE', '<i4'), ('NAME', 'S40'), ('DESCRIPTION', 'S80')])
```
So as you can see, there's nothing the MASK reffile with NON_SCIENCE.

**Comment by hbushouse** [comment]
Or they're producing simulated raw files that already have flags set in the PIXELDQ extension.

**Comment by hbushouse** [comment]
According to @cracraft the NON_SCIENCE flags are currently located in some of the FLAT reference files, so that's where they get propagated into the science products.

**Comment by hbushouse** [comment]
I would guess that the answer is no. I would think we'd need unique NON_SCIENCE maps based on EXP_TYPE. I'm sure the team will not want to create FLATs for different EXP_TYPEs for every combination of FILTER, READPATT, and SUBARRAY. Hence it would be much simpler to implement these in the MASK files, where you'd only need a few reference files for the MIRIMAGE detector.

**Comment by cracraft** [comment]
@jemorrison @macagm What do you think about this question?

**Comment by cracraft** [comment]
The MIRI team actually already provides FLAT files for each combination of Filter, Readpatt and Subarray, so that's not an issue at this point. We are going to discuss with the wider MIRI team about whether we want to somehow flag the Lyot portion of the Imager between stage 2 of the pipeline and stage 3 so it is not part of any mosaic combination.

**Comment by hbushouse** [comment]
The most recent comments added to https://jira.stsci.edu/browse/JP-164 indicate that the MIRI team has supplied FLATs for the imaging detector that correctly label appropriate pixels with DQ=NON_SCIENCE for all the MIR_IMAGE, MIR_LRS-FIXEDSLIT, MIR_LRS-SLITLESS, and MIR_CORON modes, so we now need to make sure that all downstream pipeline steps, like `tweakreg` and `resample`, are looking for these DQ flags and excluding those pixels.

**Comment by jdavies-st** [comment]
Resample currently respects NON_SCIENCE.
