### ISSUE TITLE
no valid pixels on input image

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2095]
# Issue

Running calwebb_spec3 on simulated 3-nod NIRSpec MSA data, the following occurs:

```
ValueError: no valid pixels on input image
```

# Resources
The dataset in question can be found in
```
/grp/jwst/ssb/eisenhamer/simulated-3nod
```
The notebook `calibrate.ipynb` has the full record.  Note that this is running on only two of the three nods of the simulation.  And, as with any simulation, the issue could be the data itself.

- Produced from trying to reproduce #1005.
- Same setup and data as #2094.

**Comment by hbushouse** [comment]
Please retest using B7.8 to see if the problem persists.

**Comment by stscieisenhamer** [comment]
At this point, if the issue hasn't reared its ugly head with all the real data, I call this defunct.
