### ISSUE TITLE
Add information about ASDF and Reference files

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2104]
After some discussion about how to create reference files with respect to information that is also in ASDF, it would be helpful to add some information about accessing the history of ASDF and how to use that with the creation of reference files. 

For reference, some of this was discussed in https://jira.stsci.edu/browse/CCD-81

**Comment by melanieclarke** [comment]
Closing this ticket, since the documentation has evolved quite a bit since it was filed.  If there are still specific issues with documenting ASDF and reference files, please open a new ticket.
