### ISSUE TITLE
Migrate material from old trac site

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2118]
There still is old material and planning information located at:
https://aeon.stsci.edu/ssb/trac/jwst

This material should either be migrated to the repository documentation or confluence, and the material at the trac site should be archived

**Comment by stscieisenhamer** [comment]
Material has been migrated by @bernie-simon to the [SCSB Innerspace](https://innerspace.stsci.edu/display/SCSB/Archive+of+the+CAL+JWST+SSB+Project+Pages). 

In email discussion, it was decided to leave any incorporation of the material to specific issues and projects (see #2159).
