### ISSUE TITLE
skip invalid entries in the msa metadata file

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2143]
DMS encountered the following case

```
 (19,  1, 2, 244, 128, 71, 'N', 'OPEN',   5.60144603e-01,  0.05962159),
 (19,  1, 2, 244, 129, 18, 'N', 'OPEN',   1.59281224e-01,  0.15467094),
 (19,  1, 2, 244, 130, 18, 'Y', 'OPEN',              nan,         nan)
```
There are two shutters in this slitlet for which background is 'N'.  There should never be a case with more than one shutter with background=='N' since this is the main shutter of the slitlet. This will eventually be fixed upstream. Currently the pipeline raises an error and stops processing. The INS team is suggesting we issue a warning, skip the slitlet and continue processing.

**Comment by hbushouse** [comment]
The NIRSpec team has created a new version of the APT program that gave rise to the unexpected conditions seen in the MSA meta data file above, along with adding examples of dedicated background shutters. Folks in SDP are working on getting the updated APT file processed through PPS and SDP to generate a new MSA meta data file, from which we should be able to finally determine how to handle these situations.

**Comment by hbushouse** [comment]
Closing, because it's been superseded by #2653.
