### ISSUE TITLE
Update JDOCS page

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2208]
The JDOCs page is currently being updated and this is just an issue for tracking that progress.   It is currently under review and this should be closed once it is completed and updated with information about the installation of the package.

**Comment by hbushouse** [comment]
Is this regarding the JIRA ticket https://jira.stsci.edu/browse/JP-327, which is requesting updates to the JDox page that describes the installation procedures for the calibration pipeline software?

**Comment by stscicrawford** [comment]
Closing as a duplicate of #2150
