### ISSUE TITLE
Simplifying Data Model Validation

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2209]
The current validation in the data model limits what can be done by a user especially in post pipeline usage of the data.   If the JWST data model is meant for use after the pipeline, we should review the validation required and the strictness of the data model schema.   This issue is a catch all for that discussion.

**Comment by hbushouse** [comment]
Any interest in starting or continuing discussion of this issue?  Otherwise let's close it.
@nden @jdavies-st @eslavich @stscieisenhamer

**Comment by jdavies-st** [comment]
No.  I think there's plenty of specific issues and specific optimizations that can be discussed.  This particular issue never caught on.
