### ISSUE TITLE
Remove stepsize column from drizpars reffile

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2217]
The parameter `stepsize` is a holdover from drizzlepac and is not used with the GWCS drizzling interface.  It should be removed.

While we're at it, some other modifications can be done as well. 

- [ ] remove `stepsize` column
- [ ] Define the dtype in the columns that contain strings so that strings are returned in the datamodel.  Currently `np.byte_` instances are returned.  Currently they are `[ascii, 10]`.
 - [ ] Specify `fillval` as 0.0 instead of INDEF.  INDEF is a carryover from IRAF an no longer has any meaning in python or C.

This involves schema modification and delivery of a new reffile to CRDS.

**Comment by braingram** [comment]
Closing as drizpars is no longer supported:
https://github.com/spacetelescope/jwst/pull/8546
and `stepsize` is not in the resample spec:
https://github.com/spacetelescope/jwst/blob/de39de07b6f0380860caa86e8485666b4cef35c2/jwst/resample/resample_step.py#L42
