### ISSUE TITLE
Remove JWST-specific WCS header keywords from resampled FITS files

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2225]
Based on discussions in PR #2222, we should remove the following keywords once they are no longer relevant to the data, i.e. after an image has been resampled and it is given a standard FITS WCS:

V2_REF
V3_REF
RA_REF
DEC_REF
ROLL_REF

That way there is no confusion as to whether these keywords still apply to the resampled file or not (they don't).

**Comment by nden** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2039](https://jira.stsci.edu/browse/JP-2039)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2039?focusedCommentId=525031#comment-525031):_

Fixed by #5971 for resampled 2D images. 3D IFU cubes will be handled in a separate PR.
