### ISSUE TITLE
Disperser Reference FIle description

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2227]
From [assign_wcs reference file](https://github.com/stscicrawford/jwst/blob/master/docs/jwst/assign_wcs/reference_files.rst), the second sentence was removed from the Disperser reference file description:

The disperser reference file contains reference data about the NIRSPEC dispersers (gratings or the prism). The reference data is described in the NIRSPEC Interface Control Document.

The information for describing the reference file data should be added from the document into the reference_files.rst file.

**Comment by nden** [comment]
fixed in #2216
