### ISSUE TITLE
Explanation of rmaps

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2228]
@sosey suggested that a user friendly explanation of rmaps and how they can be read should be added to the JWST pipeline documentation:

I don't see it mentioned, but perhaps putting in a sentence somewhere in the docs about how to read the current rmap that tells you what is being selected on would be useful? If it's in the CRDS docs we can link back there.

These are the crds docs: https://jwst-crds.stsci.edu/static/users_guide/rmap_syntax.html#reference-mappings-rmap, we should link there but also consider adding a short description somewhere that simplifies how to read them for users that just wonder what they mean.

**Comment by jaytmiller** [comment]
Looking at a pull request for this,  I had two issues:

1.  I wasn't able to do this in a sentence so I may be adding wildly too much stuff.

2. Reflexively,  I branched off of master and am now unsure where to merge this (theoretically) B7.2 change.

As an aside,  I noticed that Howard's recent spate of docs updates are also going into master.

These changes are well contained so it's no problem backing up and branching/merging correctly,  I just wasn't sure what "correct" is for these.

**Comment by jaytmiller** [comment]
Mentioning @nden and @hbushouse

**Comment by nden** [comment]
@jaytmiller master is fine. All doc updates are going on master.

**Comment by stscicrawford** [comment]
Closed with #2717
