### ISSUE TITLE
WAVE-TAB functionality 

### ISSUE THREAD

**Issue by jemorrison** [spacetelescope/jwst#2235]
We need to be able to create IFU Cubes with a  non-linear wavelength dimension. This  can be accomplished by using the FITS standard WAVE-TAB ( a separate extension table that contains the wavelengths of each slice) see https://www.aanda.org/articles/aa/pdf/2006/05/aa3818-05.pdf   for details.  Though it is a FITS standard astropy does not understand a WCS with a WAVE-TAB extension table.  The wrappers around the wsclib c code that astropy needs does not include the WAVE-TAB functions. In order to get the JWST pipeline to create and read  non-linear wavelength sampling  represented by the WAVE-TAB we (Nadia, Craig, Jane and Steve) have come up with the following plan: 

[ ] 1.  Modify GWCS to understand this type of data. 

[ ] 2. Add hooks into astropy so that when this type of data is encountered it will use GWCS instead of going through the wcslib.

* Note: though out of scope for a github issue we want to encourage the DS9 developers to be able to read WAVE-TAB data.

**Comment by stscicrawford** [comment]
Just as a note, the latest release of ds9 is suppose to be able to handle the wave-tab functionality. It might be useful to test against the files created.

**Comment by stscicrawford** [comment]
Functionality added to data models in #2350

**Comment by mcara** [comment]
[`gwcs.WCS.to_fits_tab()`](https://gwcs.readthedocs.io/en/latest/api/gwcs.wcs.WCS.html?highlight=to_fits_tb#gwcs.wcs.WCS.to_fits_tab) could be used to simplify generation of `-TAB` FITS WCS.

**Comment by hbushouse** [comment]
What's the status of this? I know `cube_build` is now producing FITS products using `WAVE-TAB`. Is it doing that using the gwcs method mentioned above? Can this be closed and a separate ticket filed against astropy to make future changes there?

**Comment by mcara** [comment]
To the best of my memory, `cube_build` is not using `gwcs`'s [`gwcs.WCS.to_fits_tab()`](https://gwcs.readthedocs.io/en/latest/api/gwcs.wcs.WCS.html?highlight=to_fits_tb#gwcs.wcs.WCS.to_fits_tab) to produce `WAVE-TAB`. Instead. I believe, it uses custom code. In our tag-up we have discussed with @jdavies-st that it would be a good idea to remove custom code (if possible) and switch to using the above mentioned method.

Maybe a new ticket should be opened agains the `jwst` pipeline but not `astropy`.

**Comment by jemorrison** [comment]
cube_build is not using the gwcs method to make the WAVE-TAB output.

**Comment by jdavies-st** [comment]
We should keep this open.

It is related to the ticket https://github.com/spacetelescope/jwst/issues/2685 for 2D spectral data.  The solution for both of these tickets is using `astropy` support for WAVE-TAB in 4.1 and `gwcs.WCS.to_fits_tab()` for WAVE-TAB output.

**Comment by jdavies-st** [comment]
But to be clear, the `astropy` and `gwcs` work is already done.  Thanks @mcara !

We only have to use those convenience methods in `jwst` now.

**Comment by jdavies-st** [comment]
@stscijgbot-jp

**Comment by jdavies-st** [comment]
The `astropy` and `gwcs` work has been completed.

Use issue https://github.com/spacetelescope/jwst/issues/2235 to track the work needed in `cube_build`.

**Comment by hbushouse** [comment]
> The `astropy` and `gwcs` work has been completed.
> 
> Use issue #2235 to track the work needed in `cube_build`.

This *IS* 2235, which has now been closed. Did you mean #5628 ?

**Comment by jdavies-st** [comment]
Doh!  Yes.  https://github.com/spacetelescope/jwst/issues/5628

☕ ☕
