### ISSUE TITLE
Improve datamodels.open() for missing DATAMODL

### ISSUE THREAD

**Issue by jaytmiller** [spacetelescope/jwst#2248]
When it is defined,  the DATAMODL keyword provides an excellent method of choosing an appropriate model class to construct for any given FITS file.

However,  a sizable number of legacy references and/or data do not define DATAMODL.  In these cases,  particularly for reference files,  the guess made by the datamodels may be poor.

For those instances where datamodels.open() is guessing,  **consider issuing a warning**.   

If the guesses are reasonable for science data,  it may be necessary to differentiate reference files (using REFTYPE?) to avoid spurious warnings.

It may be useful to hint at better practices for opening files in the warning message.   Something like:

WARNING:   DATAMODL keyword not present.  Guessing datamodels class [class.__name__] for [filename].  If you are creating or opening a reference file, consult [documentation link] to help open an explicit datamodels class corresponding to your file.

An alternative approach to adding a warning would be to build in a "better guesser" which can functionally replace the DATAMODL keyword.

**Comment by stscicrawford** [comment]
cc @mfixstsci

**Comment by bernie-simon** [comment]
The warning added to the generic open satisfies the original request, so I am closing this issue.
