### ISSUE TITLE
Reference file doc updates for models and keywords

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2257]
The reference file docs included with each step doc should be updated to include a few additional pieces of information:
1) The name of the corresponding data model that goes with each ref type (e.g. DarkModel, LinearityModel).
2) The list of required keywords for each ref type, which are contained in the schema for each reffile data model.

**Comment by philhodge** [comment]
Should we have a boilerplate section for this?  A common heading and style would make it easier to find the information.

**Comment by philhodge** [comment]
Regarding the required keywords, do you want the FITS keyword name or the model name?  That is, DETECTOR or meta.instrument.detector, for example?

**Comment by hbushouse** [comment]
It wouldn't hurt to have both the model name and FITS keyword name. Folks who are creating a reffile data model from within python will want to populate the meta via the model names.

**Comment by hbushouse** [comment]
Updates for this issue are being included in the work done for #2675, which is a more general update to all reference file documentation.

**Comment by hbushouse** [comment]
Closing this issue, because all of the work was done under #2675 and is now complete.
