### ISSUE TITLE
Write out pathloss extensions based on source type

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2260]
As discussed with @stscirij and @jdavies-st :
When the pathloss step was written there was no information about the source type in the pipeline and so the step writes out the extensions for point and extended sources. Now this information is available and the step can decide which extensions to write out based on that.

**Comment by hbushouse** [comment]
I believe that in the original request from the instrument team they wanted to have both forms of the correction attached to the product, one of which would be applied by the pipeline. But having them both available then makes it possible for a user to go back and apply the other one (i.e. they decide that the pipeline determination of the source type was not accurate) without having to recompute the correction. But this may also hinge on decisions that need to be made in the near future, by the CalWG and instrument teams, as to how/when/where the corrections get applied in the pipeline flow (i.e. it may end up being impossible to apply the other form of the correction without rerunning the whole pipeline anyway).
