### ISSUE TITLE
All datamodels should have a .data member

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2267]
Datamodels are set up to have a `primary_array` that points to `data`.  This means that every datamodel should have a `data` attribute.  Not all do.

Currently `MultiSpecModel` does not.  Perhaps there are others too.

Instead of
```
for spectrum in model.spec:
    print(spectrum.spec_table['columns'])
```
it should be
```
for spectrum in model:
    print(spectrum.data['columns'])
```
This will be more intuitive for users and make it easier to navigate the multitude of datamodels used in this package.

I recently changed `DrizParsModel` from `DrizParsModel.driz_table` to `DrizParsModel.data` for this reason.  It required changing the attribute name, the name in the schema and code within the pipeline that used this datamodel.

**Comment by jdavies-st** [comment]
Thanks Phil.  I hadn't thought of the ASDF models where the primary data type can often be a `dict` or `OrderedDict` instead of some numpy object.  I suspect @nden has many of these in the reference files for building the WCS models.

**Comment by jdavies-st** [comment]
I'll add that there's often (always?) a `data` attribute in `astropy.NDData` as well, so this is a nice consistency between the two abstract datamodel classes.

**Comment by nden** [comment]
`data` in asdf is reserved for a ndarray (not saying it's good or bad, it just is).
And yes, there are many models which don't contain a data array.

**Comment by drdavella** [comment]
@nden we actually removed this restriction in version 1.1.0 of the ASDF core schema.

**Comment by nden** [comment]
Ah, yes. Thanks!

**Comment by bernie-simon** [comment]
Models are not required to have a data array and if they do, it is not required to be named 'data'. This is simply the default. If a model does not have a data array, it should overload the method get_primary_array_name and return the value None. If it has a data array with some different name, then get_primary_array_name should return that name.

After reviewing the code, I see that NDModel integration handles this incorrectly and I will be fixing this problem.

**Comment by jdavies-st** [comment]
If a datamodel does not have a `data` attribute, then the yet-to-be-implemented `info()` method should use the `get_primary_array` to specify what that member is called.

**Comment by bernie-simon** [comment]
The purpose of get_primary_array is to define the shape of an image datamodel as the shape of the array it names. It wasn't needed by info().  The data property, which was added to datamodels for astropy.NDData compatibility, now calls get_primary_array_name(), so you can access the primary array through the data attribute when it is defined, which it should be for any image class.

No further work is anticipated on this issue, so I am closing it.
