### ISSUE TITLE
datamodels should have a .info() method

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2268]
It is currently difficult to introspect an open `datamodel`.  In fact it is much easier to find out what is in a JWST FITS file by just running the `fitsinfo` at the command line:
```
> fitsinfo nrs1_fs_s2d.fits 
Filename: nrs1_fs_s2d.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     299   ()      
  1  SCI           1 ImageHDU        40   (1382, 31)   float32   
  2  WHT           1 ImageHDU         9   (1382, 31)   float32   
  3  CON           1 ImageHDU         9   (1382, 31)   int32   
  4  RELSENS       1 BinTableHDU     15   101R x 2C   [D, D]   
  5  SCI           2 ImageHDU        40   (1465, 31)   float32   
  6  WHT           2 ImageHDU         9   (1465, 31)   float32   
  7  CON           2 ImageHDU         9   (1465, 31)   int32   
  8  RELSENS       2 BinTableHDU     15   101R x 2C   [D, D]   
  9  SCI           3 ImageHDU        40   (1451, 36)   float32   
 10  WHT           3 ImageHDU         9   (1451, 36)   float32   
 11  CON           3 ImageHDU         9   (1451, 36)   int32   
 12  RELSENS       3 BinTableHDU     15   101R x 2C   [D, D]   
 13  SCI           4 ImageHDU        40   (1427, 15)   float32   
 14  WHT           4 ImageHDU         9   (1427, 15)   float32   
 15  CON           4 ImageHDU         9   (1427, 15)   int32   
 16  RELSENS       4 BinTableHDU     15   101R x 2C   [D, D]   
 17  ASDF          1 BinTableHDU     11   394824R x 1C   [B]   
```
The `astropy.io.fits` library has an `info()` method for introspecting an `HDUList`.  We should have something similar in datamodels to give a layout of the datamodel - its arrays, tables, if it's a container of slits (such as `MultiSlitModel`) info about each slit, etc.

This `info()` method would make it much easier for users to find what they need in our datamodels.

**Comment by bernie-simon** [comment]
The info method has been added, so I am closing this issue.

**Comment by jdavies-st** [comment]
Reopening this issue as the current `info()` method doesn't work for `MultiSlitModel` or `ModelContainer` and it returns a stream for all other models, which is not ideal.  And since `info()` doesn't have any parameters, it's not clear it needs to be a method rather than a property.

**Comment by jdavies-st** [comment]
Also, the ordering of array sizes in `info()` is FITS order (x, y), not python order (y, x).  This will just cause confusion.  it should be changed to be consistent with python.

**Comment by nden** [comment]
There's similar work done in asdf and datamodels should use it if possible. Tagging @drdavella to keep everyone in the loop.

**Comment by jdavies-st** [comment]
Ooh, nice!  I would be happy to coordinate or just use the `asdf` methods.

**Comment by stscicrawford** [comment]
Instead of re-opening this issue: 
- can you instead make a new issue with a bug report?   
- Open another issue with the requested enhancement changes? 

I believe this was working previously, so this is new problems or features that have emerged.

**Comment by jdavies-st** [comment]
It was never working previously.  It's always been broken.  I never had a chance to review the PR that closed this.  I'm happy to open a new issue though.
