### ISSUE TITLE
Rename integration time keywords for start, middle, end

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#2274]
The `extract_1d` step can copy the times at the beginning, middle, and end of each integration from the INT_TIMES table to keywords in the headers of the output 1-D extracted spectra.  The current set of keywords is not consistent with the recommendations of FITS Paper IV, however.  The keywords should therefore be renamed.  Specifically, keywords TIMESYS = 'UTC' and TIMESYSB = 'TDB' [no; see the comment added on Jan 24, 2019] should be added to the headers for extracted spectra, and these keywords should be renamed:

current | renamed
-------- | --------
STRT_UTC | MJD-BEG
MID_UTC | MJD-AVG
END_UTC | MJD-END
STRT_TDB | MJD-BEGB
MID_TDB | MJD-AVGB
END_TDB | MJD-ENDB

Thus, the primary coordinate system uses time scale 'UTC', and alternate coordinate system "B" uses time scale 'TDB'.

**Comment by stscicrawford** [comment]
Related to #917

**Comment by philhodge** [comment]
After some discussion it was decided to not use keyword TIMESYSB, and to use the following keyword names for time scales UTC (same keywords as above) and TDB:

current | renamed
-------- | --------
STRT_UTC | MJD-BEG
MID_UTC | MJD-AVG
END_UTC | MJD-END
STRT_TDB | TDB-BEG
MID_TDB | TDB-MID
END_TDB | TDB-END

**Comment by hbushouse** [comment]
Fixed by #3058
