### ISSUE TITLE
assign_wcs.get_open_slits failure

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2321]
This bug was discovered when running the Nirspec testing tool.

```
slits_list = nirspec.get_open_slits(img)
...
> msa_config = reference_files['msametafile']
E TypeError: 'NoneType' object is not subscriptable
```
The code needs to catch a `TypeError`.

**Comment by jdavies-st** [comment]
Ah, that looks like a bug I introduced when fixing another bug in PR #2073.  Doh!

Is the file a non-MSA NIRSpec file?

**Comment by nden** [comment]
It is an MSA  file. The code was catching a KeyError while a TypeError was raised and so it missed it.
