### ISSUE TITLE
DOC: RTD is choking again

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#2323]
https://readthedocs.org/projects/jwst-pipeline/builds/7575838/

FYI

**Comment by pllim** [comment]
Again. For the past 5 days. https://readthedocs.org/projects/jwst-pipeline/builds/7735066/

**Comment by jdavies-st** [comment]
The build log is completely unhelpful.  Hmm.

**Comment by pllim** [comment]
Did you add any new dependencies? Looks familiar.

**Comment by pllim** [comment]
I feel like it is unproductive for RTD to spam me when this fails, as I cannot do anything about it. Please name a tribute to take charge of documentation from your team. Thanks.

**Comment by drdavella** [comment]
Use the heimlich!

**Comment by pllim** [comment]
Dan, did you just volunteer? What is your RTD username? 😄

**Comment by jdavies-st** [comment]
Does anyone in the `jwst` project know anything about RTD?  How are we supposed to debug if there's no log of the build accessible?

@nden @sosey any insight here?

**Comment by stscicrawford** [comment]
@pllim -- For the time being, make me admin and then we will find someone responsible from there

**Comment by sosey** [comment]
I think those with package rights can see the build file. If you have an RTD account we (the people with the spacetelescope user access) can add you to the package

**Comment by pllim** [comment]
I can't remove myself. Someone please remove me at https://readthedocs.org/dashboard/jwst-pipeline/users/ Thanks.

**Comment by stscicrawford** [comment]
Closing this as Read the Docs is now working, but @rendinam is looking at why the SSB channel and Read the Docs are not working with each other.
