### ISSUE TITLE
Use a better algorithm for finding the dispersion direction

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#2344]
Function `combine_fast_slow` in flat_field.py combines a flat-field image (the part that varies slowly with wavelength) with tabulated values (the fast variation with wavelength).  This function averages the tabulated values as a function of wavelength over each pixel, and the function needs to know the dispersion direction in order to determine the wavelength interval for each pixel.  The dispersion direction only matters if the dispersion is non-linear, so getting the dispersion direction wrong will usually not have a large effect on the results.  Nevertheless, the current algorithm for finding the dispersion direction needs to be improved because it sometimes fails due to NaNs or zeros in the array of wavelengths.

**Comment by jdavies-st** [comment]
You might use something like `np.nanmedian(wl, axis=N)` to get a median across a slice for N=0,1.

Or base it on the shape of the bounding box?  Spectral dimension is always much longer than the slit.

**Comment by philhodge** [comment]
Those are good suggestions, thanks.  I was using nanmean of the difference arrays for an offset in x and for an offset in y, but I think you're right, nanmedian would be better.  I would rather not make an assumption about the shape of the bounding box, though it's probably safe.  Eventually I think the dispersion direction should be a metadata value, or an attribute of the wcs.

**Comment by nden** [comment]
I miss `dispaxis` from HST.

**Comment by stscicrawford** [comment]
Was there a reason `dispaxis` was not included?  It might be reasonable to request to have it included.

**Comment by stscicrawford** [comment]
@philhodge Can you include an example data set that this fails on?  I think that would make it easier for anyone to pick up this issue at some point.

**Comment by stscicrawford** [comment]
Closed with #2492 merged
