### ISSUE TITLE
What is the purpose of flatten_combiners?

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/jwst#2375]
The function `jwst.datamodels.schema.flatten_combiners` appears to be causing some failures for specific cases of schema validation via `asdf` and `jsonschema`. More specifically, it causes failures when attempting to use `anyOf` or `oneOf` to specify multiple possible types for a node in the schema when one of the possible types is itself a complex type (such as `array` or `object`).

Before I dig deeper and try to understand if and/or how the function can be fixed, I'm trying to find out why it's necessary at all. Why is it necessary to modify schemas that are used by `asdf` for validation instead of passing them as-is?

FWIW, eliminating all use of `flatten_combiners` fixes the bug I am trying to fix, but I have not yet run the `jwst` test suite with this modification.

**Comment by bernie-simon** [comment]
I believe the point of flattening the schema is to make it easier to traverse. Combiners like anyOf or oneOf are non-physical and we would like the schema to only represent physical quantities, mostly the contents of the FITS file.

**Comment by drdavella** [comment]
Okay, then I'll do some more investigation into this issue. The problem is that in certain cases the original intent of the schema is not being preserved by `flatten_combiners`, which means that some well-formed schemas fail to accept valid files. This might just be an edge case in `flatten_combiners` which needs to be addressed, although I still question the logic of blindly removing valid JSON Schema keywords from schemas.

Alternatively, maybe certain schema constructions that are legal according to the JSON Schema standard are simply not acceptable in the context of JWST data models? But that seems unsatisfying. (cc @sosey)

In any case, it's clear that `flatten_combiners` has some non-trivial effect since removing its use causes a variety of failures in the test suite.

**Comment by jdavies-st** [comment]
Looking at the code, it seems very likely that there are some edge cases.

https://github.com/spacetelescope/jwst/blob/c2f253ebf256cf218bc7a2b0e19151dd577b5fd2/jwst/datamodels/schema.py#L215-L220

But yeah, converting allOf and anyOf to lists seems to be its function, though you say it is not doing it correctly for complex object types?

**Comment by drdavella** [comment]
I'm beginning to think that this is actually a fairly serious bug that affects the validation behavior of multiple schemas in `datamodels`. The tl;dr is that anywhere that `anyOf` is used in a schema, the corresponding field will not be properly validated. The consequence is that when files contain invalid values in these fields, it will not be detected.

My current feeling is that ideally `flatten_combiners` should not be used since it is destructively modifies schemas. I will open a PR presently that eliminates use of `flatten_combiners` so that we can try to determine whether/how the resulting test failures can be addressed.

**Comment by sosey** [comment]
@jdavies-st yah, this is related to the failures from the updated schemas I submitted for https://github.com/spacetelescope/jwst/pull/2286

**Comment by drdavella** [comment]
I'm wondering if the intended purpose of `flatten_combiners` is actually `merge_properties`. That is, it seems to take the property trees from multiple schemas (that are included using `$ref`) and to merge all `properties` at each level in order to create a single tree.

If that's the case, then maybe it can leave `anyOf` and `allOf` alone, or at least merge them properly. It seems like there should be a way to achieve the same effect purely with JSON Schema as well, but it may require pretty substantial changes to the schema files at this point.

I'm going to add a test case for the bug that @sosey exposed, and then see if I can fix `flatten_combiners` (and maybe rename it).

**Comment by sosey** [comment]
:laughing:  I am the Breaker of Things! http://gph.is/1DnqQZY

**Comment by bernie-simon** [comment]
Since flatten_combiners has been removed from datamodels, I am closing this issue. If new problems are discovered, they will be addressed in a separate issue.
