### ISSUE TITLE
Migrate test data to artifactory

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2391]
Now that artifactory is set up and running, the JWST test data should be migrated over to the artifactory and use the new [CI infrastructure](https://github.com/spacetelescope/ci_watson) for the regression tests.

**Comment by stsci-hack** [comment]
A new directory has been set up to serve as a LOCAL 'repo' for the input and truth data for the JWST regression tests; namely, 
    /grp/jwst/ssb/rt-artifactory

This directory can be set up with the same structure that will be used on artifactory to insure that all the regression/unit tests for JWST will work.  This whole tree can then (in one command) be uploaded to artifactory to make the final move.  The 'jwst-pipeline' repo has already been established on Artifactory for these tests to use once we identify the initial set of files which are needed to support the currently run regression tests.

Anyone who manages JWST regression tests should be able to help move just the data needed for the tests to this directory and contribute to the discussions about how best to organize the data.  Please see the 'drizzlepac' and the 'datb-stistools' repos on Artifactory already for examples of how this data can be organized.

**Comment by stscicrawford** [comment]
Closed with merging of #2665
