### ISSUE TITLE
Add regression test for #2342

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2392]
A regression test is still need to be added for #2342 : Adjust TPCorr to work with V2, V3 angles in arcsec instead of degrees

**Comment by mcara** [comment]
The code for converting spherical angles to Cartesian coordinates and back to spherical was moved to `gwcs` and is fully tested that it works correctly with different units.

What was left in the `tweakwcs` package is the code that calls `gwcs` models and [converts input `v2`, `v3` angles to degrees (from assumed `arcsec`)](https://github.com/spacetelescope/tweakwcs/blob/c11892669707270a96071f2a22b0819ebc4e343b/tweakwcs/tpwcs.py#L714-L745). I do not how to [specifically] test that this assumption about some arbitrary numbers, the assumption that they _represent_ angles in `arcsec`, is correct. It is up to the caller to make sure they pass numbers that represent angles in `arcsec`.

Indirectly, this is tested, for example, in https://github.com/spacetelescope/tweakwcs/blob/master/tweakwcs/tests/test_multichip_jwst.py by creating a simulates JWST WCS that uses `arcsec` for `v2, v3` angles and then testing that `tweakwcs` can recover simulated mis-alignment. [`tweakwcs` would not produce correct results if assumption about `v2, v3` units were incorrect.]
