### ISSUE TITLE
Add Windows job to Travis CI?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#24]
You know, for Windows.

**Comment by jhunkeler** [comment]
I'll get around to porting our recipes to Windows this year (hopefully). Until then I'm not sure we can implement Appveyor.

**Comment by pllim** [comment]
Even if it currently breaks in Windows, it is still possible to get Appveyor account set up any hooked up, right? Anyways, just a thought. I mean, who in the right mind would try to process JWST data on Windows, huh? :wink:

**Comment by hbushouse** [comment]
Who indeed. Oh wait, you did say "in their right mind".

**Comment by jhunkeler** [comment]
I activated Appveyor's webhook the other day but ended up removing it. It added several minutes the PR checks but was never going to succeed given the lack of (our) recipe support for Windows. 

`jwst` has a very long dependency chain.

**Comment by pllim** [comment]
Huh, I was under the impression that you can still have the hook there but just deactivated by unchecking the box below? Never mind if it is too much trouble. I think we should just keep this open until details are finalized in the future. Thanks!

![screenshot](https://cloud.githubusercontent.com/assets/2090236/16208101/86057c3a-36fe-11e6-9e9b-6e66e90faa58.png)

**Comment by jhunkeler** [comment]
Ah, I didn't see this last time because I clicked the :x: instead of the :pencil2:.
I just restored the Appveyor project and disabled the webhook for the time being.

**Comment by pllim** [comment]
@drdavella , does it have queue problem like Mac builds?

**Comment by drdavella** [comment]
Mac builds haven't been a problem on Travis for a long time now. And it is way faster than Appveyor for Windows builds.

**Comment by pllim** [comment]
OK, I changed the title.
