### ISSUE TITLE
Final_IFUCube not used?

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2400]
There is a reference to Final_IFUCube that does not seem set anywhere else:

https://github.com/spacetelescope/jwst/blob/b7284ab11d582e69adb54282daada66c511092ef/jwst/cube_build/cube_build_step.py#L282

**Comment by hbushouse** [comment]
Related to #2397

**Comment by stscieisenhamer** [comment]
Resolved by #2402
