### ISSUE TITLE
regression test failure due to SOSS now allowed to be non-TSO

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2409]
# Issue
@hbushouse reports:

> The reg test test_nirisssoss2pipeline1 recently started throwing an error because it can’t find the output _calints.fits product on which to do the comparison. It appears that a recent change has caused the outputs to be _cal.fits (and _x1d.fits), instead of _calints.fits (and _x1dints.fits). Something to do with a recent change somewhere or the fact that the input is a _rate.fits instead of _rateints.fits?

# Resources
- [Failed test](https://boyle.stsci.edu:8081/job/RT/job/JWST/234/testReport/junit/jwst.tests_nightly.general.niriss/test_nirisssoss2_pipeline/test_nirisssoss2pipeline1/)

# Notes
Most likely due to #2330, where NIS_SOSS was removed from the permanent TSO list.

# Question
Is this test supposed to be testing TSO data? If so, the header keyword TSOVISIT needs to be set `T` and the input should be `rateints`.

**Comment by hbushouse** [comment]
Yes, investigation of the data set in use shows it to be a bad test. The jw00034001001_01101_00001_niriss exposure is NIRISS SOSS mode, but NINTS=1, so it doesn't represent a multi-integration exposure. Hence the pipeline is actually now treating it correctly by not creating any "ints" type products. Guess we need to find a more appropriate data set for use with this test.

**Comment by stscieisenhamer** [comment]
Resolved by #2421.
