### ISSUE TITLE
Apply JWST velocity correction to WFSS modes

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2420]
Similarly to #2406 append the velocity correction at the end of the wavelength computation for these modes.

**Comment by stscicrawford** [comment]
This should include NIRISS SOSS mode as well.

**Comment by nden** [comment]
NIRISS SOSS is done already. Only the modes that @sosey implemented need to be updated.

**Comment by sosey** [comment]
Has this been discussed with @NorPirzkal or the niriss team?  Wavelength computation for WFSS modes already includes some measure of distortion, and fitted from the observed trace location I believe, I'm not sure that the proper place to put this correction is directly after traversal of the trace polynomials or directly on the wavelength entered by the user (and just before it's returned in the forward direction?

**Comment by stscicrawford** [comment]
This was a request from Kevin Volk on https://jira.stsci.edu/browse/JP-245

**Comment by nden** [comment]
Fixed in #2801
