### ISSUE TITLE
Reference file documentation

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2435]
The new reference file documentation should includes links from the index.rst 

@hbushouse: 

The file /docs/jwst/reference-file-formats-documentation.rst included in this commit is not showing up anywhere in the as-built docs, because it's not included in any index file anywhere. It should be added to either the /docs/index.rst file, if you want it to appear at the top level along with the introduction and package index, or the /docs/jwst/package_index.rst file, so that it shows up along with all the other step/pipeline level docs. And while we're at it, /docs/jwst/package_index.rst should be updated to remove the old and now obsolete file "ref_file_doc_DMS_653/index.rst", which was compiled a couple years ago just to act as a deliverable to satisfy the level 4 requirement DMS-653. We can keep the actual doc file - just don't include it in the package index. It has old and conflicting information relative what's in the rest of the current docs.

**Comment by jaytmiller** [comment]
I added this in my upcoming make-it-so pull request as the references_general "package" so I could easily find it while linking to it from the includes/standard_keywords.rst include file.

**Comment by hbushouse** [comment]
The original problematic file mentioned above (/docs/jwst/reference-file-formats-documentation.rst) was subsequently morphed into the whole new structure of reference file documentation contained under /docs/jwst/references_general/. Hence the original problem is gone and this is no longer an issue.
