### ISSUE TITLE
Running the unit tests

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2437]
It would be useful to add documentation from the perspective of a user of the package about how to add, examine, and run the unit tests.

**Comment by hbushouse** [comment]
@stscijgbot

**Comment by jdavies-st** [comment]
This is already in the README.  Anything further we should add?

https://github.com/spacetelescope/jwst#unit-tests

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2159](https://jira.stsci.edu/browse/JP-2159)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2159?focusedCommentId=534544#comment-534544):_

That entry in the README simply provides info on how to setup your local branch to be able to run unit tests, but doesn't describe how to create or add unit tests, like we have in the Wiki for regression tests. Perhaps we could add a similar section to the Wiki that specifically addresses unit tests.

**Comment by jdavies-st** [comment]
Adding unit tests really just requires people to read the pytest docs.

https://pytest.org

Nothing more to it.  Do we need anything else?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2159?focusedCommentId=534563#comment-534563):_

Probably not.

**Comment by jdavies-st** [comment]
I mean, it's as simple, and as complex, as that.  😂 

I don't think reading the `jwst` docs will or can be the equivalent of lots of experience writing tests, or even the equivalent of taking an O'Reilly online course on `pytest`.  But both are better than anything we could write in the `jwst` docs.
