### ISSUE TITLE
Disallow known optical paths that produce no data on NIRSpec NRS2 detector

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2440]
# Issue
There are known optical paths for NIRSpec where there will be no data on the NRS2 detector. Modify the Level2/Level3 rules as needed to not include exposures that fall in this category.

# Resources
From [this comment](https://github.com/spacetelescope/jwst/issues/2336#issuecomment-412113876) in #2336:

> So, the reverse then, is the cases we know that will not have NRS2 as listed in #2151. Note that this discussion is specific to actual science; all the calibration-type exposures are already handled in their own ways, for example see #1188.

# Notes
With the resolution of #2336, which handles both this situation and others where the Level2 calibration needs be run to determine whether NRS2 science exists, the resolution of this issue is more of a preemptive feature that will create more science-correct associations, but otherwise would have no real affect on processing.

**Comment by nden** [comment]
I have a recollection this was fixed already. @stscieisenhamer ?

**Comment by stscieisenhamer** [comment]
Yes, this is resolved by PR #5504
