### ISSUE TITLE
cannot build sphinx document

### ISSUE THREAD

**Issue by rizeladiaz** [spacetelescope/jwst#2453]
I am trying to build the documentation sphinx document but I cannot make it compile. The error I get is (jwst_dev) bash-3.2$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.6

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/Users/rdiaz/anaconda3/envs/astroconda/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/Users/rdiaz/anaconda3/envs/astroconda/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 19, in <module>
    import stsci_rtd_theme
ImportError: No module named 'stsci_rtd_theme'

Makefile:49: recipe for target 'html' failed
make: *** [html] Error 2
(jwst_dev) bash-3.2$ 

I downloaded a version of the stsci_rtd_theme package and installed it but still get the same error. Can someone help with this? I have spent already a lot of time trying to make it work.

**Comment by jdavies-st** [comment]
In the top level of the repository
```
$ python setup.py build_sphinx
```
should do it.  The setup.py script will pull in the dependencies.  Will document this in our README.rst
