### ISSUE TITLE
Resampling multi-integration products

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2455]
Since #2424 was merged, which turns on calls to `resample_spec` in the `calwebb_spec2` pipeline for MIRI LRS fixed-slit exposures, the regression test "test_miri_lrs_slit_1b" has been throwing an error. The reason is that the input for the test is a multi-integration data set (_rateints product), which uses a `CubeModel` data model for the 3-D data and the `resample_spec` step doesn't know what to do with a `CubeModel`. This issue raises a couple different questions.

1) Most of the time we only encounter 3-D spectral data for TSO-mode exposures and TSO data don't get resampled. So the simplest approach to fixing the current issue would be to just not call `resample_spec` when someone's running 3-D data through `calwebb_spec2`. Technically, however, the MIRI LRS fixed-slit mode is not a TSO mode and in fact the APT doesn't even allow a user to mark it as TSO (only MIRI LRS slitless can be marked as TSO). But it is reasonable to assume that a user may at some point intentionally want to process the multi-integration form of MIRI LRS fixed-slit data (or some other mode, like NIRSpec fixed-slit) in order to investigate the per-integration data. So in that case we should NOT simply disable resampling for any 3-D spectral data. `resample_spec` should instead be enhanced to know how to handle a `CubeModel`, resampling each individual "slice" of the 3-D cube and return some kind of 3-D resampled product.

2) Recent changes to stpipe and ASN infrastructure that determine product naming based on whether an exposure is a TSO type may be too restrictive. For example, in the case of the regression test mentioned above, the MIRI LRS fixed-slit data would be regarded as NOT TSO and hence the determination of the output product name would want to make it a _cal product, instead of the proper _calints product for 3-D data. The infrastructure for determining "ints" product types (for both imaging and spectral modes) should not simply rely on whether or not a given exposure was taken in a TSO mode, but should instead rely on the form of the data, i.e. is it a 2-D `ImageModel` or a 3-D `CubeModel`? If the former, the output is a _cal product, and if the latter, the output is a _calints product.

**Comment by jdavies-st** [comment]
Since the pipeline will not produce _calints products for `MIR_LRS-FIXEDSLIT` exposure types, this failing unit test is testing something that should not really happen in pipeline processing.  I think it would be best to turn resampling off for any cube models that get passed along in the pipeline, and that will handle this case.

I can also add a more useful error message within `resample` itself if passed a cube.

We do some resampling of multi-integration cubes in the `outlier_detection` step for certain modes, but I would rather not pull this out into a general `resample` step functionality if it is not currently needed in the pipeline.

**Comment by hbushouse** [comment]
Agree with the approach of just skipping `resample_spec` for now when it encounters a `CubeModel`, but should still allow `calwebb_spec2` to produce _calints and _x1dints products when given a _rateints as input (just don't produce a _s2d product).
