### ISSUE TITLE
flat_field doesn't always find the dispersion direction correctly

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#2487]
In the `flat_field` step for NIRSpec data, the dispersion direction is determined by comparing wavelengths in the wavelength array in the input file, to see along which image axis is the wavelength increasing more quickly.  This is needed in order to average the "fast variation" flat (flat field as a function of wavelength, from a table in the reference file) over each pixel in the flat field image.  Using the wrong dispersion direction would probably not usually result in a large error in the computed (on-the-fly) flat.

The main reason why the dispersion direction was not always computed correctly is that there are (often) NaNs in the wavelength array in the input file, and those NaNs get replaced early in `flat_field` by "harmless" values that turned out not to be so harmless.  Depending on the type of data, values of -1000 and 1 were used as replacements for NaN.  Also, the wavelengths were compared only for three pixels near the center of the 2-D cutout, and in some cases those pixels were on the edge or entirely outside the bounding box.  The replacement value should be the same for all types of data, and the function for determining the dispersion direction must ignore pixels with this replacement value.

**Comment by stscicrawford** [comment]
Closed with #2492
