### ISSUE TITLE
New MRIR LRS reference file

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#251]
Need to test it.

**Comment by nden** [comment]
Work done in #347. We still need to figure out discrepancies between recent data and the new reference file.

**Comment by hbushouse** [comment]
@nden Status? Close it or slip to B7.2 for further work?

**Comment by nden** [comment]
Slip to 7.2. I don't know if the MIRI team has delivered a new reference file or not but I need to look into the LRS WCS.

**Comment by nden** [comment]
Old issue, closing
