### ISSUE TITLE
Allow offset tangent plane in resample ouptut

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2512]
Currently, the `resample` output frame is computed to contain all the input data.  It produces a linear, square FITS WCS with the tangent point at the center of the image.

It will be very useful to scientists to allow a user-defined tangent point, i.e. passing in a user-defined FITS WCS and image size, much like `drizzlepac` can currently do.  This is to allow building of of pixel-aligned mosaics of the same field in different detectors and/or filters.

This is an end-user feature, not necessarily a pipeline feature.

Requested by @antonkoekemoer.

**Comment by nden** [comment]
Fixed by #6364
