### ISSUE TITLE
Confirm transformation from quaternion through SIAF

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2520]
# Issue

Most data from DGA#3 were supposedly given real quaternion pointing information. Confirm that

- [x] quaternion to V1 transformations are correct
- [ ] V1 to SIAF transformations are correct

**Comment by stscieisenhamer** [comment]
# Resources
Data is located in `/grp/jwst/ssb/eisenhamer/jwst_issues/issue2520`. Examine the EXP_TYPE; there are internal calibrations that may/may not be valid. Also, two exposures did not have quaternion data:

- jw00608002001_02101_00002_mirimage_uncal.fits
- jw00610002001_02101_00001_nis_uncal.fits

**Comment by stscicrawford** [comment]
@nden Can you take a look at this issue assess what might need to be done?   Whether it should be patched or moved to 7.3?

**Comment by stscieisenhamer** [comment]
# Confirmation
W.Kinzel independently confirms V1 calculation.

**Comment by stscieisenhamer** [comment]
# Update
In discussions with Telescopes, it has been discovered that there is a unit change in the fine mirror correction values. In Jun18, the default units were changed from radians to arcsecs. Telescopes have started a discussion on whether that change will remain in effect or not.

In the meantime, the FMS correction is wrong. The preceding confirmation by Telescopes was because they were unaware of the unit change also.

Will need to wait further direction from Telescopes.

**Comment by stscieisenhamer** [comment]
# Update 2 _12Dec18_
Another issue has come up. There is an apparent transposition of the J2FGS matrix between different data sets. The `SA_J2FGS1*` mnemonics, of which there are 9, create a 3x3 matrix. However, some data requires that matrix to be construct in transposition relative to how it should be constructed with other data. Investigation is ongoing to try to characterize any commonalities and then report upstream. A short list of proposals are below representing the two matrix orientations. Note that SIAF confirmation can still be done on the "expected" set.

- Proposals that gave expected results
    - jw00307
    - jw00308
    - jw00309
    - jw00329
    - jw00351
    - jw00604
    - jw00606
    - jw00701
    - jw00703
    - jw00711
    - jw00720
    - jw00721
    - jw00723
    - jw00728
    - jw00729
    - jw00730
    - jw00731
    - jw00756
    - jw00799
- Proposals that appear to have a transposed J2FGS matrix
    - jw00329
    - jw00601
    - jw00603
    - jw00608
    - jw00609
    - jw00610
    - jw00611

**Comment by stscieisenhamer** [comment]
Resolved by #3367
