### ISSUE TITLE
remove fits wcs hack from nircam wfss in due time

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#2533]
In order to facilitate team and pipeline testing, i added an optional parameter to the grism extract 2d, for NIRCAM:  `use_fits_wcs` gets set to true, this uses the FITS wcs from the grism image to translate the source center and box corners from the catalog for use in the trace polynomials. This is to try and counteract the catalog being created using the FITS wcs + the distortion reference file, + the simulations that I have for testing. It can be toggled manually, and removing it is simple. This should help iterating tests with the science team for the time being. There are no SDP tests sets for nircam that I know of, just simulations from the team.

**Comment by nden** [comment]
@sosey  Should `fits_wcs` be removed now?

**Comment by sosey** [comment]
This was a stopgap to help with testing until photutils could start using GWCS for the catalog.  The catalogs are based on fits wcs locations, the grism pipelines are based on gwcs locations, that affects everything downstream of assign_wcs because object and bounding box locations calculation go through the distortion file for the filter that was used for the grism observation, but not necessarily the direct image observation. 

At the time, photutils was using `pixel_to_skycoord` which required an astropy wcs, I'm not sure what it is using today.
