### ISSUE TITLE
Incorrect level-2b and level-3 processing flows for wavefront sensing (WFS) exposures

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2546]
DMS DR [5238](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/dr.5238) reports that recent test runs of WFS&C exposures resulted in unexpected products, notably a level-2b `i2d` product. The `calwebb_image2` pipeline should skip the `resample` step when processing WFSC exposures and hence only a `cal` product should be produced.

This is apparently due to the fact that `calwebb_image2` is currently only using the EXP_TYPE value to try to identify non-science exposures (like WFSC), but WFSC exposures have a normal EXP_TYPE of "NRC_IMAGE". Hence we need to make use of the VISITYPE keyword value to identify WFSC exposures. They will have VISITYPE values of "PRIME_WFSC_ROUTINE", "PRIME_WFSC_SENSING_CONTROL", or "PRIME_WFSC_SENSING_ONLY."

Also verify that `asn_generator` keys off of the VISITYPE keyword in the asn pool to trigger the creation of a level-3 WFSC ASN (asn_type = "wfs"), which results in only the `wfs_combine` step being called for level-3 processing.

**Comment by stscieisenhamer** [comment]
# Resources
- DR [5238](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/dr.5238)
- 82600 provides for some faked-up data.

**Comment by stscieisenhamer** [comment]
# Implementation

- [ ] documentation
- [ ] tests
- [ ] code
- [ ] tests
- [ ] documentation
- [ ] changelog
