### ISSUE TITLE
Computing bounding_box for a 3D datamodel is broken-ish

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2549]
So #2541 introduced an error into how `bounding_box` is computed for a multi-integration slit.

An example below for a slit that has 3 integrations:
```
In [4]: slit = datamodels.SlitModel('jw84600042001_02101_00001_nrs2_rateints.fits')

In [5]: slit
Out[5]: <SlitModel(3, 32, 2048) from jw84600042001_02101_00001_nrs2_rateints.fits>

In [7]: slit.shape
Out[7]: (3, 32, 2048)

In [8]: from jwst.assign_wcs.util import bounding_box_from_shape

In [9]: bounding_box_from_shape(slit)
Out[9]: ((-0.5, 31.5), (-0.5, 2.5))
```
Original (working) code from extract_2d below, which seems to give the correct result in terms of picking out spatial dimensions for the bounding box.  Ignore the fractional pixel differences:
```
In [10]: shape = slit.shape

In [11]: ((0, shape[2] - 1), (0, shape[1] - 1))
Out[11]: ((0, 2047), (0, 31))
```
So it seems that `bounding_box_from_shape()` doesn't compute the bounding box from the spatial dimensions.  For our 3D models, is the non-spatial dimension (time or wavelength) always the first as above?  @hbushouse @nden?

Two ways to fix this:
- [ ] Put old code back into `extract_2d`.
- [ ] Fix `bounding_box_from_shape()` to work for all cubes, and use this in `extract_2d`.

Currently this is causing the `pipelines/test_nrs_fs_brightobj_spec2.py` regression test to fail.

https://boyle.stsci.edu:8081/job/RT/job/JWST/303/testReport/jwst.tests_nightly.general.pipelines/test_nrs_fs_brightobj_spec2/test_nrs_fs_brightobj_spec2/

**Comment by jdavies-st** [comment]
The bug is from the checking of the model type.  Continuing from above:
```
In [2]: im = datamodels.open('jw84600042001_02101_00001_nrs2_rateints.fits')

In [3]: im
Out[3]: <CubeModel(3, 32, 2048) from jw84600042001_02101_00001_nrs2_rateints.fits>

In [13]: bounding_box_from_shape(im)
Out[13]: ((-0.5, 2047.5), (-0.5, 31.5))
```
So it works if the input is a `CubeModel`, but not a 3D `SlitModel`, which makes sense give the check:
https://github.com/spacetelescope/jwst/blob/501eec30bab1e620f97da7f6bba3477d37604654/jwst/assign_wcs/util.py#L646

**Comment by nden** [comment]
A third solution would be to add `SlitModel` to the type checking above which I am in favor of.

**Comment by hbushouse** [comment]
Yes, the time (non-spatial) dimension is always the first dimension in data models like `CubeModel`, and it looks like that's how @nden set it up for a 3-D `SlitModel` as well, but I'm not sure about `IFUCubeModel`. For the latter I believe wavelength is always the 3rd dimension in FITS format, which means it would be first (like `CubeModel`) in a data model array.

**Comment by jdavies-st** [comment]
But the type checking above is to figure out if something is 2D or 3D.  A SlitModel can be either 2D or 3D, so that doesn't help.

**Comment by nden** [comment]
You are right about `SlitModel` :-(
And yes, this looks like the best approach.
