### ISSUE TITLE
Enable flake8 for some steps

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2552]
#2542 enables flake8 test in Travis excluding `associations`, `exp_to_source`, `fits_generator`, `lib`, `ramp_fitting`  and `jwpsf`. This issues is a reminder to fix those steps and complete #2329

- [ ] associations
- [x] exp_to_source
- [ ] fits_generator
- [x] lib
- [x] ramp_fitting
- [x] jwpsf

**Comment by hbushouse** [comment]
`jwpsf` has been removed from the repo.

**Comment by hbushouse** [comment]
As of 16-Jul-2019 the only 2 steps still being excluded are `associations` and `fits_generator`.

**Comment by jdavies-st** [comment]
Those are still being excluded.  `fit_generator` has real bugs, i.e. code that doesn't work.  And I have not tried touching `associations`.

**Comment by hbushouse** [comment]
OK, thanks. I'm leaving this open and setting to a future milestone.

**Comment by braingram** [comment]
Fixed in #8652
