### ISSUE TITLE
Updated subarray names

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2560]
There will be an updated submission of subarray names and frame times submitted to PRD and the data model schemas should be updated to work with these subarray names.

**Comment by hbushouse** [comment]
What's our source for the new SUBARRAY names?

**Comment by stscicrawford** [comment]
Responded to you with the full email thread with the information.  Also, chat with @jaytmiller for more information.

**Comment by hbushouse** [comment]
Updates needed relative to current schema content.

FGS:
 - 8x8, 32x32, 128x128, 2048x64: remove
 - SUB128CENTER -> SUB128CNTR
 - SUB128DIAGONAL -> SUB128DIAG
 - SUB128LLCORNER -> SUB128LL
 - SUB32CENTER -> SUB32CNTR
 - SUB32DIAGONAL -> SUB32DIAG
 - SUB32LLCORNER -> SUB32LL
 - SUB8CENTER -> SUB8CNTR
 - SUB8DIAGONAL -> SUB8DIAG
 - SUB8LLCORNER -> SUB8LL

**Comment by hbushouse** [comment]
Correction: SUBARRAY names for FGS **guiding** mode data are currently hardcoded by SDP, using the values "8x8", "32x32", "128x128", and "2048x64", so those names need to be reinstated to the list of allowed values. The FGS subarray names listed above only apply to FGS **science** mode exposures.
