### ISSUE TITLE
Is BACKGRND keyword needed/used in multiexposure.schema.yaml?

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2586]
The data model schema `multiexposure.schema.yaml` defines the keyword "BACKGRND", which is mapped to the model property "background". I can't find any obvious instance of this being used anywhere in the cal pipeline code base. This keyword is not defined in the JWST Keyword Dictionary, so if we do need it for something, we need to add it to the JWKD.

To my knowledge the `multiexposure.schema.yaml` model is used for the output products from the `exp_to_source` step, which is only applied to data from spectroscopic modes in which we have multiple defined sources, such as NRS_MSASPEC, NRC_WFSS, and NIS_WFSS. The only obvious connection to a "background" status for these modes is the background indicator in the NIRSpec MSA meta data file that tells us which shutters contain background (or not). But because multiple shutters usually make up a single slit, it's not obvious to me how the background status could get transferred to a given slit or spec instance (because there would be multiple different values).

We need to figure out if this keyword definition is really needed or even possible to be used and if not, then remove it.

**Comment by jdavies-st** [comment]
@stscieisenhamer, I think this was added for some use case you were thinking of?
