### ISSUE TITLE
Retire Travis and only use Jenkins

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#2587]
No reason to maintain both `.travis.yml` and `Jenkinsfile`, unless you want to test against OSX on Travis, which you are not doing.

**Comment by nden** [comment]
Is there a reason not to test on osx in the future when we start releasing it?
We had a case when Travis and Jenkins were giving different results and it was helpful we had both for debugging.
Although I don't have strong opinions on this.

**Comment by jdavies-st** [comment]
Agree that is is useful to have had both.  Just this past week there was an issue where a PR was failing on one but not the other.

That said, I think some of this might have to be with how the testing is set up on Travis vs Jenkins.  On Travis, we use `python setup.py test` and on Jenkins we call pytest directly with some extra setup stuff in the build process.

Agree it would be good to test on MacOS, but I recall we used to have that in our Travis matrix, but that those machines running the tests were very unreliable on the Travis side.  I wonder if that has changed?

**Comment by pllim** [comment]
OK feel free to close then. I was wondering if it would reduce maintenance burden to move things like PEP 8 check and doc build test to Jenkins, but I guess not if you need to keep Travis up for other reasons.

Re: OSX -- Not sure. A while back Travis added "additional resources" but :woman_shrugging: . According to https://www.traviscistatus.com/ , there is no current backlog but it is not widely used either (because people moved away from it previously?). So you can always try your luck. :duck:

**Comment by stscicrawford** [comment]
Closing but it can be revisited in the future.
