### ISSUE TITLE
handle apername==null

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2596]
This is a spin off #1744 [comment](https://github.com/spacetelescope/jwst/issues/1744#issuecomment-425219146).
When SDP looks up the aperture name for level 1 files, some EXP_TYPEs (non-science) APERNAME points to NULL. For these cases the set_telescope_pointing scripts should be modified to **not** run `update_wcs` and `update_s_region`. The EXP_TYPEs are

`MIR_DARK`, `MIR_FLATIMG`, `MIR_FLATMRS`, `NRC_DARK`, `NRC_FLAT`, `NRC_DARK`, `NRS_DARK`, `NRS_LAMP`. 
Also `FGS External Calibration` and `NIRSpec MSA Anneal` for which there are no examples yet.

One issue awaiting clarification is how "apername pointing to null" translates to a FITS keyword value.

**Comment by hbushouse** [comment]
See https://jira.stsci.edu/browse/JP-474

**Comment by hbushouse** [comment]
Relates to https://jira.stsci.edu/browse/JSDP-364

**Comment by hbushouse** [comment]
Closing because it's now duplicated by #2929.
