### ISSUE TITLE
populate headers with FITS WCS keywords

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2597]
A side issue discussed in  #1744.

Currently FITS WCS keywords are populated both by SDP and by the set_telescope_pointing script. It was decided that set_telescope_pointing should populate all WCS keywords. 
Related issues: #2596, #2262

**Comment by hbushouse** [comment]
See https://jira.stsci.edu/browse/JP-475

**Comment by hbushouse** [comment]
Also see https://jira.stsci.edu/browse/JSDP-364

**Comment by hbushouse** [comment]
Closing this ticket, because it's now been duplicated by #2932.
