### ISSUE TITLE
TST: Test against released Astropy

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#2638]
Maybe it is still too early for such a radical idea, but eventually you'll have to do it. You can't hide in `conda-dev` forever!

**Comment by nden** [comment]
Yes it is.

**Comment by jdavies-st** [comment]
PR #2326 will allow us to build `jwst` from released versions of packages.  Once that is merged, then we should be able to test from released versions as well.  I would be up for doing that in a nightly Jenkins build that ran all the tests (unit and regression), though we'd have to figure out the truth files for the regression tests.

But it would allow us to see differences between released and dev versions.  And allow us to see our dependence on dev versions of our dependency packages.  We still need to use dev versions of `astropy`, `asdf` and `gwcs` often, but this might help track those a bit better.

**Comment by nden** [comment]
We can't run released versions of astropy or gwcs until the next astropy release and the gwcs release that follows it. There are many unreleased features that we use. The next astropy release is scheduled for ~ end of Nov.

**Comment by nden** [comment]
We've been testing/running for a while with released versions of all dependencies.
