### ISSUE TITLE
datamodels storage.py should be removed

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2654]
The storage.py module in datamodels seems to be some old leftover from an initial design for asdf and fits embed.  It is not used.  Anyone know its purpose?  @hbushouse? @bernie-simon?

https://github.com/spacetelescope/jwst/blob/9fd366286d78e62fce0d522b712dcf1ad5270a0e/jwst/datamodels/storage.py#L1-L52

**Comment by hbushouse** [comment]
No idea. @mdboom may be the only person who does.

**Comment by drdavella** [comment]
It doesn't ring any bells for me.

**Comment by perrygreenfield** [comment]
Not me. If nothing is using it, and no one currently knows the purpose, I'd say remove it.

**Comment by bernie-simon** [comment]
It looks to duplicate code that is elsewhere in datamodels and asdf. It's not clear whether this is an attempt to add another layer of abstraction to the code or an early version that was later abandoned. There's nothing in the code that's interesting and it should probably be deleted
