### ISSUE TITLE
Association.dump should attached the extension matching the requested format

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2671]
# Issue
`Association.dump` returns a suggested name for the association. However, this is only the base name, leaving the addition of the extension up to the user. However, the call itself takes `format` as a keyword argument, essentially defining the extension to be used. Just add this extension onto the returned suggested name.

# Resources
- #2666

**Comment by ddavis-stsci** [comment]
This was fixed in Jira ticket JP-839 and closed.
