### ISSUE TITLE
Reference file schemas need the P_* keyword schemas added

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2684]
- [x] `SuperBiasModel` needs keyword_preadpatt
- [x] `NirspecFlatModel` needs keyword_pexptype

Reported by @gkanarek of the NIRSpec team.  These keywords are required for CRDS validation, but are not in the schemas.  Since they are not in the schemas, if the reference file models above are used to generate them and they are populated, they don't get written out to the FITS file.

The workaround was to manually add the values to the FITS file afterwards.  But if they are required, they should be in the schema.

**Comment by jdavies-st** [comment]
@jaytmiller, can you verify that these are required?  It seems so based on the selectors in the rmaps.

Any other reference file schemas missing their `P_xxx` keywords that we can patch up while we're at it?

**Comment by jaytmiller** [comment]
There are 117 rmaps to review for this but I'll see what I can do.  

I can generate this relationship /  info with a small amount of new code:

     reftype  :  rmap   : matching parameters (model path) :  normal FITS keyword : P_ keyword

I don't have a good handle on this:

     Step  :  reftype : model : schema

Since there are many different rmaps,  I think we should probably fan out step #2 to the CAL team at large with each Step owner handling their own reftypes and models.

**Comment by jdavies-st** [comment]
I think your first relationship above is all we need.  As reftype matches 1-to-1 with reference file model schema.  I don't think the Step matters at all.  Basically we'd need to know for each reftype what the matching parameters are, and if any of those are more than single valued (i.e. require the P_ keyword), and then verify that's in the reference file model for that reftype.

If you can generate the relation above, I can check the reffile schemas.

I suspect the two that @gkanarek found above just fell through the cracks when we were generating our schemas.

I wonder if we could generate a test for this if the code generating the test above is in CRDS.  If not, then just spot checks when we make new reffile types and schemas would be sufficient I suspect.
