### ISSUE TITLE
shouldn't the readme tell people to install not develop?

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#2691]
The readme section under install instructs people to clone the repo and then install using develop, why is this the case? 
>   conda create -n jwst_dev --only-deps --override-channels -c http://ssb.stsci.edu/astroconda-dev -c defaults python=3.6 jwst
>   source activate jwst_dev
>   git clone https://github.com/spacetelescope/jwst.git
>   cd jwst
>   python setup.py develop

should be `python setup.py install` in this section ?

**Comment by stscicrawford** [comment]
The pipeline instructions have been updated and this section has been updated
