### ISSUE TITLE
Add new MIRI external flat EXP_TYPEs to asn_generator rules

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2695]
https://jira.stsci.edu/browse/JSDP-751 documents changes being made in SDP that will result in new EXP_TYPE values for MIRI external flats: "MIR_IMAGE-EXTFLAT" and "MIR_MRS-EXTFLAT". These new EXP_TYPE values need to be added to the asn_generator rules that are used to construct (or not) ASN's for flats.

**Comment by stscieisenhamer** [comment]
# Implementation

- [x] documentation
- [x] tests
- [ ] code
    - [ ] Add the new flat values
    - [ ] As per #2694 and [JSDP-692](https://jira.stsci.edu/browse/JSDP-692), add the new dark values.
- [ ] tests
- [ ] documentation
- [ ] changelog.
