### ISSUE TITLE
Data structures in the Pipeline documentation

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2697]
There are a number of tickets and issues opened about data formats used in the pipeline.  It would be useful to consolidate this information and how it should be presented to the user.   This includes information about data models, inputs and outputs of the pipeline at different stages, and ASDF.  

Issues this includes:
#1806 #2104 #1757

**Comment by hbushouse** [comment]
I'll include references to datamodels in the input/output descriptions for the pipeline docs in /docs/jwst/pipeline/. We'll need a separate doc that gives FITS file structures and equates them to particular data models.

**Comment by hbushouse** [comment]
#3000 updates all pipeline module docs to include the type(s) of data models accepted as input and produced as output.

**Comment by melanieclarke** [comment]
Closing, since documentation has evolved quite a bit since this issue was filed.  If there are still issues with documenting data structures used in the pipeline, please file a new ticket.
