### ISSUE TITLE
Allow ImageModel input to source_catalog?

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#2708]
I have simulations from the team, that haven't gone through drizzling and don't have drizzle output products or meta information. I still need to make source catalogs for them, but to do so I have to constantly edit the data I get so that it conforms to DrizProductModel.  

It would be useful if `source_catalog` could be updated to also accept ImageModels. This would help with testing, but could also be useful to the team if they want to run source detection on calibrated but not resampled single images.

**Comment by sosey** [comment]
@larrybradley any chance this could happen?

**Comment by nden** [comment]
not relevant any more
