### ISSUE TITLE
Reference spec issues 7.3

### ISSUE THREAD

**Issue by jaytmiller** [spacetelescope/jwst#2718]
This ticket documents questions and resolutions related to the reference file documentation.

**Comment by jaytmiller** [comment]
Question about standard boiler plate keywords:

XXXX -  DATE and FILENAME are significant so want to confirm before adding them to "required" checks. Not hard to check, but suspect many scripts wont have them.

**Comment by jaytmiller** [comment]
XXX - shouldn't define GAIN uniquely under different Steps. need direction on e/DN requirement.

**Comment by jaytmiller** [comment]
XXX - consider adding table adding more detail on expected array dimensions.

No docs on array dimensions in general, particularly with respect to reference pixels and YMAX=3200.

XXX - Needs array basic dimensionality docs on:

NIR 2048 x 2048
MIRI 1024 x 1032

(not in x/y order)
256 x 2048
3200 x 2048
2304 x 2048
1024 x 1024

SUBARRAY considerations

**Comment by jaytmiller** [comment]
XXXX -  RESET is defined as N/A for all instruments

Remove from CRDS rules?

**Comment by stscicrawford** [comment]
Keeping at 7.2 just in case things can be addressed prior to the patch release.
