### ISSUE TITLE
Documentation of levels vs. steps

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2731]
It would be helpful in the developer documentation to have a description of all of the levels and how they correspond to steps.   This came up in #2727

**Comment by hbushouse** [comment]
I believe the desire here is to have a mapping of DMS "levels" to JDocs user "stage" terminology, at least for internal users and developers, correct?

**Comment by stscicrawford** [comment]
For our developer and outward facing documentation, it would probably be useful to be consistent, but at least, adding a note or warning to the top of the pages if they can't be made consistent.

**Comment by hbushouse** [comment]
The updated data products docs included in #3046 include a table that cross-references the DMS "level" terminology with the public "stage" terminology.
