### ISSUE TITLE
tweakreg can use fix to union in spherical_geometry

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2739]
The following lines in `tweakreg`
https://github.com/spacetelescope/jwst/blob/f56c3fd46e536d84ee2d2388333bb928091a8869/jwst/tweakreg/wcsimage.py#L549-L574
were a workaround for a bug spacetelescope/spherical_geometry#74 which was fixed in spacetelescope/spherical_geometry#80.  `tweakreg` can now be updated to use the fix?

**Comment by hbushouse** [comment]
@mcara can you confirm that the fix in https://github.com/spacetelescope/spherical_geometry/pull/80 addresses the original issue and hence the `tweakreg` wcsimage code can be updated to remove the workaround?

**Comment by mcara** [comment]
Yes, I believe that https://github.com/spacetelescope/spherical_geometry/pull/80 fixed the bug. It is ok to remove the workaround. However, I think in light of switching to `tweakwcs` this is unnecessary work. I will continue working on moving to  `tweakwcs` once I am back.
