### ISSUE TITLE
Add NRS_MSATA and NRS_WATA as valid target acq exposure types

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2758]
# Issue

NRS_BOTA has been replaced with two new target acquisition exposure types: NRS_MSATA and NRS_WATA.

Note: This is to stay in compliance with #297.

**Comment by hbushouse** [comment]
Related to #2759.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] documentation
- [ ] tests
- [ ] code
- [ ] tests
- [ ] documentation
- [ ] change log *Left to finalization of #2780*

**Comment by stscieisenhamer** [comment]
Resolved by #2780.
