### ISSUE TITLE
Update EXP_TYPE allowed values for new NIRSpec TA names

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2759]
DMS reports that "Exposure Type NRS_BOTA was replaced by 2 new types: NRS_MSATA and NRS_WATA", so we need to update the enum list of allowed EXP_TYPE values in our data model schemas.

**Comment by hbushouse** [comment]
Related to #2758.

**Comment by nden** [comment]
assign_wcs and extract_2d should be updated as well

**Comment by nden** [comment]
@hbushouse How should the two new EXP_TYPEs be processed by assign_wcs and extract_2d?

I am assuming `NRS_MSATA` stands for MSA Target Acq. Should this be assigned an `imaging wcs`?
What does `NRS_WATA` stand for?

**Comment by hbushouse** [comment]
Yes, they are both still TA type exposures (like BOTA was), all of which are to be treated as imaging. WATA = Wide Area Target Acq.

**Comment by hbushouse** [comment]
Data model schemas updated in #2772.

**Comment by hbushouse** [comment]
The change in keyword values is mentioned in https://jira.stsci.edu/browse/REDCAT-52, but I don't know if there's a corresponding ticket to update the rmaps. I will check with ReDCaT.

**Comment by hbushouse** [comment]
Fixed by #2772 and #2781
