### ISSUE TITLE
docs failure in associations - no finalize attribute?

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#2777]
@stscieisenhamer looking at the doc failures, this one points to no finalize in `AssociationRegistry` and indeed, I don't see one. Is there supposed to be? The docs suggest so, but I only see one in the Association class (https://github.com/spacetelescope/jwst/blob/master/jwst/associations/association.py#L435)

> WARNING: autodoc: failed to import method 'AssociationRegistry.finalize' from module 'jwst.associations'; the following exception was raised:
> Traceback (most recent call last):
>   File "/Users/sosey/miniconda3/envs/jwstdev/lib/python3.5/site-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
>     obj = attrgetter(obj, attrname)
>   File "/Users/sosey/miniconda3/envs/jwstdev/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
>     return autodoc_attrgetter(self.env.app, obj, name, *defargs)
>   File "/Users/sosey/miniconda3/envs/jwstdev/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 1515, in autodoc_attrgetter
>     return func(obj, name, *defargs)
>   File "/Users/sosey/miniconda3/envs/jwstdev/lib/python3.5/site-packages/sphinx_automodapi/autodoc_enhancements.py", line 73, in type_object_attrgetter
>     return getattr(obj, attr, *defargs)
> AttributeError: type object 'AssociationRegistry' has no attribute 'finalize'

**Comment by nden** [comment]
Fixed in #2730?

**Comment by sosey** [comment]
closing...I think this was caused by an old api/ dir that needed cleanup
