### ISSUE TITLE
ImportError during test run

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/jwst#2800]
I'm trying to run the test suite and keep encountering lots of errors like the following:

>ImportError while importing test module '/Users/ddavella/jwst/jwst/tests_nightly/general/nirspec/test_spec2pipelines.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../tests_nightly/general/nirspec/test_spec2pipelines.py:5: in <module>
    from jwst.tests.base_classes import BaseJWSTTest
../../tests/base_classes.py:3: in <module>
    from ci_watson.artifactory_helpers import (
E   ImportError: cannot import name 'check_url'

I currently have `ci-watson-0.1.2` installed.

**Comment by jdavies-st** [comment]
Currently we're relying on master.  We need a new version released.  Try
```
pip install git+https://github.com/spacetelescope/ci_watson.git
```

**Comment by jdavies-st** [comment]
@pllim, any chance there could be a new release of `ci_watson`?

**Comment by pllim** [comment]
Do you need it before ADASS? :sob:

**Comment by drdavella** [comment]
It's fine, I can install from `master` for now. Will the test suite run locally if I uninstall it entirely, or is it hard requirement for tests now?

**Comment by jdavies-st** [comment]
No, not before ADASS.  We've been running off master for the past few weeks.  Another couple weeks will not hurt.

It is a hard requirement for tests now because it defines pytest marks such as `@pytest.mark.slow`.  I'm not sure how I feel about that, as we could easily define those in the jwst package to be consistent with `ci_watson`.

So while the unit tests do not use any `ci_watson` fixtures, you do need the pytest marks from `ci_watson`

**Comment by pllim** [comment]
If this is giving you so much trouble, I can do a release soon. Just need to find an hour of quiet time. Thanks for your patience!

**Comment by pllim** [comment]
I'll try to get a `ci-watson` release out today. Stealing from @larrybradley , it will be a *spooktacular* release!

**Comment by pllim** [comment]
FYI -- `ci-watson` 0.2 is released and already available on PyPI. It also will be in `astroconda` when astroconda/astroconda-contrib#416 is merged and build.

**Comment by pllim** [comment]
:bat:

**Comment by jdavies-st** [comment]
`ci_watson 0.20` has been released.  Closing this.
