### ISSUE TITLE
update MIRI LRS WCS spatial transform

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#2825]
The WCS transform for the MIRI LRS includes a spatial transform from detector to world using the Imager distortion. However the WCS pipeline does not include an intermediate frame at V2V3. Instead it goes directly to sky. 
An intermediate V2V3 frame is needed in order to get extract_1d to use the same algorithm as other steps.

Note: The spatial transform includes the distortion models but not the filter offset correction.

**Comment by skendrew** [comment]
See also https://github.com/spacetelescope/jwst/issues/268 - does this help?

**Comment by nden** [comment]
An intermediate frame was added  in #2894.
The remaining work includes composing an inverse transform. The transform is a `TabularModel` and an inverse model can be easily added in the 1D case. This can be done initially in the pipeline but should be eventually moved to modeling.

@hbushouse

**Comment by hbushouse** [comment]
Now being tracked in JIRA in https://jira.stsci.edu/browse/JP-484

**Comment by nden** [comment]
Resolved in #3001, #2951 and #3324
