### ISSUE TITLE
Ensure that number of segments does not exceed the number of groups

### ISSUE THREAD

**Issue by dmggh** [spacetelescope/jwst#2836]
For a MIRI dataset in which the first or last group was flagged as DO_NOT_USE and also flagged as a jump, the maximum number of segments calculated could exceed the number of groups which remain after the first and/or last groups are designated to be ignored for the ramp fitting. This was discovered during MIRI LEVEL_2A testing under v0.12.1 for imaging & IFUs. This can be fixed by ensuring that the number of segments does not exceed the number of groups.

**Comment by dmggh** [comment]
This is being addressed by PR #2834 ("Fixed bug in which the number of segments returned exceeds the number of groups...") which has been committed, and will be merged once the tests are fixed and rerun.

**Comment by hbushouse** [comment]
Fixed by #2834.
