### ISSUE TITLE
Unpin numpy, pytest in CI config files

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2838]
When the bugs in `numpy 1.15.3` get fixed, unpin it in `.travis.yml`, `Jenkinsfile` and `JenkinsfileRT`.

Same for `pytest 3.9.2` bugs.  `pytest 3.9.3` is out now, so it should be tested.

**Comment by sosey** [comment]
https://github.com/numpy/numpy/releases/tag/v1.15.4 was released today, with the masked array fix, looks like pytest 3.10 just showed up too

**Comment by hbushouse** [comment]
#2853 unpins pytest. Still need to unpin numpy some time.

**Comment by jdavies-st** [comment]
Resolved by #2853.
