### ISSUE TITLE
Deep copy on DataModel does not work

### ISSUE THREAD

**Issue by mcara** [spacetelescope/jwst#284]
Trying to create a deep copy of a `DataModel` fails:

``` python
>>> import copy
>>> from jwst.datamodels import DataModel
>>> copy.deepcopy(DataModel())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: copy() takes exactly 1 argument (2 given)
```

It seems to originate in the following line: https://github.com/STScI-JWST/jwst/blob/master/jwst/datamodels/model_base.py#L213 which is incorrect since it makes `__deepcopy__` to take a single argument (no `memo`). I think this line should be removed completely: why force users to not use `copy` module? Is there a solid reason for this? This line first appeared in https://aeon.stsci.edu/ssb/trac/jwst/changeset/3641/trunk/jwst_lib/models/jwst_lib/models/model_base.py and there was no justification provided for doing this.

In addition, I am not sure that `DataModel.copy()` actually performs a "true" deep copy. And if does not _deep_ copy _every_ attribute, then this should be clearly documented.

**Comment by bernie-simon** [comment]
You're right about Datamodel.copy() missing an argument and I have a patch that adds it. The DataModel class overrides the copy methods for the usual reason, because there is additional work that needs to be done to clone an object besides simply copying the data. With the change in the argument list, copy.copy and copy.deepcopy should run correctly. The copy method was added in Mike's last big release and the justification for it is as I stated. DataModel.copy() clones itself and this is what is usually meant by a copy. If it were nothing more than a simple recursive copy, there would have been no reason to write it.

**Comment by mcara** [comment]
If deep-copying an object requires special treatment, then indeed overriding ``__deepcopy__`` may be necessary. However, I do not see any reason for overriding shallow ``__copy__``. It makes no sense to deny the possibility of shallow copying.

**Comment by bernie-simon** [comment]
In what way would you expect the result of a copy of a DataModel to be different from a deepcopy of a DataModel?

**Comment by mcara** [comment]
I expect the result of ``__copy__()`` (**not** the method ``copy()`` in ``DataModel``) to return a *shallow* copy. Citing [Python documentation](https://docs.python.org/2/library/copy.html):

> The difference between shallow and deep copying is only relevant for compound objects (objects that contain other objects, like lists or class instances):

> - A *shallow copy* constructs a new compound object and then (to the extent possible) inserts *references* into it to the objects found in the original.

> - A *deep copy* constructs a new compound object and then, recursively, inserts *copies* into it of the objects found in the original.

**Comment by hbushouse** [comment]
As of today the original problem seems to have been solved:
```
In [1]: import copy

In [2]: from jwst.datamodels import DataModel

In [3]: copy.deepcopy(DataModel())
Out[3]: <jwst.datamodels.model_base.DataModel at 0x1197f29b0>
```
Are there other changes that were desired, for which we should keep this issue open?

**Comment by mcara** [comment]
@hbushouse Where was this fixed? I would like to see how...

**Comment by bernie-simon** [comment]
The fix which modified the copy behavior was "[Use a shallow copy when opening an image from another image](https://github.com/STScI-JWST/jwst/commit/600713febdccc856304eb53359005be5570f85b5#diff-458aa15d1359866095ef3864c45d9f45)" on June 30, 2017

**Comment by bernie-simon** [comment]
The reason for not having __copy__ do a shallow copy was that examining the way copy was used in the jwst pipeline indicated that a deep copy was expected and to do otherwise would require a rewrite of existing code.

**Comment by mcara** [comment]
> The reason for not having **copy** do a shallow copy...

What do you mean here by the **BOLD** "copy" above? That is, what is **copy** above referring to?

**Comment by bernie-simon** [comment]
The silly markup converted double underscore to bold.

**Comment by mcara** [comment]
Allright. So @hbushouse while the initial issue leading to the crash described here probably was fixed, in my opinion the fundamental issue of ``__copy__`` being replaced with ``__deepcopy__``: https://github.com/STScI-JWST/jwst/blob/e897dd6552149003c927d182f8e9979e11ca7195/jwst/datamodels/model_base.py#L282. In my opinion this is *really, really bad* (see my comment https://github.com/STScI-JWST/jwst/issues/284#issuecomment-249605296) and instead of making objects that behave in unexpected ways, the code should be fixed to either explicitly call ``deepcopy()`` or to call DataModel's ``.copy()`` method. Overwriting built-in ``__copy__`` is bad, in my opinion: If I do need a shallow copy, how would I do it???

**Comment by mcara** [comment]
> The reason for not having `__copy__` do a shallow copy was that examining the way **copy was used in the jwst pipeline** indicated that a deep copy was expected...

I just "examined" the code and I cannot find a *single* instance of code that calls `__copy__()` on a `DataModel`.

I think you should replace

```python
__copy__ = __deepcopy__ = copy 
```

with 

```python
__deepcopy__ = copy 
```
