### ISSUE TITLE
Update WFS Combine regression tests

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2843]
With the update of the algorithm in #2841 and with test data now available, the regression tests for the wfs_combine step should be updated.   The test is currently failing in the Nightly Regression test and could be marked as xfail.

**Comment by stscicrawford** [comment]
Information and data listed in issue #1615

**Comment by jdavies-st** [comment]
The existing input files were run through `assign_wcs` again and a new truth file generated.  Fixed.
