### ISSUE TITLE
Deprecate csv_tools package

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2870]
# Issue
`csv_tools` was born out of a DMS design discussion many years ago. The issue was that association pools and associations themselves were not FITS files, yet there was some DMS requirement stating something along the lines of "all output products must be in FITS". This package was developed to hedge against having to formally satisfy that requirement. Sometime afterwards, official proclamation stated that this type of data did not have to satisfy said requirement. Hence, this package has never been used by SDP, nor has need ever been defined in terms of JWST calibration either. As such, there is not explicit reason to have such a package withing JWST.

**Comment by nden** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2041](https://jira.stsci.edu/browse/JP-2041)._

**Comment by jdavies-st** [comment]
Instead of deprecating this subpackage, is there any objection to just removing it?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2041?focusedCommentId=520843#comment-520843):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham)

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2041?focusedCommentId=520854#comment-520854):_

Yes, please remove completely, from all history. There may already be an existing github-only issue regarding this.
