### ISSUE TITLE
Use stpipe on a different instrument

### ISSUE THREAD

**Issue by zonca** [spacetelescope/jwst#2883]
Thanks for releasing this package!

I am working on [IRIS-TMT](https://irlab.astro.ucla.edu/iris/) and we are evaluating if we can use `stpipe` for our online and offline pipelines.

Would you have any suggestion on this? Is anyone else using it outside of JWST?
Do you think we only need to implement subclasses of `Step` tailored to our instrument or we could need to tweak some of the `stpipe` internals?

**Comment by sosey** [comment]
copying @perrygreenfield  and @hbushouse

**Comment by stscieisenhamer** [comment]
Ideally, one will only need to subclass `Step` or `Pipeline`.  There is [some documentation ](https://jwst-pipeline.readthedocs.io/en/latest/jwst/stpipe/index.html)to get started on this.

The thing that may be a trick is, if needed, separating out CRDS.

**Comment by perrygreenfield** [comment]
If CRDS is hardwired in, if possible we should modify stpipe so that CRDS support is optional. I don't know the current situation though.

**Comment by perrygreenfield** [comment]
Though if you plan on having standard calibration files that will change over time and an archive to associate calibration files with data, you might take a look at CRDS too. It solves many (but not all) of the headaches of managing the calibration files and how they should be applied to the data. There's even a paper that describes it: https://www.sciencedirect.com/science/article/pii/S2213133716300221?via%3Dihub

It's a significant software project with less than trivial installation and learning curve. But if you need something like this in the long run, it's worth looking at, particularly if you haven't had an experience in dealing with the issues that are bound to come up in maintaining such files on a production telescope.

**Comment by zonca** [comment]
Yes, I agree that using CRDS would be the best choice, I'll propose it.

About `stpipe`, I tested it on some IRIS simulations (https://github.com/zonca/IRIS-data-reduction-tests/tree/201810_stpipe_image_bg_subtraction_flat/201810_stpipe_image_bg_subtraction_flat) using a NIRCAM pipeline. Of course it required to set some NIRCAM metadata. Once we reimplement all the steps and pipelines for IRIS, running them with `stpipe` won't have anything JWST specific, right? I assume `stpipe` is agnostic of the instrument and CRDS is only accessed by the steps.

**Comment by stscieisenhamer** [comment]
`stpipe` should be agnostic of instrument.  Ideally, as long as a properly constructed `DataModel` exists, the architecture and even a good number of the existing steps should not care.

**Comment by zonca** [comment]
thank you very much @stscieisenhamer @perrygreenfield for your feedback!

**Comment by zonca** [comment]
I made `stpipe` work with IRIS for a simple flat-fielding, hacking `stpipe` and CRDS, now I'd like to clean up the implementation and decouple the IRIS specific changes into separate packages.

First I need a custom schema for `DataModel` (for now [I modified JWST's ](https://github.com/zonca/jwst/pull/1/files#diff-36c6d2a5f9ab1698341e80bc05ed47e6)], can you please recommend how I should configure `stpipe` so that it uses a custom schema for my pipelines?
