### ISSUE TITLE
Improve support for WFSS data.

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#2898]
EXP_TYPE = NRC_TSGRISM needs to be added to the list of WFSS exposure types in `extract_1d`.  For this mode, the wavelength attribute is not populated by `extract_2d`.  When the output of `extract_2d` is then opened by `extract_1d`, because the model is a `SlitDataModel` object, the wavelength attribute is 3-D (`extract_1d` expects 2-D), and the wavelength values are uninitialized.  The wavelength section of slitdata.schema.yaml should specify "ndim: 2" and "default: 0.0".

**Comment by hbushouse** [comment]
Fixed by #2911
