### ISSUE TITLE
Update documentation to describe TSO pipeline configs for level2

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2901]
Describe the `calwebb_tso-image2.cfg` and `calwebb_tso-spec2.cfg` configuration for the level 2 TSO pipelines in our docs.

**Comment by hbushouse** [comment]
FYI, I've started working on a complete rewrite and restructuring of everything in /docs/jwst/pipeline/ and will incorporate the tso2 pipeline cfgs in there.

**Comment by hbushouse** [comment]
Fixed by #3000
