### ISSUE TITLE
Add call method example that includes the "steps=" argument

### ISSUE THREAD

**Issue by aliciacanipe** [spacetelescope/jwst#2921]
It might be helpful for pipeline users if there was an example in the documentation that shows how to run the pipeline from within Python without a config file, using the "steps" argument instead, e.g.:

`Image3Pipeline.call("asn.json", steps={"tweakreg":{"skip":True}, "skymatch":{"skip":True}, "source_catalog":{"output_file":"test_cat.ecsv"}})`

This issue came up from a discussion on Slack about how to get the Image3 pipeline to save out the catalog using this method.

**Comment by nden** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2042](https://jira.stsci.edu/browse/JP-2042)._

**Comment by jdavies-st** [comment]
This is I think addressed in the existing PR

https://github.com/spacetelescope/jwst/pull/5901/files#diff-671d5f3aeebc17f597458363501baa840f0aa3e8643925da56acbd5d93ad4c2fR34

which is not merged yet.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2042?focusedCommentId=521353#comment-521353):_

Fixed by #5901
