### ISSUE TITLE
collect_pipeline_configs imports drizzle

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#2976]
Is there a reason the collect_pipeline_configs script needs to import the drizzle packages?  I didn't have it installed in my jwst environment, but wonder if it's truley needed to load the configs....I think it's getting called on the import of the jwst package, which is used to find where the config files are located.

Wondering if we can use something more like this to avoid the actual import of jwst

> import importlib
> jwst = importlib.find_loader("jwst")
> jwst.path

**Comment by jdavies-st** [comment]
Looking at the `jwst` import, it's because there's a bunch of namespace imports in `jwst.pipeline.__init__` that these get pulled in.  Yeah, this has bugged me in the past as well.  Didn't realize there was an elegant solution for it!
