### ISSUE TITLE
test_detector1pipeline2 for MIRI was not testing anything

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2995]
Before the merging of #2984, the test

https://github.com/spacetelescope/jwst/blob/dcd5d7d47c3aa39a7d487e584f98468890a0928c/jwst/tests_nightly/general/miri/test_sloperpipeline.py#L94-L124

was not testing anything when running on Jenkins.  I.e. it was comparing each output file with itself, as the copying of the truth file to the working test directory overwrote the test result file.  PR #2984 segregates the truth files in a `truth` subdir, so it is now testing the test output against the truth file, and failing.

@dmggh perhaps you can have a look and see if the new results are in line with what you expect after the recent updates to `ramp_fit`?

**Comment by dmggh** [comment]
I've looked at the new output, and it looks believable (based on the code change updates since the truth files were generated), so I've updates the 2 truth files.
