### ISSUE TITLE
Update x1d WFSS and TSGRISM

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#2997]
`extract_2d` for WFSS and TSGRISM mode updates the wcs in the `SlitModels` to translate between (x, y) in the slit image, and (ra, dec, wave, order).  Spectral order has already been incorporated into the WCS model and no longer needs to be specified. i.e each SlitModel will only contain data for a single spectral order.

The current code should be updated to return an error if other than 2 inputs are detected for WFSS modes. 

Even with this update the code is still struggling to return the delta wave for either direction:
> dwlx: 0.0
> dwly: 0.0
> dispaxis = None

I think this is because, for WFSS, 1 pixel doesn't appear to be far enough away to get a measurable change in wavelength, so it gives up. I played with x1d in this PR, and it completes with an extraction, though there is no flux. This is either cause I have no idea what I'm doing for x1d, or from the fact that the test image doesn't really have sources. Need lots of discussion with @philhodge for judicious review of what I did  🤦‍♀️. I subbed looking  for wavelengths to just checking on the size of the extraction. This just assumes that the dispersion is in the direction
of the largest box extent. This is probably not a complete solution, but I don't think that the dispersion extent for any WFSS mode should be less than the cross dispersion size of the object, possibly not true for irregular, non-symmetrical objects.
<img width="1019" alt="screen shot 2018-12-21 at 9 04 01 pm" src="https://user-images.githubusercontent.com/503615/50369482-6e7c0200-0564-11e9-80b7-8f22da578cab.png">

This branch has both the ninput update and the experiment with extraction: https://github.com/sosey/jwst/tree/update-x1d-wfss

**Comment by sosey** [comment]
An alternate solution for detecting the extraction direction is hard coding it using meta information that tells us the instrument and grism in use. The code in extract_2d for wfss doesn't care about specifiying the extraction direction, just finding the box corners, they are somewhat related to each other though. As the instrument teams improve the trace polynomials after launch they will become variant in x and y, niriss having the more curved trace projection.

**Comment by philhodge** [comment]
@sosey Could I see the data?  I'd like to see the output of extract_2d.  If extract_1d can't find the dispersion direction, it could be that extract_1d is not calling the WCS function correctly for this type of data.  Or is there a wavelength attribute for each slit?  In any case, I need to run some tests.

**Comment by sosey** [comment]
There's a copy of the data in /grp/jwst/ssb/sosey/niriss/test_nis_wfss_spec20/

**Comment by hbushouse** [comment]
I'm guessing this issue is now moot, given the addition and use of the DISPAXIS keyword in #3799, since it appears the only issue here was related to figuring out the extraction/dispersion direction. @hodge and @sosey can you confirm?

**Comment by philhodge** [comment]
This is only partly correct.  Yes, the DISPAXIS keyword will give the correct dispersion direction, and extract_1d will use that to determine how to extract the data.  Another serious problem is that the wavelengths have only two values (0.75 and 2.3) in the horizontal (cross-dispersion) direction, and along every column the wavelengths are constant.  combine_1d will fail because of that.

**Comment by hbushouse** [comment]
Are those wavelength value problems due to something in our code or just bad data in the WCS reference files for (at least some of) the grism modes?

**Comment by hbushouse** [comment]
Fixed by https://github.com/spacetelescope/jwst/pull/3891
