### ISSUE TITLE
Regression tests that don't use compare_outputs don't upload failed results to Artifactory

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#3007]
It would be useful if all failing tests upload their results to artifactory.
```
miri/test_miri_steps_single.py::TestMIRIWCSFixed::test_miri_fixed_slit_wcs
miri/test_miri_steps_single.py::TestMIRIWCSSlitless::test_miri_slitless_wcs
```
are 2 examples.  There are probably a few more.

**Comment by dmggh** [comment]
I agree, it would be very useful.

**Comment by jdavies-st** [comment]
No, there is not. And I don't think there should be.  I think there's a more-simple solution here - just generate the upload script, and if the test fails, write it out.

**Comment by jdavies-st** [comment]
Since we've switched to the new regression test suite in `jwst/regtests` and no longer used `compare_outputs`, this is no longer an issue.
