### ISSUE TITLE
Make tweakwcs use WCS's bounding box instead of image size

### ISSUE THREAD

**Issue by mcara** [spacetelescope/jwst#3012]
This is the real issue that needs to be fixed instead of fixing "runaway processing" - https://github.com/spacetelescope/jwst/issues/3009

I do not know whether to classify this as a bug or an enhancement. The issue is that tweakreg attempts to compute the bounding box of an image based on the image size/shape. For unknown to me reasons (yet), MIRI's WCS returns `nan` for a coordinate such as `(-0.5, -0.5)` (corner of the first pixel).

CC: @stscieisenhamer @jdavies-st @nden

**Comment by jdavies-st** [comment]
Yeah, for this MIRI imaging dataset, the valid area of the WCS is slightly smaller, i.e. the `bounding_box` is not the full image array.  So using the `wcs.bounding_box` corners instead of the image corners might be the best general solution.
