### ISSUE TITLE
Make bounding boxes from shape clearer to understand and implement

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#3013]
This started from a discussion with @philhodge about the bounding boxes coming out of the wfss pipeline....but after discussion with @nden it seems to be unclear in general.

When creating bounding boxes:
* attached to a wcs object, the tuple should be a range in (x, y) order
* attached to a transform (for example a wcs frame transform), the tuple should be a range in (y, x) order

There are three functions in `assign_wcs.util` to help with this, but they are misleading:
* https://github.com/spacetelescope/jwst/blob/master/jwst/assign_wcs/util.py#L665
* https://github.com/spacetelescope/jwst/blob/master/jwst/assign_wcs/util.py#L683
* https://github.com/spacetelescope/jwst/blob/master/jwst/assign_wcs/util.py#L713

We need to update the functions to be clearer what their input and use should be

**Comment by nden** [comment]
Resolved by #3014
