### ISSUE TITLE
TypeError in datamodels/model_base.py

### ISSUE THREAD

**Issue by gkanarek** [spacetelescope/jwst#3030]
Tried to save an asdf file, and got this:

```
  File "/Users/gkanarek/miniconda3/envs/nirspecref/lib/python3.5/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.5-macosx-10.6-x86_64.egg/jwst/datamodels/model_base.py", line 550, in to_asdf
    inline_threshold=inline_threshold).write_to(init, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'inline_threshold'
```

**Comment by gkanarek** [comment]
You can see it in the "file" part of the traceback: `jwst-0.13.0a0.dev146`.

**Comment by gkanarek** [comment]
Should I roll back to 0.12.3?

**Comment by drdavella** [comment]
@gkanarek I think you need to update `asdf` in your environment. You can probably just do `pip install --upgrade asdf`.

**Comment by drdavella** [comment]
Er, actually, that's not quite right. But there is a mismatch between the `asdf` and `jwst` versions in your environment. Are you trying to run `jwst` from a particular release, or do you have a dev version installed in your environment? If the latter, you might need to pull down the latest `master`.

**Comment by nden** [comment]
@gkanarek  As @drdavella mentioned there's a version mismatch.  It looks like you are running conda dev but have not updated recently. If this is not on purpose you can update your environment and this should fix the issue. You should get jwst version `0.13.0b.devxxx`. 

Please post if you are actually trying to stay with an old version of the pipeline.

**Comment by nden** [comment]
@gkanarek Was this resolved? Can we close the ticket?

**Comment by jdavies-st** [comment]
Closing.  Reopen if this is still a problem.
