### ISSUE TITLE
Confusion between integer index arrays and Boolean indexing

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#3044]
Two functions in extract1d.py in the `extract_1d` step use the following syntax to get an index array and the number of non-NaN elements in a column of an image:

    good = np.isfinite(val)
    npts = good.shape[0]

However, `np.isfinite` returns a Boolean index array.  This has the same shape as `val`, so `good.shape[0]` is the total number of elements in `val`, not necessarily the number of good elements.  This can be fixed by using:

    npts = good.sum()

Using `good.shape[0]` would have been OK if `good` were a tuple containing a `numpy` array (just one array, in this case) giving the indices of all the good (non-NaN and non-Inf) elements in `val`.  Such a tuple could be obtained by using `good = np.where(np.isfinite(val))`.

Actually, there should not be any NaN or Inf values in the science data, but it still should be fixed.

**Comment by hbushouse** [comment]
Fixed by #3045.
