### ISSUE TITLE
Remove hardcoded observatory in crds client

### ISSUE THREAD

**Issue by zonca** [spacetelescope/jwst#3050]
I am trying to adapt `stpipe` for another instrument (see #2883).

Would it be possible to parametrize the `observatory` input keyword in `_get_refpaths` so I can customize it without modifying the `stpipe` codebase?

See https://github.com/spacetelescope/jwst/blob/74f15a7837e5f490606aefc02f2cf02ef8903d83/jwst/stpipe/crds_client.py#L101

Thanks!

**Comment by stscicrawford** [comment]
Pull requests are welcome!   I don't think there would be any problem in parameterizing it, but we can also determine if so during a review.   While small, this might not be high priority right now for us so submitting it as a pull request would see it implemented much sooner.

**Comment by jaytmiller** [comment]
This is not a problem to parameterize per-say in the crds_client module.   However...

Observatory is currently restricted to 'hst' or 'jwst' in the core CRDS library.

So the suggested change might eventually make sense in the context of using stpipe for HST,  but any other application probably has a large amount of core CRDS library work to support a new observatory and the observatory's associated instruments and reference types.

What is the use case for this?   Are you still interested?

**Comment by zonca** [comment]
thanks @jaytmiller for your feedback,

I want to use `stpipe` as the foundation for the [IRIS-TMT](https://irlab.astro.ucla.edu/iris/) pipeline.
I have already a simple flatfielding test that works modifying the core libraries both for CRDS and `stpipe` (see changes in https://github.com/oirlab/tmt-crds/pull/1 and https://github.com/zonca/jwst/pull/1).
My plan is to keep maintaining a modified version of CRDS but I'd like instead to use your released version of `stpipe`.

It would be great if you can parametrize this in `crds_client` or give me some hints on how to implement it so I can contribute a PR.

**Comment by jaytmiller** [comment]
Wow,  you're way ahead of the game,  never expected to see this!
I can parameterize observatory in crds_client in an hour or so.   I'll get it.

**Comment by jaytmiller** [comment]
I did a first cut on this.   Please try it out,  and if you notice something missing,  do a pull request.

**Comment by zonca** [comment]
awesome, thanks @jaytmiller! it works great
