### ISSUE TITLE
doctests are leaving behind output files in the jwst repo

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#3053]
Since the merging of #3003, when one runs the unit tests locally, the following files get left behind:
```
	jwst/associations/tests/new_distortion.asdf
	jwst/associations/tests/niriss_photom_0001.fits
	jwst/associations/tests/reffile.asdf
```
These are produced by doctests.  Doctests should not be writing out files to the local repo.  Two solutions:

1) Use a _tmpdir_ fixture that [autodetects for doctests](https://stackoverflow.com/questions/46962007/how-to-automatically-change-to-pytest-temporary-directory-for-all-doctests).

2) Comment out any `write()` or `save()` methods in the documentation.

Preferences?

The offending docs:

https://github.com/spacetelescope/jwst/blame/master/docs/jwst/assign_wcs/asdf-howto.rst#L120

https://github.com/spacetelescope/jwst/blame/master/docs/jwst/assign_wcs/asdf-howto.rst#L133

https://github.com/spacetelescope/jwst/blame/master/docs/jwst/references_general/photom_reffile.rst#L254

**Comment by stscieisenhamer** [comment]
The main culprit seems to be [test_asn_edit](
        jwst/jwst/associations/tests/test_asn_edit.py
      ).

**Comment by jdavies-st** [comment]
Ah, right.  That explains why these files are showing up in `jwst/associations/tests/`.  The above 3 doctests are why files are getting written out at all.  So maybe it will require 2 PRs to fix this.
