### ISSUE TITLE
create the master background step as a NOOP

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3082]
Initially identified tasks - 3 sp

- [x] Write the step module and the cfg file
- [x] specify a user parameter for the user supplied 1d file
- [x] input is a ModelContainer, (or AT, single file)  
- [x] the step status should be updated - FITS kw S_MSBSUB
- [x] the step should save the output
- [x] ~~Add the step result suffix to the standard locations; set suffix in step~~ Move this into the future
- [x] Record the file name of the 1D bckg file used in the FITS header  
- [x] File keyword dict tickets
    - [x] keyword `S_MSBSUB` is step completion status of Master background step
    - [x] keyword `MSTRBKGD` is User-supplied master background file

**Comment by jdavies-st** [comment]
A clarification on recording in the SCIENCE FITS header the 1D background file name used - this can only be done if
```
MasterBackgroundStep.call(input, user_background="my_amazing_background.fits")
```
or if the computed one from the association is written out to file
```
MasterBackgroundStep.call(input, save_background=True)
```
Neither of these will be the default for this step when running in `Spec3Pipeline`.  So do we still want to record this?  And just not populate it in the default mode?

**Comment by hbushouse** [comment]
Yes, I would populate the keyword whenever `user_background` is not None.

**Comment by jdavies-st** [comment]
JWST Keyword Dictionary requests filed:

https://jira.stsci.edu/projects/JWSTKD/issues/JWSTKD-300
https://jira.stsci.edu/projects/JWSTKD/issues/JWSTKD-301
