### ISSUE TITLE
sprint1- Master background subtraction manual mode

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3088]
Feb 4 - 18: 

For all observing modes (NIRSpec FS, IFU, MOS; MIRI LRS, MRS) covered by the spectroscopic master background step a user should be able to supply a 1-D spectrum to be used as the master background. This 1-D background spectrum is re-projected into the 2-D space of all source data and subtracted from it. This bypasses the construction of the 1-D master background spectrum.

Tasks:
- [x] #3082
- [x] #3083
- [x] #3084
- [x] #3085
- [x] #3086
- [x] #3087

**Comment by hbushouse** [comment]
Relates to #3076

**Comment by nden** [comment]
Closing sprint 1. Re: #3085 - the tests were written. understanding and validating the results is moved to the next sprint.
