### ISSUE TITLE
caldetector1 needs to allow for MIRIRampModel as input

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#3097]
The `calwebb_detector1` pipeline module currently loads its input explicitly into a `RampModel`, without checking to see if the input data are from MIRI and hence should be loaded into a `MIRIRampModel`. That means MIRI-unique elements, like the REFOUT data extension, are not loaded into the data model. Fortunately at this time none of the MIRI-unique elements is used anywhere in the pipeline, but they should be available.

`calwebb_detector1` should be updated to check for MIRI as input and load into a `MIRIRampModel` in those cases.

**Comment by stscirij** [comment]
The calwebb_detector1 pipeline can easily be fixed to load a MIRIRampModel, but the first step in the pipeline explicitly opens its input as a RampModel, so every step after this has a RampModel.
The most straightforward way of handling this is to add the refout attribute to the RampModel schema, and eventually do away with the MIRIRampModel (it's hardly ever used in the cal code).

**Comment by jdavies-st** [comment]
Is there a reason we couldn't add the MIRI-specific data extensions to the normal `RampModel` schema and get rid of `MIRIRampModel`?  Everything in the schema is optional, so as long as `RampModel` is a superset of everything needed by MIRI and the other instruments, it would be fine I think.

**Comment by hbushouse** [comment]
That's the approach that @stscirij and I discussed yesterday. If we can simply add the REFOUT extension to the generic ``RampModel`` and not have dummy or zero-filled versions of it appear in non-MIRI FITS files, then that's definitely the way to go. Back when the custom ``MIRIRampModel`` was created, it didn't seem possible to have extensions treated as optional.

**Comment by jdavies-st** [comment]
As long as `refout` is not accessed in `RampModel.__init__()` or anytime else in the processing of MIRI data, then it won't appear with dummy zero values.

**Comment by stscirij** [comment]
Yes, I just made the change to my local copy of datamodels, and adding the refout extension to the RampModel schema even with a default value of 0.0 doesn't create a refout array for non-MIRI data until it's accessed directly.  i.e. it doesn't appear in the .info() method, but as soon as you do non_miri_model.refout it appears.
I think for now we should keep the MIRIRampModel but update datamodels.open so that MIRI data return a RampModel.  The only place I really see much use of the MIRIRampModel is in the tests.

**Comment by jemorrison** [comment]
If you think you are going to delete the MIRIRAmpModel let me know. The MIRI team is developing all our commissioning tools based on the JWST pipeline models. I do not know if any tools have been using
the MIRIRampModel but it seems like it would be best to warn the team that might go away and to use
the generic RampModel instead

**Comment by hbushouse** [comment]
Fixed by #3546
