### ISSUE TITLE
Issue with make_header output file

### ISSUE THREAD

**Issue by jotaylor** [spacetelescope/jwst#3099]
While using make_header I found that something is wrong in the RELSENS2D (8th) extension. I created the file like so:
`make_header NIRISS NIS_WFSS 1 test_wfss1_new.fits`

I tried to see what the structure of the file was like, but encountered this error:
```
> fits.info("test_wfss1_new.fits")                                                                                                  
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
 [astropy.io.fits.card]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-06a5b374c598> in <module>
----> 1 pf.info("test_wfss1_new.fits")

~/anaconda3/envs/jwst_dev/lib/python3.6/site-packages/astropy/io/fits/convenience.py in info(filename, output, **kwargs)
    730     f = fitsopen(filename, mode=mode, **kwargs)
    731     try:
--> 732         ret = f.info(output=output)
    733     finally:
    734         if closed:

~/anaconda3/envs/jwst_dev/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in info(self, output)
    992         default = ('', '', '', 0, (), '', '')
    993         for idx, hdu in enumerate(self):
--> 994             summary = hdu._summary()
    995             if len(summary) < len(default):
    996                 summary += default[len(summary):]

AttributeError: '_ValidHDU' object has no attribute '_summary'

2019-02-07 15:44:51,126 - stpipe - WARNING - The following header keyword is invalid or follows an unrecognized non-standard convention:
```

Seems like the problem begins in the 8th extension. 

```
> fits.getheader("test_wfss1_new.fits", 8)                                                                                           
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
 [astropy.io.fits.card]
```
It then prints a LOT of blank lines. Like.... thousands, millions, billions- I don't know how many because I didn't have enough time to scroll through the terminal. After the 10^? blank lines it finally prints this:
```
XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                 2048                                                  
NAXIS2  =                 2048                                                  
PCOUNT  =                    0 / number of parameters                           
GCOUNT  =                    1 / number of groups                               
EXTNAME = 'RELSENS2D'          / extension name                                 
EXTVER  =                    1 / extension value                                

2019-02-07 15:47:18,338 - stpipe - WARNING - The following header keyword is invalid or follows an unrecognized non-standard convention:
```

Likewise, looking at the data doesn't work either:
```
> fits.getdata("test_wfss1.fits", 8)                                                                                                 
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
 [astropy.io.fits.card]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-85-c75395a3d11c> in <module>
----> 1 pf.getdata("test_wfss1.fits",8)

~/anaconda3/envs/jwst_dev/lib/python3.6/site-packages/astropy/io/fits/convenience.py in getdata(filename, header, lower, upper, view, *args, **kwargs)
    190     try:
    191         hdu = hdulist[extidx]
--> 192         data = hdu.data
    193         if data is None and extidx == 0:
    194             try:

AttributeError: '_ValidHDU' object has no attribute 'data'
```

I get the same warning about the [astropy.io.fits.card] for the 9th, 10th, and 11th extensions, however the blank lines are not printed when accessing the headers and the data can be accessed just fine.

I tried opening the file as a datamodel but that also didn't work. 
```
> dm = datamodels.ImageModel("test_wfss1_new.fits")                                                                               
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
 [astropy.io.fits.card]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-89-be9d2fbd8f35> in <module>
----> 1 dm = datamodels.ImageModel("test_wfss1_new.fits")

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/image.py in __init__(self, init, **kwargs)
     22     def __init__(self, init=None, **kwargs):
     23 
---> 24         super(ImageModel, self).__init__(init=init, **kwargs)
     25 
     26         # Implicitly create arrays

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/model_base.py in __init__(self, init, schema, extensions, pass_invalid_values, strict_validation, **kwargs)
    170                                               self._extensions,
    171                                               self._ctx,
--> 172                                               **kwargs)
    173                 self._files_to_close.append(hdulist)
    174 

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/fits_support.py in from_fits(hdulist, schema, extensions, context, **kwargs)
    540 
    541     known_keywords, known_datas = _load_from_schema(hdulist, schema,
--> 542                                                     ff.tree, context)
    543     _load_extra_fits(hdulist, known_keywords, known_datas, ff.tree)
    544     _load_history(hdulist, ff.tree)

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/fits_support.py in _load_from_schema(hdulist, schema, tree, context)
    487                 return True
    488 
--> 489     mschema.walk_schema(schema, callback)
    490     return known_keywords, known_datas
    491 

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/schema.py in walk_schema(schema, callback, ctx)
    210                 recurse(items, path + ['items'], combiner, ctx)
    211 
--> 212     recurse(schema, [], None, ctx)
    213 
    214 

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/schema.py in recurse(schema, path, combiner, ctx)
    200         if schema.get('type') == 'object':
    201             for key, val in schema.get('properties', {}).items():
--> 202                 recurse(val, path + [key], combiner, ctx)
    203 
    204         if schema.get('type') == 'array':

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/schema.py in recurse(schema, path, combiner, ctx)
    187     """
    188     def recurse(schema, path, combiner, ctx):
--> 189         if callback(schema, path, combiner, ctx, recurse):
    190             return
    191 

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/fits_support.py in callback(schema, path, combiner, ctx, recurse)
    465                 'max_ndim' in schema or 'ndim' in schema or 'datatype' in schema):
    466             result = _fits_array_loader(
--> 467                 hdulist, schema, ctx.get('hdu_index'), known_datas)
    468 
    469             if result is None:

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/fits_support.py in _fits_array_loader(hdulist, schema, hdu_index, known_datas)
    427 
    428     known_datas.add(hdu)
--> 429     return from_fits_hdu(hdu, schema)
    430 
    431 

/user/jotaylor/git/jo_jwst_fork/jwst/jwst/datamodels/fits_support.py in from_fits_hdu(hdu, schema)
    563     Read the data from a fits hdu into a numpy ndarray
    564     """
--> 565     data = hdu.data
    566 
    567     # Save the column listeners for possible restoration

AttributeError: '_ValidHDU' object has no attribute 'data'

2019-02-07 15:54:28,308 - stpipe - WARNING - The following header keyword is invalid or follows an unrecognized non-standard convention:
```

I found the same errors when making a NIRCAM/IMAGE header too. I am using the jwst dev environment and jwst version 0.13.0b.dev93+g3c5068be

**Comment by jdavies-st** [comment]
Hmm, I think `ImageModel` should not have a `relsens2d` extension, but that is probably unrelated to the actual error message here coming from `make_header`.

**Comment by jotaylor** [comment]
I'm a jwst data newbie but it is specified in the ImageModel schema, which I think is what make_header consults. I agree though, it shouldn't be in this data and I'd probably remove it in further processing 😅

**Comment by jotaylor** [comment]
Just tried this again with the latest jwst version (0.13.0b.dev295+g42121673) and am getting the same errors. It's still barfing on the 8th extension, except now it's the VAR_POISSON ext and not RELSENS2D. Exts 0-7 still work fine.

**Comment by jotaylor** [comment]
Seems to me like the problem is in the RELSENS extension. When I remove it from the ImageModel schema everything works fine. Perhaps because it's a table and not an image hdu? In `make_header.fill_extension` it attempts to fill an extension with an empty image, so that seems like a problem for a BinTable.
https://github.com/spacetelescope/jwst/blob/e91a8e0d682e1f31dbca540067d4f4b3b217cff3/jwst/datamodels/make_header.py#L254

**Comment by jdavies-st** [comment]
Well, I tried this out myself:
```
$ make_header NIRISS NIS_WFSS 1 test_wfss1_new.fits

$ fitsheader test_wfss1_new.fits > header
```
and had a look at the header.  It is doing a number of very wrong things I believe.

1. The bug you report @jotaylor is that it is populating everything in the schema, which it definitely should not be doing.  It only should be populating `data` for `ImageModels`.  Instantiating the model automatically takes care of populating `dq` and `err`.  Nothing else should be touched.  Is there a reason that the data arrays in the FITS file are being populated?

2. It looks like it is trying to create an `ImageModel`.  Is this correct if I specify the level 1 pipeline?  Or is this script supposed to be used to create something that would be the result of the level 1 pipeline? This is not documented anywhere in the code, but the calling script suggests the former.  Is this your understanding @jotaylor?  If this is the case, then it should not be an `ImageModel` but a `Level1bModel`.  If it handled this properly, then it would not even be looking for a `relsens` table.

3. Looking at the generated header, it also looks like it is populating a bunch of 3rd-axis WCS keywords, which we've never wanted populated. So that needs to be fixed too.

4. It also populates a bunch of the R_xxxx keywords giving reference file names.  But those only get populated once the pipeline is run, so I don't think these should be there either.  @hbushouse ?

5. There are no tests that test any of this.  Just a simple smoke test to make sure it runs and produces something.

So there's some work that needs to be done here.

**Comment by hbushouse** [comment]
Regarding the R_xxxx keywords, you're right that it's not necessary to have them in the template header, because they are used only as output, not input (i.e. the cal pipeline doesn't need them to run). On the other hand, it also shouldn't hurt anything to have them there on input (they'll just get ignored until populated).

**Comment by sosey** [comment]
re the R_XXXX keywords,  in the past, SDP wanted all keywords that would be cataloged on ingest to be present in the input files. Though it may not matter for this particular case, depends on how much you want to mimic SDP practice I guess.

**Comment by hbushouse** [comment]
This routine, `make_header` is not for use for creating anything that would be used by SDP or go into the archive. It's strictly for users to use as a convenience tool for knowing what keywords are needed by the cal pipeline when, for example, creating simulated images. Even if they did end up trying to archive the calibration products from these, it should be OK to leave out the R_xxxxx keywords in the inputs, because that's the way level-1b files come out of DMS/SDP processing: no R_xxxxx keywords (or S_xxxxx step status keywords). Cal adds them as necessary when steps and reference files get used. Archive knows they are optional keywords.

**Comment by jotaylor** [comment]
Also, to comment on @jdavies-st's observation- it is sometimes useful to create headers for an `ImageModel` output fits file, but it would much more useful to create headers assuming a `RampModel` output file for immediate pipeline use. 
The NIRISS team has been trying to design ways to create reliable and future-proof simulations, and a big part of that is making headers that are pipeline-compliant. The `make_header` tool is the perfect solution, so any progress on addressing the bugs would be greatly appreciated 😄 @hbushouse

**Comment by hbushouse** [comment]
Closing this issue, because the `make_header` tool is no longer being supported. Functionality has been mostly replaced by the ability to create schematic headers in the JWST Keyword Dictionary (https://archive.stsci.edu/jwst/keyword/latest/)

**Comment by jdavies-st** [comment]
Should we formally deprecate `make_header`, i.e. issue a DeprecationWarning?
