### ISSUE TITLE
Add a new column to the output table from extract_1d

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#3107]
A new NPIXELS column should be added to the 1-D extracted spectrum table, giving the number of pixels that were added together to get the net count rate.  The values will be float, because the lower and upper limits of the extraction region can include fractions of pixels.  The values can vary from pixel to pixel in the dispersion direction, and it can be difficult to determine this value unambiguously from the reference file (if any).  This is needed for the master spectroscopic background subtraction step, issue #2308.

**Comment by hbushouse** [comment]
Fixed by #3108
