### ISSUE TITLE
MBGS: NRS IFU data

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3152]
Describe Nirspec IFU data used in the master background step tests.

**Comment by nden** [comment]
The data is in /grp/jwst/ssb/chartreuse/master_background_data/nrs-ifu/

`prism_sci_bkg_cal.fits`: science + background output of calwebb_spec2; input to master_background
`prism_bkg_x1d.fits`: extracted 1D background spectrum, input to master_background

`prism_sci.fits` : the orignal rate file
`prism_sci_cal.fits`: output of calwebb_spec2 of the original file
`prism_bkg_rate.fits`: background rat efile
`prism_bkg_cal.fits`: background output of calwebb_spec2
`prism_bkg_x1d.fits.orig` : background output of extract_1d (with 2 spikes in the spectrum)
`prism_bkg_x1d.fits` : the spikes in the above file were replaced with neighbouring values
`prism_sci_bkg.fits`: sci+bkg rate image

Creating the 1D extracted background spectrum:

- the photom step was disabled
- the local background was not subtracted

```
strun calwebb_spec2.cfg prism_bkg_rate.fits --steps.photom.skip=True --steps.extract_1d.subtract_background=False
```
The science input to the master_background step:
```
strun calwebb_spec2.cfg prism_sci_bkg.fits --> prism_sci_bkg_cal.fits
```
Run the master_background_step:
```
strun master_background.cfg prism_sci_bkg_cal.fits --user_background=prism_bkg_x1d.fits
```

**Comment by nden** [comment]
![prism_diff](https://user-images.githubusercontent.com/1110361/53434972-b3d60900-39c5-11e9-8708-9f921fedec31.png)

**Comment by nden** [comment]
![prism_diff_hist](https://user-images.githubusercontent.com/1110361/53434992-be909e00-39c5-11e9-8bff-2b48706e490b.png)

**Comment by nden** [comment]
After discussing the background plot with @philhodge and @hbushouse it was determined that the features we see are result of applying the flat_field step to fake background which did not have the flat_field in the signal. So I ran the test skipping the flat_field and photom step. I replaced the files in the common area with the so created ones and copied the processing log there.

Here're some results:

The first one is the plot of the extracted science spectrum (without background) with the overplotted output of the master_background step.

![diff_x1d](https://user-images.githubusercontent.com/1110361/53530163-08a87b00-3abd-11e9-8319-33f7fd5a13c6.png)

The difference of the original (no background) image with the master_background corrected image:
![diffsci](https://user-images.githubusercontent.com/1110361/53530211-207fff00-3abd-11e9-8917-58a5c3e064f2.png)


The histogram of the above difference
![hist_diffsci](https://user-images.githubusercontent.com/1110361/53530220-2b3a9400-3abd-11e9-8077-43c5a1ca8fc9.png)

**Comment by jemorrison** [comment]
Comparison of the 1-D extraction looks great. This plot shows the same as Nadia's above it just has the added plot  of subtracting the two spectra
![compare_nirspec_fs_1d_4](https://user-images.githubusercontent.com/18491225/53683300-648d2280-3cbc-11e9-9074-7a4f86efce7b.png)

I am not sure I have the test correct for subtracting the masterbackground subtracted image from
the science image. I looped over each slice and I test each slice. I have a plot of two slices below
and I may not understand the bounding box. I thought the bounding box is for each slice not
all the slices. But my plots look strange - some of the slices seem to fill the plot and others do not.
Here is my code for extracting the regions. I will go ahead and make a pull request for this new code in
the regression tests, but I am not sure I have the NRS IFU case right.

   # Test 2                                                                                                  
      for i in range(30):
         print('slice ',i+1)
         slice_wcs = nirspec.nrs_wcs_set_input(input_sci,i)
         x, y = wcstools.grid_from_bounding_box(slice_wcs.bounding_box)
         ra, dec, lam = slice_wcs(x, y)
         valid = np.isfinite(lam) # this is used later for the statistics for the test but it is not used for plotting

         result_slice_region = result.data[y.astype(int), x.astype(int)]
         sci_slice_region = input_sci.data[y.astype(int), x.astype(int)]
         sci_bkg_slice_region = input_sci_bkg.data[y.astype(int), x.astype(int)]

I have assumed that fringing is causing the strips so I have assumed the stripe region is the slice on
the IFU. Here is one where I think the slice is not fully on the selected area. 
![compare_images_nirspec_ifu_slit3](https://user-images.githubusercontent.com/18491225/53683367-4aa00f80-3cbd-11e9-8898-fc89b380af40.png)

Here is one that it looks like it is
![compare_images_nirspec_ifu_slit12](https://user-images.githubusercontent.com/18491225/53683378-5d1a4900-3cbd-11e9-8a8e-57a3aa7a464d.png)
