### ISSUE TITLE
MBGS: NRS MOS data

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3153]
Describe Nirspec MOS data used in the master background step tests.

**Comment by jemorrison** [comment]
nrs_mos_sci_cal.fits - original science image, for comparison
nrs_mos_bkg_cal.fits - background signal centered at 20 DN/s with Poisson distribution
nrs_mos_bkg_x1d.fits - 1-D background spectrum for input to master background (single slit instance)
nrs_mos_sci+bkg_cal.fits - science + background, for input to master background step

nrs_mos_sci+bkg_cal.fits has  11 extracted slitlets in it (MultiSlitModel with 11 slit instances), each of which covers a little different wavelength range.

The data was created by @hbushouse:  
1. Created a bkg rate image  and then ran it all the way through calspec2 to create the bkg x1d file to use as the user-supplied master background. Note the NIRSPEC calibration factors are all set to 1.0 so the FLUX and NET columns in nrs_mos_bkg_x1d.fits are identical. The flux column is still in units of DN/s not flux.
 2. The  bkg rate image  was added to an existing sci rate image, to form a sci+bkg rate image. That sci+bkg rate image was then run all the way through calspec2 to create the sci+bkg cal image to use as input to the master background step. 

So they've both  (background and science) have been all the way through calspec2.

**Comment by jemorrison** [comment]
Plot of 1-D user background
![user_bkg_nirspec_mos](https://user-images.githubusercontent.com/18491225/53243029-d255a080-3663-11e9-8d69-0dcf68b005f5.png)

**Comment by jemorrison** [comment]
For the first slit I have made plots of the images. I labeled each image. The science plot (second plot)
with no background add has much smaller values than Sci + BKG. Is the BGK maybe too large ?
The mean of the science image for this slit is ~5.8 (I think Dn/s)
The mean of the MasterBackground Subtracted - Science (last plot) is 15.
Looking at the headers all the data has PHOTOM Completed.  The 1-D background has FLUX column = NET column. 
![compare_images_nirspec_mos_slit1](https://user-images.githubusercontent.com/18491225/53268683-fb962100-36a3-11e9-93c3-ad7cff00ccb0.png)


When I compare the extracted 1-D background subtracted spectra to 1-D extracted science spectra I get a extracted 1-D background subtracted spectra I think WAY too large given the images.
Puzzled ? Suggestions ? 
![compare_1d_1](https://user-images.githubusercontent.com/18491225/53268419-3e0b2e00-36a3-11e9-869f-fd02336f6ccb.png)

**Comment by hbushouse** [comment]
What you're seeing in the images of slit 1 above is the fact that the user-supplied background spectrum starts at a minimum wavelength of ~1.75 microns, while slit 1 spans a wavelength range of 1.65-1.94 microns, so a substantial amount of the left half of slit 1 doesn't get any bkg subtracted. The right half does, as is evidenced by the darker shades in the bottom two panels, but it's only being applied over a restricted y-axis range (bounding_box limitation I suspect) and it's also undersubtracted for some reason (still investigating that).

**Comment by jemorrison** [comment]
I put my test routine for the nrs-mos, test_mos.py, in the common area in the nrs-mos directory.
I hard coded the names of the files for the input 1-D spectrum and other files. 
The test runs the subtract mastarbackground step, run extract 1-d and plots up
various data. For each slit it creates a sub_nrs_mos_slit#.fits file that contains only data for the slit.
This fits file has primary image: science + bkg
1st extension: sci
2nd extension: master background subtracted output
3rd extension: master background subtracted - sci

I am going to add a histogram plot of the comparison between the master bakcground subtracted - sci
image to make sure I am comparing VALID pixels in the slit and not edge ones.

Let me know if you use this and have improvements.

**Comment by hbushouse** [comment]
Good news. It's been discovered that the flat-field step is imposing artifacts into the 2-D data that complicate our analysis (more on that later). So I've reprocessed all of the data files for the MOS examples with all unnecessary (or harmful) steps in calspec2 turned off, namely msa_flagging, barshadow, pathloss, flat-field, and resample_spec. All we really need is extract_2d and extract_1d to do this analysis.

- strun calwebb_spec2.cfg nrs_mos_bkg_rate.fits: produces nrs_mos_bkg_x1d.fits to use for MBS step
- strun calwebb_spec2.cfg nrs_mos_sci_rate.fits: original science data with no background added
- strun calwebb_spec2.cfg nrs_mos_sci+bkg_rate.fits: science with background added
- strun jwst.master_background.MasterBackgroundStep nrs_mos_sci+bkg_cal.fits --user_background=nrs_mos_bkg_x1d.fits
- strun jwst.extract_1d.Extract1dStep nrs_mos_sci+bkg_masterbackgroundstep.fits: produces final nrs_mos_sci+bkg_extract1dstep.fits file of background-subtracted 1-D spectra

**Comment by hbushouse** [comment]
Here are some results. First some looks at the 2-D cutouts. Here's the 2-D cutout of the background only image, showing a nice smooth signal with random noise (mean bkg signal is ~20 DN/s):
![nrs_mos_bkg_2d](https://user-images.githubusercontent.com/12860084/53517954-e94e2580-3a9d-11e9-8584-e573ba7ae670.gif)
Now here's the original 2-D science data for slit 2 (from the nrs_mos_sci_cal.fits file):
![nrs_mos_sci2_2d](https://user-images.githubusercontent.com/12860084/53518020-17336a00-3a9e-11e9-935b-0b0abc544b6c.gif)
Here's the result of using master_background to subtract the background from nrs_mos_sci+bkg_cal.fits:
![nrs_mos_sci bkg-bkg2_2d](https://user-images.githubusercontent.com/12860084/53518080-38945600-3a9e-11e9-8cbe-fca45b667011.gif)
If you look really closely, you can see that the bkg has been subtracted within a limited y-pixel range, due to the limits of the wcs bounding_box. You can see this better when I take the difference of the original science image with this background-subtracted image:
![nrs_mos_scidiff2_2d](https://user-images.githubusercontent.com/12860084/53518162-72655c80-3a9e-11e9-933b-e4bd7adc5e66.gif)
The dark region in the middle is the range over which the background subtraction was done. Areas above and below still have the additional ~20 DN/s of background signal in them. The good news here is that the mean of this difference image in the region of the bounding box is -0.027 (i.e. nearly zero), with a sigma of ~4.6, which is completely consistent with the sigma of the background being ~4.5.

I get the same results for a couple other slits on which I performed the same analysis.

**Comment by hbushouse** [comment]
Here are some results for the 1-D extracted spectra. The first plot is for slit 2, showing the background, original science, and science+background spectra:
![nrs_mos_slit2_extr1](https://user-images.githubusercontent.com/12860084/53518441-09caaf80-3a9f-11e9-9b71-91c0374bdf58.png)
The second one shows the result of overplotting the 1-D spectra from the original nrs_mos_sci_x1d.fits file for slit 2 (science only) with the result for slit 2 in nrs_mos_sci+bkg_extract1dstep.fits, which is after performing master_background subtraction. The two spectra lie right on top of one another, with a bit of noise!!
![nrs_mos_slit2_extr2](https://user-images.githubusercontent.com/12860084/53518560-4c8c8780-3a9f-11e9-98dd-d447a29c618b.png)

**Comment by hbushouse** [comment]
Here's a similar plot for slit 5. There seems to be a little bit of offset between the two spectra at the short wavelength end. Not sure what might be causing that.
![nrs_mos_slit5_extr2](https://user-images.githubusercontent.com/12860084/53518907-084db700-3aa0-11e9-8927-18d6bd93d7bf.png)

**Comment by jemorrison** [comment]
I plotted up the 1-D extracted spectra for the slits and why do slits 1,3 and 4 have such a small signal ?
Here is a plot of the 1-D extracted spectra for slit 4 from the science data and background subtracted data. I assume the messiness of the background subtracted 1-D is just the noise added to the user background. 
![compare_1d_nrs_mos_4](https://user-images.githubusercontent.com/18491225/53639593-deeb7300-3be6-11e9-8b3b-882aa2fed8c3.png)

**Comment by hbushouse** [comment]
The level of the background signal in the "nrs_bkg_cal.fits" file is ~20 DN/s per pixel, with a sigma of 4.5. When this gets summed over a 1-D extraction aperture, the bkg spectrum has a mean of ~160 and sigma ~13 (pixel to pixel in the x1d).

The various science slits were scattered around semi-randomly in the field of the "nrs_sci+bkg_cal.fits" image, so yes some of them have a lot more signal in them than others. Slits 2 and 5, for example, result in mean extracted spectra with signal in the 200-500 range, while others like Slits 1, 3, and 4 happen to fall in areas of the image that have little source signal in them, so they have extracted signals in the 10-30 range.

So your plot above, for Slit 4, is not surprising. The background-subtracted spectrum matches the mean of the original fairly well, with a scatter that's consistent with the background sigma of ~13. When I compute the difference of those two Slit 4 spectra, I get a mean of 0.58 (pretty close to zero) and stdev~16.6, which is again consistent with the bkg alone having sigma~13, plus a little more for the noise in the original source spectrum.

**Comment by jemorrison** [comment]
Ok I changed the testing code to only look at the wavelength ranges contained in both
the 1-D user spec and sci extracted 1-D.   One test in the regression test was going to be comparing
the subtracted (masterbackground 1-D spectra - science 1-D) and see how close  those
values (for the valid wavelengths) are to 0. I have found an assert_close with an atol = 50
works fine. 
@hbushouse does that seem like a reasonable value given the noise you put in the 1-D user spectra ?
![compare_1d_nrs_mos_2](https://user-images.githubusercontent.com/18491225/53658583-67353c80-3c16-11e9-976d-e82e73cf522e.png)

**Comment by jemorrison** [comment]
ok I think a better test is to take the mean of the subtracted 1-D spectra. This mean should be close to 0. For the MOS data it is except for slit 5 which was already mentioned about by Howard. The   mean is -4.4 (see second plot) 
So I could set a tolerance of absolute value (5) ?

Slit 5 results
![compare_1d_nrs_mos_5](https://user-images.githubusercontent.com/18491225/53660903-322be880-3c1c-11e9-9499-4157e05b7238.png)

**Comment by hbushouse** [comment]
I wouldn't want to inflate the tolerance for all tests to 5 just to make slit 5 fit. Maybe skip slit 5 if it's the only one that's off that far. Or we figure out why it's off.

**Comment by nden** [comment]
The results for Slit 5 need to be investigated. But in general we've agreed results look good.

**Comment by hbushouse** [comment]
A new set of files has been copied into /grp/jwst/ssb/chartreuse/master_background/nrs-mos/, which includes versions with and without `resample_spec` processing of the 2-D data. The new set of files is as follows:
- nrs_mos_bkg_rate.fits: The full-frame 2-D background image. Input to calspec2.
- nrs_mos_bkg_cal.fits: The calibrated bkg image. Output of calspec2.
- nrs_mos_bkg_x1d.fits: Extracted 1-D bkg spectrum. Output of calspec2. Input to `master_background`.
- nrs_mos_sci_rate.fits: Original full-frame 2-D science image. No bkg added. Input to calspec2.
- nrs_mos_sci_cal.fits: Original calibrated science images. No bkg added. Output of calspec2.
- nrs_mos_sci_s2d.fits: Resampled calibrated science images. No bkg added. Output of calspec2.
- nrs_mos_sci_x1d.fits: Extracted 1-D source spectra. No bkg added. Output of calspec2, with resampling.
- nrs_mos_sci_noresamp_x1d.fits: Extracted 1-D source spectra. No bkg added. Output of calspec2, without resampling.
- nrs_mos_sci+bkg_rate.fits: Full-frame 2-D image with bkg added. Input to calspec2.
- nrs_mos_sci+bkg_cal.fits: Calibrated images with bkg added. Output of calspec2. Input to `master_background` step.
- nrs_mos_sci+bkg_s2d.fits: Resampled images with bkg added. Output of calspec2.
- nrs_mos_sci+bkg_x1d.fits: Extracted 1-D spectra with bkg added. Output of calspec2, with resampling.
- nrs_mos_sci+bkg_noresamp_x1d.fits: Extracted 1-D spectra with bkg added. No resampling.
- nrs_mos_sci+bkg_bsub.fits: Bkg-subtracted calibrated images. Output of `master_background` step. (no resampling yet)
- nrs_mos_sci+bkg-bsub_s2d.fits: Resampled bkg-subtracted images. Output of `resample_spec`.
- nrs_mos_sci+bkg-bsub_x1d.fits: Extracted 1-D bkg-subtracted spectra, with resampling.
- nrs_mos_sci+bkg-bsub_noresamp_x1d.fits: Extracted 1-D bkg-subtracted spectra, without resampling.

**Comment by hbushouse** [comment]
Comparisons should be done between "nrs_mos_sci_s2d.fits" (original data with no bkg) and "nrs_mos_sci+bkg-bsub_s2d.fits" (bkg-subtracted data) for 2-D images, and between "nrs_mos_sci_x1d.fits" (original data with no bkg) and "nrs_mos_sci+bkg-bsub_x1d.fits" (bkg-subtracted) for 1-D spectra.
