### ISSUE TITLE
Bug in reference pixel correction transformation of PIXELDQ array

### ISSUE THREAD

**Issue by chriswillott** [spacetelescope/jwst#3181]
In do_fullframe_corrections and do_subarray_corrections of reference_pixels.py there are transformations of the detector coordinates from DMS to native and then back again. However the pixeldq array is not dealt with symmetrically by these two transformations because it is only changed by the first one. The result is that the pixeldq array is incorrect for every other group. I would think the best way to do the transformation is once per data cube, however it is coded as once per group. This needs to be checked and possibly corrected for every NIRDataset class. 
I am working with NIRISS data. For NIRISS, the revised code that works is:
class NIRISSDataset(NIRDataset):
    """For NIRISS data"""

    def DMS_to_detector(self, integration, group):
        #
        # NIRISS has a 180 degree rotation followed by a flip across the line
        # X=Y
        self.get_group(integration, group)
        self.group = np.swapaxes(self.group[::-1, ::-1], 0, 1)
        self.pixeldq = np.swapaxes(self.pixeldq[::-1, ::-1], 0, 1)

    def detector_to_DMS(self, integration, group):
        #
        # Just flip and rotate back
        self.group = np.swapaxes(self.group, 0, 1)[ ::-1, ::-1]
        self.pixeldq = np.swapaxes(self.pixeldq, 0, 1)[ ::-1, ::-1]
        self.restore_group(integration, group)

where in detector_to_DMS the line self.pixeldq = np.swapaxes(self.pixeldq, 0, 1)[ ::-1, ::-1] has been added to change the pixeldq array back to the original.

**Comment by chriswillott** [comment]
v0.12.3

**Comment by stscirij** [comment]
This change isn't necessary because the pixeldq values are never changed, they are only used to decide whether to include the science pixels in the processing.  So at the conclusion of processing of each group, the science pixel array is transformed and copied back to the DMS frame in the input model, while the pixeldq array is discarded.

**Comment by chriswillott** [comment]
Hi,

I don’t understand this explanation. The pixeldq array is only read once at the start of reference_pixels.py:

line 177     self.pixeldq = self.get_pixeldq()

I don’t see where it is re-defined at the start of processing each group. 

Then every time a NIRISS group is processed this array gets flipped by this line:

line 1078   self.pixeldq = np.swapaxes(self.pixeldq[::-1, ::-1], 0, 1)

The result is that the pixeldq array is incorrect for every other group. I did some testing and saw this was the case.

Cheers, Chris

**Comment by stscirij** [comment]
Hi Chris,

Sorry, I completely misunderstood your original comment, now I see what you mean and I agree with your assessment.  I'll work on a fix for this.

Thanks for spotting this!!

Robert Jedrzejewski
