### ISSUE TITLE
Set flux to zero if wavelength is out of range

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#3189]
The `extract_1d` step uses the RELSENS extension to convert net count rate to flux.  For some modes, the wavelengths in the RELSENS table do not cover the full range of wavelengths for the science data.  The conversion factor is currently set to 1 for wavelength bins that are outside the range of the wavelengths in RELSENS, resulting in flux values for those pixels that are the same as the net.  The flux should instead be set to 0 for those pixels.

**Comment by hbushouse** [comment]
fixed by #3190
