### ISSUE TITLE
Don't use CDELTn in wcs_from_footprints()

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#3250]
Instead, use the gwcs object to compute an x and y scale at the reference pixel.

Prompted by #3247.

**Comment by hbushouse** [comment]
Now that the problem with the computation of CDELTn values has been fixed (in #3248), this should no longer be a problem, but it would be good to implement eventually anyway, just to remove dependencies on the FITS WCS keywords. Low priority for B7.4.

**Comment by jdavies-st** [comment]
Also, don't use the PC matrix to get the orientation.
