### ISSUE TITLE
Level-2b ASN problem with NIRSpec dedicated backgrounds

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#3257]
SOR4b tests include program jw00626, which is NIRSpec observations of various types. In particular, Obs 09 acquires a NIRSpec IFU observation of target 5, which is listed as requiring background exposures of target 6. Obs 9 uses the dither pattern "2-POINT-NOD" and 2 filter+grating combinations, resulting in a total of 4 exposures (2 dithers * 2 gratings) for each detector, for a grand total of 8 exposures.

Obs 11 acquires the required observation of background target 6, using the same 2-POINT-NOD dither pattern and 2 filter+grating settings, resulting again in a grand total of 8 exposures.

The ASN pool created by SDP contains all of these exposures (as well as the rest of the program 00626 exposures), with the 8 Obs 9 exposures correctly given an OBSERVATION candidate ID of o009 and the 8 Obs 11 exposures given an OBSERVATION candidate ID of o011, with all 16 of those exposures also allocated to "BACKGROUND" candidate ID c1003. The BKGTARG column of the ASN pool has the correct F/T settings for the Obs 9 and Obs 11 exposures.

When ``asn_generate`` is executed on the pool, it produces the expected 16 individual o009 and o011 spec2 ASN's for each individual exposure, and it also produces spec2 ASN's for the c1003 candidate, but it produces a total of only 5 of those, instead of the expected 8. Furthermore, the contents of those 5 c1003 spec2 ASN's does not appear to be correct.

jw00626-c1003_spec2_001_asn.json contains 2 Obs 9 exposures labeled as type "science" and 2 Obs 11 expsoures labeled as type "background". There should never be more than 1 science member in a spec2 ASN.

Furthermore, the remaining 4 c1003 spec2 ASN's cover products for only 4 of the 8 source exposures in Obs 9. The remaining ones only appear in their individual o009 spec2 ASN's.

The level-2b background ASN rules apparently need some tweaking.

All of the relevant data files (ASN pool, ASN tables, and FITS data files) can be found on central store in /grp/jwst/ssb/bushouse/jwst_data/NIRSpec/IFU/SOR4b/.

**Comment by hbushouse** [comment]
Could part of the problem here be confusion in the rules due to the fact that there are 2 different kinds of backgrounds going on here? One comes from the 2-POINT-NOD dither pattern type, which indicates that the science exposures should be used as backgrounds for one another. Meanwhile, there's also dedicated background target exposures linked with the science target. Perhaps the rules just don't know how to handle such a case of apparently redundant background specs.

**Comment by stscieisenhamer** [comment]
Not that there are other issues, but the pool table is incorrect: Though proposed as "two-point-dither", the PATTTYPE column is null.  This ensures that any nodding associations are not created.  Now onto the rest of the problem...
