### ISSUE TITLE
Remove conda-dev from install instructions

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#3280]
@jdavies-st said it is possible now to use the pipeline without conda-dev. However, it is still mentioned in README. Fortunately, not mentioned on JDox anymore (https://jwst-docs.stsci.edu/display/JDAT/Obtaining+and+Installing+Software) thanks to @jhunkeler's updates.

**Comment by sosey** [comment]
The text above is a little misleading, jwst hasn't been publicly released yet, so is not part of astroconda.  If users want to install jwst itself, they need to clone the repo and install, or create a new environment as shown in the README using one of the delivery files, where those files are pulling from conda-dev major dependencies.

**Comment by jdavies-st** [comment]
Currently the `jwst` package itself has its recipe on `astroconda-dev` channel.  In our development, all the upstream dependencies are public releases, so can be retrieved from pypi via `pip` or from a combination of the `astroconda` and default conda channels.  We just started doing this though in the last few weeks.  So yes, if things look good, we will update the docs.

Of course one can just completely ignore conda and `pip install` the `jwst` package from a git checkout.  That also works.

**Comment by stscicrawford** [comment]
Closing as conda-dev has been removed from the instructions
