### ISSUE TITLE
Regression test test_nrs2_nodata_strun fails on MacOS

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#3321]
This test passes on linux in our Jenkins builds, but when run locally on a Mac, it fails:
```
____________________________ test_nrs2_nodata_strun ____________________________

envopt = 'dev', _jail = None

    @pytest.mark.bigdata
    def test_nrs2_nodata_strun(envopt, _jail):
        """Ensure that the appropriate exit status is returned from strun"""
    
        data_file = get_bigdata('jwst-pipeline', envopt,
                                'nirspec', 'test_assignwcs',
                                'jw84700006001_02101_00001_nrs2_rate.fits'
        )
    
        cmd = [
            'strun',
            'jwst.pipeline.Spec2Pipeline',
            data_file,
            '--steps.assign_wcs.skip=false'
        ]
        status = subprocess.run(cmd)
    
>       assert status.returncode == 64
E       assert 1 == 64
E         -1
E         +64

../../dev/jwst/jwst/tests_nightly/general/nirspec/test_spec2.py:46: AssertionError
```

**Comment by stscieisenhamer** [comment]
Using master and bytesalad, this passes for me locally on a mac. The issue will involve wcs calculation and would be caused by anything that moves a source spectral footprint from being NRS1-only onto NRS2. Things such as model changes or even floating-point library changes, like the MKL vs. non-MKL situation, would affect footprints.

**Comment by jdavies-st** [comment]
This test now passes for all variants of our packaging - both `mkl` and `nomkl` in the conda builds, and in a `pip`-only build with Numpy from PyPI.  So not sure what PR fixed it, but this bug no longer exists.  Closing.
