### ISSUE TITLE
Ramp groups flagged with GROUPDQ=4 ("soft saturation") erroneously

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/jwst#3357]
I ran a few CV3 linearity ramps through the pipeline (version 7.2.6).  These ramps were taken in NISRAPID mode with no frame averaging so each group is an individual frame.  The signal extends to saturation in the 220 group ramps.  There are 10 such long ramps in the data set.  The output ramp slope values for some pixels are clearly wrong when compared with the raw data values:  rather than a ramp slope value of order 42 ADU/second the ramp slope values are small and sometimes negative for all 10 of the linearity ramps.  Investigation of the ramps after the linearity step for such a pixel showed that the GRUODQ flag is set to 4 for most of the groups after the first group (but not all of them, even though the signal rises continuously to saturation along the ramps), but that some of the groups that should be flagged as saturated later in the ramp were given GROUPDQ=0.  No pixels have GROUPDQ=2, although the pixel definitely saturates for the second half of the ramps.  I am assuming that this is the cause of the bad ramp slope values that are produced.

If I read the GROUPDQ definitions correctly a value of 2 indicates saturation and a value of 4 indicates possible saturation in groups that have averaging, even though the recorded value is below the saturation limit.  In this case with no group averaging I would expect that no pixels will have GROUPDQ=4.  Also the GROUPDQ=4 values start at very low signals under 1000 ADU which must be wrong for the pixel that I was looking at; the saturation values are over 30000 ADU.  Comparison of the GROUPDQ flags for one such pixel with those of an adjacent pixel with a reasonable output ramp slope shows that in the pixel which behaves normally the GROUPDQ flags are 0 up to some value around 31000 ADU after which all the values are 2, as expected.

The output files from the pipeline in this case can be found at

/ifs/jwst/wit/niriss/kevin/datareduce/newlienarity/pipeline/

The long linearity ramps are the 10 files 

NIST717-LONG-LIN-5365210033_1_496_SE_2015-12-31T21h50m33_uncal.fits
NIST717-LONG-LIN-5365214120_2_496_SE_2015-12-31T22h30m37_uncal.fits
NIST717-LONG-LIN-5365222126_3_496_SE_2015-12-31T23h10m52_uncal.fits
NIST717-LONG-LIN-5365230150_4_496_SE_2015-12-31T23h50m39_uncal.fits
NIST717-LONG-LIN-5365234222_5_496_SE_2016-01-01T00h32m22_uncal.fits
NIST717-LONG-LIN-6001002228_6_496_SE_2016-01-01T01h12m18_uncal.fits
NIST717-LONG-LIN-6001010301_7_496_SE_2016-01-01T01h52m54_uncal.fits
NIST717-LONG-LIN-6001014350_8_496_SE_2016-01-01T02h32m38_uncal.fits
NIST717-LONG-LIN-6001022356_9_496_SE_2016-01-01T03h12m38_uncal.fits
NIST717-LONG-LIN-6001030429_10_496_SE_2016-01-01T04h50m18_uncal.fits

and the output ramps and ramp slope files are in the same directory.  An example of a pixel where there is the issue is pixel x=960 y=1068 (using IRAF-like 1-based pixel numbering).  An example of a pixel with normal behaviour is pixel [961,1069].  The raw signal, linearized signal, error, and GROUPDQ flags for these pixels for the 10 sets of ramps were dumped to files pixel_values_0960_1068.data and pixel_values_0961_1069.data in the same directory, if people wish to look at the values that way (as I did) rather than trying to work with the large arrays.  In those files the first column is the group number then one has ten groups of four values, these being the raw signal, the corrected signal, the error values (all zero, it seems), and the GROUPDQ value.

When I ran the pipeline I skipped the DQINIT step to have all pixels flagged as good, so that all the pixels go through the steps I wanted to run.  However, this particular pixel [960,1068] is flagged as good in the NIRISS DQ reference file and all the linearity data for the pixel seems normal.

**Comment by KevinVolkSTScI** [comment]
Just to add the the above:  the pipeline is run via commands such as

strun ramp_fit_pipeline.cfg NIST717-LONG-LIN-5365210033_1_496_SE_2015-12-31T21h50m33_uncal.fits 

and the ramp_fit_pipeline.cfg file is in the directory with the other files mentioned above.  It carries out a minimum reduction of the ramp in calwebb_detector1 to get the ramp slope file out.

**Comment by dmggh** [comment]
Hi Kevin,

There currently is no "soft saturation" DQ flag; the GROUPDQ flags are :
{'GOOD': 0, 'DO_NOT_USE': 1, 'SATURATED': 2, 'JUMP_DET': 4, 'DROPOUT': 8}

... which you can find in jwst.datamodels.  A value of 4 indicates a jump detection that has been flagged by the jump step, so you may want to look at the rejection_threshold value used by that step.

-Dave

**Comment by KevinVolkSTScI** [comment]
Hi Dave
OK, I was looking at an out of date list of flags.  However there is also no reason for the code to flag all the groups as jumps.  Should I close this issue and re-submit it saying that there is an issue with the jump detection?

**Comment by dmggh** [comment]
I think so - If the rejection_threshold is set very low, then groups that are not cosmic rays may be erroneously flagged.

**Comment by KevinVolkSTScI** [comment]
I am using the default rejection threshold in these runs.  In fact I have no particular grasp of how the rejection threshold is set.
