### ISSUE TITLE
The jump detection step is flagging almost all the groups in a normal exposure.  Also, some groups that I think should be flagged as saturated are not so flagged.

### ISSUE THREAD

**Issue by KevinVolkSTScI** [spacetelescope/jwst#3358]
This is the same issue that I posted as Issue 3357 earlier today.  Apparently I was looking at an out-of-date list of flags and so interpreted the situation wrongly.  The following is mostly copied from the other issue, with some revisions in the discussion of the flags.

I ran a few CV3 linearity ramps through the pipeline (version 7.2.6). These ramps were taken in NISRAPID mode with no frame averaging so each group is an individual frame. The signal extends to saturation in the 220 group ramps. There are 10 such long ramps in the data set. The output ramp slope values for some pixels are clearly wrong when compared with the raw data values: rather than a ramp slope value of order 42 ADU/second the ramp slope values are small and sometimes negative for all 10 of the linearity ramps. Investigation of the ramps after the linearity step for such a pixel showed that the GRUODQ flag is set to 4 for most of the groups after the first group (but not all of them, even though the signal rises continuously to saturation along the ramps and the differential signal from read to read decreases up the ramp), but that some of the groups that should be flagged as saturated--just from the shape of the ramp--later in the ramp were given GROUPDQ=0. No pixels have GROUPDQ=2, although the pixel definitely saturates for the second half of the ramps. I am assuming that this is the cause of the bad ramp slope values that are produced.

I have not changed the defaults for the jump detection step in the run.  I think one should not get 119 of the first 120 groups all flagged has jumps when the signals are varying normally up the ramp, as is the case for pixel [960,1068] in the first ramp for the set for example.  Comparison of the size of the signals accumulated per group, by just taking the first differences, shows similar values for pixel [960,1068] and pixel [961.1069] but in the one pixel all sorts of GROUPDQ = 4 flags are seen while in the other pixel there are none of these.

Also, I see that groups for pixel [960,1068] that are above the saturation threshold are NOT flagged with GROUPDQ = 2.  After the pedestal subtraction the "saturation" values are 32315 ADU for pixel [960,1068] and 37416 ADU for pixel [961,1069].  For the latter pixel there are lots of GROUPDQ = 2 flags on the latter part of the ramps as expected.  For the [960,1068] pixel there seem to be NO GROUPDQ = 2 entries.

I am using file jwst_niriss_superbias_0080.fits to find pedestal values and file jwst_niriss_saturation_0010.fits to get the "saturation" values for the pixels.  The code appears to be flagging saturation for pixel [961,1069] at about 31000 ADU which is lower than the value I calculate by hand for the signal ramps.  This needs to be investigated, but the pixel [960,1068] should have many values flagged as saturated since the ramp is driven well past the point of failure of the linearity fitting.

The output files from the pipeline in this case can be found at

/ifs/jwst/wit/niriss/kevin/datareduce/newlienarity/pipeline/

The long linearity ramps are the 10 files

NIST717-LONG-LIN-5365210033_1_496_SE_2015-12-31T21h50m33_uncal.fits
NIST717-LONG-LIN-5365214120_2_496_SE_2015-12-31T22h30m37_uncal.fits
NIST717-LONG-LIN-5365222126_3_496_SE_2015-12-31T23h10m52_uncal.fits
NIST717-LONG-LIN-5365230150_4_496_SE_2015-12-31T23h50m39_uncal.fits
NIST717-LONG-LIN-5365234222_5_496_SE_2016-01-01T00h32m22_uncal.fits
NIST717-LONG-LIN-6001002228_6_496_SE_2016-01-01T01h12m18_uncal.fits
NIST717-LONG-LIN-6001010301_7_496_SE_2016-01-01T01h52m54_uncal.fits
NIST717-LONG-LIN-6001014350_8_496_SE_2016-01-01T02h32m38_uncal.fits
NIST717-LONG-LIN-6001022356_9_496_SE_2016-01-01T03h12m38_uncal.fits
NIST717-LONG-LIN-6001030429_10_496_SE_2016-01-01T04h50m18_uncal.fits

and the output ramps and ramp slope files are in the same directory. An example of a pixel where there is the issue is pixel x=960 y=1068 (using IRAF-like 1-based pixel numbering). An example of a pixel with normal behaviour is pixel [961,1069]. The raw signal, linearized signal, error, and GROUPDQ flags for these pixels for the 10 sets of ramps were dumped to files pixel_values_0960_1068.data and pixel_values_0961_1069.data in the same directory, if people wish to look at the values that way (as I did) rather than trying to work with the large arrays. In those files the first column is the group number then one has ten groups of four values, these being the raw signal, the corrected signal, the error values (all zero, it seems), and the GROUPDQ value.

When I ran the pipeline I skipped the DQINIT step to have all pixels flagged as good, so that all the pixels go through the steps I wanted to run. However, this particular pixel [960,1068] is flagged as good in the NIRISS DQ reference file and all the linearity data for the pixel seems normal.  To run the pipeline I use commands such as

strun ramp_fit_pipeline.cfg NIST717-LONG-LIN-5365210033_1_496_SE_2015-12-31T21h50m33_uncal.fits 

where the ramp_fit_pipeline.cfg file in the directory turns off a number of the detector1 steps that I did not want to be applied in this case.

**Comment by KevinVolkSTScI** [comment]
It looks like the problems stem from not flagging any groups in the ramps as saturated for pixel [960,1068], having had more time to think about the issue.  However I am unable to find a reason why the groups later in the ramp are not being flagged.  All the checks I can make of the raw data file and the reference file say that the pixels later in the ramp should be flagged as "saturated".  The raw ramps for pixel [960,1068] go to 65535 ADU and the saturation reference file value is 47350 for this pixel.

**Comment by aliciacanipe** [comment]
Sorry, I didn't catch the jira/github bot in time and it generated #3441 when I opened a Jira ticket for this issue -- either this github ticket or the other one can be closed as a duplicate. #3441 is linked to the Jira issue I created for tracking purposes.

**Comment by stscicrawford** [comment]
Closing with that one being closed.
