### ISSUE TITLE
FITS BINTABLE column values not always correct

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/jwst#3435]
There are some problems with `datamodels` for FITS BINTABLE extensions, having to do with the data type of a column.

One issue is that for unsigned integer columns the TZERO value is not handled correctly; in one example TZERO appears to have been added twice.  This was reported earlier; see GitHub issue #3179.

The other issue is that, if the columns in an input table are not in the correct order (as defined in the schema), the data are actually gotten correctly, but the data types for the columns are assigned in the order defined by the schema.  This was noticed in a table that was the output from the `extract_1d` step (`MultiSpecModel`).  The DQ column has type unsigned 32-bit integer (`numpy.uint32`), and all other columns are double precision (`numpy.float64`).  When the DQ column was gotten via the data model, the array had dtype `numpy.float64`, and the values were the raw, unscaled values (i.e. the TZERO value was not added).

Here is an example for the first issue.  The values in the DQ column are 0 when they are read correctly, i.e. by `astropy.io.fits`.  The raw values in the FITS table are actually -2147483648, but TZERO4 = 2147483648, so the "scaled" DQ value (the raw value plus TZERO) is 0.

    model = datamodels.open("jw87600017001_02101_00002_nis_extract_1d.fits")
    type(model)
    <class 'jwst.datamodels.multispec.MultiSpecModel'>
    dq = model.spec[0].spec_table["dq"]
    print(dq.dtype)
    uint32
    print(dq[0:3])
    [2147483648 2147483648 2147483648]      # these values should be 0
    model.close()

Here is an example for the second issue.  For a `MultiSpecModel`, the schema defines the columns in this order:

    WAVELENGTH
    FLUX
    ERROR
    SURF_BRIGHT
    SB_ERROR
    DQ
    BACKGROUND
    BERROR
    NPIXELS

File nrs_mod_extract_1d.fits has the correct column names and data types (all are `float64` except DQ, which is `uint32`), but the order is different:

    WAVELENGTH
    FLUX
    ERROR
    DQ
    SURF_BRIGHT
    SB_ERROR
    BACKGROUND
    BERROR
    NPIXELS

Since several of the columns in an actual output file from `extract_1d` have all zero values, I assigned non-zero values to these columns (using `astropy.io.fits` instead of JWST data models) for purposes of testing:

    fd = fits.open("nrs_mod_extract_1d.fits", mode="update")
    fd[1].data.field("error")[:] = 1
    fd[1].data.field("sb_error")[:] = 2
    fd[1].data.field("berror")[:] = 3
    fd[1].data.field("dq")[:] = 15
    fd.close()

Here is what was seen when this modified table (FITS BINTABLE) was examined using JWST data models:

    model = datamodels.open("nrs_mod_extract_1d.fits")
    spec = model.spec[0].spec_table

    wl = spec["wavelength"]
    flux = spec["flux"]
    error = spec["error"]
    dq = spec["dq"]
    surf_bright = spec["surf_bright"]
    sb_error = spec["sb_error"]
    background = spec["background"]
    berror = spec["berror"]
    npixels = spec["npixels"]

    wl.dtype
    dtype('float64')                    # correct
    dq.dtype
    dtype('float64')                    # wrong
    sb_error.dtype
    dtype('uint32')                     # wrong

    wl.mean()
    1.4025502912646264                  # correct
    flux.mean()
    1918.4621382684336                  # correct
    error.mean()
    1.0                                 # correct
    dq.mean()
    -2147483633.0                       # correct raw value
    -2147483633.0 + 2147483648          # manually add TZERO
    15.0                                # now it's the expected value

    surf_bright.mean()
    1918.4621382684336                  # correct
    sb_error.mean()
    2.0                                 # correct
    background.mean()
    0.0                                 # correct
    berror.mean()
    3.0                                 # correct
    npixels.mean()
    7.0                                 # correct

**Comment by hbushouse** [comment]
Fixed by #3680
