### ISSUE TITLE
Failures in extract_2d caused by upstream changes in dev version of photutils

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#3534]
This appears to be the case, at least.

https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fjwst/detail/PR-3514/7/tests

These test failures are against the current dev version of `photutils`.  @larrybradley, @philhodge

**Comment by larrybradley** [comment]
This is due to a forthcoming API change in `photutils`.  I'll submit a PR to fix this.
