### ISSUE TITLE
ImportError: combine_1d_spectra

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/jwst#3553]
Importing `jwst` fails with:
```python
[...]/jwst-0.13.3a0.dev106+g9fe29906-py3.6.egg/jwst/master_background/master_background_step.py", line 5, in <module>
    from ..combine_1d.combine1d import combine_1d_spectra
ImportError: cannot import name 'combine_1d_spectra'
```

ref: https://plwishmaster.stsci.edu:8081/job/AstroConda/view/dev-problems-latest/job/dev_OSX-10.13_py3.6_np1.14/job/jwst/119/console

**Comment by jdavies-st** [comment]
Hmm, this looks like it might be a circular import issue.  Shall we defer the import to the function that needs it?

It might be better to move the problematic code to `jwst/lib` where both packages can access it?
