### ISSUE TITLE
Update build instructions for the package documentation 

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#3662]
In a clean environment, after pulling and installing the current master repo, I had to pip install these additional packages in order to build the documentation. Minimally, instructions should be added to the README for the documentation install/build.

* stsci_rtd_theme
* sphinx_rtd_theme
* sphinx_astropy
* sphinx_asdf

I also received this warning in the build, I'm unsure which theme it applies to yet, probably the stsci_rtd_theme since that inherits from sphinx_rtd_theme. 

> writing additional pages... search/miniconda3/envs/jwstdev/lib/python3.7/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
> {{ super() }}

issue to address the warning added here: https://github.com/spacetelescope/stsci_rtd_theme/issues/11

**Comment by jdavies-st** [comment]
```
pip install -e .[docs]
```
does it.

**Comment by sosey** [comment]
I see that, but that specification also uninstalls the jwst package I had installed, then reinstalls the current checkout with develop mode. What if I don't want to be in develop mode, I want to install it into my env and build the docs?  Is the project now recommending users install only in develop mode? It would be nice to see some docs that explain the difference without messing with users local installs.  I think it would be minimally nice to see some mention of `pip install .` and `pip install .[docs]` , separating install from development work.

**Comment by jdavies-st** [comment]
I think if users are building docs, they are going to do it from a git checkout.  I don't think we need to support anything beyond that.  Do you see other use cases?

If people just want to install the package in non-dev mode, (without a git checkout), then they can use the docs on readthedocs.

**Comment by sosey** [comment]
I just gave my use case, and it's useful to have the docs installed locally and offline.  If project doesn't prefer to include the distinction then this issue can be closed.
