### ISSUE TITLE
TST: Test against Python 3.8

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#3688]
Beta is out, so not long now. Might wanna future proof before it is too late.

https://docs.python.org/3.8/whatsnew/3.8.html

**Comment by jdavies-st** [comment]
Yeah, I think we might still have a `DeprecationWarning` that will probably be a hard error in Python 3.8.  Should probably find that.

**Comment by pllim** [comment]
You might also wanna test this with astropy dev, due to astropy/astropy#8853

**Comment by jdavies-st** [comment]
Fixed by #4196
