### ISSUE TITLE
Resample_spec docs clarification

### ISSUE THREAD

**Issue by dmggh** [spacetelescope/jwst#3730]
The link to the readthedocs docs for resample_spec takes me to the docs for resample, in which there are several mentions of resample_spec, but distinctions between the two are not clear. For example, either a separate page for resample_spec, or a new subsection for it within the resample docs would help.

**Comment by hbushouse** [comment]
Jira tracking in https://jira.stsci.edu/browse/JP-849

**Comment by hbushouse** [comment]
Closing this issue, because it's now been duplicated by the jira bot in #3792.
