### ISSUE TITLE
Incomplete/incorrect instructions for "Installing for developers"

### ISSUE THREAD

**Issue by elwinter** [spacetelescope/jwst#3811]
Hi folks. I am helping a summer student debug this problem.

Following the instructions at:

https://github.com/spacetelescope/jwst/blob/master/README.md

in the "Installing for developers" section, there seems to be a missing step. Once the repo mis cloned with:

git clone https://github.com/spacetelescope/jwst

and numpy installed:

pip install numpy

the developer is directed to run:

pip install -e .

resulting in an error message that setup.py is not found. Presumably, this step must be run first, before "pip install -e .":

cd jwst

The setup.py runs, but then (on a Mac) there is a popup window indicating the need for Xcode command-line tools. But while those tools are installed by the system, setup.py continues, with many errors.

Running setup.py again after the installation of the Xcode command-line tools results in more errors, of the sort:

  ERROR: Complete output from command /Users/ewinter/anaconda3/envs/jwst_env/bin/python /Users/ewinter/anaconda3/envs/jwst_env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/m6/5msx0nwd6_j4r3g_17542hz40001q2/T/tmpzmho1u3v:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/stsci
  copying stsci/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/stsci
  creating build/lib.macosx-10.7-x86_64-3.6/stsci/imagestats
  copying stsci/imagestats/histogram1d.py -> build/lib.macosx-10.7-x86_64-3.6/stsci/imagestats
  copying stsci/imagestats/version.py -> build/lib.macosx-10.7-x86_64-3.6/stsci/imagestats
  copying stsci/imagestats/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/stsci/imagestats
  running build_ext
  building 'stsci.imagestats.buildHistogram' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ewinter/anaconda3/envs/jwst_env/include -arch x86_64 -I/Users/ewinter/anaconda3/envs/jwst_env/include -arch x86_64 -DNUMPY=1 -I/private/var/folders/m6/5msx0nwd6_j4r3g_17542hz40001q2/T/pip-build-env-9o2hfuh2/overlay/lib/python3.6/site-packages/numpy/core/include -I/Users/ewinter/anaconda3/envs/jwst_env/include/python3.6m -c src/buildHistogram.c -o build/temp.macosx-10.7-x86_64-3.6/src/buildHistogram.o
  xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for stsci.imagestats

This error occurs on an OS X Mojave system.

Does the JWST pipeline code have other requirements that are not listed? Specifically, it looks like a C++ compiler is needed. Which C++ compiler should be used to build the software? What else is needed before the setup instructions are performed? The summer students are using brand-new Macs with very little preinstalled software, so we (ITSD) need to know what to put on their machines for this work.

Thanks
Eric Winter

**Comment by jdavies-st** [comment]
Yes, one needs to `cd jwst`.  Will update the docs.  "Install from _within_ your local checked out copy..."

And yes, if one is going to develop on the Mac, one needs Xcode with command-line tools which includes the C compiler.  Definitely.  All the Macs that ITSD supplies to software engineer employees work out-of-the-box without issues.

And of course make sure all of this is being done within an activated conda or virtualenv environment as indicated in the instructions.  Don't try to do this using the system version of python.

**Comment by elwinter** [comment]
Thanks for the quick reply, James. The laptops provided to the summer interns are not configured the same as those for the engineering staff, apparently.

For the summer students, I think the instructions need to be even more explicit. They are (mostly) following instructions verbatim, so I really think an explicit

cd jwst

is needed.

So the full Xcode is needed? OK, I’ll try that and see if it clears up the problem.

Thanks
Eric

**Comment by jdavies-st** [comment]
Dependencies of `jwst` currently need to have the GNU C++ libraries installed, which means Xcode 9.  Xcode 10 doesn't have them, as they are deprecated for the CLANG compiler on MacOS.

This will require changes in dependency packages, but nothing here in `jwst`.  See below:

https://github.com/spacetelescope/spherical_geometry/issues/175
