### ISSUE TITLE
Poisson variance determinations in Ramp Fitting are unreliable in low signal case (e.g. darks).

### ISSUE THREAD

**Issue by chriswillott** [spacetelescope/jwst#3878]
This is a problem with the calculation and use of Poisson variance for determining the weighting of partial ramp segments when a cosmic ray has been detected and the ramp is split into more than one segment. The Poisson variance is determined from the median slopes derived in the 'First Pass' over the data. These median slopes are determined as the median of the differences between subsequent groups in the array. This is fine for cases where there is a high signal. However, for the low signal case, such as darks with little background or source illumination, the median of the differences is not a useful quantity.

For example, the NIRISS detector has a dark current of 0.04 e-/s which is 0.025 ADU/s. For a frame time of approximately 10 seconds the typical increase in pixel value due to dark current per frame is 0.25 ADU. This is to be compared with the read noise (random fluctuations up and down from one group to the next) of about 10 ADU. The consequence is that about half the differences for a given pixel are positive and half are negative. For about half the pixels the median of the differences is negative and this is used to calculate the Poisson variance in the 'Second Pass' over the data. For some short segments (e.g. after a cosmic ray has hit near the end of a ramp) there can be unreasonably large values of the median of the differences, so it is not only the negative values that are a problem.

The consequence of negative values of the median slope rates in the 'Second Pass' is that the Poisson variance gets set to a large value (1.0E8) on line 505.

https://github.com/spacetelescope/jwst/blob/ad87fa493f02bc5ea7c6c215a32db9bebd2d1fb5/jwst/ramp_fitting/ramp_fit.py#L505

Then when the Poisson and readnoise variances get summed on line 522

https://github.com/spacetelescope/jwst/blob/ad87fa493f02bc5ea7c6c215a32db9bebd2d1fb5/jwst/ramp_fitting/ramp_fit.py#L522

the result is 1.0E8, irrespective of the readnoise variance of the segment. So the slope from a very short segment after a cosmic ray hit is given equal weight to a long segment and the resulting final slope can be very bad. This is obvious when looking at the final slope image for a NIRISS dark with simulated cosmic rays. At the locations of many pixels hit by cosmic rays, particularly those hit near the start or end of the ramp, the noise is much higher than expected.

The true variance for the low signal case should be just the readnoise component. for the Poisson variance replacing the median of the differences with a 4-sigma-clipped mean of the differences provides more robust values, but there are still some negative values for the low count rates of NIRISS darks. I think the solution to this problem should be to set the variance equal to the readnoise variance unless the Poisson variance can be shown to have been measured significantly. I believe the exact algorithm change required needs to be considered by a group familiar with the statistical method.

I note there was a previous issue #1687 that sounds similar and indeed describes why including the Poisson variance even if well measured could cause a bias, but whatever solution was taken there still leaves the problem described above in 0.13.7.

**Comment by chriswillott** [comment]
I have just realized that there is a bug in the code that contributes to this problem. As described above, for low signal rates the Poisson variance gets set to the large value 1.0E8 on line 505. After this the large values should get reset to zero before being added to the readnoise variance. However, the line that resets to zero acts on a different variable, var_p3, on line 519:
https://github.com/spacetelescope/jwst/blob/f1bbfdd4a8bc2979eeff8ee27c18e4ebd689410d/jwst/ramp_fitting/ramp_fit.py#L519
        var_p3[var_p3 > 0.1 * utils.LARGE_VARIANCE] = 0. 
I think this line should be changed to reset var_p4 and then moved above the previous block that derives var_p3 from var_p4. Then both var_p4 and var_p3 will have the large variances reset to zero.

If this change is made, then it is not required to change line 522 as suggested in the original issue, as the Poisson variance will be negligible for the low signal case.

**Comment by mwregan2** [comment]
Chris,
  The code changed a while back to not use the Poisson noise in the semi-ramp combination process. This is to deal with both the problem you mentioned and to avoid a bias against high flux samples that comes from Poisson weighting. The code only using the effective read noise which is the single sample read noise scaled by the number of samples in the semi-ramp.
  I have tested the combination process and it works as it should.
  I'd recommend this issue be closed.

**Comment by chriswillott** [comment]
Mike - thanks for looking into this. Good to hear it is no longer a problem. I processed some data with cosmic rays using 0.16.2 and it did look OK, but I haven't dug deep to check everything is perfect. My only question is if these variances are used in the calculation of ERR arrays so a bug could still cause a problem there. But I will close this issue.
