### ISSUE TITLE
Incorrect Calculation of the Median Difference in the Jump Step

### ISSUE THREAD

**Issue by mwregan2** [spacetelescope/jwst#3958]
The Jump step does not calculate the median correctly when there are saturated or do_not_use frames. In some circumstances this leads to a median of around 50K and thus a large number of incorrect cosmic rays being detected. With MIRI always flagging the first and last frame, this will happen in every integration.
  I have identified the problem and have an fix that I want to test a little more before I create a pull request.

**Comment by stscicrawford** [comment]
Closed with #3987
