### ISSUE TITLE
Review if any of fixed-length tabular schema could be relaxed to arbitrary shape

### ISSUE THREAD

**Issue by mcara** [spacetelescope/jwst#3980]
PR https://github.com/spacetelescope/jwst/pull/3976 introduced arbitrary shape array specification in schemas for structured arrays. Specifically, the `shape` descriptor may not longer be necessary in many cases. Therefore, `shape` attributes in the following schemas (and associated code) that I could identify may no longer be needed:

[fgs_photom.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/fgs_photom.schema.yaml#L15-L21) - 3x5,000 elements

[mirimg_photom.schema.yaml](https://github.com/spacetelescope/jwst/blob/master/jwst/datamodels/schemas/mirimg_photom.schema.yaml#L19-L28) - 3x500 elements

[nircam_photom.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/nircam_photom.schema.yaml#L21-L27) - 2x3,000 elements

[niriss_photom.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/niriss_photom.schema.yaml#L21-L27) - 2x5,000 elements

[nirspec_flat.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/nirspec_flat.schema.yaml#L39-L45) - 2x130,000 elements

[nirspec_photom.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/nirspec_photom.schema.yaml#L19-L28) - 3x150 elements

[nirspec_quad_flat.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/nirspec_quad_flat.schema.yaml#L37-L45) - 2x130,000 elements

[nirspecfs_photom.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/nirspecfs_photom.schema.yaml#L21-L30) - 3x150 elements

[photom.schema.yaml](https://github.com/spacetelescope/jwst/blob/27526f9ac8035676de26df6a43d321d254a36e93/jwst/datamodels/schemas/photom.schema.yaml#L16-L25) - 3x50 elements

**Comment by jdavies-st** [comment]
Yeah, I think it would be good to change these so that there's not a bunch of unused elements, though I expect the code and the schemas would have to be changed in unison, as in some cases the code make assumptions about the array length.

For many of these would the `ndim` schema element replace `shape`?

**Comment by mcara** [comment]
`ndim` is only necessary if you wanted to constrain the number of dimensions instead of a specifically required shape. If elements of a table can have any shape (shape determined from actual data), i.e., if neither number of dimensions nor shape is predetermine, then neither `ndim` nor `shape` is required in the schema.

**Comment by hbushouse** [comment]
It appears this is no longer an issue. All of the photom ref files schemas have been rewritten and the new forms do not hardwire the array lengths. See, e.g.
https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schemas/nrcimg_photom.schema.yaml
https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schemas/nisimg_photom.schema.yaml
https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schemas/mirlrs_photom.schema.yaml
https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schemas/nrsfs_photom.schema.yaml

So I'm closing this.
