### ISSUE TITLE
WCS-TAB needs only two points for linear spectral dependence

### ISSUE THREAD

**Issue by mcara** [spacetelescope/jwst#3983]
While working on https://github.com/spacetelescope/jwst/pull/3976, I saw that WCS-TAB of "complex" cubes (i.e., cubes formed with data from three channels) contain a large number of wavelengths values. However, WCS of single-channel cubes seems to be well described using `WAVE` WCS with a linear model. This means that `WCS-TAB` of three-channel cubes does not need to have over 4,000 values to be described because `WCS-TAB` specification says that intermediate values in-between two table values will be interpolated which should be good enough for linear dependence.

Therefore, I suggest `cube_build` step be modified so that only end values for the linear portions for each channel are saved in the table extension. This way, the table will contain just 6 values.

CC: @jemorrison @jdavies-st @nden

**Comment by jemorrison** [comment]
@drlaw1558 Please check this PR out and comment on it

**Comment by jemorrison** [comment]
If an IFU Cube has a linear wavelength then  standard WCS routines are used and NO WCS-TAB is created. The WCS-TAB is only for non-linear wavelength IFUcubes. 
Does this answer your question ?
I do not think any changes need to be made to the cube_build step - unless I am misunderstanding your comment.

**Comment by mcara** [comment]
No. (I think) The reason you are using `WCS-TAB` is that while wavelength is linear (as a function of slice) for each channel, there is a jump between channels. You cannot use a _single_ linear model to describe a cube created from 3 channels. However, the WCS is piecewise linear and can be described with a single linear WCS on different slice intervals. Therefore, specifying only end points of those intervals should be enough to _completely_ describe a piecewise linear WCS using `WCS-TAB` specification.

**Comment by jemorrison** [comment]
Ok I did misunderstand what you were suggesting. David Law defined the wavelengths to use for
cube made from different channels - so we need to get his input: @drlaw1558
Can ds9 support what you are suggesting ? We really should   create IFU cubes that ds9 can read  - since that is likely the first way observers will look at the output.

**Comment by mcara** [comment]
If DS9 uses `WCSLIB` (via `AST`?) then it should be able to handle what `WCS-TAB` says.

**Comment by drlaw1558** [comment]
Hi all- the multichannel wavelength solution is not piecewise linear, it is neither linear nor logarithmic and defined by a generating function designed to provide reasonable delta-wavelength spacing everywhere.  In detail, it is produced by the function mrs_multiwave() within https://github.com/STScI-MIRI/miri3d/blob/master/miri3d/cubepar/make_cubepar.py
I've also attached an image showing what it looks like.
![mrswave](https://user-images.githubusercontent.com/11397442/64209758-60aaaa80-ce6f-11e9-9475-3624ccd22be8.png)

**Comment by drlaw1558** [comment]
The idea is that the cubepar file defines linear wavelength solutions to use for each individual MRS wavelength band since linear solutions are easy to work with.  When creating a multiband cube though it will pull the appropriate wavelengths from the nonlinear solution above.

**Comment by mcara** [comment]
I do not understand why a linear model is good enough for each single band but a piece-wise linear model is not good for a multi-band cube. My question came from code such as:

https://github.com/spacetelescope/jwst/blob/aebd70bd45e3db06f17b3b5ee853ea032f726fb0/jwst/cube_build/ifu_cube.py#L1837-L1840

which clearly creates a linear `WAVE` WCS. Now I see that sometimes the wavelength axis is not (set to) linear.
