### ISSUE TITLE
Update fits_generator to include new WCS pointing keywords

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#419]
The fits_generator WCS templates should be updated to include the additional set of WCS-related keywords that are now required by the B7 cal pipeline, which are:

V2_REF
V3_REF
RA_REF  (=CRVAL1)
DEC_REF (=CRVAL2)
ROLL_REF

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2162](https://jira.stsci.edu/browse/JP-2162)._

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2162](https://jira.stsci.edu/browse/JP-2162)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-2162?focusedCommentId=759520#comment-759520):_

Closing, since the fits_generator is no longer needed.
