### ISSUE TITLE
Genericize the generator

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#420]
Options such as `candidate_id`,`DMS`, etc. are very JWST-specific. Better isolate such specific items using a more generic API.

**Comment by stscieisenhamer** [comment]
# Implementation

## ToDO
- [ ] Split/subclass Main
- [ ] Identify internals that are too-JWST specific

## Design
Much can be done through the use of a more generic Main class, and a JWST subclass. However, there is sprinkled throughout a bit of JWST/DMS specific items.

**Comment by melanieclarke** [comment]
Closing - this does not appear to be relevant to the current association generator structures.
