### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#4258]
Hi, 

When I try to install with 
pip install git+https://github.com/spacetelescope/jwst

The following error happens
Failed to build astropy
ERROR: Could not build wheels for spherical-geometry, stsci.image, stsci.imagestats, drizzle, stsci.stimage which use PEP 517 and cannot be installed directly

Any idea how to fix it? 

Thanks,
Guang

**Comment by jdavies-st** [comment]
Without seeing the complete traceback, I can only guess that you do not have a C compiler properly configured on your machine? If you are using MacOS, do you have both Xcode and the command line utilities for Xcode installed?

**Comment by Guang91** [comment]
I'm using Ubuntu Linux 18.04.3 LTS. I have gcc installed. The full error log is attached. 
[log.txt](https://github.com/spacetelescope/jwst/files/3842753/log.txt)

**Comment by jdavies-st** [comment]
Hmm, nothing too helpful in that traceback.  Since it is astropy that is failing, you can try just installing astropy from Github on it's own in a new environment and seeing if it builds.

`pip install git+https://github.com/astropy/astropy#egg=astropy --verbose`

and if it does not, then file an issue with the astropy folks, showing the verbose traceback above.  Perhaps they can help you figure out why it is not installing on your system?

https://github.com/astropy/astropy/issues

**Comment by Guang91** [comment]
Somehow I cannot install astropy with pip. But conda does the job. After re-installation, I realized there're still some other packages cannot be installed (such as spherical-geometry and drizzle). I manually install them one by one, and rerun pip for jwst. It works! 
Thanks a lot, James!

**Comment by jdavies-st** [comment]
Glad you got it working.  What version of `pip` are you using?
```
$ pip --version
pip 19.3.1 from /Users/jdavies/miniconda3/envs/jwst/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by Guang91** [comment]
pip 19.3.1 from /home/guang/anaconda3/envs/jwst_env/lib/python3.7/site-packages/pip (python 3.7)
git version 2.17.1

I guess it's not due to pip and git. Probably due to gcc (or some other basic library). When I install the packages manually, I need to reinstall "build-essential" (https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory).

**Comment by jdavies-st** [comment]
Ah, ok.  So once you did
```
sudo apt-get install --reinstall build-essential
```
The installations installed normally?  I.e. once you had the full gcc toolchain, you could then install everything OK in a new conda environment using
```
pip install git+https://github.com/spacetelescope/jwst
```
?

**Comment by Guang91** [comment]
Just tried on a new env. Yes, after reinstall build-essential. The pip install runs successfully.

**Comment by jdavies-st** [comment]
Thanks for the extra info.  This may help us troubleshoot the same problem for others.  👍

**Comment by emolter** [comment]
just wanted to say thank you for this.  I was experiencing the same problem as @Guang91 on MacOS Monterey, and fixed it by installing brew and then running `brew install gcc` to update the compiler.
