### ISSUE TITLE
CRDS - ERROR

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#4293]
I run the pipeline for some simulated MIRI images with "Detector1Pipeline.call"
I got lots of CRDS errors like this 

2019-11-19 14:39:25,109 - CRDS - ERROR -  Error determining best reference for 'pars-groupscalestep'  =   Unknown reference type 'pars-groupscalestep'

But the command still outputs the result files. 
I wonder if the outputs are still valid. Are these errors a serious problem, or just some warnings that can be ignored? 

Thanks,
Guang

**Comment by stscicrawford** [comment]
For now, this is an error that you can ignore.  It is an expected message though it is not an error and we are trying to update the message to be more appropriate.  Thanks for the report. 

Closing as duplicate

**Comment by Guang91** [comment]
Thanks for the explanation, Steve.
