### ISSUE TITLE
Run individual steps 

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#4300]
When trying to run individual pipeline steps such as
  img3 = Image3Pipeline()
  img3.tweakreg.run(association)
  img3.skymatch.run(association)
  img3.resample.run(association)

It seems each step run independently from each other. 
What I need is to use the results from previous steps. 
For example, when running resample, the code should use the results from tweakreg and skymatch. 

Is that possible to do it? 

Thanks,
Guang

**Comment by jdavies-st** [comment]
The following
```
result = Image3Pipeline.call("input_cal.fits")
```
runs the whole pipeline and returns the result in memory.  If you want to save the results to files:
```
result = Image3Pipeline.call("input_cal.fits", save_results=True)
```
This is documented in the documentation:

https://jwst-pipeline.readthedocs.io/en/latest/jwst/introduction.html#running-from-within-python

**Comment by Guang91** [comment]
Thanks for the quick response, James. 

But Image3Pipeline.call runs the entire Image3 pipeline. 
Now I need to experiment with each individual step, i.e. tweakreg, resample, skymatch, and source_catalog.
For example, when running resample, how can I use the results from tweakreg?

**Comment by philhodge** [comment]
@Guang91 the steps are run sequentially, not independently.  The image3 pipeline runs tweakreg, then runs skymatch on the output of tweakreg, then outlier_detection on the output of skymatch, then resample on the output of outlier_detection.

**Comment by jdavies-st** [comment]
Here's one way, which is essentially what the `Image3Pipeline` does:

```
from jwst.tweakreg import TweakRegStep
from jwst.skymatch import SkyMatchStep
from jwst.resample import ResampleStep

result = TweakRegStep.call("input_asn.json")
result = SkyMatchStep.call(result)
result = ResampleStep.call(result)
```

**Comment by Guang91** [comment]
@jdavies-st  This is exactly what I need. Thank you, James and Phil. 
-Guang

**Comment by jdavies-st** [comment]
Or doing it the way you've tried above is also fine.
```
img3 = Image3Pipeline()
result1 = img3.tweakreg.run(association)
result2 = img3.skymatch.run(result1)
result3 = img3.resample.run(result2)
```
The difference between `call` and `run` is that `call` creates a new instance of the class and allows an config file as input.  `run` just runs the existing instance.
