### ISSUE TITLE
Background over-subtracted 

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#4302]
I was running the pipeline on a set of simulated MIRI images (3 dithers). After finishing stage 1 & 2 procedures, I got three images with background ~ 8. Then I run stage 3, and merged the three images together. The merged image has background ~ -8, instead of ~0. 

I investigated each step in stage 3, i.e. tweakreg -> skymatch -> outlier_detection -> resample. After skymatch, the three images still have background ~ 8. But after outlier_detection, the background became ~ 0. After resample (which merges the three images), the background became ~ -8. So, outlier_detection and resample both subtracted the background, leading to an over-subtraction. 

Any idea what's wrong?

Thanks,
Guang

**Comment by jdavies-st** [comment]
Hi @Guang91, thanks for reporting this and sorry for the late feedback.

It sounds like the background is somehow getting subtracted in `outlier_detection`, and it should not be.  `outlier_detection` should only be updating the DQ array.  We will take a look at this.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1416](https://jira.stsci.edu/browse/JP-1416)._

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1503](https://jira.stsci.edu/browse/JP-1503)._

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1416](https://jira.stsci.edu/browse/JP-1416)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=468929#comment-468929):_

Duplicated by JP-1503

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=468931#comment-468931):_

Should JP-1503 be closed (as duplicate) instead of this one?

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1503](https://jira.stsci.edu/browse/JP-1503)._

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1416](https://jira.stsci.edu/browse/JP-1416)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=468929#comment-468929):_

Duplicated by JP-1503

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=468931#comment-468931):_

Should JP-1503 be closed (as duplicate) instead of this one?

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=472967#comment-472967):_

I think outlier detection must take into account background, i.e., subtract it BUT **temporarily** and maybe on a copy of input files. This is needed for correct CR identification. However, in the end, this step should leave input images' "flux" data unchanged (only DQ flags should be affected).

**Comment by Guang91** [comment]
BTW, the current background subtraction assumes a single background value. But the actual background is spatially dependent. Do you plan to model the background as a function of position?

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=479237#comment-479237):_

I am also seeing this in my tests, and have a detail to add. Since the background level is being subtracted in the outlier_detection step, the background levels in a recent test level range between -0.5 to 0.5 (as an estimate) in the output from outlier_detection. The negative background pixels are flagged as outliers in the dq array, while the positive values are not. This is leading to many of the background pixels being flagged as outliers, when I really don't think that should be the case. The grey pixels in the attached image starfield_50stars4ptdither_outlierdet_dqflags are flagged as 17 (Outlier and DO_NOT_USE), while the black pixels are 0 (good pixels). The black pixels here correspond mostly to positive pixels in the science data while the flagged pixels are negative in the science data.

**Comment by mcara** [comment]
@Guang91 How do you know that the actual background is a function of position?

If the _actual background_ is spatially variable, current method obviously will not be able to subtract it because indeed it computes a constant background.

**Comment by Guang91** [comment]
![image](https://user-images.githubusercontent.com/7922328/90181260-284d6500-dd7e-11ea-9b53-baf3e0610ebb.png)
Here is a simulated F1500W image, after passing through stage 1 & 2 pipeline. Apparently, the background depends on the position.

**Comment by mcara** [comment]
OK. But is this a "real background" (i.e., is it from an an empty part of the sky with no extended sources) that should be subtracted or is this light from an extended source that is not, for example, of interest for a particular study of a specific point source?

**Comment by mcara** [comment]
Also, what does `'raw'` refer to in the plot label?

**Comment by Guang91** [comment]
I believe this is real. The extended sources are not that bright/crowded to produce the background. Oh, "raw" just means before background subtraction (I have modeled spatially-dependent background with SEP and subtract it). The entire figure (raw & bkg-subtracted) looks
![image](https://user-images.githubusercontent.com/7922328/90182338-ce4d9f00-dd7f-11ea-8f9b-83db17eb0aa7.png)

**Comment by mcara** [comment]
The method used here is intended to *match* images in the overlapping areas. Unless there is a systematic background gradient that could change from image (observation) to image _in the same patch of the sky_, this method should be able to handle complicated backgrounds (for example, it is used to successfully match images of Horsehead nebula that have minimal overlap - see https://github.com/spacetelescope/notebooks/blob/master/notebooks/DrizzlePac/sky_matching/sky_matching.ipynb). The purpose of this step is to match images before cosmic-ray detection and/or before drizzle-combining those images. It is not intended to produce "true background"-subtracted images. That part, I believe, is left to the observer. For example, what should this step subtract in from the horsehead nebula image in the link above?

Moreover, the background that you illustrate seems to be impossible to model with bi-linear/quadratic/cubic models.

Maybe @hbushouse could answer what are the plans for modeling "true background" (light from empty patches of the sky).

**Comment by hbushouse** [comment]
@hbushouse does not make plans for what algorithms to implement. Those plans are made by the JWST Calibration Working Group.

**Comment by stscijgbot-jp** [comment]
_Comment by [Vincent Geers](https://jira.stsci.edu/secure/ViewProfile.jspa?name=vincent.geers) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=481370#comment-481370):_

This ticket was discussed at the JWST CalWG telecon on August 25th: <https://outerspace.stsci.edu/display/JWSTCC/2020-08-25+Meeting+notes].> To repeat a point that was brought up:

Default MIRISim simulations include a non-uniform background component in their scene description, which is based on the zodiacal dust + JWST straylight models that formed the background part of the MIRI Sensitivity model, which is described in this 2015 PASP paper by [Alistair Glasse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=alistair.glasse) : <https://iopscience.iop.org/article/10.1086/682259/pdf>  (ADS: <https://ui.adsabs.harvard.edu/abs/2015PASP..127..686G/abstract]).>

To verify whether this was truly the source of your remnant spatially variable background, you could check the "scene.ini" file that was used to produce the MIRI simulated data to see if it contains a "[Background]" section. If so, you could create a new simulation from those config files, but with that background section removed, and then see if the component goes away after PL reduction.

**Comment by Guang91** [comment]
> _Comment by [Vincent Geers](https://jira.stsci.edu/secure/ViewProfile.jspa?name=vincent.geers) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=481370#comment-481370):_
> 
> This ticket was discussed at the JWST CalWG telecon on August 25th: [https://outerspace.stsci.edu/display/JWSTCC/2020-08-25+Meeting+notes].](https://outerspace.stsci.edu/display/JWSTCC/2020-08-25+Meeting+notes%5D.) To repeat a point that was brought up:
> 
> Default MIRISim simulations include a non-uniform background component in their scene description, which is based on the zodiacal dust + JWST straylight models that formed the background part of the MIRI Sensitivity model, which is described in this 2015 PASP paper by [Alistair Glasse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=alistair.glasse) : https://iopscience.iop.org/article/10.1086/682259/pdf  (ADS: [https://ui.adsabs.harvard.edu/abs/2015PASP..127..686G/abstract]).](https://ui.adsabs.harvard.edu/abs/2015PASP..127..686G/abstract%5D).)
> 
> To verify whether this was truly the source of your remnant spatially variable background, you could check the "scene.ini" file that was used to produce the MIRI simulated data to see if it contains a "[Background]" section. If so, you could create a new simulation from those config files, but with that background section removed, and then see if the component goes away after PL reduction.

Thanks, @stscijgbot-jp Will run mirisim without the background section.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=481605#comment-481605):_

Also, to add a few more details from the [2020-08-25](https://outerspace.stsci.edu/display/JWSTCC/2020-08-25+Meeting+notes) JWST CalWG meeting, regarding the non-uniform background: the current skymatch algorithm presupposes a flat sky background, so possible options for dealing with a non-uniform background could include: (1) fitting a functional form on each exposure, or (2) using reference files that describe the shape and then scaling their amplitude per exposure, which is likely the preferred option though it may be best characterized with in-flight data. We can make an initial start, however, using current ground or model data of the instrument, eg with the above references from the MIRI team (and corresponding data for other instruments, if those are available).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=483085#comment-483085):_

Fixed in #4858

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1416?focusedCommentId=483086#comment-483086):_

The original problem of the background getting subtracted twice has been fixed. Any requests for enhancements to handle things like a spatially varying background should be submitted via new tickets.
