### ISSUE TITLE
units of fits image

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#4306]
Hi, 

I'm running the pipeline on simulated MIRI images. I wonder what is the units of the final fits image (produced by calwebb_image3)? 

The source_catalog.py of the pipeline seems to treat the units as DN/s, as it multiplies a conversion factor to get the units of MJy/sr, 
However, the photom.py says the units should be already MJy / sr as following 
        # For most modes, the scalar conversion factor in the photom reference
        # file is in units of (MJy / sr) / (DN / s), and the output from
        # the photom step will be in units of surface brightness, specifically
        # MJy / sr.

Any idea which one is correct? 

Thanks,
Guang

**Comment by philhodge** [comment]
The data to be calibrated are in units of DN / s.  It's the reference file that has -- for most modes -- units of (MJy / sr) / (DN / s).

**Comment by Guang91** [comment]
Just make sure I understand: 
The data *before* calibration ("photom" in stage 2) have units of DN / s. 
The data *after* calibration have units of MJy / sr

Is that what you mean, Phil?

**Comment by philhodge** [comment]
@Guang91 well, that's true, but I was just answering your question specifically.  You asked for a clarification of a comment in photom.py.  That comment gave the units of the photom reference file, not the units of the input science data.  The comment did also give the units of the output science data.  So it's the reference file (not the input science data) that has units of (MJy / sr) / (DN / s).

The reason I qualified my answer with "for most modes" is that for some types of data the output units will be MJy, not MJy / sr.

**Comment by Guang91** [comment]
Got it! Thanks, Phil. 

Then I think "source_catalog.py" messes up the units:
      micro_Jy = (catalog['source_sum'] *
                    model.meta.photometry.conversion_microjanskys *
                    model.meta.photometry.pixelarea_arcsecsq)
where conversion_microjanskys is the factor converting *DN/s* to uJy/arcsec^2. 
I think the right thing to do is to use the factor converting *MJy/sr* to uJy/arcsec^2

Am I correct?

**Comment by philhodge** [comment]
Yes, @Guang91 , you are absolutely correct.  It wasn't intentional, it's just that `source_catalog` hasn't been updated yet to get in synch with recent changes to `photom`.  @hbushouse filed ticket JP-1149, GitHub #4287, to track this issue.

**Comment by Guang91** [comment]
Thanks for the clarification, @philhodge . Then I will re-scale the flux from the catalog to get the correct values.
