### ISSUE TITLE
fits-schema has incorrect $schema reference

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#4308]
The datamodels schema that extends the standard ASDF schema to allow use of `fits_keyword` and `fits_hdu` properties references itself:

https://github.com/spacetelescope/jwst/blob/cc4c8c61a2ca8a29651f384fac57775222e6a76c/jwst/datamodels/metaschema/fits-schema.yaml#L3-L4

This is probably a bug.

I believe it should instead extend YAML schema
```
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
```
or extend ASDF schema:
```
$schema: "http://stsci.edu/schemas/asdf/asdf-schema-1.0.0"
```
or possibly
```
$schema: "http://stsci.edu/schemas/asdf/core/asdf-1.1.0"
```
Not sure which, but the way it is implemented now looks incorrect.  @nden? @perrygreenfield?

**Comment by braingram** [comment]
The datamodels were moved to stdatamodels in:
https://github.com/spacetelescope/stdatamodels/pull/112
The corresponding metaschema in stdatamodels appears to be fixed and no longer has this issue.
https://github.com/spacetelescope/stdatamodels/blob/e70a9a0d1cb5145af82e7a5c871f5b729f7ee9dc/src/stdatamodels/jwst/datamodels/metaschema/fits-schema.yaml#L3-L4
