### ISSUE TITLE
problems to generate documentation

### ISSUE THREAD

**Issue by rizeladiaz** [spacetelescope/jwst#4339]
I am trying to re-buld the Cal Pipeline documentation to see some updates I made to one table but I am having issues with getting sphinx to run to completion. I got the latest version of the JWST  code from github and when I run "make html" I get an error that seems to be unrelated to the documentation:

`Exception occurred:
File "/Users/rdiaz/Documents/sandbox_diaz/jwst/jwst/resample/resample_utils.py", line 10, in
from astropy.nddata.bitmask import interpret_bit_flags
ModuleNotFoundError: No module named 'astropy.nddata.bitmask'`

to get here I first ran:

> pip install -e .[docs] 
> make html

the full error is:

`sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.0.0+/4985a8a9
/Users/rdiaz/Documents/sandbox_diaz/jwst/docs/conf.py:23: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet("stsci.css")
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
intersphinx inventory has moved: http://matplotlib.org/objects.inv -> https://matplotlib.org/objects.inv
[autosummary] generating autosummary for: index.rst, jwst/ami/ami_analyze.rst, jwst/ami/ami_average.rst, jwst/ami/ami_normalize.rst, jwst/ami/index.rst, jwst/ami/main.rst, jwst/assign_wcs/asdf-howto.rst, jwst/assign_wcs/exp_types.rst, jwst/assign_wcs/index.rst, jwst/assign_wcs/main.rst, ..., jwst/wfs_combine/main.rst, jwst/wfs_combine/reference_files.rst, jwst/white_light/arguments.rst, jwst/white_light/description.rst, jwst/white_light/index.rst, jwst/white_light/reference_files.rst, jwst/wiimatch/index.rst, jwst/wiimatch/lsq_optimizer.rst, jwst/wiimatch/match.rst, jwst/wiimatch/utils.rst
Failed to import 'jwst.skymatch.skystatistics': no module named jwst.skymatch.skystatistics
Failed to import 'jwst.tweakreg.tweakreg_catalog': no module named jwst.tweakreg.tweakreg_catalog
Failed to import 'jwst.skymatch.skymatch_step': no module named jwst.skymatch.skymatch_step
Failed to import 'jwst.tweakreg.tweakreg_step': no module named jwst.tweakreg.tweakreg_step
Failed to import 'jwst.skymatch.region': no module named jwst.skymatch.region
Failed to import 'jwst.skymatch.skymatch': no module named jwst.skymatch.skymatch
Failed to import 'jwst.skymatch.skyimage': no module named jwst.skymatch.skyimage

Exception occurred:
  File "/Users/rdiaz/Documents/sandbox_diaz/jwst/jwst/resample/resample_utils.py", line 10, in <module>
    from astropy.nddata.bitmask import interpret_bit_flags
ModuleNotFoundError: No module named 'astropy.nddata.bitmask'
The full traceback has been saved in /var/folders/dv/08hbjvn906q6z8s8d9tx94rm0005cc/T/sphinx-err-1hwjikgp.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:51: html] Error 2
`

**Comment by rizeladiaz** [comment]
I installed the latest version of astropy and python but still see this error. When I load python I am able to import the module Sphinx complains about:

```
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy.nddata.bitmask
>>> from astropy.nddata.bitmask import interpret_bit_flags
```

 but Sphinx still fails. Why?

**Comment by stscieisenhamer** [comment]
Were you able to build the docs before making your changes? Also, are you doing this in a fresh environment?

**Comment by rizeladiaz** [comment]
No, I started making changes because things were not working.

**Comment by stscieisenhamer** [comment]
There is a version issue. If using environments, I would suggest creating a new environment and install the jwst package as suggested.

If you do not want to create a new environment, or you are not using environments, then you can try uninstally astropy and jwst and re-install jwst:

```
pip uninstall astropy jwst
pip install -e .[docs]
```

**Comment by rizeladiaz** [comment]
I was able to make it work in the linux server tljwdmsins but not in my Mac. Not sure why! Will try later to re-install everything in my Mac. Will keep this issue open until then

**Comment by jdavies-st** [comment]
If you create a fresh conda env and then `pip install astropy` into it, does it install cleanly?  I.e. no errors?  Can you start up python and import astropy?

**Comment by rizeladiaz** [comment]
James, adding a new coda environment didn't help. So I ended up wiping out all my conda and started from scratch. That fixed the issue! Though I notice that the documentation is missing this install: 
pip install sphinx_rtd_theme
maybe it can be added to the instructions or to the package?

**Comment by jdavies-st** [comment]
Yeah, `conda` can sometimes get into a broken state and wiping it and starting from scratch is the only alternative.

The `sphinx_rtd_theme` package is included in the `[docs]` install requirements for `jwst`:

https://github.com/spacetelescope/jwst/blob/0074db585b60215bac560807cf58a99c911c02ce/setup.py#L37-L45

So if you do
```
pip install -e .[docs]
```
that will install it as a dependency.  I just verified that that is the case now by creating a fresh conda env, installing `jwst` as above, and building the docs.

**Comment by rizeladiaz** [comment]
I did that but didn't work. I had to install it independently.
