### ISSUE TITLE
Windows support: Move all scripts into entry points

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#4466]
All the CLI defined in "scripts" needs to be changed into proper console entry points for them to be recognized under Windows terminal like Anaconda Prompt (Powershell). This is as discussed with @stscieisenhamer

**Comment by jdavies-st** [comment]
Agreed.

**Comment by jdavies-st** [comment]
And some of these scripts need to be deleted.  There's no reason to have a separate script for `assign_wcs` when `strun` can run that step itself.  Same goes for all the step-level scripts.

**Comment by stscieisenhamer** [comment]
Relevant Jira issues are [JP-1245](https://jira.stsci.edu/browse/JP-1245), [JP-1477](https://jira.stsci.edu/browse/JP-1477). Closing.

**Comment by pllim** [comment]
Wut...? But those issues are not fixed.

**Comment by stscieisenhamer** [comment]
The primary tracker of issues are the Jira issues, and this issue is a duplicate, so closing as a duplicate.

**Comment by pllim** [comment]
What about the other 300+ GitHub issues? It is confusing to track things in 2 places if you have stopped syncing them. Maybe just disable GitHub Issues altogether in the repo admin settings.
