### ISSUE TITLE
Jump Step Flagging too many Jumps due to an Incorrect Parameter being used in the Calculation of Read Noise in Grouped Data

### ISSUE THREAD

**Issue by mwregan2** [spacetelescope/jwst#4571]
The Jump step has a parameter mismatch between detect_jumps and find_crs(twopoint_difference). Detect_jumps is passing the number of groups in the integration rather than the number of frames in each group. For an integration with a large number of groups this difference leads to a large error in the value of the effective read noise and thus a large number of false positives in low flux regions. The fix is simple and has been coded. A test was added to recreate the problem before the fix.

**Comment by jdavies-st** [comment]
Thanks for debugging and fixing this @mwregan2 !

Could you create a separate branch and PR for this bugfix commit https://github.com/mwregan2/jwst/commit/a18f5f83a9f522a1a698e10782e75425666af50e that is separate from your `flag-CR-neighbors` branch/PR?  That way it can get a review and discussion on its own without being held up or buried in the review of the other PR.  They are really two separate things - one a bugfix and the other a feature enhancement.

Also, it looks like you've encapsulated a good unit test for this problem, so review should go quickly.

**Comment by philhodge** [comment]
I don't understand this.  I see the following in `detect_jumps` in jump.py (lines 55 and 110):

    nframes = input_model.meta.exposure.nframes
    median_slopes, gdq = twopt.find_crs(data, gdq, readnoise_2d, rejection_threshold, nframes)

**Comment by mwregan2** [comment]
Well, Phil's comment shows that the master version of detect_jumps is correct. So, this fix actually is needed to make the pull request work. I have to admit that I have no memory of changing the variables. It is a good lesson of the problems that poor variables names can cause. nframes should be called frames_per_group. After doing a lot of MIRI work where frames_per_group is always 1, I seem to have mapped nframes to be a synonym for ngroups.

**Comment by jdavies-st** [comment]
Ah, ok!  Thanks for the clarification.  So this issue only applies to #4434?

**Comment by philhodge** [comment]
No, I don't think it only applies to #4434.  It looks as if @mwregan2 found a serious bug in the jump step, but someone (apparently @jdavies-st ) has already fixed it.

**Comment by mwregan2** [comment]
From my reading of the history the master version of the code shows the last change for the affected code being four years ago. That looks like the first time that nframes was passed to find_crs and it passed the correct value. So I think the only place with the bug is in the pull request.

**Comment by jdavies-st** [comment]
Cool.  Thanks @mwregan2.  Feel free to close this issue then if you think it is not a change that needs to be done on `master`.

**Comment by mwregan2** [comment]
This is problem was introduced in PR #4434 and is now fixed in the same PR. I am closing the issue.
