### ISSUE TITLE
'ERR' cube is not populated after cube_build step for MIRI MRS. [Feature Request]

### ISSUE THREAD

**Issue by nenasedk** [spacetelescope/jwst#4582]
Error propagation seems to work up to the PHOTOM step, but the 'ERR' tag in the s3d.fits files are filled with only zeros. Should the error cube be built similarly to the science cube?

**Comment by nden** [comment]
@jemorrison Is this still an issue? If not, please close. Otherwise file a JP ticket.

**Comment by jemorrison** [comment]
The error plane is now populated in the s3d files
