### ISSUE TITLE
Unclosed file ResourceWarning for calwebb_image3

### ISSUE THREAD

**Issue by micaelabagley** [spacetelescope/jwst#4679]
All individual input files are left open, the resource warning occurs at shutdown of calwebb_image3

For example: 
2020-02-18 02:06:43,806 - stpipe - WARNING - sys:1: ResourceWarning: unclosed file <_io.FileIO name='calibrated/jw00042006003_01101_00014_nrcb4_cal.fits' mode='rb' closefd=True>

(jwst version 0.14.2)

**Comment by jdavies-st** [comment]
For clarification, the `ResourceWarning` is indicating that python closed these files at the end of the python session.  They should be closed via the context manager before python exits.  This is a known issue.  See #2887 and #2328
