### ISSUE TITLE
Call asdf.schema.get_validator with _visit_repeat_nodes flag

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/jwst#4864]
Version 2.6.0 of the asdf library improved validator efficiency by visiting nodes only once each, even if they were represented in the tree multiple times.  Unfortunately, this breaks datamodels fits output, which rides along with asdf validation and expects that nodes will be visited every time they show up in the tree.  Included in asdf 2.6.0 is a new flag, `_visit_repeat_nodes`, which will cause the validator to revert to its original behavior.

Currently the asdf requirement is restricted to `~=2.5.0`.  When we want to upgrade asdf, we'll need to change that to `>=2.6` and add `_visit_repeat_nodes=True` to the call to `get_validator` in `jwst.datamodels.fits_support._save_from_schema`. 

asdf 2.6.0 is compatible with both astropy 4.0.x and 4.1.x, but 4.1.x requires it, so making this change is a prerequisite to upgrading astropy.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1420](https://jira.stsci.edu/browse/JP-1420)._

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1420?focusedCommentId=463928#comment-463928):_

Fixed in #4905
