### ISSUE TITLE
Modify data type of HGA_motion column in GS Pointing table

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4888]
_Issue [JP-1428](https://jira.stsci.edu/browse/JP-1428) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The guidestar Pointing extension table column "hga_motion" is currently defined as integer data type and contains coded integer values of 0, 1, 2, 3. SDP is proposing to change the format to string, so that it can be populated directly with the values from the EngDB (JSDP-1549). Hence we should update our guider datamodel schemas to make this change in data type.

This work needs to be coordinated with SDP, so that the changes in both subsystems get delivered together.

**Comment by hbushouse** [comment]
Fixed in https://github.com/spacetelescope/jwst/pull/4946

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1428?focusedCommentId=464491#comment-464491):_

Fixed in #4946
