### ISSUE TITLE
Investigate the effect of removing default values in schemas on the pipeline

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4922]
_Issue [JP-1443](https://jira.stsci.edu/browse/JP-1443) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

It has become clear that having defaults in schemas is a hindrance to developing the asdf format and improving performance. There are occasions, especially with schema combiners, when it is difficult to decide which default should be used. The json schema standard does not enforce any rules about it. In asdf validation makes two passes, one of which is to fill in defaults. 

Given all these difficulties, it would make sense to remove defaults from our schemas. We need to understand what the impact of this on the JWST pipeline would be.

**Comment by jdavies-st** [comment]
I think the main feature of `default` in the ASDF schemas was to allow skipping of serialization of an item in the tree that was set to a default value.  Basically to save space in the output file.  In `jwst.datamodels`, we for the most part write out the ASDF to FITS, so there is no skipping of serialization and everything gets written out.  So if that feature went away, I don't think it would be a problem.

That said, we could still keep `default` as an allowed schema entry, and it might serve as an annotation in ASDF, and datamodels could still keep using that annotation as we have been doing, if that is desired.  Or we could remove it completely in ASDF core and add it as a feature in `datamodels` if that is desired.

Or we can clean up `jwst.datamodels` and be explicit about population of arrays with values, which might help out with some issues we've seen recently where arrays full of default values are getting written out inadvertently when an HDU gets auto-created from a header keyword.

**Comment by nden** [comment]
@jdavies-st Could you update the status of this. Could this be closed?

**Comment by jdavies-st** [comment]
Yes, I think this can be closed.

Special treatment of writing out (or not) of defaults in `asdf` has been removed in asdf 2.8.0 (unreleased so far)

https://github.com/asdf-format/asdf/pull/863

and `jwst` already supports this via https://github.com/spacetelescope/jwst/pull/5371

I think any further changes to how `jwst.datamodels` uses `defaul` in the schema would amount to an interface change and should be discussed separately.  Here, the question is, what should happen if (if anything) when I instantiate a model like:

```python
model = datamodels.ImageModel((10, 10))
```

Should I get back a model with the data array populated with a 10x10 array filled with the default value?  What about when I access the `err` array?  Should that then also get populated with an array of the same shape populated with the default value for `err`?  That's an interface change and outside the scope of the changes required for `asdf`.  I.e. this is an `stdatamodels` issue, not an `asdf` issue.

So yeah, I think this can be closed, and we can discuss interface changes, if desired, elsewhere.

@nden @hbushouse
