### ISSUE TITLE
Rules for excluding NIRSpec NRS1 or NRS2 detector from processing

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4971]
_Issue [JP-1466](https://jira.stsci.edu/browse/JP-1466) was created on JIRA by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol):_

For NIRSpec fixed slit mode with certain disperser and slit combinations, spectra do not fall on one of the two detectors.  In these instances, the calwebb_spec3 pipeline currently crashes because no level 2b products are generated.  The level 3 associations should not include any files for the detector with no data.  Here are the relevant combinations for which the indicated detector contains **no** data and should be **excluded** from the association:

 

NRS1:

slit S200B1 + PRISM/CLEAR, G140M/F100LP, G235M/F170LP, G395M/F290LP, G140H/F100LP, G235H/F170LP, G395H/F290LP

 

NRS2:

all slits other than S200B1 + PRISM/CLEAR, G140M/F070LP, G140M/F100LP, G235M/F170LP, G395M/F290LP, G140H/F070LP

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=481060#comment-481060):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) or [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)  Are these combinations in a list of "do not process"? and if they are, where is that list? i.e. how the Calibration  Pipeline knows that these should not be processed because they don't have data.

**Comment by nden** [comment]
In these cases the assign_wcs step does not run and is set to `SKIPPED`. The calspec2 pipeline checks this and knows to skip further processing.

There are two ways the combinations can be skipped. One is to have a hard-coded list like the one above. The other is to run the transform from slit to detector and exclude the slit from processing if it does not. 

I chose the second option for two reasons. There are certain cases, for example with MOS mode, when some slitlets fall outside the detector although the combinations in general are valid. In that case the above list will not help. I think we still need to take into consideration this case when thinking about calspec3. The second is the list was not available at the time.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=481116#comment-481116):_

The rules could be encoded into the level-2b and level-3 asn generator rules, such that no spec2 or spec3 ASN's get generated for these detector+disperser combinations and hence processing (at least within the Ops environment) will not get triggered to begin with, thus processing would stop with the level-2a (rate) products.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=481125#comment-481125):_

To re-iterate what [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) said, one can do some pre-filtering on optical configuration, but even with valid combinations, there will be cases where no data appears on the NRS2 detector.

In ground processing, `Spec2Pipeline` returns a different code to indicate whether an exposure has no valid data on it. Ground processing recognizes this state and then removes that exposure from further processing.

At what point are these crashes being seen?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483635#comment-483635):_

The ticket as written applies to fixed-slit exposures. Are there similar situations for the IFU and MOS modes? We recently had an NRS2 IFU exposure using PRISM/Clear fail in calwebb_spec2 due to "jwst.assign_wcs.util.NoDataOnDetectorError: No IFU slices fall on detector NRS2".

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483674#comment-483674):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Yes. IFU plus PRISM, any of the medium-resolution gratings, or G140H+F070LP will only project spectra onto NRS1.  MOS could have no data on either detector, depending on which shutters are opened (I think the pipeline is already set up to handle that case, though?).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483703#comment-483703):_

Thanks. Yes, for all modes the assign_wcs step is setup to detect when no data falls on a given detector and abort the remaining calspec2 processing. The only cases we can predict and head-off ahead of time (in the ASN generator) are the FS and IFU grating+filter combinations for which we know there will never be any data on a given detector.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483712#comment-483712):_

For combinations of optical elements that are know to never produce science data on a particular detector, such combinations can be encoded in the association rules such that they will not appear in Level 2 or Level 3 associations.

For the cases, such as MOS, where the "no science" situation is only known after stage 2 processing, the ground system is setup to handle, and the archived products are correct in that any exposure that results in "no science" are removed from all level 3 associations.  This should be the current state now, even without the aforementioned association changes.

If there are situations found that archived level 3 association still have exposures without science, those exact situations should be filed as issues against the JP project.

For the use-case where users are creating their own associations, it is up the user to ensure their associations are correct.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=497676#comment-497676):_

## Clarification of Coverage of the FS modes

The wording in the description leaves out a few of the modes, hence leading to some ambiguity. As such, using jdocs as the reference, the below list of slit/mode vs detector has been created. Is this accurate?

For all A slits:
 * prism/clear: nrs1
 * g395h/f290lp: nrs1/nrs2
 * g235h/f170lp: nrs1/nrs2
 * g140h/f100lp: nrs1/nrs2
 * g140h/f070lp: nrs1
 * g395m/f290lp: nrs1
 * g235m/f170lp: nrs1
 * g140m/f100lp: nrs1
 * g140m/f070lp: nrs1

For S200B1:
 * prism/clear: nrs2
 * g395h/f290lp: nrs2
 * g235h/f170lp: nrs2
 * g140h/f100lp: nrs2
 * g140h/f070lp: nrs1/nrs2
 * g395m/f290lp: nrs2
 * g235m/f170lp: nrs2
 * g140m/f100lp: nrs2
 * g140m/f070lp: nrs1/nrs2

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=498642#comment-498642):_

Also, for documentation and clarification, the IFU modes and their respective detector usage is as follows:
* prism/clear: nrs1
* (g395m, g235m, g140m)/(all filters): nrs1
* (g395h, g235h)/(all filters): nrs1/nrs2
* g140h/f070lp: nrs1
* g140h/f100lp: nrs1/nrs2

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=498737#comment-498737):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) the above lists are correct.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=499020#comment-499020):_

Resolved by [PR #&#x2060;5504](https://github.com/spacetelescope/jwst/pull/5504)

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=481060#comment-481060):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) or [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)  Are these combinations in a list of "do not process"? and if they are, where is that list? i.e. how the Calibration  Pipeline knows that these should not be processed because they don't have data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=481116#comment-481116):_

The rules could be encoded into the level-2b and level-3 asn generator rules, such that no spec2 or spec3 ASN's get generated for these detector+disperser combinations and hence processing (at least within the Ops environment) will not get triggered to begin with, thus processing would stop with the level-2a (rate) products.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=481125#comment-481125):_

To re-iterate what [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) said, one can do some pre-filtering on optical configuration, but even with valid combinations, there will be cases where no data appears on the NRS2 detector.

In ground processing, `Spec2Pipeline` returns a different code to indicate whether an exposure has no valid data on it. Ground processing recognizes this state and then removes that exposure from further processing.

At what point are these crashes being seen?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483635#comment-483635):_

The ticket as written applies to fixed-slit exposures. Are there similar situations for the IFU and MOS modes? We recently had an NRS2 IFU exposure using PRISM/Clear fail in calwebb_spec2 due to "jwst.assign_wcs.util.NoDataOnDetectorError: No IFU slices fall on detector NRS2".

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483674#comment-483674):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Yes. IFU plus PRISM, any of the medium-resolution gratings, or G140H+F070LP will only project spectra onto NRS1.  MOS could have no data on either detector, depending on which shutters are opened (I think the pipeline is already set up to handle that case, though?).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483703#comment-483703):_

Thanks. Yes, for all modes the assign_wcs step is setup to detect when no data falls on a given detector and abort the remaining calspec2 processing. The only cases we can predict and head-off ahead of time (in the ASN generator) are the FS and IFU grating+filter combinations for which we know there will never be any data on a given detector.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=483712#comment-483712):_

For combinations of optical elements that are know to never produce science data on a particular detector, such combinations can be encoded in the association rules such that they will not appear in Level 2 or Level 3 associations.

For the cases, such as MOS, where the "no science" situation is only known after stage 2 processing, the ground system is setup to handle, and the archived products are correct in that any exposure that results in "no science" are removed from all level 3 associations.  This should be the current state now, even without the aforementioned association changes.

If there are situations found that archived level 3 association still have exposures without science, those exact situations should be filed as issues against the JP project.

For the use-case where users are creating their own associations, it is up the user to ensure their associations are correct.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=497676#comment-497676):_

## Clarification of Coverage of the FS modes

The wording in the description leaves out a few of the modes, hence leading to some ambiguity. As such, using jdocs as the reference, the below list of slit/mode vs detector has been created. Is this accurate?

For all A slits:
 * prism/clear: nrs1
 * g395h/f290lp: nrs1/nrs2
 * g235h/f170lp: nrs1/nrs2
 * g140h/f100lp: nrs1/nrs2
 * g140h/f070lp: nrs1
 * g395m/f290lp: nrs1
 * g235m/f170lp: nrs1
 * g140m/f100lp: nrs1
 * g140m/f070lp: nrs1

For S200B1:
 * prism/clear: nrs2
 * g395h/f290lp: nrs2
 * g235h/f170lp: nrs2
 * g140h/f100lp: nrs2
 * g140h/f070lp: nrs1/nrs2
 * g395m/f290lp: nrs2
 * g235m/f170lp: nrs2
 * g140m/f100lp: nrs2
 * g140m/f070lp: nrs1/nrs2

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=498642#comment-498642):_

Also, for documentation and clarification, the IFU modes and their respective detector usage is as follows:
* prism/clear: nrs1
* (g395m, g235m, g140m)/(all filters): nrs1
* (g395h, g235h)/(all filters): nrs1/nrs2
* g140h/f070lp: nrs1
* g140h/f100lp: nrs1/nrs2

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=498737#comment-498737):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) the above lists are correct.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1466?focusedCommentId=499020#comment-499020):_

Resolved by [PR #&#x2060;5504](https://github.com/spacetelescope/jwst/pull/5504)
