### ISSUE TITLE
Fix remaining open files issues due to latest pytest-openfiles

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4978]
_Issue [JP-1468](https://jira.stsci.edu/browse/JP-1468) was created on JIRA by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

There's some open files issues raised with `pytest-openfiles 0.7`.  Fix them.

**Comment by jdavies-st** [comment]
These can be seen here (internal only)

https://plwishmaster.stsci.edu:8081/job/RT/job/eslavich-dev/21/testReport/
