### ISSUE TITLE
HDRTAB should contain only a single entry for each exposure

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4985]
_Issue [JP-1472](https://jira.stsci.edu/browse/JP-1472) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

When CubeModel data are used as input to steps like resample, which run blendheaders to create a HDRTAB extension, they are typically reorganized into a ModelContainer where each ImageModel in the container is the image from a single plane (integration) in the original CubeModel, so that the resample step itself doesn't have to reorganize the data before combining. This has an undesirable side effect in that the blendheaders routine then treats each of those images contained in the ModelContainer as is it were from a separate exposure and hence creates multiple rows in the HDRTAB table that contain identical data (because they're all from the same exposure).

An example of this behavior is when running the calwebb_coron3 pipeline on exposures that have NINTS>1, resulting in NINTS rows for each original exposure in the HDRTAB extension of the i2d product.

Updates should be made to only create a single row in the HDRTAB for a given filename value of the inputs.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1472?focusedCommentId=465823#comment-465823):_

This same problem likely also exists for any combined products created for TSO mode data, since they're also processed at the integration level. While TSO data don't go through the resample step, there may be other types of combined products created by the calwebb_tso3 pipeline that contain a HDRTAB extension.

**Comment by jdavies-st** [comment]
When there's a single cube, we probably don't have to make any HDRTAB, as there's no blending needed. Agree that when we have more than one, we only want one row (and one blending pass) per input file.

**Comment by jdavies-st** [comment]
One option would be to pull the header blending into a separate step that can be called via a hook.  I.e. take it out of `resample` completely.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1472?focusedCommentId=467064#comment-467064):_

Resolved by [PR #&#x2060;5007](https://github.com/spacetelescope/jwst/pull/5007)
