### ISSUE TITLE
Add note to installation instructions that Windows compatibility is not supported 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4988]
_Issue [JP-1474](https://jira.stsci.edu/browse/JP-1474) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

We should add a note to the installation instructions (and mabye ReadTheDocs/JDox?) that, while the software should install and run for Windows, it is not currently supported. This question came up in the DMSWG meeting today.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1474?focusedCommentId=465909#comment-465909):_

[Steven Crawford](https://jira.stsci.edu/secure/ViewProfile.jspa?name=scrawford) FYI

**Comment by stscijgbot-jp** [comment]
_Comment by [Steven Crawford](https://jira.stsci.edu/secure/ViewProfile.jspa?name=scrawford) on [JIRA](https://jira.stsci.edu/browse/JP-1474?focusedCommentId=465912#comment-465912):_

Thanks Alicia - I'm adding [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp).  This is our current position and you are right we should add a note.   

We could try to consider adding in Windows builds on conda as we have had requested from other users as well for this.   However, there is no guarantee that all the dependencies and everything will work and that will require more testing and support.

**Comment by jdavies-st** [comment]
We don't know if it runs on Windows because we don't test it.  Maybe a good first step would be to add a job to our Travis CI matrix that runs our unit tests on a Windows box and see what breaks.  And then fix it.  Then I think we can say something more definitive in our documentation.

**Comment by jdavies-st** [comment]
Based on the results of #4993, there are 163 unit test failures in `jwst` when run on Windows.

https://travis-ci.org/github/spacetelescope/jwst/jobs/692239993#L76133-L76304

A number of these come via `crds`, which also does not support Windows.

```
>               raise CrdsDownloadError(
                    "Failed caching mapping files:", str(exc)) from exc
E               crds.core.exceptions.CrdsDownloadError: Failed caching mapping files: Error fetching data for 'jwst_system_datalvl_0002.rmap' at CRDS server 'https://jwst-crds.stsci.edu' with mode 'http' : [WinError 3] The system cannot find the path specified: 'C:\\Users\\travis\\AppData\\Local\\Temp\\crds_cache\\mappings\\jwst'

c:\python38\lib\site-packages\crds\core\heavy_client.py:354: CrdsDownloadError
```

And others come from the assumption that we are running on a unix system, but can probably easily be fixed in the future.

```
>       log.log.info("Hostname: {0}".format(os.uname()[1]))
E       AttributeError: module 'os' has no attribute 'uname'
```

So I suspect a hard "We do not support Windows" would be the correct message now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Steven Crawford](https://jira.stsci.edu/secure/ViewProfile.jspa?name=scrawford) on [JIRA](https://jira.stsci.edu/browse/JP-1474?focusedCommentId=466218#comment-466218):_

Thanks for running the test – I'm going to move the question on supporting windows in another thread, and we can keep this ticket on just updating the documentation which should be quick to do.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1474?focusedCommentId=466260#comment-466260):_

FYI: See jp-1245 and another issue about command-line tools need to be made entry points. Can't find it; it may be a github-only issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1474?focusedCommentId=466860#comment-466860):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)  [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies)  [Steven Crawford](https://jira.stsci.edu/secure/ViewProfile.jspa?name=scrawford) 

I'll go ahead and update the JDox page ([https://jwst-docs.stsci.edu/jwst-data-reduction-pipeline)] in version 1.1 to also include a similar note (unless one of you would rather update JDox). I figured it's not urgent enough to update the frozen version of JDox since it points to the github repo and the readthedocs anyway, but I don't want to forget about it, so I can go ahead and make the edit in the next version. Sound good?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1474?focusedCommentId=466868#comment-466868):_

(y)

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1474?focusedCommentId=469234#comment-469234):_

Version 1.1 JDox page w/ added note: <https://jwst-docs.stsci.edu/display/JDOX/.JWST+Data+Reduction+Pipeline+v1.1>
