### ISSUE TITLE
Add default to datamodels 'lamp_mode' entry

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5022]
_Issue [JP-1496](https://jira.stsci.edu/browse/JP-1496) was created on JIRA by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij):_

Since the datamodel parameter meta.instrument.lamp_mode will be used as a parkey for reference files, and since some of our test data doesn't have the OPMODE keyword, set the default value of meta.instrument.lamp_mode to 'NONE' so that CRDS can do a lookup even if the OPMODE keyword isn't present in the FITS header.  Also add enum entries for this attribute.

**Comment by hbushouse** [comment]
Fixed by #5024

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1496?focusedCommentId=468927#comment-468927):_

Fixed by #5024
