### ISSUE TITLE
DataModel mishandles unsigned integers from fits BinTableHDU

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5089]
_Issue [JP-1548](https://jira.stsci.edu/browse/JP-1548) was created on JIRA by [James White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jwhite):_

BinTableHDU data from a reference file being read into its corresponding DataModel produces unexpected results from a column that's stored as an unsigned integer. 

 

For example, with reference file 'jwst_miri_apcorr_0004.fits' when read in with its DataModel:
```java
model = MiriLrsApcorrModel('jwst_miri_apcorr_0004.fits')
model.apcorr_table[model.apcorr_table['SUBARRAY'] == 'SLITLESSPRISM']['nelem_wl']
Out[12]: array([-32380], dtype=int16)
```
However, when the data is then read in with fits.open:
```java
data = fits.getdata('jwst_miri_apcorr_0004.fits')
data[data['SUBARRAY'] == 'SLITLESSPRISM']['nelem_wl']
Out[13]: array([388], dtype=uint16) 
```
This test was performed with the latest version of asdf which includes a fix for a (possibly) similar issue in ~~AL-335~~

 

Additionally, I've used a similar testing script which uses a BinTableHDU rather than an ImageHDU when generating the test data with results:
```java
Creating the data...
uint32_data = [2147483648 2147483648 2147483648]
uint32_data dtype = uint32 order = "="
asdf_in_fits = [(2147483648,) (2147483648,) (2147483648,)]
asdf_in_fits dtype = (numpy.record, [('col1', '<i4')]) order = "|"
Now read it back in...
back_in = [(0,) (0,) (0,)]
back_in dtype = (numpy.record, [('col1', '>i4')]) order = "|"
back_in_hduls = [(2147483648,) (2147483648,) (2147483648,)]
back_in_hduls dtype = (numpy.record, [('col1', '>i4')]) order = "|"
Convert to little-ending...
back_in = [0 0 0]
```

**Comment by jdavies-st** [comment]
Just so the code snipped that produced the above output is capture on the github issue:

```
import numpy as np
from asdf.fits_embed import AsdfInFits
from astropy.io import fits
from astropy.table import Table

print('Creating the data...')
uint32_data = np.array([2147483648] * 3, dtype=np.uint32)
print(f'uint32_data = {uint32_data}')
print(f'uint32_data dtype = {uint32_data.dtype}'
      f' order = "{uint32_data.dtype.byteorder}"'
)

hduls = fits.HDUList()
hduls.append(fits.BinTableHDU(Table({'col1': uint32_data}), name='UDATA'))

tree = {
    'udata': {
        'data': hduls['udata'].data
    }
}

asdf_in_fits = AsdfInFits(hduls, tree)
print(f'asdf_in_fits = {asdf_in_fits.tree["udata"]["data"]}')
print(f'asdf_in_fits dtype = {asdf_in_fits.tree["udata"]["data"].dtype}'
      f' order = "{asdf_in_fits.tree["udata"]["data"].dtype.byteorder}"'
)

asdf_in_fits.write_to('uint32.fits', overwrite=True)

print('\nNow read it back in...')
back_in = AsdfInFits.open('uint32.fits')
back_in_data = back_in['udata']['data'][:]  # Force load
print(f'back_in = {back_in_data}')
print(f'back_in dtype = {back_in_data.dtype}'
      f' order = "{back_in_data.dtype.byteorder}"'
)

back_in_hduls = fits.open('uint32.fits')
print(f'back_in_hduls = {back_in_hduls["UDATA"].data}')
print(f'back_in_hduls dtype = {back_in_hduls["UDATA"].data.dtype}'
      f' order = "{back_in_hduls["UDATA"].data.dtype.byteorder}"'
)

print(f'\nConvert to little-ending...')
print(f'back_in = {np.ndarray(back_in_data.shape, dtype="<u4", buffer=back_in_data)}')
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=470119#comment-470119):_

I think this is happening because astropy.io.fits.FITS_rec is reporting a dtype that doesn't match the data.  If you look at the dtype of the BinTableHDU data attribute:

 

In [9]: hdu = fits.BinTableHDU(Table(\{'col1': uint32_data}), name='UDATA')

In [10]: hdu.data
Out[10]:
FITS_rec([(2147483648,), (2147483648,), (2147483648,)],
 dtype=(numpy.record, [('col1', '<i4')]))

 

... which is wacky, because 2147483648 can't be represented in a signed 4-byte integer.  There's an [open issue](https://github.com/astropy/astropy/issues/8862) on astropy to fix this.

**Comment by jdavies-st** [comment]
Yeah, the FITS_rec is misreporting what the dtype actually is.

```
In [49]: for colname in hdu.data.names: 
    ...:     print(hdu.data.dtype[colname]) 
    ...:     print(hdu.data[colname].dtype) 
    ...:                                                                                                                      
int32
uint32
```

And both `asdf` and `jwst.datamodels` are taking the `int32` at face value, when it is really an `uint32`.

**Comment by stscijgbot-jp** [comment]
_Comment by [James White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jwhite) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=470168#comment-470168):_

Yikes. 

 

Thanks [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) and [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) for finding this. I didn't even notice the sketchy output dtypes. Is there a workaround in data models that we could implement to get around this issue while we're waiting on the fix in astropy?

**Comment by stscijgbot-jp** [comment]
_Comment by [James White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jwhite) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=470176#comment-470176):_

Wait... isn't jwst.datamodels.util.gentle_asarray supposed to be the actual workaround?

**Comment by stscijgbot-jp** [comment]
_Comment by [James White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jwhite) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=470203#comment-470203):_

```java
new_dtype = []
for i in range(len(out_dtype.fields)):
    in_type = in_dtype[i]
    out_type = out_dtype[i]
    if in_type.subdtype is None:
        type_str = in_type.str
    else:
        type_str = in_type.subdtype[0].str
    if np.can_cast(in_type, out_type, 'equiv'):
        new_dtype.append(
            (out_dtype.names[i],
             type_str,
             in_type.shape))
    else:
        return np.asanyarray(a, dtype=out_dtype)   # Why return here? It would mean that other cols in later iterations wouldn't be evaluated
return a.view(dtype=np.dtype(new_dtype))
```

**Comment by jdavies-st** [comment]
Yeah, Ed implemented a fix in `gentle_asarray`as a work-around.  But it may be being undone.  Here's where all that is called

https://github.com/spacetelescope/jwst/blob/ff9fc3352f00fded08590518d70446804295e4e7/jwst/datamodels/properties.py#L84-L88

and that last line is important, as it looks like it is undoing the fix.

https://github.com/spacetelescope/jwst/blob/ff9fc3352f00fded08590518d70446804295e4e7/jwst/datamodels/properties.py#L106

Though I don't have time to debug this today.

There's a lot of logic in these functions.  I really hate this paradigm of taking all the data and running them through a dozen functions, each function having it's own logic of whether it does anything to the data or not.  The logic for how a particular datatype is handled is spread over several functions, 9 out of 10 being red herrings, and it makes it very difficult to test.  Better to have the logic in one place, and then it either calls the function or not.  And the function does one thing to do the data, if necessary.  You're much less likely to have oddball side effects.  /endrant

**Comment by stscijgbot-jp** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=535171#comment-535171):_

spacetelescope/stdatamodels#75

**Comment by stscijgbot-jp** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=535232#comment-535232):_

The stdatamodels PR above makes a change to the gentle_asarray function to only allow safe casts, and raise an error otherwise.  Here's a jwst PR showing the test failures that result:

#6170

The failures are due to a combination of:

- Step code that assigns arrays to models with dtype incompatible with the schema (float64 for a float32 schema, or int16 for uint32, etc)
- Test code that does the same thing when creating dummy data for models
- Reference files that contain data with the wrong dtype.  There are 770 of these in the current context, I'll attach a list to this issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=537168#comment-537168):_

FYI, the particular ref file that started this whole investigation - jwst_miri_apcorr_0004.fits - was found to be bad, in that the dtype for the nelem_wl column did not match the apcorr schema definition and hence was replaced long ago by an updated ref file (jwst_miri_apcorr_0007.fits). Quoting the delivery log for the new ref file "The previous version of the JWST MIRI LRS apcorr file had a column, nelem_wl, defined as data type uint16 rather than a regular signed integer, int16 as specified in the JWST data model, which caused problems in the pipeline. This column data type has been updated in this version of the file."

So to a certain extent this whole ticket is now moot. That ref file should be erased from CRDS and never allowed to be used anywhere ever again. There's no purpose in keeping it around, because it won't work with any version of the pipeline software.

**Comment by stscijgbot-jp** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=546075#comment-546075):_

I did some further investigation on this and identified a batch of files in the current context (jwst_0747.pmap) that datamodels is also mishandling:


```
jwst_miri_flat_0364.fits
jwst_miri_flat_0365.fits
jwst_miri_flat_0366.fits
jwst_miri_flat_0368.fits
jwst_miri_flat_0370.fits
jwst_miri_flat_0371.fits
jwst_miri_flat_0373.fits
jwst_miri_flat_0375.fits
jwst_miri_flat_0376.fits
jwst_miri_flat_0377.fits
jwst_miri_flat_0378.fits
jwst_miri_flat_0379.fits
jwst_miri_flat_0381.fits
jwst_miri_flat_0383.fits
jwst_miri_flat_0384.fits
jwst_miri_flat_0385.fits
jwst_miri_flat_0386.fits
jwst_miri_flat_0387.fits
jwst_miri_flat_0389.fits
jwst_miri_flat_0391.fits
jwst_miri_flat_0393.fits
jwst_miri_flat_0394.fits
jwst_miri_flat_0395.fits
jwst_miri_flat_0396.fits
jwst_miri_flat_0397.fits
jwst_miri_flat_0399.fits
jwst_miri_flat_0400.fits
jwst_miri_flat_0401.fits
jwst_miri_flat_0402.fits
jwst_miri_flat_0404.fits
jwst_miri_flat_0405.fits
jwst_miri_flat_0406.fits
jwst_miri_flat_0407.fits
jwst_miri_flat_0409.fits
jwst_miri_flat_0411.fits
jwst_miri_flat_0413.fits
jwst_miri_flat_0414.fits
jwst_miri_flat_0416.fits
jwst_miri_flat_0417.fits
jwst_miri_flat_0418.fits
jwst_miri_flat_0419.fits
jwst_miri_flat_0420.fits
jwst_miri_flat_0421.fits
jwst_miri_flat_0424.fits
jwst_miri_flat_0425.fits
jwst_miri_flat_0427.fits
jwst_miri_flat_0428.fits
jwst_miri_flat_0430.fits
jwst_miri_flat_0431.fits
jwst_miri_flat_0432.fits
jwst_miri_flat_0434.fits
jwst_miri_flat_0435.fits
jwst_miri_flat_0438.fits
jwst_miri_flat_0439.fits
jwst_miri_flat_0443.fits
jwst_miri_flat_0444.fits
jwst_miri_flat_0445.fits
jwst_miri_flat_0446.fits
jwst_miri_flat_0448.fits
jwst_miri_flat_0449.fits
jwst_miri_flat_0450.fits
jwst_miri_flat_0451.fits
jwst_miri_flat_0452.fits
jwst_miri_flat_0456.fits
jwst_miri_flat_0457.fits
jwst_miri_flat_0458.fits
jwst_miri_flat_0459.fits
jwst_miri_flat_0460.fits
jwst_miri_flat_0461.fits
jwst_miri_flat_0462.fits
jwst_miri_flat_0463.fits
jwst_miri_flat_0464.fits
jwst_miri_flat_0465.fits
jwst_miri_flat_0468.fits
jwst_miri_flat_0469.fits
jwst_miri_flat_0471.fits
jwst_miri_flat_0472.fits
jwst_miri_flat_0473.fits
jwst_miri_flat_0556.fits
jwst_miri_flat_0557.fits
jwst_miri_flat_0558.fits
jwst_miri_flat_0559.fits
jwst_miri_flat_0560.fits
jwst_miri_flat_0561.fits
jwst_miri_flat_0562.fits
jwst_miri_flat_0563.fits
jwst_miri_flat_0564.fits
jwst_miri_flat_0565.fits
jwst_miri_flat_0566.fits
jwst_miri_flat_0567.fits
jwst_miri_flat_0568.fits
jwst_miri_flat_0569.fits
jwst_miri_flat_0570.fits
jwst_miri_flat_0571.fits
jwst_miri_flat_0572.fits
jwst_miri_flat_0573.fits
jwst_miri_flat_0574.fits
jwst_miri_flat_0575.fits
jwst_miri_flat_0576.fits
jwst_miri_flat_0577.fits
jwst_miri_flat_0578.fits
jwst_miri_flat_0579.fits
jwst_miri_flat_0580.fits
jwst_miri_flat_0581.fits
jwst_miri_flat_0582.fits
jwst_miri_flat_0583.fits
jwst_miri_flat_0584.fits
jwst_miri_flat_0585.fits
jwst_miri_flat_0586.fits
jwst_miri_flat_0587.fits
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/JP-1548?focusedCommentId=547592#comment-547592):_

The miri flats listed above have been replaced, and the next version of stdatamodels (0.3.0) will raise an exception when it detects this problem.
