### ISSUE TITLE
Modify calspec2 steps to allow for return of correction arrays

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5105]
_Issue [JP-1558](https://jira.stsci.edu/browse/JP-1558) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

In order to accommodate the updates needed to support NIRSpec master background subtraction for MOS and FS modes (JP-1213 and JP-1493) it will be necessary to modify the calwebb_spec2 steps flat-field, pathloss, barshadow, and photom to allow them to be called in a way that they just compute and return the appropriate 2D correction array, rather than actually applying the correction to the input science data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1558?focusedCommentId=475129#comment-475129):_

The reason we need the correction arrays from these steps is so that we can imprint/impose the effect into the otherwise perfect background signal (i.e. impose the flat-field variations into the bkg data, impose the pathloss and barshadow effects into the data, etc.). So I'm wondering if there might be some clever way that we could modify each step such that they still return only the modified science data (as they do now), but have a switch that down inside the step flips the parity of the way each correction is applied? i.e. instead of dividing the flat-field reference data into the science data, multiply by it. Same things with pathloss and the others. Or is this just wacko?

**Comment by nden** [comment]
A step needs input science data, some reference data and an operation on those which creates the output data, which is the typical forward operation. We could introduce a `Step.inverse` method which still uses the reference data but takes the output and computes the input. This can't be done for all steps (e.g. multiple inputs, one output) but in cases where not possible `Step.inverse` can return `None` or simply return the input where appropriate. If that's the case then we could even have an inverse for the entire level 2 pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1558?focusedCommentId=475331#comment-475331):_

## Design

This comment will represent what will be implemented to resolve this issue. This comment should be updated with any modifications that occur due to later comments/offline discussions.
## Goal

Provide inverse functionality to selected steps such that calibrated data, such as master background, can be un-calibrated back to a pseudo-detector state to better match science-in-detector-state that it may be applied to.
## Implementation

For steps
 * flat field
 * pathloss
 * barshadow
 * photom

modify such that
 * Internal/private functions to implement the inverted code
 * Access that inverted code

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1558?focusedCommentId=475463#comment-475463):_

## Question

Is it possible that the input science will have one or more of the steps skipped? If so, should the corresponding step not be un-applied on the background?  I.e. if the science skipped `flat_field`, the background will not have `flat_field` un-applied.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1558?focusedCommentId=475479#comment-475479):_

I guess that scenario is possible, but would be off-nominal and hence I don't think we should put effort into supporting it. For the case of NIRSpec MOS, if we end up using the design outlined in JP-1493 where this gets applied to source slitlets right after they come out of the spec2 extract_2d step, they will in fact have none of the subsequent calibrations applied to them yet (wavecorr, flat_field, pathloss, barshadow, photom) which is why we need to impose the inverse of those corrections into the bkg data, so that they match.

If we wait till later in the calibration flow, when the source slitlets have been fully calibrated, then the problem is even more severe, because the calibrations applied to the source slitlets can be different than the calibration that's appropriate for the bkg signal in those source slitlets. So then we need to apply/unapply the ratio of source/bkg calibrations in order to get the pristine master bkg signal to match the bkg signal in the source slitlet. Speaking of which, that use case (which may be needed for NIRSpec FS mode), would likely still require a mode for each of the flat_field, pathloss, barshadow, photom steps in which they just return the correction arrays without modifying the data. Each step will need to be called twice, to compute the correction array that **was used** for the source slitlet when it went through those spec2 steps, as well as the correction array that **should have been used** for the bkg signal in that source slitlet, and then apply the ratio of those 2 correction arrays to the pristine bkg data to make it match the actual bkg signal contained in the source slitlet.

I suppose the same mathematical result could be achieved by first calling a step in inverse mode, to essentially remove the calibration that had been applied earlier, and then call the step again in forward (normal) mode to apply the correction appropriate for the bkg signal only.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1558?focusedCommentId=480331#comment-480331):_

Resolved by [PR #&#x2060;5268](https://github.com/spacetelescope/jwst/pull/5268)
