### ISSUE TITLE
Is there a way to set pixel size when merging exposures?

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#5106]
Hi, 
I'm trying to merge a few MIRI imaging exposures. The resulting image has a pixel size of 0.11 arcsec. But is there a way to set another pixel size, say 0.06 arcsec? 
Thanks,
Guang

**Comment by jdavies-st** [comment]
Not currently.  This issue is related to #4764

**Comment by Guang91** [comment]
Thanks, @jdavies-st
