### ISSUE TITLE
cube build crashes with Lvl2 association files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5115]
_Issue [JP-1560](https://jira.stsci.edu/browse/JP-1560) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

When testing spec2 associations I noticed that they cause cube building to crash with incorrect channel configurations.  Although running each rate file through calwebb_spec2 individually works fine, running the association file through calwebb_spec2 does not.  It works ok up to the _cal.fits stage if I disable cube build and extract1d, but not if those two steps are on.

Error message for the crash is:

2020-06-30 12:48:18,511 - stpipe.Spec2Pipeline.photom - INFO - Step photom done
2020-06-30 12:48:18,771 - stpipe.Spec2Pipeline.cube_build - INFO - Step cube_build running with args (<IFUImageModel(1024, 1032) from det_image_seq4_MIRIFULONG_34LONGexp1_cal.fits>,).
Traceback (most recent call last):
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 95, in process
 asn.filename
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 306, in process_exposure_product
 result_extra = self.cube_build(result)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 357, in run
 f'Step \{self.name} parameters are: \{self.get_pars()}'
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 1221, in get_pars
 pars = config_parser.config_from_dict(instance_pars, spec, allow_missing=True)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/config_parser.py", line 301, in config_from_dict
 validate(config, spec, root_dir=root_dir, allow_missing=allow_missing)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/config_parser.py", line 390, in validate
 raise ValidationError('\n'.join(messages))
jwst.stpipe.config_parser.ValidationError: Config parameter 'channel': the value "" is unacceptable.
Config parameter 'filter': the value "" is unacceptable.
Config parameter 'grating': the value "" is unacceptable.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
 One or more products failed to process. Failing calibration.
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/Users/drlaw/jwcode/jwst/scripts/strun", line 26, in <module>
 step = Step.from_cmdline(sys.argv[1:])
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 156, in from_cmdline
 return cmdline.step_from_cmdline(args)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
 step.run(*positional)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 392, in run
 step_result = self.process(*args)
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 111, in process
 'One or more products failed to process. Failing calibration.'
RuntimeError: One or more products failed to process. Failing calibration.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=472973#comment-472973):_

calwebb_spec2 is intended to only process one exposure at a time. So I assume the use case of having more than one exposure listed in the ASN file is simply to make it easier to process multiple exposures - one at a time - through all the steps of calwebb_spec2. In other words, you're not expecting them to be combined, right? I believe this use case of having the processing loop through a list of multiple exposures did work in the past, so something must've changed somewhere.

**Comment by jemorrison** [comment]
ok I will look into this. The error about the config parameter related to grating and filter is NIRSPEC requirement. I believe I have using associations to run calspec2 in the past.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473000#comment-473000):_

Clarification on spec2 and associations: There are two aspects: multiple products and multiple members in a product. For spec2, per product, there should be only one science exposure. There may be other exposures, but they should only be "background".  spec2 can handle multiple products, though this capability is not used in ground system processing and may be removed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473005#comment-473005):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) I can see the files in the directory listed above, but permissions don't allow me to see into or copy any of the individual files, including the l2_asn.json file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473007#comment-473007):_

[Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) if this use case is what we think it is, then it's non-standard for normal Operational processing (in normal Ops there's always only 1 product defined in a Lvl2 ASN file) and hence you may want to rethink the priority level.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473020#comment-473020):_

Thanks, [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse), I'll remove our final priority label until we hear more from INS.

**Comment by jemorrison** [comment]
I looked into this issue. I ran cal_spec2 using an association of 2 MIRI MRS files just to see what it would do.
It ran the spec2 pipeline on the first file in the association.  All the steps in spec2 pipeline ran.
 Since there is only 1 output product name  the final output name of the cal file, FU cube and the extract 1d for this single file was the one given in the association: det_image_cal.fits, det_image_s3d.fits and det_image_1xd.fits. 
I defer to Jonathon and Howard - but  I really don't think this makes sense to run calspec2 on an
association containing more than 1 file but only having 1 product name. Even if it ran over both files the final output name for cube_build, cal and extract 1d would have the same name.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473221#comment-473221):_

You're correct [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) that a Lvl2 ASN should not have multiple science members per product (that's for Lvl3). But what it can allow is multiple products, each containing one member, in which case it'll just loop over the creation of each product one at a time (or at least it should). I'm assuming the case here is the latter, but we won't know that for sure until the file permissions are changed to allow us to see the Lvl2 ASN file ("l2_asn.json"). Or simply attach that file to this ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473893#comment-473893):_

Reading <https://jwst-pipeline.readthedocs.io/en/latest/jwst/associations/asn_from_list.html#level2-associations> my take-away was that l2 associations could include multiple science files (e.g., all science files for a given visit), so long as they each had their own entry in the 'products' category.  (Permissions should now be fixed on the central store directory by the way to see the original example asn file).

It sounds like that's not the case though, and normal flight operations will treat each science frame individually for spec2 associations?

If so, perhaps this is a documentation issue and the above link simply needs to be updated to remove description of lvl2 files producing products for multiple input files with different names.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473894#comment-473894):_

Also attaching the asn file directly to this ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473914#comment-473914):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) you're correct in your interpretation of the docs in that you should be able to specify multiple **products** within a spec2 ASN, such that calwebb_spec2 should then just loop over the creation of them one at a time, so that the user doesn't have to create n separate ASN's and run calwebb_spec2 n times. What calwebb_spec2 can NOT do is combine the data from more than 1 science member within a single product. The only time a spec2 ASN can have multiple members within a given product is if the additional members are background exposures. Only 1 member per product can be tagged as "science".

At first glance it appears that your ASN file conforms to this and should work. So we'll need to figure out why it's not working as desired.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=473917#comment-473917):_

As the code stands today, this is a bug: The association is correct and technically the pipeline should operate.

However, as discussed, this capability of handling multiple products has not been completely flushed out. There has been a long standing github issue to address this which has now been linked to JP-1580.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=500285#comment-500285):_

Attempted to reproduce this error today using jwst master, version 0.17.2.dev77+g6ce0ea65. Using the command below, all ran to completion. Going to remark this issue as ready-to-test, for confirmation.

`strun calwebb_spec2.cfg l2_asn.json`

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=500692#comment-500692):_

Just tried this again with the latest master (0d75fff6) on a similar l2 asn file and got the same error as before with newly-created files at <https://stsci.app.box.com/folder/128067233158>

Using strun calwebb_spec2.cfg l2_asn.json

I get a lengthy series of messages ending in

Traceback (most recent call last):
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 110, in process
 result = self.process_exposure_product(
 File "/Users/drlaw/jwcode/jwst/jwst/pipeline/calwebb_spec2.py", line 267, in process_exposure_product
 resampled = self.cube_build(calibrated)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 365, in run
 f'Step \{self.name} parameters are: \{self.get_pars()}'
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/step.py", line 1235, in get_pars
 pars = config_parser.config_from_dict(instance_pars, spec, allow_missing=True)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/config_parser.py", line 301, in config_from_dict
 validate(config, spec, root_dir=root_dir, allow_missing=allow_missing)
 File "/Users/drlaw/jwcode/jwst/jwst/stpipe/config_parser.py", line 390, in validate
 raise ValidationError('\n'.join(messages))
jwst.stpipe.config_parser.ValidationError: Config parameter 'channel': the value "" is unacceptable.
Config parameter 'filter': the value "" is unacceptable.
Config parameter 'grating': the value "" is unacceptable.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=501018#comment-501018):_

Just a note for reference that NIRSpec has also encountered the same error using version 0.17.1.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=503443#comment-503443):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) Once you did the hard work and  found out where the problem was coming from I think I now have a fix. 
I  pushed over the changes in PR #&#x2060;5603 so you can either review the PR or pull in the changes I have made
to your version code. I have tested this with the MIRI data David Law provided and I going to round up some data to test it with NIRSPEC data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=503932#comment-503932):_

Fixed by #5603

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=503933#comment-503933):_

Assigning back to you [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) for testing, when you have the chance.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-1560?focusedCommentId=503983#comment-503983):_

Looks good, thanks!  My spec2 test case now runs as expected, so I think this ticket can be closed.
