### ISSUE TITLE
magnitude cut in extract2d for WFSS data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5126]
_Issue [JP-1566](https://jira.stsci.edu/browse/JP-1566) was created on JIRA by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita):_

This is not a bug report but suggestion for possible convenience:

Extract2dStep has an argument for magnitude cut, "mmag_extract", but this is currently only for NRC_TSGRISM. 
<https://github.com/spacetelescope/jwst/blob/f6863653995ed46a09fc8da7348a4de48cd09c2c/jwst/extract_2d/extract_2d.py#L67-L78>

We, NIRISS WFSS working group, think this option would be very helpful for users who wish to extract only bright objects, rather than everything in the field. The magnitude cut can be applied universally to the sources.

**Comment by nden** [comment]
It's actually only for WFSS mode but it's not propagated. The propagation problem is fixed in #5122.

https://github.com/spacetelescope/jwst/pull/5122/files#diff-274d7bf150c395adb6f9f305dee0f6b1R78

Is this going to work for you?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-1566?focusedCommentId=472399#comment-472399):_

Yes, this fix is exactly I was expecting! We could close this ticket then. Thank you!

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1566?focusedCommentId=490777#comment-490777):_

Fixed by #5122
