### ISSUE TITLE
NIRSpec IFU flat fielding step Nan out overlapping slice bounding box

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5147]
_Issue [JP-1584](https://jira.stsci.edu/browse/JP-1584) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

The SCI data of the slices after flat fielding appear to have missing regions. These missing regions (set to nans) appears very similar to the error report in JP-932. The data are processed slice by slice. The overlapping bounding box of a slice seems to over-write the data. The code in the flat field step: flat_field.nirspecIfu.py should (probably) be updated to
handle overlapping bounding boxes.
[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) could you confirm this is a bug

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1584?focusedCommentId=474490#comment-474490):_

 !Screen Shot 2020-07-16 at 11.43.10 AM.png|thumbnail! 
Image of issue

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1584?focusedCommentId=474501#comment-474501):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Yes, this looks like exactly the same problem with overlapping bounding boxes as found in JP-932.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1584?focusedCommentId=475112#comment-475112):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)[Beth Sargent](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sargent)
Do either of you have some data I could test how the flat fielding is working on NIRSPEC. Maybe a few different filters/grating setting. I now am not sure there is any problem with the flat field step - but the quality of the data. The data (above) that I found this problem in - I did not have a rate file - I was using an assign_wcs file. The assign_wcs file has data that looks like the bounding boxes overlap and it should not.
I am not sure I got the input from.If a file has an 'assign_wcs' attached to the name it really should just be a rate file with asdf wcs attached - we should not see this overlapping bounding box issue (I think).

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1584?focusedCommentId=475335#comment-475335):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I noticed the file you were using is from an OTB test run; I downloaded from MAST the rate file that was automatically generated by the pipeline when those data were initially processed.  See ██████████████████████████████████████████  I ran that through calspec2 using the latest dev version, those products are also in the directory.  There is no missing data in the resulting cal file.  I'd venture to guess that the problem you were seeing was somehow related to the fact that you were starting with the assign_wcs intermediate product?

**Comment by jemorrison** [comment]
Thanks for following up on this issue. I will close this ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1584?focusedCommentId=475538#comment-475538):_

With correct data it was determined this was not an issue.
