### ISSUE TITLE
Datamodels should be able to read and write ASDF files

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#5153]
Data models have an attribute `DataModel.meta.model_type` which is used to initialize the correct data model from a FITS file. This is written to the FITS keyword `DATAMODEL`. 
 `DataModel.meta.model_type` is also written to an ASDF file but is not taken into acocunt when reading an ASDF file with `datamodels.open`  which does not initialize the correct data model and instead creates an instance of the base `DataModel` class.

Adding this keyword to `datamodels.open` when an asdf file is read will allow using the `open` function with reference files without having to specify the exact model the reference file represents. 

It will also help with using datamodels for the Roman pipeline.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1734](https://jira.stsci.edu/browse/JP-1734)._

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1734?focusedCommentId=492865#comment-492865):_

PR is here

#5442
