### ISSUE TITLE
Documentation update: Reference file selection criteria for dark reffiles

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwst#5266]
Currently the table listing the dark current reference file selection criteria lists instrument, detector, subarray, date, and time as the keywords used to select reference files.
https://jwst-pipeline.readthedocs.io/en/stable/jwst/dark_current/reference_files.html#reference-selection-keywords-for-dark

However, when delivering reference files today, I was told that EXP_TYPE is also included in the selection criteria. This is for NIRCam, but I'm assuming it's true for the other instruments as well.

**Comment by hbushouse** [comment]
Looking at the NIRCam dark ramp at https://jwst-crds.stsci.edu/ it appears that EXP_TYPE is in fact used as a selector, but that's the only instrument that does so. Meanwhile, some other instruments also use READPATT, so we clearly need to update the dark docs for these differences.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1650](https://jira.stsci.edu/browse/JP-1650)._

**Comment by hbushouse** [comment]
Problem has been fixed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1650?focusedCommentId=579091#comment-579091):_

As of today the list of selectors in <https://jwst-pipeline.readthedocs.io/en/latest/jwst/dark_current/reference_files.html#dark-reffile> matches the rmaps for all instruments. So I'm closing this ticket. Not sure when/where it got fixed.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1650](https://jira.stsci.edu/browse/JP-1650)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1650?focusedCommentId=579091#comment-579091):_

As of today the list of selectors in <https://jwst-pipeline.readthedocs.io/en/latest/jwst/dark_current/reference_files.html#dark-reffile> matches the rmaps for all instruments. So I'm closing this ticket. Not sure when/where it got fixed.
