### ISSUE TITLE
tests should pass on installed package

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5289]
_Issue [JP-1661](https://jira.stsci.edu/browse/JP-1661) was created on JIRA by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

Currently a number of of the subpackages in `jwst` fail when the tests are run on the installed version of the package via

`$ pytest --pyargs jwst`

This should be fixed.

Further, tests that require data that is not packaged with the installable `sdist` or `bdist_wheel` should be marked as such.

Eventually, we will want to not package as much (or any) test data with the installable python package, to keep the installed size small.  Currently it is 30-40MB, which is very large.

**Comment by jdavies-st** [comment]
Closed by #5319
