### ISSUE TITLE
NIRSPEC: flat field calspec2 failing validation for MOS data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5293]
_Issue [JP-1663](https://jira.stsci.edu/browse/JP-1663) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

JP-1071 fixed the NIRSPEC ALLSlits and BOTS flat fielding bug.

This ticket deals with NIRSPEC MOS  issues that were not fixed in JP-1071.

The remaining issues deals with how the pipeline uses the DQ flags of the s-flat, d-flat, and f-flat for the mos flat fielding step.   

The JWST pipeline only looks at reference file DQ flags set with DO_NOT_USE  as to whether the reference data should be used. It is unclear if the NIRSPEC s-flat reference files are set correctly. There are DQ data for the science fields but the DO_NOT_USE is not set.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=481923#comment-481923):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena)

(copied from JP-1071 - closed that ticket because ALL SLITS and BOTS fixed) 

A remaining question on how to the dq flags of the s-flat, d-flat and f-flat to find the interpolated flat for NIRSPEC MOS data. : I have given an example to explain. The example is the interpolated flat  for the first slit  MOS data: mos_G140M_LINE1_NRS2_extract_2d.fits.  The interpolated s-flat on the right edge of the slit uses data from the s-slit that have values of Nan. The jwst pipeline sets this s-flat interpolated data to 1 and sets the DQ flag to DO_NOT_USE. When the dq flags from the s-flat, d_flat and f_flat are combined this region is given a value of 1 in the final interpolated flat. The NIRSPEC flat_calc image contains non 1 data in this region. If I comment out the line that combines the dq flags from the s flat, d flat and f flat then the results are similar to this region. The reason is the combined dq flags are used to mark data that have DO_NOT_USE set and where this occurs the interpolated flat = 1.
The line in question is 809 in flat_field.py. Does the NIRSpec team want to set the final interpolated flat to 1 if any of the components of the D, F or S flat are set to 1 because the input flat data was a Nan ?

 

!image-2020-08-27-13-37-12-856.png!

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=481946#comment-481946):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I'm tempted to say no, since the three flat components are independent of one another.  However, if we do that, there should be some indication that some of the components had to be set to 1; for example, perhaps we could set the UNRELIABLE_FLAT flag in the final interpolated flat?

**Comment by jemorrison** [comment]
@jmuzerolle 
Marking those pixel with UNRELIABLE_FLAT sounds like a good idea. I think they should be marked some way because  in the example I have the portion of the slit (on the right) of the interpolate flat is made up of only the d-flat and f-flat data. 
In so that flat changes from values around 2.5 when all the flats are used to a  values ~ 0.8 when the s-flat is not valid and
only the d-flat (and f-flat) are used. 

[compare_pipelines.pdf](https://github.com/spacetelescope/jwst/files/5152723/compare_pipelines.pdf)

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482121#comment-482121):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)

Currently if any flat has 0 or Nan data when it is read in then that data is changed to 1 and the DQ FLAG is set to DO_NOT_USE.

When the s-flat, d-flat and f-flat are combined together I am going to set the DO_NOT_USE flag for the interpolated flat only for pixels that have DO_NOT_USE set on all THREE flats. If there is at least one flat with valid data (either one or two of the other  flats have the DO_NOT_USE flag set)  then the interpolated flat will be made from the good data and the DQ flags will be set to UNRELIABLE_FLAT . 

I think this is what you want.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482125#comment-482125):_

The jwst and NIRSpec interpolated flat is much closer now, but there are still differences.  See example of the interpolate flat for 1 NIRSPEC slit below.

[Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena)  [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) Are the differences large enough that we should continue to investigate how the interpolated flat is being created in the JWST pipeline. 

 

!image-2020-08-31-16-05-16-014.png!

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482126#comment-482126):_

PR-5284 addresses this ticket

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482277#comment-482277):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) These differences are still too large, particularly the "sidelobes" at +/- 0.1.  Are you able to see the difference image?  The spatial structure might help in nailing down the origin of the problem.  At least part of the problem may be due to inconsistency with how the DQ flags are being treated, [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) we'll have to check that on our end.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482280#comment-482280):_

And affirmative on the proposed rules for setting the UNRELIABLE_FLAT flag.  We may need to revisit after I get feedback from the team (our flat expert has been out), but I think this is a reasonable solution for now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482294#comment-482294):_

I have a image of the difference in the interpolated flat between the NIRSPEC and JWST pipeline. It is a bit difficult to show since it is so long but the height is small. I have clipped a region of the difference image. To me the pattern looks like it is related to the DQ flags. Before I made the changes in this PR the JWST interpolated flat sort of followed the bright portion of this image. [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) can you update the NIRSPEC pipeline to use the DQ flags the same as the JWST pipeline - which is - only set the interpolated flat to 1 if the dq flag of S-flat, d-flat and f-flat are all DO_NOT_USE. You will also need to set the DQ flags of the reference files to DO_NOT_USE. Currently the code sets the DQ flag to DO_NOT_USE when the flat value = NAN or 0. 

Here is the difference image for a portion of the interpolated flat:

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482343#comment-482343):_

Looks like the best agreement is at the center, which as you say are mostly the pixels that are not flagged in the S-flat.  The pixels closer to the edges have mostly negative differences; I'm not sure what would cause that.  I don't see many cases of positive differences (>0.05), though the histogram indicates there should be hundreds of them - are those in the part of the trace that you're not showing?

We will have to re-deliver the reference files with the DO_NOT_USE flags set appropriately.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482381#comment-482381):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) Good question. I made another plot to show the difference image (difference between interpolated flat for jwst and nirspec pipeline)
The top plot is for the short wavelength end and bottom plot is for the long wavelength end.

I am guess this points to a problem with how the s flat is interpolated.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482477#comment-482477):_

Interesting, there seems to be sort of a gradient from positive to negative differences as a function of wavelength in the outer flagged pixels.  I wonder if there's an indexing issue in either version of the algorithm?  On the other hand, the central unflagged pixels look ok (a bit hard to tell with the color scheme).

**Comment by jemorrison** [comment]
I was thinking we could force the d-flat to be 1 (the f-flat is already 1) and see what the interpolated flat looks only using the s-flat.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482554#comment-482554):_

I changed the color map for the image to make it a little obvious. The top plot is the short wavelength end and the bottom plot the long wavelength end. The red regions is where there is no valid data (this data is flagged as 999 in the Nirspec pipeline.  Green the center region in both plots  is ~0

!image-2020-09-02-14-41-01-093.png|width=687,height=231!

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482560#comment-482560):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Maria is working on our test code to make sure it has a consistent treatment of the DQ flags.  Results coming soon...

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482705#comment-482705):_

Hi [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison), I am using jwst pipeline version: 0.17.1.dev4+g944cd605, and I made all the changes you requested to the NIRSpec code, you can find the new version at:

<https://github.com/spacetelescope/nirspec_pipe_testing_tool/blob/master/nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py>

I placed the new files at:

████████████████████████████████████████████████████████████████████████

Same convention:
 * _flat_field.fits -> output from the pipeline flat field step
 * _interpolated.fits -> calculated flat from pipeline
 * _calc.fits -> calculated flat from NIRSpec flat field step implementation
 * _comp.fits -> comparison of the 2 files
 * .png -> output plots from the NIRSpec code

The differences we are getting are still too large, something else is not quite the same in both calculations of the flat so we need to keep investigating. I added a sample histogram of our new results to this ticket, its called: g140m_line1_NRS1_flat_field_MOS_flattest_82_124_histogram.png

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=482737#comment-482737):_

[Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) Ok I have not merged my changes into master yet. So I will take your result and compare the results of the pipeline with my local branch where I made the changes.  I will get back to you soon.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=483440#comment-483440):_

[Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) I have been working with the NRS2 data because I have extract_2d.fit for NRS2 but not NRS1.
I have tried to run calspec2 on the NRS1 rate file I have but I do not have the MSA file.

So could you point me to the NRS1 extract_2d.fits file that is the input to the field_field step for NRS 1  ?

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=483590#comment-483590):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison), I placed the extract_2d file at  ████████████████████████████████████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=483621#comment-483621):_

[Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)

 Using the new results from the NIRSpec pipeline the Maria made I think the differences are less but still not in the range that you want them.

I have focused on the first slit since it is nice and long: 506 X 14.  The difference image between the two pipelines given below. The center of slit is close to zero (green). So any suggestions on what to do next ?  Should we try to focus on the s-flat which I think is likely the cause of the differences. Maybe set the D- flat and F-flat to 1 (I think the f-flat is already 1) ?

!image-2020-09-10-15-58-32-999.png|width=774,height=252!

Ignore the red region this data is flagged as 999 in the NIRSPEC data (not flat exists)



The histogram of the flats follows with the last histogram for the difference image. I assume the data in the last histogram with differences >  0.02 is where we should concentrate. Maria I have put the interpolated flat for this version of the pipeline at:

████████████████████████████████████████

 

  !image-2020-09-10-16-02-58-332.png|width=565,height=565!

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=483776#comment-483776):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I think you're right, it looks like the biggest differences are for the pixels that are flagged in the S-flat (the values >~0.02).  So, there is still a discrepancy between the two implementations in how those pixels are being treated.  We may have to compare codes to see exactly how this is happening.

[Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) is out next week, so this may have to be tabled until after that.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=483914#comment-483914):_

Part of a git to this issue was in  PR5284. More work is required to find the differences between the NIRSPEC and JWST pipelines. It is likely a difference in s-flat interpolation

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=486583#comment-486583):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison), I made the changes in NPTT to force the d- and f-flats to 1.0 so we can investigate the s-flat. I placed the results for NRS1 at ██████████████████████████████████████████████████████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1663?focusedCommentId=486596#comment-486596):_

Wonderful I was going to get back to this issue today. Good timing. I will go grab the data now.
