### ISSUE TITLE
NIRSpec: Upload testing data to Artifactory

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5322]
_Issue [JP-1682](https://jira.stsci.edu/browse/JP-1682) was created on JIRA by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena):_

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1682?focusedCommentId=483903#comment-483903):_

Great, thanks, [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena)! I'll work on this. Can you tell me which steps/pipelines the data are for? It's fine if they go with multiple steps, just want to make sure to store them in the correct spot.

**Comment by hbushouse** [comment]
INS work is done and JP ticket closed.
