### ISSUE TITLE
LEVEL_3 fails during cube build: ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5327]
_Issue [JP-1690](https://jira.stsci.edu/browse/JP-1690) was created on JIRA by [Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam):_

3 cases of datasets failing in DMS b7.6 complete_long testing with this error:

2020-09-09 17:46:24,072 - stpipe.Spec3Pipeline.cube_build - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
 return _methods._mean(a, axis=axis, dtype=dtype,

2020-09-09 17:46:24,073 - stpipe.Spec3Pipeline.cube_build - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
 ret = ret.dtype.type(ret / rcount)

Traceback (most recent call last):

<snip>

File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
 return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

 

Full log on Dstring2 machine tljwdmscsched2 is here: /ifs/archive/test/jwst/test2/info/owl/logs/rspencer_jw00825-c1001_20200909t054751_spec3_001_1599646390.098572/ALOG_1599646516_level_3_jw00825-c1001_20200909t054751_spec3_001.out

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=483495#comment-483495):_

This is crashing in the "cube_build" step, after successfully running both "mrs_imatch" and "outlier_detection". All data files needed as input to calwebb_spec3 have been copied to ███████████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=483932#comment-483932):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) I get error trying to access this data

 cd ██████████████████████████████████████████████

-bash: cd: ███████████████████████████████████████████████ No such file or directory

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=483935#comment-483935):_

I can see and ls in that directory:
```java
cd █████████████████████████████████████████████
(jwstdev) new-host-8:jwstdms-408 bushouse$ ls
jw00825-c1001_20200909t054751_spec3_001_asn.json	jw00825008001_02101_00001_mirifulong_cal.fits
jw00825006001_02101_00001_mirifulong_cal.fits		jw00825008001_02101_00001_mirifushort_cal.fits
jw00825006001_02101_00001_mirifushort_cal.fits		jw00825008001_02101_00002_mirifulong_cal.fits
jw00825006001_02101_00002_mirifulong_cal.fits		jw00825008001_02101_00002_mirifushort_cal.fits
jw00825006001_02101_00002_mirifushort_cal.fits		jw00825008001_02101_00003_mirifulong_cal.fits
jw00825006001_02101_00003_mirifulong_cal.fits		jw00825008001_02101_00003_mirifushort_cal.fits
jw00825006001_02101_00003_mirifushort_cal.fits		jw00825008001_02101_00004_mirifulong_cal.fits
jw00825006001_02101_00004_mirifulong_cal.fits		jw00825008001_02101_00004_mirifushort_cal.fits
jw00825006001_02101_00004_mirifushort_cal.fits		jw00825009001_02101_00001_mirifulong_cal.fits
jw00825007001_02101_00001_mirifulong_cal.fits		jw00825009001_02101_00001_mirifushort_cal.fits
jw00825007001_02101_00001_mirifushort_cal.fits		jw00825009001_02101_00002_mirifulong_cal.fits
jw00825007001_02101_00002_mirifulong_cal.fits		jw00825009001_02101_00002_mirifushort_cal.fits
jw00825007001_02101_00002_mirifushort_cal.fits		jw00825009001_02101_00003_mirifulong_cal.fits
jw00825007001_02101_00003_mirifulong_cal.fits		jw00825009001_02101_00003_mirifushort_cal.fits
jw00825007001_02101_00003_mirifushort_cal.fits		jw00825009001_02101_00004_mirifulong_cal.fits
jw00825007001_02101_00004_mirifulong_cal.fits		jw00825009001_02101_00004_mirifushort_cal.fits
jw00825007001_02101_00004_mirifushort_cal.fits```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=483937#comment-483937):_

Maybe a permission problem? Try again.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=484245#comment-484245):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies)

I am look this ticket that involved running calspec3 over a set of MIRI data that contains data from MIRIFULONG (channel 3 and 4) MIRIFUSHORT(channel 1 and 2) and data in sub channel short and medium (for both LONG and SHORT data).

mrs_imatch and outlier detection both call cube_build in SINGLE MODE.  The initial cube_build call is not building these initial cubes in a single band (so only  sub channel short or sub channel medium) but combining the sub-channel data together.  Maybe it does not matter but I wanted to check what it should be doing. In the case of mrs_imatch the cube_build band is set to 'ALL', but channel is set to only 1 value.. In outlier detection the documentation it says the cubes are built per BAND. I think it would probably be cleaner if they built per BAND but maybe it does not matter. I wondered if there is a preference 

I ran outlier detection and saved the results. Looking at the *crf files. Every pixel is different from the cal file. Can someone remind me what the crf files are. I can not find it in the outlier detection step documentation. Did I miss it ?   This data must be some sort of faked data because it is strange and all the slices are hugely negative.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=484251#comment-484251):_

The contents of the crf files should be identical to the cal files except for the DQ arrays. The crf should be a copy of the cal, with only the DQ values updated wherever a CR was detected. Oh, but mrs_imatch is also being run before outlier_detection, so it's mrs_imatch that's changing all the science pixel values. Save the output of mrs_imatch and then those results should be identical to the crf files, other than DQ values added by outlier_detection.

**Comment by jemorrison** [comment]
I believe that the mrs_imatch polynomial is only applied in cube_build. It is not applied to the cal files. I will double check this

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485029#comment-485029):_

[James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)

Ok I believe I have tracked how why this set of data is failing in cube build. I ran the calspec3 pipeline and printed out the results after outlier detection. I then compared the CAL DQ and CRF DQ planes. For some reason in the CRF files  of at least one of the files has a DQ value of 23 for all the science pixels. So there is NO valid data on the detector. I don't have a check in cube_build that all the data is flagged as bad - I could do that - but first I do not understand a DQ flag values of 23. That is DO_NOT_USE (1) + SATURATED (2) + PERSISTENCE (2****5). The OUTLIER flag is 2****4. 

I looked at other DQ planes in the crf files and sometimes more than 1/2 that data has a value of 23. 

I think I must be mis-understanding a DQ flag of 23 - does my logic seem correct ?

I don't think the persistence step is run on MIRI data and it should be flagged in the CAL files which it is not.  

Ideas ?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485032#comment-485032):_

When building "SINGLE" type cubes that are used in mrs_imatach and outlier_detector that background determined from
mrs_imatch is not subtracted. Is that the correct thing to do for outlier_detector ? Or should the background be subtracted from the data that will go into making the median cubes which is then blotting back to the detector for outlier detection

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485033#comment-485033):_


```python
In [1]: import numpy as np

In [4]: np.binary_repr(23, width=32)
Out[4]: '00000000000000000000000000010111'

In [5]: from jwst import datamodels

In [6]: for mnemonic, bit in datamodels.dqflags.pixel.items():
   ...:     if np.bitwise_and(23, bit):
   ...:         print(mnemonic)
   ...: 
DO_NOT_USE
SATURATED
JUMP_DET
OUTLIER
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485036#comment-485036):_

Ditto. 23 = 1 + 2 + 4 + 16 = DO_NOT_USE + SATURATED + JUMP_DET + OUTLIER, where JUMP_DET is set by the detector1 jump step and OUTLIER is set by outlier_detection. So these look legit. This indicates that outlier_detection is flagging almost everything sight as an outlier, probably due to crappy/bogus data (e.g. OTB simulator).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485045#comment-485045):_

[James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) might have a better handle on the background subtraction question, but I believe the correct behavior is to only store the background values determined by mrs_imatch so that outlier_detection can take it into account when making its noise models and doing comparisons, but I don't think it should be subtracted from the median cubes. You want the signal in the median cubes to match the individual images when it gets blotted back to the space of each individual image, and because the bkg is still in the original images you need it in the blotted results too. I think the background doesn't actually get subtracted from the science data until cube_build makes the final science cubes (after outlier_detection).

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485057#comment-485057):_

Thanks guys I seem to have problems with bitwise combinations. 2**5 is 32 (persistence flag)  - duh. 

This data is really strange looking. Most of the data is very negative. So should I just put a check in cube_build that looks to see if all the data has DQ value that included DO_NOT_USE and then to skip that data. I can print a warning to the screen that indicates this. I do worry that this could might cause us to miss a real problem later on in outlier detection.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485118#comment-485118):_

Hi Jane-

This data looks completely bogus, so as Howard remarked this is surely just test pattern data injected by the OTB to have **some** kind of values in the file.  Of course, as you say that does question the utility of OTB data for testing the pipeline by the time it gets to the SPEC3 stage.

Until the OTB uses something more realistic I don't think there's much to be done about it, and it would be helpful for spec3 to exit cleanly with some kind of warning message such as 'Is this an OTB test pattern?'  It doesn't really make any sense to run through mrs_imatch or outlier_detection either in this case, although it's comforting (maybe?) that it doesn't cause those to crash.

As far as testing outlier detection properly goes, so far I've been doing that based on more realistic mirisim data.

I'd have to test the behaviour with regard to mrs_imatch and outlier detection; while I've testing both of these individually (it requires hacking the simulated data to make real outliers or background variations) I don't think I've ever tried **both** background offsets and outliers at the same time.  I'll have to add that to my list and get back to you.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1690?focusedCommentId=485134#comment-485134):_

GitHub PR 5347 has been made to clean up various aspects of cube_build in the calspec 3 pipeline. 

The data for this JP ticket is not realistic data to use in calspec3. The exact same data is found on all the channel/bands, but it is dithered around the sky. The data itself on a single file is not realistic at all (large negatives values are found throughout the cal files - for science pixels.) When these data sets are dithered around the sky the result from outlier detection is many pixels are flagged as OUTLIERS + DO_NOT_USE. On a few files all the science data is flagged as DO_NOT_USE - resulting the error reported in this ticket. A check is done in cube_build to see if after selecting the science data after checking the DQ flag  if there is any valid data. If there is not - the file is skipping in cube_building and a WARNING message is printed to the log file.
