### ISSUE TITLE
NIRSpec pathloss MOS point source discrepancy with NPTT testing

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5335]
_Issue [JP-1698](https://jira.stsci.edu/browse/JP-1698) was created on JIRA by [Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking):_

The MSA point source pathloss testing comparing the pipeline output with the NPTT output has absolute correction residuals ranging from about 0.003 to 0.006. This is four orders of magnitude greater than the difference which we hope to see. 

While there is about 10^-5^% error on the correction values for all FS modes, all IFU modes, and MOS extended source pathloss corrections, this is about 5% error on the MOS point source pathloss correction. The MOS PS correction varies more rapidly than the other modes and thus interpolating in a different manner could have a larger effect; still, it is unexpected to have such large residuals.

Numerous files showed this large percent error on the correction values. Although they differed with position (and the correction at (0,0) was 1, as expected), the residuals did not seem to have a clearly structured dependence on position.

Furthermore, both grism and prism data have been tested. The science file wavelength from the WCS object only differed from the extract_2d wavelength on the order of 10^-13, so this reduces the likelihood that there’s an issue with using the wrong wavelength or this being shifted due to any wavelength zero point correction. 

Various interpolation methods have been implemented (both from scipy and numpy, as well as linear, cubic, and nearest methods, etc), all of which retain correction residuals roughly around 0.003-0.006. Because griddata uses three array values that surround the point rather than the four array values that are used in the bilinear interpolator, a bilinear interpolation method was also tested, and, like the other variances in the interpolation, it was found that the correction values varied by about a percent.

More details on these tests as well as the corresponding NIRSpec FS and IFU pathloss tests for point sources and uniform sources can be found in the attached document. [^Pathloss_Documentation.pages]

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=534229#comment-534229):_

[Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) can you provide a pointer to example data files that you used for the analysis, for use in our debugging?

**Comment by stscijgbot-jp** [comment]
_Comment by [Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=534339#comment-534339):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) you can find example data files in the following directory: /user/tking/MSA_PS_pathloss

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=545624#comment-545624):_

`[Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) It looks like in the nirspec_pipe_testinng_tool file [auxiliary_code/pathloss_mos.py](https://github.com/spacetelescope/nirspec_pipe_testing_tool/blob/master/nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos.py) line 299:`

`pipe_correction = pipe_slit.pathloss_uniform`

This is the pipeline-generated correction that your custom calculated correction is comparing with, so will give poor results when comparing with corrections calculated for point sources.  You should probably move this line down into the if is_point_source section and select the appropriate extension for point_source and uniform types.

**Comment by stscijgbot-jp** [comment]
_Comment by [Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=562402#comment-562402):_

Hi [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij), It looks like with a combination of the above adjustments and accounting for the coordinate change as mentioned in [this ticket](https://jira.stsci.edu/browse/JP-1151), [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) found that our tests are now showing that there is *not* a significant discrepancy between the MOS point source calculations from the pipeline and the NIRSpec Pipe Testing Tool. Hence, this ticket can be closed.

**Comment by stscirij** [comment]
@tnking97 glad to hear!

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=534229#comment-534229):_

[Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) can you provide a pointer to example data files that you used for the analysis, for use in our debugging?

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=545624#comment-545624):_

`[Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) It looks like in the nirspec_pipe_testinng_tool file [auxiliary_code/pathloss_mos.py](https://github.com/spacetelescope/nirspec_pipe_testing_tool/blob/master/nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos.py) line 299:`

`pipe_correction = pipe_slit.pathloss_uniform`

This is the pipeline-generated correction that your custom calculated correction is comparing with, so will give poor results when comparing with corrections calculated for point sources.  You should probably move this line down into the if is_point_source section and select the appropriate extension for point_source and uniform types.

**Comment by stscijgbot-jp** [comment]
_Comment by [Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=552680#comment-552680):_

Hi [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij), Thank you for catching this. A [PR](https://github.com/spacetelescope/nirspec_pipe_testing_tool/pull/217) has been merged to make that fix. This particular line was actually introduced in a very recent update to the code and, while it needed to be fixed, this issue was not the underlying reason why there was this discrepancy in the pathloss correction, and the error in the correction remains the same as originally described in this issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=553543#comment-553543):_

Hi again [Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) - this looks like another case where the wrong wavelength array was used to calculate the correction, similar to [JP-2225|[http://https://jira.stsci.edu/browse/JP-2225].](http://https//jira.stsci.edu/browse/JP-2225).]  The wavelength array, which includes offsets from the wavelength calibration step, is included with each science array in the WAVELENGTH extension, and this differs from the wavelengths calculated using the WCS, which do not include the wavelength corrections from the wavecorr step.  This is only a factor for point source exposures.  Try replacing line 287 in auxiliary_code/pathloss_mos.py with

`wave = slit.wavelength`

and see if that helps.

**Comment by stscijgbot-jp** [comment]
_Comment by [Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=554882#comment-554882):_

Hi [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij), Thank you for the suggestion. This adjustment to the code has been tested and does not seem to have any noticeable impact on the residuals comparing the pipeline-calculated correction value and the correction value that the nirspec-pipe-testing-tool calculates.

**Comment by stscijgbot-jp** [comment]
_Comment by [Teagan King](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tking) on [JIRA](https://jira.stsci.edu/browse/JP-1698?focusedCommentId=562402#comment-562402):_

Hi [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij), It looks like with a combination of the above adjustments and accounting for the coordinate change as mentioned in [this ticket](https://jira.stsci.edu/browse/JP-1151), [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) found that our tests are now showing that there is *not* a significant discrepancy between the MOS point source calculations from the pipeline and the NIRSpec Pipe Testing Tool. Hence, this ticket can be closed.
