### ISSUE TITLE
No level-2b processing for NRS lamp exposures with NOLAMP or OPMODE='NONE'

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5337]
_Issue [JP-1699](https://jira.stsci.edu/browse/JP-1699) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

Now that basic level-2b processing of NIRSpec internal lamp exposures has been implemented (JP-1429) there are many trouble cases in existing test suites due to lamp exposures with LAMP='NOLAMP' and/or OPMODE='NONE'. These meta values cause errors in either the CRDS prefetch or the actual calwebb_nrslamp-spec2 processing. Discussion captured in JP-473 and  JP-1429 indicates consensus that these exposures should just stop at the end of level-2a (calwebb_detector1) processing and not even attempt level-2b processing. Implementation of this behavior will require update to ASN generator rules to exclude such exposures from any spec2 ASN's and hence not trigger level-2b processing for them.

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=484693#comment-484693):_

There is another case that we should probably treat the same way: one of the allowed values for the OPMODE keyword is 'GRATING-ONLY'.  According to the discussion in <https://jira.stsci.edu/browse/JP-473,> these data should also not invoke the calspec2 pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=487203#comment-487203):_

In addition to the OPMODE='NONE' and LAMP='NOLAMP' variety of NIRSpec lamp exposures, JWSTDMS-409 also discusses the case of EXP_TYPE='NRS_LAMP' and GRATING='MIRROR'. They are undispersed images (used to determine stuck open/closed shutters, etc.) and should be treated as image mode, rather than spectroscopic. As such, they could theoretically be processed at level-2b with calwebb_image2, but the NIRSpec team has requested that such exposures simply stop at the end of level-2a processing.

So another ASN rule update is needed to exclude exposures with EXP_TYPE='NRS_LAMP' and GRATING='MIRROR' from any spec2/image2 ASN.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=496892#comment-496892):_

To summarize, the cases where there should be NO Level2b, and, subsequently, no Level3 processing, are as follows, all involving NIRSpec. Consider each bullet an OR case:
 * LAMP == NOLAMP
 * OPMODE == NONE
 * EXP_TYPE == "NRS_LAMP" and OPMODE == GRATING-ONLY
 * EXP_TYPE == "NRS_LAMP" and GRATING == "MIRROR"

It is true that LAMP and OPMODE are relevant only when EXP_TYPE == "NRS_LAMP". Or can there be other exposure types involved?

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=496899#comment-496899):_

Yes, LAMP and OPMODE are relevant for exposure types NRS_AUTOFLAT and NRS_AUTOWAVE.  So the full bullet list should be:
 * LAMP == NOLAMP
 * OPMODE == NONE
 * EXP_TYPE == "NRS_LAMP" and OPMODE == GRATING-ONLY
 * EXP_TYPE == "NRS_LAMP" and GRATING == "MIRROR"
 * EXP_TYPE == "NRS_AUTOWAVE" and OPMODE == "GRATING-ONLY"
 * EXP_TYPE == "NRS_AUTOWAVE" and GRATING == "MIRROR"
 * EXP_TYPE == "NRS_AUTOFLAT" and OPMODE == "GRATING-ONLY"
 * EXP_TYPE == "NRS_AUTOFLAT" and GRATING == "MIRROR"

I think the AUTOWAVE+MIRROR and AUTOFLAT+MIRROR should never happen though, and the AUTOFLAT/AUTOWAVE + GRATING should be unlikely, but perhaps [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) could confirm?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=496905#comment-496905):_

I don't think we can just blindly say that any exposure with LAMP='NOLAMP' or OPMODE='NONE' does not get level-2b (or beyond) processing. Certainly all science exposures will have those values and they obviously need calibration. So it's only those LAMP and OPMODE values in conjunction with EXP_TYPEs NRS_LAMP, NRS_AUTOWAVE, and NRS_AUTOFLAT.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=496973#comment-496973):_

[Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) Correct, MIRROR cannot be used with AUTOFLAT or AUTOWAVE.  By " AUTOFLAT/AUTOWAVE + GRATING", I assume you mean "GRATING-ONLY"?  That combination also will never occur in science observations, it's only used for engineering-level checkouts and will not need to be processed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=497508#comment-497508):_

Further clarification: Currently the association rules also require that FILTER == OPAQUE. Please confirmat that this is true for any of [NRS_LAMP, NRS_AUTOWAVE, NRS_AUTOFLAT] that one does want to process through Level 2b.

**Comment by stscirij** [comment]
I believe this is true, but again @jmuzerolle is the expert here

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=497526#comment-497526):_

Confirmed!

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=497578#comment-497578):_

Clarification: Above says not to process if LAMP == NOLAMP. Keyword dictionary does not have NOLAMP as a value. Is this an actual value or just a way of saying it must be defined as one of the other valid values?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=497894#comment-497894):_

In some of the random NIRSpec exposures I've got laying around locally I'm seeing cases where LAMP='NO_LAMP'. We should confirm whether the value SDP is getting from the OSF's to populate the LAMP keyword has the form "NOLAMP" (no underscore) or "NO_LAMP" (with underscore), so that the rules can be written appropriately.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=497952#comment-497952):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) Any info on whether the value of NOLAMP, or is it NO_LAMP, actually is valid? And what exactly does it mean?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=498457#comment-498457):_

I'm not sure why there are two different versions of NO_LAMP.  There are two ways of specifying LAMP=NONE within the lamp template, one using the "GRATING_ONLY" op mode (where NONE is the only option, used only to move the grating wheel), the other as a selectable option in any of the other op modes (usually referred to as "exposure-only", e.g. used in the GSEG test observations).  Perhaps the two names are associated with these two pathways?

That being said, in the "GRATING_ONLY" case, no exposure is taken, so there shouldn't be any data to process.  The other cases do have normal exposures (basically equivalent to darks), and should only be processed to level 2a.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=498962#comment-498962):_

For some sanity, when through all the products produced by testing for B7.6, and the only form of the "no lamp" value is "NOLAMP".

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1699?focusedCommentId=499337#comment-499337):_

Resolved by [PR #&#x2060;5496](https://github.com/spacetelescope/jwst/pull/5496)
