### ISSUE TITLE
Detector1 TSO test notebook crashes

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5358]
_Issue [JP-1727](https://jira.stsci.edu/browse/JP-1727) was created on JIRA by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft):_

I have a notebook to test TSO imaging through detector1 that ran on Build 7.5. I'm trying to put it into the validation notebooks repo, but when attempting to run this in Jenkins, it crashed. After a discussion with Nadia about where the problem might be, the Jenkins error is listed in the data location field, she thought the error could be due to a data model issue between build 7.5 and 7.6. I just re-tested my notebook under an installed dev version of 0.17.0 (listed above), and got an I/O error.

 
2020-09-24 11:40:03,117 - stpipe - WARNING - /Users/cracraft/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above. and should_run_async(code)
 
--------------------------------------------------------------------------- ValueError Traceback (most recent call last) <ipython-input-9-c33bb429a892> in <module>  13 fig, ax = plt.subplots(nrows=1, ncols=2, figsize=[8,10])  14 ---> 15 rplt = ax[0].imshow(rmod.data, origin='lower', aspect='equal', interpolation='None', vmin=0, vmax=10)  16 ax[0].set_title('Integrated rate file slope image')  17 ax[0].set_xlabel('px') ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/matplotlib/*_init_*.py in inner(ax, data, *args, **kwargs)  1429 def inner(ax, *args, data=None, **kwargs):  1430 if data is None: -> 1431 return func(ax, *map(sanitize_sequence, args), **kwargs)  1432  1433 bound = new_sig.bind(ax, *args, **kwargs) ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/matplotlib/axes/*axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, filternorm, filterrad, resample, url, **kwargs)  5517 resample=resample, **kwargs)  5518 -> 5519 im.set_data(X)  5520 im.set_alpha(alpha)  5521 if im.get_clip_path() is None: ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/matplotlib/image.py in set_data(self, A)  691 if isinstance(A, PIL.Image.Image):  692 A = pil_to_array(A) # Needed e.g. to apply png palette. --> 693 self._A = cbook.safe_masked_invalid(A, copy=True)  694  695 if (self._A.dtype != np.uint8 and ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/matplotlib/cbook/__init_*.py in safe_masked_invalid(x, copy)  680  681 def safe_masked_invalid(x, copy=False): --> 682 x = np.array(x, subok=True, copy=copy)  683 if not x.dtype.isnative:  684 # If we have already made a copy, do the byteswap in place, else make a ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/asdf/tags/core/ndarray.py in *_array_*(self)  289  290 def *_array_*(self): --> 291 return self.*make_array()  292  293 def __repr_*(self): ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/asdf/tags/core/ndarray.py in *make_array(self)  258 block = self.block  259 shape = self.get_actual_shape( --> 260 self._shape, self._strides, self._dtype, len(block))  261  262 if block.trust_data_dtype: ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/asdf/fits_embed.py in __len_*(self)  37  38 def *_len_*(self): ---> 39 return self.*hdu.data.nbytes  40  41 @⁣property ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/astropy/utils/decorators.py in __get_*(self, obj, owner)  756 return val  757 else: --> 758 val = self.fget(obj)  759 obj.*_dict_*[self._key] = val  760 return val ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py in data(self)  228 return  229 --> 230 data = self._get_scaled_image_data(self._data_offset, self.shape)  231 self._update_header_scale_info(data.dtype)  232 ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py in _get_scaled_image_data(self, offset, shape)  699 code = BITPIX2DTYPE[self._orig_bitpix]  700 --> 701 raw_data = self._get_raw_data(shape, code, offset)  702 raw_data.dtype = raw_data.dtype.newbyteorder('>')  703 ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)  518 offset=offset)  519 elif self._file: --> 520 return self._file.readarray(offset=offset, dtype=code, shape=shape)  521 else:  522 return None ~/anaconda3/envs/jwst_0170_dev/lib/python3.7/site-packages/astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)  302 '{}'.format(size, shape, dtype))  303 --> 304 filepos = self._file.tell()  305  306 try: ValueError: I/O operation on closed file
 
The notebook can be found here: <https://github.com/spacetelescope/jwst_validation_notebooks/tree/master/jwst_validation_notebooks/calwebb_detector1/jwst_detector1_miri_test>
 
The cell I'm trying to execute is to show some plots, (9th executable cell) that starts with loading two files into datamodels for ImageModel and CubeModel.
 
Any ideas?

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1727?focusedCommentId=486349#comment-486349):_

Some information on this: I was initially trying to read in my files into a datamodel with the 'with' statement like so:

with ImageModel(outname+'_rate.fits') as rmod:
     # raises exception if file is not the correct model

    pass

This fails with the I/O operation on closed file error.

At Nadia's advice, I tried to read in the data as part of the with command:

with ImageModel(outname+'_rate.fits') as rmod:
     # raises exception if file is not the correct model
     rdata = rmod.data

 

This worked once, but is also failing more often than not.

 

So now I'm just reading the file in like this, and it's working:

rmod = ImageModel(outname+'_rate.fits')
rdata = rmod.data

 

So what is the best advice for how to do this in the notebooks? It didn't complain in build 7.5, but seems to be having problems in 7.6. I've put this into most of my test notebooks, and would just like to know if I should be changing the way I access data models in all of my notebooks.

**Comment by jdavies-st** [comment]
The `with` context manager is designed to manage resources in Python, and thus when you use it to open a file (or instantiate a datamodel from a FITS file), you should expect the file to be closed on exiting the `with` block.  That's the definition of the `with` context manager in Python.  That's the reason for it existing.

So anything you need to do that with that data should be done inside the `with` block:

```
with Image(file) as im:
    do things with im
```

Dont' access `im` outside the block.  Even though `im` still exists as an object in memory, the file handle that it is connected to is closed and not accessible.

All of the above is a general rule for the `with` context manager in Python.  Adjust your code accordingly.

That said, there was a bug in previous versions of datamodels where files handles were left dangling, open, and depending if the object had been loaded into memory, (depending on the lazy load and memory mapping settings), it's possible you could access a data array outside the `with` block.  But this should not be counted on.

Hope this helps.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1727?focusedCommentId=486413#comment-486413):_

The documentation in readthedocs shows this usage, which is what I was copying:

from jwst.datamodels import ImageModel

with ImageModel("myimage.fits") as im:

    #raises exception if myimage.fits is not an image file

    pass

The documentation should be updated to reflect the correct usage. Does that need to be a documentation ticket?

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1727?focusedCommentId=488466#comment-488466):_

Here's the current error when trying to build on Jenkins. The previous problem was fixed and the notebook runs, but this happens.
jinja2.exceptions.TemplateNotFound: nb_html.tpl[Pipeline] }[Pipeline] // stage[Pipeline] stage[Pipeline] { (Deploy)Stage "Deploy" skipped due to earlier failure(s)[Pipeline] }[Pipeline] // stage[Pipeline] stage[Pipeline] { (Declarative: Post Actions)[Pipeline] deleteDir[Pipeline] }[Pipeline] // stage[Pipeline] }[Pipeline] // withEnv[Pipeline] }[Pipeline] // withEnv[Pipeline] }[Pipeline] // node[Pipeline] End of PipelineERROR: script returned exit code 1
Finished: FAILURE

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1727?focusedCommentId=509520#comment-509520):_

This problem was resolved with Brian York's help and the notebook is now running.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1727?focusedCommentId=509521#comment-509521):_

Notebook is now running fine under Jenkins.
