### ISSUE TITLE
Reduce jump step memory usage

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5368]
_Issue [JP-1735](https://jira.stsci.edu/browse/JP-1735) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

A significant fraction of the memory errors that occur during calwebb_detector1 processing of TSO exposures in the Ops environment occur in the jump step, when it tries to allocate memory for any one of the large temporary arrays it uses during processing.

One the worst (if not the worst) offenders is the `all_ratios` array, which is created at <https://github.com/spacetelescope/jwst/blob/master/jwst/jump/twopoint_difference.py#L36.> It is a 4-D floating-point array of the same size as the original SCI and ERR arrays, hence consuming a large amount of memory. A quick scan of the code suggests that it may not be necessary to make this array 4-D (covering all integrations in the exposure), but could instead be a 3-D array specific to each integration. This needs to be investigated and updated, if possible.

**Comment by jdavies-st** [comment]
There's also a bunch of temporary arrays made used for indexing that are unnecessary or can at least be deleted after they are used.  Look for any call to `np.where`, and this can be replaced with a normal boolean array indexing.

As an example

https://github.com/spacetelescope/jwst/blob/fd905fb4c66d779b67fef3ea92f4c9731cd38ac3/jwst/jump/twopoint_difference.py#L66-L67

can be replaced with

```python
first_diffs[np.isnan(first_diffs)] = 100000.
```

I had investigated this a while ago, even started a branch, but ran into unit test failures that were completely unexpected.  Happy to share my branch with anyone who will work on this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1735?focusedCommentId=490720#comment-490720):_

Fixed by #5404
