### ISSUE TITLE
Add NRS_VERIFY to assign_wcs/nirspec exposure type list

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5400]
_Issue [JP-1747](https://jira.stsci.edu/browse/JP-1747) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Need to add `NRS_VERIFY` to the `exp_type2transform` at

<https://github.com/spacetelescope/jwst/blob/master/jwst/assign_wcs/nirspec.py#L1750>

Note: Oddity that the step seems to run correctly without this. Investigate whether the regressions actually catch this.

**Comment by nden** [comment]
The step will not crash but will set assign_wcs to `SKIPPED`.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1747?focusedCommentId=489998#comment-489998):_

`assign_wcs` does successfully run without any modification. The reason is that grating is MIRROR which forces the `imaging` pipeline as per the following code:

<https://github.com/spacetelescope/jwst/blob/354074e61b8275d378e35e5e83047e337952ef7f/jwst/assign_wcs/nirspec.py#L55-L63>

Regardless, will still add NRS_VERIFY to the exp_type2transform list.

**Comment by jdavies-st** [comment]
Maybe it would be good to remove the "mirror" block

https://github.com/spacetelescope/jwst/blob/354074e61b8275d378e35e5e83047e337952ef7f/jwst/assign_wcs/nirspec.py#L56-L57

and have all the configuration happen in the `exp_type2transform` dict?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1747?focusedCommentId=490009#comment-490009):_

I believe it is true that grating setting is semi-independent of exposure type. For example, it is (may be?) possible to have NRS_IFU but have grating as MIRROR, which would force the imaging pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1747?focusedCommentId=490271#comment-490271):_

Resolved by [PR #&#x2060;5403](https://github.com/spacetelescope/jwst/pull/5403)
