### ISSUE TITLE
Add setting of FITS keyword for quality of eng mnemonics used in set_telescope_pointing

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5418]
_Issue [JP-1753](https://jira.stsci.edu/browse/JP-1753) was created on JIRA by [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp):_

The set_telescope_pointing function  uses a set of engineering telemetry mnemonics to calculate and populate the FITS keywords with pointing info.  If the  engineering mnemonics are not present, the function uses the PPS planned  boresight pointing info.

Update set_telescope_pointing to set the following FITS keyword.  ENGQLPTG as follows:
 * CALCULATED, if the function was able to calculate the pointing info from the engineering telemetry mnemonics
 * PLANNED, if the function was unable to calculate the pointing and used the PPS planned  pointing info.

 

<https://jira.stsci.edu/browse/JWSTKD-386>

**Comment by hbushouse** [comment]
Technically, it does not default to the planned *boresight* pointing, but rather the RA/Dec of the target. The target is placed at the aperture reference point, which is some distance (a few arc minutes) away from the boresight (the V1 axis).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1753?focusedCommentId=495699#comment-495699):_

Will require a corresponding JWSTKD ticket to add this new keyword to the dictionary. I'll file that and link it.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp) on [JIRA](https://jira.stsci.edu/browse/JP-1753?focusedCommentId=495700#comment-495700):_

JWSTKD-386 was already filed and is linked to this ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1753?focusedCommentId=501210#comment-501210):_

Fixed by #5556
