### ISSUE TITLE
Typos in ASDF reference file "how to" page

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5449]
_Issue [JP-1768](https://jira.stsci.edu/browse/JP-1768) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

This page has a couple of minor typos: <https://jwst-pipeline.readthedocs.io/en/latest/jwst/assign_wcs/asdf-howto.html> 
 * <https://jwst-pipeline.readthedocs.io/en/latest/jwst/assign_wcs/asdf-howto.html#create-the-reference-file>

 # 
 ## DictortionModel --> DistortionModel
 ## validaiton --> validation

 * <https://jwst-pipeline.readthedocs.io/en/latest/jwst/assign_wcs/asdf-howto.html#save-a-transform-to-an-asdf-file>
 ## Once the model is **create** --> Once the model is **created**

**Comment by hbushouse** [comment]
Fixed by #6524 and #6795

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1768?focusedCommentId=581247#comment-581247):_

First 2 items fixed by #6524

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1768?focusedCommentId=581305#comment-581305):_

Fixed by #6795

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1768?focusedCommentId=581247#comment-581247):_

First 2 items fixed by #6524

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1768?focusedCommentId=581305#comment-581305):_

Fixed by #6795
