### ISSUE TITLE
Add version information to the stable version of the Calibration Pipeline documentation

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5454]
_Issue [JP-1772](https://jira.stsci.edu/browse/JP-1772) was created on JIRA by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz):_

The  Calibration Pipeline documentation for the stable and the latest version do not include the version number. If it is there I cannot see it. I am looking here

<https://jwst-pipeline.readthedocs.io/en/stable/jwst/introduction.html>

and

<https://jwst-pipeline.readthedocs.io/en/latest/jwst/data_products/index.html>

Please add the build number at the top of the left hand side menu; e.g. Build 7.5 or JWST 0.16.0 version; not sure what would be more adequate. This is in particular important for when we are adding the PDF version of this documentation via JDox

**Comment by hbushouse** [comment]
See also https://github.com/spacetelescope/jwst/issues/5673

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1772?focusedCommentId=578883#comment-578883):_

Relates to #5673

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1772?focusedCommentId=578883#comment-578883):_

Relates to #5673

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-1772?focusedCommentId=611877#comment-611877):_

Looks good. This can be closed
