### ISSUE TITLE
jwst ephemeris in the headers already

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#548]
@perrygreenfield has found that the core schema already had ephemeris keywords. @stscieisenhamer has confirmed that these are being populated. Need to confirm whether these should be used for pointing info instead of the currently independent reading of the ephemeris.

**Comment by melanieclarke** [comment]
Closing - this issue appears to be overtaken by events.  If there are still issues with sourcing ephemeris data, please open a new issue.
