### ISSUE TITLE
Standardize wfs_combine

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5511]
_Issue [JP-1793](https://jira.stsci.edu/browse/JP-1793) was created on JIRA by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

The `WfsCombineStep` has a number oddities that make it difficult to work with.  These should be resolved.

* It only accepts an assocation as input.  Generally steps also accept open datamodels, or in this case perhaps a ModelContainer would be appropriate.
* The step does not return anything.  It merely writes out the results.  These makes it very difficult to test.  It should return either a DataModel or ModelContainer as appropriate
* It always writes out the results.  But steps shouldn't do this.  They should only write out results if asked to.
* It doesn't know whether it is a Step or Pipeline.  It seems to be being used as a pipeline, and perhaps that's why it has hard-coded writing of files and no return at the end of the step.

**Comment by jdavies-st** [comment]
Some good comments here

https://github.com/spacetelescope/jwst/pull/5519#discussion_r537820643

On returning the model with the correct name without having to write it out manually, as we currently do.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=564213#comment-564213):_

Just checking in on this, since it isn't quite clear... is this fix implemented? If so, should we ask wavefront experts to test? 

[Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) FYI

**Comment by stscijgbot-jp** [comment]
_Comment by [Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=564218#comment-564218):_

[Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) I can give it a try but it seems that it is more about the wfs_combine method that the actual science quality output, i.e., images. Not sure what should be the expectation about the output.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=564251#comment-564251):_

Yes, the updates were implemented in <https://github.com/spacetelescope/jwst/pull/6376.> It's a change to step infrastructure only; no changes to the actual algorithm. So new results should be identical to the old.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=575587#comment-575587):_

Fixed by #6376

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=564213#comment-564213):_

Just checking in on this, since it isn't quite clear... is this fix implemented? If so, should we ask wavefront experts to test? 

[Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) FYI

**Comment by stscijgbot-jp** [comment]
_Comment by [Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=564218#comment-564218):_

[Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) I can give it a try but it seems that it is more about the wfs_combine method that the actual science quality output, i.e., images. Not sure what should be the expectation about the output.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=564251#comment-564251):_

Yes, the updates were implemented in <https://github.com/spacetelescope/jwst/pull/6376.> It's a change to step infrastructure only; no changes to the actual algorithm. So new results should be identical to the old.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1793?focusedCommentId=575587#comment-575587):_

Fixed by #6376
