### ISSUE TITLE
Calimage3 not working correctly with MIRI dithered BRIGHTSKY data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5528]
_Issue [JP-1806](https://jira.stsci.edu/browse/JP-1806) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

There seems to be possibly two problems.
 # When running calwebb_image3 with 4 dithered Brightsky MIRI simulated  data the combined image contains mostly zeros. This type of error was also reported in JP-1694.
 # When turning off outlier_rejection the combined data seems to contain data from the 4 dithers, but some of the image are highly distorted.
 !image-2020-12-11-09-34-03-985.png|width=272,height=198!

The below image (top 4 images )  are i2d files from cal_spec2. The bottom four images are the result of running the outlier detection step and setting save_intermediate_results = True. These images are the single images mapped to the output plane. These images show that something seems wrong with the WCS of the images.
 !image-2020-12-11-09-30-15-866.png|width=563,height=275!

 

The data can be found at ███████████████████████████████████████████

**Comment by nden** [comment]
@jemorrison JP-1694 was resolved. Did it resolve this issue as well?

**Comment by jemorrison** [comment]
Resolve by JP01694 #5601

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1806?focusedCommentId=510887#comment-510887):_

resolved by JP-1694 #&#x2060;5601

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1806?focusedCommentId=510887#comment-510887):_

Fixed by #5601
