### ISSUE TITLE
subarray bounding boxes are 1 pixel too small

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5542]
_Issue [JP-1818](https://jira.stsci.edu/browse/JP-1818) was created on JIRA by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

Testing of

#5507

found a bug in `jwst.assign_wcs` where NIRCam time-series subarrays of 64x64 were getting bounding boxes of size

```
In [9]: result
Out[9]: <CubeModel(4, 64, 64) from jw00312006001_02102_00001-seg001_nrcb1_rateints.fits>

In [11]: result.meta.subarray.instance
Out[11]: 
{'fastaxis': 1,
 'name': 'SUB64P',
 'slowaxis': -2,
 'xsize': 64,
 'xstart': 1985,
 'ysize': 64,
 'ystart': 1985}

In [12]: result.meta.wcs.bounding_box
Out[12]: ((-0.5, 62.5), (-0.5, 62.5))
```

It looks like this is a general problem for all subarray bounding boxes.

**Comment by jdavies-st** [comment]
For non-subarrays, such as full-frame NIRCam images, we have the following bounding boxes:

```
In [56]: model = datamodels.open("jw42424001001_01101_00001_nrca5_cal.fits")

In [57]: model.meta.wcs.bounding_box
Out[57]: ((-0.5, 2047.5), (-0.5, 2047.5))

In [58]: model.data.shape
Out[58]: (2048, 2048)
```
