### ISSUE TITLE
The sky positions in the imaging source catalogue do not match the WCS for the pixel positions

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5550]
_Issue [JP-1824](https://jira.stsci.edu/browse/JP-1824) was created on JIRA by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk):_

I made some testing data sets for NIRISS imaging, using the normal four-point dithers.  These run through the pipeline without issues, but when I looked at the source catalogues and compared the sky positions reported to the WCS sky positions for the pixel coordinates (x,y) there is a discrepancy of the order of 1 arc-second between the two sky positions.  I had expected these positions to be the same.  The position differences appear to be a systematic function of the right ascension values in the catalogue.

I also note that the right ascension values returned by the call to the WCS wcs.meta.wcs() function are negative for the test field in pipeline_test3, which I would have thought should not happen.  Apparently the WCS code is not testing that the RA values are in the range 0 to 360 degrees.  Adding 360 degrees to the WCS RA values fixes the problem, but this should not be needed.  Such an issue was reported in JP-1585 and is marked as being resolved, but it happened again here.

The attached images show the position offsets in RA and Dec for two sky positions:  one is at about (12:36:30, +36:09:10) and the other is at about (05:13:20, -68:46:00).  The offsets are positive for the north field and negative for the south field, and appear to be correlated with the RA value with the image.  There are fewer sources in the north field because the south field is a commissioning field in the LMC while the north field was selected to be at fairly high galactic latitude.

**Comment by jdavies-st** [comment]
For background, see discussion in https://github.com/spacetelescope/jwst/issues/5141

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=504872#comment-504872):_

[Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) can you make the permissions for this test data such that we can look at it? It is currently locked down.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=504888#comment-504888):_

As far as I can see the directory has world read/execute permissions.  Can you "see" the /ifs/jwst/wit/niriss/ directory?

**Comment by stscijgbot-jp** [comment]
_Comment by [Clare Shanahan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cshanahan) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=504897#comment-504897):_

i can access /ifs/jwst/wit/, but the niriss subdirectory has different permissions set

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=504982#comment-504982):_

I am copying the directories to /user/volk/pipeline_tests/ which people should be able to "see".

**Comment by stscijgbot-jp** [comment]
_Comment by [Clare Shanahan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cshanahan) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=506961#comment-506961):_

I checked this out and luckily it does not look to be an issue with the pipeline. It seems like you are using the source pixel positions in the drizzled frame (x & y in the source catalog), and using the WCS of one of the input frames (cal.fits files) to transform to RA & Dec to compare to the source catalog's sky positions. This is not a valid comparison because the pixel positions of those sources in the input frame are going to be different than the final image.

 

While I'm not sure exactly what steps you took to generate the attached plots showing the offset in sky coordinates (next time, would you mind isolating your issue in a jupyter notebook, that would be helpful!), I used one of the datasets in your test directory and was able to produce a plot showing the same thing when I compared source_catalog RA & Dec to cal_file.wcs(x, y), so I'm fairly certain this is what is going on.  !Screen Shot 2021-01-28 at 8.28.00 PM.png|width=345,height=214!

I verified that source_catalog's sky positions check out with the final image's WCS (source_catalog RA + Dec minus final_image.wcs(x, y)) and there are no systematics. 

!Screen Shot 2021-01-28 at 8.49.12 PM.png|width=297,height=217,thumbnail!

Finally, I did the round-trip of taking the source catalogs ra + dec, using each input frame's wcs to compute x & y, then using the inverse transform to go back to RA & Dec and also found no systematic offsets there, so the WCSs of the individual frames also check out with source_catalog.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=507388#comment-507388):_

OK I have to apologise for raising an issue due to getting the pixel positions mixed up.  I will try and re-check it but I assume I will find that the positions match as indicated.

I am not very good with notebooks, but if there is a next time I will see about trying to use that...I have basically had nothing but problems making notebooks in the past.  Somehow these do not mesh with the way I think about things.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=539586#comment-539586):_

Just to close this out, testing in pipeline 7.8rc4 show that the pixel positions and the WCS sky positions match well as expected.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1824?focusedCommentId=539596#comment-539596):_

Temporarily reopening to reset status.
