### ISSUE TITLE
TSO outlier_detection does not follow requirements

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5613]
_Issue [JP-1845](https://jira.stsci.edu/browse/JP-1845) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The algorithm to be used for outlier detection in TSO and Coronagraphy exposures is outlined in <https://outerspace.stsci.edu/display/JWSTCC/Vanilla+Stack+Outlier+Detection.> The current outlier_detection step does **not** follow these specs. Instead, it is using all of the normal imaging mode algorithms, with the simple addition of turning off resampling of the images when forming the median image and hence working in detector space. New functionality that follows the specs needs to be implemented.

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Gordon](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kgordon) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=503610#comment-503610):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse): I have started looking at this step and what it would take to implement the JCalWG algorithm.  Is there a github issue for this work or should I use this Jira ticket?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=503642#comment-503642):_

Huh, no there isn't a github issue for some reason. The git bot that normally creates a github issue for new Jira tickets appears to have been AWOL since about Jan 4. We'll git that fixed. In the meantime just use this Jira ticket for communication.

**Comment by karllark** [comment]
So, should I now use the github issue?  ;-)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=503665#comment-503665):_

Now that the gitbot is turned back on you can use either one. Comments posted to Jira will get copied to github and vice versa.

**Comment by karllark** [comment]
Initial review of the stage 3 outlier detection code.

All of the data is run through outlier_detection_step.py and the outlier detection is done using 4 different outlier_detection_XXX.py (imaging = outlier_detection.py, scaled = outlier_detection_scaled.py, ifu = outlier_detection_ifu, and slitspec = outlier_detection_spec).  

Yet there are two other "xxx_step.py" files - outlier_detection_scaled_step.py and outlier_detection_stack_step.py.  Are these still used?  It is not clear if they are.  If not, maybe remove them?

The detection in outlier_detection.py is close to what is needed for TSO/coronagraphy.  There is code to handle the case where resampling the data is not needed (e.g., non-dithered data).  But the actual detection of CRs is done using a derivative image of as well as the simple comparison of each image to the median.  It looks like having an option to ignore the derivative portion of the calculation looks to be what is needed.

Summary.  Could be quite straightforward to implement the needed capability.

**Comment by karllark** [comment]
The docstrings could use some updating to more clearly say what they are doing (e.g., OutlierDetection.flag_cr could have a bit more info that would have made it clearer the algorithms being used to flag CRs).  I will do some of this as part of my planned PR unless it is stated this is not desired.

**Comment by hbushouse** [comment]
Useful doc strings are good!

**Comment by karllark** [comment]
Looking for the logic in OutlierDetectionStep.process, I don't see how MIRI TSO imaging is identified.  TSO_IMAGE_MODES only includes NRC_TSIMAGE.  MIRI TSO imaging is not a separate template, so is not a different exptype? 

I will continue with the work needed, just putting this note here to ensure that this question is answered at some point.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=513742#comment-513742):_

Well that's obviously an oversight. It was probably written that way back when NRC_TSIMAGE was the only TSO mode imaging available, and then things were upgraded in APT to allow it for other imaging, like MIRI. You're right that NRC_TSIMAGE is the only dedicated TSO imaging mode, so all other instances with have normal EXP_TYPE's (e.g. MIR_IMAGE), in which the TSOVISIT keyword is used to determine whether it's TSO or not. TSOVISIT is a boolean. So you need the combination of MIR_IMAGE and TSOVISIT.

**Comment by jdavies-st** [comment]
Can the `jwst.lib.pipe_utils.is_tso()` function help here?

**Comment by karllark** [comment]
Thanks for the insight.  Will investigate.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=521547#comment-521547):_

Fixed by #5822

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=556369#comment-556369):_

[Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena)   [Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza)   [Dean Hines](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hines) Does anyone know if this was tested in the last round of pipeline testing? If not, can it be tested in the build 7.8 patch testing in the next few weeks?

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Gordon](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kgordon) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=503610#comment-503610):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse): I have started looking at this step and what it would take to implement the JCalWG algorithm.  Is there a github issue for this work or should I use this Jira ticket?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=503642#comment-503642):_

Huh, no there isn't a github issue for some reason. The git bot that normally creates a github issue for new Jira tickets appears to have been AWOL since about Jan 4. We'll git that fixed. In the meantime just use this Jira ticket for communication.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=503665#comment-503665):_

Now that the gitbot is turned back on you can use either one. Comments posted to Jira will get copied to github and vice versa.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=513742#comment-513742):_

Well that's obviously an oversight. It was probably written that way back when NRC_TSIMAGE was the only TSO mode imaging available, and then things were upgraded in APT to allow it for other imaging, like MIRI. You're right that NRC_TSIMAGE is the only dedicated TSO imaging mode, so all other instances with have normal EXP_TYPE's (e.g. MIR_IMAGE), in which the TSOVISIT keyword is used to determine whether it's TSO or not. TSOVISIT is a boolean. So you need the combination of MIR_IMAGE and TSOVISIT.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=521547#comment-521547):_

Fixed by #5822

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=556369#comment-556369):_

[Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena)   [Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza)   [Dean Hines](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hines) Does anyone know if this was tested in the last round of pipeline testing? If not, can it be tested in the build 7.8 patch testing in the next few weeks?

**Comment by stscijgbot-jp** [comment]
_Comment by [Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=583049#comment-583049):_

Coming back to this ticket to say that we will not be able to check this until after commissioning.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=629970#comment-629970):_

Does anyone want to test this (it was implemented quite a while ago) or should we close the ticket?

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=646691#comment-646691):_

[Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza) [Nikolay Nikolov](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nnikolov)  Do you know if this is working as intended now? We'd like to close out these older tickets. If we don't hear any updates on the ticket, we plan to close them out at the end of the week and let people open any new tickets for further issues.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1845?focusedCommentId=647530#comment-647530):_

Closing the ticket due to lack of response from originators. Any new issues related to this can be opened as new bug tickets.
