### ISSUE TITLE
surface brightness not being populated in x1d products for NIRSpec fixed slit data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5619]
_Issue [JP-1852](https://jira.stsci.edu/browse/JP-1852) was created on JIRA by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol):_

The surface brightness column of the x1d product generated from calwebb_spec2 processing of a single FS exposure contains all zeroes.  I tried processing both with and without the keyword "SRCTYAPT=EXTENDED", the result was the same.  The exposure is a full frame image, originally taken in MOS mode, but I changed EXP_TYPE to NRS_FIXEDSLIT in order to extract the FS spectra that are present (in this example, I extracted only the S200A2 slit).  This is particularly relevant for master background subtraction, since there will be many cases in which the user will want to use the FS for background subtraction of MOS data, and that does not work if SURF_BRIGHT is not populated.

Edit: I subsequently noticed that the x1d file header has "SRCTYPE = POINT", which is not correct.  I added the keyword "SRCTYAPT = EXTENDED" to the rate file prior to calwebb_spec2 processing, though there is no SRCTYPE keyword in the cal or s2d output files (not sure if this is expected?).  However, the verbose output of the processing indicates that the source is being treated as EXTENDED.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=505898#comment-505898):_

NRS fixed-slit mode is a little tricky in that Cal makes an assumption that the SRCTYAPT only applies to the primary slit that has the science target in it, which is expected to be designated in the FXD_SLIT keyword. So the source_type step will do appropriate processing for that slit (i.e. use the SRCTYAPT keyword if it's been set, otherwise it defaults to POINT. All other slits (if present in the data) default to POINT, regardless of the SRCTYAPT value. But either way, all slit instances should end up with a SRCTYPE keyword value of some sort in their SCI extension headers. So the fact that SRCTYPE doesn't exist is a bit of a mystery.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=506135#comment-506135):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) as a side-note, the SRCTYPE assignment for the FS originally came up in [JP-1150](https://jira.stsci.edu/browse/JP-1150), though there was never a dedicated ticket.  The default for non-primary slits should be EXTENDED, since most often they will only contain background.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=506201#comment-506201):_

D'oh! Missed that one. Thanks for making that "point" [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol). JP-1878 has been created to make that fix.

Also, for anyone from the CalWG who's listening, the specs for the srctype step should also be updated at <https://outerspace.stsci.edu/display/JWSTCC/Vanilla+Point+vs+Extended+Decision>

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=507157#comment-507157):_

 

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I copied your rate file and I ran calspec2 on that file to produce the s2d file I can use in extract1d testing. When I do that I get SRCTYPE=EXTENDED ( I believe you want this ) for all the slits. I realize your test only had 1 slit but for some reason your s2d file for  1 slit had SRC=POINT. So I went with my version.  The SRCTYPE for every slit in my s2d file is EXTENDED.

I get values of surface bright in the extract1d table. So trying running calspec2 on the rate file and see what you get. 

James do the units in the s2d image you created make sense to you ? The header says MJy/sr but  that seems   wrong the numbers seem too big.

**Comment by nden** [comment]
@hbushouse Close this?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=507301#comment-507301):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I'll try processing all the slits.  In my original case, it must have defaulted to POINT because I specified a single slit to be processed.

The weird units are a result of our reference files not having real numbers for PHOTMJ or AREA; to get surface brightness, the pipeline ends up dividing one by steradians/sqarcsec, so 1 DN/s = 4.25e10 "MJy/sr".

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=507365#comment-507365):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I just reprocessed this exposure with calwebb_spec2 using all defaults, extracting all the FS, and I still get SRCTYPE=POINT in both the cal and s2d products (though SRCTYAPT in the primary header of both is EXTENDED).  Weirdly enough, the verbose output for the extract_1d step says "Target is extended, so the entire region will be extracted", yet the surface brightness column is still not populated.  I'm using 0.17.1, perhaps something was updated since then?  I can try the latest release candidate.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=507371#comment-507371):_

Try the latest release candidate we are on 0.18.3

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=507380#comment-507380):_

The fix to the srctype step for NRS FS did not make it into the 0.18.3 release (missed it by a couple days). So you'll need to test with the latest dev version from github.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1852?focusedCommentId=507500#comment-507500):_

Ok, tested with 0.18.4.dev14+g83215761.  All looks good, I'll close the ticket.
