### ISSUE TITLE
Remove hard-coded MRS outlier detection parameters

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5639]
_Issue [JP-1862](https://jira.stsci.edu/browse/JP-1862) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

We previously put in place some stopgap code to ensure that the MRS used reasonable default parameters for outlier rejection ([https://github.com/spacetelescope/jwst/pull/4778).]  Once a new parameter reference file has been created we should remove the hard-coded values.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-1862?focusedCommentId=510156#comment-510156):_

Parameter reference files delivered, PR to remove hard-coded values is #5753

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-1862?focusedCommentId=510850#comment-510850):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) Please close this ticket of all associated work is complete.

**Comment by hbushouse** [comment]
Fixed by #5753

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1862?focusedCommentId=510864#comment-510864):_

Fixed by #5753
