### ISSUE TITLE
Computation of velocity aberrated RA, DEC and scale

### ISSUE THREAD

**Issue by mcara** [spacetelescope/jwst#5658]
In https://github.com/spacetelescope/jwst/pull/5602 I implemented _constant scale correction_ to be applied to `gwcs` in order to obtain Velocity Aberration (VA)-free coordinates. That correction relies on constant scale value supplied in `datamodel.meta.velocity_aberration.scale_factor`. My understanding is that this value is computed by https://github.com/spacetelescope/jwst/blob/master/jwst/lib/set_velocity_aberration.py

I do not know where this script is called and how it is used. However, I have noticed a couple of apparent inconsistencies in the returned values of the [`aberration_offset()`](https://github.com/spacetelescope/jwst/blob/4a60fe1ad92a50a38a15e25b43402ac024c4406e/jwst/lib/set_velocity_aberration.py#L90-L127) function:

1. It returns _difference_ between corrected RA, DEC and uncorrected values;
2. [Even more weird is that] It returns above differences converted to radians;
3. However, [datamodel's schema](https://github.com/spacetelescope/jwst/blob/4a60fe1ad92a50a38a15e25b43402ac024c4406e/jwst/datamodels/schemas/core.schema.yaml#L1292-L1305) indeed says (confirms) that the `DVA_RA` and `DVA_DEC` are in `rad`.

Here are my comments and questions:
1. `DVA` implies "differential" effects of VA, that is, effects left over after correcting for the absolute ("offsets") aberration. However, `DVA_RA` and `DVA_DEC` seem to be the absolute corrections, not the differential that are (mostly) accounted for by a constant scale correction.
2. Another issue is that reported values are deltas. Shouldn't we report corrected `RA` and `DEC` instead of "corrections to old values"? This will also make life easier since after adding "corrections" to `RA` and `DEC` one would need to take care of the 180 and 360 angle wrapping.
3. Based on points 1. and 2. above, I would suggest renaming these names in `meta` to `VACORR_RA` and `VACORR_DEC` (or `VA_RA` and `VA_DEC` or something along these lines) _that report **corrected(?) `RA` and `DEC` values in degrees**_.
4.  [`aberration_offset()`](https://github.com/spacetelescope/jwst/blob/4a60fe1ad92a50a38a15e25b43402ac024c4406e/jwst/lib/set_velocity_aberration.py#L90-L127) and [`aberration_scale`](https://github.com/spacetelescope/jwst/blob/4a60fe1ad92a50a38a15e25b43402ac024c4406e/jwst/lib/set_velocity_aberration.py#L34-L87) share a lot of code/computations. Would it be _**OK**_ to combine these two functions into a single one or do we have to keep them separate? Computationally, this would be more efficient.

Thanks!

CC: @nden @hbushouse

**Comment by hbushouse** [comment]
Combining the two existing functions into a single routine is fine. I don't see any reason to keep them separate. Both are always called together when the `set_velocity_aberration.py` script is run during level-1b processing.

As far as the `DVA_RA` and `DVA_DEC` keywords reporting offsets ("deltas") and in units of radians - I have no idea. Those keywords were defined a long, long time ago (perhaps copied from HST somewhere?), and I've never been able to find any record of how they were intended to be calculated or used. As of right now they aren't used anywhere downstream and hence changing their meaning from being offsets to corrected absolute values, as well as changing the units, should not affect anything.
