### ISSUE TITLE
Update RTD docs to show the version number

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#5673]
The current doc displays just the "latest" value in the left nav banner,  mouse-over of the browser tab shows the last commit on master.

The same is true for "stable", where the mouse-over the tab will show the last release.

Having the version more prominently displayed would probably be a useful prompt for onlookers as to whether they are looking at dev or released  :-)

**Comment by jdavies-st** [comment]
Agree.  Here's some documentation for anyone who wants to tackle it

https://docs.readthedocs.io/en/stable/versions.html

Currently it just shows latest and stable, but it would be nice to get the documentation for previously released tags as well.

**Comment by hbushouse** [comment]
"Latest" is built nightly from whatever updates have been merged to the jwst master branch. Those daily updates don't have a simple version number, like 7.9.3 or 1.4.6. And if we were to use the version number of the last release and attach it to "latest", it would then be misleading. So do you really want the docs to have a version of something like "1.4.2.dev5+gd7f97405.d20220120"?
