### ISSUE TITLE
Coron3 ASN lists x1dints product as background member

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5732]
_Issue [JP-1918](https://jira.stsci.edu/browse/JP-1918) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

As noted in JWSTDMS-486 the coron3 ASN jw00628-c1023_coron3_001_asn.json correctly includes a background member from Obs 86, but the product type for background exposure is x1dints. Coronagraphy is an imaging mode and hence a cal (or calints) product should be used for background.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1918?focusedCommentId=510800#comment-510800):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) I believe I've found the root cause, but because I am not all that familiar with this machinery, I'm not sure I know how best to solve the problem.

The long-winded explanation:
The pool entry in question has the column 'BKGDTARG' set to T, which is listed in SPECIAL_EXPOSURE_TYPES in dms_base.py. This changes the return of the default get_exposure_type method given in dms_base to 'background'. In DMS_Level3_Base.make_member, the expname is generated for the association entry using Utility.rename_to_level2. This function checks the provided exptype - if 'background', the suffix is set to 'x1d'. 

Looking at the code, it would appear that this " if member_exptype == 'background' then suffix = 'x1d' " (rules_level3_base, line 534) seems intentional and must have a purpose outside of this bug, but it is the root of this issue. Knowing as little as I do about the pathways general pool files go through to reach this point, it seems that the issue lies either in the value of BKGDTARG set in this pool file, or there is an additional logic branch that needs to be created for background-flagged exptype entries.

**Comment by hbushouse** [comment]
I'm guessing this is due to the fact that the only use of background ASN members in level 3 processing is for the purpose of spectroscopic master background subtraction, which always uses x1d (or x1dints) files as input. For coron3 ASN's we don't need to include background members at all, because the background subtraction is done in level 2b processing and hence they need to be listed in an image2 ASN (using rate products, not x1d).

**Comment by tapastro** [comment]
Does this mean the goal of the ticket is to simply remove the background exposure from the Coron3 association, if it's not used in level 3? Or is your comment more an explanation of why background-labelled items are given the x1d suffix by default? I could imagine a couple of ways to solve this ticket's issue, but it seems most options are likely to have severe implications for other pool files.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1918?focusedCommentId=511013#comment-511013):_

Yes, background members are not needed in a coron3 ASN and hence they can be completely removed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1918?focusedCommentId=511283#comment-511283):_

Adding a constraint of "not background" to the Asn_Lv3Coron rule should do the trick.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1918?focusedCommentId=511590#comment-511590):_

Fixed by #5781
