### ISSUE TITLE
GitHub Actions reports syntax error in ci.yml

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#5733]
https://github.com/spacetelescope/jwst/blob/bf24eaeaa5825f95439956e4e053f51b49655fb6/.github/workflows/ci.yml#L67-L68

If you open that file for edit using GitHub UI, you will see a complain that saying something like "expect string, blah blah, but an object is found" -- maybe you cannot change env that way inside a matrix; not sure.

**Comment by jdavies-st** [comment]
Thanks @pllim.  Hmm, it looks like you have to set it up in one of the steps.

https://docs.github.com/en/actions/reference/environment-variables#about-environment-variables

which is silly, as the definition then lives outside the actual job itself.

They didn't think through this stuff very well, did they?

**Comment by pllim** [comment]
Since you already use tox, maybe you can define a tox var to set it instead?

**Comment by jdavies-st** [comment]
That's a good idea, and it makes that tox env actually more useful/accurate when run outside of our CI.  🎉
