### ISSUE TITLE
stage3 resample issue

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#5772]
Hi, 

I'm running the latest pipeline (v0.18.3) on simulated MIRI images from MIRISIM. My data have three dithers. 

The pipeline works well before "resample" in stage3. 
But "resample", which merges the three dithers, messes up the outputs (see below, the first three are the input, the last one is the output).
My guess is there's some WCS issues in resample, but I can't figure it out. 

Could you help me fix it?

BTW, I had used v0.15.1. The old version did not have such an issue.

Thanks,
Guang 

![image](https://user-images.githubusercontent.com/7922328/108641698-4c44de00-7466-11eb-8678-af25b4f1febd.png)

**Comment by jdavies-st** [comment]
Try turning off `outlier_detection` in the stage3 pipeline and see if that makes things better.  The default parameteres of outlier detection are not very good for MIRI I believe.  The MIRI team is working on tuning them.

Also verify that `tweakreg` is doing what you expect it to in the stage 2 pipeline.  If these are simulated data, you can also probably turn it off, so as to take one extra variable out of the mix.

It looks like your 3rd image (bottom left) is really noisy relative to the other two.  Are these all on the same stretch?  And what is the actual problem with the output image (bottom right I assume)?

**Comment by Guang91** [comment]
>> Try turning off outlier_detection in the stage3 pipeline and see if that makes things better. The default parameteres of outlier detection are not very good for MIRI I believe. The MIRI team is working on tuning them.

I have tried to turn off outlier_detection. The results look similar. 

>> Also verify that tweakreg is doing what you expect it to in the stage 2 pipeline. If these are simulated data, you can also probably turn it off, so as to take one extra variable out of the mix.

Indeed, tweakreg is the root. After turning it off, things appear to be normal. I realized tweakreg only detects 3 sources in my data. Maybe that's the reason why it fails? Why it detects so few sources? 

>> It looks like your 3rd image (bottom left) is really noisy relative to the other two. Are these all on the same stretch? 

These're just due to different stretches. 

>> And what is the actual problem with the output image (bottom right I assume)?

Below is the same plot as the previous but zooming in on one bright star. You can see there appear to be two stars in the output (bottom right). 

![image](https://user-images.githubusercontent.com/7922328/108664978-824f8580-7499-11eb-8a92-409f682f08ac.png)

**Comment by hbushouse** [comment]
Given that it's simulated data there's probably no error in the WCS settings for each image to begin with and hence tweakreg isn't really necessary. But if you want to keep using it, you could try adjusting some of its params to detect more sources, such as `snr_threshold`, `kernel_fwhm`, and `fitgeometry`. For `fitgeometry` you could use a simpler solution, like `shift` or `rshift`, which gets a better fit from fewer sources.

**Comment by jdavies-st** [comment]
Cool, glad we found the issue.  I believe the MIRI team also has a CRDS reference file for `tweakreg` parameters that are optimized for MIRI.  Currently the default parameters are (loosely) optimized for NIRCam/NIRISS/NIRSpec/FGS.

**Comment by Guang91** [comment]
Thanks a lot @jdavies-st @hbushouse
