### ISSUE TITLE
Update TARG_RA/TARG_DEC keywords for MT exposures

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5785]
_Issue [JP-1939](https://jira.stsci.edu/browse/JP-1939) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

PPS does not populate the TARG_RA/TARG_DEC values for exposures of moving targets, mainly because they don't know in advance what the values will be when the target is observed. We should update the "update_mt_kwds" function in the "set_telescope_pointing" script to populate the TARG_RA/TARG_DEC keywords with the same values computed for the MT_RA/MT_DEC keywords.

**Comment by hbushouse** [comment]
Fixed by #5808

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1939?focusedCommentId=514737#comment-514737):_

Fixed by #5808
