### ISSUE TITLE
Detector1 not using the right sequence of steps with MIRI TSO imaging

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5789]
_Issue [JP-1940](https://jira.stsci.edu/browse/JP-1940) was created on JIRA by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew):_

I'm doing an end-to-end pipeline run for a MIRI TSO imaging dataset, using build 0.17.1. My call for Detector1Pipeline is as follows:
```java
det1 = Detector1Pipeline.call(mods[0], config_file='cfg_files/calwebb_tso1.cfg', save_results=True, output_dir=od, steps={"jump": {"rejection_threshold": 10.}})```
and just to check:

 

 
```java
In [16]: mods[0].meta.visit.tsovisit
Out[16]: True
In [17]: mods[0]
Out[17]: <RampModel(600, 60, 64, 72) from miri_imtso_SUB64_60G600I1E_F770Wexp1.fits>
 


```
The calwebb_tso1.cfg file has both the first and last frame steps set to 'SKIPPED'. However when I look at the output it looks like those steps were performed:

 
```java
In [18]: det1.meta.cal_step.firstframe
Out[18]: 'COMPLETE'
In [19]: det1.meta.cal_step.lastframe
Out[19]: 'COMPLETE'
 


```
Any thoughts on why this is happening?

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=521734#comment-521734):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) are you able to access this link: <http://vospace.esac.esa.int/vospace/sh/4a94b5c553fbf3be40aa11d5f0823048a67f45e6?dl=1> ](http://vospace.esac.esa.int/vospace/sh/4a94b5c553fbf3be40aa11d5f0823048a67f45e6?dl=1)

This is a tar file with the uncal as well as processed exposures for the dataset, using pipeline v0.18.3. Sorry it's in an external location (it's an ESA server though), but I produced this dataset for a colleague in the ESA archives group, and I had to physically go to STScI to get these data uploaded as my home connection is so slow and unstable. I think this link should be publicly accessible.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=521874#comment-521874):_

That worked for me, thanks! I'll get back to you with some results.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=522101#comment-522101):_

Hi [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew), after taking a quick look at this, do you have the .cfg file available that you're using? If I run calwebb_detector1 with 

```bash
strun calwebb_detector1 det_images/miri_imtso_SUB64_60G600I1E_F770Wexp1.fits --steps.firstframe.skip=True --steps.lastframe.skip=True
```

the cal_step outputs in the fits headers have no entry for S_FRSTFR or S_LASTFR. If I run the pipeline with no skip flags set, both header keywords are present and set to 'COMPLETE'.

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=522122#comment-522122):_

I use the file calwebb_tso1.cfg, which reads:

name = "Detector1Pipeline"
class = "jwst.pipeline.Detector1Pipeline"
save_calibrated_ramp = True

[steps]
 [[group_scale]]
 [[dq_init]]
 [[saturation]]
 [[ipc]]
 skip = True
 [[superbias]]
 [[refpix]]
 [[rscd]]
 [[firstframe]]
 skip = True
 [[lastframe]]
 skip = True
 [[linearity]]
 [[dark_current]]
 [[persistence]]
 skip = True
 [[jump]]
 [[ramp_fit]]
 [[gain_scale]]

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=522148#comment-522148):_

Hmm, that's puzzling. When I run the pipeline with this config, I get the same results as if I had specified the skips on the command line, i.e. neither of those cal_step keywords are populated in the _ramp.fits header. I can check doing this procedure in an interactive environment, but can you check your output _ramp.fits and see if the keywords are populated?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523011#comment-523011):_

Hi [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew), just wanted to check in and say that I have a fix for you, but it's not a complete fix and I think this is going a bit over my head. 

If, when you call the pipeline, you add in your step flags in addition to the jump step flag:
```java
steps={"jump": {"rejection_threshold": 10.}, "firstframe": {"skip": True}, "lastframe": {"skip":True}}
```

you should see in the resulting logs that the two steps are appropriately skipped and the cal_step keywords should not exist. 

However, I don't yet have a good answer for why the config file is not being used correctly. I can also tell you that if you move your jump step flag to your config file, the config file will read properly. However, the combination of a provided config file AND the steps flags you provide in the Pipeline.call() seem to conflict, and the .call(steps()) seems to override the provided config.

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) Do you have any insight on this? Is it intended? (Presumably not, but who knows)

**Comment by jdavies-st** [comment]
Interesting Tyler.  I wonder if `steps` dict is getting overwritten by the kwarg instead of a `dict.update()`?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523052#comment-523052):_

Sarah's expectation is correct and, since the config file has the steps as being skipped, and those parameters are not being set anywhere else, they should be skipped. This is a bug and concur with James that the dict must be getting overwritten somewhere.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523464#comment-523464):_

The issue was located in stpipe/step.py, and I've attempted a PR in that repo. Unit tests to follow (hopefully soon.)

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523664#comment-523664):_

Thanks for hunting this bug down all! Let me know if you need me to test the fix and how I can best do that.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=531728#comment-531728):_

Assigning back to [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) for testing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=556373#comment-556373):_

[Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) Do you know if this was tested in the last round of pipeline testing, and if not, can it be tested as part of the build 7.8 patch testing in the next few weeks?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=521718#comment-521718):_

Hi [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew), could you share the uncal dataset with me?

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=521734#comment-521734):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) are you able to access this link: <http://vospace.esac.esa.int/vospace/sh/4a94b5c553fbf3be40aa11d5f0823048a67f45e6?dl=1> ](http://vospace.esac.esa.int/vospace/sh/4a94b5c553fbf3be40aa11d5f0823048a67f45e6?dl=1)

This is a tar file with the uncal as well as processed exposures for the dataset, using pipeline v0.18.3. Sorry it's in an external location (it's an ESA server though), but I produced this dataset for a colleague in the ESA archives group, and I had to physically go to STScI to get these data uploaded as my home connection is so slow and unstable. I think this link should be publicly accessible.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=521874#comment-521874):_

That worked for me, thanks! I'll get back to you with some results.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=522101#comment-522101):_

Hi [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew), after taking a quick look at this, do you have the .cfg file available that you're using? If I run calwebb_detector1 with 

```bash
strun calwebb_detector1 det_images/miri_imtso_SUB64_60G600I1E_F770Wexp1.fits --steps.firstframe.skip=True --steps.lastframe.skip=True
```

the cal_step outputs in the fits headers have no entry for S_FRSTFR or S_LASTFR. If I run the pipeline with no skip flags set, both header keywords are present and set to 'COMPLETE'.

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=522122#comment-522122):_

I use the file calwebb_tso1.cfg, which reads:

name = "Detector1Pipeline"
class = "jwst.pipeline.Detector1Pipeline"
save_calibrated_ramp = True

[steps]
 [[group_scale]]
 [[dq_init]]
 [[saturation]]
 [[ipc]]
 skip = True
 [[superbias]]
 [[refpix]]
 [[rscd]]
 [[firstframe]]
 skip = True
 [[lastframe]]
 skip = True
 [[linearity]]
 [[dark_current]]
 [[persistence]]
 skip = True
 [[jump]]
 [[ramp_fit]]
 [[gain_scale]]

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=522148#comment-522148):_

Hmm, that's puzzling. When I run the pipeline with this config, I get the same results as if I had specified the skips on the command line, i.e. neither of those cal_step keywords are populated in the _ramp.fits header. I can check doing this procedure in an interactive environment, but can you check your output _ramp.fits and see if the keywords are populated?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523011#comment-523011):_

Hi [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew), just wanted to check in and say that I have a fix for you, but it's not a complete fix and I think this is going a bit over my head. 

If, when you call the pipeline, you add in your step flags in addition to the jump step flag:
```java
steps={"jump": {"rejection_threshold": 10.}, "firstframe": {"skip": True}, "lastframe": {"skip":True}}
```

you should see in the resulting logs that the two steps are appropriately skipped and the cal_step keywords should not exist. 

However, I don't yet have a good answer for why the config file is not being used correctly. I can also tell you that if you move your jump step flag to your config file, the config file will read properly. However, the combination of a provided config file AND the steps flags you provide in the Pipeline.call() seem to conflict, and the .call(steps()) seems to override the provided config.

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) Do you have any insight on this? Is it intended? (Presumably not, but who knows)

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523052#comment-523052):_

Sarah's expectation is correct and, since the config file has the steps as being skipped, and those parameters are not being set anywhere else, they should be skipped. This is a bug and concur with James that the dict must be getting overwritten somewhere.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523464#comment-523464):_

The issue was located in stpipe/step.py, and I've attempted a PR in that repo. Unit tests to follow (hopefully soon.)

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=523664#comment-523664):_

Thanks for hunting this bug down all! Let me know if you need me to test the fix and how I can best do that.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=531725#comment-531725):_

Fixed by spacetelescope/stpipe#22

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=531728#comment-531728):_

Assigning back to [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) for testing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-1940?focusedCommentId=556373#comment-556373):_

[Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) Do you know if this was tested in the last round of pipeline testing, and if not, can it be tested as part of the build 7.8 patch testing in the next few weeks?
