### ISSUE TITLE
NIRSpec MOS bug with 0-sized 2D extractions

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5806]
_Issue [JP-1949](https://jira.stsci.edu/browse/JP-1949) was created on JIRA by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol):_

I've run into a bug processing a simulated MOS exposure.  For this particular case, the spec2 pipeline crashes at the flat_field step because one of the slits has an x-dimension of zero.  Normally, assign_wcs skips any slits for which the bounding box is completely outside the detector, but for some reason that is not happening here.

**Comment by hbushouse** [comment]
Fixed by #5927
