### ISSUE TITLE
Enhance documentation for spectroscopic background subtractions

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5835]
_Issue [JP-1960](https://jira.stsci.edu/browse/JP-1960) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

Given the various different ways of doing background subtraction for different spectroscopic modes, users are often confused as to which method is used for a particular instrument mode and/or observation setup, and in what pipeline (calspec2 or calspec3) the subtraction actually occurs. We need to improve our documentation to try to explain this more clearly.

**Comment by jdavies-st** [comment]
It might be good to have a small table at the beginning of the `master_background` docs

https://jwst-pipeline.readthedocs.io/en/latest/jwst/master_background/description.html

that shows what sort of background subtraction is available in each mode.  This info can be found right now, but sections much further down modify the info given at the beginning, which is confusing.

And these tables needs to be updated

https://jwst-pipeline.readthedocs.io/en/latest/jwst/pipeline/calwebb_spec2.html#calwebb-spec2

and

https://jwst-pipeline.readthedocs.io/en/latest/jwst/pipeline/calwebb_spec3.html#calwebb-spec3

with the correct steps and modes.  Specifically, `master_background` is not listed as a `spec2` step, and NIRSpec MOS is still listed as a mode that gets `master_background` in `spec3`, which is no longer the case.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1960?focusedCommentId=519184#comment-519184):_

Fixed by #5913
