### ISSUE TITLE
0.18.0 ami testing

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5847]
_Issue [JP-1965](https://jira.stsci.edu/browse/JP-1965) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

ami version 0.18.0 updates are in this table: <https://outerspace.stsci.edu/pages/viewpage.action?spaceKey=JPT&title=JP-1948+-<ins>Pipeline+Validation+Test+Epic</ins>-+2021-03-07>

Please test the ami pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Deepashri Thatte](https://jira.stsci.edu/secure/ViewProfile.jspa?name=thatte) on [JIRA](https://jira.stsci.edu/browse/JP-1965?focusedCommentId=518679#comment-518679):_

We need an extension to test AMI3 pipeline. Can we do it by May 30th?

**Comment by hbushouse** [comment]
Closing, because this is an INS testing task and does not involve any github code work.

**Comment by stscijgbot-jp** [comment]
_Comment by [Deepashri Thatte](https://jira.stsci.edu/secure/ViewProfile.jspa?name=thatte) on [JIRA](https://jira.stsci.edu/browse/JP-1965?focusedCommentId=518679#comment-518679):_

We need an extension to test AMI3 pipeline. Can we do it by May 30th?
