### ISSUE TITLE
outlier_detection: removed unused step files?

### ISSUE THREAD

**Issue by karllark** [spacetelescope/jwst#5895]
There are two "step" files that do not look to be used.  They are jwst/outlier_detection/outlier_detection_scaled_step.py and jwst/outlier_detection/outlier_detection_stack_step.py.  The capabilities provided by these two steps are handled as part of the main jwst/outlier_detection/outlier_detection_step.py.  In the interest of long-term maintenance, they could be considered for removal.

I started down the road to do this as part of PR #5822, but fairly quickly realized that this would involve changing a number of files throughout the pipeline and so thought it would be better as a separate PR.  And that it should be checked by someone else that these files are no longer used.

**Comment by braingram** [comment]
Removed in https://github.com/spacetelescope/jwst/pull/8438
