### ISSUE TITLE
source_catalog:  Calculate aperture-corrected total magnitudes for all sources

### ISSUE THREAD

**Issue by larrybradley** [spacetelescope/jwst#5905]
The Photometry WG wants to change the source catalog such that aperture-corrected total fluxes and magnitudes (and errors) are calculated for all sources in the catalog.  Currently, such calculations are performed only for sources where the `is_star` value is `True`.  The rationale is the `is_star` criteria is imperfect.

Because these aperture-corrected total values are only valid for point-sources, documentation will need to be added stating that they should not be used for extended sources.

**Comment by hbushouse** [comment]
@stscijgbot

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2063](https://jira.stsci.edu/browse/JP-2063)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2063?focusedCommentId=524499#comment-524499):_

Fixed by #5996
