### ISSUE TITLE
Missing level 3 products in 00675013

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5912]
_Issue [JP-2014](https://jira.stsci.edu/browse/JP-2014) was created on JIRA by [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp):_

From  James Muzerolle:

For 00675 observation 13, based on the APT file, I would expect the following exposures:  1 set for 2 nods * 2 mosaic tiles, and 1 set for 2 nods * 2 mosaic tiles + 1 wavecal.  It looks like that is the case: 02101_00001,2 + 02103_00001,2 are the former, and 02105_00001,2 + 02107_00001,2,3 are the latter (i.e., the wavecal is 02107_00003, as Mark correctly pointed out).  The two sets correspond to different exposure specifications in APT, so I would not expect them to be associated with one another, which is consistent with the actual association files here.  (Note, this would not be a normal science use case because the selection of a wavecal is either/or, there's no reason to do both. This was presumably done here for testing purposes only.)
 * This observation was targeting a MinAsn test case  for NIRSpec IFU:
 ** dither : yes
 ** mosaic : yes
 ** autocal : yes (wave)
 ** target acq. : yes

No level 3 file was produced.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519334#comment-519334):_

On D2, the spec3 job was running, but probably terminated after over 21 hrs, [jw00675-o013_20210311t152305_spec3_001](https://tljwdmsweb.stsci.edu/owlgui2/logs/directory_view?directory_path=/ifs/archive/test/jwst/test2/info/owl/logs/rspencer_jw00675-o013_20210311t152305_spec3_001_1615492781.899543&fileset_name=jw00675-o013_20210311t152305_spec3_001).

During the run on A-string, using b7.6.4 this job completed with status=0, but no level_3 product was output probably because of the following error
```
2021-01-27 09:14:06,877 - stpipe.Spec3Pipeline.cube_build - ERROR - All the wavelength planes have zero data, check input data
2021-01-27 09:14:15,702 - stpipe.Spec3Pipeline.cube_build - INFO - Update S_REGION to POLYGON ICRS  240.285466896 70.735671832 240.285466896 70.737060721 240.289508478 70.737060721 240.289508478 70.735671832
2021-01-27 09:14:15,708 - CRDS - DEBUG -  Using reference file selection rules 'jwst_0641.pmap' defined by environment CRDS_CONTEXT.
2021-01-27 09:14:15,709 - stpipe.Spec3Pipeline.cube_build - INFO - Step cube_build done
2021-01-27 09:14:15,709 - stpipe.Spec3Pipeline - WARNING - Resampling was not completed. Skipping extract_1d.
2021-01-27 09:14:15,721 - stpipe.Spec3Pipeline - INFO - Ending calwebb_spec3
2021-01-27 09:14:15,721 - stpipe.Spec3Pipeline - INFO - Step Spec3Pipeline done
2021027091426-I-INFO-extracting calibration output filename from log_jw00675-o013_20210126t144129_spec3_001_asn.json.capture_3492672
2021027091426-I-INFO-restoring SDP python env...
SSB python deactivated; OWL python ready for interactive use.
2021027091426-I-INFO-exit status=0 ```
Only the level_2c (crf.fits) files were written
```
2021027091426 INFO src=calibration_output_mgr.run fsn=jw00675-o013_20210126t144129_spec3_001 msg="Calibration input file /ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3/jw00675-o013_20210126t144129_s
pec3_001_asn.json:"
2021027091426 INFO src=calibration_output_mgr.read_cal_output_files fsn=jw00675-o013_20210126t144129_spec3_001 msg="reading cal output files from /ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3/jw006
75-o013_20210126t144129_spec3_001_asn.cal_outputs"
2021027091426 INFO src=calibration_output_mgr.read_cal_output_files fsn=jw00675-o013_20210126t144129_spec3_001 msg="cal output filenames:"
jw00675013001_02101_00001_nrs1_o013_crf.fits
jw00675013001_02101_00001_nrs2_o013_crf.fits
jw00675013001_02101_00002_nrs1_o013_crf.fits
jw00675013001_02101_00002_nrs2_o013_crf.fits
jw00675013001_02103_00001_nrs1_o013_crf.fits
jw00675013001_02103_00001_nrs2_o013_crf.fits
jw00675013001_02103_00002_nrs1_o013_crf.fits
jw00675013001_02103_00002_nrs2_o013_crf.fits
jw00675013001_02105_00001_nrs1_o013_crf.fits
jw00675013001_02105_00001_nrs2_o013_crf.fits
jw00675013001_02105_00002_nrs1_o013_crf.fits
jw00675013001_02105_00002_nrs2_o013_crf.fits
jw00675013001_02107_00001_nrs1_o013_crf.fits
jw00675013001_02107_00001_nrs2_o013_crf.fits
jw00675013001_02107_00002_nrs1_o013_crf.fits
jw00675013001_02107_00002_nrs2_o013_crf.fits
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="initial value for regex: jw00675-o013_t007_nirspec_g235h"
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="applying regex(^jw00675-o013_t007_nirspec_g235h) to full cal output file list"
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="regex on cal output filenames matched: []"
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="No calibration output files found using regex: ^jw00675-o013_t007_nirspec_g235h, but that is
 often ok." ```
A-string logs at /ifs/archive/ops/jwst/info/owl/logs_old/2021/027/owlmgr_jw00675-o013_20210126t144129_spec3_001_1611678193.825821.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519548#comment-519548):_

I can confirm that in the latest B7.7.1 processing results we got the expected total of 18 level-2b "cal" products (16 for the science exposures and 2 wavecal) and the jw00675-o013_20210311t152305_spec3_001_asn.json ASN file does contain the expected 16 science cal products as inputs. So it's highly likely that the level-3 processing just failed or never completed for some reason (NIRSpec IFU cube building with 16 exposures is going to take a loooooong time to run). I'll try processing off-line and see what happens.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519705#comment-519705):_

I've processed these data off-line using the "cal" products from a recent test run on the D-2 string. The calwebb_spec3 processing did finish without crashing or serious error, however:

1) processing ran from 2 Apr 20h30m till 4 Apr 03h50m, so that's a whopping 31.3 hours of processing time

2) The cube_build step ended with the same message seen in the comment above "All the wavelength planes have zero data"

Hence no "s3d" product was created by the cube_build step, which in turn led to the final step of the pipeline, extract_1d, being skipped (because it had no input data to work with). Therefore the only products created after all of that processing were the "crf" (level 2c) products created by the outlier_detection step.

So everything ran more or less as expected, but no level 3 products were created due to lousy input data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519708#comment-519708):_

The reason for this result is the fact that all of the input "cal" products are populated with nothing but zeros in the regions of the IFU slices and NaN's everywhere else. There's not a single non-zero pixel anywhere. Need to investigate how the cal products ended up in that state.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=520101#comment-520101):_

Just an idea and a suspicion, but if background subtraction was done in L2b, and it was done by subtracting one nod from the other, it might have left nothing but zeros since these are of course not real data, and data values for different nods might be indistinguishable from each other?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=520114#comment-520114):_

That's it!!! Of course. I'm so used to thinking of level-2b processing in terms of a single exposure (and that's the way I was doing all my testing, by running just a single exposure through calwebb_spec2) I didn't think about the fact that in an Ops environment they're always processed via an ASN file. And in this case, because the observation involves point-source nods, the calwebb_spec2 background subtraction step is applied. And - as [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) suspected - each exposure has exactly the same dummy pixel values and hence the subtraction gives a zero result. I've confirmed that by processing via a spec2 ASN file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=520421#comment-520421):_

So I'm interested to know the stakeholder's views on this situation and what, if any, changes we might want to make to handle this situation differently. Right now the level 3 pipeline runs without crashing, but does not create the s3d or x1d level-3 products that would be expected from such an observation, due to the fact that the cube_build step has logic in it to abort processing when all of the input data are zero. This should only ever happen due to the use of dummy OTB data and should never happen with real data.

If this were imaging data, or even some form of non-IFU spectroscopy, the level 3 processing would most likely run as normal and simply create level 3 products that are full of zeros. It's only the cube_build step (for IFU data) that has logic in it to abort when the data are all zeros.

Would it be better to change cube_build so that it still creates an s3d product (full of zeros), so that we at least get products into the archive? But again, this is an extreme corner case (waaaaaay in the corner) that should affect our processing of some test observations.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521473#comment-521473):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) do you have a standalone test case with simulated data that we can provide for James to examine?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521483#comment-521483):_

Sure, but there's not much to examine when every image is just full of zeros. And of course as mentioned above there's no level 3 product to examine (it's not created, because the data are all zeros). But I can provide a pointer to level-2a and level-2b data. [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) let me know if you can see files in the directory ███████████████████████████████████████████ That directory has all of the level-2a (rate) products that go into calwebb_spec2 processing and all of the spec2 ASN files needed to do that processing. The ASN files list each science exposure, along with their associated background exposures. It's the process of background subtraction in calwebb_spec2 that results in cal files that are all zero. One example is jw00675013001_02105_00002_nrs2_cal.fits, which is created from processing jw00675-o013_20210311t152305_spec2_001_asn.json. No s3d or x1d product is created, because the cube_build step sees that all of the input planes are zero and aborts, which also causes extract_1d to abort. Same thing happens when running calwebb_spec3 on all of the cal files (combined cube is also all zeros).

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521555#comment-521555):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) I can see the files.  I spot-checked one of the association files, it looks fine.  There is no association file containing the autocal; does that still get processed through spec2?

As for the zeros problem, I'm not sure what to tell you.  How easy/difficult would it be to turn off the check in cube_build?  Or is there any way to insert a different test pattern after the fact?  Of course, real data should never have this problem because there is a source that changes position, and the various noise components, unflagged bad pixels, CR hits, etc, will mean the subtracted result will always be non-zero.

Doesn't nod subtraction with MOS and FS also result in all zeros for OTB test data?  Yet there have been level 3 products generated in those cases; perhaps there is no check in the resample_spec step?

**Comment by jemorrison** [comment]
THe main reason cube_build does not produce an output  for all zero data is because the initial cube built often had extra wavelength planes in the beginning and end of the cube.. We wanted to  trim the IFU cube down to contain the region that had actual data. When all the data is zero this trimming - trims out everything and there is nothing left because it is all zero. We could not allow the trimming to remove all the data and if that occurs then ignore trimming and just write out zero data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521563#comment-521563):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) Yes I'm sure there must be other examples of this same kind of behavior when doing background subtraction using OTB data for other modes, like MIRI LRS, NRS MOS, NRS FS, etc.  It's just that the resample_spec step does not check for all zero data and hence is happy to create s2d files that are all zero. So until someone actually dives into the files to look at the data, it goes unnoticed. It's only cube_build right now that has this hook to abort when all the computed wavelength planes for the cube are zero (of course it only does that **after** having spent an enormous amount of processing time to build the zero-filled cube, and then just drops it on the floor!).

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519334#comment-519334):_

On D2, the spec3 job was running, but probably terminated after over 21 hrs, [jw00675-o013_20210311t152305_spec3_001](https://tljwdmsweb.stsci.edu/owlgui2/logs/directory_view?directory_path=/ifs/archive/test/jwst/test2/info/owl/logs/rspencer_jw00675-o013_20210311t152305_spec3_001_1615492781.899543&fileset_name=jw00675-o013_20210311t152305_spec3_001).

During the run on A-string, using b7.6.4 this job completed with status=0, but no level_3 product was output probably because of the following error
```
2021-01-27 09:14:06,877 - stpipe.Spec3Pipeline.cube_build - ERROR - All the wavelength planes have zero data, check input data
2021-01-27 09:14:15,702 - stpipe.Spec3Pipeline.cube_build - INFO - Update S_REGION to POLYGON ICRS  240.285466896 70.735671832 240.285466896 70.737060721 240.289508478 70.737060721 240.289508478 70.735671832
2021-01-27 09:14:15,708 - CRDS - DEBUG -  Using reference file selection rules 'jwst_0641.pmap' defined by environment CRDS_CONTEXT.
2021-01-27 09:14:15,709 - stpipe.Spec3Pipeline.cube_build - INFO - Step cube_build done
2021-01-27 09:14:15,709 - stpipe.Spec3Pipeline - WARNING - Resampling was not completed. Skipping extract_1d.
2021-01-27 09:14:15,721 - stpipe.Spec3Pipeline - INFO - Ending calwebb_spec3
2021-01-27 09:14:15,721 - stpipe.Spec3Pipeline - INFO - Step Spec3Pipeline done
2021027091426-I-INFO-extracting calibration output filename from log_jw00675-o013_20210126t144129_spec3_001_asn.json.capture_3492672
2021027091426-I-INFO-restoring SDP python env...
SSB python deactivated; OWL python ready for interactive use.
2021027091426-I-INFO-exit status=0 ```
Only the level_2c (crf.fits) files were written
```
2021027091426 INFO src=calibration_output_mgr.run fsn=jw00675-o013_20210126t144129_spec3_001 msg="Calibration input file /ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3/jw00675-o013_20210126t144129_s
pec3_001_asn.json:"
2021027091426 INFO src=calibration_output_mgr.read_cal_output_files fsn=jw00675-o013_20210126t144129_spec3_001 msg="reading cal output files from /ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3/jw006
75-o013_20210126t144129_spec3_001_asn.cal_outputs"
2021027091426 INFO src=calibration_output_mgr.read_cal_output_files fsn=jw00675-o013_20210126t144129_spec3_001 msg="cal output filenames:"
jw00675013001_02101_00001_nrs1_o013_crf.fits
jw00675013001_02101_00001_nrs2_o013_crf.fits
jw00675013001_02101_00002_nrs1_o013_crf.fits
jw00675013001_02101_00002_nrs2_o013_crf.fits
jw00675013001_02103_00001_nrs1_o013_crf.fits
jw00675013001_02103_00001_nrs2_o013_crf.fits
jw00675013001_02103_00002_nrs1_o013_crf.fits
jw00675013001_02103_00002_nrs2_o013_crf.fits
jw00675013001_02105_00001_nrs1_o013_crf.fits
jw00675013001_02105_00001_nrs2_o013_crf.fits
jw00675013001_02105_00002_nrs1_o013_crf.fits
jw00675013001_02105_00002_nrs2_o013_crf.fits
jw00675013001_02107_00001_nrs1_o013_crf.fits
jw00675013001_02107_00001_nrs2_o013_crf.fits
jw00675013001_02107_00002_nrs1_o013_crf.fits
jw00675013001_02107_00002_nrs2_o013_crf.fits
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="initial value for regex: jw00675-o013_t007_nirspec_g235h"
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="applying regex(^jw00675-o013_t007_nirspec_g235h) to full cal output file list"
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="regex on cal output filenames matched: []"
2021027091426-INFO-calib_out_mgr calibration_output_mgr.get_matching_cal_output_files fsn=jw00675-o013_t007_nirspec_g235h msg="No calibration output files found using regex: ^jw00675-o013_t007_nirspec_g235h, but that is
 often ok." ```
A-string logs at /ifs/archive/ops/jwst/info/owl/logs_old/2021/027/owlmgr_jw00675-o013_20210126t144129_spec3_001_1611678193.825821.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519548#comment-519548):_

I can confirm that in the latest B7.7.1 processing results we got the expected total of 18 level-2b "cal" products (16 for the science exposures and 2 wavecal) and the jw00675-o013_20210311t152305_spec3_001_asn.json ASN file does contain the expected 16 science cal products as inputs. So it's highly likely that the level-3 processing just failed or never completed for some reason (NIRSpec IFU cube building with 16 exposures is going to take a loooooong time to run). I'll try processing off-line and see what happens.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519705#comment-519705):_

I've processed these data off-line using the "cal" products from a recent test run on the D-2 string. The calwebb_spec3 processing did finish without crashing or serious error, however:

1) processing ran from 2 Apr 20h30m till 4 Apr 03h50m, so that's a whopping 31.3 hours of processing time

2) The cube_build step ended with the same message seen in the comment above "All the wavelength planes have zero data"

Hence no "s3d" product was created by the cube_build step, which in turn led to the final step of the pipeline, extract_1d, being skipped (because it had no input data to work with). Therefore the only products created after all of that processing were the "crf" (level 2c) products created by the outlier_detection step.

So everything ran more or less as expected, but no level 3 products were created due to lousy input data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=519708#comment-519708):_

The reason for this result is the fact that all of the input "cal" products are populated with nothing but zeros in the regions of the IFU slices and NaN's everywhere else. There's not a single non-zero pixel anywhere. Need to investigate how the cal products ended up in that state.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=520101#comment-520101):_

Just an idea and a suspicion, but if background subtraction was done in L2b, and it was done by subtracting one nod from the other, it might have left nothing but zeros since these are of course not real data, and data values for different nods might be indistinguishable from each other?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=520114#comment-520114):_

That's it!!! Of course. I'm so used to thinking of level-2b processing in terms of a single exposure (and that's the way I was doing all my testing, by running just a single exposure through calwebb_spec2) I didn't think about the fact that in an Ops environment they're always processed via an ASN file. And in this case, because the observation involves point-source nods, the calwebb_spec2 background subtraction step is applied. And - as [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) suspected - each exposure has exactly the same dummy pixel values and hence the subtraction gives a zero result. I've confirmed that by processing via a spec2 ASN file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=520421#comment-520421):_

So I'm interested to know the stakeholder's views on this situation and what, if any, changes we might want to make to handle this situation differently. Right now the level 3 pipeline runs without crashing, but does not create the s3d or x1d level-3 products that would be expected from such an observation, due to the fact that the cube_build step has logic in it to abort processing when all of the input data are zero. This should only ever happen due to the use of dummy OTB data and should never happen with real data.

If this were imaging data, or even some form of non-IFU spectroscopy, the level 3 processing would most likely run as normal and simply create level 3 products that are full of zeros. It's only the cube_build step (for IFU data) that has logic in it to abort when the data are all zeros.

Would it be better to change cube_build so that it still creates an s3d product (full of zeros), so that we at least get products into the archive? But again, this is an extreme corner case (waaaaaay in the corner) that should affect our processing of some test observations.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521473#comment-521473):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) do you have a standalone test case with simulated data that we can provide for James to examine?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521483#comment-521483):_

Sure, but there's not much to examine when every image is just full of zeros. And of course as mentioned above there's no level 3 product to examine (it's not created, because the data are all zeros). But I can provide a pointer to level-2a and level-2b data. [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) let me know if you can see files in the directory ███████████████████████████████████████████ That directory has all of the level-2a (rate) products that go into calwebb_spec2 processing and all of the spec2 ASN files needed to do that processing. The ASN files list each science exposure, along with their associated background exposures. It's the process of background subtraction in calwebb_spec2 that results in cal files that are all zero. One example is jw00675013001_02105_00002_nrs2_cal.fits, which is created from processing jw00675-o013_20210311t152305_spec2_001_asn.json. No s3d or x1d product is created, because the cube_build step sees that all of the input planes are zero and aborts, which also causes extract_1d to abort. Same thing happens when running calwebb_spec3 on all of the cal files (combined cube is also all zeros).

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521555#comment-521555):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) I can see the files.  I spot-checked one of the association files, it looks fine.  There is no association file containing the autocal; does that still get processed through spec2?

As for the zeros problem, I'm not sure what to tell you.  How easy/difficult would it be to turn off the check in cube_build?  Or is there any way to insert a different test pattern after the fact?  Of course, real data should never have this problem because there is a source that changes position, and the various noise components, unflagged bad pixels, CR hits, etc, will mean the subtracted result will always be non-zero.

Doesn't nod subtraction with MOS and FS also result in all zeros for OTB test data?  Yet there have been level 3 products generated in those cases; perhaps there is no check in the resample_spec step?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=521563#comment-521563):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) Yes I'm sure there must be other examples of this same kind of behavior when doing background subtraction using OTB data for other modes, like MIRI LRS, NRS MOS, NRS FS, etc.  It's just that the resample_spec step does not check for all zero data and hence is happy to create s2d files that are all zero. So until someone actually dives into the files to look at the data, it goes unnoticed. It's only cube_build right now that has this hook to abort when all the computed wavelength planes for the cube are zero (of course it only does that **after** having spent an enormous amount of processing time to build the zero-filled cube, and then just drops it on the floor!).

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2014?focusedCommentId=690103#comment-690103):_

No longer relevant given changes to cube build since this time, closing.
