### ISSUE TITLE
Spherical-geometry and numpy dependencies for v1.1.0

### ISSUE THREAD

**Issue by micaelabagley** [spacetelescope/jwst#5924]
I'm having problems installing v1.1.0 on Ubuntu (18.04), related to building spherical-geometry and, when downgrading to fix that, numpy dependencies.

Installing using:
`conda create -n jwstv1 python`
`conda activate jwstv1`
`pip install jwst`
results in a problem building `spherical-grometry`:
> ERROR: Could not build wheels for spherical-geometry which use PEP 517 and cannot be installed directly

Installing spherical-geometry from github also failed, both with and without `--no-use-pep517`. This might be a problem with Debian specifically? I also tried upgrading pip, setuptools, and wheel, but no luck. Spherical-geometry exists on the astroconda channel, but requires a lower version of python:

>   - spherical-geometry -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
> Your python: python=3.9

However, installing `jwst` using python 3.7.x results in a numpy ImportError as with #5744 :

> ImportError: numpy.core.multiarray failed to import

when importing tblot from drizzle.cdrizzle. Numpy v1.19.2 comes with this installation process (python 3.7). Upgrading numpy will then work as with #5744:  
`pip install --no-cache-dir numpy==1.20.0`

So it seems that upgrading numpy is still required after pip installing jwst, as it doesn't install the latest version of numpy (perhaps because I'm using python 3.7).

**Comment by jdavies-st** [comment]
Hi Micaela, thanks for the report.

We do our daily CI unit testing on Ubuntu 20.04 which runs on as a VM via Github actions with the following specs:

https://github.com/actions/virtual-environments/blob/ubuntu20/20210330.1/images/linux/Ubuntu2004-README.md

So I don't think it is Debian issue.

And our nightly testing on Red Hat Enterprise Linux 7.

Could you report the full stack trace of the issue with `spherical-geometry` so we can see why it is not compiling?

Thanks.

**Comment by jdavies-st** [comment]
I'll add that we also unit test `sphericial-geometry` weekly as well, and we have not seen errors there.

https://github.com/spacetelescope/spherical_geometry/actions/runs/696826686

though again, this build runs on Ubuntu 20.04.  🤔

**Comment by micaelabagley** [comment]
Hi James, 
Here's the part relevant to spherical-geometry (all of the other builds were successful):

```
Building wheel for spherical-geometry (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/micaela/software/anaconda3/envs/jwstv1/bin/python /home/micaela/software/anaconda3/envs/jwstv1/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmph9mzl3oo
       cwd: /tmp/pip-install-v8swus7j/spherical-geometry_42a00e08e01f4270844f19b012188467
  Complete output (39 lines):
  /tmp/pip-build-env-ve0q_0ks/overlay/lib/python3.9/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
    warnings.warn(
  /tmp/pip-build-env-ve0q_0ks/overlay/lib/python3.9/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'show-response' will not be supported in future versions. Please use the underscore name 'show_response' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/spherical_geometry
  copying spherical_geometry/polygon.py -> build/lib.linux-x86_64-3.9/spherical_geometry
  copying spherical_geometry/__init__.py -> build/lib.linux-x86_64-3.9/spherical_geometry
  copying spherical_geometry/vector.py -> build/lib.linux-x86_64-3.9/spherical_geometry
  copying spherical_geometry/graph.py -> build/lib.linux-x86_64-3.9/spherical_geometry
  copying spherical_geometry/great_circle_arc.py -> build/lib.linux-x86_64-3.9/spherical_geometry
  creating build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/test_util.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/test_shared.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/__init__.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/test_intersection.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/setup_package.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/benchmarks.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/test_union.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  copying spherical_geometry/tests/test_basic.py -> build/lib.linux-x86_64-3.9/spherical_geometry/tests
  creating build/lib.linux-x86_64-3.9/spherical_geometry/utils
  copying spherical_geometry/utils/__init__.py -> build/lib.linux-x86_64-3.9/spherical_geometry/utils
  creating build/lib.linux-x86_64-3.9/spherical_geometry/utils/compat
  copying spherical_geometry/utils/compat/weakref.py -> build/lib.linux-x86_64-3.9/spherical_geometry/utils/compat
  copying spherical_geometry/utils/compat/__init__.py -> build/lib.linux-x86_64-3.9/spherical_geometry/utils/compat
  copying spherical_geometry/utils/compat/weakrefset.py -> build/lib.linux-x86_64-3.9/spherical_geometry/utils/compat
  running build_ext
  building 'spherical_geometry.math_util' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/libqd
  creating build/temp.linux-x86_64-3.9/libqd/src
  creating build/temp.linux-x86_64-3.9/src
  gcc -pthread -B /home/micaela/software/anaconda3/envs/jwstv1/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/micaela/software/anaconda3/envs/jwstv1/include -fno-semantic-interposition -fPIC -O2 -isystem /home/micaela/software/anaconda3/envs/jwstv1/include -fno-semantic-interposition -fPIC -I/tmp/pip-build-env-ve0q_0ks/overlay/lib/python3.9/site-packages/numpy/core/include -Isrc -Ilibqd/include -I/home/micaela/software/anaconda3/envs/jwstv1/include/python3.9 -c libqd/src/bits.cpp -o build/temp.linux-x86_64-3.9/libqd/src/bits.o
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for spherical-geometry
```

Is this a compiler version issue? 

Thanks!

**Comment by jdavies-st** [comment]
Ah, `cc1plus` is the underlying executable that needs to be run to actually compile C++ code.  So your system does not have the `gcc` compiler set up right.  That's solvable I believe:

```
sudo apt-get install --reinstall build-essential
```

Which should pull everything to compile C/C++ code.

Let us know if that fixes it.

**Comment by micaelabagley** [comment]
That fixed it! I had to do some extra updates for matplotlib (including PyQt5) but it seems to all be working now. Thank you for your help!

**Comment by jdavies-st** [comment]
Great!  Glad things are working.
