### ISSUE TITLE
Add instructions for contributing tests 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5975]
_Issue [JP-2052](https://jira.stsci.edu/browse/JP-2052) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

INS would like to contribute some of their tests as pass/fail tests, along with test data, to be run as part of the regular test suite. It would be helpful to have instructions for how to do this, e.g.:
 # Where/how to submit test data
 # What do pass/fail test formats need to look like to be integrated into the test suite for the repo 
 # What is the process for submitting new tests

**Comment by jdavies-st** [comment]
This is mostly documented on the repo WIKI.  Tests are written using the normal `pytest` framework with simple `assert` statements.

If the tests need input data, then they need to be regression tests.  All regression tests are corralled in `jwst/regtest` and there are many examples there.  General info to get started about where to store data and how to read it into a regression test:

https://github.com/spacetelescope/jwst/wiki/Writing-regression-tests

https://github.com/spacetelescope/jwst/wiki/Maintaining-Regression-Tests

If no input test data is needed (or if the data can be generated on-the-fly), then they can be written as unit tests and placed in the submodule which are being tested.  Again, look at existing tests in the `jwst/<submodule>/tests` directories.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2052?focusedCommentId=522560#comment-522560):_

Ah thanks! I was poking around but didn't see this information, I just saw the page for maintaining the tests for some reason. I'll circulate it to INS and close this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2052?focusedCommentId=530628#comment-530628):_

Docs exist already, closing this issue
