### ISSUE TITLE
BUNIT -> astropy.units.Unit

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#5990]
Do you have a helper function to convert `BUNIT` to a valid `astropy.units.Unit`? For HST, there is no such thing and often I have to code in special rules to translate the units. But it doesn't have to be this way for JWST.

Here's an example from HST DRZ: `'ELECTRONS/S'` (I have to change it to `'electron/s'` for `astropy` to understand.)

**Comment by jdavies-st** [comment]
We don't, as we don't use `astropy.units` in the `jwst` pipeline.  But we probably should.

I would expect something like:

```python
from jwst import datamodels
import astropy.units as u


with datamodels.open("file.fits") as model:
    data = model.data * u.Unit(model.meta.bunit_data)
    err = model.err * u.Unit(model.meta.bunit_err)
```

would work, assuming `astropy.units` can parse and understand the text in bunit.

**Comment by nden** [comment]
Some more Info before I close the issue - until recently asdf was not serializing non-VO units, e.g. `e/s`. The pipeline can work with both ASDF and FITS formats so in principle it's possible now to use units. However, it's unlikely we'll change this soon. The best way forward is to write a custom function.
