### ISSUE TITLE
datamodels.open improperly handle pathlib.Path objects

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6054]
_Issue [JP-2091](https://jira.stsci.edu/browse/JP-2091) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

`datamodels.open` improperly handle `pathlib.Path` objects as demonstrated below:

`>>> from pathlib import Path`
`>>> from jwst import datamodels`
`>>> image_model = datamodels.ImageModel((50, 50))`
`>>> print(image_model)`
`<ImageModel(50, 50)>`
`>>> image_model.save('image_model.fits')`
`'image_model.fits'`
`>>> image_model_path = Path('image_model.fits')`
`>>> from_path = datamodels.open(image_model_path)`
`>>> print(from_path)`
`<JwstDataModel from image_model.fits>`
`>>> from_str = datamodels.open(str(image_model_path))`
`>>> print(from_str)`
`<ImageModel(50, 50) from image_model.fits>`

**Comment by jdavies-st** [comment]
Yeah, we've never implemented `pathlib` handling consistently.

Isn't there a test for this case here?

https://github.com/spacetelescope/jwst/pull/5345

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2091?focusedCommentId=531743#comment-531743):_

[James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) It looks like that test was removed and ported to stdatamodels, though I don't fully comprehend where tmp_path is initialized as a PurePath object. Should a version testing a jwst-specific datamodel remain in test_models?

The test as written there will still pass, because instead of datamodels.open(), it's using ImageModel() to open the Path object. I should change this and add it back once fixed, perhaps?

**Comment by jdavies-st** [comment]
Tyler it looks like the bug seen above in @stscieisenhamer's bug report is that `datamodels.open()` opens the written out `ImageModel` as a generic `JwstDataModel` instead of as the correct `ImageModel` type.  And it looks like you've added exactly that test to your PR.  👍 

My comment above about our tests are that we do have some tests that test aspects of this, but clearly not this buggy case.

Shortest path to success!  🚀

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2091?focusedCommentId=538882#comment-538882):_

Fixed in #6130
