### ISSUE TITLE
Refactor jwst.transforms schemas to use the ASDF Converter framework

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6057]
_Issue [JP-2092](https://jira.stsci.edu/browse/JP-2092) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2092?focusedCommentId=561428#comment-561428):_

#6205

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2092?focusedCommentId=562327#comment-562327):_

Fixed by #6205

**Comment by pllim** [comment]
xref pytest-dev/pytest#9169

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2092?focusedCommentId=561428#comment-561428):_

#6205

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2092?focusedCommentId=562327#comment-562327):_

Fixed by #6205
