### ISSUE TITLE
Use stcal/jump in jwst/jump

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6059]
_Issue [JP-2093](https://jira.stsci.edu/browse/JP-2093) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Review spacetelescope/stcal#23

Once it is approved and merged, make changes to jwst/jump to call the code in stcal.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) on [JIRA](https://jira.stsci.edu/browse/JP-2093?focusedCommentId=529225#comment-529225):_

This is analogous to RCAL-81 ("Develop jump detection code for Roman WFI data")

**Comment by pubghiter** [comment]
I am makeing game but I don't know lot of c++ can you help me ????

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2093?focusedCommentId=543377#comment-543377):_

PR: #6089
