### ISSUE TITLE
Move computationally intensive portion of cube build to C or use numba(stage 2 of cube_build improvements)

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6064]
_Issue [JP-2096](https://jira.stsci.edu/browse/JP-2096) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

Move the module cube_cloud.py (match_det2cube_msm) to a c++ routine.

This is stage 2 of a improving the efficiency of cube_build. Stage 1 was JP-364. 

This ticket will also include investigating  moving map_fov_to_dqplane to a c++ routine. 

 

JP-2015 can follow after this ticket is complete.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=530097#comment-530097):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)

A timing and profiling was done on the code to point out the modules that take the most time. These modules were adapted to use 'numba' to speed up processing. I had to pip install numba. 

Using a 4 channel 1/2 MIRI exposures and creating a cube that would encompass all the data (it will be non-linear) the time went from

768 seconds (12.8 minutes)

192 seconds (3.2 minutes) - using numba (so ~ 4 times faster)



After a small learning curving using numba it was fairly straight forward on the changes need in the code to support numba. Numba works with numpy arrays but not all the functionally in numpy is allowed in numba
So some modifications of the code was necessary.  Also modules that were part of a class had to be moved out of the class. As I understand it, numba - does not know what to do with 'self' in a class. 

I hope we can add numba to the JWST Pipeline. It was a quick way to make the code run faster

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=530192#comment-530192):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Fantastic, that sounds like a really useful gain!  Is there a branch that I can try out?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=530207#comment-530207):_

I am finishing up some clean up and folding my the changes for building normal IFU cubes and the 'single" type used for outlier detection. I should have a cleaned up branch that I will put on GitHub this weekend.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=530546#comment-530546):_

#6093

 

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) try using the above PR to test using cube_build with numba

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=530676#comment-530676):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) That's awesome!  Runtime for building a 4-pt dithered cube drops from 5 min to 1 min, and outlier_detection drops from 11 min to 6 min.  That's an incredibly useful gain.

I'm seeing some strange crashes when running cube build as part of the spec2 pipeline though; processing a _cal.fits file through cube build works fine, but if I run the spec2 pipeline on a _rate.fits file then cube building crashes with:
```java
2021-06-02 15:07:10,444 - stpipe.Spec2Pipeline.cube_build - WARNING - /Users/dlaw/anaconda3/envs/jwst/lib/python3.9/site-packages/numba/core/ir_utils.py:2119: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'rois_table' of function 'find_closest_wave'.For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-typesFile "../../../../jwcode/jwst/jwst/cube_build/cube_cloud.py", line 14:
@jit(nopython=True)
def find_closest_wave(iw,w,
^warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))```
`Strangely I don't get that message when running cube_build directly though.`

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=531596#comment-531596):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) I fixed the problem. Numba does not have all functions using list enabled. I have been converting lists to numpy arrays.  rois_table  was getting converted to a list when working with a single file. I fixed that and it runs now.

I am going to test the 'internal cal" options now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=531613#comment-531613):_

This PR is ready for review. I worked out how to get the regression tests to work with numba code. I just needed to add the following 2 lines to the code that I am using numba with

log = logging.getLogger('numba')

log.setLevel(logging.WARNING) 

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) You asked about the cons of using numba. Though I am not an expert  here is  what I have found
 # Numba does not have all the numpy and python functions enabled. For example, numba does not work will with lists. I converted all the list to numpy arrays for variables that are used in the numba routines. Numba also does not work well with strings. I just removed strings- I really did not need them for the routines I used numba for
 # At first it is a little tricky to understand the errors that are returned. But after much googling you can figure out what the error means. It is a learning curve and once you understand how numba is working it makes more sense
 # You can not use ipython with numba. So if you want to interact with the code you have to commit out the declaration @⁣jit(nopython=True). But that is all you have to do to "turn numba off". Very simple. 

 # On the LLVM dependency - this is getting over my head.  I did not have to do anything to make numba work except pip install numba. After some googling I think this concern is a worry of the past -LLVM  is widely used and stable. But others more experienced than me might want to do follow up research before it is used in the JWST Pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=531646#comment-531646):_

Great, thanks [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) .  Now that it works as called from Spec2 I reran my Spec2+Spec3 example notebook processing a 4-pt dithered data set in a single band.  Total runtime (cumulative) is as follows:

 
||Stage||Time Original (s)||Time New (s)||
|Detector1| 125|134|
|Spec2| 2234| 659|
|Spec3| 5548| 1716|

That's an important difference, knocking about 70% off of the overall pipeline runtime.  I'd be strongly in favor of merging this PR if everyone else is happy with introducing the numba dependency.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=531915#comment-531915):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) as I have gone through the code to clean it up as much as possible I wonder if we need to set all the various ctype1 and ctype2 for MIRI data when coord_system = 'internal_cal'

For these types of cubes for NIRSPEC we only set

ctype1 = NRSSLICERX

ctype2 = NRSSLICERy

We could do this for MIRI internal cal

ctype1 = MRSALPHA

ctype2 = MRSBETA
the channel and band  for these cubes are in the header. 
Just a thought. Back when we made up internal_cal type cubes for MIRI I think we thought we needed something detailed -  I am not sure if we really need that. It might just. be a bit confusing now.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=531984#comment-531984):_

I think that's reasonable, let's do it.  These cubes are really only for engineering utility, and I don't see any practical problems with doing so.  Strictly MRSALPHA is not unique as it can mean different things, but together with other metadata there would be no loss of information.  Looks like this would shorten over 100 lines of code to just 2.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=535454#comment-535454):_

[Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva)

I wrote a c wrapper (I have not put the c code in the routine yet) I want to see if I have to python to c wrapper correct. The routine is called match_det_cube.c it is called from ifu_cube.py. I pushed this up to my github:

<https://github.com/jemorrison/jwst/tree/cube_build_stage3/jwst/cube_build>

 

[Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) When you have time could look this over. I also have a few questionsfor you - so if you have time

later today or early next week I could set up a web-ex and I could ask you some details about this process.

also do I need to add to the setup.py (this c routine) so it will compile.
Would it be this:
setup(
 use_scm_version=True,
 setup_requires=["setuptools_scm"],
 scripts=scripts,
 packages=find_packages(),
 package_data=package_data,
 ext_modules=[
 Extension(
 'jwst.lib.winclip',
 ['jwst/lib/src/winclip.c'],
'jwst.cube_build.match_det_cube',
['jwst/cube_build/match_det_cube.c'],
include_dirs=include_dirs,
define_macros=define_macros

)
 ],
)

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=535482#comment-535482):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Yes, you need to add an extension in setup.py. What you showed above seems correct to me. [Although, it used to be customary to put C code in  a separate directory such as 'src' but I think it should be OK to leave it as is].

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=535492#comment-535492):_

@⁣mihia - I figured out how to compile the code using the winclip example

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=536480#comment-536480):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva)

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)

[James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) 

So far I have converted the 2 computationally intensive routines in cube_build to c.  One routine determines the overlap between the point cloud element and the IFU cube spaniels and the other routine sets the initial dq plane. This second routine includes a number of other routines that had to be convert to c. I am still improving the c routine for setting the dq plane for NIRSPEC. 

MIRI test results used 12 files that covered the 12 band. I ran cube build and created 12 different IFU cubes.

Original python code: took 27.6 minutes
Numba code: 7.0 minutes
C code: 1 min, 20 seconds **** a winner

 

For NIRSPec the timing improvements are not as good. For NIRSPEC I took 12 dithered prism files.
The limiting factor is  the code assign_wcs.nirspec nrs_wcs_set_input takes about 1 minute per file. For all 12 files that is 12 minutes. I can not get under that  time with my improvements

Original python code: 29.5 minutes

Numba code: 18.2 minutes
C code: 16.7 minutes.

I think with improvements to c code in setting the dq plane I can get the c code to run faster (but I will not get it under 12 minutes because of mrs_wcs_set_input.

But the conclusion is the c code is the way to go.  I have follow up questions  on the c library that I will ask [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) and [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) in a follow up email.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=536491#comment-536491):_

Just a quick note:

>Original python code: took 27.6 minutes
>Numba code: 7.0 minutes
>C code: 1 min, 20 seconds **** a winner

Absolutely fantastic, that's AWESOME, way to go [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) !

**Comment by jdavies-st** [comment]
That is fantastic Jane!  Clearly we have a winner.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=536572#comment-536572):_

We are working on speeding up the Nirspec WCS. This requires restructuring of code in astropy.modeling and implementing a "compound" bounding box - a bounding box that stores individual bounding boxes for each slice. Once implemented it will eliminate the need to call nrs_wcs_set_input.

Thanks for all the work on the comparison, Jane!

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=539188#comment-539188):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) I have moved the computational code into a few c extensions. Do you want to keep 'msm' as a weighting option ? It seemed 'emsm' worked better and after I get merge this PR we can tackle the 3-D drizzling so I was not sure if 'msm' was still useful.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=539369#comment-539369):_

I'm inclined to keep MSM for the time being; I think EMSM is probably better, but I'm inclined to keep it until we can determine whether or not to retire it based on performance on flight data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=546946#comment-546946):_

B7.8.2 justification:

1) Why do we need it? Dramatically decreases processing time for NIRSpec and MIRI IFU data in the level-3 cube building step.
2) What does it fix? IFU data are notoriously slow to process, especially in the level-3 stages that perform 3D cube building. These changes speed up the process by factors of 10-30x.
3) What happens if we don't include it in B7.8.2? Turn-around time for IFU observations both within the operational pipeline and in off-line use by instrument scientists will be painfully slow and increase the wait time for results, thus hampering analysis efforts.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2096?focusedCommentId=549651#comment-549651):_

For the record, testing of this update, along with the updates to blotting in JP-2207, for MRS data from program 684, obs 006, consisting of 4 input exposures from the IFUSHORT detector only, leads to the following results for calwebb_spec3 processing times using B7.8.1 (before this fix) and B7.8.2 (after this fix):

B7.8.1: 26 mins, 4 secs processing time (26.1 min)
B7.8.2: 4 mins, 47 secs processing time (4.8 min)

for a speed-up of ~5.4x.

Relevant processing logs (as proof) are attached.
[^log_b781.txt]  [^log_b782.txt]
