### ISSUE TITLE
Move transforms and datamodels to standalone package(s)

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6097]
_Issue [JP-2114](https://jira.stsci.edu/browse/JP-2114) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Move jwst.transforms and jwst.datamodels to standalone packages to facilitate reading of JWST data without installing multiple pipelinne dependencies.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2114?focusedCommentId=564647#comment-564647):_

Hasn't this been done already, or only partially?

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2114?focusedCommentId=564680#comment-564680):_

This is not completed. I'll look into it this quarter.

**Comment by nden** [comment]
Done!

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2114?focusedCommentId=564647#comment-564647):_

Hasn't this been done already, or only partially?

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2114?focusedCommentId=564680#comment-564680):_

This is not completed. I'll look into it this quarter.

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2114?focusedCommentId=626484#comment-626484):_

JP-3076 is handling the movement of jwst.datamodels. I will use this ticket to track the movement of jwst.transforms.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2114?focusedCommentId=629009#comment-629009):_

Fixed by #7441
