### ISSUE TITLE
WCS error in resample for image2 run of VISITYPE='PRIME_TARGETED_MOVING'

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6111]
_Issue [JP-2126](https://jira.stsci.edu/browse/JP-2126) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

During calwebb_image2 run of jw00634045001_02102_00003_nrcb1_rate.fits with VISITYPE='PRIME_TARGETED_MOVING', [SUBARRAY]': 'SUB400P', error creating output wcs for resample step:
```python
2021-05-30 13:12:50,698 - CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_nircam_drizpars_0001.fits'
2021-05-30 13:12:50,699 - stpipe.Image2Pipeline.resample - INFO - Drizpars reference file: /ifs/archive/test/jwst/ref/tmp_crds/cache/references/jwst/nircam/jwst_nircam_drizpars_0001.fits
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image2Pipeline':
    unsupported operand type(s) for +: 'NoneType' and 'int'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_image2.py", line 66, in process
    result = self.process_exposure_product(
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_image2.py", line 161, in process_exposure_product
    self.resample(input)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/resample/resample_step.py", line 78, in process
    resamp = resample.ResampleData(input_models, **kwargs)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/resample/resample.py", line 72, in __init__
    self.output_wcs = resample_utils.make_output_wcs(self.input_models,
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/resample/resample_utils.py", line 44, in make_output_wcs
    output_wcs = wcs_from_footprints(input_models, pscale_ratio=pscale_ratio)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/assign_wcs/util.py", line 253, in wcs_from_footprints
    wcsinfo = pointing.wcsinfo_from_model(refmodel)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/assign_wcs/pointing.py", line 106, in wcsinfo_from_model
    for ax in range(1, wcsaxes + 1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

```

**Comment by jdavies-st** [comment]
It looks like the input subarray data is missing the WCSAXES keyword. This should be populated in all data by the Sci Ops PRD.  So a problem with the database used by SDP in the creation of the uncal file?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=531328#comment-531328):_

This looks like it is related to the other Moving Target issues with set_telescope_pointing.  Linking to the other issue, #&#x2060;6110 / JP-2125.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=531700#comment-531700):_

Can we find the level-1 processing log to confirm whether this also had problems due to MT table column names mismatch? Given that the target type is MOVING, I suspect that's the case, but should confirm.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=531722#comment-531722):_

looking into it...

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=531737#comment-531737):_

Attached the actual log and below was Mike's original comment. Will be investigating further.

> /ifs/archive/test/jwst/test2/info/owl/logs/mswam_jw00634045001_02102_00003_nrcb3_1622380050.471018/ALOG_1622380082_level_1_jw00634045001_02102_00003_nrcb3.err This case fails Level1 during calc_wcs_over_time_wrapper.py (called for MOVING TARGETs), specifically during the set_telescope_pointing.py invocation. Apparently APERNAME=UNKNOWN is not handled by this code, though I suspect the failure cases are for detectors that should NOT be read out anyway (NRCB[234] fail, NRCB1 is fine). SDP should figure out how this is failing and try to assign default values so that Level1 can complete, if possible.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=531761#comment-531761):_

There's not really much that can be done when APERNAME='UNKNOWN'. Pointing could be set to the Target coords (TARG_RA, TARG_DEC), but we still don't know where the target is located in the V2/V3 plane without knowing an aperture and hence we don't know a pixel location to assign TARG_RA/TARG_DEC to.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=535410#comment-535410):_

I'm really confused. Neither exposure referenced above (jw00634045001_02102_00003_nrcb1, jw00634045001_02102_00003_nrcb3) failed in LEVEL_2A processing in the SIR3 run around May 30th.

jw00634045001_02102_00003_nrcb1 run successfully through LEVEL_2A.

jw00634045001_02102_00003_nrcb3 failed LEVEL_1 and did NOT attempt LEVEL_2A processing because the APERNAME NRCB3_SUB400P could not be  found in the PRD SIAF. SDP changed it to UNKNOWN whereupon the wcs code raised an exception that LEVEL_1 processing caught and proceeded to exit with status 1. Processing for this exposure then stopped and did not proceed to LEVEL_2A.

Perhaps the calwebb_image2 failure was for a different exposure?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=535433#comment-535433):_

calwebb_image2 is LEVEL_2*B* processing. Problems with WCS-related info, like APERNAME, won't cause failures in LEVEL_2A. because WCS info is not needed by any of the LEVEL_2A steps. The failures occur in steps like assign_wcs and resample in LEVEL_2B processing (calwebb_image2, calwebb_spec2).

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=535439#comment-535439):_

I'm still confused. You reported the problem for the nrcb1 exposure. The attached log is for the nrcb3 exposure, so it's not relevant.

It appears that nrcb1 level 1 processing proceeded like it was supposed to, but I'll go have a closer look and look at the uncal FITS file itself to verify.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=535449#comment-535449):_

Yes, I confused the level 1 issue with NRCB3 with this issue concerning NRCB1. I will remove the errant log.

There is no resolution, yet, on this issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=538879#comment-538879):_

If there's no resolution yet on this issue, why is the workflow set to "Ready for Testing"? Does it need to be set back to Open or In Progress?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=538890#comment-538890):_

should be back to open. sorry, i didn't change it when realizing the confusion.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=559734#comment-559734):_

Since SUB400P was used only the nrcb1 and nrcblong SCAs will succeed. All others (nrcb2, nrcb3, nrcb4) will fail at L1 due to APERNAME = UNKNOWN. See !https://jira.stsci.edu/secure/viewavatar?size=xsmall&avatarId=13010&avatarType=issuetype! JSOCINT-547.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=560563#comment-560563):_

From [JSDP-2053](https://jira.stsci.edu/browse/JSDP-2053), a re-run of SIR3_OTB including the SSR files that had gone missing for a few months shows a successful output of Stage 2 processing for  jw00634045001_02102_00003_nrcb1, found in:

```python
/ifs/archive/test/jwst/store/rspencer/tests/SIR3_OTB/dtest2/JWSTDP-2022.1.0-22~06dd61d2/2021-11-22-180715/sdp/archive/level2b
```

This can be closed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2126?focusedCommentId=560614#comment-560614):_

Error no longer reproducible - SIR3_OTB runs to completion for this exposure.
