### ISSUE TITLE
Multiprocessing for ramp fitting doesn't return the same data as single processing

### ISSUE THREAD

**Issue by kmacdonald-stsci** [spacetelescope/jwst#6143]
While doing analysis for JP-1926 I discovered differences in output depending on whether or not the data went through single processing or multiprocessing.  

I ran the code snippet described in JP-1926 to recreated the bug detailed in that issue.  Running the pipeline I created file

NRCNRCA1-DARK-60011933591_1_481_SE_2016-01-01T20h04m44_level1b_Sept2018_jump.fits

For this file in ramp fitting the pipeline identified the following reference files needed for ramp fitting:

crds_cache/references/jwst/nircam/jwst_nircam_readnoise_0025.fits

and

crds_cache/references/jwst/nircam/jwst_nircam_gain_0050.fits

to test the ramp fitting code on.  I created a test script that ran

    slopes, cube_model = RampFitStep.call(
        ramp,
        override_gain=gain,
        override_readnoise=rnoise,
        output_dir=odir,
        save_results=True,
        save_opt=False,
        maximum_cores=cores,
    )

where `cores="none"` and `cores="half"`.  I ran this on the latest version of JWST and the 1.1.0 release.  The resultant output FITS files are different in the computation of the VAR_POISSON arrays, which results in a difference for the ERR array.  

The multiprocessing code simply slices the input ramp data by row in the image according to the number of processors requested (8 on my machine with "half").  Each slice is then run through the same code that single processing is, then the sliced outputs are reassembled into a single data product.  Roughly 30% of the VAR_POISSON (and ERR) pixels are different, with large differences, which can be found using `fitsdiff` on the output file from the single processor test and multi processor test.

**Comment by nden** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2139](https://jira.stsci.edu/browse/JP-2139)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2139?focusedCommentId=534843#comment-534843):_

If the only differences are on the VAR POISSON, then I would look at the where those values are moved from slices to the full array.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2139](https://jira.stsci.edu/browse/JP-2139)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2139?focusedCommentId=534843#comment-534843):_

If the only differences are on the VAR POISSON, then I would look at the where those values are moved from slices to the full array.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2139?focusedCommentId=686376#comment-686376):_

Is this ticket stale and/or duplicated and resolved by JP-3521?

**Comment by stscijgbot-jp** [comment]
_Comment by [Kenneth MacDonald](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmacdonald) on [JIRA](https://jira.stsci.edu/browse/JP-2139?focusedCommentId=686377#comment-686377):_

This has been resolved.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2139?focusedCommentId=689163#comment-689163):_

Resolved, in connection with JP-3521
