### ISSUE TITLE
Test against astropy 4.3rc1

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#6169]
Better catch any incompatibility before it is officially released. The risk is low if you already test against dev, but still you want to make sure the packaged code (not installing from source) works as expected.

https://github.com/astropy/astropy/wiki/v4.3-RC-testing

**Comment by pllim** [comment]
`astropy` has decided that RC2 is not necessary.

**Comment by jdavies-st** [comment]
Tested against 4.3rc1 and things look good.

https://plwishmaster.stsci.edu:8081/job/RT/job/jdavies-dev/261

**Comment by pllim** [comment]
Awesome. Thanks!
