### ISSUE TITLE
Investigate Numba performance for the case of stsci.imagestats

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6172]
_Issue [JP-2168](https://jira.stsci.edu/browse/JP-2168) was created on JIRA by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara):_

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-2168?focusedCommentId=535417#comment-535417):_

A couple of interesting, albeit some old, articles/links:

 

<https://murillogroupmsu.com/numba-versus-c/>

<https://lewiscoleblog.com/cython-numba>

 

I will attach a notebook that I used for comparing performance of Python, Numba, and C code. In general I am getting that Numba  performance for this particular algorithm is comparable to C. The first time the function is called - the run time is longer. This could be an issue in the pipeline if a specific code that one wants to accelerate is run only once. Then every time a script is run, Numba (I think) will have to compile the code all over again. In this case Cython would be faster than Numba.

**Comment by jemorrison** [comment]
Your summary is consistent with what I found reviewing how to use numba. If you are only calling the once or twice then it not a good case for numba, but if the code is called many times then it would be.
