### ISSUE TITLE
NRC engineering subarray exposures failing in calwebb_tso3

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6174]
_Issue [JP-2170](https://jira.stsci.edu/browse/JP-2170) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The front-end logic that resets the EXP_TYPE for any NIRCam engineering exposure using one of the SUBGRISM* subarrays such that EXP_TYPE='NRC_TSIMAGE' or 'NRC_TSGRISM', even though TSOVISIT=F is still causing problems. In the case of EXP_TYPE='NRC_TSIMAGE', TSOVISIT=F, and PUPIL='CLEAR', the data get sent to the calwebb_tso3 pipeline, where they're identified as imaging mode and hence the tso_photometry step gets called. The CRDS lookup for the TSOPHOT ref file correctly returns 'N/A' (because TSOVISIT=F), which causes the tso_photomety to skip, without returning any photometry data. Unfortunately, the calwebb_tso3 pipeline still tries to create an output file from the run, but because there's no photometry data, it fails with a "cannot convert None to table column" error.

The calwebb_tso3 pipeline module, and/or tso_photometry step, need to be made more robust to handle this condition without crashing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2170?focusedCommentId=543158#comment-543158):_

Fixed by #6265

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2170?focusedCommentId=546951#comment-546951):_

B7.8.2 justification:

1) Why do we need it?  Many NIRCam exposures taken during commissioning use the Engineering observation template in the APT, which in certain situations causes the population of inconsistent meta data values used by the calibration pipeline, thus leading to failures in either level-2b or level-3 calibration processing.
2) What does it fix?  Makes the calibration pipeline code more robust to this particular failure mode, so that the pipeline shuts down gracefully, without crashing.
3) What happens if we don't include it in B7.8.2?  Processing of these kinds of engineering exposures will cause the pipeline to crash, thus not completing the processing and archiving of needed data products.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp) on [JIRA](https://jira.stsci.edu/browse/JP-2170?focusedCommentId=548575#comment-548575):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) do you have a test case for this condition?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2170?focusedCommentId=548593#comment-548593):_

Yes, the ones listed in the "data location" field, which consists of the ASN jw00809-o024_20210628t153748_tso3_002_asn.json, containing several exposures: 
                    "expname": "jw00809024001_03102_00001_nrca3_calints.fits",
                    "expname": "jw00809024001_03104_00001_nrca3_calints.fits",
                    "expname": "jw00809024001_03104_00001_nrca1_calints.fits",
                    "expname": "jw00809024001_03102_00001_nrca1_calints.fits",

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2170?focusedCommentId=549611#comment-549611):_

In B7.8.2 testing on the D2 string (run2517), the 4 jw00809024 exposures listed above all failed in level-2a processing, due the problem with dark ref file selection for exposures with DETECTOR=NRCA1 or NRCA3 and SUBARRAY=SUBGRISM256 (no coverage). When processed manually - skipping the dark subtraction step - and subsequently processing all resulting products through level-2b and level-3, all steps and pipelines complete successfully, with all expected output products created and saved (and no crashes, obviously). So the Cal pipeline parts of this fix are confirmed to work properly.

**Comment by bhilbert4** [comment]
There are darks for NRCA1/3 SUBGRISM256 in CRDS. I have a feeling the dark selection is failing because those have EXP_TYPE set to NRC_DARK, rather than N/A? The other detail is that they contain the NOUTPUTS keyword (there are separate files for NOUTPUTS = 1 and 4), so perhaps the failure is because the science data don't have NOUTPUTS?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2170?focusedCommentId=549629#comment-549629):_

These are the infamous Engineering Template exposures that just happen to use one of the SUBGRISM* subarrays, which causes the front-end to reset the EXP_TYPE to a bogus value of NRC_TSIMAGE (or sometimes NRC_TSGRISM) even though they aren't time series exposures. Relevant header params:

```
TEMPLATE= 'NIRCam Engineering Imaging' / Observation template used              
TSOVISIT=                    F / Time Series Observation visit indicator                                                    
INSTRUME= 'NIRCAM  '           / Instrument used to acquire the data            
DETECTOR= 'NRCA1   '           / Name of detector used to acquire the data          
PUPIL   = 'CLEAR   '           / Name of the pupil element used                             
EXP_TYPE= 'NRC_TSIMAGE'        / Type of data in the exposure                                 
NOUTPUTS=                    4 / Number of detector outputs used                              
SUBARRAY= 'SUBGRISM256'        / Subarray used                                  
```

so there's just no coverage in CRDS for this weird combination of exp_type, detector, subarray, and noutputs.

**Comment by bhilbert4** [comment]
I think that once I change the EXP_TYPE of the existing darks from NRC_DARK to N/A (which has been on my To Do list), the files we have should cover this case. Specifically, jwst_nircam_dark_0271.fits looks like it will work.
