### ISSUE TITLE
Task: Update datamodels to use Keyword Dictionary schemas

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#618]
SDP and the JWST Keyword Dictionary use a set of json schemas to define FITS header keywords and map them to datamodel members. These schemas were originally based on the jwst datamodels core.schema.json. Keeping the 2 sets of definitions in synch is time-consuming and subject to human error. We need to revise our datamodels library to somehow make use of the schemas defined within the Keyword Dictionary, so that both SDP and Cal Pipeline are always working from the same set of definitions.

**Comment by bernie-simon** [comment]
> On Jan 19, 2017, at 10:48 AM, Howard Bushouse <notifications@github.com> wrote:
> 
> SDP and the JWST Keyword Dictionary use a set of json schemas to define FITS header keywords and map them to datamodel members. These schemas were originally based on the jwst datamodels core.schema.json. Keeping the 2 sets of definitions in synch is time-consuming and subject to human error. We need to revise our datamodels library to somehow make use of the schemas defined within the Keyword Dictionary, so that both SDP and Cal Pipeline are always working from the same set of definitions.

Would you like me to work on this problem? I have some free time.

**Comment by hbushouse** [comment]
Yes, I was going to assign this to you, but was waiting till I had a chance to talk to you about it. SDP has a collection of a couple dozen json schema files, which are segregated into groups of keywords that only apply to a certain instrument mode, or all the keywords associated with WCS information, etc., and then has "top" level schemas that inherit/include all of the lower-level sections to construct a full header definition for particular observing modes. We need to figure out how to somehow make use of those in place of our datamodels/schemas/core.schema.yaml file. We can't rely on accessing the SDP json files directly, because they won't be available when our software is installed on other systems by other users. So we need to keep something that is in the jwst package that is somehow a direct copy of the SDP version.

A web-based interface to the SDP keyword dictionary is here: https://iwjwdmsdauiwebv.stsci.edu/portal/Mashup/Clients/jwkeywords/

You can get a copy of all the json files by clicking on the link "Download Keyword Schemas" in the upper-right corner of that page.

**Comment by melanieclarke** [comment]
Closing: this ticket relates to the schema_editor, which is now deprecated ([JP-3804](https://jira.stsci.edu/browse/JP-3804)).
