### ISSUE TITLE
Add 4 new dither pattern names to PATTTYPE for MIRI External Flat Template for Coronagraph Flats

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6214]
_Issue [JP-2200](https://jira.stsci.edu/browse/JP-2200) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The MIRI team is adding new dither patterns to be used for coronagraphic external flats, so we need to update the PATTTYPE enum list in core.schema to include these new values, as documented in JWSTKD-460.

**Comment by stscijgbot-jp** [comment]
_Comment by [Linda Thompson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lthomp) on [JIRA](https://jira.stsci.edu/browse/JP-2200?focusedCommentId=539981#comment-539981):_

Discussion on 7/22/2021 (Rossy, Mark, Linda) is that these enum values are critical to commissioning. Can they be added to 7.8.1?

**Comment by hbushouse** [comment]
They can easily be added in time for inclusion in B7.8.1, but we just need to know what the values are that we need to add. Do we have confirmation of the values from the front-end and/or instrument folks?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2200?focusedCommentId=540024#comment-540024):_

Regarding case: FITS allows for string keyword values to be mixed case, but for consistency we stick to all uppercase for instrument/exposure related keyword values such as this. So, yes, we should use 4QM_LFLAT, 4QM_PFLAT, LYOT_LFLAT, and LYOT_PFLAT.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2200?focusedCommentId=540086#comment-540086):_

Final names have been agreed to in <https://jira.stsci.edu/browse/JSOCINT-590>

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2200?focusedCommentId=540188#comment-540188):_

fixed by #6232

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2200?focusedCommentId=540237#comment-540237):_

Justification for inclusion in B7.8.1:

1) Why do we need it?  MIRI will be using several new dither patterns during calibration of the coronagraphic mode. The names of these new patterns need to be added to the list of allowed values for the PATTTYPE keyword, so that exposures taken using these new dither patterns can be successfully processed through the calibration pipeline.

2) What does it fix?  The current calibration pipeline data model schemas need to include these new dither pattern names so that automatic validation of keyword values does not result in an error when exposures using these PATTTYPEs are processed. If the PATTTYPE names are not recognized as valid, the entire keyword will be dropped from the headers of DMS output products, resulting in processing failures downstream where that keyword is needed. This ticket adds the new keyword values to the data model schema, thus allowing exposures to pass schema validation tests.

3) What happens if we don't include it in B7.8.1?  MIRI coronagraphic calibration exposures using these dither patterns will fail processing in the calibration pipeline.
