### ISSUE TITLE
Use spectral order as input to WCS in NIRISS SOSS mode 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6216]
_Issue [JP-2153](https://jira.stsci.edu/browse/JP-2153) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Create and assign a  compound_bounding_box to the NIRISS SOSS WCS. 

The WCS then can be evaluated by passing a spectral order, e.g.

ra, dec, lam = wcs(x, y, order)

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=534265#comment-534265):_

I have extracted the majority of the `compound_bounding_box` code from `astropy.modeling` and moved it to `gwcs`. This is so that we can more easily do a release of JWST which does not depend on a development version of `astropy`.

Doing this was more involved than I initially anticipated, so it will require a refactor of my old unit tests. I believe it should function the same as when I introduced the `compound_bounding_box` into this using a special branch of `astropy`. The main issues involve the fact that in `astropy.modeling` the model itself has information on input keywords (we support passing inputs as keywords) and their normal positions. So the `compound_bounding_box` can process the slicing inputs from the "processed evaluation inputs" that `astropy.modeling.Model` naturally produces as it is evaluating. Moreover, the `bounding_box` is only really used inside the "evaluation" logic and not anywhere else. Thus the `compound_bounding_box` needs much more sophisticated logic to find its slicing inputs when it is moved into `gwcs`

In the process of moving and testing the from `compound_bounding_box` to `gwcs`, I noticed some issues with the initial approach of using a `compound_bounding_box` in place of a normal `bounding_box`. Namely, that in order for a `compound_bounding_box` to be useful as a bounding box directly one needs to know the value of the slicing input, which in general may not be available in places which use the `bounding_box` within the `gwcs`. Currently, the only place I know this won't be an issue is in `*_call_*` as I designed everything so that `*_call_*` would function correctly.

The functions that are part of `gwcs.wcs.WCS` that involve a `bounding_box` which could have potential issues with a `compound_bounding_box` are: `gwcs.wcs.WCS` `in_image`, `numerical_inverse`, `_vectorized_fixed_point`, `footprint` , `_to_fits_sip`, `to_fits_tab`, `_calc_approx_inv` . 

One way to avoid any issues in any of these other functions is to separate `bounding_box` and `compound_bounding_box` into their own properties or add processing logic to some of  these functions to set their internal bounding box logic to `None` values when they receive a `compund_bounding_box`.

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=534371#comment-534371):_

So very close testing has relieved to me that I don't think its possible to replicate the processing of inputs that a `Model` would do to `compound_bounding_box`, unless we are prepared to tell the compound bounding box about every single input to the model. The issue is the following: suppose we are in the NIRISS SOSS case, it has 3 inputs `x`, `y`, and `order`. Currently it would be completely valid to call the wcs as `wcs(1, x=2, y=3)` which is the inputs `x=2`, `y=3` and `order=1`. Here we are slicing the  compound bounding box by `order` so the box as no info on x or y. In the case I described I cannot find the value of `order` via keyword nor can I find the value of order by its input index (which would be 2 for the case of the `astropy` model). Thus we get stuck. I suppose one could say that the look up index is the min of the input index and the maximum input index, but that could lead to other issues like if there are multiple slicing arguments (which should be supported), or the slicing argument is not the last argument.

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=535010#comment-535010):_

To test my introduction of a bounding box to niriss you can look use: <https://github.com/WilliamJamieson/gwcs/tree/niriss_bbox_kwarg> and <https://github.com/WilliamJamieson/jwst/tree/niriss_bbox].> To see this in action you can use:


```python
from jwst import datamodels
from jwst.assign_wcs import niriss

# NIRISS SOSS mode data file
soss = datamodels.open('soss_sasign_wcs.fits')

soss.meta.wcs.bounding_box = niriss.niriss_bounding_box(soss)
print(soss.meta.wcs.bounding_box)
```

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=538558#comment-538558):_

See the following branches which implement this. * JWST branch: <https://github.com/WilliamJamieson/jwst/tree/feature/compound_bounding_box>
 * GWCS branch: <https://github.com/WilliamJamieson/gwcs/tree/feature/compound_bounding_box>
 * astropy branch: <https://github.com/WilliamJamieson/astropy/tree/feature/compound_bounding_box>

See the astropy PR: astropy/astropy#11942 

The no PRs have been opened on JWST or GWCS yet due to the differences in release schedules, which needs to be resolved.

**Comment by jdavies-st** [comment]
> the NIRISS SOSS case, it has 3 inputs `x`, `y`, and `order`. Currently it would be completely valid to call the wcs as `wcs(1, x=2, y=3)` which is the inputs `x=2`, `y=3` and `order=1`.

Doesn't the `gwcs` object specify the order of inputs specifically in the input frame?  I.e. in the in the `axes_order` attribute of the input coordinate frame?  I.e. `gwcs.coordinate_frames.Frame2D.axes_order?

If I open a SOSS file that has had `assign_wcs` run on it:

```
In [1]: from jwst import datamodels

In [2]: model = datamodels.open("/tmp/scratch/test_niriss_soss_rtdata_module0/jw00625023001_03101_00001-seg002_nis_calints.fits")

In [3]: model.meta.wcs.pipeline[0].frame
Out[3]: <Frame2D(name="detector", unit=(Unit("pix"), Unit("pix")), axes_names=('x', 'y'), axes_order=(0, 1))>
```

**Comment by WilliamJamieson** [comment]
First, `order` in my example refers to `spectral_order` in this case so `axes_order` is not what is needed.

In my latest version this is solved by moving compound bounding box to astropy itself rather than trying to accomplish something similar entirely in gwcs. This is because, in astropy, when a model is evaluated the user's inputs are always passed through this [method](https://github.com/astropy/astropy/blob/841908f7286c72f80b47a6b108754c96fdb3676a/astropy/modeling/core.py#L920-L973). It turns the user's inputs into an ordered list. In the case I listed these would always be turned into the list `[2, 3, 1]`. This input is then what can be used by a compound bounding box to determine which bounding box slice to invoke.

Basically, the issue amounts to the fact that in order for compound bounding box to exist solely as part of gwcs, it must replicate the method I mentioned above (or do something hacky like calling all the way down into this private method for a given model). In the end it makes more sense for compound bounding box to be part of astropy because from there I can eliminate any kluges (especially if one accepts my refactoring of bounding_box and model evaluation).

There is still some potential issues with using a compound bounding box in place of a bounding box in gwcs. These arise from the fact that `bounding_box` is used by methods which are not involved in model evaluation. A compound bounding box will not be able to act as a `bounding_box` in some situations (like looking up lower and upper bounds) because it requires additional information (which may not be present or accessible) to determine these things.

**Comment by jdavies-st** [comment]
I see.  That method is kinda nutty, and not entirely clear why one would even need to do that re-ordering.  But yeah, I see the issue now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=565330#comment-565330):_

Fixed by #6496

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=534265#comment-534265):_

I have extracted the majority of the `compound_bounding_box` code from `astropy.modeling` and moved it to `gwcs`. This is so that we can more easily do a release of JWST which does not depend on a development version of `astropy`.

Doing this was more involved than I initially anticipated, so it will require a refactor of my old unit tests. I believe it should function the same as when I introduced the `compound_bounding_box` into this using a special branch of `astropy`. The main issues involve the fact that in `astropy.modeling` the model itself has information on input keywords (we support passing inputs as keywords) and their normal positions. So the `compound_bounding_box` can process the slicing inputs from the "processed evaluation inputs" that `astropy.modeling.Model` naturally produces as it is evaluating. Moreover, the `bounding_box` is only really used inside the "evaluation" logic and not anywhere else. Thus the `compound_bounding_box` needs much more sophisticated logic to find its slicing inputs when it is moved into `gwcs`

In the process of moving and testing the from `compound_bounding_box` to `gwcs`, I noticed some issues with the initial approach of using a `compound_bounding_box` in place of a normal `bounding_box`. Namely, that in order for a `compound_bounding_box` to be useful as a bounding box directly one needs to know the value of the slicing input, which in general may not be available in places which use the `bounding_box` within the `gwcs`. Currently, the only place I know this won't be an issue is in `*_call_*` as I designed everything so that `*_call_*` would function correctly.

The functions that are part of `gwcs.wcs.WCS` that involve a `bounding_box` which could have potential issues with a `compound_bounding_box` are: `gwcs.wcs.WCS` `in_image`, `numerical_inverse`, `_vectorized_fixed_point`, `footprint` , `_to_fits_sip`, `to_fits_tab`, `_calc_approx_inv` . 

One way to avoid any issues in any of these other functions is to separate `bounding_box` and `compound_bounding_box` into their own properties or add processing logic to some of  these functions to set their internal bounding box logic to `None` values when they receive a `compund_bounding_box`.

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=534371#comment-534371):_

So very close testing has relieved to me that I don't think its possible to replicate the processing of inputs that a `Model` would do to `compound_bounding_box`, unless we are prepared to tell the compound bounding box about every single input to the model. The issue is the following: suppose we are in the NIRISS SOSS case, it has 3 inputs `x`, `y`, and `order`. Currently it would be completely valid to call the wcs as `wcs(1, x=2, y=3)` which is the inputs `x=2`, `y=3` and `order=1`. Here we are slicing the  compound bounding box by `order` so the box as no info on x or y. In the case I described I cannot find the value of `order` via keyword nor can I find the value of order by its input index (which would be 2 for the case of the `astropy` model). Thus we get stuck. I suppose one could say that the look up index is the min of the input index and the maximum input index, but that could lead to other issues like if there are multiple slicing arguments (which should be supported), or the slicing argument is not the last argument.

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=535010#comment-535010):_

To test my introduction of a bounding box to niriss you can look use: <https://github.com/WilliamJamieson/gwcs/tree/niriss_bbox_kwarg> and <https://github.com/WilliamJamieson/jwst/tree/niriss_bbox].> To see this in action you can use:


```python
from jwst import datamodels
from jwst.assign_wcs import niriss

# NIRISS SOSS mode data file
soss = datamodels.open('soss_sasign_wcs.fits')

soss.meta.wcs.bounding_box = niriss.niriss_bounding_box(soss)
print(soss.meta.wcs.bounding_box)
```

**Comment by stscijgbot-jp** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=538558#comment-538558):_

See the following branches which implement this. * JWST branch: <https://github.com/WilliamJamieson/jwst/tree/feature/compound_bounding_box>
 * GWCS branch: <https://github.com/WilliamJamieson/gwcs/tree/feature/compound_bounding_box>
 * astropy branch: <https://github.com/WilliamJamieson/astropy/tree/feature/compound_bounding_box>

See the astropy PR: astropy/astropy#11942 

The no PRs have been opened on JWST or GWCS yet due to the differences in release schedules, which needs to be resolved.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=565330#comment-565330):_

Fixed by #6496

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=583154#comment-583154):_

I do not have time to look at this.  For SOSS mode the order bounding boxes should be independent of the sky position, since we assume that only the one source that is acquired is of concern in the observation.  There is no way to assign sky coordinates to the pixels in the SOSS mode images. We probably do not want the order bounding box to move if the reported sky coordinates move a tiny bit from the source sky coordinates, although that may need some thought.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=583216#comment-583216):_

[Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) I just want to confirm that what you say above is still the case. This ticket was to rework a bit the internals of the WCS but there's no change in functionality from before. Perhaps the ticket should be closed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2153?focusedCommentId=583218#comment-583218):_

I agree that we can close this. It was strictly internal work and not intended for review by INS.
