### ISSUE TITLE
Bar mask darks missing in version 1.2.3

### ISSUE THREAD

**Issue by kammerje** [spacetelescope/jwst#6217]
Hi! I have been trying to run simulated NIRCam coronagraphy data through the Stage 1/2 pipeline. With the SUB320A430R subarray it works, but with the SUB320ALWB it crashes with the following error:

crds.core.exceptions.CrdsLookupError: Error determining best reference for 'dark'  =   No match found.

Could you please make sure that all subarrays listed in the [JWST Keyword Dictionary](https://mast.stsci.edu/portal/Mashup/Clients/jwkeywords/index.html) under NIRCAM/coron/Subarray parameters/SUBARRAY are supported (at least that they refer to an empty dummy dark if no proper dark is available yet)?

Thanks for your help!

**Comment by stscieisenhamer** [comment]
Examining the [CRDS website](https://jwst-crds.stsci.edu/), for NIRCam dark, there is an entry for SUB320ALWB. Most likely there is header information missing or different than required. The following header keywords should have the specified values:

- 'DETECTOR' is 'NRCBLONG' 
- 'SUBARRAY' is SUB320ALWB
- Observation date needs to be after 2015-06-01. 

Ensure that the header information corresponds to the above requirements.

If the header information is correct, could you post the output of the `fitsheader` command to this issue.

**Comment by kammerje** [comment]
Hi! Thanks a lot for your help and sharing the very helpful CRDS website. Most likely the issue is that I used NRCALONG as detector, because it also says SUB320(A)LWB. I didn't know that this subarray in fact uses the B detector module. I will try it tomorrow and close the issue if it works!
