### ISSUE TITLE
Add a github label to all github issues created by jirabot

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6221]
_Issue [JP-2204](https://jira.stsci.edu/browse/JP-2204) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Consider adding a label to all github issues that are created/linked to Jira issues by jirabot.

This will make it easier to find/filter such issues so that issues filed only on github can be easier to identify.

**Comment by jdavies-st** [comment]
Finding issues not opened by the bot can be done by going to issues and filtering by author in UI, then putting a minus sign in front. I.e.:
```
is:open is:issue -author:stscijgbot-jp 
```
So the following URL:

https://github.com/spacetelescope/jwst/issues?q=is%3Aopen+is%3Aissue+-author%3Astscijgbot-jp

If you want to filter out our old bot, which had a slightly different name:
```
is:open is:issue -author:stscijgbot
```

It doesn't look like you can `and` or `or` the authors together, or use wildcards when filtering.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2204?focusedCommentId=539372#comment-539372):_

Thanks! That will handled what I need.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2204?focusedCommentId=539373#comment-539373):_

Another solution has been presented and is acceptable.
