### ISSUE TITLE
NIRCAM Mask File not setting DO_NOT_USE bit

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6235]
_Issue [JP-2212](https://jira.stsci.edu/browse/JP-2212) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

The current NIRCAM mask reference files are rarely setting the DO_NOT_USE bit for almost all of the non-nominal pixels. Only pixels identified as DEAD are always set to DO NOT USE. The other used flags of SATURATED, HOT, RC and NONLINEAR rarely set the DO NOT USE bit. All non ideal pixels should default to DO NOT USE. This will allow the level 3 mosaics to ignore those pixels when it creates the final mosaic.

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) on [JIRA](https://jira.stsci.edu/browse/JP-2212?focusedCommentId=551206#comment-551206):_

Can someone clarify why SATURATED is in a bad pixel mask? I don't recall; are these RC/HOT that reach well on first/second sample? Those should definitely be DO_NOT_USE.  RC (and IRC if tracked in the DMS pipeline masks) should probably be set DO_NOT_USE.  One could potentially recover some information in RC pixels that are still responsive by removing the RC signal via e.g. frame-by-frame dark correction, but I wouldn't trust em!  I also don't recall what NONLINEAR means in the context of a bad pixel mask.  Are these merged from e.g. the linearity masks for pixels which we were unable to derive a non-linearity correction?

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2212?focusedCommentId=558836#comment-558836):_

Updated mask files have been delivered. The pixels previously flagged as NONLINEAR have had that flag removed. Those were the pixels originally flagged as WEIRD in the masks that [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) created. After discussing with him, we think those pixels should be treated as good. All pixels containing any other flags have had the DO_NOT_USE flag added.

**Comment by hbushouse** [comment]
Closing this issue, because all of the work to be done is assigned to the INS NIRCam team and does not involve any code changes.

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) on [JIRA](https://jira.stsci.edu/browse/JP-2212?focusedCommentId=551206#comment-551206):_

Can someone clarify why SATURATED is in a bad pixel mask? I don't recall; are these RC/HOT that reach well on first/second sample? Those should definitely be DO_NOT_USE.  RC (and IRC if tracked in the DMS pipeline masks) should probably be set DO_NOT_USE.  One could potentially recover some information in RC pixels that are still responsive by removing the RC signal via e.g. frame-by-frame dark correction, but I wouldn't trust em!  I also don't recall what NONLINEAR means in the context of a bad pixel mask.  Are these merged from e.g. the linearity masks for pixels which we were unable to derive a non-linearity correction?

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2212?focusedCommentId=558836#comment-558836):_

Updated mask files have been delivered. The pixels previously flagged as NONLINEAR have had that flag removed. Those were the pixels originally flagged as WEIRD in the masks that [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) created. After discussing with him, we think those pixels should be treated as good. All pixels containing any other flags have had the DO_NOT_USE flag added.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2212?focusedCommentId=685319#comment-685319):_

Closing ticket; if still necessary will be addressed as part of upcoming DQ work
