### ISSUE TITLE
NIRSpec Mask File never sets the DO NOT USE bit

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6236]
_Issue [JP-2213](https://jira.stsci.edu/browse/JP-2213) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

The current NIRSpec mask reference files never set the DO_NOT_USE bit for all of the non-nominal pixels. The used flags of DEAD, LOW_QE, OPEN, and ADJ_OPEN are labeled as viable pixels. All non ideal pixels should default to DO NOT USE. This will allow the level 3 pipeline to ignore those pixels when it creates the final products.

**Comment by hbushouse** [comment]
Closing this issue, because all of the work to be done is assigned to the INS MIRI team and does not involve any code changes.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-2213?focusedCommentId=665934#comment-665934):_

Reference files have been updated with appropriate DO_NOT_USE pixels. This ticket can be closed.
