### ISSUE TITLE
NIRISS Mask File not setting DO_NOT_USE

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6237]
_Issue [JP-2214](https://jira.stsci.edu/browse/JP-2214) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

The current NIRISS mask reference files are not setting the DO_NOT_USE bit for all of the non-nominal pixels. Pixels identified as NONLINEAR, AD_FLOOR, DROPOUT rarely set the DO NOT USE bit. All non-ideal pixels should default to DO NOT USE. This will allow the level 3 mosaics to ignore those pixels when it creates the final mosaic.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2214?focusedCommentId=547332#comment-547332):_

The bad pixel mask code for NIRISS is written and maintained by Chris Willott.  I will coordinate with Chris about these flags and see what he says.  I had thought that pixels that Chris' code flags as nonlinear are flagged as DO_NOT_USE.  The other two flags are ones that I am not immediately familiar with in terms of the treatment in Chris' codes.  In any case, the plan is to use the commissioning darks to regenerate the bad pixel mask and these changes can be inserted at that time as needed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Chris Willott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=chris.willott) on [JIRA](https://jira.stsci.edu/browse/JP-2214?focusedCommentId=547624#comment-547624):_

The NIRISS mask reference file generation code does set pixels identified as NONLINEAR and AD_FLOOR with the DO NOT USE bit. The latest version of the mask in CRDS did not have any pixels with these flags set because of incomplete analysis of linearity and superbias data. That will be corrected in future versions.

Could you clarify what you mean by DROPOUT for the mask reference file? My understanding is dropout is to be applied for science data that is lost in transmission. So how would this apply to a mask? There are no pixels that will always be lost in transmission.

**Comment by hbushouse** [comment]
Closing this issue, because all of the work to be done is assigned to the INS MIRI team and does not involve any code changes.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2214?focusedCommentId=547332#comment-547332):_

The bad pixel mask code for NIRISS is written and maintained by Chris Willott.  I will coordinate with Chris about these flags and see what he says.  I had thought that pixels that Chris' code flags as nonlinear are flagged as DO_NOT_USE.  The other two flags are ones that I am not immediately familiar with in terms of the treatment in Chris' codes.  In any case, the plan is to use the commissioning darks to regenerate the bad pixel mask and these changes can be inserted at that time as needed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Chris Willott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=chris.willott) on [JIRA](https://jira.stsci.edu/browse/JP-2214?focusedCommentId=547624#comment-547624):_

The NIRISS mask reference file generation code does set pixels identified as NONLINEAR and AD_FLOOR with the DO NOT USE bit. The latest version of the mask in CRDS did not have any pixels with these flags set because of incomplete analysis of linearity and superbias data. That will be corrected in future versions.

Could you clarify what you mean by DROPOUT for the mask reference file? My understanding is dropout is to be applied for science data that is lost in transmission. So how would this apply to a mask? There are no pixels that will always be lost in transmission.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2214?focusedCommentId=685320#comment-685320):_

Closing ticket; if still necessary will be addressed as part of upcoming DQ work
