### ISSUE TITLE
Incorrect NIRCAM Read Noise Reference Files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6239]
_Issue [JP-2215](https://jira.stsci.edu/browse/JP-2215) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

The read noise reference files that are currently being used were not created correctly. The current files reflect the CDS read noise in the raw integrations. The pipeline requires the CDS noise at the start of the jump step. The major difference in the two is that the dark current subtraction step needs to be performed before the "read noise" is calculated. The jump step needs to know the noise component that is not associated with the Poisson noise. The dark subtraction increases the CDS noise. Using the current files will lead to the jump step incorrectly flagging noise spikes as jumps (cosmic rays).  

  An additional problem is that this file seems to have a subset of pixels with significantly higher read noise than the median pixel. These pixels are distributed randomly and problem due to cosmic rays induced jumps being included in the read noise calculation.

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=551204#comment-551204):_

Is not the CDS noise computed on the raw ramps already effectively dark 'corrected' since they are formed as the difference of two adjacent frames with essentially the same dark current?  In general, until demonstrated necessary, I would recommend not doing the 'dark' correction anyway, at the very least on the SW NIRCam channels. 

Re - significantly higher read noise than median; I don't think CRs are the culprit here.  The read noise (cds) images were generated from in excess of several hundred time adjacent pairs and had robust outlier rejection applied to that stack before computing the temporal variance in the stack.  More likely those pixels are subject to stochastic electronic 'jumps'?  Will have to look back at the data.

**Comment by hbushouse** [comment]
Closing this issue, because all of the work to be done is assigned to the INS MIRI team and does not involve any code changes.

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=551204#comment-551204):_

Is not the CDS noise computed on the raw ramps already effectively dark 'corrected' since they are formed as the difference of two adjacent frames with essentially the same dark current?  In general, until demonstrated necessary, I would recommend not doing the 'dark' correction anyway, at the very least on the SW NIRCam channels. 

Re - significantly higher read noise than median; I don't think CRs are the culprit here.  The read noise (cds) images were generated from in excess of several hundred time adjacent pairs and had robust outlier rejection applied to that stack before computing the temporal variance in the stack.  More likely those pixels are subject to stochastic electronic 'jumps'?  Will have to look back at the data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=681124#comment-681124):_

Well, we still have a problem. The read noise measured in the jump step is higher than the reference file values. This leads to false positives.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=681182#comment-681182):_

Reopening till the NIRCam team creates and delivers new readnoise ref files. Who does this need to be assigned to?

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=681202#comment-681202):_

Since this doesn't involve changes to the pipeline infrastructure, maybe this ticket should be closed and we can open one in the NIRCam JIRA project? 

It sounds like there will need to be some investigation into how to adjust the method used to construct the readnoise files. Our dark reference files in the SW have zeros everywhere except for warm pixels. So dark subtraction isn't going to help much for those detectors.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=681207#comment-681207):_

[Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) That was my intention behind closing the linked github issue a year ago, because at the very least this work doesn't belong in the jwst github project. Unfortunately the github-Jira bot recently caught up with my activities on github and also closed this Jira ticket. I wasn't sure if there was a separate Jira project related to instrument teams creating reference files or if those were still being tracked here in the JP project. It would be really useful and easier to manage the JP project if purely reference file issues were in fact tracked in a different project. So if you want to move this to the NIRCam team project, I'm in favor. The question then is whether all the instrument teams have such a Jira project, to which all these reference file tickets could be moved.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=691029#comment-691029):_

This issue has been moved to the NIRCam project: <https://jira.stsci.edu/browse/NIRCAM-11>
Closing the JP issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=691029#comment-691029):_

This issue has been moved to the NIRCam project: <https://jira.stsci.edu/browse/NIRCAM-11>
Closing the JP issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2215?focusedCommentId=691031#comment-691031):_

Ticket moved to NIRCAM JIRA project
