### ISSUE TITLE
Incorrect NIRISS Read Noise Reference Files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6240]
_Issue [JP-2216](https://jira.stsci.edu/browse/JP-2216) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

The read noise reference files that are currently being used were not created correctly. The current files reflect the CDS read noise in the raw integrations. The pipeline requires the CDS noise at the start of the jump step. The major difference in the two is that the dark current subtraction step needs to be performed before the "read noise" is calculated. The jump step needs to know the noise component that is not associated with the Poisson noise. The dark subtraction increases the CDS noise. Using the current files will lead to the jump step incorrectly flagging noise spikes as jumps (cosmic rays).

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2216?focusedCommentId=553032#comment-553032):_

I ran a test for a set of five NIRISS CV3 darks in the current pipeline.  If one just takes the dark signal ramps with the reference pixel correction done the first difference values have a mean sigma over the array of 10.91 ADU.  The sigma value for each pixel is the sigma clipped standard deviation value for all the first difference samples in this calculation (250 independent first difference values). If I then apply the dark current subtraction step and repeat the calculation the value comes out as 10.83.  The value is slightly affected by the reference pixels, but only at the 0.01 ADU level.  Hence, contrary to expectations, the dark subtraction does not appear to be increasing the "read" noise estimate.  This suggests that the dark ramp subtraction takes out a small amount of reproducible noise in the dark ramps.  It also suggests that the change is in any case at the 1% or 2% level and hence it will not have a strong effect on the jump step.

We have code in place to run the "read" noise calculation with or without the dark current step in the pipeline.

**Comment by hbushouse** [comment]
Closing, because this is reference file work to be done by INS, not involving any code changes.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2216?focusedCommentId=553032#comment-553032):_

I ran a test for a set of five NIRISS CV3 darks in the current pipeline.  If one just takes the dark signal ramps with the reference pixel correction done the first difference values have a mean sigma over the array of 10.91 ADU.  The sigma value for each pixel is the sigma clipped standard deviation value for all the first difference samples in this calculation (250 independent first difference values). If I then apply the dark current subtraction step and repeat the calculation the value comes out as 10.83.  The value is slightly affected by the reference pixels, but only at the 0.01 ADU level.  Hence, contrary to expectations, the dark subtraction does not appear to be increasing the "read" noise estimate.  This suggests that the dark ramp subtraction takes out a small amount of reproducible noise in the dark ramps.  It also suggests that the change is in any case at the 1% or 2% level and hence it will not have a strong effect on the jump step.

We have code in place to run the "read" noise calculation with or without the dark current step in the pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2216?focusedCommentId=691147#comment-691147):_

Readnoise reference files to be assessed elsewhere, closing this ticket.
