### ISSUE TITLE
Incorrect NIRCAM gain reference files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6247]
_Issue [JP-2220](https://jira.stsci.edu/browse/JP-2220) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

The NIRCAM gain files do not allow the correct calculation of the Poisson noise in the science data. The gain file needs not be corrected for IPC. The IPC correction is needed to calculate the total number of detected electrons but the post-IPC gain file will overestimate the Poisson noise. IPC causes a reduction in the observed Poisson noise thus using a gain file that has been corrected for IPC will yield an overestimate of the Poisson noise.

This will affect the noise calculation of the jump step and the weighting in the ramp_fitting step.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2220?focusedCommentId=551075#comment-551075):_

The NIRCam gain reference files that are currently in CRDS were created from data that were not IPC corrected. We will continue to use data that have not been IPC-corrected when updating the gain reference files with commissioning data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) on [JIRA](https://jira.stsci.edu/browse/JP-2220?focusedCommentId=551202#comment-551202):_

Concur with Bryan - IPC was not applied to IDT supplied gain files.  

In any case, this should be a tiny affect  (and in fact I think our jump detection is underestimating total noise and so is a bit too sensitive).  And I can't quite wrap my head around whether the statement "corrected for IPC will yield an overestimate of the Poisson noise" is true on an individual pixel basis.  IPC reduces the Poisson noise when computed treating pixel ensembles by 'smearing' spatial signal. The Poisson noise for a single pixel should depend on the true charge in the pixel and I **think** IPC corrected gain + IPC corrected data per pixel should give the correct Poisson noise.

**Comment by hbushouse** [comment]
Closing this issue, because all of the work to be done is assigned to the INS MIRI team and does not involve any code changes.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2220?focusedCommentId=551075#comment-551075):_

The NIRCam gain reference files that are currently in CRDS were created from data that were not IPC corrected. We will continue to use data that have not been IPC-corrected when updating the gain reference files with commissioning data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Karl Misselt](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmisselt) on [JIRA](https://jira.stsci.edu/browse/JP-2220?focusedCommentId=551202#comment-551202):_

Concur with Bryan - IPC was not applied to IDT supplied gain files.  

In any case, this should be a tiny affect  (and in fact I think our jump detection is underestimating total noise and so is a bit too sensitive).  And I can't quite wrap my head around whether the statement "corrected for IPC will yield an overestimate of the Poisson noise" is true on an individual pixel basis.  IPC reduces the Poisson noise when computed treating pixel ensembles by 'smearing' spatial signal. The Poisson noise for a single pixel should depend on the true charge in the pixel and I **think** IPC corrected gain + IPC corrected data per pixel should give the correct Poisson noise.
