### ISSUE TITLE
Incorrect MIRI gain reference files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6250]
_Issue [JP-2223](https://jira.stsci.edu/browse/JP-2223) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

The MIRI gain reference files are all set to a constant value that was derived from a measurement of a non-MIRI detector. To date, there has not be a measurement of the gain for the MIRI detectors. The standard photon transfer method will not work due to the change in the sensitivity of the MIRI detectors as the accumulate charge. 
In some work I did a while back the value I derived the gain was significantly different than the assumed value. 

The error in the gain will affect the noise calculation of the jump step and the weighting in the ramp_fitting step.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2223?focusedCommentId=547336#comment-547336):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Perhaps this is something to discuss in a RTS meeting?

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2223?focusedCommentId=552098#comment-552098):_

This task is on the MIRI team to do and should not need any work from SCSB if all we're doing is replacing the image values in the SCI extension of the reference file.

**Comment by hbushouse** [comment]
Closing this issue, because all of the work to be done is assigned to the INS MIRI team and does not involve any code changes.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2223?focusedCommentId=547336#comment-547336):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Perhaps this is something to discuss in a RTS meeting?

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2223?focusedCommentId=552098#comment-552098):_

This task is on the MIRI team to do and should not need any work from SCSB if all we're doing is replacing the image values in the SCI extension of the reference file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2223?focusedCommentId=665952#comment-665952):_

The gain reference files have been updated in CRDS and are now in use in OPS. Closing the issue since the files are updated.
