### ISSUE TITLE
MIR_TACQ Level1b models do not round-trip

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6271]
_Issue [JP-2227](https://jira.stsci.edu/browse/JP-2227) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

MIR_TACQ image does not round-trip on second save. Commands provided above produces the following stack trace:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in get_hdu(hdulist, hdu_name, index)
    131     try:
--> 132         hdu = hdulist[pair]
    133     except (KeyError, IndexError, AttributeError):

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py in *_getitem_*(self, key)
    311             return self.*try_while_unread_hdus(super().__getitem_*,
--> 312                                                self._positive_index_of(key))
    313         except IndexError as e:

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py in _positive_index_of(self, key)
    766
--> 767         index = self.index_of(key)
    768

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py in index_of(self, key)
    747         if (found is None):
--> 748             raise KeyError(f'Extension {key!r} not found.')
    749         else:

KeyError: "Extension 'TARG_ACQ' not found."

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in get_hdu(hdulist, hdu_name, index)
    135             if isinstance(pair, str):
--> 136                 hdu = hdulist[(pair, 1)]
    137             elif isinstance(pair, tuple) and index == 0:

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py in *_getitem_*(self, key)
    311             return self.*try_while_unread_hdus(super().__getitem_*,
--> 312                                                self._positive_index_of(key))
    313         except IndexError as e:

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py in _positive_index_of(self, key)
    766
--> 767         index = self.index_of(key)
    768

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py in index_of(self, key)
    747         if (found is None):
--> 748             raise KeyError(f'Extension {key!r} not found.')
    749         else:

KeyError: "Extension ('TARG_ACQ', 1) not found."

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in _get_or_make_hdu(hdulist, hdu_name, index, hdu_type, value)
    174     try:
--> 175         hdu = get_hdu(hdulist, hdu_name, index=index)
    176     except AttributeError:

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in get_hdu(hdulist, hdu_name, index)
    141         except (KeyError, IndexError, AttributeError):
--> 142             raise AttributeError(
    143                 "Property missing because FITS file has no "

AttributeError: Property missing because FITS file has no ''TARG_ACQ'' HDU

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-5-a53d8717aa45> in <module>
----> 1 s1.save('s_2.fits')

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/model_base.py in save(self, path, dir_path, *args, **kwargs)
    509             if 'clobber' not in kwargs:
    510                 kwargs.setdefault('overwrite', True)
--> 511             self.to_fits(output_path, *args, **kwargs)
    512         elif ext == '.asdf':
    513             self.to_asdf(output_path, *args, **kwargs)

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/model_base.py in to_fits(self, init, *args, **kwargs)
    621         self.on_save(init)
    622
--> 623         with fits_support.to_fits(self._instance, self._schema) as ff:
    624             with warnings.catch_warnings():
    625                 warnings.filterwarnings('ignore', message='Card is too long')

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in to_fits(tree, schema)
    394
    395     _save_from_schema(hdulist, tree, schema)
--> 396     _save_extra_fits(hdulist, tree)
    397     _save_history(hdulist, tree)
    398

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in _save_extra_fits(hdulist, tree)
    359         if 'data' in parts:
    360             hdu_type = _get_hdu_type(hdu_name, value=parts['data'])
--> 361             hdu = _get_or_make_hdu(hdulist, hdu_name, hdu_type=hdu_type,
    362                                    value=parts['data'])
    363         if 'header' in parts:

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in _get_or_make_hdu(hdulist, hdu_name, index, hdu_type, value)
    175         hdu = get_hdu(hdulist, hdu_name, index=index)
    176     except AttributeError:
--> 177         hdu = _make_hdu(hdulist, hdu_name, index=index, hdu_type=hdu_type,
    178                         value=value)
    179     else:

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/stdatamodels/fits_support.py in _make_hdu(hdulist, hdu_name, index, hdu_type, value)
    164         hdu = hdu_type(value)
    165     else:
--> 166         hdu = hdu_type(value, name=hdu_name)
    167     if index is not None:
    168         hdu.ver = index + 1

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/table.py in *_init_*(self, data, header, name, uint, ver, character_as_bytes)
    856             header = hdu.header
    857
--> 858         super().*_init_*(data, header, name=name, uint=uint, ver=ver,
    859                          character_as_bytes=character_as_bytes)
    860

~/miniconda3/envs/jwst-master-local/lib/python3.9/site-packages/astropy/io/fits/hdu/table.py in *_init_*(self, data, header, name, uint, ver, character_as_bytes)
    366                 pass
    367             else:
--> 368                 raise TypeError('Table data has incorrect type.')
    369
    370         # Ensure that the correct EXTNAME is set on the new header if one was

TypeError: Table data has incorrect type.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2227?focusedCommentId=541730#comment-541730):_

For some reason I cannot change the type of this issue to "Bug".

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2227?focusedCommentId=542711#comment-542711):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) weird... I changed the type to Bug. Not sure why you weren't able to. Let me know if it happens again and we can ping the Jira gurus.

**Comment by nden** [comment]
Fixed by https://github.com/spacetelescope/stdatamodels/pull/89

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2227?focusedCommentId=574812#comment-574812):_

Fixed by spacetelescope/stdatamodels#89

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2227?focusedCommentId=541730#comment-541730):_

For some reason I cannot change the type of this issue to "Bug".

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2227?focusedCommentId=542711#comment-542711):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) weird... I changed the type to Bug. Not sure why you weren't able to. Let me know if it happens again and we can ping the Jira gurus.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2227?focusedCommentId=574812#comment-574812):_

Fixed by spacetelescope/stdatamodels#89
