### ISSUE TITLE
Opening an already open datamodel doesn't coerce the dtype

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6275]
_Issue [JP-2248](https://jira.stsci.edu/browse/JP-2248) was created on JIRA by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

The following issue was reported by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert).

The following reproduces the problem:

```
In [14]: with datamodels.Level1bModel((1, 1, 10, 10)) as model:
    ...:     model.save("temp_uncal.fits")
    ...: 

In [15]: with datamodels.open("temp_uncal.fits") as model:
    ...:     print(type(model), model.meta.model_type, model.data.dtype)
    ...:     model = datamodels.RampModel(model)
    ...:     print(type(model), model.meta.model_type, model.data.dtype)
    ...: 
<class 'jwst.datamodels.level1b.Level1bModel'> Level1bModel >u2
<class 'jwst.datamodels.ramp.RampModel'> Level1bModel uint16

In [27]: model.save("temp.fits")
Out[27]: 'temp.fits'

In [28]: print(type(model), model.meta.model_type, model.data.dtype)
<class 'jwst.datamodels.ramp.RampModel'> RampModel uint16

In [29]: model = datamodels.open("temp.fits")

In [30]: print(type(model), model.meta.model_type, model.data.dtype)
<class 'jwst.datamodels.ramp.RampModel'> RampModel uint16
```

So opening as a `RampModel` an already open datamodel of a different type, does not coerce to the new type, specifically it does not coerce the dtype, nor does it validate against the dtype of the `RampModel` which is float32 for the data array.  If one then runs this new model through `Detector1Pipeline` it eventually fails with 

```
2021-08-05 11:52:21,687 - stpipe.Detector1Pipeline.superbias - WARNING - Keyword NOISY does not correspond to an existing DQ mnemonic, so will be ignored
Traceback (most recent call last):
  File "run_pipeline.py", line 39, in <module>
    model.run(datamodel)
  File "/Users/hilbert/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/hilbert/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/jwst/pipeline/calwebb_detector1.py", line 107, in process
    result = self.superbias(result)
  File "/Users/hilbert/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/hilbert/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/jwst/superbias/superbias_step.py", line 41, in process
    result = bias_sub.do_correction(input_model, bias_model)
  File "/Users/hilbert/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/jwst/superbias/bias_sub.py", line 43, in do_correction
    output_model = subtract_bias(input_model, bias_model)
  File "/Users/hilbert/miniconda3/envs/jwql-py3.8/lib/python3.8/site-packages/jwst/superbias/bias_sub.py", line 80, in subtract_bias
    output.data -= bias.data
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float32') to dtype('uint16') with casting rule 'same_kind'
```

This is a pretty serious bug, as the above workflow should work fine.

A further example using Bryan's data above:

```
In [5]: model = datamodels.open(filename)

In [6]: print(type(model), model.meta.model_type, model.data.dtype)
<class 'jwst.datamodels.level1b.Level1bModel'> Level1bModel uint16

In [7]: model = datamodels.RampModel(model)
2021-08-05 13:35:38,061 - stpipe - WARNING - /Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stdatamodels/validate.py:34: ValidationWarning: While validating <RampModel(1, 2, 2048, 2048) from my_test_uncal.fits> the following error occurred:
'0' is not of type 'integer'

Failed validating 'type' in schema['properties']['meta']['properties']['dither']['properties']['dither_points']:
    OrderedDict([('title', 'Number of points in image dither pattern'),
                 ('type', 'integer'),
                 ('fits_keyword', 'NRIMDTPT'),
                 ('blend_table', True)])

On instance['meta']['dither']['dither_points']:
    '0'
  warnings.warn(errmsg, ValidationWarning)


In [8]: print(type(model), model.meta.model_type, model.data.dtype)
<class 'jwst.datamodels.ramp.RampModel'> Level1bModel uint16

In [9]: model.data += 3.2
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-9-d4e656d9d087> in <module>
----> 1 model.data += 3.2

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('uint16') with casting rule 'same_kind'
```

Very odd that the validation warning only happens on reopening as a RampModel.

So the question becomes do we validate against the schema on write only, which seems to be what we do currently?  Or do we check it on read as well?  That said, it isn't even validating `model.data` dtype on write or read it seems.

Btw, all the archived _uncal.fits files in MAST right now have model types of `Level1bModel` in their FITS headers, which is why you get that model type when doing `datamodels.open()`.

If one just passes the filename to `calwebb_detector1``, it explicitly reads the file from disk as a `RampModel` and works fine, runs through the pipeline without problems.

This seems like a serious bug, so I'm labelling Major.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2248?focusedCommentId=543090#comment-543090):_

Note that if one doesn't skip IPC step above, it fails there instead.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2248?focusedCommentId=543090#comment-543090):_

Note that if one doesn't skip IPC step above, it fails there instead.

**Comment by braingram** [comment]
FWIW it seems like this may be intentionally disabled (and can be turned on with `validate_arrays=True`).

Changing the original example to include:
```
model = datamodels.RampModel(model, validate_arrays=True)
```

Results in the expected validation failure:
```
Failed validating 'datatype' in schema['properties']['data']:
    OrderedDict([('title', 'The science data'),
                 ('fits_hdu', 'SCI'),
                 ('default', 0.0),
                 ('ndim', 4),
                 ('datatype', 'float32')])

On instance['data']:
    {'byteorder': 'little',
     'datatype': 'uint16',
     'shape': [1, 1, 10, 10],
     'source': 0}
```

See https://github.com/spacetelescope/stdatamodels/pull/79 for the PR that added this option.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2248?focusedCommentId=691856#comment-691856):_

Given how old this ticket is and the fact that (to my knowledge) we haven't had any other complaints or problems with this in the past 2.5 years since originally reported, I don't see it as a big issue. Especially since there's also the new workaround available that will at least check data array dtypes. So I'm going to close.
