### ISSUE TITLE
Add a "Getting Started" section to the documentation

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6279]
_Issue [JP-2249](https://jira.stsci.edu/browse/JP-2249) was created on JIRA by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

Currently the jwst docs don't have a simple "Getting Started" section that goes through a basic example of, say, running some imaging data through the 3 stages of the jwst pipeline.  This would be very useful to users.  Feedback from ERS team users:

> If I want to know "how do I create an association file" or "how do I run calwebb_image3 on a set of images" one is completely in the dark. Having copious (and simple) examples will make "read the docs" excellent reference material.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=543585#comment-543585):_

Note: we're also working on a similar page in JDox with Ori and Cami. 
 * Rough draft (Ori): <https://jwst-docs.stsci.edu/display/JDOX/.Getting+Started+with+JWST+Data+v1.1>
 * Rough draft (Ori): <https://jwst-docs.stsci.edu/display/JDOX/.Running+the+Pipeline+v1.1> 
 * Example of how to display JWebbinar content (Cami): <https://outerspace.stsci.edu/display/JP/JDox+content> 

CC: [Ori Fox](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ofox) [Alaina Henry](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ahenry) [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz)

Other note for myself: None of the JWebbinar notebooks go through how you would create an association file based on how a program is designed. The users will not have easy insight into how JWST associations are designed, so it would be tough for them to figure out how to set up level-2b or 3 association files based on a program with, e.g., science and background targets, dithers, shortwave + longwave data, multiple filters, etc.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=544429#comment-544429):_

Definitely we don't want to duplicate this information in Read-the-docs. I would suggest to put this ticket on hold until the above pages (mentioned by Alicia) are complete. The Dev team is welcome to provide input on this pages at that time to make them more useful to users.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=544510#comment-544510):_

Documentation on specifics of the `jwst` software should live in the `jwst` repo, with the code, so that examples actually get tested and the documentation remains up-to-date.  This includes how to run the pipeline, i.e. what commands to use.

It's fine to have some general information on JDox, but specific stuff should really live in `jwst` and be built on RTD for maintainability purposes.

I'm mainly worried about web pages getting out of date here.  This happens routinely when documentation is separated from the code it describes.  This is the advantage of having the documentation built by RTD daily.  Not only is the latest, but the examples are tested against the actual existing code in the pipeline so that we know it works.

This is also the reason that any notebooks written to describe how to use the `jwst` pipeline code also need to be under CI so that we *know* they work with the latest release and have not become stale.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=544514#comment-544514):_

Meanwhile, the RTD documentation is really wanting.  It needs a real organizational update, and it's missing a lot of user-level detail that it would be very important to get in there.  So any contributions to the existing docs that remedy this would be greatly appreciated.

**Comment by nden** [comment]
I'm closing this since there was an overhaul of the RTD documentation a while ago. We'll open specific tickets for further improvements.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=543585#comment-543585):_

Note: we're also working on a similar page in JDox with Ori and Cami. 
 * Rough draft (Ori): <https://jwst-docs.stsci.edu/display/JDOX/.Getting+Started+with+JWST+Data+v1.1>
 * Rough draft (Ori): <https://jwst-docs.stsci.edu/display/JDOX/.Running+the+Pipeline+v1.1> 
 * Example of how to display JWebbinar content (Cami): <https://outerspace.stsci.edu/display/JP/JDox+content> 

CC: [Ori Fox](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ofox) [Alaina Henry](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ahenry) [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz)

Other note for myself: None of the JWebbinar notebooks go through how you would create an association file based on how a program is designed. The users will not have easy insight into how JWST associations are designed, so it would be tough for them to figure out how to set up level-2b or 3 association files based on a program with, e.g., science and background targets, dithers, shortwave + longwave data, multiple filters, etc.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=544429#comment-544429):_

Definitely we don't want to duplicate this information in Read-the-docs. I would suggest to put this ticket on hold until the above pages (mentioned by Alicia) are complete. The Dev team is welcome to provide input on this pages at that time to make them more useful to users.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=544510#comment-544510):_

Documentation on specifics of the `jwst` software should live in the `jwst` repo, with the code, so that examples actually get tested and the documentation remains up-to-date.  This includes how to run the pipeline, i.e. what commands to use.

It's fine to have some general information on JDox, but specific stuff should really live in `jwst` and be built on RTD for maintainability purposes.

I'm mainly worried about web pages getting out of date here.  This happens routinely when documentation is separated from the code it describes.  This is the advantage of having the documentation built by RTD daily.  Not only is the latest, but the examples are tested against the actual existing code in the pipeline so that we know it works.

This is also the reason that any notebooks written to describe how to use the `jwst` pipeline code also need to be under CI so that we *know* they work with the latest release and have not become stale.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=544514#comment-544514):_

Meanwhile, the RTD documentation is really wanting.  It needs a real organizational update, and it's missing a lot of user-level detail that it would be very important to get in there.  So any contributions to the existing docs that remedy this would be greatly appreciated.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=636326#comment-636326):_

I'm closing this since there was an overhaul of the RTD documentation a while ago. We'll open specific tickets for further improvements.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2249?focusedCommentId=691133#comment-691133):_

Most of this is taken care of by a combination of the latest readthedocs and jdox together, along with multiple notebooks existing and under development.  Future work will continue to improve upon it, but closing this ticket.
