### ISSUE TITLE
CrdsLookupError: Error determining best reference for 'dark'  =   No match found.

### ISSUE THREAD

**Issue by kglidic** [spacetelescope/jwst#6337]
Below is a minimal working example of the issue at hand attached. Here is also a link to the offending file: [https://arizona.box.com/s/cmx41n2v01xqcqmjzk3395fievy6qhm1](https://arizona.box.com/s/cmx41n2v01xqcqmjzk3395fievy6qhm1)

Previously, in May 2021, using the JWST pipeline version 1.1.1, stage 1 of the pipeline (module Detector1Pipeline) successfully ran. I expected this to be the same in a recent attempt to run the code. Now, when using the JWST pipeline version 1.1.1 and even with the updated JWST pipeline version 1.3.1, it returns the following error: 

---------------------------------------------------------------------------
```
CrdsLookupError                           Traceback (most recent call last)
/tmp/ipykernel_4104924/2857652551.py in <module>
     17 
     18 # Execute the pipeline using the run method
---> 19 result_stage1 = pipeline_stage1.run(filename_stage1)

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/stpipe/step.py in run(self, *args)
    403             else:
    404                 if self.prefetch_references:
--> 405                     self.prefetch(*args)
    406                 try:
    407                     step_result = self.process(*args)

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/stpipe/step.py in prefetch(self, *args)
    520         # prefetch truly occurs at the Pipeline (or subclass) level.
    521         if len(args) and len(self.reference_file_types) and not self.skip:
--> 522             self._precache_references(args[0])
    523 
    524     def process(self, *args):

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/stpipe/pipeline.py in _precache_references(self, input_file)
    233             with self.open_model(input_file, asn_n_members=1,
    234                                 asn_exptypes=["science"]) as model:
--> 235                 self._precache_references_opened(model)
    236         except (ValueError, TypeError, IOError):
    237             self.log.info(

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/stpipe/pipeline.py in _precache_references_opened(self, model_or_container)
    256         else:
    257             # precache a single model object
--> 258             self._precache_references_impl(model_or_container)
    259 
    260     def _precache_references_impl(self, model):

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/stpipe/pipeline.py in _precache_references_impl(self, model)
    280         self.log.info("Prefetching reference files for dataset: " + repr(model.meta.filename) +
    281                       " reftypes = " + repr(fetch_types))
--> 282         crds_refs = crds_client.get_multiple_reference_paths(model.get_crds_parameters(), fetch_types, model.crds_observatory)
    283 
    284         ref_path_map = dict(list(crds_refs.items()) + list(ovr_refs.items()))

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/stpipe/crds_client.py in get_multiple_reference_paths(parameters, reference_file_types, observatory)
     53 
     54     log.set_log_time(True)
---> 55     refpaths = _get_refpaths(parameters, tuple(reference_file_types), observatory)
     56     return refpaths
     57 

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/stpipe/crds_client.py in _get_refpaths(data_dict, reference_file_types, observatory)
     67         return {}
     68     with crds_cache_locking.get_cache_lock():
---> 69         bestrefs = crds.getreferences(
     70             data_dict, reftypes=reference_file_types, observatory=observatory)
     71     refpaths = {filetype: filepath if "N/A" not in filepath.upper() else "N/A"

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/crds/core/heavy_client.py in getreferences(parameters, reftypes, context, ignore_cache, observatory, fast)
    125     # Attempt to cache the recommended references,  which unlike dump_mappings
    126     # should work without network access if files are already cached.
--> 127     best_refs_paths = api.cache_references(
    128         final_context, bestrefs, ignore_cache=ignore_cache)
    129 

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/crds/client/api.py in cache_references(pipeline_context, bestrefs, ignore_cache)
    846     Returns:   { reference_keyword :  reference_local_filepath ... }
    847     """
--> 848     wanted = _get_cache_filelist_and_report_errors(bestrefs)
    849 
    850     if config.S3_RETURN_URI:

~/miniconda3/envs/JWST-1.3.1/lib/python3.9/site-packages/crds/client/api.py in _get_cache_filelist_and_report_errors(bestrefs)
    889             log.error(str(last_error))
    890     if last_error is not None:
--> 891         raise last_error
    892     return wanted
    893 

CrdsLookupError: Error determining best reference for 'dark'  =   No match found. 
```

---------------------------------------------------------------------------------------------

Upon seeing similar reported errors, I have attempted to change the observation date (DATE-OBS)  to be further in the future, specifically 2023-10-23 but still encountered the same error in both versions of the pipeline. Fetching the CRDS version`$ crds list --version` returns :10.3.7, b10.3.7, fdd1a1cbc45c038e33366f339cf8793bdfc69434

Here the minimal working code: 

```
#Import Library 
import jwst
print(jwst.__version__)
from jwst.pipeline.calwebb_detector1 import Detector1Pipeline
from astropy.io import fits

# Stage 1: Dectector1Pipeline
HDUList = fits.open('modified_jw88888001001_01101_00001_nrca1_uncal.fits')
#read modified uncalibrated file header information 
HDUList[0].header

filename_stage1='modified_jw88888001001_01101_00001_nrca1_uncal.fits' #Use the modified uncalibrated file created above
# Instantiate the class. Do not provide a configuration file.
pipeline_stage1 = Detector1Pipeline()
# Manually set any desired non-default parameter values
# Default is to skip the persistence and IPC correction
# Make that explicit here
pipeline_stage1.persistence.skip = True
pipeline_stage1.ipc.skip = True

# The default value for CR flagging is 3 or 4 sigma
# which tends to be too aggressive and flags noise.
# Set it to something more reasonable
pipeline_stage1.jump.rejection_threshold = 9

# Execute the pipeline using the run method
result_stage1 = pipeline_stage1.run(filename_stage1)
```

Thank you

**Comment by hbushouse** [comment]
NIRCam dark ref files are selected based on values of EXP_TYPE, DETECTOR, SUBARRAY, NOUTPUTS, and DATE-OBS, so we'll need to know the values of those keywords in the input science exposure to figure out why CRDS can't find a matching dark. I tried the link above to get to the file, but it requires a UA box account to access.

**Comment by kglidic** [comment]
I went ahead and fixed the link to the offending file:[https://arizona.box.com/s/cmx41n2v01xqcqmjzk3395fievy6qhm1](https://arizona.box.com/s/cmx41n2v01xqcqmjzk3395fievy6qhm1). 

After some testing, I found that the dark reference file error shows up after the CRDS jwst_0759.pmap update. The error does not show up when I use older versions. As for the header value information you requested: 
 EXP_TYPE = ‘NRC_TSIMAGE'
 DETECTOR = 'NRCA1   '
 SUBARRAY = 'SUBGRISM256'
 NOUTPUTS= 4                    
 DATE-OBS= '2021-10-25'

**Comment by hbushouse** [comment]
Darks taken in the SUBGRISM256 subarray are only provided for detectors A2, A4, B1, B3. So there's no coverage for A1. And I'm also guessing that this is one of those exposures taken with the Engineering Template in APT, which lets users pick any semi-random combination of instrument settings, regardless of whether they make any sense, and is also the mode where one of the front-end systems automatically resets the EXP_TYPE to either NRC_TSIMAGE or NRC_TSGRISM just because one of the SUBGRISM* subarrays is in use, even though the exposure isn't taken in time series mode. This has been a real problem case for a long time.

Darks covering this detector, subarray, and noutputs values were recently added to CRDS, but all have EXP_TYPE='NRC_DARK', so even those won't match here (because of the EXP_TYPE mismatch). I believe @bhilbert4 said he was going to remove the EXP_TYPE values for those darks, so they would then apply to other modes too.  Now that you mention it, why would we want/need darks to cover EXP_TYPE='NRC_DARK' exposures - why would subtract dark from a dark exposure? Dark exposures stop processing in the calwebb_detector1 pipeline before getting to the dark step.

**Comment by bhilbert4** [comment]
I will be updating the darks relatively soon. The darks with EXP_TYPE set to NRC_DARK will have it changed to N/A. Note that these darks already have the NOUTPUTS keyword in them. The SUBGRISM256 darks for A2, A4, B1, and B3 will be removed, since that aperture is not defined for those detectors.
