### ISSUE TITLE
Incorrect Nonlinearity Referece File for NIRISS

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6345]
_Issue [JP-2276](https://jira.stsci.edu/browse/JP-2276) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

I've attached an image of the NIRISS nonlinearity correction factor at saturation. There are many features in this image that are not physical. The left center of the image shows several stripes of pixels with correction factors above 1.4. While the pdf version does smooth out some of the details, the overall trend is correct. 
There is something fundamentally wrong with this reference file. It needs to be fixed before the commissioning of NIRISS.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548241#comment-548241):_

Hi [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) --- thanks for this! Can you detail how this correction factor was calculated? Was this the linear slope over the computed non-linearity solution?

N.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548243#comment-548243):_

The correction factor is the value that is multiplied by the raw DN value to obtain the corrected (linear) DN. The value displayed is the value approximately at saturation. This will be the largest correction factor.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548244#comment-548244):_

Got it, thanks for the clarification!

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548265#comment-548265):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) Could you clarify the version of the ref file used for the plot? If that is the latest version, we noticed similar issues too and we are ready to deliver an updated version. If you would be willing to check the latest version before it being delivered, please let me know so I can share the location of the file. 


I would also appreciate it if you could confirm that this was not seen in the previous versions of the file, to understand where the issue is originating from.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548270#comment-548270):_

The strange features on the left of the image were not in version 11 but were in version 12. I'm also worried about the general left to right gradient. If the illumination pattern has a left/right gradient, then there is still a major problem with the solution.

I'd be fine with checking out a new version of the file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548279#comment-548279):_

Thank you for the clarification. The latest version of the file is stored here. Note that this version has one less coefficients than version 12.
/ifs/jwst/wit/niriss/tmorishita/linearity_May2021_rerevisit_C0positive/niriss_ref_linearity.fits

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548343#comment-548343):_

[^niriss_May2021.pdf]

This is the updated correction factor. The changes appear to be pretty small.

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548344#comment-548344):_

The new one seems almost identical to the previous one to my eye in these pdf files, by pixel-to-pixel level. Given the difference is not small in coefficient values, I was expecting more variation, if not necessarily better...
The attachment is for the first coefficient, for example; left for the new one, right version 12 (/ifs/jwst/wit/mirage_data/niriss/reference_files/linearity/jwst_niriss_linearity_0012.fits).

!image-2021-09-08-19-39-11-897.png!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548535#comment-548535):_

My mistake. I've attached the correct version. Too much copy and paste. I thought it looked very similar but I somehow convinced myself that there were differences.

The latest version is very close to the 0011 version. The large anomalies on the left side have been removed but there is still a very large (~20%) left-right gradient. It's hard to understand how that the nonlinearity could have such a large global gradient.  This image is normalized to the median value. I'll post the actual correction factor next.

[^niriss_May2021.pdf]

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548539#comment-548539):_

The unnormalized correction factor is attached.

[^niriss_May2021.pdf]

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548555#comment-548555):_

Thank you. It's assuring to know that the latest version is close to the 0011 version.  Do you have the same plot for the 0011 version that can be shared here, so I can see how the left-to-right gradient compares to the previous version? 

Also, 
>  the value approximately at saturation
is this set constant over the detector, or taken from the saturation file for each pixel?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548934#comment-548934):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) here are the plots of correction factor for version 11 and the new one, calculated at the saturation value taken from the satulation reference file at each pixel. To my eye, they look almost identical, though the median value is ~0.44% higher in the latter. If you are happy with this version, we will start the process to deliver it. Please let me know.

Regarding gradient, I'm attaching the same plots above but divided by the median value respectively. Again, these look very similar, so it seems that the issue is not originated from the specific method used in the latest version. 

Here I'm including [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk), to see if he has any additional comments.

!correction_all_ver11_2d.png|thumbnail!!correction_all_2d.png|thumbnail!

!correction_all_ver11_2d_grad.png|thumbnail!!correction_all_2d_grad.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549047#comment-549047):_

Yes, it is now very close to version 11. I started to write this ticket on version 11 but found that version 13 was the latest version. The variation in the correction factor is an order of magnitude higher than I expect and have seen. You should not see a left/right gradient or the picture frame in the NL correction factors. Can you post an image of the illumination pattern of the calibration image?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549065#comment-549065):_

here is the map of signals at frame number 150 just as an example.
!signal.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549120#comment-549120):_

This looks like a raw DN value image. It has significant structure that is in the bias. Can you show a CDS image?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549135#comment-549135):_

ah, right. Here is the map for ideal linearized signal rates, derived from the "forward" fitting. I just checked the previous version of the same map, and they look very similar. Note that we used the same input ramp file, so the similarity over the various output products is not a surprise.
!signal-1.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549151#comment-549151):_

Well, there is a clear problem here. The correction factor is correlated with the saturation file and the illumination pattern. Neither of them should be true. The saturation file has a separate issue but the NL file is wrong.
Can you point me to the raw images you used to derive the coefficients?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549163#comment-549163):_

The raw image is placed here: 

/ifs/jwst/wit/niriss/tmorishita/linearity/raw/meanlong.fits

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549355#comment-549355):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) please see the attachment, updated map for the correction factor. This time the correction factor was calculated by using the latest version of the saturation file generated from the same code. (Previously I mistakenly used an old version of the saturation file when I created the map. Apology for making the situation confusing.) 

In this version, the L-to-R gradient clearly seen in version 11 (posted above, with "ver11" title) has almost completely removed. The map is not correlated with the input signal map that I posted earlier. With these improvements, we consider this version as deliverable to the reference repo, especially given that the previous one (ver13) shows some strange structure. I'd appreciate your thoughts or any other feedback for further improvement.

  !correction_all_2d_grad-1.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549961#comment-549961):_

[Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) This version is significantly improved over any previous version. I'd be fine with having this be the current version. I assume the matching saturation file will also be delivered. 
Even so, there are still problems. The picture frame is visible in the map and saturation pattern is also visible. Eddie Bergeron and I think this may be due to pushing the saturation limit close to the A/D limit of 64K. There are some problems with the A/D converters on the SIDECAR above 61K and below 5K. We need to address these issues with all the NIR instruments for cycle 1. I just wanted to mention that.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=550351#comment-550351):_

[Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) 
The directory you pointed to above :
/ifs/jwst/wit/niriss/tmorishita/linearity/raw/meanlong.fits
cannot be read by anyone expect yourself. Can you change the permissions?
Thanks

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=550844#comment-550844):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) I changed the permissions of the directory. Please let me know if this still does not give you access to the file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=550855#comment-550855):_

I can get to the linearity directory but not it's subdirectory raw

**Comment by hbushouse** [comment]
This is an INS task that has no connection to code work in the github repo. Closing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548243#comment-548243):_

The correction factor is the value that is multiplied by the raw DN value to obtain the corrected (linear) DN. The value displayed is the value approximately at saturation. This will be the largest correction factor.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548244#comment-548244):_

Got it, thanks for the clarification!

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548265#comment-548265):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) Could you clarify the version of the ref file used for the plot? If that is the latest version, we noticed similar issues too and we are ready to deliver an updated version. If you would be willing to check the latest version before it being delivered, please let me know so I can share the location of the file. 


I would also appreciate it if you could confirm that this was not seen in the previous versions of the file, to understand where the issue is originating from.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548270#comment-548270):_

The strange features on the left of the image were not in version 11 but were in version 12. I'm also worried about the general left to right gradient. If the illumination pattern has a left/right gradient, then there is still a major problem with the solution.

I'd be fine with checking out a new version of the file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548279#comment-548279):_

Thank you for the clarification. The latest version of the file is stored here. Note that this version has one less coefficients than version 12.
/ifs/jwst/wit/niriss/tmorishita/linearity_May2021_rerevisit_C0positive/niriss_ref_linearity.fits

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548343#comment-548343):_

[^niriss_May2021.pdf]

This is the updated correction factor. The changes appear to be pretty small.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548535#comment-548535):_

My mistake. I've attached the correct version. Too much copy and paste. I thought it looked very similar but I somehow convinced myself that there were differences.

The latest version is very close to the 0011 version. The large anomalies on the left side have been removed but there is still a very large (~20%) left-right gradient. It's hard to understand how that the nonlinearity could have such a large global gradient.  This image is normalized to the median value. I'll post the actual correction factor next.

[^niriss_May2021.pdf]

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548539#comment-548539):_

The unnormalized correction factor is attached.

[^niriss_May2021.pdf]

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548555#comment-548555):_

Thank you. It's assuring to know that the latest version is close to the 0011 version.  Do you have the same plot for the 0011 version that can be shared here, so I can see how the left-to-right gradient compares to the previous version? 

Also, 
>  the value approximately at saturation
is this set constant over the detector, or taken from the saturation file for each pixel?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=548934#comment-548934):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) here are the plots of correction factor for version 11 and the new one, calculated at the saturation value taken from the satulation reference file at each pixel. To my eye, they look almost identical, though the median value is ~0.44% higher in the latter. If you are happy with this version, we will start the process to deliver it. Please let me know.

Regarding gradient, I'm attaching the same plots above but divided by the median value respectively. Again, these look very similar, so it seems that the issue is not originated from the specific method used in the latest version. 

Here I'm including [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk), to see if he has any additional comments.

!correction_all_ver11_2d.png|thumbnail!!correction_all_2d.png|thumbnail!

!correction_all_ver11_2d_grad.png|thumbnail!!correction_all_2d_grad.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549047#comment-549047):_

Yes, it is now very close to version 11. I started to write this ticket on version 11 but found that version 13 was the latest version. The variation in the correction factor is an order of magnitude higher than I expect and have seen. You should not see a left/right gradient or the picture frame in the NL correction factors. Can you post an image of the illumination pattern of the calibration image?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549065#comment-549065):_

here is the map of signals at frame number 150 just as an example.
!signal.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549120#comment-549120):_

This looks like a raw DN value image. It has significant structure that is in the bias. Can you show a CDS image?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549135#comment-549135):_

ah, right. Here is the map for ideal linearized signal rates, derived from the "forward" fitting. I just checked the previous version of the same map, and they look very similar. Note that we used the same input ramp file, so the similarity over the various output products is not a surprise.
!signal-1.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549151#comment-549151):_

Well, there is a clear problem here. The correction factor is correlated with the saturation file and the illumination pattern. Neither of them should be true. The saturation file has a separate issue but the NL file is wrong.
Can you point me to the raw images you used to derive the coefficients?

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549163#comment-549163):_

The raw image is placed here: 

/ifs/jwst/wit/niriss/tmorishita/linearity/raw/meanlong.fits
*This file is in the CV3 format (while all others presented here are in DMS), so you need to flip the array.

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549355#comment-549355):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) please see the attachment, updated map for the correction factor. This time the correction factor was calculated by using the latest version of the saturation file generated from the same code. (Previously I mistakenly used an old version of the saturation file when I created the map. Apology for making the situation confusing.) 

In this version, the L-to-R gradient clearly seen in version 11 (posted above, with "ver11" title) has almost completely removed. The map is not correlated with the input signal map that I posted earlier. With these improvements, we consider this version as deliverable to the reference repo, especially given that the previous one (ver13) shows some strange structure. I'd appreciate your thoughts or any other feedback for further improvement.

  !correction_all_2d_grad-1.png|thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=549961#comment-549961):_

[Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) This version is significantly improved over any previous version. I'd be fine with having this be the current version. I assume the matching saturation file will also be delivered. 
Even so, there are still problems. The picture frame is visible in the map and saturation pattern is also visible. Eddie Bergeron and I think this may be due to pushing the saturation limit close to the A/D limit of 64K. There are some problems with the A/D converters on the SIDECAR above 61K and below 5K. We need to address these issues with all the NIR instruments for cycle 1. I just wanted to mention that.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=550351#comment-550351):_

[Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) 
The directory you pointed to above :
/ifs/jwst/wit/niriss/tmorishita/linearity/raw/meanlong.fits
cannot be read by anyone expect yourself. Can you change the permissions?
Thanks

**Comment by stscijgbot-jp** [comment]
_Comment by [Takahiro Morishita](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tmorishita) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=550844#comment-550844):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) I changed the permissions of the directory. Please let me know if this still does not give you access to the file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2276?focusedCommentId=550855#comment-550855):_

I can get to the linearity directory but not it's subdirectory raw
