### ISSUE TITLE
Possibly incorrect computation of "crpix" (or offsets) in assign_wcs' wcs_from_footprints

### ISSUE THREAD

**Issue by mcara** [spacetelescope/jwst#6359]
In [`wcs_from_footprints`](https://github.com/spacetelescope/jwst/blob/82d5766b7e08c7e39d15dd3e6ec701b50d93995c/jwst/assign_wcs/util.py#L196), see https://github.com/spacetelescope/jwst/blob/82d5766b7e08c7e39d15dd3e6ec701b50d93995c/jwst/assign_wcs/util.py#L294-L298
input coordinates are shifted by the coordinates of the middle of the bounding box. In FITS WCS, this corresponds to CRPIX. 
Normally, the value of CRPIX is tied to CRVAL ("fiducial" point in this code). Setting CRPIX independently from CRVAL results in a shift in the coordinate system.

For the resample step this may not be relevant as long as input images are aligned relative to each other. However, this may result in incorrect WCS (in the absolute coordinate system, or, i.e., relative to GAIA) of the resampled product.

At first glance, fiducial point is computed as the mean of the cartesian spherical (on the celestial sphere) coordinates of the bounding boxes' corners (on the sky) and so computing "CRPIX" as mean of bounding boxes' corners of the images (in image coordinates - NOTE: this plane is tangent to the sphere) may seem like a reasonable estimate of CRPIX. However, IMO, this is very likely is not correct because the transformation from a tangent plane (image) to the spherical coordinates is non-linear.

**Comment by hbushouse** [comment]
Fixed by #6789
