### ISSUE TITLE
Turn on MacOS CI builds

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6375]
_Issue [JP-2295](https://jira.stsci.edu/browse/JP-2295) was created on JIRA by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

MacOS CI matrix job was turned off in

#6373

because the Github runners are flaky and slow.

If Github makes these more reliable, they should be turned back on, i.e revert the above PR.

**Comment by frosario** [comment]
Do you specifically need a MacOS feature, or can this be accomplished in linux builds as well?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2295?focusedCommentId=685826#comment-685826):_

Fixed by [#&#x2060;7498](https://github.com/spacetelescope/jwst/pull/7498).
