### ISSUE TITLE
Rename ResidualFringeModel to better match reftype name fringefreq

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6381]
_Issue [JP-2299](https://jira.stsci.edu/browse/JP-2299) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

To avoid confusion, and to keep with convention when defining reference models, reference model name generally match their CRDS reftype counterpart.

For model `ResidualFringeModel`, the CRDS reftype that this is being referred to as is `fringefreq`.  This is not causing any code/runtime issues. However, it does not match the above convention.

Suggestion is to rename `ResidualFringeModel` to `FringeFreqModel`.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2299?focusedCommentId=552524#comment-552524):_

Sounds reasonable to me; better now than later.

**Comment by jemorrison** [comment]
I will make the change
