### ISSUE TITLE
Level2 Associations

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#639]
Finalize Level2 associations.  Issues include
- [x] [Level2 association file naming scheme](https://aeon.stsci.edu/ssb/trac/jwst/ticket/203)
- [x] How the workflow will produce/use them
- [x] How the Level2b module is using them
    See implementation in comments.
- [x] Complete ToDo below

**Comment by stscieisenhamer** [comment]
# Resources
- [Background types discussion](https://confluence.stsci.edu/pages/viewpage.action?pageId=58786600#Level3FileNames(AssociationProducts)-Feb28th,2017-Associationsweeklymeeting(Backgrounds,Testdata))

**Comment by stscieisenhamer** [comment]
In discussions with @hbushouse, the level2 associations should be an allowed input for the calweb_spec/image2 module. The modules will loop through all the members, processing each member, using any extra attributes, such as background or imprint, for processing purposes.

From the SDP standpoint. the generator will generate a Level 2 association for each observation. The association will contain all the exposures of that observation. For each exposure that needs extra information, that information will be added to the member's attributes, such as background or imprint.

**Comment by hbushouse** [comment]
A couple of subtleties here:

1) imprint and dedicated background exposures will also appear as members with exptype=science, but with no additional attributes such as 'bkgexps' or 'imprint', so that they will also get processed through all of the steps of the pipeline like a normal exposure, producing a calibrated product.

2) collections of exposures from something like a dither or mosaic pattern that do NOT use any mechanisms such as nodded/dedicated backgrounds or imprint will still be built into a level-2b ASN file, and the level-2b pipeline will simply calibrate all of them one by one.

**Comment by stscieisenhamer** [comment]
@hbushouse So, there are two level2 modules: `spec2` and `image2`. Do we produce two level2 associations: one for each? Or is there/can there be a wrapper Level2b pipeline, `calwebb_level2` that wraps/decides which sub-pipeline to run per exposure? This way the looping through the association is done by the wrapper, and the individual `spec2|image2` routines do not have to.

Methinks the workflow, and even for user processing, having the wrapper pipeline would be much easier.

**Comment by sosey** [comment]
How does this connect into the WFSS pipeline which needs the association with the grism and imaging observations to do spec2 processing of the grisms?

**Comment by stscieisenhamer** [comment]
## Naming proposal
Level 3 associations are named as follows:
```
jw<ppppp>-<"o"ooo>_<GT-DATETIME>_<type>_<mmm>_asn.json
```
Depending on archive/fileset requirements, a proposal would be
```
jw<ppppp>-<"o"ooo>_<GT-DATETIME>_level2_asn.json
```
The `<type>` is simply set to `level2`. If it is determined that we need separate spec/image associations, this could be `level2-spec` and `level2-image`.

The `<"o"ooo>` designation is needed to differentiate each observation, since this is the workflow granularity.

There should be no need for the `<mmm>` sequence. There will only be one per observation.

Consistency-wise, this is easiest. However, it may be an issue that they look too much like the Level3 associations.

**Comment by sosey** [comment]
Maybe I'm just confused, trying to clarify in my head where the high level wfss wrapper fits into this scheme. See https://github.com/STScI-JWST/jwst/issues/598

**Comment by stscieisenhamer** [comment]
While working with #598, a possible simplification appears: Instead of handling level2 separate from level3, the info for both are combined into just the level3 format, but with the level2 information for each exposure listed as it currently is in level2, but just in the member lists for level3.

Workflow ramification: There would only be two calibration steps: calwebb_sloper for all exposures, and then `calwebb_all` for everything down line.  This `calwebb_all` would run the `[spec|image]2`, `calwebb_wfss`, and whatever other `calwebb` pipelines are needed.

The workflow "unit of data" would be the association candidate: OBSERVATION plus any other higher lever association, such as  WFSS, CORONOGRAPHC, and AMI.

Data ramifications:
- Because the level2a->2b processing would now be dependent on the existence of level3 association, not all level2a exposures may get further calibration.
- level2b calibrations can be created twice. The situation is for chopped, or off-target, backgrounds. In this situation, Level2b's would be produced for the OBSERVATION candidate. Then, when the background observation is available, the Level2b's would be re-created, with the background info, when the BACKGROUND candidate association is triggered.  This is, in principle, OK, but needs to be understood and accepted by DMS.

**Comment by stscieisenhamer** [comment]
# Example association
```
{
    "asn_rule": "Asn_MIRI_BkgChop",
    "targname": "2MASS-J00243075-6635527",
    "asn_pool": "jw82600_001_20160304T145416_pool",
    "program": "82600",
    "members": [{
                    "exptype": "SCIENCE",
                    "expname": "test_lrs1_rate.fits",
                    "bkgexps": [{"expname": "test_lrsbkg_rate.fits"}]
                },
                {
                    "exptype": "SCIENCE",
                    "expname": "test_lrs2_rate.fits",
                    "bkgexps": [{"expname": "test_lrsbkg_rate.fits"}]
                },
                {
                    "exptype": "SCIENCE",
                    "expname": "test_lrs3_rate.fits",
                    "bkgexps": [{"expname": "test_lrsbkg_rate.fits"}]
                },
                {
                    "exptype": "SCIENCE",
                    "expname": "test_lrs4_rate.fits",
                    "bkgexps": [{"expname": "test_lrsbkg_rate.fits"}]
                }
            ],
    "asn_type": "background",
    "asn_id": "a3002"
}
```

**Comment by stscieisenhamer** [comment]
## Question about format
Because of my CRS, I want to ask which format of level2 associations we do want to use, and document the reasoning.

The current one is described in [the comment above](https://github.com/STScI-JWST/jwst/issues/639#issuecomment-288224078).

The other option is to take an approach similar to Level3, by bringing in the `products` list. An example appears below. Characteristics of the example are:
- Three exposures being processed
- First one is the degenerate case, which motivated the current simpler example above.
- Second is when there are backgrounds present
- Third is with a background and imprint/leak image

The CON reason, and reason for the simpler list, was because of the degenerate case, which will be the majority of exposures.

The PRO reasons would be:
- Matches the Level3 formatting, making use consistent, documentation consistent, etc.
- The output name is a template/prefix, just like level3. I believe this is actually necessary because Level2b processing could produce different outputs(?).
- Satisfies my OCD.

@hbushouse Thoughts?
```
{
    "asn_rule": "Asn_MIRI_BkgChop",
    "target": "1",
    "asn_pool": "jw82600_001_20160304T145416_pool",
    "program": "82600",
    "asn_type": "spec2",
    "asn_id": "a3002",
    "products": [
        {
            "name": "test_lrs1",
            "members": [
                {
                    "expname": "test_lrs1_rate.fits",
                    "exptype": "SCIENCE",
                },
            ],
        },
        {
            "name": "test_lrs2",
            "members": [
                {
                    "expname": "test_lrs2_rate.fits",
                    "exptype": "SCIENCE",
                },
                {
                    "expname": "test_lrs2_bkg_rate.fits",
                    "exptype": "BACKGROUND",
                },
            ],
        },
        {
            "name": "test_lrs3",
            "members": [
                {
                    "expname": "test_lrs3_rate.fits",
                    "exptype": "SCIENCE",
                },
                {
                    "expname": "test_lrs3_background_rate.fits",
                    "exptype": "BACKGROUND",
                },
                {
                    "expname": "test_lrs3_leak_rate.fits",
                    "exptype": "LEAK",
                },
            ],
        },
    ]
}
```

**Comment by hbushouse** [comment]
![image](https://cloud.githubusercontent.com/assets/12860084/24862240/dbf49cb8-1dc9-11e7-928a-111f1b80703c.png)

**Comment by hbushouse** [comment]
This does obviously have the PRO of keeping a consistent format between level-2 and level-3 tables. It gets around the fact that there's no single output product generated by declaring an output product for each input product. Of course it does modify the structure of how we had been planning to declare background and imprint exposures. We had previously listed them as additional attributes for a given input member, but in this scheme they're just listed as additional members, but their role is identified via their exptype. That too makes the whole structure of the ASN simpler, rather than defining additional attributes like "bkgexps" and "imprint". For WFSS calspec2 ASN's, we could use exptypes of "catalog" and "segmentation" to designate those input types.

So overall I think I like it. We would want, however, to also have background and imprint exposures listed within their own products, with exptype=science, so that they also get processed by the pipeline. E.g.
`
  {"name": "test_lrs3_background",
   "members": [
       {"expname": "test_lrs3_background_rate.fits",
        "exptype": "SCIENCE"}
    ]
   }`

We'll also obviously need to modify what's been implemented so far in calspec2 to handle this new scheme, but that should not be much work. Again, I like the overall consistency of the format for level-2 and level-3 and this takes more advantage of the exptype value.

**Comment by stscieisenhamer** [comment]
`calwebb_sloper` can create Level2a files with the following types (possibly more?):
- `rate`
- `rateints`
- `ramp`

The generator needs to know which one to use for each particular exposure, solely from what is available in the pool. Is this actually possible? If so, what is/are the key(s)?

**Comment by hbushouse** [comment]
_ramp products are an intermediate output of calwebb_sloper and hence will never be used in subsequent processing (it's the fully corrected 4D ramp data, before converting to count rates).

_rate is the most common product to be passed along to level-2b processing. It is a 2D countrate product, averaged over all integrations, for an exposure.

_rateints is produced whenever nintegrations>1, but is only used for downstream processing when the exposure is part of a time-series observation, where users want data for each integration (as opposed to averaged over integrations).

So the default for the generator would be to always use _rate products as input to level-2b ASN tables, but use _rateints when an exposure has one of the following EXP_TYPE values:

NRC_TSIMAGE
NRC_TSGRISM
NRS_BRIGHTOBJ
NIS_SOSS
MIR_LRS-SLITLESS

**Comment by stscieisenhamer** [comment]
All related issues discussed in this story have been completed!
