### ISSUE TITLE
ImageModel cannot find the default schema in v1.3.3

### ISSUE THREAD

**Issue by victoriastrait** [spacetelescope/jwst#6392]
Hi, when creating an ImageModel from a file, assuming the default schema=None, e.g., ImageModel(file), the following error is returned. It looks like the schema has been moved or deleted. 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-bb85a570dba3> in <module>
      7 
      8 for file in rate_files[:6]: # for each of the first 6 rate files:
----> 9     img = ImageModel(file) # get a datamodel of it
     10     pupil = img.meta.instrument.pupil # This seems more like the filter [from the metadata]
     11     filt = img.meta.instrument.filter # This is what grism it is

/opt/conda/envs/python3/lib/python3.8/site-packages/stdatamodels/model_base.py in __init__(self, init, schema, memmap, pass_invalid_values, strict_validation, validate_on_assignment, ignore_missing_extensions, **kwargs)
    162             else:
    163                 # Create an AsdfFile so we can use its resolver for loading schemas
--> 164                 schema = asdf_schema.load_schema(self.schema_url, resolve_references=True)
    165 
    166         self._schema = mschema.merge_property_trees(schema)

/opt/conda/envs/python3/lib/python3.8/site-packages/asdf/schema.py in load_schema(url, resolver, resolve_references, resolve_local_refs)
    455     # expect that they're changing the schema everywhere.
    456     return copy.deepcopy(
--> 457         _load_schema_cached(url, resolver, resolve_references, resolve_local_refs)
    458     )
    459 

/opt/conda/envs/python3/lib/python3.8/site-packages/asdf/schema.py in _load_schema_cached(url, resolver, resolve_references, resolve_local_refs)
    462 def _load_schema_cached(url, resolver, resolve_references, resolve_local_refs):
    463     loader = _make_schema_loader(resolver)
--> 464     schema, url = loader(url)
    465 
    466     # Resolve local references

/opt/conda/envs/python3/lib/python3.8/site-packages/asdf/schema.py in load_schema(url)
    373         # If not, fall back to fetching the schema the old way:
    374         url = resolver(str(url))
--> 375         return _load_schema(url)
    376     return load_schema
    377 

/opt/conda/envs/python3/lib/python3.8/site-packages/asdf/schema.py in _load_schema(url)
    346 @lru_cache()
    347 def _load_schema(url):
--> 348     with generic_io.get_file(url) as fd:
    349         if isinstance(url, str) and url.endswith('json'):
    350             json_data = fd.read().decode('utf-8')

/opt/conda/envs/python3/lib/python3.8/site-packages/asdf/generic_io.py in get_file(init, mode, uri, close)
    995                 fd = atomicfile.atomic_open(realpath, realmode)
    996             else:
--> 997                 fd = open(realpath, realmode)
    998             fd = fd.__enter__()
    999             return RealFile(fd, mode, close=True, uri=uri)

FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/python3/lib/python3.8/site-packages/asdf/schemas/stsci.edu/jwst_datamodel/image.schema.yaml'

**Comment by nden** [comment]
@victoriastrait Were you able to fix the installation or is this still a problem?
