### ISSUE TITLE
Get Association Candidate information into the exposure level headers

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#641]
Because of the importance association candidates information is to the creation of associations, and the need for the user to be able to [create associations](#640) from their exposure files, it would seem that having the association candidate information place as header keywords into, at least, Level2a exposure files, would be of great use.  This would give the user the ability to reproduce association pools and tables as they would have been from the workflow.

**Comment by stscieisenhamer** [comment]
@hbushouse thoughts?

**Comment by hbushouse** [comment]
What type(s) of candidate info do you have in mind here, for including in the science product headers? Things such as the candidate ID and the type? I guess that having that kind of info would make it possible for an off-line tool to scan the keyword info in a bunch of files that a user has sitting somewhere and try to build associations from them based on those ID's and other meta data. Is that what you had in mind?

**Comment by stscieisenhamer** [comment]
The exact information would be that contained in the Association Pool column ASN_CANDIDATE. This is the list of candidates and candidate types that an exposure belongs to.

**Comment by stscieisenhamer** [comment]
If agreed upon, the question is: who/where does the population occur? Ideally I would like to see it occur as early as possible, Level1b?, and by SDP.

**Comment by melanieclarke** [comment]
Closing - there are offline tools that can be used to make associations from pools or lists of FITS files (asn_make_pool, asn_generate, asn_from_list).
