### ISSUE TITLE
Breakthrough bad pixels with default values of "0"

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6418]
_Issue [JP-2311](https://jira.stsci.edu/browse/JP-2311) was created on JIRA by [Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez):_

There are many breakthrough bad pixels with default values of "0" that are not marked as "do not use" by the JWST pipeline. Attach are a couple of examples of  pixels with default values of "0.0" without the "do not use mask" in particular:
 # A pixel with a value of "0" close to the center of the PSF that has the flags: linearity correction not available, bias variance large and flat variance large. However, this pixel shows an expected up-the-ramp behavior so I am not sure why the pipeline assigned a value of "0" having workable groups. 
 # There is a similar pixel as above but farther from the PSF. 
 # Another pixel, with a flag as dead pixel but without the do not use flag. This pixel has a value 0f -81 Mjy/sr, clearly a bad pixel. 

In the screenshots, blue pixels are those flagged as "Do not use". As you can see from some of the images, there are more than a few bad pixels without the "do not use" flag. 

 

JWST Pipeline Version 1.3.3

 

Data Available:

/ifs/jwst/tel/MIMF_KDP_Practice_Sept2021/OTE-29/output/JWST_1.3.3/jw01166018001_02101_00001_g1_cal.fits [uncal,rate]

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558340#comment-558340):_

I looked at the data and the issue seems to be for those pixels that have a rate = 0, but a DQ value that does not have the DO_NOT_USE flag set. For these pixels the NO_LIN_CORR flag is set. Looking at the linearity correction coefficients for these pixels, all the coefficients = 0, but the DQ flag for this pixel in the linearity correction = 0. Applying a linearity correction with coefficients =0 results in a linearity corrected value of 0. I also noticed that the reference pixels have all their linearity coefficients = 0. The linearity correction file needs to be updated.  The DQ flag  in the reference file for pixels with all the coefficients = 0 should also have the DO_NOT_USE flag set. 

For pixels that you just don't want the linearity correction todo  anything- in the case of reference pixels - the linear term (second coefficient in the reference file) needs to be set to 1. 

[Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) if you agree with this summary I will close this ticket - one should be opened to fix the FGS linearity reference file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558341#comment-558341):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) it wouldn't hurt to check to see what kind of hooks are already in the linearity step to handle situations related to bad or missing data in the linearity ref file and perhaps add yet another hook that sets the DO_NOT_USE flag for pixels that have all zero coeffs and/or the NO_LIN_CORR flag.  You're right that the correct solution is have the DO_NOT_USE flag set in the linearity ref file itself, but it never hurts to cover all the bases.

**Comment by stscijgbot-jp** [comment]
_Comment by [Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558369#comment-558369):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Thanks for looking into this and I agree with your solution. Are you going to open the ticket to fix the FGS linearity reference file? if so, can you add me to the watchlist? 

Thanks!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558396#comment-558396):_

I don't think that changing the FGS linearity reference file coefficients fixes this problem. If there is no correction for the pixel, the DQ DO NOT USE bit needs to be set. Jane is right that setting the linear term to 1 will prevent the pixel from being set to zero, but that might be worse than were we are now. Now we get pixels with 0 slope when the NL correction failed for that pixel. That allowed Marcio to see there was a problem. If we just no-op the linearity correction step, we get uncorrected slopes that we fit ramps to. That is harder to notice than zero slope pixels.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558413#comment-558413):_

If the FGS linearity reference file had the DO_NOT_USE flag set for pixels with all linearity coefficient =0, then we would not have this problem of rate values =0 - but the DO_NOT_USE flag not set. 

We can certainly add an extra check in the linearity step code that checks if all the coefficients =0 then we set the DO_NOT_USE for that pixel. I do worry about unintended consequences if we do this. For the FGS linearity correction the reference pixels all have coefficients of 0 so we would wipe out the reference pixel values, but since the refpix step for FGS occurs before linearity it really does not matter for this case. 

I believe only MIRI has the refpix step after the linearity step. The current MIRI linearity correction for reference pixel has coefficients all 0. This is a mistake that I have been meaning to fix.  

So essentially it comes down to making sure the reference files are set correctly for the linearity step. 
For now I will add a check in the linearity step and I will also open a ticket to get the FGS linearity reference files updated.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=559462#comment-559462):_

On further inspection the pixels with a rate =0 are 0 because the linearity coefficients are all zero (as previous report) and the linearity dq flag = 0, BUT  final dq flag for the pixel has the NO_LIN_CORR set. This is because the MASK reference file applied in the dq_init has the NO_LIN_CORR flag set for these pixels.  The linearity step only looks are the DQ flags for the linearity reference file.  The linearity reference file needs to be updated for these pixels to have  the DQ flag set to  NO_LIN_CORR. Also it might lead to less confusion in the future if the DQ  in the MASK file does not set NO_LIN_CORR - or at a minimum if it does then the corresponding pixel dq flag in the linearity correction reference file should also have NO_LIN_CORR set.



[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) in the linearity code in STCAL if the correction contains NaNs then the lin correction DQ flag is set to NO_LIN_CORR and the linearity coefficients are set to values that will not change the data.  We should add a check if all the coefficient = 0 and do the same thing. Can I edit code that is STCAL or is that someone else ? 



In keeping with how the pipeline works in other cases - the pixels with all zeros for linearity coefficients the NO_LIN_CORR would be set but not the DO_NOT_USE. It has been left to the instrument teams to set that dqflag in the reference file. If this flag is not set in the linearity reference file when there might be confusion down the line with pixels that do not have a linearity correction set and are not flagged as DO_NOT_USE. I will file a ticket for the FGS linearity reference file for these pixels and how the mask reference file  has NO_LIN_CORR for these pixel.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560385#comment-560385):_

JP-2341 was filed to have the FGS linearity reference pixels updated to include NO_LIN_CORR (+DO_NOT_USE) for pixels with no linearity coefficients derived.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560645#comment-560645):_

The pixels which lack a good set of linearity coefficients should have the coefficients set to zero except for the linear coefficient in the correction which should be set to 1, so these pixels have no change in the linearity correction step.  This is the case for NIRISS for example.  If indeed the guider linearity reference file has pixels where all the values are zero then that is a mistake in the reference file.  That was not intended when I had Mike Wolfe make the reference file.  These pixels were not given a DO_NOT_USE flag because for the normal guiding functions the issue is just whether there is signal and so the pixels to avoid are either things like RC pixels or things like dead/low QE/open pixels.  It was not intended to flag pixels that fail the linearity fitting but have no sign of anomalous behaviour in the darks and the flats as DO_NOT_USE because they are OK for guiding even if they cannot be used for science after the pipeline reduction.  Maybe this was not the right decision to make.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560743#comment-560743):_

The linearity reference file I have been using (taken from CRDS) is jwst_fgs_linearity_0014.fits
There are 2245 science pixels that have a linear linearity coefficient of zero and the linearity DQ flag is not flagged with "NO_LIN_CORR'. These do not include reference pixels.

They are scattered throughout the detector and are very easy to see when using DS9 and looking at the linear coefficient plane. 
They might be hard to see in this image since they are often single isolated pixels: but here is an image of the central part of the detector for linear linearity coefficient
Zero values are orange. 

!Screen Shot 2021-12-01 at 9.34.28 AM.png|width=369,height=234,thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560745#comment-560745):_

Yes I am looking at the files now and there is clear some issue compared to what I had originally asked for way back when.  The pixels flagged with "NO_LIN_CORR" do have coefficients listed – unless I am doing something wrong in my code which I have to double-check.  The pixels with all zero values have no flag associated with them.  All the reference pixels have all zero coefficients which is not what I would want, but the illuminated ones with all zeros are the bigger issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=564305#comment-564305):_

Updates to the linearity step to add a DQ flag to pixels with a linear correction term of zero have been included in #6509 and <https://github.com/spacetelescope/stcal/pull/65.> So the Cal part of the updates for this are now considered complete.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=564306#comment-564306):_

What DQ flag is added in this case?  As noted before, the issue should be corrected in the linearity reference file so that those pixels without a valid linearity correction have the coefficients that do not change the ramp, and have a NO_LIN_COEFF flag.  I was working with Pierre to fix this since it is clearly a mistake in making the reference file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=564307#comment-564307):_

It adds the NO_LIN_CORR flag.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=568543#comment-568543):_

Updates to Cal code to handle these issues in a more robust way were included in B7.9. Remaining work is in the hands of one or more instrument teams to review and update linearity reference files. As such, can this ticket be reassigned for the ref file work or closed in favor of a new ticket covering only the ref file work?

**Comment by hbushouse** [comment]
Fixed in #6509

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=555449#comment-555449):_

I'm pretty sure this is a duplicate of JP-2292. The current FGS bad pixel masks almost never set the DO_NOT_USE bit.

**Comment by stscijgbot-jp** [comment]
_Comment by [Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=555478#comment-555478):_

[Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) This seems to be the case for "dead pixels" without the DO_NOT_USE flag but what about pixels with default values equal to "0" but with reasonable slopes. A value of zero would indicate not workable groups for the pipeline in the exposure which doesn't seems to be the case. These are values assigned to pixels, independent of the DQ mask, is this correct?

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=555492#comment-555492):_

I don't understand what you mean by default values of zero but with reasonable slopes. MIRAGE is not designed to be a high fidelity simulator of non-ideal pixels. That means that what we see in flight will look a lot different than what we see with MIRAGE.

**Comment by stscijgbot-jp** [comment]
_Comment by [Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=555499#comment-555499):_

It is my understanding that the JWST pipeline will assign a value of zero as default when there are not workable groups in the ramp to perform any of the pipeline steps, for example, when all groups are saturated in an exposure. In this example, there is a pixel with a value set to zero by the pipeline but with a good slope, i.e., good groups for the pipeline to work with. So, I don't understand why the pipeline setup that value.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=555523#comment-555523):_

We (SCSB) will take a look at the level-2a "ramp" and "rate" products and see what the history is for those pixels that have zero value without a DO_NOT_USE flag.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=555536#comment-555536):_

Rate images are not affected by the DO NOT USE flag. To get a zero slope something else must be wrong.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558340#comment-558340):_

I looked at the data and the issue seems to be for those pixels that have a rate = 0, but a DQ value that does not have the DO_NOT_USE flag set. For these pixels the NO_LIN_CORR flag is set. Looking at the linearity correction coefficients for these pixels, all the coefficients = 0, but the DQ flag for this pixel in the linearity correction = 0. Applying a linearity correction with coefficients =0 results in a linearity corrected value of 0. I also noticed that the reference pixels have all their linearity coefficients = 0. The linearity correction file needs to be updated.  The DQ flag  in the reference file for pixels with all the coefficients = 0 should also have the DO_NOT_USE flag set. 

For pixels that you just don't want the linearity correction todo  anything- in the case of reference pixels - the linear term (second coefficient in the reference file) needs to be set to 1. 

[Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) if you agree with this summary I will close this ticket - one should be opened to fix the FGS linearity reference file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558341#comment-558341):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) it wouldn't hurt to check to see what kind of hooks are already in the linearity step to handle situations related to bad or missing data in the linearity ref file and perhaps add yet another hook that sets the DO_NOT_USE flag for pixels that have all zero coeffs and/or the NO_LIN_CORR flag.  You're right that the correct solution is have the DO_NOT_USE flag set in the linearity ref file itself, but it never hurts to cover all the bases.

**Comment by stscijgbot-jp** [comment]
_Comment by [Marcio Melendez Hernandez](https://jira.stsci.edu/secure/ViewProfile.jspa?name=melendez) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558369#comment-558369):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Thanks for looking into this and I agree with your solution. Are you going to open the ticket to fix the FGS linearity reference file? if so, can you add me to the watchlist? 

Thanks!

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558396#comment-558396):_

I don't think that changing the FGS linearity reference file coefficients fixes this problem. If there is no correction for the pixel, the DQ DO NOT USE bit needs to be set. Jane is right that setting the linear term to 1 will prevent the pixel from being set to zero, but that might be worse than were we are now. Now we get pixels with 0 slope when the NL correction failed for that pixel. That allowed Marcio to see there was a problem. If we just no-op the linearity correction step, we get uncorrected slopes that we fit ramps to. That is harder to notice than zero slope pixels.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=558413#comment-558413):_

If the FGS linearity reference file had the DO_NOT_USE flag set for pixels with all linearity coefficient =0, then we would not have this problem of rate values =0 - but the DO_NOT_USE flag not set. 

We can certainly add an extra check in the linearity step code that checks if all the coefficients =0 then we set the DO_NOT_USE for that pixel. I do worry about unintended consequences if we do this. For the FGS linearity correction the reference pixels all have coefficients of 0 so we would wipe out the reference pixel values, but since the refpix step for FGS occurs before linearity it really does not matter for this case. 

I believe only MIRI has the refpix step after the linearity step. The current MIRI linearity correction for reference pixel has coefficients all 0. This is a mistake that I have been meaning to fix.  

So essentially it comes down to making sure the reference files are set correctly for the linearity step. 
For now I will add a check in the linearity step and I will also open a ticket to get the FGS linearity reference files updated.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=559462#comment-559462):_

On further inspection the pixels with a rate =0 are 0 because the linearity coefficients are all zero (as previous report) and the linearity dq flag = 0, BUT  final dq flag for the pixel has the NO_LIN_CORR set. This is because the MASK reference file applied in the dq_init has the NO_LIN_CORR flag set for these pixels.  The linearity step only looks are the DQ flags for the linearity reference file.  The linearity reference file needs to be updated for these pixels to have  the DQ flag set to  NO_LIN_CORR. Also it might lead to less confusion in the future if the DQ  in the MASK file does not set NO_LIN_CORR - or at a minimum if it does then the corresponding pixel dq flag in the linearity correction reference file should also have NO_LIN_CORR set.



[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) in the linearity code in STCAL if the correction contains NaNs then the lin correction DQ flag is set to NO_LIN_CORR and the linearity coefficients are set to values that will not change the data.  We should add a check if all the coefficient = 0 and do the same thing. Can I edit code that is STCAL or is that someone else ? 



In keeping with how the pipeline works in other cases - the pixels with all zeros for linearity coefficients the NO_LIN_CORR would be set but not the DO_NOT_USE. It has been left to the instrument teams to set that dqflag in the reference file. If this flag is not set in the linearity reference file when there might be confusion down the line with pixels that do not have a linearity correction set and are not flagged as DO_NOT_USE. I will file a ticket for the FGS linearity reference file for these pixels and how the mask reference file  has NO_LIN_CORR for these pixel.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560385#comment-560385):_

JP-2341 was filed to have the FGS linearity reference pixels updated to include NO_LIN_CORR (+DO_NOT_USE) for pixels with no linearity coefficients derived.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560645#comment-560645):_

The pixels which lack a good set of linearity coefficients should have the coefficients set to zero except for the linear coefficient in the correction which should be set to 1, so these pixels have no change in the linearity correction step.  This is the case for NIRISS for example.  If indeed the guider linearity reference file has pixels where all the values are zero then that is a mistake in the reference file.  That was not intended when I had Mike Wolfe make the reference file.  These pixels were not given a DO_NOT_USE flag because for the normal guiding functions the issue is just whether there is signal and so the pixels to avoid are either things like RC pixels or things like dead/low QE/open pixels.  It was not intended to flag pixels that fail the linearity fitting but have no sign of anomalous behaviour in the darks and the flats as DO_NOT_USE because they are OK for guiding even if they cannot be used for science after the pipeline reduction.  Maybe this was not the right decision to make.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560743#comment-560743):_

The linearity reference file I have been using (taken from CRDS) is jwst_fgs_linearity_0014.fits
There are 2245 science pixels that have a linear linearity coefficient of zero and the linearity DQ flag is not flagged with "NO_LIN_CORR'. These do not include reference pixels.

They are scattered throughout the detector and are very easy to see when using DS9 and looking at the linear coefficient plane. 
They might be hard to see in this image since they are often single isolated pixels: but here is an image of the central part of the detector for linear linearity coefficient
Zero values are orange. 

!Screen Shot 2021-12-01 at 9.34.28 AM.png|width=369,height=234,thumbnail!

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=560745#comment-560745):_

Yes I am looking at the files now and there is clearly some issue compared to what I had originally asked for way back when.  The pixels flagged with "NO_LIN_CORR" do have coefficients listed – unless I am doing something wrong in my code which I have to double-check.  The pixels with all zero values have no flag associated with them.  All the reference pixels have all zero coefficients which is not what I would want, but the illuminated ones with all zeros are the bigger issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=564305#comment-564305):_

Updates to the linearity step to add a DQ flag to pixels with a linear correction term of zero have been included in #6509 and <https://github.com/spacetelescope/stcal/pull/65.> So the Cal part of the updates for this are now considered complete.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=564306#comment-564306):_

What DQ flag is added in this case?  As noted before, the issue should be corrected in the linearity reference file so that those pixels without a valid linearity correction have the coefficients that do not change the ramp, and have a NO_LIN_COEFF flag.  I was working with Pierre to fix this since it is clearly a mistake in making the reference file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=564307#comment-564307):_

It adds the NO_LIN_CORR flag.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=568543#comment-568543):_

Updates to Cal code to handle these issues in a more robust way were included in B7.9. Remaining work is in the hands of one or more instrument teams to review and update linearity reference files. As such, can this ticket be reassigned for the ref file work or closed in favor of a new ticket covering only the ref file work?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2311?focusedCommentId=578167#comment-578167):_

Closing. Remaining ref file updates to be done via JP-2341 and possibly other JP tickets.
