### ISSUE TITLE
extract_1d bug for NIRSpec IFU cubes with internal_cal coordinates

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6434]
_Issue [JP-2322](https://jira.stsci.edu/browse/JP-2322) was created on JIRA by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol):_

I'm encountering a spec2 pipeline crash at the extract_1d step when processing IFU data taken with an internal lamp. The CRDS rmap for the step has not yet been updated to handle internal lamps, so I specified a local reference file using an override. It's possible that I did not modify the reference file correctly (the only thing I changed was the exposure type, from NRS_IFU to NRS_LAMP). However, the reference file is asdf format, while the error implies that the pipeline is expecting an image format, which seems strange.

The full error message:

--------------------------------------------------------------------------- RuntimeError Traceback (most recent call last) /var/folders/md/d_53ff791wqg6ydy43qlywf000014q/T/ipykernel_66691/2865387647.py in <module>  8 step.save_results = True  9 step.output_dir = output_dir ---> 10 result = step(filename) ~/anaconda3/envs/jwst_dev/lib/python3.9/site-packages/stpipe/step.py in run(self, *args)  411 self.prefetch(*args)  412 try: --> 413 step_result = self.process(*args)  414 except TypeError as e:  415 if "process() takes exactly" in str(e): ~/anaconda3/envs/jwst_dev/lib/python3.9/site-packages/jwst/extract_1d/extract_1d_step.py in process(self, input)  267 self.log.info(f'Using APCORR file \{apcorr_ref}')  268 --> 269 result = extract.run_extract1d(  270 input_model,  271 extract_ref, ~/anaconda3/envs/jwst_dev/lib/python3.9/site-packages/jwst/extract_1d/extract.py in run_extract1d(input_model, extract_ref_name, apcorr_ref_name, smoothing_length, bkg_fit, bkg_order, bkg_sigma_clip, log_increment, subtract_background, use_source_posn, was_source_model)  2675 ref_dict['need_to_set_to_complete'] = False  2676 -> 2677 output_model = do_extract1d(  2678 input_model,  2679 ref_dict, ~/anaconda3/envs/jwst_dev/lib/python3.9/site-packages/jwst/extract_1d/extract.py in do_extract1d(input_model, extract_ref_dict, apcorr_ref_model, smoothing_length, bkg_fit, bkg_order, bkg_sigma_clip, log_increment, subtract_background, use_source_posn, was_source_model)  3018 source_type = "UNKNOWN"  3019 -> 3020 output_model = ifu.ifu_extract1d(  3021 input_model, extract_ref_dict, source_type, subtract_background,  3022 bkg_sigma_clip, apcorr_ref_model ~/anaconda3/envs/jwst_dev/lib/python3.9/site-packages/jwst/extract_1d/ifu.py in ifu_extract1d(input_model, ref_dict, source_type, subtract_background, bkg_sigma_clip, apcorr_ref_model)  91 slitname = "ANY"  92 ---> 93 extract_params = get_extract_parameters(ref_dict, bkg_sigma_clip, slitname)  94  95 if subtract_background is not None: ~/anaconda3/envs/jwst_dev/lib/python3.9/site-packages/jwst/extract_1d/ifu.py in get_extract_parameters(ref_dict, bkg_sigma_clip, slitname)  286 if not foundit:  287 log.error("No match for slit name %s in reference image", slitname) --> 288 raise RuntimeError("Specify slit name or use 'any' in ref image.")  289  290 else: RuntimeError: Specify slit name or use 'any' in ref image.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557901#comment-557901):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I need to get up to speed with how the pipeline processes NIRSpec Lamp data.  In the directory of the data you only have a rate file not a cal file - so the calspec 2 pipeline is not run on this data ? I am guessing the assign_wcs step is. I first looked at the s3d file to see if cube_build was creating this file correctly. Could you look at it - is that what you expect  ? I am not sure how it should look - is it supposed to have bright spots on the IFU planes ? I don't understand the IFU planes

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557908#comment-557908):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I was running the full spec2 pipeline - no cal file was generated because of the crash (it is output only at the very end). I did look at the cube, and at least qualitatively speaking, it seemed ok.

I also had to use a custom pipeline parameter file in order to turn off some steps, since we haven't yet updated CRDS for these lamp cases. I just copied that file to the central store directory in case you need to take a look.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557918#comment-557918):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) A few more questions to fill in some of my lack of knowledge of NIRSpec LAMP data. I have a picture of the rate image and an arbitrary wavelength plane of the s3d file (516 wavelength plane). Are the bright rectangles on the IFU plane image open msg shutters ? If that the streaks in the rate image ?   !image-2021-11-09-15-39-10-805.png|width=493,height=254!

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557973#comment-557973):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) yes, those bright spaxels are from the traces of the failed open MSA shutters.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558353#comment-558353):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I think I am running the spec2 pipeline wrong for this data. I get a different error than you but I think I must be doin g something wrong. . I got the jwst_nirspec_extract1d_new_ifulamp.asdf reference file. I ran spec2 like this:

strun jwst_nirspec_pars-spec2pipeline_linelamp_ifu_new.asdf jwdata0010010_11010_0001_NRS1_lamp_rate.fits --steps.extract_1d.override_apcorr='jwst_nirspec_extract1d_new_ifulampsdf'

 

I get this error - 

raise RuntimeError("extract1d reference file must be JSON or a FITS image.")

RuntimeError: extract1d reference file must be JSON or a FITS image.

 

How did you file spec2 pipeline on this data.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558357#comment-558357):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) both the apcorr and extract_1d reference files need to be specified - the pipeline crashes because it can't find a valid match for either (even though an apcorr file isn't actually needed). We're in the process of modifying the CRDS selection rules to fix this, but that won't take effect until after the software freeze. I forgot to put the apcorr file on central store; it's there now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558429#comment-558429):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly)  [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham)  [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) 
A fix for this is to add 'NRS_LAMP' as one of the exptypes in extract.py (line 138).
I did this and it works. Bit I wonder if there is something smarter we could do. Like first check the file of reference we have (asdf, json or fits).

 I have cut and pasted the code that is reading in the extract1d reference file to show what is going on. Without NRS_LAMP as an option it goes through the options and opens the reference file as a fd = datamodels.MultiExtract1dImageModel(refname). No error is give here. Should it ? The multiextract1d.schema.yaml file is expecting an input fits file. 



if refname == "N/A":
    ref_dict = None
 elif exptype in ['MIR_MRS', 'NRS_IFU', 'NRS_LAMP']:             <--------- Adding this fixes the problem
 # read in asdf file
    extract_model = datamodels.Extract1dIFUModel(refname)
    ref_dict = {}
    ref_dict['ref_file_type'] = FILE_TYPE_ASDF
    ref_dict['ref_model'] = extract_model

else:
 # Try reading the file as JSON.
    fd = open(refname)
    try:
        ref_dict = json.load(fd)
        ref_dict['ref_file_type'] = FILE_TYPE_JSON
        fd.close()
    except (UnicodeDecodeError, JSONDecodeError):
        fd.close()
        # Try opening the file as a reference image.
       try:
           fd = datamodels.MultiExtract1dImageModel(refname).           <------------------ Code gets here (WITHOUT ABOVE FIX)
          ref_dict = \{'ref_file_type': FILE_TYPE_IMAGE, 'ref_model': fd}
       except OSError:                                                                                 <------------------- OSError does not occur (should it?) 
          log.info("The extract1d reference file should be JSON or FITS.")
          log.error(f"Don't know how to read \{refname}.")
          raise

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558611#comment-558611):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)   There is a line of code in extract.py (module do_extract1d) that sets the types of data to turn on use_source_posn

Clipped code: 

# Turn use_source_posn on for types that should use it by default
 if use_source_posn is None:
    if exp_type in ['MIR_LRS-FIXEDSLIT', 'MIR_MRS', 'NRS_FIXEDSLIT', 'NRS_IFU', 'NRS_MSASPEC']:
    use_source_posn = True
    log.info(f"Turning on source position correction for exp_type = \{exp_type}")

 

Should I add NRS_LAMP to this set to run on use_source_posn ?
For lamp data I am not sure you even have an concept of use_source_posn

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558650#comment-558650):_

I'm pretty sure that the `use_source_posn` operation uses the RA/Dec of the target to estimate the location of the source in image/detector space and center the extraction at that location. I doubt that target RA/Dec would have any useful or real meaning for lamp exposures and hence could lead to very wacky results.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558732#comment-558732):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) for the special spec2 parameter file you had where the data is located the apply_apcorr is set to false. But there is a special apcorr reference file in the directory. Do you intend to ever apply and apcorr ref file to NRS_LAMP - or will it always be turned off ? 

If you want to have to option to apply it - I have to add a hook in extract.py for this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558856#comment-558856):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I can get the NRS1 data to process through the spec2 pipeline, but the NRS2 is failing.

I have saved the ifu cube. I am pretty sure the problem is because for NRS1 the input_model.meta.target.source_type is undefined

so it defaults to 'EXTENDED', but the NRS2 source type is POINT.

I am assuming that is wrong.  I will investigate why it gets set to POINT.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558870#comment-558870):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)

For this data there are 2 files, one for NRS1 and one for NRS2. The special parameter file to process this data - skips the srctype step.

But somehow after cube_build the s3d file (input to extract_1d) has SOURCE_TYPE = POINT for the NRS2 data and it is undefined for the NRS1 data (so it defaults to EXTENDED). Both have SCRTYAPT = UNKNOWN.
Any idea where SOURCE_TYPE could be getting set to POINT.  I will save all the results from the STEPS and see where it get sets to POINT.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558891#comment-558891):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) note that there is no way to specify the source type in APT for any lamp exposure (NRS_LAMP or autocals), so SRCTYAPT will always be UNKNOWN in these cases. The pipeline should just automatically default to EXTENDED. However, if srctype needs to be run in order to avoid any ambiguity, we can always add that to the parameter file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558899#comment-558899):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I just think something is wrong with the NRS2 file.
I opened the rate file and printed out  source_type and it was POINT. That does not make sense to me.  Since no other steps touch this value, it is getting passed onto s3d file and then extract_1d thinks it is POINT and goes down a line code that results in an error. 

m2 = datamodels.open('jwdata0010010_11010_0001_NRS2_lamp_rate.fits')

In [**14**]: m2.meta.target.source_type

Out[**14**]: 'POINT'

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558903#comment-558903):_

Because the src_type step isn't run until calwebb_spec2 (after the rate product is created) the SRCTYPE keyword should not be set at all in the rate file. At most it could have SRCTYAPT='UNKNOWN', indicating that the source type was not designated in the APT. Given that condition, the src_type step would then use the appropriate default value based on EXP_TYPE, which in this case should be EXTENDED. Although I'm not sure if the src_type step has any hooks in it for exposures with EXP_TYPE='NRS_LAMP' (as opposed to NRS_IFU). If it doesn't, then it won't do any good to turn on the src_type step for lamp exposures, unless we make a small upgrade to the src_type step to handle them.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558907#comment-558907):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I don't see SRCTYPE in either rate file header?  Or did you mean it must have been added by one of the calspec2 steps that are being run?

**Comment by jemorrison** [comment]
If you open the files using datamodels and print input_model.meta.target.source_type you will see the set values. 
I think something left over from how the file was created and got stuck in the asdf extension is causing this problem. I just opened the file using datamodels, set meta.target.source_type to UNKNOWN and saved it. I am testing this file.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558913#comment-558913):_

Ah, I see. There must be a default somewhere in our scripts used to convert raw ground data files to pipeline format that puts that in. I would expect data taken on orbit should not have that; I can check some Normal Ops data to be sure.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558917#comment-558917):_

I confirm meta.target.source_type is set to None for autocal rate files generated from a normal ops test run.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558919#comment-558919):_

I just put in a PR to fix this JP ticket (6460). Tyler had a good question in the review of that PR do all NRS_LAMP exposures produce an IFUModel, or can NRS_LAMP be assigned to data from fixed slits or the MSA?
I was thinking that all NRS_LAMP produce IFUModel data - but I want to confirm with you if this is true

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558948#comment-558948):_

NRS_LAMP can be paired with IFU, FS, or MOS, so the proposed fix here I think needs to combine EXP_TYPE=NRS_LAMP with OPMODE=IFU. EXP_TYPE=NRS_AUTOWAVE should also be included (lamp usage but via the science template).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=561701#comment-561701):_

Fixed by #6460

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557901#comment-557901):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I need to get up to speed with how the pipeline processes NIRSpec Lamp data.  In the directory of the data you only have a rate file not a cal file - so the calspec 2 pipeline is not run on this data ? I am guessing the assign_wcs step is. I first looked at the s3d file to see if cube_build was creating this file correctly. Could you look at it - is that what you expect  ? I am not sure how it should look - is it supposed to have bright spots on the IFU planes ? I don't understand the IFU planes

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557908#comment-557908):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I was running the full spec2 pipeline - no cal file was generated because of the crash (it is output only at the very end). I did look at the cube, and at least qualitatively speaking, it seemed ok.

I also had to use a custom pipeline parameter file in order to turn off some steps, since we haven't yet updated CRDS for these lamp cases. I just copied that file to the central store directory in case you need to take a look.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557918#comment-557918):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) A few more questions to fill in some of my lack of knowledge of NIRSpec LAMP data. I have a picture of the rate image and an arbitrary wavelength plane of the s3d file (516 wavelength plane). Are the bright rectangles on the IFU plane image open msg shutters ? If that the streaks in the rate image ?   !image-2021-11-09-15-39-10-805.png|width=493,height=254!

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=557973#comment-557973):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) yes, those bright spaxels are from the traces of the failed open MSA shutters.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558353#comment-558353):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I think I am running the spec2 pipeline wrong for this data. I get a different error than you but I think I must be doin g something wrong. . I got the jwst_nirspec_extract1d_new_ifulamp.asdf reference file. I ran spec2 like this:

strun jwst_nirspec_pars-spec2pipeline_linelamp_ifu_new.asdf jwdata0010010_11010_0001_NRS1_lamp_rate.fits --steps.extract_1d.override_apcorr='jwst_nirspec_extract1d_new_ifulampsdf'

 

I get this error - 

raise RuntimeError("extract1d reference file must be JSON or a FITS image.")

RuntimeError: extract1d reference file must be JSON or a FITS image.

 

How did you file spec2 pipeline on this data.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558357#comment-558357):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) both the apcorr and extract_1d reference files need to be specified - the pipeline crashes because it can't find a valid match for either (even though an apcorr file isn't actually needed). We're in the process of modifying the CRDS selection rules to fix this, but that won't take effect until after the software freeze. I forgot to put the apcorr file on central store; it's there now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558429#comment-558429):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly)  [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham)  [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) 
A fix for this is to add 'NRS_LAMP' as one of the exptypes in extract.py (line 138).
I did this and it works. Bit I wonder if there is something smarter we could do. Like first check the file of reference we have (asdf, json or fits).

 I have cut and pasted the code that is reading in the extract1d reference file to show what is going on. Without NRS_LAMP as an option it goes through the options and opens the reference file as a fd = datamodels.MultiExtract1dImageModel(refname). No error is give here. Should it ? The multiextract1d.schema.yaml file is expecting an input fits file. 



if refname == "N/A":
    ref_dict = None
 elif exptype in ['MIR_MRS', 'NRS_IFU', 'NRS_LAMP']:             <--------- Adding this fixes the problem
 # read in asdf file
    extract_model = datamodels.Extract1dIFUModel(refname)
    ref_dict = {}
    ref_dict['ref_file_type'] = FILE_TYPE_ASDF
    ref_dict['ref_model'] = extract_model

else:
 # Try reading the file as JSON.
    fd = open(refname)
    try:
        ref_dict = json.load(fd)
        ref_dict['ref_file_type'] = FILE_TYPE_JSON
        fd.close()
    except (UnicodeDecodeError, JSONDecodeError):
        fd.close()
        # Try opening the file as a reference image.
       try:
           fd = datamodels.MultiExtract1dImageModel(refname).           <------------------ Code gets here (WITHOUT ABOVE FIX)
          ref_dict = \{'ref_file_type': FILE_TYPE_IMAGE, 'ref_model': fd}
       except OSError:                                                                                 <------------------- OSError does not occur (should it?) 
          log.info("The extract1d reference file should be JSON or FITS.")
          log.error(f"Don't know how to read \{refname}.")
          raise

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558611#comment-558611):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)   There is a line of code in extract.py (module do_extract1d) that sets the types of data to turn on use_source_posn

Clipped code: 

# Turn use_source_posn on for types that should use it by default
 if use_source_posn is None:
    if exp_type in ['MIR_LRS-FIXEDSLIT', 'MIR_MRS', 'NRS_FIXEDSLIT', 'NRS_IFU', 'NRS_MSASPEC']:
    use_source_posn = True
    log.info(f"Turning on source position correction for exp_type = \{exp_type}")

 

Should I add NRS_LAMP to this set to run on use_source_posn ?
For lamp data I am not sure you even have an concept of use_source_posn

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558650#comment-558650):_

I'm pretty sure that the `use_source_posn` operation uses the RA/Dec of the target to estimate the location of the source in image/detector space and center the extraction at that location. I doubt that target RA/Dec would have any useful or real meaning for lamp exposures and hence could lead to very wacky results.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558732#comment-558732):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) for the special spec2 parameter file you had where the data is located the apply_apcorr is set to false. But there is a special apcorr reference file in the directory. Do you intend to ever apply and apcorr ref file to NRS_LAMP - or will it always be turned off ? 

If you want to have to option to apply it - I have to add a hook in extract.py for this.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558849#comment-558849):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) use_source_posn should not be used with NRS_LAMP because all apertures are uniformly illuminated. (This should probably be the case for any source that does not have srctype "POINT".)

For the same reason, apcorr should never be applied to any NRS_LAMP exposure. The reference file is there because currently the pipeline will crash if it is not overridden, even if apply_apcorr is set to false - that should be fixed once we update the CRDS rmap.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558856#comment-558856):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I can get the NRS1 data to process through the spec2 pipeline, but the NRS2 is failing.

I have saved the ifu cube. I am pretty sure the problem is because for NRS1 the input_model.meta.target.source_type is undefined

so it defaults to 'EXTENDED', but the NRS2 source type is POINT.

I am assuming that is wrong.  I will investigate why it gets set to POINT.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558870#comment-558870):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)

For this data there are 2 files, one for NRS1 and one for NRS2. The special parameter file to process this data - skips the srctype step.

But somehow after cube_build the s3d file (input to extract_1d) has SOURCE_TYPE = POINT for the NRS2 data and it is undefined for the NRS1 data (so it defaults to EXTENDED). Both have SCRTYAPT = UNKNOWN.
Any idea where SOURCE_TYPE could be getting set to POINT.  I will save all the results from the STEPS and see where it get sets to POINT.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558891#comment-558891):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) note that there is no way to specify the source type in APT for any lamp exposure (NRS_LAMP or autocals), so SRCTYAPT will always be UNKNOWN in these cases. The pipeline should just automatically default to EXTENDED. However, if srctype needs to be run in order to avoid any ambiguity, we can always add that to the parameter file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558899#comment-558899):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I just think something is wrong with the NRS2 file.
I opened the rate file and printed out  source_type and it was POINT. That does not make sense to me.  Since no other steps touch this value, it is getting passed onto s3d file and then extract_1d thinks it is POINT and goes down a line code that results in an error. 

m2 = datamodels.open('jwdata0010010_11010_0001_NRS2_lamp_rate.fits')

In [**14**]: m2.meta.target.source_type

Out[**14**]: 'POINT'

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558903#comment-558903):_

Because the src_type step isn't run until calwebb_spec2 (after the rate product is created) the SRCTYPE keyword should not be set at all in the rate file. At most it could have SRCTYAPT='UNKNOWN', indicating that the source type was not designated in the APT. Given that condition, the src_type step would then use the appropriate default value based on EXP_TYPE, which in this case should be EXTENDED. Although I'm not sure if the src_type step has any hooks in it for exposures with EXP_TYPE='NRS_LAMP' (as opposed to NRS_IFU). If it doesn't, then it won't do any good to turn on the src_type step for lamp exposures, unless we make a small upgrade to the src_type step to handle them.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558907#comment-558907):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I don't see SRCTYPE in either rate file header?  Or did you mean it must have been added by one of the calspec2 steps that are being run?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558913#comment-558913):_

Ah, I see. There must be a default somewhere in our scripts used to convert raw ground data files to pipeline format that puts that in. I would expect data taken on orbit should not have that; I can check some Normal Ops data to be sure.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558917#comment-558917):_

I confirm meta.target.source_type is set to None for autocal rate files generated from a normal ops test run.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558919#comment-558919):_

I just put in a PR to fix this JP ticket (6460). Tyler had a good question in the review of that PR do all NRS_LAMP exposures produce an IFUModel, or can NRS_LAMP be assigned to data from fixed slits or the MSA?
I was thinking that all NRS_LAMP produce IFUModel data - but I want to confirm with you if this is true

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=558948#comment-558948):_

NRS_LAMP can be paired with IFU, FS, or MOS, so the proposed fix here I think needs to combine EXP_TYPE=NRS_LAMP with OPMODE=IFU. EXP_TYPE=NRS_AUTOWAVE should also be included (lamp usage but via the science template).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2322?focusedCommentId=561701#comment-561701):_

Fixed by #6460
