### ISSUE TITLE
Linearity Reference file for FGS needs to be updated to include NO_LIN_CORR flags

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6481]
_Issue [JP-2341](https://jira.stsci.edu/browse/JP-2341) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

In JP-2311 a fix was made in the linearity step in stcal that sets the DQ flag for the linearity model to NO_LIN_CORR when all the linearity coefficients =0. Applying a linearity correction with all the coefficients =0  when the corresponding linearity DQ flag is 0 results in a corrected linearity value of 0, which then results in a rate of 0.  The step now sets the linearity ref model  DQ value to NO_LIN_CORR and sets the coefficients to values that will make no change to the input data for cases where the coefficients all =0. 

The linearity step only uses the linearity reference model to determine if the coefficients of the linear correction are valid. There is a disconnect in the FGS reference files. For pixels with all zeros for the linearity coefficients the MASK reference files has NO_LIN_CORR set for the pixel instead of the DQ plane of the linearity reference file. This should be fixed in the FGS reference linearity reference files. I was using jwst_fgs_linearity_0014.fits.  The JWST pipeline in general does not set the DO_NOT_USE flag - it instead - propagates these values from the reference files to the output pixel DQ.  It may lead to confusion in the final rate values for pixel with NO_LIN_CORR set but DO_NOT_USE not set. These pixel will not have linearity correction applied. The DO_NOT_USE flags will not be set if it is not set in the linearity reference file. It might be a better idea to also set the DO_NOT_USE flags in the linearity reference file for all pixels flags with NO_LIN_CORR.

**Comment by hbushouse** [comment]
This is an INS task that has no connection to code work in the github repo. Closing.
