### ISSUE TITLE
NIRCam Coron3 resample not co-adding properly for LWB and SWB masks

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6484]
_Issue [JP-2342](https://jira.stsci.edu/browse/JP-2342) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

NIRCam Coronagraphy Team members noticed issues in resample output during Stage 3 processing of NIRCam coronagraphic data using the LWB and SWB masks, but not for the round masks. From [Jens Kammerer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jkammerer):

"In our NIRCam Coronagraphy Meeting today, we noticed that it seems like the bar mask data was rotated around the reference pixel of the NRCA5_MASKLWB subarray which is close to the center of the image (see left panel of the attached screenshot), although the APERNAME in the fits file header is NRCA5_MASKLWB_NARROW which has the reference pixel at the edge of the image (where the PSF in the simulation is located)."

First check is to examine the SIAF aperture provided for the different masks.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=562722#comment-562722):_

I can't find an entry for aperture NRCA5_MASKLWB_NARROW in the version of the NIRCam SIAF table that I happen to have lying around, although it's several years old. Does anyone have the latest SIAF table for NIRCam?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=562727#comment-562727):_

Ah, never mind. Found a very recent NIRCam SIAF table, which gives:

NRCA5_MASKLWB  XSciSize=320 YSciSize=320 XSciRef=160.0 YSciRef=175.5 (so ref point very near the image center)
NRCA5_MASKLWB_NARROW  XSciSize=320 YSciSize=320 XSciRef=293.0 YSciRef=175.5  (so ref point close to right edge of image)

Will need to check the data files to see what info they have in the relevant WCS-related keywords.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=563198#comment-563198):_

[Julien Girard](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jgirard) [Ben Sunnquist](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bsunnquist) 

When you have a chance, would you mind adding a priority level for this, e.g., nrc_high, nrc_med? Note that if "critical" is the priority level, it needs to be justified in the comments here.

**Comment by hbushouse** [comment]
Also see [JP-2335](https://jira.stsci.edu/browse/JP-2335)

**Comment by hbushouse** [comment]
Closing as duplicate. See #6471

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=572304#comment-572304):_

Closing, because it duplicates the problem reported in JP-2335.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=562722#comment-562722):_

I can't find an entry for aperture NRCA5_MASKLWB_NARROW in the version of the NIRCam SIAF table that I happen to have lying around, although it's several years old. Does anyone have the latest SIAF table for NIRCam?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=562727#comment-562727):_

Ah, never mind. Found a very recent NIRCam SIAF table, which gives:

NRCA5_MASKLWB  XSciSize=320 YSciSize=320 XSciRef=160.0 YSciRef=175.5 (so ref point very near the image center)
NRCA5_MASKLWB_NARROW  XSciSize=320 YSciSize=320 XSciRef=293.0 YSciRef=175.5  (so ref point close to right edge of image)

Will need to check the data files to see what info they have in the relevant WCS-related keywords.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=563198#comment-563198):_

[Julien Girard](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jgirard) [Ben Sunnquist](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bsunnquist) 

When you have a chance, would you mind adding a priority level for this, e.g., nrc_high, nrc_med? Note that if "critical" is the priority level, it needs to be justified in the comments here.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2342?focusedCommentId=572304#comment-572304):_

Closing, because it duplicates the problem reported in JP-2335.
