### ISSUE TITLE
Investigate and fix issues related to image resampling

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6512]
_Issue [JP-2353](https://jira.stsci.edu/browse/JP-2353) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

INS has a reported a couple of apparent issues with the process of resampling images, which need to be investigated and fixed (if the cal code is determined to be in error).

**Comment by hbushouse** [comment]
No need to track on github, because the corresponding JP ticket is a rollup. Actual code work will be tracked via child tickets/issues. Closing.
