### ISSUE TITLE
Investigate and fix issues related to spectral resampling

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6516]
_Issue [JP-2357](https://jira.stsci.edu/browse/JP-2357) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

INS has a reported a couple of apparent issues with the process of resampling spectral data, which need to be investigated and fixed.

**Comment by hbushouse** [comment]
No need to track on github, because the corresponding JP ticket is a rollup. Actual code work will be tracked via child tickets/issues. Closing.
