### ISSUE TITLE
Add Keywords to MSA_TARG_ACQ Schema

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6535]
_Issue [JP-2369](https://jira.stsci.edu/browse/JP-2369) was created on JIRA by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett):_

Add 6 header keywords specified in JTM JWST-STScI-007719 not included in the current MSA_TARG_ACQ schema:
 * NUMREFST =   number of MSATA reference stars
 * V2HFOFFS =-0.27288  MSA half-facet offset in V2
 * V3HFOFFS = 0.10764  MSA half-facet offset in V3
 * V2MSACTR = 378.771240   center of MSA in V2
 * V3MSACTR =-428.156219   center of MSA in V3
 * OFFSTMAG =   least squares fit offset magnitude (arcsec)

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2369?focusedCommentId=564639#comment-564639):_

I'll add details soon.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2369?focusedCommentId=564669#comment-564669):_

I see there are some that need to be renamed as well.  I'll add them when I have figured out the full set of them.

**Comment by hbushouse** [comment]
Fixed by https://github.com/spacetelescope/jwst/pull/6757

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2369?focusedCommentId=572600#comment-572600):_

I got the JTM document from SOCCER, but there’s a copy of the current latest version (March 2021) attached to JSDP-1751 as 321Z523_01JBCMC840001L5-2.pdf. You can find info about the keyword dictionary at <https://innerspace.stsci.edu/display/jwstdms/JWST+Keyword+Dictionary].>  We actually need a bigger scope than what is described above. I originally wrote this ticket with a plan for piecemeal changes because that makes sense for the SD software work. Since writing the ticket, I’ve come to understand that SCSB prefers a single ticket or as few as possible rather than a bunch of tickets to cover a lot of keywords, and that’s fine because the s/w work is being done on a separate project branch, develop-targ-acq, and won’t affect SDP main work on the develop branch. If you want to break up the work into more than one JP ticket, that’s fine.  Whatever works best for you.

There’s actually order 200 keywords which includes the table definition keywords for 55 columns (TTYPEx, TBCOLx, TFORMx, TUNITx).  All of them are in a single keyword dictionary json file, core.targacq.msa.schema.json. I was thinking that giving you the file before and after I made changes would work to specify the changes needed for the data model schema.  Let me know if that doesn’t work and we can talk about a different way.  I’ve attached the two versions to this ticket: before-core.targacq.msa.schema.json and after-core.targacq.msa.schema.json. They are from the jwstkd project branches develop and develop-targ-acq respectively. I don’t expect much to change now, though, I’m currently working on a change to some default values which I don’t believe affect changes to the data model schema. Please note that there have been changes to some details in the keyword definitions in the JTM document, but the set of keywords should be the same. The json file has the definitive definitions. The jwstkd project is on GitLab at <https://grit.stsci.edu/OED_DSB/jwstkd/-/branches].> There you can see all the json files of the keyword dictionary and grab the latest one anytime for MSA target acquisition from the develop-targ-acq branch.

All the changes need to be delivered to SDP together in a single CAL release and at the same time I merge the SDP develop-targ-acq branch into the develop branch. I had planned on that happening during the 3/14-3/27 sprint. Let me know if you don’t think that’s feasible. We can adjust the schedule.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2369?focusedCommentId=583378#comment-583378):_

Fixed by #6757

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2369?focusedCommentId=564669#comment-564669):_

I see there are some that need to be renamed as well.  I'll add them when I have figured out the full set of them.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2369?focusedCommentId=572600#comment-572600):_

I got the JTM document from SOCCER, but there’s a copy of the current latest version (March 2021) attached to JSDP-1751 as 321Z523_01JBCMC840001L5-2.pdf. You can find info about the keyword dictionary at <https://innerspace.stsci.edu/display/jwstdms/JWST+Keyword+Dictionary].>  We actually need a bigger scope than what is described above. I originally wrote this ticket with a plan for piecemeal changes because that makes sense for the SD software work. Since writing the ticket, I’ve come to understand that SCSB prefers a single ticket or as few as possible rather than a bunch of tickets to cover a lot of keywords, and that’s fine because the s/w work is being done on a separate project branch, develop-targ-acq, and won’t affect SDP main work on the develop branch. If you want to break up the work into more than one JP ticket, that’s fine.  Whatever works best for you.

There’s actually order 200 keywords which includes the table definition keywords for 55 columns (TTYPEx, TBCOLx, TFORMx, TUNITx).  All of them are in a single keyword dictionary json file, core.targacq.msa.schema.json. I was thinking that giving you the file before and after I made changes would work to specify the changes needed for the data model schema.  Let me know if that doesn’t work and we can talk about a different way.  I’ve attached the two versions to this ticket: before-core.targacq.msa.schema.json and after-core.targacq.msa.schema.json. They are from the jwstkd project branches develop and develop-targ-acq respectively. I don’t expect much to change now, though, I’m currently working on a change to some default values which I don’t believe affect changes to the data model schema. Please note that there have been changes to some details in the keyword definitions in the JTM document, but the set of keywords should be the same. The json file has the definitive definitions. The jwstkd project is on GitLab at <https://grit.stsci.edu/OED_DSB/jwstkd/-/branches].> There you can see all the json files of the keyword dictionary and grab the latest one anytime for MSA target acquisition from the develop-targ-acq branch.

All the changes need to be delivered to SDP together in a single CAL release and at the same time I merge the SDP develop-targ-acq branch into the develop branch. I had planned on that happening during the 3/14-3/27 sprint. Let me know if you don’t think that’s feasible. We can adjust the schedule.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2369?focusedCommentId=583378#comment-583378):_

Fixed by #6757
