### ISSUE TITLE
Ramp fitting GLS has bad DQ dimensions for intermediate computation

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6561]
_Issue [JP-2378](https://jira.stsci.edu/browse/JP-2378) was created on JIRA by [Kenneth MacDonald](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmacdonald):_

During test_two_groups_fit when the check for saturated pixels occurs the intermediate DQ array has bad dimensions, resulting in an exception.

**Comment by hbushouse** [comment]
Fixed by https://github.com/spacetelescope/stcal/pull/109

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2378?focusedCommentId=600460#comment-600460):_

Fixed by spacetelescope/stcal#109

Will need stcal release before it's picked up by the jwst repo.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2378?focusedCommentId=600460#comment-600460):_

Fixed by spacetelescope/stcal#109

Will need stcal release before it's picked up by the jwst repo.
