### ISSUE TITLE
Produce B7.9 releases

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6562]
_Issue [JP-2379](https://jira.stsci.edu/browse/JP-2379) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Create needed release candidates and final release for B7.9

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2379?focusedCommentId=565791#comment-565791):_

RC1 produced 20220110

**Comment by nden** [comment]
RC2 released 20220115

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2379?focusedCommentId=565791#comment-565791):_

RC1 produced 20220110

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2379?focusedCommentId=567115#comment-567115):_

RC3 released 20220120

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2379?focusedCommentId=567670#comment-567670):_

RC3, 1.4.2, is the final release.
