### ISSUE TITLE
DMS-461: Create level-3 data products as described in OP-07 Handbook

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#660]
DMS level-4 requirement 461 states: "The Calibration Software shall create Level 3 Science Data Products as specified in the User Handbooks, OP-07."

The OP-07 handbook will be created by MESA, with input/collaboration from SSB, during the B7.1 development cycle. A draft is due in April 2017, with the final being due in August 2017. This requirement will be satisfied by comparing the pipelines and steps described in the handbook against the actual jwst package code base.

**Comment by hbushouse** [comment]
Delivery and verification of DMS-461 has been slipped to B7.2, along with other level-3 processing requirements.

**Comment by stscicrawford** [comment]
Build 7.3 satisfied this requirement with the exception of moving target data that currently does not have any test data
