### ISSUE TITLE
DMS-463: Level-3 data processing rate for WFS&C data

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#661]
DMS level-4 requirement 463 states "For designated WFS&C visits containing up to 10 Gbits of uncompressed level 0 data, calibration shall generate level 3 data products within 60 minutes of receipt of all level 1b data needed to process the visit."

This requirement must be met before B7.1 is delivered to I&T on 11/10/2017, so the tests will be run by some of the DMS testers in their environment using one of our last B7.1 release candidates (September-October 2017 timeframe).

Note, however, that because this requirement applies only to the processing of Wave-Front Sensing and Control (WFSC) visits, for which all of the calibration processing is already available (calwebb_sloper, calwebb_image2, and wfs_combine), such tests could be executed as soon as the necessary info/data is available to construct an ASN file on the fly in the test environment.

**Comment by hbushouse** [comment]
Delivery and verification of DMS-463 has been slipped to B7.2, along with other level-3 processing requirements.

**Comment by stscicrawford** [comment]
Leaving open as data for confirming this is not yet available

**Comment by hbushouse** [comment]
Closing, because the whole issue of meeting performance requirements is now being handled as an integrated DMS effort.
