### ISSUE TITLE
set_telescope_pointing: Do not import pysiaf if the prd information is available.

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6693]
_Issue [JP-2501](https://jira.stsci.edu/browse/JP-2501) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Often `pysiaf` runs behind the version of the PRD that is installed in operations. As a result, on import, it produces warnings.  This is extra, unnecessary noise in operation because all information comes from the operations PRD anyways.

Explore whether it is possible to make the `pysiaf` package import dependent on whether the PRD is used or not. Logically this should be possible but need to ensure no helper functions from `pysiaf` are used.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=568148#comment-568148):_

Is this because not all the PRD changes are SIAF changes and hence pysiaf does not require an update?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=568232#comment-568232):_

Not sure of details, though that is definitely one aspect.

The other mechanical detail is, even if the `pysiaf` package is kept in lock-step with PRD updates, PRD updates can become operational anytime, including between builds. `pysiaf` can only be updated at builds/exceptions. As soon as such an update occurs, `pysiaf` in operations becomes out-of-date.

Note: set_telescope_pointing, and any other SDP-based code that relies on SIAF information, takes its information from the PRD, not `pysiaf`. There is no reason for `pysiaf` to be continually updated in operations.

`pysiaf` is only used when the PRD information is not available; i.e. outside of operations. And, in that case, users can update their version of `pysiaf` when needed. Hence, the modification suggested in this ticket is feasible. The fact the `pysiaf` is imported in operations is unnecessary.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=568313#comment-568313):_

Saw this ticket go by and thought I should jump in quickly.  Generally speaking the SIAF update procedure is to deliver updated information to the PRD **via** pysiaf; pysiaf is how we check that all of the changes are ok before the PRD delivery.  PRD updates can happen that don't include SIAF of course, but SIAF information in the PRD should never be more recent than in pysiaf.

Functionally this distinction doesn't matter though, as it should still be the case that the SDP code pulls from the PRD first and pysiaf only if that isn't possible.

**Comment by hbushouse** [comment]
Fixed by #6735

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=572002#comment-572002):_

Resolved by [PR#&#x2060;6735](https://github.com/spacetelescope/jwst/pull/6735)

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=568148#comment-568148):_

Is this because not all the PRD changes are SIAF changes and hence pysiaf does not require an update?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=568232#comment-568232):_

Not sure of details, though that is definitely one aspect.

The other mechanical detail is, even if the `pysiaf` package is kept in lock-step with PRD updates, PRD updates can become operational anytime, including between builds. `pysiaf` can only be updated at builds/exceptions. As soon as such an update occurs, `pysiaf` in operations becomes out-of-date.

Note: set_telescope_pointing, and any other SDP-based code that relies on SIAF information, takes its information from the PRD, not `pysiaf`. There is no reason for `pysiaf` to be continually updated in operations.

`pysiaf` is only used when the PRD information is not available; i.e. outside of operations. And, in that case, users can update their version of `pysiaf` when needed. Hence, the modification suggested in this ticket is feasible. The fact the `pysiaf` is imported in operations is unnecessary.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=568313#comment-568313):_

Saw this ticket go by and thought I should jump in quickly.  Generally speaking the SIAF update procedure is to deliver updated information to the PRD **via** pysiaf; pysiaf is how we check that all of the changes are ok before the PRD delivery.  PRD updates can happen that don't include SIAF of course, but SIAF information in the PRD should never be more recent than in pysiaf.

Functionally this distinction doesn't matter though, as it should still be the case that the SDP code pulls from the PRD first and pysiaf only if that isn't possible.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2501?focusedCommentId=572002#comment-572002):_

Resolved by [PR#&#x2060;6735](https://github.com/spacetelescope/jwst/pull/6735)
