### ISSUE TITLE
set_telescope_pointing: Log argv settings

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6701]
_Issue [JP-2505](https://jira.stsci.edu/browse/JP-2505) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

With respect to `set_telescope_pointing` command line utility: Log to `logging.INFO` the values specified on the command line. I.e. the `argv` settings.

**Comment by hbushouse** [comment]
Fixed by #6735

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2505?focusedCommentId=572004#comment-572004):_

Resolved by [PR#&#x2060;6735](https://github.com/spacetelescope/jwst/pull/6735)

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2505?focusedCommentId=572004#comment-572004):_

Resolved by [PR#&#x2060;6735](https://github.com/spacetelescope/jwst/pull/6735)
