### ISSUE TITLE
Update level2b ASN rules for NRC grism Module B subarray exposures

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6705]
_Issue [JP-2508](https://jira.stsci.edu/browse/JP-2508) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

As described in JSOCINT-576 and JWSTDMS-632, some NIRCam exposures during commissioning will be using Module B subarrays that are normally dedicated to the NRC_TSGRISM observing mode. Currently, Module B is not supported for science observations with the NRC_TSGRISM mode and hence when such exposures reach the assign_wcs step in the calwebb_spec2 pipeline, the pipeline aborts with an error message indicating that they're not supported.

Fortunately the use of these exposures during commissioning only requires level-1b and level-2a products. So we need to update the level-2b ASN rules to exclude construction of any ASN's for these kinds of exposures, which will effectively end processing at level-2a.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2508?focusedCommentId=569456#comment-569456):_

I've moved the initial batch of asns made and the asn batch produced after the change into the ticket's data directory, under init_asn/ and change_asns/. Note that I misspoke during the meeting - there are tsimage asns for both Stage 2 and 3 processing. The new rule excludes tsgrism exptypes with detector set to nrcblong, but allows all other asns from this pool.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2508?focusedCommentId=570420#comment-570420):_

Fixed by #6709

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2508?focusedCommentId=569052#comment-569052):_

The assign_wcs step is currently using EXP_TYPE='NRC_TSGRISM' & MODULE != 'A' to identify exposures that are not supported, so those 2 pieces of meta data could presumably also be used to form an appropriate ASN rule.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2508?focusedCommentId=569456#comment-569456):_

I've moved the initial batch of asns made and the asn batch produced after the change into the ticket's data directory, under init_asn/ and change_asns/. Note that I misspoke during the meeting - there are tsimage asns for both Stage 2 and 3 processing. The new rule excludes tsgrism exptypes with detector set to nrcblong, but allows all other asns from this pool.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2508?focusedCommentId=570420#comment-570420):_

Fixed by #6709

**Comment by stscijirahub** [comment]
_This issue is tracked on JIRA as [JP-2508](https://jira.stsci.edu/browse/JP-2508)._
