### ISSUE TITLE
from jwst.pipeline import Detector1Pipeline fails under Python 3.8

### ISSUE THREAD

**Issue by npirzkal** [spacetelescope/jwst#6708]
Trying the simple:
from jwst.pipeline import Detector1Pipeline
results in the following error under Python 3.8:
ImportError                               Traceback (most recent call last)
~/opt/anaconda3/envs/mirage/lib/python3.8/site-packages/astropy/units/_typing.py in <module>
      8 try:  # py 3.9+
----> 9     from typing import Annotated
     10 except (ImportError, ModuleNotFoundError):  # optional dependency

ImportError: cannot import name 'Annotated' from 'typing' (/Users/npirzkal/opt/anaconda3/envs/mirage/lib/python3.8/typing.py)

**Comment by tapastro** [comment]
Hi Nor,

I just made a new conda environment with python=3.8, then ran `pip install jwst`. I can import Detector1Pipeline without error, so it might be an astropy version issue. What do you see when running `pip list` in your environment? Mine shows:
`asdf                     2.8.3
asdf-astropy             0.1.2
asdf-coordinates-schemas 0.1.0
asdf-transform-schemas   0.2.0
asdf-wcs-schemas         0.1.1
astropy                  5.0.1
attrs                    21.4.0
BayesicFitting           2.8.1
certifi                  2021.10.8
charset-normalizer       2.0.11
crds                     11.6.0
cycler                   0.11.0
drizzle                  1.13.4
filelock                 3.4.2
fonttools                4.29.1
future                   0.18.2
gwcs                     0.18.0
idna                     3.3
importlib-resources      5.4.0
jmespath                 0.10.0
jsonschema               3.2.0
jwst                     1.4.2
kiwisolver               1.3.2
lxml                     4.7.1
matplotlib               3.5.1
numpy                    1.22.1
packaging                21.3
Parsley                  1.3
photutils                1.3.0
Pillow                   9.0.0
pip                      21.2.4
poppy                    1.0.2
psutil                   5.9.0
pyerfa                   2.0.0.1
pyparsing                3.0.7
pyrsistent               0.18.1
python-dateutil          2.8.2
PyYAML                   6.0
requests                 2.27.1
scipy                    1.7.3
semantic-version         2.8.5
setuptools               58.0.4
six                      1.16.0
spherical-geometry       1.2.22
stcal                    0.6.0
stdatamodels             0.4.0
stpipe                   0.3.1
stsci.image              2.3.5
stsci.imagestats         1.6.3
stsci.stimage            0.2.5
tweakwcs                 0.7.3
urllib3                  1.26.8
wheel                    0.37.1
zipp                     3.7.0
`

**Comment by nden** [comment]
The error is coming from astropy. Astropy keeps most of its dependencies optional. Is this the full traceback you are showing?

**Comment by npirzkal** [comment]
Yes, it is astropy 5.0.1, as I just figured out. Maybe we should no longer be using astropy...

**Comment by npirzkal** [comment]
Hi Nadia

Indeed it is astropy. It seems to always be astropy,,,,

N

**Comment by nden** [comment]
We can't stop using it but we may look into the best way to install it with all optional dependencies by default.
Can we close this?

**Comment by npirzkal** [comment]
yep, we can close this. Thanks for the prompt answers! :-)
