### ISSUE TITLE
Modify the calwebb_spec2, calwebb_tso3, and calwebb_spec3 flow for NIRISS SOSS flux cal

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6711]
_Issue [JP-2512](https://jira.stsci.edu/browse/JP-2512) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The new NIRISS SOSS 1D spectral algorithm provided by the IDT is designed to work with input data that is **not** flux calibrated. So the step flows of the `calwebb_spec2`, `calwebb_tso3`, and `calwebb_spec3` pipelines need to be modified, in order to execute the `photom` step **after** `extract_1d` has been performed. 

For the `calwebb_spec2` pipeline this amounts to a simple reordering of the existing steps. For `calwebb_tso3` and `calwebb_spec3`, however, which don't currently apply the `photom` step at all, it means adding that step to each pipeline, immediately following the `extract_1d` in each. Note that `calwebb_spec3` is included in this work, because it is possible for SOSS observations to be obtained in a non-TSO mode, in which case the data are processed using the regular `calwebb_spec3` pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2512?focusedCommentId=569245#comment-569245):_

See the Cal WG meeting minutes and presentation at <https://outerspace.stsci.edu/display/JWSTCC/2022-02-01+Meeting+Notes> for more information.

**Comment by hbushouse** [comment]
https://github.com/spacetelescope/jwst/pull/6734

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2512?focusedCommentId=582096#comment-582096):_

Fixed by #6734

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2512?focusedCommentId=569245#comment-569245):_

See the Cal WG meeting minutes and presentation at <https://outerspace.stsci.edu/display/JWSTCC/2022-02-01+Meeting+Notes> for more information.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2512?focusedCommentId=582096#comment-582096):_

Fixed by #6734
