### ISSUE TITLE
Excessive error logging for MRS 1d spectral extraction

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6731]
_Issue [JP-2516](https://jira.stsci.edu/browse/JP-2516) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

Something has changed in the pipeline error logging such that the MRS pipeline now reports hundreds to thousands of pages of errors when running the Extract1D step:

> `2022-02-11 12:43:15,972 - stpipe.Spec2Pipeline.extract_1d - WARNING - /Users/dlaw/opt/anaconda3/envs/jwst/lib/python3.10/site-packages/astropy/stats/sigma_clipping.py:957: RuntimeWarning: Mean of empty slice`
> ` mean = np.nanmean(data_clipped, axis=axis)``2022-02-11 12:43:15,972 - stpipe.Spec2Pipeline.extract_1d - WARNING - /Users/dlaw/opt/anaconda3/envs/jwst/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1216: RuntimeWarning: Mean of empty slice`
> ` return np.nanmean(a, axis, out=out, keepdims=keepdims)``2022-02-11 12:43:15,972 - stpipe.Spec2Pipeline.extract_1d - WARNING - /Users/dlaw/opt/anaconda3/envs/jwst/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.`
> ` var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,`

I've narrowed this down to line 634 of extract_1d.ifu where the sigma_clipped_stats routine is run in a loop over wavelength space for an EXTENDED source type object.  When run in calspec2 however, there is a huge empty region in the middle-wavelength range of the cube where there is no good data (since MRS Lvl2 data consists of data from two different spectral channels).  sigma_clipped stats is thus being passed an empty array for thousands of wavelengths, and throwing lengthy errors for each.

Fixing this may be as easy as adding a check for non-zero array size.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2516?focusedCommentId=570757#comment-570757):_

Potential fix: #6728

**Comment by hbushouse** [comment]
Fixed by #6728

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2516?focusedCommentId=571129#comment-571129):_

Fixed by #6728

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2516?focusedCommentId=570757#comment-570757):_

Potential fix: #6728

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2516?focusedCommentId=571129#comment-571129):_

Fixed by #6728
