### ISSUE TITLE
error running Image2Pipeline

### ISSUE THREAD

**Issue by x12red** [spacetelescope/jwst#6742]
Hi all, 

I've just installed the new version of MIRAGE (2.2.2.dev10+g8616f6a) + the JWST pipeline (1.4.3).
After I create my own simulations with mirage, I use the pipeline with the so-called standard configuration.
Step 1 works well. However, when I try to use Image2Piepline, it returns me the following error message:

----------------------------------------------------------------------
ERROR RUNNING STEP 'Image2Pipeline':
    'properties'

del schema['properties']
KeyError: 'properties'
----------------------------------------------------------------------

What does it mean?

**Comment by WilliamJamieson** [comment]
Looks like this is caused by asdf-format/asdf-transform-schemas#31.

**Comment by WilliamJamieson** [comment]
@x12red the best fix is to downgrade asdf-transform-schemas to version 0.2.0. Everything should function without issue using that version.

**Comment by WilliamJamieson** [comment]
Note that `asdf-transform-schemas` 0.2.1 has been yanked on pypi. Thus installing jwst in a fresh environment should result in obtaining `asdf-transform-schemas` 0.2.0 (or the latest version of `asdf-transform-schemas` which is not 0.2.1).
