### ISSUE TITLE
WARNING when I run the JWST pipeline

### ISSUE THREAD

**Issue by x12red** [spacetelescope/jwst#6748]
Hi All, 

I noticed the following warning when I run the pipeline. I do not have any problem in the end, but I would like to know what it means. Here is the warning:
**WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-039 DOESN'T MATCH THE CURRENT ONLINE VERSION PRDOPSSOC-044

What am I supposed to do?

**Comment by stscieisenhamer** [comment]
Greetings,

What command or API call were you doing that generated this message?

**Comment by x12red** [comment]
I've just noticed that it happens when my script calls MIRAGE to simulate data. So, it is not related to the pipeline directly.
You can close this issue!
