### ISSUE TITLE
How to use a specific function in the pipeline?

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#6753]
Hi, 

I'm working on simulated MIRI IFU data. I ran through stage 1 and got the _rate.fits file. 
Now, I'd like to study the details of assign_wcs in stage 2. In particular, I want to know how to transform from detector coordinates to alpha-beta-lambda coordinates. 

I see there's a function "detector_to_abl" in the file jwst/assign_wcs/miri.py
Is there a way I can use that function independently? 

Thanks,
Guang

**Comment by nden** [comment]
Yes, this function will return the transform from `detector` to `alpha-beta-lambda`.
Assuming you have an `input_model` which in this case should be a `IFUImageModel` you can get the reference files from CRDS using something like this:

```
from jwst.assign_wcs.assign_wcs_step import AssignWcsStep
from jwst.assign_wcs import miri

refs = {}

for reftype in step.reference_file_types:
    refs[reftype] = step.get_reference_file(input_model, reftype)

det_to_abl = miri.detector_to_abl(input_model, refs)
```

If necessary you can work around not having an `input_model`.

**Comment by Guang91** [comment]
Thanks for the instructions.

**Comment by nden** [comment]
@Guang91 Sorry for the delay, I missed your reply. I updated the example above with answers. Let me know if anything else is needed.
