### ISSUE TITLE
How to cite the jwst pipeline?

### ISSUE THREAD

**Issue by taylorbell57** [spacetelescope/jwst#6859]
I am in the process of writing a paper that will make use of the jwst pipeline, and I would like to know how I should cite your pipeline. Relatedly, I would recommend adding a "How To Cite" section or something like that to the README.md file on GitHub and/or Introduction page on the readthedocs page to make sure people know how best to give credit to your work.

**Comment by shuwn** [comment]
Hi, @taylorbell57 
I'm also study how to use JWST Pipeline. 
You can refer to the following linked documents and videos.
[JWebbinars](https://www.youtube.com/watch?v=EaGNxQsoAZ8&list=PLTOSd8OgUP5p4pRLTiVFY0kIRSw04xDP6)
[JWebbinar material](https://github.com/spacetelescope/jwebbinar_prep)

**Comment by taylorbell57** [comment]
Hi @shuwn, my difficulty is not in using the JWST pipeline, I am just asking how I should cite the pipeline in a paper which uses the pipeline

**Comment by ivastar** [comment]
Bumping this issue, it would be great to at least have a CFF file that gives credit to all the authors and better yet a Zenodo DOI. Users are coming up with many different ways of citing the code that are inconsistent and impossible to keep track of.

**Comment by nden** [comment]
Just a quick note that this is being discussed and a solution is coming soon.

**Comment by nden** [comment]
We've added a citation and a Zenodo badge to the DOI. 
We'll add a reference to a paper in the near future as well.

**Comment by taylorbell57** [comment]
Thanks so much for addressing this!
