### ISSUE TITLE
Pipeline stage 1 reset error on LRS data (pipeline version 1.6.1)

### ISSUE THREAD

**Issue by Achrene** [spacetelescope/jwst#6932]
Hi, 

I noticed  the reset anomaly correction step is automatically disabled in the 1.6.0 and 1.6.1 one versions of this stage 1. I tried to activate it but an error pops out. The crds I am using is the last updated one: jwst_miri_reset_0073.fits. I am wondering whether I am doing something wrong or if this error is something you already know about. 

Here is the error: something about floats and ints. I noticed the reset crds file is coded on 8 bits (only integers) and the previous one (jwst_miri_reset_0043.fits) is coded on 16 bits.

<img width="1092" alt="Screenshot 2022-07-14 at 16 40 56" src="https://user-images.githubusercontent.com/79970560/179995925-61f6067c-5c21-4d9d-960c-1bfe428c6c33.png">

Thank you very much for your help, 

Achrène

**Comment by hbushouse** [comment]
Is this LRS slitless or fixed-slit data?

**Comment by Achrene** [comment]
Hi, it is the slitless data.

**Comment by jemorrison** [comment]
I created this file. I will look into this problem and get back to you

**Comment by hbushouse** [comment]
Is this still an issue? We have a nightly regression test that runs fine using jwst_miri_reset_0073.fits on LRS slitless data and have heard of no other problems within operations using this new reference file.

**Comment by nden** [comment]
This will be closed in a week for lack of activity. Let us know if it's still an issue.
