### ISSUE TITLE
No wavelength solution for MIRI/LRS in _calints files after Spec2Pipeline

### ISSUE THREAD

**Issue by taylorbell57** [spacetelescope/jwst#6963]
As of right now, the WAVELENGTH extension of all my MIRI slitless LRS _calints files (point source, TSO) is completely filled with zeros. I believe this should be fairly easy to populate (and the extract1d step does calculate the wavelength solution for the _x1dints files) and don't see why it couldn't be computed given that the extension is populated for other instruments. I have skipped the photom step and can't say for sure yet that the wavelength solution is still missing if the photom step is run, but running the photom step should not be required to get a wavelength solution. I believe it should be happening in the assign_wcs step.

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by hbushouse** [comment]
@stscijgbot
