### ISSUE TITLE
TweakReg: More catalog parameters should be exposed

### ISSUE THREAD

**Issue by thomaswilliamsastro** [spacetelescope/jwst#6995]
The make_tweakreg_catalog part in TweakReg has parameters that currently aren't exposed (e.g. roundness limits, background median box size). I've noticed for some cases that having the background box size too large in images full of extended emission will end up with a very low number detected sources, so it would be useful to have these exposed to the user

**Comment by hbushouse** [comment]
Yes, work to implement this is already underway via #6987

**Comment by thomaswilliamsastro** [comment]
@hbushouse it seems that this PR is more for aligning to the Gaia catalogues, would this also be building in the make_tweakreg_catalog parameters?

**Comment by nden** [comment]
@stscijgbot-jp
