### ISSUE TITLE
NIRCam mosaics relative and absolute astrometry misaligned

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7074]
_Issue [JP-2628](https://jira.stsci.edu/browse/JP-2628) was created on JIRA by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe):_

The relative and absolute astrometry for all NIRCam exposures and mosaics (level 2 and level 3 products) are currently still misaligned by several pixels (~0.1-0.2") because updated SIAF information has not yet been delivered from commissioning data from program NRC-21, but pre-flight values are instead still being used.

Specifically, the 8 short-wavelength SCAs, and the 2 long-wavelength SCAs, are misaligned relative to each other, and in an absolute sense, as a result of residual shifts and rotations in their locations, that can be measured in-flight more accurately than the values that were available from the pre-flight data.

To correct for this in the pipeline, the updated SIAF values for these shifts and rotations need to be delivered by the NIRCam team, along with the non-linear polynomial distortion coefficients, which are being measured from NIRCam Commissioning program NRC-21.

This issue is significantly impacting the quality of the resulting images and other pipeline products (although it is not a software issue per se), and is critical to address (1) before DMS reprocessing of the NIRCam commissioning data can begin in June, and (2) before science observations start, especially since accurate NIRCam astrometry is fundamental to other science modes including NIRSpec spectroscopy.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2628?focusedCommentId=590935#comment-590935):_

Point of information: If `pysiaf` has been updated with the necessary SIAF updates, or the XML files with the updates are available, the JWST task `set_telescope_pointing` can be run on any already-existing data to get the updates in.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2628?focusedCommentId=590938#comment-590938):_

Thanks [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) , and yes. it's the "if" part that's needed here - ie, the necessary SIAF updates (for offsets/ rotations of the SCAs) are what need to be delivered from NIRCam / NRC-21 (in addition to the non-linear polynomial distortion coefficient files to CRDS), to update the older, less accurate values currently still in use by SIAF/pysiaf.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2628?focusedCommentId=692192#comment-692192):_

[Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) I assume that this is no longer relevant given updates over the last few years?

**Comment by bhilbert4** [comment]
The relative positions of the detectors were improved in the latest SIAF update, from late February. So the alignment should in general be much better now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2628?focusedCommentId=692203#comment-692203):_

thanks [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) for confirming that these latest SIAF updates (Feb 2024) should resolve this issue.
