### ISSUE TITLE
1.5.3 ami_average

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7094]
_Issue [JP-2732](https://jira.stsci.edu/browse/JP-2732) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## ami\_average
  * Updated the step to handle inputs with different sizes for ??fit\_image?? and ??resid\_image??. Larger inputs are trimmed to match the size of the smallest input. [#&#x2060;6870]

**Comment by nden** [comment]
ins test ticket
