### ISSUE TITLE
1.5.3 straylight

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7102]
_Issue [JP-2746](https://jira.stsci.edu/browse/JP-2746) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## straylight
  * Add a check that input data is IFUImageModel [#&#x2060;6861]
 * Update straylight algorithm to use cross-artifact model [#&#x2060;6873]

**Comment by nden** [comment]
ins test ticket
