### ISSUE TITLE
1.5.0 reset

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7119]
_Issue [JP-2784](https://jira.stsci.edu/browse/JP-2784) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

##### 1.5.0
 * Fix bug in how segemented data is corrected [#&#x2060;6784]

##### 1.4.5
 * Read NINTS and NGROUPS from model.meta for reset reference file and data instead of using the shape of the data to define these values [#&#x2060;6749]

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2784?focusedCommentId=600617#comment-600617):_

The MIRI reset notebook shows no errors, but has no test for segmented data. <https://jwst-validation-notebooks.stsci.edu/jwst_validation_notebooks/reset/jwst_reset_miri_test/jwst_reset_miri_testing.html>

**Comment by nden** [comment]
ins test issue
