### ISSUE TITLE
Add links to stcal modules

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7129]
_Issue [JP-2619](https://jira.stsci.edu/browse/JP-2619) was created on JIRA by [Jo Taylor](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jotaylor):_

It would be helpful to include hyperlinks for modules that have been moved from jwst to stcal. For example, in the saturation step:

<https://jwst-pipeline.readthedocs.io/en/latest/jwst/saturation/description.html>

perhaps the word "stcal" could link to the documentation/source code for the stcal.saturation step.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2619?focusedCommentId=684622#comment-684622):_

I believe this ticket was effectively duplicated/worked by JP-3525 - can this be closed?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2619?focusedCommentId=684640#comment-684640):_

The only 2 steps that have documentation in the stcal RTD are jump and ramp fitting. Saturation, linearity, and dark_current don't have any docs in stcal. So [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) is correct that this has been fixed by JP-3525.

**Comment by hbushouse** [comment]
jump and ramp fitting docs updated to contain links to stcal in #8253
