### ISSUE TITLE
1.7.0 transforms

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7159]
_Issue [JP-2881](https://jira.stsci.edu/browse/JP-2881) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## transforms
  * Updated the NIRISS WFSS transforms from direct to grism image to V4.[#&#x2060;6803]

**Comment by nden** [comment]
ins test issue
