### ISSUE TITLE
1.5.0 ami

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7175]
_Issue [JP-2767](https://jira.stsci.edu/browse/JP-2767) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## ami
  * Allow AmiAverageStep to be run on list in command line interface [#&#x2060;6797]

**Comment by nden** [comment]
ins test issue
