### ISSUE TITLE
1.5.0 cube_skymatch

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7176]
_Issue [JP-2771](https://jira.stsci.edu/browse/JP-2771) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## cube\_skymatch
  * Enabled support for mnemonic DQ codes in the cube\_skymatch step. [#&#x2060;6733, #&#x2060;6736]

**Comment by nden** [comment]
ins test issue
