### ISSUE TITLE
Memory leak/overuse during processing loop with save_results

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7216]
_Issue [JP-2798](https://jira.stsci.edu/browse/JP-2798) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

We received a help desk ticket from a user developing a 1/f denoising algorithm for use in the detector1 pipeline flow. While running a step-by-step processing loop with multiple save_results present, they noticed that memory usage was ballooning, and for large input TSO datasets of size >~5 GB, the instance would request >30 GB of memory and crash their VM.

Minimal working example present in data location, along with a TSO uncal file for tests. The example code loops a call of the GroupScaleStep, which skips internally and saves a result. With a 117MB input dataset, a loop of 40 calls reaches 14 GB of memory usage. The memory usage persists and is easily noted when calling the example script with interactive flag, e.g. `python -i loop_groupscale_mwe.py`.

I've tested using .run() vs. .call(), disabling crds-steppars, using a different step (dq_init), and adding some computations after the step.call() in each loop; none had any effect.

**Comment by braingram** [comment]
This issue is being worked on in stdatamodels: https://github.com/spacetelescope/stdatamodels/pull/109

**Comment by braingram** [comment]
Fixed in https://github.com/spacetelescope/stdatamodels/pull/109
Fix included in 0.4.5 release of stdatamodels: https://github.com/spacetelescope/stdatamodels/releases/tag/0.4.5

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-2798?focusedCommentId=624506#comment-624506):_

Fix included in stdatamodels release 0.4.5
<https://github.com/spacetelescope/stdatamodels/releases/tag/0.4.5>
