### ISSUE TITLE
Additional WCS parameters in header for NIRISS WFSS pipeline products

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7220]
_Issue [JP-2698](https://jira.stsci.edu/browse/JP-2698) was created on JIRA by [Swara Ravindranath](https://jira.stsci.edu/secure/ViewProfile.jspa?name=swara):_

This is from a help desk call received on 07/27/2022 (INC0180163). The user noted that they can't find some WCS parameters in the NIRISS grism header, (e.g., CRVAl1, CRVAL2, cd1_1, cd1_2), while they exist in some simulated data and HST grism. Is there a way to add those parameters to the header?

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=599370#comment-599370):_

I looked at the image the user posted and it is a full frame WFSS image.  One cannot define the WCS for such an image since any given pixel may have spectra of different sources/orders falling at that position.  A separate question is whether one would like to add these FITS keywords for the 2D extracted images of the different orders for sources in the catalogue?  For a point source one can map the cutout pixels to wavelength and sky position, but that is not unique for extended sources.  One might map to wavelength and sky offset with the latter in arc-seconds.  That might be some use.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604044#comment-604044):_

For the purpose of determining the feasibility of adding any FITS WCS type keywords to grism image headers, it would be useful if someone who has knowledge of what's done for HST grism images could provide some details here, e.g. an example HST grism image header, how the WCS keywords are used, what are they expected to provide (e.g. crude source locations only or an attempt at wavelength solutions as well), etc.

**Comment by stscijgbot-jp** [comment]
_Comment by [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604423#comment-604423):_

In HST WFSS data, the WCS is defined as it would be for imaging. It therefore provides information about the pointing of the telescope. This is very good information to have as it provides a quick access to this information. This WCS contains the coordinate transformation for the undispersed beam. Since all grism configurations are done with respect to this reference frame, current 3rd party codes use this. 
I have tried to explain this a few times in Slack but got push back that this made no sense. However, as I tried to explain, this does make complete sense as it provides un-dispersed coordinates of the targets and this can be accessed using any legacy code users have, displaying of coordinates in ds9, and mosaicing etc...

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604434#comment-604434):_

I suppose there is no problem providing the equivalent imaging WCS for dispersed images in WFSS mode, but we have to document this clearly.

**Comment by stscijgbot-jp** [comment]
_Comment by [Swara Ravindranath](https://jira.stsci.edu/secure/ViewProfile.jspa?name=swara) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604444#comment-604444):_

I agree with [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal) . This is a priority for most of the grism users who are using legacy codes. And yes, the documentation can be included to note that the WCS is defined as would be for imaging and corresponds to the undispersed beam.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604447#comment-604447):_

I agree that an imaging-like set of WCS keywords would be relatively straight-forward to insert, but my main objection is that it leads us down a very slippery slope. By intentional design, we all agreed to not include any FITS WCS keywords in the headers of JWST spectroscopic products, because they make no physical sense and can't be used to derive a **real** wcs solution for the data. If we start putting it into WFSS image headers, how long will it be before the NIRSpec folks start asking for it in MOS and FS mode headers, or MIRI LRS?  It would also need to be made VERY WELL KNOWN (not sure how) that those WCS keywords in no way represent the actual WCS for the grism image.  I appreciate the argument that some existing software tools depend on that info, but at some point we all have to bite the bullet when it comes to giving up on old, obsolete practices and move into the 21st century. I miss lots of IRAF/STSDAS tasks that I can't run anymore, because there aren't any (or at least many) modern computer systems that will support its old 32-bit architecture. It's a pain, but I move on and make do with new, modern tools.

**Comment by stscijgbot-jp** [comment]
_Comment by [Swara Ravindranath](https://jira.stsci.edu/secure/ViewProfile.jspa?name=swara) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604466#comment-604466):_

Is there a way to implement this temporarily because it came in the help call from the users? Or, maybe give them a workaround to get the information they want? Maybe the user community can transition into the new methods once they are familiar with the data. Right now, JWST data is still new territory and users are trying to use the tools developed for HST grism data because they need to do the science quickly and prepare for the upcoming proposal cycles.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604470#comment-604470):_

Agreed. One person's "legacy" is another's "obsolete" ;-)  But we're here to support our community, so I concede.

I think someone like [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) might be able to demonstrate how the equivalent image WCS info can be retrieved from the wcs object that's in the grism images, which could be used as a workaround until we get updated products available.

**Comment by stscijgbot-jp** [comment]
_Comment by [Russell Ryan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rryan) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604481#comment-604481):_

I think the issue is that the GWCS has five transformations, the first four of which provide WORLD to DETECTOR and the last does DETECTOR to DETECTOR_GRISM.  This WCS in the fits headers would provide the very same information as the first four, and whatever the first four layers represent is what this would represent.  

Yes, of course the the pixels may contain light for different orders at different wavelengths and different objects, however that aspect is well handled by any grism code.  But without the first four transformations directly represented in the fits headers, one cannot use standard tools like ds9 to work with the data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604541#comment-604541):_

IMHO we need to patch ds9 to work with gwcs but this work was always pushed back as not high priority to the point that it's not on the table any more. Perhaps it's worth revisiting the decision by INS and MO.

I do not believe that if we put FITS WCS keywords in the headers users will slowly transition to the new software. They will simply fall into the mode that they know and are comfortable with. All the effort to create and represent an accurate WCS is gone then.

That said we'll do what you think is best. Can you confirm these are the keywords you want in the headers:

CRVAL

CRPIX

PC matrix

CUNIT (deg)

CDELT 

CTYPE (I need clarification on what this should be set to. I assume this will be a 2D imaging WCS and will not have a third spectral axis. Please confirm.) 

RADESYS = ICRS

WCSNAME

WCSAXES=2

SIP coefficients?

**Comment by stscijgbot-jp** [comment]
_Comment by [Russell Ryan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rryan) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604721#comment-604721):_

I suspect users will want (or I would want) the equivalent information for a direct image.  So for example, if it is NIRISS GR150C filter and F200W pupil, then they'll want the equivalent WCS that one would expect had the image been F200W.  Yes, I think SIP coefficients should be present, because that is how the trace and dispersion polynomials are determined.  [Swara Ravindranath](https://jira.stsci.edu/secure/ViewProfile.jspa?name=swara) or @⁣should comment, but I think the trace and dispersion solutions are measured on the distorted reference frame, and so the notional WCS should include the distortion information (even if only accurate to the level of 0.01pix). If [Swara Ravindranath](https://jira.stsci.edu/secure/ViewProfile.jspa?name=swara) agrees with the previous, then I think the answer to what CTYPE is RA--~~TAN-SIP , DEC~~-TAN-SIP, as that is what one would get for the effective direct image.  

 

I sense people are really worried about the fact that images are dispersed.  Personally, I don't think this is a big deal as in 8 years of supporting the HST grisms for WFC3 and ACS, no one has ever asked "what does the WCS mean in the dispersed image", as it would seem to be fairly obvious.  But, perhaps a compromise here could be in the WCSNAME keyword.  One could use something to highlight that, such as WCSNAME = "DIRECT_IMAGE"  or even "F200W" as in my example.  

 

Just my $0.02, but I'm not on the NIRISS team, and they should probably be the ones to comment more.  It would seem that one could just reuse the assign_wcs step, which currently exits early when it sees this WFSS image type.  If one just relaxes that check, then it would seem that all of what I said just naturally comes out.  In testing for myself, I did that.  I ultimately found it was just easier to change the FILTER/PUPIL settings and the EXP_TYPE keywords before running assign_wcs  (and resetting them after it was finished).

 

As for people not or reluctant to use GWCS.  I can't speak for everyone, but I will say.  GWCS is actually kinda slow. I did a bunch of performance tests where I disperse a single coordinate at 1024 wavelengths for the +1 order using the fifth layer (ie. the detector to detector_grism) transformation and with the third party codes that the community is using, then GWCS takes 18 to 22 times longer to run.  While both operations are quite fast, in doing the grism spectroscopy, in particular for the contamination modeling, one needs to do this operation many times.  So that performance cost of 20x becomes a bottle neck, particularly when trying to process contamination.  I suspect the performance difference arises from the standard codes are just using python built-in (like sum) and numpy functions (like np.array).  Again, just my $0.02.

**Comment by stscijgbot-jp** [comment]
_Comment by [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604723#comment-604723):_

Yes, the exact same thing that is put in the header by the pipeline if the PUPIL/FILTER (depending on instrument) was set to CLEAR instead of a grism name and the EXP_TYPE to imaging. As Russ pointed out, this is how we have gone around this particular pipeline issue in our programs.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604733#comment-604733):_

As I understand it we cannot put in FITS header WCS information that is accurate to a small fraction of a pixel because the distortion cannot be handled properly to that level of precision, which is why we had to go to the GWCS format in the first place.  I do not remember whether anyone has checked to see how big a discrepancy there is between the actual GWCS and the approximation in the FITS header for imaging, but I think it is a problem if we put in the imaging WCS information in the FITS header and then people simply ignore the GWCS extension and use the FITS keywords for analysis because this will introduce additional error in the results.  People will not do this for imaging, I think, because they will see that the approximate WCS from the header as in DS9 is not accurate.  But for WFSS reductions people might go ahead and do this without carefully checking the images.  If that is what people are going to do I would not favour doing adding the keywords; we should not facilitate poor data reduction.  It is one thing to give the FITS WCS keywords with the understanding that this is approximate and that the GWCS has to be used if people want accurate values, it is another thing if people use this in place of the GWCS because they dislike moving away from the FITS standard.

**Comment by stscijgbot-jp** [comment]
_Comment by [Russell Ryan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rryan) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=604796#comment-604796):_

[Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) I noticed that the assign_wcs step only puts in a fifth-order SIP, which reproduces the GWCS results at the level of 0.05pix.  I didn't know if there is a reason the order **must** be fifth order, so I increased it and refit the SIP coefs outside of the pipeline.  My 6-order model matches the GWCS solution at the level of 10^-4 pix.  I don't want to speak for everyone, but I think that level of reproduction is sufficient for many purposes (as I'm sure that there are far larger uncertainties lurking in WFSS data).  I didn't question why a 6-order was so much better, but I assumed that this level of agreement is probably because the distortion that was originally packaged into GWCS was effectively a 6 order polynomial — but that was just me daydreaming.  I can share those figures and analysis methodology if that'd be useful, but I'd like to close the loop on thing before I do.  

 

I appreciate not wanting to introduce unnecessary errors, but in the end the WCS+SIP is provided for other forms of data and the WCS+SIP representation for grism data would be no better/worse than for anything else.  So, I would imagine that whatever caveats are appropriate for the other data are also present here.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=612423#comment-612423):_

For completeness, this was discussed at the last quarterly meeting with JWSTMO, DMS, CalWG: [notes page|[https://outerspace.stsci.edu/pages/viewpage.action?spaceKey=JWSTPWG&title=2022-09-29+Meeting+Notes%3A+Development+Priorities#id-20220929MeetingNotes:DevelopmentPriorities-Build9.1TopPriorities:MajorDevelopment]] 



> Final decision: we'll add the FITS WCS to the headers so the community can do their science, but we need to let them know they're approximations and provide them with the tools to calculate the keywords themselves. We should discuss how to advertise the tool for imaging and spectroscopy that computes more accurate WCS solutions, since the community has been confused about this 


> [Alicia Canipe](https://outerspace.stsci.edu/display/~acanipe) will create a JP ticket for training the community on using the tool (we can move it to another project if needed) and will tag Patrick Ogle for user support

**Comment by nden** [comment]
Fixed in #7373

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=622901#comment-622901):_

FITS SIP WCS keywords added to WFSS grism image headers by #7373

via JP-2921

**Comment by stscijgbot-jp** [comment]
_Comment by [Jo Taylor](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jotaylor) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=644120#comment-644120):_

For NIRISS: confirmed that newer versions of the pipeline do include FITS SIP WCS keywords in WFSS grism images. I calibrated a NIRISS/WFSS rate file:

/ifs/jwst/wit/niriss/jotaylor/pipeline_testing/b9.2/jp-2698/jw01089001001_03101_00001_nis_rate.fits

using both pipeline versions 1.9.6 and 1.5.2 and confirmed that the newer products have WCS keywords and the older ones do not. I calibrated data only through Spec2.assign_wcs flat_field. Loading the newer cal image in ds9 properly showed sky coordinates as well.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2698?focusedCommentId=685326#comment-685326):_

Sounds like this is confirmed working as intended based on comments above, closing.
