### ISSUE TITLE
GROUPDQ Extension is not Populated with the DO_NOT_USE bit from the Mask File

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7222]
_Issue [JP-2862](https://jira.stsci.edu/browse/JP-2862) was created on JIRA by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan):_

Currently, the groupdq extension does not get populated with any DO_NOT_USE flags set in the mask file. The mask file represents detector effects that are constant and therefore only need to be set in the mask file. 
The jump and ramp fitting steps look for the DONOTUSE bit in the groupdq. By this not being set we end up with jumps being detected on bad pixels and then being extended into good pixels. We also get slopes determined for bad pixels when none should be calculated. 
I'm not sure what set actually creates the GROUPDQ extenstion but it should be very easy to populate the groupdq from the mask.
This bug interferes with my method for finding and extending large radiation events (snowballs and showers). It can be worked around by hacking the saturation file but that's only a workaround.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=604041#comment-604041):_

Given that the MASK reference file is used to flag pixels that are permanently bad, and hence bad throughout an entire ramp and exposure, the original design of the dq_init step was to have the MASK flags propagated into the PIXELDQ array, rather than the GROUPDQ array. The GROUPDQ array was reserved for flags that would be group-dependent. So perhaps this is actually more of a flaw in the jump and/or ramp_fit steps in that they are only paying attention to flags in the GROUPDQ array and not the PIXELDQ array as well. It would of course be pretty simple to update the dq_init step to copy the MASK flags (or at the least the DO_NOT_USE flags) into **both** the PIXELDQ and GROUPDQ arrays.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=604170#comment-604170):_

I think populating group_dq with at least the DO_NOT_USE and SATURATED bits from pixel_dq would be both the cleanest and lowest risk. Changing JUMP and RAMP_FIT to check both the groupdq and pixel_dq would be more work. In the end both would just end up doing an OR with those to bits across all the groups. But that's what DQ_INIT would have to do anyway.

I've done some quick hacks to get this work in my testing and the output from ramp_fit makes so much more sense. With the change bad pixels have zero slopes (should be NaN but that's not today's topic).  Currently, the cal.fits files are very misleading in that bad pixels have slopes but have DO_NOT_USE set so the reported slopes are not correct.

**Comment by nden** [comment]
Fixed in #7447

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=626609#comment-626609):_

If I remember correctly (which is not necessarily a valid assumption), I think this may have actually been a conscious design decision way back in the early days of the pipeline specifications, in that pixels flagged as DO_NOT_USE would still get calculations/corrections applied to them (e.g. dark subtraction, flat-fielding, ramp fitting, ...) and the potentially wacky results for those pixels would then be ignored in places where they could cause trouble (e.g. any calculations in downstream steps that actually depend on the pixel values, like measuring background, or detecting sources) by paying attention to the DO_NOT_USE flag that had been set for them. But hindsight always has more visual acuity than foresight, and hence I agree that it probably is better to just exclude them in steps like jump and ramp_fit.

I see that a cal_wg priority has been assigned, so SCSB will put this on our list of tickets for semi-immediate work.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=626822#comment-626822):_

My initial implementation doesn't show any real variation in the final dq plane - I can provide the code update as-is, but I'm wondering if you have an example uncal file that would show strong variation between the before and after, [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan)?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=628949#comment-628949):_

Hopefully folks won't be too surprised (or start filing lots of help desk tickets) when suddenly their rate and cal files have way more NaNs in them than before. I guess we'll just direct their questions to [Michael Regan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mregan) ;)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=629968#comment-629968):_

Fixed by #7447

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=638605#comment-638605):_

I took a look at some MIRI data that I just recently processed with build 9.2 code. I see the pixels from the PIXELDQ marked in the GROUPDQ. The HOT pixels from the PIXELDQ (2049 for HOT and DO_NOT_USE) get flagged as SATURATED and DO_NOT_USE (3) in the GROUPDQ plane. Pretty much all other flags from the PIXELDQ have value 1 (DO_NOT_USE) in the GROUPDQ. I'm assuming that in those cases, the pixels were flagged as DO_NOT_USE in the PIXELDQ array along with some other flag and only the most important portion of the flag, the DO_NOT_USE is copied over. So long as the HOT is meant to be flagged as SATURATED and the DO_NOT_USE portions of other combined flags are all that is meant to be copied over, this works.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=638675#comment-638675):_

The original request was in fact to only copy DO_NOT_USE flags from the MASK ref file into both the pixeldq and groupdq arrays during the dq_init step. It did not include the copying of other informational flag values (like HOT, DEAD, etc.), and that's what's been implemented (as you've discovered).

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-2862?focusedCommentId=638680#comment-638680):_

Ah, of course, the SATURATED pixels were put there by the saturation step. So yes, I'd say this is working as requested.
