### ISSUE TITLE
bug in saturation check for NIRSpec IRS2 data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7228]
_Issue [JP-2933](https://jira.stsci.edu/browse/JP-2933) was created on JIRA by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol):_

There seems to be a bug in the saturation flagging code for NIRSpec IRS2 data. Pixels that have the DO_NOT_USE and NO_SAT_CHECK flags set are still being flagged as saturated. This results in a large number of 3x3 blocks of zeroed-out pixels mostly around "dead" pixels (DQ=1025), losing a considerable amount of usable data in IRS2 exposures.

Note we used a modified mask reference file for testing, which is included in the data directory above.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=609984#comment-609984):_

JP-2611 was implemented to fix this situation and appears to be applied to IRS2 data, as shown by the code block starting here:

<https://github.com/spacetelescope/jwst/blob/master/jwst/saturation/saturation.py#L138>

That update was included in B8.1 (Cal 1.6.2), so I'm surprised the effect is still being seen. Will need to look at the data and figure out why pixels flagged with NO_SAT_CHECK are still getting flagged as SATURATED.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=609990#comment-609990):_

Does the modified mask file contain anything relevant to this processing, e.g. NO_SAT_CHECK flags or anything like that?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=610017#comment-610017):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) the modified mask sets DO_NOT_USE for the dead pixels, which the current mask reference files in CRDS do not do (though that should be rectified later this week).

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=611081#comment-611081):_

Bit of investigation has found the following, and a request for verification.
 * The override MASK file, nirspec_mask_nrs1_i_forcrds.fits, has DO_NOT_USE set, but not NO_SAT_CHECK.
 * The CRDS provided SATURATION ref, jwst_nirspec_saturation_0027.fits, has no flags set in its DQ extension.
 * The code, as referenced above, is expecting to find NO_SAT_CHECK flags in the SATURATION reference. Have not tested, but the code would handle NO_SAT_CHECK if present in the SATURATION reference file.
 * However, there appears to be no code in the SaturationStep that references the input's PIXELDQ or GROUPDQ to prevent saturation checking of DO_NOT_USE pixels.

~~Question 1~~: The one implication of this issue is that DO_NOT_USE should be honored. Is this true?
_Answered: JP-2611 says that DO_NOT_USE should not be apart of checking._

{-}Question 2{-}: Currently the NO_SAT_CHECK is retrieved only from the SATURATION DQ array. Is there desire to also look for this flag in the MASK reference?
_Answered: The NO_SAT_CHECK flag should only come from the SATURATION DQ array._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=611465#comment-611465):_

The Cal WG discussed this on 2022-06-07: <https://outerspace.stsci.edu/display/JWSTCC/2022-06-07+Meeting+Notes>

The consensus was:
 * proposal is to use the no_sat_check dq flag in the dq_init reference file  (note the typo here, in that it's not the "dq_init" reference file, but the saturation reference file)
 * action to instrument teams to find out which pixels these are and to set the bit accordingly in this reffile

Hence JP-2611 was implemented to update the saturation step to skip saturation checking for pixels that have NO_SAT_CHECK set in the saturation reference file DQ array. No updates were made to check for DO_NOT_USE flags in the input science data. So either the NIRSpec team needs to put NO_SAT_CHECK flags in their saturation ref files, or the matter needs to go back to the Cal WG to see if everyone agrees to also skip saturation checking for DO_NOT_USE pixels in the input science data (presumably set via the MASK ref file).

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=611483#comment-611483):_

In light of the answers to the questions, as given above, and the facts that the SATURATION references in CRDS have no flags set, then the situation, as initially described, is exactly as expected: The addition of DO_NOT_USE flags does not affect the operation of the saturation step, as designed.

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) do you agree with this assessment? If so, I will close out this issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Cheryl Pavlovsky](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cherylp) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=613331#comment-613331):_

Actually, the nirspec saturation files in crds do have no_sat_check flags set in the DQ array. The problem is the DQ_DEF table has the value listed as 2 and the DQ extension has them as 2097152. THis is because, the original reffile had the no_sat_check flag set to 2 in both the DQ and DQ_DEF extensions. When the file was then read into the datamodl, the datamodl changed the value in the DQ ext but not the DQ_DEF extension. When the pipeline sees this, it ignores the flags entirely.

I have updated the DQ_DEF table to match the DQ extension of 2097152. But when I try to certify, I get this warning "Constraint (warn_only(SCI_ARRAY.SHAPE[-2:]in[(2048,2048),(32,2048),(64,2048),(256,2048)])) is not satisfied."

The actual array is 260, 2048. I started with the files already in CRDS. Why did this work before and is it a problem now? [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=613346#comment-613346):_

[Cheryl Pavlovsky](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cherylp) My only guess is that the certify checking has gotten more strict since the previous versions of those ref files were delivered?  If the 2048x260 size is legit (which I believe it is, for the ALLSLITS or BRIGHTOBJ subarray?), then that needs to be added to list of values that certify is checking against.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=613373#comment-613373):_

Are the SCI and DQ arrays the same shape? I.e. both should be 2048x260.

**Comment by stscijgbot-jp** [comment]
_Comment by [Cheryl Pavlovsky](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cherylp) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=613433#comment-613433):_

yes all of the arrays are 2048x260, but we usually deliver allslits/brightobj as 2048x256. Will the extra rows cause an offset in how the reffile is applied? If I remember correctly we may have added a few rows because we didn't know exactly where the final subarrays would end up.

If the pipeline knows what to do with a 2048x260 and this is only a warning, I will deliver the new files and start a crds ticket to expand the expected sizes. And then this ticket can be closed. thanks [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=613436#comment-613436):_

Of course it appears that CRDS certify still needs to be convinced that 2048x260 is an allowable size for the data arrays.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=613499#comment-613499):_

[Cheryl Pavlovsky](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cherylp) from your message, it looks like it is only a warning, so it can still be submitted. You can try submission to JWST TEST to just confirm. Regardless, file a CRDS issue to fix the validation to include this shape and attach an example reference to that issue.

**Comment by nden** [comment]
JIRA ticket was closed, closing this one

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2933?focusedCommentId=621343#comment-621343):_

There is currently no code issues found. There were issues found with both the references and CRDS which will be handled through CRDS issues.
