### ISSUE TITLE
JWST Tweakreg step should be able to align using user-supplied catalogs and single images

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7233]
_Issue [JP-2620](https://jira.stsci.edu/browse/JP-2620) was created on JIRA by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe):_

While the JWST Pipeline Tweakreg step has a built-in ability to align images to Gaia, there are many cases where observers may need to supply other absolute astrometric reference catalogs when running offline (eg, regions of the sky that are sparse in Gaia sources or with all the Gaia sources saturated, or other failure modes for the Gaia matching), where other catalogs may be more appropriate.

In addition, users may also want to provide their own catalogs that they have run for the images that are being aligned (since the image catalogs produced by tweakreg might not always be optimal in all situations); in this case the use mode is to provide to tweakreg, for each image being aligned, also a corresponding catalog for that image (with source locations in x,y pixel coordinates for that image), for all the images being aligned.

Both these capabilities (providing a user-supplied reference catalog of RA,Dec positions, and providing a user-supplied image catalog of x,y positions for each image being aligned) have been standard implementations on HST tweakreg for many years and observers are now expressing a desire to have these capabilities also in tweakreg for JWST data.

This capability is important in enabling observers to produce scientifically optimal products when running the pipeline offline.

This ticket requests the ability to pass a user-supplied astrometric reference catalog as a parameter to the Tweakreg step, which if supplied would be used as ref_cat, instead of Gaia, to perform the absolute astrometric matching.

A user-supplied catalog would at a minimum be expected to contain columns for Right Ascension and Declination, in units of degrees.

This ticket also requests the ability for users to supply image catalogs, one corresponding to each image being aligned, with the source locations specified in x,y pixel positions on the image.

In summary, these interface improvements are being requested:
 * an optional user-supplied general reference catalog, that can be used instead of gaia, containing at a minimum RA and Dec columns
 * an optional user-supplied catalog for each image being aligned, containing at a minimum the x,y pixel positions of sources in the image
 * exposing these parameters for the reference catalog (currently that are hardwired in the code): minobj, searchrad, use2dhist, separation, tolerance. xoffset, yoffset, fitgeometry, nclip, sigma
 * ability to align just a single image to the reference catalog, ie gracefully skip the part that attempts to align images to each other first, since currently the code exits with an error if just a single image is provided.
 * option to provide an initial solution as input (shift, rotation, scale), with the option of not having tweakreg do any additional fitting but simply apply this solution directly to the input images.

This ticket is of critical importance for science since there continue to be instances of tweakreg failing in the pipeline, due to default parameters not always being successful, and therefore users need to be able to run tweakreg offline with these additional levels of flexibililty.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=589224#comment-589224):_

[Armin Rest](https://jira.stsci.edu/secure/ViewProfile.jspa?name=arest) mentioned to me a few days ago that someone on his analysis team has made code changes to enable this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=596545#comment-596545):_

This was discussed in [JWST Cal WG Meeting 2022-07-05](https://outerspace.stsci.edu/display/JWSTCC/2022-07-05+Meeting+notes) for this work to proceed with implementation, further discussion about the specifics of the details can take place in the comments here as implementation proceeds.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=598519#comment-598519):_

Question for clarification on the request for:
 * an optional user-supplied catalog for each image being aligned, containing at a minimum the x,y pixel positions of sources in the image

Do you mean a unique (separate) catalog to be used for each individual input image, i.e. a one-to-one list of input images and catalogs? In the case of NIRCam, for example, where multiple images from each of the detectors within a given exposure are treated as a single "image" (or "group" in the terminology used in the tweakreg step), would that be one catalog per group of images within a single exposure (e.g. the 8 short-wave images from one exposure) or one catalog for every detector image?

Also, in this use case, would tweakreg do just a single alignment process, using just the provided catalogs, or would there also still be the option to then do final alignment to either GAIA or yet another user-supplied catalog?

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=598783#comment-598783):_

I wish #1556 never happened as having these two steps separate would have allowed for a much greater flexibility.

Is this too late to undo? That is, can we split source finding from WCS alignment? Also, currently tweakreg step performs two alignments: relative alignment of input images and then alignment of all input images as a single group to Gaia. Fundamentally, there is not much difference between these two alignments. Can we make tweakreg step perform a single alignment and have user specify what alignment they want and run this step 2 or 3 or whatever number of times they want?

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=599378#comment-599378):_

Thanks [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)  for the question.:

> Do you mean a unique (separate) catalog to be used for each individual input image, i.e. a one-to-one list of input images and catalogs? In the case of NIRCam, for example, where multiple images from each of the detectors within a given exposure are treated as a single "image" (or "group" in the terminology used in the tweakreg step), would that be one catalog per group of images within a single exposure (e.g. the 8 short-wave images from one exposure) or one catalog for every detector image?

Yes, it would be the latter, ie one catalog for every detector image – the basic idea is simply to pass it a catalog for each detector, so that tweakreg would not attempt to create its own set of catalogs but simply use these input catalogs instead.

Ie, essentially the user would provide to tweakreg a set of "ecsv" files that look the same as those that tweakreg can currently write out for each detector image - just a simple file with at a minimum the columns "xcentroid" and "ycentroid"

In terms of how to pass these to tweakreg, one option could be to for the user to just specify a parameter that is a suffix to be appended to the input image filename (eg "_custom.ecsv") - so, eg, if the images are called:
 * jw02736001001_02105_00009_nrcb1_cal.fits
 * jw02736001001_02105_00009_nrcb2_cal.fits

and they specify a suffix parameter value of "_custom.ecsv"

then they would need to have in the directory a set of catalog files like:
 * jw02736001001_02105_00009_nrcb1_cal_custom.ecsv
 * jw02736001001_02105_00009_nrcb2_cal_custom.ecsv

and so tweakreg would read these and use them instead of trying to generate its own catalogs.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=599379#comment-599379):_

In terms of breaking down the work in this ticket, I very much like the approach of dealing with the following two tickets first before moving onto the other tickets, and implementing these two tickets in the dev pipeline at this time:

<https://jira.stsci.edu/browse/JP-2686>  (Allow passing an external catalog to tweakreg)

<https://jira.stsci.edu/browse/JP-2678> (Expose hard-coded parameters in tweakreg)

Once the above are implemented in a dev version,  please let us know here so that we can try it out

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=599382#comment-599382):_

Then after those two tickets (JP-2686 and JP-2678) are implemented in a dev version, you (or [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva)) could set up separate JP tickets please for the next 2 items, in this order of priority:
 * ability to align just a single image to the reference catalog, ie gracefully skip the part that attempts to align images to each other first, since currently the code exits with an error if just a single image is provided.
 * an optional user-supplied catalog for each image being aligned, containing at a minimum the x,y pixel positions of sources in the image (with the details as described in the recent comment)

Then finally if you could set up a JP ticket please for this item, that would help decouple it from the others and we could then discuss its details on that ticket:
 * option to provide an initial solution as input (shift, rotation{-}, scale){-}, with the option of not having tweakreg do any additional fitting but simply apply this solution directly to the input images.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=599390#comment-599390):_

[Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) :

??Then after those two tickets (JP-2686 and JP-2678) are implemented in a dev version, you (or ??[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva)??) could set up separate JP tickets please for the next 2 items, in this order of priority:??
 * ??ability to align just a single image to the reference catalog, ie gracefully skip the part that attempts to align images to each other first, since currently the code exits with an error if just a single image is provided.??

I am currently working on JP-2686 and this point above - skipping first part of alignment - is done in <https://github.com/spacetelescope/jwst/pull/6938.> It needs review/testing.

**Comment by nden** [comment]
Fixed in B9.2

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=628646#comment-628646):_

[Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) All tasks in this ticket were implemented. Close?

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2620?focusedCommentId=628757#comment-628757):_

Thanks very much. From my perspective you can go ahead and close this ticket, if Howard concurs, and any issues with implementation would then be tracked as bug reports.
