### ISSUE TITLE
Define and implement regression test matrix

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7235]
_Issue [JP-2605](https://jira.stsci.edu/browse/JP-2605) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

## Issue

With respect to CRDS, there are three servers that are in various states:
 * jwst-crds: contexts usable by the OPS-installed version of jwst/crds
 * jwst-crds-pub: contexts usable by the latest release of jwst/crds
 * jwst-crds-test: contexts usable by the development release of jwst/crds

Current standard regression tests jwst development again OPS, which is not fully appropriate. Need to define and decide on the matrix of cal state vs. crds server to use.
## Testing matrix

The testing matrix to handle all situations is as follows:
||Jenkins Job||CAL version||CRDS/context||Artifactory||Comments||
|JWST*|master|TEST/jwst-edit|dev|Nightly|
|JWST-devdeps*|master|TEST/jwst-edit|dev|Weekly|
|JWST-release|latest release|PUB/jwst-edit|<release>_pub|Run on new context|
|JWST-ops**|ops release|OPS/jwst-edit|<release>|Run on new context|
|JWST_devops|master|OPS/jwst-edit|dev_ops|Run on new context|
|JWST_devpub|master|PUB/jwst-edit|dev_pub|Run on new context|

* Jobs that already exist
 ** Possibly redundant with ReDCaT

Minimally, the current nightly regression only needs to be reconfigured to use the TEST server. The other situations could be left to manual intervention.

Otherwise, separate Jenkins jobs can be setup to run the other tests, again either manually, or on some regular schedule. There may be possibility to have these automatically triggered with context updates.

Other comments
 - SDP will continue to get development versions of JWST through the JWST job.
 - SDP will get any official JWST releases through github.
 - The JWST-ops job may be redundant. ReDCaT has their own version.
 - There will always be special cases. Jobs setup to handle the common situations.
 - JWST and JWST-devdeps are critical during routine development.
 - JWST-release and JWST-devpub are most critical during Build integration.
 - Investigate how to implement "Run on new context". In the meantime, this can be left to be manually run jobs or weekly.

## Artifactory Management

Current procedures, when a release is made, is to copy the `dev` environment to a release-specific environment. The release-specific environments, truth-wise, would be kept up to date until the next release is made.
  
## Actions
 - Setup Jenkins jobs as in the table
 - Move and update procedures from the wiki to Innerspace. In particular, update how Artifactory environments are managed.

## Quesitons
 - Should Jenkins jobs be setup for all possibilities? Or should we just use
 procedures to handle the other cases? The switch-off is whether to have multiple jobs
 that may not run all the time vs. as-needed procedures.
 - Is JWST-ops job too redundant? Do we care?

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2605?focusedCommentId=586470#comment-586470):_

When we make a delivery to OPS or make a public jwst release on PyPi we copy the regression test inputs and truths to a directory matching the release tag. These directories can perhaps be used for continuous testing of those specific environments with a changing CRDS context, PUB or OPS. Then "dev" would be reserved for development.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2605?focusedCommentId=586673#comment-586673):_

Yes, and fits in with the current procedures already. Makes total sense. This removes any need for the potential splitting of inputs from truths, keeping the environments self-contained. Amending the description.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2605?focusedCommentId=587191#comment-587191):_

Description update. Commentary requested.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-2605?focusedCommentId=605759#comment-605759):_

The attached [^regression_data.xlsx]file here provides with the list of regression test data we are currently using to test reference file deliveries. I am sharing this here because it seems to be related to this ticket and we were going to see if we could use the same data (as we are going to request the instrument teams to provide input on which in-flight data to use). If this is not the right place, please let me know. I do plan to share this with the instrument teams at the next DMSWG meeting.

**Comment by nden** [comment]
JIRA ticket was resolved, closing this one.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2605?focusedCommentId=623089#comment-623089):_

This issue was generated because of the addition of the JWST PUB server. Since this server is no longer in-the-mix, this issue, as described, is no longer relevant.

Other issues/discussions with testing should be opened in new issues.
