### ISSUE TITLE
Update JDox for showers and snowballs in jump step

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7237]
_Issue [JP-2947](https://jira.stsci.edu/browse/JP-2947) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

[Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) FYI

We'll need to make sure the algorithm pages in JDox are consistent once the baseline snowballs and showers algorithm is in ops. I can create the JDOXCM ticket, just adding this one for tracking <https://jira.stsci.edu/secure/Dashboard.jspa?selectPageId=21000>

**Comment by nden** [comment]
not a pipeline ticket

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2947?focusedCommentId=685360#comment-685360):_

JDox has been updated with the latest information about showers/snowballs.
