### ISSUE TITLE
1.7.1 engdb_tools

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7242]
_Issue [JP-2964](https://jira.stsci.edu/browse/JP-2964) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## engdb\_tools
  * Update HTTP status list to include 4xx issues [#&#x2060;7026]
 * Add retries and timeout parameters to engineering access calls [#&#x2060;7025]

**Comment by nden** [comment]
ins test issue
