### ISSUE TITLE
1.7.1 straylight

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7244]
_Issue [JP-2966](https://jira.stsci.edu/browse/JP-2966) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## straylight
  * Fix a bug in calibrated MRS slopes from small pedestal rate offsets between exposures by reintroducing zeropoint subtraction using dark regions of MRS detectors. [#&#x2060;7013]

**Comment by nden** [comment]
ins test issue
