### ISSUE TITLE
1.8.0 resample_spec

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7250]
_Issue [JP-2959](https://jira.stsci.edu/browse/JP-2959) was created on JIRA by [JWST PARSER](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jpparser):_

 ## resample\_spec
  * Update computation of target RA/Dec for slit spectra to handle data containing negative spectral traces (due to nodded background subtraction) in a more robust way. [#&#x2060;7047]
  
>   * Move update\_slit\_metadata out of ResampleData and into ResampleSpecStep. [#&#x2060;7042]
>

**Comment by nden** [comment]
ins test issue
