### ISSUE TITLE
Sampling artifacts in NIRSpec IFU cubes when using the default weighting

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7260]
_Issue [JP-2571](https://jira.stsci.edu/browse/JP-2571) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The default cube_build weighting scheme, esm, is producing strange results for NIRSpec exposures of point sources. The spatial reconstruction appears somewhat jagged, with the PSF core and wings somewhat smeared out and asymmetric. The wavelength resampling also looks incorrect, with significant oscillations seen in the x1d spectrum (most prominent at wavelengths where the spectral resolution is lowest). See the first attachment, which shows two wavelength slices and the x1d product for a single exposure with PRISM (note the PSF core was saturated between ~0.8 to 1.6 microns). It's possible that the other cube_build parameters need to be adjusted, however, these results are not consistent with what we saw using simulations using the same defaults. I do get excellent results using the drizzle option (see second attachment), which suggests that that should be the default weighting option until/unless we can fix the problem with esm.

Example data can be found in ████████████████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=581008#comment-581008):_

Initially reported in [JWSTDMSDR-5788](https://jtar.stsci.edu/browse/JWSTDMSDR-5788), which contains more details and examples.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=581554#comment-581554):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) and [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) – when [Swara Ravindranath](https://jira.stsci.edu/secure/ViewProfile.jspa?name=swara)  and I looked at this ticket it didn't seem to be critical or high priority to fix for commissioning since a demonstrated solution exists, as demonstrated by using the existing 'drizzle' option in the code when running offline, so we've assigned it a calwg_med priority for now – however, we're leaving the NIRSpec priority up to you, so could you take a look please at assigning it a  NIRSpec team priority as well in the 'INS team priority' field ((nrs_high, or nrs_med, etc, depending on your assessment, and we may then re-evaluate our calwg priority if needed)?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=595974#comment-595974):_

Given that the default weighting option for cube_build has now been changed to "drizzle", for both MIRI and NIRSpec, is this still an issue? Does it need any reference file updates to go along with the default parameter change?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=604658#comment-604658):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) [Swara Ravindranath](https://jira.stsci.edu/secure/ViewProfile.jspa?name=swara) can we close this ticket ? Did switching to the "drizzle" method fix this issue ?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=606429#comment-606429):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) we're now seeing inconsistent results with either weighting scheme. Most recently, I tried producing a combined cube for a data set processed with updated flat reference files, and the result produced with drizzle weighting is showing a sinusoidal pattern in the 1D extracted spectrum, as well as a slightly smeared PSF. Results using emsm weighting are actually much better in this case. I'm perplexed because the drizzle product before the reference file update looked good, and the new flat corrections are not introducing any kind of pattern into the cal data that could explain the difference. Should I file a new ticket?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=606493#comment-606493):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) Don't file another ticket but if you can add as much information to this ticket. The data you used that gave you the sinusoidal pattern in the 1D extracted spectrum and any other results that might help figure this out

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=606502#comment-606502):_

Particularly critical- is the spectrum extracted from a single spaxel or a larger region?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=606564#comment-606564):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I put data on █████████████████████████████████████ Subdirectory "new" contains all of the cal files with the new flux calibration, versions of the combined cube using emsm or drizzle weighting, and an exposure-level cube generated with drizzle weighting. "old" contains the original exposure-level cube generated with drizzle weighting using an input cal file without the new flux calibration (and including nod subtraction, which the new files do not have); I mistakenly overwrote all of the original cal files, so I can't provide them without rerunning everything - let me know if you need them.

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) I checked with cubeviz and see the sinusoidal pattern in the 1D spectrum from the "new" drizzle cube regardless of aperture size. It is not there in the emsm cube. These data contain a single point source.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=609269#comment-609269):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) Just double checking something. You did not have the x1d spectrum in the directory. So did you just run extract1d on the data in the 'new' directory with all the default parameters  - so on:

jw01128-o009_t007_nirspec_drizzle_g235h-f170lp_s3d.fits

and 

jw01128-o009_t007_nirspec_emsm_g235h-f170lp_s3d.fits

If so I  will produce the X1d files and look at them. Can I just use the cal files in the 'new' directory to make new s3d files if I want to test things. From your comment above the new directory does not have the nod subtraction done. Do you think that will make a difference in trying to understand what is going on with the two different weighting ?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=609310#comment-609310):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) sorry about that. I had to rerun extract_1d with a different center_xy because the default was not centered on the source. I just copied the x1d products from each combined cube to central store. In case you want to rerun with different parameters, I used center_xy = 35, 39, and subtract_background = False.

I don't think the nod subtraction would make any difference here? The background level is fairly negligible for this high-resolution grating.

Also note that our bad pixel flagging is wonky here because of a reference file problem, which should be fixed imminently. If that is making your life difficult, I can reprocess using the improved reference files.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=610387#comment-610387):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) 

I am not having any luck of making sense of the extract1d files you posted. I have not plotted many extracted spectra so maybe my tool is not good enough. I am pulling out the wavelength and flux columns and plotting them. It is a mess. Could you post what your plots look like so I know what I should be looking at. One thing that would help what is a reasonable flux range I should be looking at. There are pixels with extremely high values are those real ?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=610393#comment-610393):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) ok let me get you new cubes with improved pixel flagging.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=610400#comment-610400):_

The very high values are an artifact introduced because our original mask files do not set the DO_NOT_USE bit for dead pixels. After filtering out the crap, I get the attached 1d spectrum (in blue). There's still a lot of bad pixel spikes, but you can see the wavy pattern of the continuum (cf. the predicted spectrum in black). But this will be much easier to see when I generate a new cube using the improved mask, I'll try to get that ready by tomorrow.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=610694#comment-610694):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I put improved cal files, plus the two flavors of combined cubes, in █████████████████████████████████████████ Most (but not all) of the outliers are now being masked properly! To save time, I only processed the data on the NRS1 detector, but the same results hold - the drizzle version has the sinusoidal pattern, while the emsm version does not.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611127#comment-611127):_

Ok I know see what you are referring to in the extract1d spectra. I need to refresh my memory on how drizzle is working and why it might cause this. I attached the screen shot of the extract 1d for both types of weighting. 

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) have any suggestions on what I should look at?

My first thought is something is not correct in the wavelength direction in drizzle for NIRSpec. If we were to smooth out the spectrum with a box car filter in wavelength direction it might be close to matching the emsm. Is there something we assumed concerning drizzle for MIRI that does not hold for NIRSpec.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611129#comment-611129):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) also since you put 4 cal files in that directory I assume all 4 were used to create the IFUCube - right ?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611166#comment-611166):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) yes, that's right, the cube is the combination of all 4 cal files (a 4-pt nod observation).

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611230#comment-611230):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)  I wanted to plot the spectra from each dither - so run calspec2 on each file to make the cube and x1d file. I just wanted to see if this pattern is in each dither location or maybe related to when we put all the dithers together. Do I need to shift the x,y extraction location for each cube if I do that ? The default ones are not correct

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611243#comment-611243):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I just noticed that the wmap between the two cubes you made are very different. 

I am not sure if that could cause what we are seeing but I am going to look into that. 

The emsm weight map values are about 14-15X that of the drizzle weight map values

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611285#comment-611285):_

EMSM ROI can be pretty big; I've noticed the values are often significantly higher than the drizzle wmaps for MIRI as well.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611290#comment-611290):_

I popped up both cubes quickly and could see this structure when doing a ds9 spectral plot with various different apertures.  Unlike in the MIRI case, it didn't seem to reduce in magnitude as the aperture size increased.  One possibility is that there could be a bug in the drizzled pixel footprint computation- that would explain drizzle being affected while emsm is not.  If it were a unit issue I think emsm should show it too.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611293#comment-611293):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I was trying to re-run cube build and change the wavelength roi for drizzle, but I ran into some problems. So I just built a cube using the 4 dithers with no changes. My cubes do not look like yours. I made an association that contained the 4 cal files and just ran the cube_build step.

Do I need to override a reference files or something. 

I attached am image of what I mean. Your drizzle cube is on the left and one I just made in on the right. I picked roughly the central wavelength - but mine seems to show the 2 dithers much more than yours.
What step have I missed  that I need to include ?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611297#comment-611297):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) yes, you need to use a specific x,y center for each exposure. The default doesn't work because the WCS is off.

In your cube example, it looks like you only included 2 of the 4 nods? The star is placed into separate corners of the IFU aperture in each nod, so the spatial axes of the combined cube should be roughly symmetric.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611318#comment-611318):_

My assocation contains the 4 files:

jw01128009001_03106_00001_nrs1_cal.fits
jw01128009001_03106_00002_nrs1_cal.fits
jw01128009001_03106_00003_nrs1_cal.fits
jw01128009001_03106_00004_nrs1_cal.fits

The logging says it maps each of the files to the cube;

2022-10-12 12:57:13,955 - stpipe.cube_build - INFO - Mapping each NIRSpec slice to sky for input file: jw01128009001_03106_00001_nrs1_cal.fits

2022-10-12 12:58:42,239 - stpipe.cube_build - INFO - Mapping each NIRSpec slice to sky for input file: jw01128009001_03106_00002_nrs1_cal.fits

2022-10-12 13:00:08,740 - stpipe.cube_build - INFO - Mapping each NIRSpec slice to sky for input file: jw01128009001_03106_00003_nrs1_cal.fits

2022-10-12 13:01:34,276 - stpipe.cube_build - INFO - Mapping each NIRSpec slice to sky for input file: jw01128009001_03106_00004_nrs1_cal.fits

 

I just made sure that I had the most recent version of the pipeline. So what could be wrong ? It definitely looks like I do not have the complete dither set.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611337#comment-611337):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I am very stuck. I looked at all the planes of my IFU Cube and it is using all 4 dithers. Here is a plot of top (your cube) bottom my cube. The flux plane is on the left and the weight map is on the right. The weight map values are about the same in the two cases.  See attached image. The values that seem to be missing my cube are just really small values - they are not zero which would be the case if I only used 2 dithers. I checked the headers and it seems the same reference files are used in both cases. 

I am only running cube_build. Should I have subtracted a background or something from the data that would equalize them out ?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611342#comment-611342):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) that's very strange. I ran the spec3 pipeline, skipping outlier detection (so only cube_build and extract_1d were actually executed). I can't think of why you'd be getting a different result. What are the flux values in the "missing" regions on the right and left?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611463#comment-611463):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) I created a new environment and went and got the newest master branch of the pipeline. Now my cube is matches  yours in appearance if I  have each cube set its own scaling.  

But the values for the spaxels are VERY different  (image yours/image mine) ~ 1.36 E 10.

The images look identical by eye if I do not set them to the same scale. So this is some units issue . I suppose. What could it be ?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611624#comment-611624):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)  I looked at the ratio of several wavelength planes and the ratio of your cube to my cube is ~ 10e10 different. Which is so strange because I am using your cal files. I have put my version of the cube at  ███████████████████████████████

 

What version of the pipeline are you using. Let me try using exactly the same version you are.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611626#comment-611626):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) your cube seems to be a factor of ~1e10 too small. The counts on-source are roughly 1e-19, while in the cal files they are ~1e-9. You're sure you're using the latest cal files in █████████████████████████████████████████ I copied them there about a week ago.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611749#comment-611749):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol)  Thank you that did it!  I thought I got those cal files when I got the you made cubes, but I must not have. Now my cubes are like yours and I can start to track down this problem with the drizzle method of NIRspec

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=611910#comment-611910):_

Good news/weird news/bad news. 

Bad news: I've run across an example of this same kind of thing happening in a MIRI MRS example (drizzle looks weird, EMSM doesn't).

Weird news: It doesn't show up in all data, only **some** data

Good news: Hopefully easier for me to help debug it now that it involves MRS too??

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=612059#comment-612059):_

Looks like the MRS failure case I mentioned above was an outlier detection failure; i.e. known cause that doesn't help us with this issue.  Sorry :(

Looking at the NIRSpec code, one thought that strikes me is what impact the 'near the slice boundaries the corners can become Nan - do not use pixels with Nan corners' statement is having.  For MIRI, we never have the case where a pixel with a valid transform at the center has a nan transform at the corner.  Transforms exist or not on a per-pixel basis; if there's a transform for a pixel it is valid everywhere within the pixel.  That's why we use the +0.499 etc. code to move us right up to where the transform is still valid.

If that's not true for NIRSpec then I can imagine weird behaviour could result.  So question for James; does the WCS transform ever return nan in some parts of a pixel and values in other parts?  If so we'll need to rethink the corner computation method.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=612447#comment-612447):_

That looks fantastic, thanks [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) and [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) !

**Comment by hbushouse** [comment]
Fixed by #7306

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=613298#comment-613298):_

Fixed by #7306

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-2571?focusedCommentId=666458#comment-666458):_

Testing with the current pipeline, I think both 'emsm' and 'drizzle' weights now produce good results.

I ran both weight types for cube_build in spec3 on the data referenced, with auto-centering for extract_1d and otherwise default reduction, and both look very good now – see attached (jw01128009001_03106_00003_x1d_v1.12.3.png).
 
Input data was: jw01128009001_03106_0000[1-4]_nrs1_rate.fits, from MAST (v1.10.1, jwst_1107.pmap), reduced through spec2 and spec3 with v1.12.3, jwst_1138.pmap.

I think this issue is resolved and can be closed.
