### ISSUE TITLE
set_telescope_pointing does not properly account for subarray and aperture

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7267]
_Issue [JP-2821](https://jira.stsci.edu/browse/JP-2821) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Module `set_telescope_pointing`, when applying the SIAF transformation, does not also apply corrections for subarrays and aperture location. This is resulting in bad CRPIX* values being calculated.

**Comment by nden** [comment]
JP ticket is resolved

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-2821?focusedCommentId=627132#comment-627132):_

Resolved by [PR#&#x2060;7449](https://github.com/spacetelescope/jwst/pull/7449)
