### ISSUE TITLE
APCORR file docs improvement

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7270]
_Issue [JP-2700](https://jira.stsci.edu/browse/JP-2700) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

From help desk ticket: [INC0179964](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=c34cec7d47fc9950ec5b9448436d43d4%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

Explanations of the values in the APCORR file might be helpful for users working on the aperture photometry or digging into the APCORR files. Should we add this to the descriptions or the reference file section for the steps where the file is used? 

Source catalog
 * Documentation: <https://jwst-pipeline.readthedocs.io/en/latest/jwst/source_catalog/index.html#source-catalog>
 * Maybe add the information in the description of the ticket from creating the models? JP-1022

Extract 1D
 * Documentation: <https://jwst-pipeline.readthedocs.io/en/latest/jwst/extract_1d/description.html>
 * Maybe add the info in the description here? JP-1049

**Comment by aliciacanipe** [comment]
Testing to see if the Jirabot is alive again

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2700?focusedCommentId=695263#comment-695263):_

Looks like the documentation has been updated significantly in the past couple years, closing unless you feel it needs to be reopened.
