### ISSUE TITLE
LRS slit wavelength calibration

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7276]
_Issue [JP-2903](https://jira.stsci.edu/browse/JP-2903) was created on JIRA by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew):_

I have been working for a while to diagnose a problem with the wavelength calibration for the LRS fixed-slit mode. These issues were reported by several users via the Helpdesk, and we have been working with users to diagnose the issue. 

It is possible (likely?) that the issue originates in our specwcs reference file rather than the pipeline code itself, which we updated in mid-July based on our slitless commissioning data. Previously we have always worked with a single specwcs calibration file, as the dispersion relation is the same for slit and slitless modes. Our calibration works well for slitless data (modulo some fine tuning), but now, when applied to fixed-slit data we see offsets up to ~0.5-0.6 µm, i.e. large. 

I have been able to identify that there appears to be a registration error of 9 pixels, i.e. the dispersion solution is being shifted by 9 pixels (even though the header keyword that defines the zero-point in our specwcs file, IMY and IMYSLTL, have *not* changed). We're somewhat limited by line measurement accuracy given teh low spectral resolution of the LRS, but it seems very close to 8.5-9 px. However, I do not understand where this issue is coming in, it's probably in how the location of the bounding box is defined, and would like your help.

An observer has independently arrived at a workaround solution that matches very closely what I found. She fitted a polynomial to the wavelength residuals (calibrated - expected), and applying this correction matches the impact of the 9-px registration offset very closely. 

I have attached some plots to illustrate the issue. 
 * VFTS822_lines.png: a plot showing our commissioning data, calibrated with our current flight specwcs reference file, with lines identified with their expected wavelength, demonstrating the offset
 * lrs_dispersion_fixes.png: shows the dispersion relation plotted from our specwcs calibration file. Solid blue is the current calibration file, orange is the observer's empirical fix, and dashed blue is the flight cal with the zero-point shifted by 9 px, which matches the orange line to within a few 10s of nm. 
 * VFTS822_wavecal_workaround.png: showing both fixes applied to the PID1259 commissioning data. 

We would really appreciate your help in diagnosing the origin of this issue so we can resolve it asap. The main dataset we are using is PID 1259, the LRS wavelength calibration commissioning activity. Obs 1 is the fixed slit observation shown in the plots, Obs 5 is the slitless observation that we used to derive the current wave cal in CRDS.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2903?focusedCommentId=606133#comment-606133):_

Here's a snippet of code from the construction of the LRS slit wcs object, in assign_wcs:

```
    with ref:
        lrsdata = np.array([d for d in ref[1].data])
        # Get the zero point from the reference data.
        # The zero_point is X, Y  (which should be COLUMN, ROW)
        # These are 1-indexed in CDP-7 (i.e., SIAF convention) so must be converted to 0-indexed
        if input_model.meta.exposure.type.lower() == 'mir_lrs-fixedslit':
            zero_point = ref[0].header['imx'] - 1, ref[0].header['imy'] - 1
        elif input_model.meta.exposure.type.lower() == 'mir_lrs-slitless':
            zero_point = ref[0].header['imxsltl'] - 1, ref[0].header['imysltl'] - 1
            # Transform to slitless subarray from full array
            zero_point = subarray2full.inverse(zero_point[0], zero_point[1])

    # In the lrsdata reference table, X_center,y_center,wavelength describe the location of the
    # centroid trace along the detector in pixels relative to nominal location.
    # x0,y0(ul) x1,y1 (ur) x2,y2(lr) x3,y3(ll) define corners of the box within which the distortion
    # and wavelength calibration was derived
    xcen = lrsdata[:, 0]
    ycen = lrsdata[:, 1]
    wavetab = lrsdata[:, 2]
    x0 = lrsdata[:, 3]
    y0 = lrsdata[:, 4]
    x1 = lrsdata[:, 5]
    y2 = lrsdata[:, 8]

    # If in fixed slit mode, define the bounding box using the corner locations provided in
    # the CDP reference file.
    if input_model.meta.exposure.type.lower() == 'mir_lrs-fixedslit':

        bb_sub = ((np.floor(x0.min() + zero_point[0]) - 0.5, np.ceil(x1.max() + zero_point[0]) + 0.5),
                  (np.floor(y2.min() + zero_point[1]) - 0.5, np.ceil(y0.max() + zero_point[1]) + 0.5))
```
So you can see that `zero_point` contains the 2 values from the IMX/IMY keywords, with 1 subtracted to put them in 0-indexed column and row units. And then the bounding_box is constructed from min/max values of all the x0,x1,y0,y2 values in the specwcs table that give the boundaries of each individual wavelength element, with the appropriate zero_point values added in, because all of the x[n], y[n] values are deltas relative to the reference/zero point. The additional +-0.5 values just put the edges of the bounding_box at the left, right, bottom, top edges of the pixels, instead of the center.

So at first glance this appears to make sense. But keep in mind that there's a lot of additional computations following this that then compute the actual wavelength values assigned to each pixel within the bounding box. So perhaps there's some other assumption further in that's leading to an apparent offset.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2903?focusedCommentId=606208#comment-606208):_

Adding a quick note from an offline email thread that this looks like it may be due to inherent variation in the LRS dispersion solution across the field of view.  As such it may be necessary to have different reference files (or different extensions in the current reference file) for slit/slitless.

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-2903?focusedCommentId=607733#comment-607733):_

Just to concur with @⁣dlaw - it seems like this is likely *not* a pipeline issue, so I'm going to re-prioritize this as low for now, unless we get more evidence to the contrary. I'll leave it open for now just to maintain awareness of the issue.

**Comment by nden** [comment]
JP ticket was resolved

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-2903?focusedCommentId=638672#comment-638672):_

We are confident that this is not a pipeline issue - so closing the ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-2903?focusedCommentId=638673#comment-638673):_

closing the ticket as we are now confident that this is not a pipeline issue.
