### ISSUE TITLE
Primary HDU information source

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#729]
For each source, whence does the Primary HDU/meta information come from? Options are:

1. fitsblender
2. first exposure for each source

Possibility is both: Option 2 for the initial creation, then option 1 in a pipeline-step situation.

**Comment by hbushouse** [comment]
Related to #603

**Comment by hbushouse** [comment]
This is all handled now by `model_blender` rules incorporated into the keyword schemas. Closing.
