### ISSUE TITLE
Pickle error when multiprocessing of JWST stage1  pipeline

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7292]
_Issue [JP-2935](https://jira.stsci.edu/browse/JP-2935) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

From user helpdesk ticket INC0182566:

> just got something wrong when using multiprocessing.Pool().map to run calwebb_detector1.Detector1Pipeline.call. Everything is ok if single-threaded. When multiprocessing is adopted, it looks good for the first several files (~10-20 rate files would be produced successfully). However, a problem related to asdf.types occurred during the reduction, and then the program exits. All the crds files have been prepared. It is weird because nothing happened to the first several files in the multiprocessing or to all the files if there is only one single process.

See attached images for partial script and partial traceback provided.

**Comment by nden** [comment]
JP ticket was resolved
