### ISSUE TITLE
Link to JWST Engineering Database in documentation is not correct.

### ISSUE THREAD

**Issue by scfleming** [spacetelescope/jwst#7298]
On this page: https://jwst-pipeline.readthedocs.io/en/latest/jwst/lib/engdb.html

Thrre is a link to "non-operational use through the MAST AUI website" to the Portal: https://mast.stsci.edu/

The correct link to engineering data access is through this AUI: https://mast.stsci.edu/portal/Mashup/Clients/jwstedb/jwstedb.html

**Comment by nden** [comment]
@stscijgbot-jp

**Comment by hbushouse** [comment]
@scfleming Is https://mast.stsci.edu/portal/Mashup/Clients/jwstedb/jwstedb.html still the appropriate link to use here?  If so, I'll go ahead and make the change.
