### ISSUE TITLE
MSA observation shows discrepancy in source_id list between APT and MSA meta file

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7305]
_Issue [JP-2978](https://jira.stsci.edu/browse/JP-2978) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

From pipeline Help Desk ticket INC0182948:

"
I am quite confused about the missing slit issues. I went through the pipeline in stage 2 and 3, I still can’t figure out where this issue arises. My initial impression was that this could be a wcs assigning issue to slits, but even in the wcs assign step it is bit unclear for me what goes on for science slits vs background slits. It looks like only the empty background slits end up getting an ID there. 

The *msa.fits files are also bit confusing: For example, in obs100 in 2565: 

In the APT there are 76 targets in all selected exposures, 79 in at least one selected exposure. 

In the jw02565100001_01_msa.fits there are 81 unique targets. So there is a slight difference. 

Objects 0, 9601, 8056 and in the fits file but not in apt. Object 16605 is there in the APT but nit in the fits file. 

Similarly jw02565200001_01_msa.fits has 99 unique targets while 97 (at least one selected exposure) in APT. 

There are 64, 64, and 21 objects (including s0000, which is more like a stack of slits) for obs100/200/300 in MAST. So there are def some missing L3 objects. 
When I reduce the data myself I also get 64 objects extracted for observation 100. 

Objects 12629 and 14552 are high priority objects in our obs200. These are in the jw02565200001_01_msa.fits file. However, there are no calibrated products for these galaxies in MAST. None of our primary targets in observing obs300 are there in MAST. 

I can’t figure out how the *msa.fits file is produced in the APT, so I guess it comes as an output from stage 1 of the pipeline? Overall, the targets in the fits file looks consistent (modulo slight difference mentioned above). If the issue is arising from this file, I wonder if the way how the slits are mapped in to they table is causing this issue. 
"

I confirmed the difference stated in the o100 APT program plan versus the msa meta file, though I haven't gotten to o200 or o300 yet.

**Comment by nden** [comment]
JP issue was resolved

**Comment by stscijgbot-jp** [comment]
_Comment by [Gary Curtis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=curtis) on [JIRA](https://jira.stsci.edu/browse/JP-2978?focusedCommentId=616971#comment-616971):_

The difference in the number of targets reported in APT and the number in the *msa.fits file is due to changes in the NIRSpec MSA model in the PRD since the observation flew. Reopening the program APT applies the updated MSA model and while the changes are subtle they move some targets into or out of slitlets at the margins.

Reviewing the PPSDB for 2565 observation 100 there are 81 nirspec_msa_source records matching reported number in  jw02565100001_01_msa.fits. There are 89 unique slitlet_ids which includes some with no sources.

APT doesn't generate the *msa.fits file which si presumably generated from the PPSDB to which APT writes the source data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2978?focusedCommentId=621952#comment-621952):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) Do you think this particular issue will be resolved by the fixes implemented for JP-2969, which fixes the handling of source_id's for shutters that are off-source (but still have a source in the slitlet)?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2978?focusedCommentId=622210#comment-622210):_

I'm still in communication with the Help Desk ticket filers - I think things have been mostly resolved at this point, but I'm still working to wrap up the discussion.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2978?focusedCommentId=624860#comment-624860):_

Assigning to [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) to update and/or close when you think all issues have been resolved (or worked around) with the original user.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2978?focusedCommentId=626048#comment-626048):_

User reports that updated msa metadata files on MAST now list the expected sources. Closing.
