### ISSUE TITLE
SourceCatalog step fails for _cal.fits images in the background subtraction

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7313]
_Issue [JP-2983](https://jira.stsci.edu/browse/JP-2983) was created on JIRA by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk):_

I have been trying to run the source catalogue step on some NIRISS imaging _cal.fits files that were taken for photometric calibration, and some others such files as well.  This has worked in the past even just a few days ago on October 21.  But running the script now produces an error message about an issue in the background subtraction step.

 

Traceback (most recent call last):
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/jwst/source_catalog/detection.py", line 74, in _background2d
    bkg = Background2D(self.data, self.box_size,
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 230, in _{_}init{_}_
    self._prepare_box_data()
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 398, in _prepare_box_data
    self._select_initial_boxes()
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 370, in _select_initial_boxes
    self._box_idx = self._get_box_indices()
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 358, in _get_box_indices
    raise ValueError('All boxes contain > '
ValueError: All boxes contain > 100000.0 (10.0 percent per box) masked pixels (or all are completely masked). Please check your data or increase "exclude_percentile" to allow more boxes to be included.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/jwst/wit/niriss/kevin/on_orbit/01063/skyflat12new/../../../run_source_catalogue_step.py", line 52, in <module>
    result = SourceCatalogStep.call(input_filename, save_results=True)
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/stpipe/step.py", line 662, in call
    return instance.run(*args)
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/stpipe/step.py", line 483, in run
    step_result = self.process(*args)
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/jwst/source_catalog/source_catalog_step.py", line 81, in process
    model.data -= bkg.background
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/astropy/utils/decorators.py", line 777, in _{_}get{_}_
    val = self.fget(obj)
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/jwst/source_catalog/detection.py", line 98, in background
    return self._background2d.background
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/astropy/utils/decorators.py", line 777, in _{_}get{_}_
    val = self.fget(obj)
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/jwst/source_catalog/detection.py", line 81, in _background2d
    bkg = Background2D(self.data, self.data.shape,

  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 230, in _{_}init{_}_
    self._prepare_box_data()
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 398, in _prepare_box_data
    self._select_initial_boxes()
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 370, in _select_initial_boxes
    self._box_idx = self._get_box_indices()
  File "/home/kvolk/anaconda3/envs/pipeline_20oct2022/lib/python3.10/site-packages/photutils/background/background_2d.py", line 358, in _get_box_indices
    raise ValueError('All boxes contain > '
ValueError: All boxes contain > 4194303.0 (100.0 percent per box) masked pixels (or all are completely masked). Please check your data or increase "exclude_percentile" to allow more boxes to be included.

 

The code block where this is happening is the following, lines 73 to 86 of detection.py <https://github.com/spacetelescope/jwst/blob/master/jwst/source_catalog/detection.py> :

 
|try:|
|bkg = Background2D(self.data, self.box_size,|
|filter_size=filter_size,|
|coverage_mask=self.coverage_mask,|
|sigma_clip=sigma_clip,|
|bkg_estimator=bkg_estimator)|
|except ValueError:|
| # use the entire unmasked array|
|bkg = Background2D(self.data, self.data.shape,|
|filter_size=filter_size,|
|coverage_mask=self.coverage_mask,|
|sigma_clip=sigma_clip,|
|bkg_estimator=bkg_estimator,|
|exclude_percentile=100.)|

 

The first exception is in the initial call to Background2D, the second one at line 81 is for the second call to Background2D where no mask is being specified, but the error message says that all the pixels in the image are masked so no background subtraction can be done.

 

The reason for wanting to run the source catalogue step on the _cal.fits image rather than the _i2d image is to get signal measurements for the photometric standard star in the un-resampled image, since there are sometimes systematic effects in the signal values of the _i2d images, and we do not want such systematic errors in the photometric calibration measurements.  I tried some different versions of the pipeline from the spring through to the fall to see if that made any difference and it does not.  I tried logging out and back in and going to the conda environment again and that also did not make any difference.  I ran the script successfully on a set of images last Friday morning, but on Friday afternoon it failed on a photometric calibration image.  When I went back to the previous image that had worked in the morning, the error occurred there as well.  The photutils version in this conda environment, which was installed on 20 October, is 1.5.0 and the pipeline version is 1.8.2.  I tried earlier versions of the pipeline back to 1.4.3.dev47+g7a719fe with photutils 1.3.0 (from 17 March 2022) but it consistently failed in the same way for these previous versions.  But as noted above, the script worked within this environment just Friday where it does not work now.  I have also included the output source catalogue file from the last successful run of the script in the directory.

 

The error message says to increase the exclude_percentile in the call to Background2D, but it is already at 100.0. 

 

This is probably not a code issue within the pipeline itself, but it is still a problem. for me.  Presumably if it happens for me it will also happen for other users sooner or later.

**Comment by larrybradley** [comment]
The source catalog step was never designed or considered to work with level-2 imaging data (`cal`), only level 3 (`i2d`).  Specifically, `source_catalog` uses the `i2d` model `wht` image to define a coverage mask.  For level-2 data, the `wht` image is all zeros, which results in the coverage mask being all `True`.  In other words, the entire image will always be masked, leaving no pixels on which to perform any calculations.  The background subtraction is the first step, and thus fails because there are no unmasked pixels.

Even if the masking logic and other changes were made in `source_catalog` to allow for level-2 images, there's a more fundamental issue.  `source_catalog` converts the input level-3 data from MJy/sr to Jy to perform photometry.  The level-3 data all have the same pixel area on the sky (which is recorded in the header).  However, the level-2 data have geometric distortions leading to each pixel having a different area on the sky.  To properly perform photometry on level-2 data, one would need to incorporate detector-dependent pixel area maps to account for the geometric distortion.

Kevin Volk claims that this worked before with level-2 `cal` data (on Oct 21), but I don't see how that's possible (unless the particular `wht` image was not all zeros) since the code hasn't changed.  With `wht` all zeros it could never work.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2983?focusedCommentId=618924#comment-618924):_

[Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) when you have time, would you mind letting me know your thoughts on the priority for this ticket? I'll update the labels accordingly.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2983?focusedCommentId=619094#comment-619094):_

[Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) for me this is high priority because it hampers my work on the photometric calibration of imaging mode.  On the other hand this does not immediately affect science observations although people doing high precision photometry may also have the need to work with the cal images not the resampled ones.  So...somewhere between medium and high priority, definitely not critical.  You can assign it either medium or high priority depending on how much weight you give to the cycle 1 calibration needs.

**Comment by stscijgbot-jp** [comment]
_Comment by [Larry Bradley](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lbradley) on [JIRA](https://jira.stsci.edu/browse/JP-2983?focusedCommentId=620948#comment-620948):_

I don't consider this a bug because the source catalog step was never designed or intended to work with level-2 imaging data.  I just added a comment on GitHub:

The source catalog step was never designed or considered to work with level-2 imaging data (cal), only level 3 (i2d). Specifically, source_catalog uses the i2d model wht image to define a coverage mask. For level-2 data, the wht image is all zeros, which results in the coverage mask being all True. In other words, the entire image will always be masked, leaving no pixels on which to perform any calculations. The background subtraction is the first step, and thus fails because there are no unmasked pixels.

Even if the masking logic and other changes were made in source_catalog to allow for level-2 images, there's a more fundamental issue. source_catalog converts the input level-3 data from MJy/sr to Jy to perform photometry. The level-3 data all have the same pixel area on the sky (which is recorded in the header). However, the level-2 data have geometric distortions leading to each pixel having a different area on the sky. To properly perform photometry on level-2 data, one would need to incorporate detector-dependent pixel area maps to account for the geometric distortion.

Kevin Volk claims that this worked before with level-2 cal data (on Oct 21), but I don't see how that's possible (unless the particular wht image was not all zeros) since the code hasn't changed. With wht all zeros it could never work.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2983?focusedCommentId=620953#comment-620953):_

Due to the comment from Larry Bradley I am closing this issue.
