### ISSUE TITLE
Transforms in NIRSPec instrument model for IFU do not round trip from detector-> to sky -> back to detector 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7316]
_Issue [JP-2985](https://jira.stsci.edu/browse/JP-2985) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

A James's request I filled this issue as a JP-ticket and assigned to to James to work on.

A Helpdesk ticket was filed because outlier detection was not working for NIRSpec data. The main reason is because mapping from detector to sky and then the inversion mapping from sky to detector produces x offsets of roughly 5.35 pixels and y offsets of 1.22 pixels.  These offsets are for G234H and F170LP.

Attached is a picture of taking valid x,y detector pixels that have been mapped to the sky then taking those values and  inverse mapping the ra,dec,lamba  to x,y

This code sniper was used to derive these values:

For slice 6, ii = 6

slice_wcs = nirspec.nrs_wcs_set_input(model, ii)
slicer2world = slice_wcs.get_transform('slicer','world')
detector2slicer = slice_wcs.get_transform('detector','slicer')
    
x, y = wcstools.grid_from_bounding_box(slice_wcs.bounding_box)   
x = x.flatten()
y = y.flatten()
cube_ra, cube_dec, cube_wave = slice_wcs(x, y)
slx, sly, sllam = slicer2world.inverse(cube_ra, cube_dec, cube_wave)
xslice,yslice = detector2slicer.inverse(slx, sly,sllam)

igood = np.where(np.isfinite(xslice))
x = x [igood]
y = y[igood]
xslice = xslice[igood]
yslice = yslice[igood]
ax.scatter(x,y, color = 'blue')
ax.scatter(xslice, yslice, color = 'red')
dx = x -xslice
dy = y -yslice])

print(dx[0:100])
print(dy[0:100])
!image-2022-10-26-12-05-47-799.png|width=902,height=446!

**Comment by nden** [comment]
Resolved by new reference files.

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=615326#comment-615326):_

So far I did the same test with NIPS and there the "roundtrip" is consistent. I am now working on a step-by-step comparison

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=622242#comment-622242):_

[Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) are you still working on this issue or do you need any assistance with testing ?

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=622245#comment-622245):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) over the past weeks I haven't had time to work on this because I was heavily involved in the NIRSpec flux calibration. Sorry for the delays. I will continue working on it after the holidays (I will be on vacation next week). The tricky part is to get comparable outputs (in terms of units, vectos, etc.) between the ST pipeline and NIPS.

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=628440#comment-628440):_

Hi all,

I have now finally managed to finalize my analysis and in conclusion it is the OTEIP to V2V3 step in the STScI pipeline where things are inconsistent. The output of the computations are in *STScI_pipeline.txt* and *NIPS.txt*

*What I did:*

I used the same observation ({_}jw01335008001_02101_00006_nrs1_cal.fits{_}) as in the original help desk ticket ([INC0182676](https://stsci.service-now.com/nav_to.do?uri=incident.do?sys_id=25d4c7f647921d10289c4f32736d4335%26sysparm_view=JWST)) to setup the WCS object for the STScI pipeline. For NIPS I used the latest model and the XTILT and YTILT from the header of this observation. Then I created a fake point in virtual slit 6 at coordinates x{*}=0, y=0.5{*} at wavelength of {*}1.71 micron{*}. From this I calculated the trip to the Detector (through each step) and to the V2V3 plane (each individual step) for both NIPS and the ST pipeline. At each step ({*}Input{*}) I also immediately calculated the back transform ({*}inverse{*}) and compared it to the input in this step ({*}Difference [%]{*}). From the two files you can see that from the Slit to v2v3 the steps are identical while from Slicer to Detector NIPS and the ST pipeline are somewhat different in their computation, but both are correct.

*Results:*

+NIPS:+ The maximum difference between the forward and backward transformation is in the Slicer to MSA_out step, which is 0.035% and -0.0076%, hence negligible.

+STScI:+ The difference between the forward and backward transformation of all steps is close to 0 but the **OTEIP to V2V3 step has a discrepancy of 0.14% and 0.41%, which are exactly the 5.2 pixel** difference when transforming it back to the detector. When comparing the output of NIPS and STScI they agree remarkable (to 5 digits) for those steps that are identical in their computation (teh detector corrdiantes are off by 1 because STScI starts at 0,0 and NIPS and 1,1) but for the OTEIP to V2V3 step I actually see a discrepancy already in the forward transformation, so I would argue that both transforms are incorrect.
 
*Since it is the OTEIP to V2V3 step this should not just affect the IFU but all spectra since this transformation is mode independent.*

If you would like to see the code or need further information, please let me know

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=628498#comment-628498):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) 

FYI - I wanted you to be aware of the results of Peter's analysis.

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=628778#comment-628778):_

Hi [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) we are currently double checking that the correct reference files were used to doe the translation from the ESA/NIPS format to the STScI format. Since all round trips using NIPS work, I assume that the NIPS model reference files are correct.

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=630214#comment-630214):_

Ok it looks like there were some discrepancies in the translation script from the ESA output to asdf. [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) provided me with new files and testing the OTEIP to V2V3 step it now looks good:


```java
oteip <=> v2v3
      Input oteip: 0.05181, -0.04357, 1.710e-06
    inverse oteip: 0.05188, -0.04374, 1.710e-06
inverse oteip old: 0.05188, -0.04374
inverse oteip new: 0.05181, -0.04357

   Difference [%]: 0.14298, 0.40855, 0.000e+00
Difference old[%]: 0.14298, 0.40855
Difference new[%]: 0.00000, -0.00000

      Output v2v3: 298.35812, -497.63118, 1.710e+00
  Output v2v3 old: 298.35812, -497.63118
  Output v2v3 new: 298.47323, -497.35183 ```
**inverse oteip, Difference, Output v2v3** are the results using the model read through the cal.fits file processed in MAST. **inverse oteip old, Difference old, inverse oteip old** are the same transforms using the asdf file from CRDS (as sanity check) and **inverse oteip new, Difference new, inverse oteip new** are the results using the newly created asdf file for teh OTE to v2v3 step.

The following are the v2v3 coordinate output using NIPS, which agree perfectly.
```java
Output v2v3: 298.47323, -497.35183 ```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=630437#comment-630437):_

Great news, [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) !  Is it safe to assume that updated ref file(s) will be submitted to CRDS soon?

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=630501#comment-630501):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) yes. It is been worked on and we should have them ready soon.

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=631701#comment-631701):_

Dear all,

after some tests by our team we concluded that the new OTE reference files are definitely an improvement regarding the outlier detection.

That said I ran a few more tests and although the coordinate roundtrip is much better there seems to be still an offset in x-direction (dispersion direction) of {*}dx={*}{*}0.304px{*}. I y-direction (cross-dispersion) the offset is negligible {*}dy=-0.0037px{*}. After some further investigation, I am pretty certain that this is happening in the **Slicer to GWA** transform. Now to find this offset is quite tricky because it requires only very small offsets in the x coordinate of the GWA plane. Testing showed that to reach an x offset of 0.3px a GWA x offset of ~0.000023 is needed (at a value of 0.11540739). NIPS: One challenging part in the direct comparison between to NIPS and the STScI pipeline is that they use different coordinate planes in this part of the model. The step **Slicer to GWA** and **GWA to SCA/DET** are in NIPS **SLICER to MSA_OUT** (virtual slits) **MSA_OUT to FPA** and **FPA to DET** hence the virtual slit step is missing in the STScI pipeline (if I am not mistaken).

Since the effect seems to come from very small changes in the coordinates I was wondering whether the translation script somewhere cut digits or something similar? That is all I have for now but I am happy to run more tests or for any inputs anyone has ([Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) , [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva))? Once the new OTE files are in place it might also be worth checking the effects on the different gratings. At the moment this test was done using and IFU G395H observation (1538:62:1), which was observed in August hence using the model version 6.4.0. A quick test qith the newer model v7.3.0 showed a similar offset ({*}~{*}{*}0.5px{*}).


In any case this additional offset does not come from the OTE part, hence we will deliver the new files.

Cheers

Peter

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=643339#comment-643339):_

[Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) Sorry for the delayed response. I ran a test today using file 

"jw01621001001_02103_00003_nrs1_rate.fits".

For this particular file the forward and backward transforms agree to 0.09 px. I think this is a good agreement. Let me know if you see something different and in this case please pass me the data. For reference here's my test.
```java
from jwst import datamodels
from jwst.assign_wcs import nirspec, AssignWcsStep

rate=datamodels.open('jw01621001001_02103_00003_nrs1_rate.fits')
out=AssignWcsStep.call(rate)
ifuwcs=nirspec.nrs_ifu_wcs(out)

for slice, w in enumerate(ifuwcs):
    print(f"slice #{slice}")
    x, y = grid_from_bounding_box(w.bounding_box)
    r, d, l = w(x, y)
    x1, y1 = w.invert(r, d, l)
    notnan = ~np.isnan(x1)
    assert_allclose(x[notnan], x1[notnan], atol=.09)
    assert_allclose(y[notnan], y1[notnan], atol=.09)```

**Comment by stscijgbot-jp** [comment]
_Comment by [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=645148#comment-645148):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) thank you very much for the test. After this I also downloaded the data I used again from MAST (since all is reprocessed) and also on my end there is no discrepancy visible a anymore. We believe that something went wrong when we reprocessed the data manually using the new OTE reference files. Will will double-check as sanity check but given that we did test with different codes and different dataset and came to the same conclusion, I would argue we can declare it a success and the issue as resolved.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=645208#comment-645208):_

[Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) Given Peter's declaration of success (above), shall we go ahead and close this?

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2985?focusedCommentId=645218#comment-645218):_

Close this one. If we find issues later we'll open another one but for now I think we can put this to rest.
