### ISSUE TITLE
Readthedocs and Pypi update for CRDS PUB server deprecation

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7322]
_Issue [JP-2986](https://jira.stsci.edu/browse/JP-2986) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

We need to remove readthedocs references to CRDS PUB now that the plan is to decommission that server. I think it's only mentioned here: <https://jwst-pipeline.readthedocs.io/en/stable/jwst/introduction.html#crds>

What about JWST Pypi documentation? Does that need to be updated? 

 

Background information about this change is here: <https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=CRDS&title=JWST+CRDS+OPS+and+PUB+Confusion>

**Comment by jdavies-st** [comment]
There's also jdocs references to OPS and PUB.

https://jwst-docs.stsci.edu/jwst-science-calibration-pipeline-overview/jwst-data-calibration-reference-files

https://jwst-docs.stsci.edu/jwst-calibration-pipeline-caveats

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2986?focusedCommentId=614336#comment-614336):_

Just a note for visibility:

JDox updates are being tracked in <https://jira.stsci.edu/browse/JDOXCM-454,> which is also linked to the CRDS epic ticket CRDS-650.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2986?focusedCommentId=615796#comment-615796):_

Also be sure to mention in the RTD page that users should completely clear/wipe their local cache when switching from PUB to OPS, so that bestref doesn't get confused (we've had at least a few reports of problems related to that).

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2986?focusedCommentId=615807#comment-615807):_

Equivalent JDox update blurb is here: <https://jwst-docs.stsci.edu/display/JDOX/.JWST+Data+Calibration+Reference+Files+v1.2#id-.JWSTDataCalibrationReferenceFilesv1.2-crdsCalibrationReferenceDataSystem>

copying for those w/o access to JDox draft:

> As of November 10, 2022 all observers should use only the standard **CRDS OPS** server for obtaining the best JWST calibration reference files.
> 
> Previously, there were 2 servers available for retrieving calibration reference data:
>  * [JWST OPS](https://jwst-crds.stsci.edu/) (or CRDS-OPS) to support the JWST Operational Pipeline; 
>  * [JWST PUB](https://jwst-crds-pub.stsci.edu/) (or CRDS-PUB) to support the latest public release of the **jwst** [calibration pipeline package](https://github.com/spacetelescope/jwst/), which may contain code updates or changes to the reference files that have not been merged into the operational pipeline yet.
> 
> The CRDS PUB server was set up in anticipation of rapid reference file updates during commissioning and Cycle 1; however, due to the trouble-free commissioning process and the smooth transition to science operations, it has been decided that the PUB server is no longer needed and it will be decommissioned on March 1, 2023. The institute will retain an internal archive of the maps and calibration reference files, so observers who wish to use any files from the CRDS PUB server in future will need to file a [JWST Pipeline help desk ](https://stsci.service-now.com/jwst)ticket to access the information. Including the name of the CRDS server along with the data reduction software versions in your publications will help ensure reproducibility for future data reductions and analysis. 
> 
> For observers who are transitioning out of using the CRDS PUB server, we recommend that you rebuild your local cache by first removing all local CRDS caches and then repointing to the CRDS OPS server ([https://jwst-crds.stsci.edu/]). This will eliminate any possible confusion in the calibration that can lead to errors or cause the pipeline to crash.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2986?focusedCommentId=615947#comment-615947):_

RTD updates included in #7342
