### ISSUE TITLE
MIRI MRS cube builed at stage 2 ignores output_type in piline version 1.8.2

### ISSUE THREAD

**Issue by jeroenbouwman** [spacetelescope/jwst#7341]
If I try to build a 3d cube from the cal.fits data product at the end of the stage 2 pipeline, and specify a different output_type other than the default 'multi', this option is ignored. The information printed to the command line when running the stage 2 pipeline still states 'multi' irrespective of specifying 'band' or 'channel'. To run the stage 2 pipeline on MIRI MRS data I used the following code:

```python
def runspec2(filename, outdir):
    crds_config = Spec2Pipeline.get_config_from_reference(filename)
    spec2 = Spec2Pipeline.from_config_section(crds_config)
    spec2.output_dir = outdir
    spec2.cube_build.skip = False
    spec2.cube_build.output_type = 'band'
    spec2.cube_build.weighting='drizzle'
    spec2.cube_build.coord_system = 'skyalign'
    spec2.save_results = True
    spec2(filename)
```

Changing the spec2.cube_build.output_type in the above code does not do anything to the cube format produced at the stage 2 level.

**Comment by hbushouse** [comment]
Tracking in Jira via https://jira.stsci.edu/browse/JP-3137

**Comment by hbushouse** [comment]
See https://jira.stsci.edu/browse/JP-3137 for explanation of why this is not being implemented and the workaround that's available.

**Comment by jdavies-st** [comment]
@hbushouse , can you echo that to this Github issue?  We don't see internal Jira issues externally, and this was an externally-raised issue.  Thanks!

**Comment by hbushouse** [comment]
> @hbushouse , can you echo that to this Github issue? We don't see internal Jira issues externally, and this was an externally-raised issue. Thanks!

Yes, there's a good reason for Jira tickets not being seen externally!  ;-)   (we wouldn't want the whole world knowing all of our secrets, now would we?)

**Comment by hbushouse** [comment]
From @drlaw1558:

Changing this would be dangerous; the spec2 pipeline requires cubes to be built in 'multi' mode as the spectra extracted from such cubes are what spec3 expects to find.  As such, spec2 cube building is really just an intermediate step to produce the 1d background spectra for spec3 master background subtraction.  If anyone needs to run cube building on individual exposures it's possible to do so on individual cal.fits files with any set of desired parameters, so I would not be in favor of changing this within the spec2 workflow given the unexpected issues it could cause downstream.

Suggest closing as 'will not do'.

**Comment by jdavies-st** [comment]
Thanks Howard!  That's helpful.
