### ISSUE TITLE
Level2: Implement background

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#735]
# Issue
Two of three cases of backgrounds need be handled:
- MSA-specific backgrounds: No association needed
- Nodding
   These are multiple exposures that have the science target(s) moving a small distance within the available slit(s). The multiple exposures will be subtracted from one another in order to remove background signal. This can be applied to several observing modes, including MIRI LRS fixed-slit, NIRSpec fixed-slit, and NIRSpec MSA (and rumor has it from Jeff Valenti that it might also be used for NIRSpec IFU observations of smallish sources). These need association information, because they involve the use of multiple exposures, and hence we need to know which exposures to group together into an association. Because all of the exposures contain the science target(s), none of them is designated as being a background exposure. They are all science exposures, containing spectra of the science target(s).
   - Spectroscopic cases only
    - All exposures are listed as science, none are labeled as background
    - As far as we know we have all the information we need to distinguish source from background, but that may change once we get real examples out of the OTB simulations.
- Chopping = Off-target backgrounds
   These are multiple exposures that have the science target in some of them and regions of blank sky in others. These are the flavor being discussed in the recent email thread. The regions of blank sky will be designated in the APT by creating virtual targets for them and taking observations of them. The APT user will also indicate which of these background targets should be used with each science target. Associations are needed to tell us which exposures (science and background) get grouped together and which of them in the resulting group are the science exposures and which are the background exposures.

**Comment by stscieisenhamer** [comment]
# Resources
- [Problem Report #87164](https://www.ess.stsci.edu/prsystem/servlet/prbrowse/pr.87164): JWST: add level-1b FITS keyword for BKGDTARG (background = T/F) for use in Asn Pool

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] Mockup Pool with
    - BACKGROUND column where non-Null flags the exposure as background
    - association candidate BACKGROUND with one observation as background
- [ ] Rules
    - [ ] Nodding _block_
    - [ ] Chopping

**Comment by stscieisenhamer** [comment]
Question: Besides DETECTOR, what else has to match between the science and background exposures? Sub-array size, groups, integrations, anything else? Or not?

**Comment by philhodge** [comment]
Filter and/or grating should match.  The subarray size (but not 
location) might need to match between science and background exposures, 
but maybe not.  I can imagine computing a single value for the 
background by averaging (or sigma-clipped average, or median) over an 
entire background subarray, and in that case the sizes wouldn't have to 
match.

**Comment by hbushouse** [comment]
In the context of background subtraction during level-2b processing, the operation is a simple image-from-image subtraction, with no action taken to do anything like extracting a subarray from the background to match the science image. So in addition to matching detector, filter, pupil, grating, band (whatever's appropriate for the optical elements of the instrument observing mode), the subarray setting should also match. Fancier methods, such as those suggested by Phil, will be allowed (eventually) at other places in the processing.

**Comment by stscieisenhamer** [comment]
## Question
There is an example, proposal 84500, for NIRSpec Fixed Slit, where, within an observation, there are EXP_TYPEs of:

- NRS_FIXEDSLIT
- NRS_TACONFIRM
- NRS_CONFIRM
- NRS_TASLIT
- NRS_TACQ
- NRS_AUTOWAVE

If an off-target background were also applied, besides NRS_FIXEDSLIT, would any of the other exposures get the background subtracted?

**Comment by hbushouse** [comment]
When the ASN file is built, exposures 2-5 should have exptype values set to something like "TACQ" (they're all different flavors of target acquisition and confirmation exposures), and exposure 6 should have exptype of "AUTOWAVE". So the only member in this whole list that will get processed at all by a level-2b pipeline is the NRS_FIXEDSLIT (it's the only exptype='science' member). None of the other exptype's get any processing done to them, and hence certainly no background subtraction.

**Comment by stscieisenhamer** [comment]
Block removed because there are now APT examples in hand of MSA with slit nodding. Can examine the sql and determine exposure layout.

**Comment by stscieisenhamer** [comment]
All sub-issues that made up this mega-issue have been resolved. Closing.
