### ISSUE TITLE
cube_build does not allow a custom suffix

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#7367]
`CubeBuildStep` ignores custom suffixes.

https://github.com/spacetelescope/jwst/blob/5a0634e30e04fd422403afda357f6e4fdf64409f/jwst/cube_build/cube_build_step.py#L78

It should allow something like:

```python
step = CubeBuildStep()
step.suffix = "test_s3d"
```

Currently this is ignored.

Probably something like:

```python
if self.suffix is None:
    self.suffix = 's3d'
```

would be sufficient.

**Comment by stscieisenhamer** [comment]
Related JIRA issue [JP-3016](https://jira.stsci.edu/browse/JP-3016)
