### ISSUE TITLE
Output files *_outlier_i2d.fits not saved to the specified output_dir

### ISSUE THREAD

**Issue by karllark** [spacetelescope/jwst#7419]
When running the pipeline with the call method with a specified output directory (using `output_dir` in call) all the files *except* those ending with `outlier_i2d.fits` are correct saved into the specified output directory.  The `outlier_i2d.fits` files are saved in the current direction. 

This is a minor bug, but somewhat annoying when running many exposures with specific subdirs for their output.

**Comment by stscieisenhamer** [comment]
What versions of JWST and STPIPE are in use? Can you post the results of command `pip freeze`?

**Comment by karllark** [comment]
jwst==1.8.5
stpipe=0.4.2

Feel free to tell me to upgrade to solve this problem.

**Comment by stscieisenhamer** [comment]
I do not see any PR's that directly relate to this, and the current master, depending on data, may require CRDS references that are not available yet, so upgrading will most likely not help.

**Comment by karllark** [comment]
Ok.  For the record, I got the latest released version of stpipe (0.4.5) and see no change in the behavior.

**Comment by stscieisenhamer** [comment]
Opened issue JP-3046.

**Comment by braingram** [comment]
Fixed in https://github.com/spacetelescope/jwst/pull/8464 @karllark Please re-open this issue if you're still having the problem.
