### ISSUE TITLE
Extraction of 1-D spectroscopic data (x1d) 

### ISSUE THREAD

**Issue by Aseman7** [spacetelescope/jwst#7429]
Hello, I would like to extract 1-D spectroscopic data (x1d) from NIRISS data. 

First, using the following command,  I extracted calints and x1dints files.
> $strun` calwebb_spec2 jw00017001001_01101_00001_nrca1_rateints.fits

But when I run this one:
> $strun calwebb_spec2 jw00017001001_01101_00001_nrca1_rate.fits
I did not get x1d and cal files. I don't know where is the problem.

Also, I tried by extract_1d class as:
> $strun extract_1d jw00017001001_01101_00001_nrca1_cal.fits
and I got extract1dstep.fits file not x1d file.

Any help for extracting x1d file would be appreciated. Thanks.

**Comment by stscieisenhamer** [comment]
Greetings! Sorry to hear that you are having issues with extracting spectra. A few questions...

What program ID are this data from? Usually, the program id is the first five digits of the filename. However, for the file you provide above, that is "00017" which is not a valid program.

What is the type of data you are trying to extract? It is stated that this is NIRISS data. What is the observing mode, such as SOSS?

It is implied that running calwebb_spec2 on the "rateints" file was successful and produced the expected "calints" and "x1dints" files.  However, running on the "rate" file failed. How did it fail? If there was an exception, what was that exception?

Presuming that the data is SOSS, which is a time series type observation, the only valid data is in the "rateints". Using the non-time series data, "rate", is not expected to work.

Please provide any other information you can about the data and how you are processing it.
