### ISSUE TITLE
Possible bug in fits_generator create_dms_data

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#743]
I think there's a bug in the setting of the new NAXIS1, NAXIS2 values for NIRISS and GUIDER images after they've been swapped/flipped to their DMS orientations. Lines such as:

https://github.com/STScI-JWST/jwst/blob/70c75452597c33cbe50f84518c32a47faf440dc6/jwst/fits_generator/create_dms_data.py#L480-L481

https://github.com/STScI-JWST/jwst/blob/70c75452597c33cbe50f84518c32a47faf440dc6/jwst/fits_generator/create_dms_data.py#L500-L501

https://github.com/STScI-JWST/jwst/blob/70c75452597c33cbe50f84518c32a47faf440dc6/jwst/fits_generator/create_dms_data.py#L521-L522

set the ncols and nrows to the original NAXIS1 and NAXIS2 values, respectively. But all 3 of these image types get their x/y axes swapped, which means those ncols and nrows assignments should also be swapped. This swapping is done in parts of the code for other detector that get their axes swapped, such as here

https://github.com/STScI-JWST/jwst/blob/70c75452597c33cbe50f84518c32a47faf440dc6/jwst/fits_generator/create_dms_data.py#L369

for the NRS1 detector. But it does not happen for NIRISS, GUIDER1, or GUIDER2. I suspect that this error has simply been covered up by the fact that the FITS i/o routines reset the NAXIS1 and NAXIS2 values to the actual image dimensions when the images are saved to a file.

On a related note, where in the fits_generator functions do the SUBSTRTn and SUBSIZEn keyword values get set? Those would not be cleaned up by the FITS i/o routines and hence we need to make sure they are being set correctly.

**Comment by stscirij** [comment]
I'm looking at this now, I'll clean up the NIRISS and GUIDER subarray parameters.  As for the SUBSTRTn and SUBSIZEn keywords, they get set in the templates from the COLSTART, COLSTOP, ROWSTART, ROWSTOP,FASTAXIS,SLOWAXIS keywords that are set for all detectors around lines 527-535.

**Comment by melanieclarke** [comment]
Closing - the fits_generator is no longer used.
