### ISSUE TITLE
Flux density values in Jansky units for a spectrum

### ISSUE THREAD

**Issue by Aseman7** [spacetelescope/jwst#7437]
Please compare these two extracted spectra for a star using NIRSpec and NIRISS data. The values on the vertical axis (flux density) for two plots vary greatly. Probably one of them is incorrect; which one of them is reasonable?

![image](https://user-images.githubusercontent.com/66720969/213716046-6c87ccd2-68e7-411b-86eb-ef072b9a20cc.png)

**Comment by hbushouse** [comment]
Can you supply more details as to which instrument modes these spectra came from? Is "NIRISS" the SOSS mode? And for NIRSpec I assume it's either fixed-slit or MOS? Also, when were the data last processed in the calibration pipeline? Some of the NIRSpec calibration reference files that contain flux calibration data were updated to in-flight values back in mid-December of 2022. Previous to that, the flux calibration values were all set to 1, and hence you weren't actually getting flux units out the back end.

**Comment by Aseman7** [comment]
Thanks for your reply. It was solved.
