### ISSUE TITLE
skymatch: "match" should minimize difference in overlaps, not in whole images

### ISSUE THREAD

**Issue by thomaswilliamsastro** [spacetelescope/jwst#7472]
It appears that in the skymatch "match" step, the minimization occurs between the entire images, not the overlap images. At least, I think that's what happens in the 
`A, W = _overlap_matrix(images, apply_sky=apply_sky)`
step in `skymatch.py`. This is fine for mostly blank images where you can calculate a "true" background, but for images heavily full of emission that isn't symmetric about the overlap points, this can cause really noticeable steps between tiles in the final mosaic. We've found for the PHANGS work that actually turning off the skymatch can help, but still isn't ideal. We have found that mosaicking each field separately and then stitching together using e.g. Montage has produced better results that the pipeline, but obviously this isn't a great solution.

Likely, what should happen is that calc_sky should be called for each part of the tile that overlaps, and then those values should be minimized. I don't think this would be a huge amount of rewriting, just pulling out the overlap regions rather than relying on the statistics for the whole tile. I think this is the intent, reading the docs: "For each pair of images, the sky mismatch is computed only in the regions in which the two images overlap on the sky." but this does not appear to be the case looking into the code

**Comment by hbushouse** [comment]
See https://jira.stsci.edu/browse/JP-3118

**Comment by thomaswilliamsastro** [comment]
To report back on this, I've tried getting MIRI dithers in a group to a common level and then skymatch either tying them together or all separately, neither works. PR #7473 is the only solution working at the moment

**Comment by mcara** [comment]
> It appears that in the skymatch "match" step, the minimization occurs between the entire images, not the overlap images. At least, I think that's what happens in the `A, W = _overlap_matrix(images, apply_sky=apply_sky)` step in `skymatch.py`.
................
I think this is the intent, reading the docs: "For each pair of images, the sky mismatch is computed only in the regions in which the two images overlap on the sky." but this does not appear to be the case looking into the code

That is just not true. If we follow the code starting with:
https://github.com/spacetelescope/jwst/blob/6376c03ff1370bf87787a22e94a958e10c9b2fc0/jwst/skymatch/skymatch.py#L498-L500

Here `images` is not a list of simple `numpy.ndarray` but rather of `SkyImage` instances. Then the code in the `_overlap_matrix()` calls `SkyImage.calc_sky` members:
https://github.com/spacetelescope/jwst/blob/6376c03ff1370bf87787a22e94a958e10c9b2fc0/jwst/skymatch/skymatch.py#L479-L485

It is clearly visible that the `overlap` argument is set for both `i` and `j` images and so the sky is computed in the regions in which images do overlap. This is done using a mask computed by filling polygons formed by the intersection _on the sky_ of the bounding polygons for each image:

https://github.com/spacetelescope/jwst/blob/6376c03ff1370bf87787a22e94a958e10c9b2fc0/jwst/skymatch/skyimage.py#L617-L638

**Comment by thomaswilliamsastro** [comment]
You're right, I hadn't properly dug into the code. I think the issue we're having is that it's assumed the background in the overlap region somehow maps to the overall background. If you use 'global+match', initially there's a sky value of 0, it will then calculate some value to minimize between overlaps in the images and use that as the sky value, which is maybe not the thing to do if you have an image where the overlap is source but there is some background present in the full tile. I'm also not sure if the global subtraction then uses the differences between the sky values (the delta it reports) or the minimum it calculates, but if it's the former that could also cause some issues for these diffuse emission mosaics

I did try changing it so the sky value would be initialised as the value calculated on the input image but also couldn't get satisfactory tile matching there either. Getting the images to a common level before skymatching (I matched relative differences between overlapping pixels) and then just using 'global' works, but obviously that's the whole purpose of this step so it would be good to not have to do that by hand

**Comment by mcara** [comment]
> I think the issue we're having is that it's assumed the background in the overlap region somehow maps to the overall background.

Nothing like that is assumed. For 'match' part, it is assumed that the total flux in the two images in the region where they overlap _should_ be equal. The algorithm tries to minimize the differences in these overlaps between all images.

> it will then calculate some value to minimize between overlaps in the images **_and use that as the sky value_**, which is maybe not the thing to do

That is not how the algorithm works.

Please take a look at https://github.com/spacetelescope/jwst/pull/7531 I added unit tests that verify that results of sky matching are as expected. It tests all methods including 'global+match'.

I do not believe there is an issue with the code.
