### ISSUE TITLE
jwst_pipeline/zeus issue with Python 3.10

### ISSUE THREAD

**Issue by davidpfriedlander** [spacetelescope/jwst#7482]
Hello,

There is a problem with the zeus package (part of the jwst_pipeline, I believe) that only appears in python 3.10 or newer.

What we see is:
>>> import zeus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abcde/opt/anaconda3/envs/jwst-pipeline/lib/python3.10/site-packages/zeus.py", line 2, in <module>
    from collections import Iterable as IterableType
ImportError: cannot import name 'Iterable' from 'collections' (/Users/abcde/opt/anaconda3/envs/jwst-pipeline/lib/python3.10/collections/__init__.py)

Googling this error, I found:
https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

which says this was deprecated starting in python 3.10. And that above URL points out that the (new) correct way to fix this is to change
    from collections import Iterable as IterableType
to
    from collections.abc import Iterable as IterableType
I have made this change to line 2 of      
    /Users/abcde/opt/anaconda3/envs/jwst-pipeline/lib/python3.10/site-packages/zeus.py
and then the "import zeus" command worked without error. (In this case, I was trying to help someone do
    >>> import transitspectroscopy
which brought out the zeus error.)

Anyhow, I think this zeus.py file will need some conditional code to determine the python version, so as to import from either collections or collections.abc.

Thank you,
David Friedlander
NASA Goddard Space Flight Center.

**Comment by tapastro** [comment]
Hi David,

zeus is not a part of our distribution - you may need to find out where you got the code from and post this to the zeus repository, if it exists.

**Comment by davidpfriedlander** [comment]
OK, that is useful, thank you. I will check with the person I was helping to get more information about how she installed it.
