### ISSUE TITLE
Updated NIRCam WFSS photom algorithm to account for varying dispersion 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7659]
_Issue [JP-3238](https://jira.stsci.edu/browse/JP-3238) was created on JIRA by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe):_

NIRCam is working on addressing an issue with the interaction of the flight WFSS/TSGRISM flux cal files with the current design of the photom step, which is causing the flux calibration to be off by a factor of 10. The near-term fix will be to divide the PHOTMJSR values by 10. However, this triggered a discussion that dividing by 10 is not quite right – the dispersion varies across the detector, and is also wavelength dependent, so we can't just create a 2048x2048 array of dispersions and extract 2D boxes. Instead, the pipeline needs to know the wavelength at each pixel in order to find the dispersion. This is something that needs to be done individually for each source in the FOV. Forcing a pixel size/sr/bin size to the sensitivity will always be an approximation and introduces an error in the flux calibration. Because it's a small variation, it will probably not be noticed until the contamination and background subtraction are resolved, but we should begin investigating this issue to improve the quality of WFSS data products. 

The photom step already creates the 2d array of wavelength values for each source. A 2d array of dispersion values would have to be constructed on the fly for each source and the pipeline would have to know the function for calculating dispersion.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=644280#comment-644280):_

A note for tracking: this issue was raised after investigation of Help Desk ticket [INC0189809.](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=e33c1d4e97bea55023a2fe971153aff7%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by stscijgbot-jp** [comment]
_Comment by [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=645085#comment-645085):_

I do not mean to tell anyone how to implement this, but if the pipeline has a 2D image with the center wavelength of each pixels, the dispersion can be computed from that image down to a descent level of accuracy.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=645089#comment-645089):_

Reassigning to [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) and [Greg Sloan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=gcsloan) for CalWG input.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=645270#comment-645270):_

Adding [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) and [André Martel](https://jira.stsci.edu/secure/ViewProfile.jspa?name=martel) for NIRISS – please examine whether or not this issue has NIRISS impacts, and edit the 'criticality' fields accordingly if you could please.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=645315#comment-645315):_

I am not able to understand why there is a factor of 10 problem in the NIRCam WFSS photometry calibration from the description in the ticket, so it is difficult to comment on whether there is some NIRISS equivalent.  In the general sense for the SOSS mode we have a wavelength reference file that gives wavelengths pixel by pixel across the field and this allows for the (small) changes in dispersion over the array.  In that mode the assumption is that all sources are at the same position so we do not need to worry about changes as a function of where the source is located in the direct images.

For the WFSS mode the dispersion does not appear to be a strong function of wavelength or position on the detector, although some small variations are measured.  This does not appear to be an urgent issue, but I can take it to the WFSS sub-group within NIRISS for comments.

**Comment by stscijgbot-jp** [comment]
_Comment by [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=645326#comment-645326):_

The source of the factor of 10 in the spectroscopic calibration comes from the sensitivity being delivered as Mjy/sr/lamba while the pipeline assumes that it is in units of Mjy/sr/"pixel"
 where "pixel" is the wavelength range of a dispersed spectrum across a pixel. 
If NIRISS has assumed all along that field dependence and variation is not an issue and has calibrated things assuming that nothing varies on the detector then it should not be an issue (at least to within the error that this assumption introduces).

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=664464#comment-664464):_

This is among the CalWG tasks prioritized in the [quarterly development priorities meeting with WMO 2023-09-06](https://outerspace.stsci.edu/display/JWSTPWG/2023-09-06+Meeting+Notes%3A+Development+Priorities)

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) could you let us know please who from SCSB has been assigned to this, so that they can start working with [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal)  [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk)  [André Martel](https://jira.stsci.edu/secure/ViewProfile.jspa?name=martel)  and others for the next steps in proceeding with this effort?

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=678068#comment-678068):_

Hi foks, I'm starting to work on this.  Which modes need to be corrected?
 * NRC_WFSS
 * NRC_GRISM
 * NRC_TSGRISM
 * NIS_WFSS
 * NIS_SOSS
 * MIR_LRS_SLITLESS

Any others?

**Comment by stscijgbot-jp** [comment]
_Comment by [Greg Sloan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=gcsloan) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=678077#comment-678077):_

I don't believe LRS slitless has any issues here.  Or it might be better to say that if it does, then we've corrected for it with our current photometric calibration.  Any changes to how the pipeline handles the photometric calibration from pixel space to extracted spectra would require a fresh delivery of reference files for photometric calibration.

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=678752#comment-678752):_

Thanks [Greg Sloan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=gcsloan)  and [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) .  For NIRCAM, I'll only look at NRC_WFSS and NRC_TSGRISM, as NRC_GRISM data only runs through the detector1 pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=678768#comment-678768):_

hi [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) can you point us please to the source for the modes you mention? (eg NRC_WFSS vs NRC_GRISM, and others)

I'd like to compare the place where you found those modes, to the one used by JSSE ([https://innerspace.stsci.edu/display/JSSE/Templates+-+modes])

Thanks in advance!

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=678775#comment-678775):_

Hi [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) , I used this table:

 

<https://jwst-pipeline.readthedocs.io/en/latest/jwst/pipeline/main.html#pipelines-vs-exposure-type>

 

Also, I tried running the spec2 pipeline on a NRC_GRISM rate file and it failed with a message about being unable to find a WAVELENGTHRANGE reference file, so I suspect that there aren't entries in the crds rmaps for NRC_GRISM data

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=678777#comment-678777):_

[Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) Originally "NRC_GRISM" was used for any NIRCam mode that had a grism in the beam, including the WFSS science mode. Meanwhile NIRISS WFSS mode was using EXP_TYPE='NIS_WFSS'. So many years ago we had SDP modify the "NRC_GRISM" value that it gets from front-end systems and change it to "NRC_WFSS" when storing EXP_TYPE in the FITS headers for NIRCam WFSS exposures - for consistency between NIRCam and NIRISS WFSS modes. But the old "NRC_GRISM" value is still used for exposures taken in the NIRCam engineering mode, because there were some other parts of the ground system (e.g. commissioning tools) that depended on that original value. So that's why we have a mixture of values.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=678785#comment-678785):_

thanks [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij)  and [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) 

And yes, the reason I asked was exactly for what [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)  describes, ie: on the front-end PPS side the template is set to "NRC_GRISM" for any non-TSO grism NIRCam data, including both science and engineering data:
 * science data for wide field slitless (where the FITS header keyword EXP_TYPE ends up getting a value of "NRC_WFSS")
 * engineering mode (where the FITS header keyword retains the value of "NRC_GRISM")

So I just wanted to make sure that the list of "modes"  that [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) posted earlier were not the PPS observing modes (where "NRC_GRISM" is used for both science and engineering) but were in fact the values populated in the FITS header EXP_TYPE keyword.

Ie, yes, if the list from [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) refers to the FITS header EXP_TYPE keyword, then I concur that we only need to worry about science modes here for NIRCam and not engineering modes, so the relevant EXP_TYPE vales are then "NRC_WFSS" and "NRC_TSGRISM"

Thanks for confirming!

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=680419#comment-680419):_

Fixed by #8207

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=696379#comment-696379):_

[Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) Reminder to please take a look at this and confirm that it's now fixed the original issue as expected.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=696432#comment-696432):_

I've checked this and the results look good to me. I've sent my results and a note to [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal), asking if he wants to do any further checking

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3238?focusedCommentId=696437#comment-696437):_

Great, thanks [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) .  Closing for now then, but please feel free to reopen if [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal) comes back with any issues.

**Comment by stscijirahub** [comment]
_This issue is tracked on JIRA as [JP-3238](https://jira.stsci.edu/browse/JP-3238)._
