### ISSUE TITLE
Add OIFITS compliant schema to stdatamodels

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7670]
_Issue [JP-3283](https://jira.stsci.edu/browse/JP-3283) was created on JIRA by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham):_

Add an OIFITS compliant schema and corresponding model to stdatamodels to be used for AMI updates to the JWST pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3283?focusedCommentId=650493#comment-650493):_

PR opened, approved and merged:
spacetelescope/stdatamodels#174

**Comment by braingram** [comment]
Fixed in https://github.com/spacetelescope/stdatamodels/pull/174
