### ISSUE TITLE
For IFU data, how to handle when  Photom value = NaN but DQ flag is not set to DO_NOT_USE

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7708]
_Issue [JP-3301](https://jira.stsci.edu/browse/JP-3301) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

Recent MIRI MRS photom reference files have a science value of NaN but the DQ flag in the reference file was not set to DO_NOT_USE. The reference files are being fixed. But this error highlighted what happens if  the photom value is a nan, but the associated DQ flag is not set to DO_NOT_USE.  As a safety guard we could  update the photom step to make sure pixels in the reference file with NaN values also set the DQ flag to DO_NOT_USE (currently only NON_SCIENCE is set). This also  helps the outlier detection algorithm when the association contains multiple bands from the same IFU detector (MIRI case)

Update Photom step for MIRI MRS and Nirspec IFU when reference file has NON_SCIENCE dqflag set. This would require 2 changes in the photom step but would be consistent with the how the pipeline set DO_NOT_USE  in the dq plane. 

a. The current code in photom for MIRI MRS 
 # Reset NaN's in conversion array to 1
            where_nan = np.isnan(ftab.data)
            ftab.data[where_nan] = 1.0

            # Make sure all NaN's and zeros have DQ flags set
            ftab.dq[where_nan] = np.bitwise_or(ftab.dq[where_nan],
                                               dqflags.pixel['NON_SCIENCE'])
 * 
 ** 
 *** ONE SUGGESTION IS TO ADD DO_NOT_USE TO ftab.dq

b. The current code for Photom NIRSPEC IFU  (only looks at NON_SCIENCE flag of photom reference file when setting photom value to 1.)
 # Reset NON_SCIENCE pixels to 1 in sens2d array and flag
                # them in the science data DQ array
                where_dq = np.bitwise_and(dqmap, dqflags.pixel['NON_SCIENCE'])
                sens2d[where_dq > 0] = 1.
                self.input.dq = np.bitwise_or(self.input.dq, dqmap)
 ** 
 *** SUGGESTED change is when this happens to ALSO SET input.dq to DO_NOT_USE

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3301?focusedCommentId=678767#comment-678767):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) Since the MRS photom reference files have been updated should I close this ticket ? Or should I make the suggested changes as a double check to prevent problems in the future ?

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3301?focusedCommentId=678776#comment-678776):_

I think it should be unnecessary to do anything further; MRS photom files should now always have DO_NOT_USE set whenever the SCI value is non-finite.  More importantly though, the downstream code is robust against unflagged NaNs in the SCI array.  Frequently I'll just NaN-out some sci values that I want to mask for testing, and cube building ignores them cleanly.  So, I think we can close as unnecessary.

**Comment by jemorrison** [comment]
Reference files have been update that does not require a change to code. Closing issue

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3301?focusedCommentId=678791#comment-678791):_

Updates to reference file resulting in changes to code not being needed.
