### ISSUE TITLE
Streamline cube building code and ref files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7734]
_Issue [JP-3047](https://jira.stsci.edu/browse/JP-3047) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

Extensive use of the IFU drizzle cube building algorithm in the last year has suggested a few key areas of improvement that can be made to the code and reference files for consistency and long-term maintainability.

1)ON HOLD until NIRSpec team can  evaluate if EMSM produces better results than DRIZZLE.
Remove MSM and EMSM weighting schemes.  These schemes see no use given the extensive work that has gone into development and characterization of the 3d drizzle algorithm lately.  3d drizzle is better motivated, better performing, and uses far fewer free parameters.  Removing these old schemes would significantly streamline the cube building code and cubepar reference files.

2) COMPLETE by PR 7559.

 Homogenize the use of the wavemin/wavemax parameters defining output cubes between MIRI and NIRSpec.  At present MIRI uses cubepar to define the default wavelength range with which to build cubes for a given band, while NIRSpec determines it dynamically from the data.  Given the barycentric wavelength correction (which can differ between observations) and other factors, this means that the NIRSpec cubes are not always consistent with each other which can make comparisons between cubes hard.  I suggest NIRSpec similarly use cubepar to define default wavelength ranges.

Tagging [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) [Nora Luetzgendorf](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nluetzgendorf) for input and feedback.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=624396#comment-624396):_

I think this will greatly improve the maintenance of cube build. I think it will also help resolve bug tickets and help desk questions sooner.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=636844#comment-636844):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) [Peter Zeidler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zeidler) 

Are we ready to tackle at least part 2 of this ticket ? 

Also what is happening with the difference between point source and extended source NIRSpec data and the fact that drizzle needs the data in surface brightness. Did a separate ticket get filed for this. Is it a reference file change on NIRSpec's side or a Cube build change for NIRSpec data ?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=636851#comment-636851):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) see <https://jira.stsci.edu/browse/JP-3163> for the units issue - it requires a code change in the photom and extract_1d steps.

As for the output wavelength determination, would you need a new reference file before tackling the code? Tagging [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda), who can do that work.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=636942#comment-636942):_

The new reference file is needed first. Once we have that I will just remove the part of the code in ifu_cube.py concerning if self.instrument = 'NIRSPEC' and treat all data like the lines for MIRI
final_lambda_min = self.wavemin (determined from reference file)
final_lambda_max = self.wavemax (determined from reference file)

 # for MIRI wavelength range read in from cube pars reference file
        if self.instrument == 'MIRI':
            final_lambda_min = self.wavemin
            final_lambda_max = self.wavemax

# for NIRSPec wavelength range determined from the data
        if self.instrument == 'NIRSPEC':
            final_lambda_min = min(lambda_min)
            final_lambda_max = max(lambda_max)
            if self.wavemin_user:
                final_lambda_min = self.wavemin

            if self.wavemax_user:
                final_lambda_max = self.wavemax

**Comment by stscijgbot-jp** [comment]
_Comment by [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=637016#comment-637016):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jmorrison)  The current operational wavelength range reference file is located in CRDS at

<https://jwst-crds.stsci.edu/browse/jwst_nirspec_wavelengthrange_0006.asdf>

I hope this file works for what you need to move forward. Please let me know if that is not the case. Thank you.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=637027#comment-637027):_

[Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) I think this will work. Let me fill in some background information on how cube_build works just to confirm.

The default location to put this information is in the cubepars reference file. It is fine if NIRSPEC has an existing reference file they store this information. Let make sure this logic works. The reason cube_build was designed to hold this information is that if the weight method in cube_build is modified shepherd method (msm) - the table in cube_pars related to msm is read in. This table holds the parameters of the weighting based on a given wavelength table. Likewise for 'emsm'. For the drizzle method only the wavelength region is needed. If you look at the  MIRI cubepars reference file you will see the layout.
If you want to use the wavelength table you pointed at when the drizzle method is use we can do that. I can see a benefit to NIRSpec that you would not want to update a table 2 places if you ever wanted to change it. BUT is the user uses the weight method 'msm' or 'emsm' then the code WILL USE THE WAVELENGTH range provide in the nirspec cubepars table for those weighting methods. I just want to avoid confusing and make sure this plan works for you.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=637066#comment-637066):_

Let me add more detail. I had to remind myself how the wavelength tables are used. I think this is simpler for NIRSpec.

If we only have one MIRI band or one NIRSpec grating/filter combination then the output cube will have a linear wavelength region and the start and stop wavelength WILL now for NIRSpec be set by the WAVEMIN and WAVEMAX given in the first table (CUBEPAR) (instead of being determined from the data). This change will be a software change. 

The issue is if we combine data together that does not have the same spectral size in the CUBEPARS table.

I think (please correct me if I am wrong) that for NIRSpec we do not combine different gratings but we can have  more than 1 filter. If the filters in the CUBEPAR file have different spectral step values then we would have a non-linear wavelength plane.  This only occurs for
G235M and G234H.

For example, 
G235M & F170 has a spectral size of 1.06E-03
G235M & F290 has a spectral size of  1.79E-03

HOWEVER, I think we made cube build rather generic, so  if association has  multiple grating and filters it will make and IFU cube from the data. But I believe this only makes sense if the grating are either PRISM, from MED resolution or from HIGH resolution. Hence the different tables for MSM and EMSM. 

So for NIRSPEC we just need a wavelength band for drizzle when data is being combined and the spectral size is not the same in CUBEPAR extension. 
MIRI just has 1 wavelength band in the case. 
I don't know if NIRSPEC will want to do as it has done for the other  weighting and have a Wavelength band for MEDIUM and HIGH. The other weighting schemes had   values that could  vary across the wavelength but that is not the case for the drizzle method. 

If this is not clear - we can set up a Webex to go over it. 



 I need to run a few tests because as the code is written now I am assuming the NIRSPec associations NEVER have data from multiple filters  ? The code never gets to seems to look for the non-linear wavelength table is weighting = drizzle. I will continue to research.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=637949#comment-637949):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) 

For NIRSpec I am going to set the min and max wavelength be to that given in the cubepars reference file. That will work for drizzle case in about all the cases except if the NIRSpec IFU data contains data from more than 1 grating/filter combination that has a different spectral size in the first table in the cube pars reference file - I attached a screen shot of the table to this ticket. 

The information I need from the NIRSPEC team or maybe Jonathan - is how are associations made for NIRSPEC IFU data. If they are made of only 1 grating/filter combination then the drizzle method will work fine.  If they contain multiple grating - say G140M and G235M then the drizzle code will have a problem because currently there is not wavelength array in the cubepars reference file BUT I can use the wavelength table Leonardo pointed me to (in this ticket). I just want to know if we will ever have that case before I write the code to read in this file and use it.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=638069#comment-638069):_

Currently the rules create Level 3 associations on a per-grating basis. Hence the drizzle method should be good.

However, there is nothing particularly written-in-stone about that. If there is a code where the multi-grating case cannot be supported, that will need be documented, though I am not sure how. Some commentary to the rule could be added.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=638950#comment-638950):_

[Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) After thinking about it I do not think the wavelength reference file you pointed me at is what we want because we want a different wavelength bin for MEDIUM and HIGH resolution data.  Instead if you can make a new NIRSPEC cubepars reference file with 3 extensions
MULTICHAN_PRISM_DRIZZLE, MULTICHAN_MED_DRIZZLE, MULTICHAN_HIGH_DRIZZLE

and each extension contains the wavelength array to use for the associated gratings when filters or gratings are combined.This will be the most flexible and we will not have to change code if people run cube build with different combining gratings or filters.

Looking at how the cubepars reference file is set up - just copy the wavelength array from say the MSM

into these extensions. 



The PRISM one is not necessary but for consistency sake add it,  The MEDIUM one should cover the wavelengths and **spectral step** appropriate for:
G140M, G235M and G395M. 
The high resolution the wavelength and **spectral step** for G140H, G235H and G395H.

If you have any question let me know.

**Comment by stscijgbot-jp** [comment]
_Comment by [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=639084#comment-639084):_

Hi [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jmorrison) I created a new cubepars reference file for NIRSpec based on the one that is active now. I added four new extensions that look like this:

> 10 CUBEPAR_DRIZZLE 1 BinTableHDU 16 16R x 3C [5A, 6A, D]
> 
> 11 MULTICHAN_PRISM_DRIZZLE 1 BinTableHDU 12 367R x 1C [D] 
> 
>  12 MULTICHAN_MED_DRIZZLE 1 BinTableHDU 12 4036R x 1C [D] 
> 
>  13 MULTICHAN_HIGH_DRIZZLE 1 BinTableHDU 12 10413R x 1C [D]

Extension 10 contains the disperser/filter/spectral step data for all possible combinations. Extensions 11, 12, and 13 have one column each with the wavelength array taken from the MSM extensions.

I hope that I understood your request. Let me know if I missed or misunderstood anything. I am attaching the file in this ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=639145#comment-639145):_

Send me the cubepars file so I can look it over. I do not think you need extension 10. So let me see what is in it.  That information should be in extension 1. The drizzle routine does not have wavelength dependent parameters like the other weighting schemes. It just need the wavelength plane that you have in extensions 11-13

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=639156#comment-639156):_

[Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) Ok you can remove extension 10 - that inforamtion is in the first extension. Sorry if I confused you. I only need the extension 11, 12, 13.

Thanks for making that reference file so quickly.

When you have a new file can you also attach it to this ticket and I will test cube_build with it.

**Comment by stscijgbot-jp** [comment]
_Comment by [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=639163#comment-639163):_

This is done. I removed extension 10. The new file is attached and has the following name:

jwst_nirspec_cubepar_0005_drizzle_02.fits

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=639778#comment-639778):_

[Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) the new file looks good. I had to update the data model for the cubepar reference file in stdatamodels. Currently there is slight problem getting the jwst pipeline and a new version stdatamodels to work together, but this is not your problem. When we this resolved I can full test the new reference file you gave and then we can get it into CRDS.  I will let you know when this happens

**Comment by stscijgbot-jp** [comment]
_Comment by [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=639799#comment-639799):_

Thank you for this information, Jane.

**Comment by stscijgbot-jp** [comment]
_Comment by [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=642014#comment-642014):_

Excellent! I will deliver the new file next week.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=642629#comment-642629):_

Item 2 fixed by #7559

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=654576#comment-654576):_

[Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) 

I would like to clean up this ticket - it has been on my board for months. 

Do we want to remove the EMSM was an option or keep it ? One thing I would like to clean up is making 'single type cubes'. These were 

used to support the old outlier detection routine and the mrs_imatch step (we are not doing this). If 'single' was selected then a series of 'single' IFU cubes are made. Each 'single' cube is made by mapping a single exposure to the footprint that would hold all the cubes. If we remove this then mrs_imatch step will not work (but we are not using it).

**Comment by stscijgbot-jp** [comment]
_Comment by [Leonardo Ubeda](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lubeda) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=654655#comment-654655):_

I agree with David. Let us keep EMSM as an option. Thank you.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3047?focusedCommentId=672725#comment-672725):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) This ticket has been open for a while, and I think at this point we've completed the parts of it that we're going to do, and declared that other parts will not be done.  Can we close this, or am I misremembering something that you're still working on?

**Comment by jemorrison** [comment]
@drlaw1558  Yes we can close this ticket. We completed updating the reference file work and how cube build uses the reference files. From testing and user reports we should keep the emsm weighting option. Since we are still looking at possible further improvements to outlier rejection we should keep making the "single" type ifucube because they might be useful in the future.
