### ISSUE TITLE
Create C framework in STCAL ramp fitting

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7735]
_Issue [JP-3121](https://jira.stsci.edu/browse/JP-3121) was created on JIRA by [Kenneth MacDonald](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmacdonald):_

Create C framework in STCAL to prepare for refactoring part of ramp fitting in C.

**Comment by hbushouse** [comment]
Fixed by https://github.com/spacetelescope/jwst/pull/8355

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3121?focusedCommentId=700366#comment-700366):_

Fixed by #8355

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3121?focusedCommentId=700378#comment-700378):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) So can we now pass an argument to the jwst ramp_fitting code to tell it to use the C version?  What's the relevant flag?

**Comment by stscijgbot-jp** [comment]
_Comment by [Kenneth MacDonald](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmacdonald) on [JIRA](https://jira.stsci.edu/browse/JP-3121?focusedCommentId=700382#comment-700382):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) there are two ways you can use the C extension.  If you feel comfortable changing the code you can hard code the `use_c` variable `True` in `ols_fit.py`.  

<https://github.com/spacetelescope/stcal/blob/6739c1c6b0559943bd4ac29e90e009541e217f00/src/stcal/ramp_fitting/ols_fit.py#L665>

This way allows you to run the pipeline using the C extension.  Unfortunately, since the `OLS` is currently hard coded this is the only way to run the C extension as a part of the pipeline.

The second way is programmatically.  To run the C extension code programmatically requires an already computed `jump` file ready to run ramp fitting.  To run the C code on the jump file instantiate the ramp fit step `ramp_fit_step = RampFitStep()` class, set `ramp_fit_step.algorithm = "OLS_C"`, then run `rate, rateints = ramp_fit_step.process(jump_file_name)`.  The `process` method needs to be called.  If you run the `call` or `run` method, the algorithm is hard coded as "OLS", which will default to the python code.

 

<https://github.com/spacetelescope/jwst/blob/aaf38ad19fee5c25a668153d1a576c700661459e/jwst/ramp_fitting/ramp_fit_step.py#L402>

 

However, this morning I was given authorization to change the above `spec` for the RampFitStep to change the choice of algorithm.  I will change the `spec` today.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3121?focusedCommentId=700402#comment-700402):_

Ticket for the spec change is JP-3632.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3121?focusedCommentId=700405#comment-700405):_

Great, thanks both.  I'm comfortable changing the code to test it, but exposing the parameter makes it much simpler for the instrument teams and any external users to take advantage of it.
