### ISSUE TITLE
Support Update from RHEL7 to RHEL9

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7753]
_Issue [JP-3312](https://jira.stsci.edu/browse/JP-3312) was created on JIRA by [Ian Broussard](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ibroussard):_

Per JSOCINT-712, we need to develop a plan to move from Redhat Linux 7 to 8.  This is also a Cross Division Engineering Initiative being tracked under CDEI-71.  *The end-of-life for REL7 is June 2024.*

We need the component leads for CAL to document what work will be needed to upgrade any use of REL7 or older, and what build it would be feasible to get that work done in.  We are targeting Q1 of 2024 to have this work completed, but each component can let us know if Q1 2024 or earlier would work for them.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=659705#comment-659705):_

Reassigned to Howard, [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) FYI

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=700726#comment-700726):_

[Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) Do you think there's anything jwst Cal needs to be worried about when the DMS Linux servers get upgraded from RHEL7 to RHEL9? Is there a RHEL9 machine on which we could do something like a regtest run?

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=700755#comment-700755):_

I don't expect it will require any changes.

I'm not aware of any RHEL 9 machines. It looks like `science8` and `jwcalibdev` are both version 7.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=700772#comment-700772):_

Since jwcalibdev is our regtest machine, I guess we'll find out the hard way whether RHEL9 causes any issues once that server gets updated!

**Comment by braingram** [comment]
If you're worried maybe we can:
- update jwcalibdev first (or one of the other servers) and test there
- try to spin up a docker image (does RHEL9 require a license?)

Perhaps @jhunkeler has some more ideas or answers.

**Comment by braingram** [comment]
@jhunkeler pointed me to a RHEL9 machine. I am running the unit tests now and will look at running the regtests (likely tomorrow). The only issue I ran into so far was something with the `/tmp` directory permissions which interferes with `pip` (Joe foresaw his and recommended changing the directory with `TMPDIR=/somewhere/else`).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=702304#comment-702304):_

[Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) [Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) Can you post latest results here, in terms of differences you're seeing in the results from RHEL9, to bring me up to speed and to document for posterity.

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=702549#comment-702549):_

To summarize what's known so far, the differences between RHEL7 and RHEL9 match the differences between RHEL7 and ubuntu 20.04 ([Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) performed a number of comparisons and might be able to provide details). Since the differences match and the github actions regression tests run on ubuntu 20.04 they can serve as a proxy for RHEL9 (the current RHEL9 test machine is down so it's difficult to see the results). Examining this [github actions](https://github.com/spacetelescope/RegressionTests/actions/runs/9294710305/job/25610552180#step:25:3373) run shows 11 failures.
 * Common failures (these also randomly fail on RHEL7)

 ** test_nirspec_missing_msa_fail
 ** test_nirspec_missing_msa_nofail
 ** test_duplicate_names
 * coron 3 related failure see <https://jira.stsci.edu/browse/JP-3646>
 ** test_nircam_coron3_sci_exp[003-psfalign]
 ** test_miri_coron3_sci_exp[4-psfalign]
 ** test_miri_coron3_sci_exp[4-psfsub]
 ** test_miri_coron3_sci_exp[5-psfalign]
 ** test_miri_coron3_sci_exp[5-psfsub]
 ** test_miri_coron3_product[i2d]
 * errors that have not been investigated
 ** test_cube_build_miri_ifualign (this is a single pixel difference close to the acceptable tolerance)
 ** test_miri_image3_catalog (there are a handful of differences in this output)

The coron 3 differences appear to be a combination of small numerical differences across systems amplified by the `align_arrays` algorithm used to produce the `psfalign` output (which is used in some of the later products in the pipeline). The test (a pixel-wise comparison) is also very sensitive to to small alignment errors. A reasonable approach given the matching results for RHEL9 and ubuntu 20.04 is to accept the new results as "truth". This would require jwcalibdev being updated to RHEL9 so that the regression tests run there will pass with the new "truth".

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) is there someone who can look into the test_miri_image3_catalog difference?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=702581#comment-702581):_

[Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) Regarding the differences in the test_miri_image3_catalog results, like the others there are only 1 or a few entries showing differences above the current thresholds, and the max differences are still only at the level of ~0.1 percent. These quantities are all derived using various fitting and thresholding methods within photutils functions and hence could easily be susceptible to slight changes in the implementation of third-party numerical algorithms. I don't see them as a big problem.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=708947#comment-708947):_

I looked into the tests Brett mentioned needed investigation:
 * errors that have not been investigated
 ** test_cube_build_miri_ifualign (this is a single pixel difference close to the acceptable tolerance)  -> this one is passing for me with the current main branch
 ** test_miri_image3_catalog (there are a handful of differences in this output)  -> this one required a missing parameter for the function and it is now passing with the following tolerances 
rtol=1e-3, atol=1e-4

PR with fix: #8653

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=710321#comment-710321):_

Test issue for test_miri_image3_catalog is fixed by #8653

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=719038#comment-719038):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) Can this ticket be closed out now?

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3312?focusedCommentId=744454#comment-744454):_

Closing, please reopen [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) if necessary.
