### ISSUE TITLE
Saving pixel_replace step output results in no cal file generated

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7777]
_Issue [JP-3320](https://jira.stsci.edu/browse/JP-3320) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

A user reported that when turning the pixel_replace step on and saving its results, no cal file was generated. This behavior was reproduced, and a cause was found. PR has been filed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3320?focusedCommentId=654442#comment-654442):_

PR filed before ticket here: #7772

**Comment by hbushouse** [comment]
Fixed by #7772

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3320?focusedCommentId=654550#comment-654550):_

Fixed by #7772
