### ISSUE TITLE
"background" fails when combining full and subarray data

### ISSUE THREAD

**Issue by thomaswilliamsastro** [spacetelescope/jwst#7807]
Not sure if this is intended behaviour, but when trying to combine subarray science observations with full chip background observations the background subtraction step fails because the arrays are different sizes. An example for this are two of the MIRI observations for M33 (NGC0598) in program 2130, where SUB256 is used for two tiles in a mosaic, but the background observations use the FULL MIRI array.

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by thomaswilliamsastro** [comment]
This (should) be resolved by #7827
