### ISSUE TITLE
Allow users to scale MRS aperture extraction radii

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7815]
_Issue [JP-3340](https://jira.stsci.edu/browse/JP-3340) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

At present, MRS 1d spectral extraction for point sources is always performed using a conical aperture in which the radius is 2x the PSF FWHM at all wavelengths (based on a linear model of the FWHM outlined by Law et al. 2023).  However, it can be very useful to be able to use different radii, particularly at longer wavelengths where the high thermal background can easily dominate the counts within large apertures by factors of 50 or more.  While it's inadvisable to make the extraction aperture too small due to issues with resampling noise, some flexibility is important and the aperture correction reference files already provide scaling factors from 0.5x to 3x the PSF FWHM.  (Although see <https://jira.stsci.edu/browse/JP-3339)>

At the moment using different apertures is extremely clunky; the extract1d asdf reference file must be modified locally to specify the new aperture radii, and then the pipeline overridden to use this locally edited reference file.

This ticket is to include an easy command line option in the arguments to extract_1d to allow users to scale the default aperture extraction radius by a fixed amount.  E.g., ifu_rscale might define the number of PSF FWHM to use for the extraction radius, accept values in the range of 0.5 to 3.0, and have a default value of 2.0.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3340?focusedCommentId=661512#comment-661512):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw)  I am assuming only the extraction radius is scaled. The inner_bkg and outer_bkg are not scaled or changed at all - CORRECT ?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3340?focusedCommentId=661513#comment-661513):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) 

ifu_rscale can have values of 0.5 to 3. These are the psf FWHM.

The default radius was created with a value of 2.

So really the scaling factor is ifu_rscale/2 - Correct ?
Is the 2 documented in the reference file any place that I should read in or should I just hard code it for now.

**Comment by hbushouse** [comment]
Fixed by #7883

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3340?focusedCommentId=663280#comment-663280):_

Fixed by #7883

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3340?focusedCommentId=672739#comment-672739):_

Tested and working, closing.
