### ISSUE TITLE
Request for API change

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7844]
_Issue [JP-3133](https://jira.stsci.edu/browse/JP-3133) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

This ticket came through Github. It is requesting better naming of keywords. Since it's an API change it may take careful consideration and possibly deprecation of existing keywords.

We should respond on Github with the resolution.

#7495
[jwst/jwst/jump/jump_step.py](https://github.com/spacetelescope/jwst/blob/905ddd0ca3d5141d99960c01c06432fed9ede6cb/jwst/jump/jump_step.py#L21)

Line 21 in [905ddd0](https://github.com/spacetelescope/jwst/commit/905ddd0ca3d5141d99960c01c06432fed9ede6cb)
|| maximum_cores = option('none', 'quarter', 'half', 'all', default='none') # max number of processes to create|

 

For use of the jwst package on a HPC cluster it seems weird to only allow fraction specifications which are, at best, hard to debug.
It would be ideal if one could optionally give an integer value that specifies how many cores it will use.

When reading the documentation it also seems weird that "maximum_cores" refers to a fractional amount of the total. A better word would be "maxcore_fraction", or some other name that is appropriately descriptive.

**Comment by izkgao** [comment]
I noticed that `JumpStep` now supports numbers in the string format for `maximum_cores`. Is it possible to apply this change to `RampFitStep`, which also has a `maximum_cores` parameter? Thank you.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3133?focusedCommentId=697651#comment-697651):_

Both the jump and ramp_fit steps have been updated to allow the `maximum_cores` parameter to support an integer number of cores, as well as the fractional specifications (e.g. quarter, half, ...). Given these updates, I believe the viability of this ticket should be reconsidered. We may want to close this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3133?focusedCommentId=717134#comment-717134):_

Work to address this was completed in spacetelescope/stcal#183 and #8123 ; considering this ticket completed.
