### ISSUE TITLE
Errors in ramp_fit median rate and variance calculations

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7884]
_Issue [JP-3368](https://jira.stsci.edu/browse/JP-3368) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

While converting some of the ramp_fit low-level functions to C, errors were found in the python code for some special cases.

Originally, the median rates excluded only SATURATED flagged groups, but should also exclude DO_NOT_USE flagged groups as well. This affects slope and Poisson variance calculations.

Also, for invalid integrations, non-zero variances were computed, but they should be 0.0. This had already been properly handled for slope calculations in a previous PR addressing JP-3004. Unfortunately, improper calculation of rateints and rate variances continued.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3368?focusedCommentId=661534#comment-661534):_

Also see spacetelescope/stcal#192 and spacetelescope/stcal#203

**Comment by hbushouse** [comment]
Fixed by https://github.com/spacetelescope/stcal/pull/208

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3368?focusedCommentId=661677#comment-661677):_

Fixed by spacetelescope/stcal#208
