### ISSUE TITLE
NIRSpec fixed slit spectra nrs2 spectrum not reduced for G140H + F070LP filter

### ISSUE THREAD

**Issue by jhennawi** [spacetelescope/jwst#7969]
The spec2 pipeline is not reducing or calibrating nrs2 spectra for the combination of G140H+F070LP filter. This is presumably because of second order contamination for lambda > 1.4um. However, for red sources (like high-z quasars) that have no flux below  say 9000A, then there is no second order contamination and so the entire spectral range on nrs2 is usable. This appears to be a major flaw in the pipeline, since it basically throws away very valuable data from 1.4um-2.0um. 

Some workers are adopting hacks by changing header cards, i.e. https://arxiv.org/pdf/2309.06470.pdf discussion on page 3, but this is rather cumbersome. Users should be able to take their chances with second order light when they know it will not have an impact. Maybe an option can be added to allow calibration of NRS2. I tried to look into the source to figure out how to do this, but the stdatamodels.jwst.transforms code that is figuring out which slits are present is inscrutable.

**Comment by hbushouse** [comment]
The association generator rules for NIRSpec were setup to not create any associations containing exposures using certain combinations of grating, filter, and detector (nrs1 or nrs2) that supposedly do not result in any data being projected onto the nrs2 detector. These combinations were specified by the NIRSpec instrument team. You're correct that G140H+F070LP is one of those combinations and hence no processing beyond calwebb_detector1 is done in the automated pipeline for exposures using G140H+F070LP on the NRS2 detector. Changing this behavior would be a decision to be made by the NIRSpec instrument team and not the calibration pipeline development team. So I would suggest submitting this information via the regular JWST help desk system at http://jwsthelp.stsci.edu/, where it should then get reviewed by the NIRSpec team to decide if the change is feasible. I don't know if this particular mode has calibration data available for it.

**Comment by jhennawi** [comment]
Dear @hbushouse, 

Thanks for your quick reply. I will submit the issue to the JWST help desk as you requested.
