### ISSUE TITLE
provide public API for product naming 

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#798]
For Level2 and Level3 associations, the **output name** is specified as part of the association. However, since modules often need to produce multiple types of output and/or there is information in the name that is only available during processing, the product name itself is incomplete in some form. Since information from the association, module, and the data all combine to create the output names, but the format of the name is the responsibility of the association, an association function need be created to produce the DMS correct name, given input from all the above.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] Bring back templates into the product name
- [ ] `load_asn` should return an object with the method.
    - [ ] Explore how close we are to this. It already returns the appropriate class type, but is there enough info known at load.

**Comment by stscicrawford** [comment]
@stscieisenhamer Please close  if finished or re-milestone to Build 7.3

**Comment by stscieisenhamer** [comment]
Resolved by #1322
