### ISSUE TITLE
Difficulties in aligning short wavelenth NIRCAM images 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7993]
_Issue [JP-3435](https://jira.stsci.edu/browse/JP-3435) was created on JIRA by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara):_

In help desk ticket  [INC0193095](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=bad2b3689719f11044d5f6a3f153af10%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true) user reports that she was unable to align short-wavelength NIRCAM images. In some parts of her mosaic stars are doubled. [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert)  notified me that ticket INC0193340 is also very similar to this. When I tried to adjust tweakreg's step parameters, I could improve image alignment in one part of the mosaic only to get worse alignment in a different part.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3435?focusedCommentId=665303#comment-665303):_

To understand what is going on with this data set, I found two images of the same sky region that were taken at different visits. I tried aligning them using standard algorithm for grouping images (8 chips form one group). This resulted in double starts in the overlap region. Then I adjusted the code to choose NRCA4 chip as the "reference" chip to which the second "group" (of 8 images aligned together) will be aligned. This resulted in an image that has good alignment in the previously bad alignment but now overlaps over other chips are bad. Tp illustrate this, I am attaching "misalignment.gif" image. It illustrates what I am talking about.

This experiment indicates to me that WCS assigned to individual chips is likely incorrect (possibly distortion model and/or accounting for gaps between chips). It is difficult to say exactly which chips are affected but based on my experiment, either NRCA3 and NRCA4 or NRCB3 and NCRB4 that have incorrect WCS.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3435?focusedCommentId=665843#comment-665843):_

In ticket INC0193340, user writes:

??In the end I'm going into the model metadata and setting the exposure number manually to something unique so everything is ungrouped. Obviously this isn't ideal but since tweakreg at the moment groups up the simultaneous NRCA and NRCB observations is necessary. I didn't see this in the list of known issues and am surprised it's so big (0.2arcsec is something like 7pix), but for now I think we can work around it.??

First, what user reports as his estimate for the alignment error is in agreement with my own observations on a different dataset.

Second, I believe we should implement the option for users to assign their own grouping so that they do not have to edit metadata.

Finally, with regard to my help desk ticket, there is very little the user can do because of how observations were made (some chips have little or no overlap with others).

Someone from the NIRCAM team should take a look at distortion models and chip positions used to define NIRCAM WCS. To me these models seem misaligned and tweakreg was not designed to deal with these kinds of errors.

**Comment by bhilbert4** [comment]
This is similar to what I have found in other cases recently. Turning off the detector grouping resulted in better alignments. I think this is due to uncertainties/errors in the relative positions of the detectors in the PRD. This is something that the NIRCam team is looking into and will be improving in the future. Discussions with Armin were consistent with what I saw, which was an offset of ~2 SW pixels between the cases with the detector grouping on vs off. 

Note that JHAT, which essentially is a wrapper around a slightly modified version of tweakreg, does not do detector grouping, and provides a good way to run tests.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anton Koekemoer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=koekemoe) on [JIRA](https://jira.stsci.edu/browse/JP-3435?focusedCommentId=665903#comment-665903):_

thanks [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara)  and [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert)  – I agree, and it's indeed already possible to use tweakreg in this mode since tweakreg just uses whatever we give it in terms of an association file, so when running the pipeline manually one just creates separate association files for each detector, then run tweakreg on each one separately (which as Bryan mentions is what JHAT also does, but one can just do this oneself before running tweakreg, even if JHAT is not being used).

I also agree with you both that this isn't really ideal, since aligning each detectors individually results in more uncertainties in the fit since there are fewer sources, and ideally we would want to be able to group the detectors together in a single fit, with confidence that their relative offsets are all correct, as opposed to the ~2 SW pixel offsets that Bryan mentions (which I've heard reported elsewhere too).

So for the user, [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) could perhaps clarify for them the ability to run tweakreg on a custom-made association file for each detector separately (which they may want to consider as an alternative to their editing of the model metadata) – a useful trick that you can suggest for them here is: (1) if they have LW data of the field, then first make a mosaic with that, since each LW detector covers all 4 SW detectors (also running tweakreg separately for module A and B if needed), then (2) make a catalog from the LW mosaic and use that as an absolute astrometry catalog to align each SW detector (running tweakreg separately for each of the SW detectors in each module).

And on the NIRCam team side, we can explore adding some text to the 'known issues' page, as the user suggests, to highlight the fact that offsets on the scale of a few pixels may indeed still be present across detectors (while the distortion models with in each detector are much better known, to the level of milliarcseconds)

**Comment by thomaswilliamsastro** [comment]
To weigh in on this, I found this exact problem very recently. You can degroup the A/B in the tweakreg step if you have the various models loaded in (in this case as `asn_file`):

```
for i, model in enumerate(asn_file._models):
    module = model.meta.instrument.module.strip().lower()

    exp_no = int(model.meta.observation.exposure_number)
    if module == "a":
        model.meta.observation.exposure_number = str(exp_no + 99)
    elif module == "b":
        model.meta.observation.exposure_number = str(exp_no + 100)
    else:
        raise ValueError("Expecting module to either be A or B")

    model_name = list(copy.deepcopy(model.meta.filename))
    model_name[0] = module
    model_name = "".join(model_name)
    model.meta.filename = copy.deepcopy(model_name)
```

you may need to set that exp number and model name back at the end, but this effectively will degroup things at the A/B chip level whilst maintaining everything else

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3435?focusedCommentId=666092#comment-666092):_

??So for the user, ??[Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara)?? could perhaps clarify for them the ability to run tweakreg on a custom-made association file for each detector separately (which they may want to consider as an alternative to their editing of the model metadata) – a useful trick that you can suggest for them here is: (1) if they have LW data of the field, then first make a mosaic with that, since each LW detector covers all 4 SW detectors (also running tweakreg separately for module A and B if needed), then (2) make a catalog from the LW mosaic and use that as an absolute astrometry catalog to align each SW detector (running tweakreg separately for each of the SW detectors in each module).??
 # Indeed, having LW *may* help. However, recently in another ticket - see INC0193409 - user describes similar issues with LW images.
 # Creating custom associations to process a single file may be a solution for some situations but here the overlaps are suboptimal (very little overlap of one detector from one visit with two detectors from another; mostly detectors overlap >90% and any excess  fills the gaps). For example, I modified the code to treat each input image independently (no grouping) and the quality of the alignment is poor.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3435?focusedCommentId=666279#comment-666279):_

My previous point implies that users should be warned about this issue and they should plan observations accordingly making sure images  have sizable inter-detector overlaps.
