### ISSUE TITLE
Errors need to be interpolated in pixel_replace fit_profile code

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8029]
_Issue [JP-3447](https://jira.stsci.edu/browse/JP-3447) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

As mentioned in a comment on <https://jira.stsci.edu/browse/JP-3250,> one origin of NaN values predominating in extracted 1d spectra appears to be the pixel replacement step.

At least for MIRI MRS, ERR values are finite with pixel replacement skipped, and using the 'mingrad' algorithm, but NaN using the 'fit_profile' algorithm.

The reason appears to be that fit_profile interpolates values for SCI pixels, and sets the DQ array so that these pixels are used in cube building, but does not change the ERR values from NaN.  This step should interpolate reasonable values for the ERR as well if these pixels are to be used in later pipeline steps.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=698530#comment-698530):_

Does anyone have suggestions as to the best way to estimate error values for interpolated pixels? There's the simple approach of just interpolating existing error values (if they exist; they might not, if the pixel value is bad), or a more sophisticated approach of estimating uncertainties based on the ERR values of the neighboring pixels that were used to compute the interpolated SCI value.

**Comment by stscirij** [comment]
Probably best to use the approach used in calculating the variances in the drizzled images: the variance is the weighted sum of the variances of the samples used to created the interpolated value and the weights used for the calculation of the variance are the squares of the weights used to calculate the interpolated flux value.  I know that reads horribly, but it makes sense in my head :).  https://jira.stsci.edu/browse/JP-3569 has the actual details.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=698664#comment-698664):_

As I recall the fit_profile method scales a version of nearby cuts across pixel indices to match the existing cut with missing pixel values, and uses those scaled values to fill in the missing values.  I think we'd do the same thing for the ERR values as for the SCI values- build a similar profile and do a similar replacement.  Wouldn't hurt to have a check at the top somewhere to make sure that there's consistency about SCI=ERR=NaN and DQ=DNU going into the routine to make sure that we're replacing all of the possible problem pixels.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=700176#comment-700176):_

[Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) Sounds great, please do!

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=700721#comment-700721):_

This work is done, and posted in a PR here:

#8504

There are likely to be conflicts with the PR to move pixel_replace in the spec2 and spec3 pipelines (JP-3566), so I'm leaving it at draft status until that PR is resolved.

I spot-checked new error and variance values on a few sample data sets and they looked reasonable to me, with both the mingrad and fit_profile algorithms.  [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw), I'll tag you in the PR when it's ready for review.  Let me know if you'd like to test in the meantime.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=700922#comment-700922):_

[Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) Just tested out the latest version as well, and looks good to me.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=700923#comment-700923):_

Great! Thanks for testing!

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=703586#comment-703586):_

Fixed by #8504

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3447?focusedCommentId=703608#comment-703608):_

Tested and confirmed working after the merge, closing.
