### ISSUE TITLE
Add header keyword to record measurement time

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8036]
_Issue [JP-3449](https://jira.stsci.edu/browse/JP-3449) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

Following a meeting on timing keywords (https://outerspace.stsci.edu/pages/viewpage.action?spaceKey=JN&title=Investigation+of+timing+headers) and associated tickets, the decision was made to add the measurement time, i.e. the time from first to last measurement.  

Further clarification required from higher ups on whether the measurement time per integration or total measurement time is required. Relevant eqs:

t_measure_per_int = TGROUP * (NGROUPS - 1)
t_measure = TGROUP * (NGROUPS - 1) * NINTS

At one point, proposed FITS keyword name was TMEASURE - subject to change depending on above clarification.

This ticket will cover work in cal, primarily to update datamodels to allow for the propagation of the new keyword from SDP level 1 through cal processing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-3449?focusedCommentId=669259#comment-669259):_

Just for tracking – I think this will also need a JWSTKD ticket once the details for the header are sorted out.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mario Gennaro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=gennaro) on [JIRA](https://jira.stsci.edu/browse/JP-3449?focusedCommentId=669260#comment-669260):_

t_measure is definitely needed and would be equivalent to the "Measurement Time" reported in eq(3) of the [timing memo](https://outerspace.stsci.edu/display/JN/Investigation+of+timing+headers?preview=/214205927/214205934/Consistent_Times_and_Repetition_Factors_in_ETC_and_APT_RevA_SM-12.pdf#Investigationoftimingheaders-Tag-upnotes)

t_measure_per_int is not strictly necessary but would do no harm. On the other hand I may be overlooking whether eg it would make sense to have t_measure_per_int in some of the products (eg rateints, calints). Possibly a question for the DMSWG and/or CALWG.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-3449?focusedCommentId=672860#comment-672860):_

Help desk tickets:

 
[INC0194102](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=7c4d7a269779351044d5f6a3f153af5f%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

[INC0195024](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=babdd932971e755023a2fe971153af1d%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3449?focusedCommentId=675827#comment-675827):_

Proposed data model attribute name (in JWSTKD-550) is "measurement_time", so use that when updating our schema entry. With a FITS keyword name of "TMEASURE" and data type float. FITS comment/title field "[sec] Measurement Time".

**Comment by hbushouse** [comment]
Fixed by https://github.com/spacetelescope/stdatamodels/pull/248

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3449?focusedCommentId=680753#comment-680753):_

Fixed by spacetelescope/stdatamodels#248

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3449?focusedCommentId=696559#comment-696559):_

JP work done, closing.
