### ISSUE TITLE
1-D spectral extraction problems

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8052]
_Issue [JP-3136](https://jira.stsci.edu/browse/JP-3136) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

Copying from github issue #7365  See that issue for details.

Currently waiting on further details from the user.

**Comment by stscijgbot-jp** [comment]
_Comment by [Sarah Kendrew](https://jira.stsci.edu/secure/ViewProfile.jspa?name=skendrew) on [JIRA](https://jira.stsci.edu/browse/JP-3136?focusedCommentId=670285#comment-670285):_

could tickets like these please be directed to the Helpdesk instead of coming straight to JIRA? we may be able to solve things there without requiring a ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3136?focusedCommentId=670488#comment-670488):_

See <https://stsci.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D3035cb034738a190ec5b9448436d43ce%26sysparm_view%3DJWST%26sysparm_view_forced%3Dtrue> or <https://stsci.service-now.com/nav_to.do?uri=incident.do?sys_id=d34e2a5d977e591023a2fe971153af77> for the Help Desk tickets that spawned the github issue, which were referenced in the discussion there. Communication through all discussion channels appeared to cease in early 2023.

**Comment by hbushouse** [comment]
No response from user in months. Closing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3136?focusedCommentId=670739#comment-670739):_

Given that there hasn't been any response for months from the user in the original help desk ticket(s), I propose we close these as withdrawn. If he ever does respond again, it can continue to be tracked within the Help Desk system.
