### ISSUE TITLE
IFU 1d spectral extraction should account for covariance

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8083]
_Issue [JP-3470](https://jira.stsci.edu/browse/JP-3470) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

As discussed in detail by Law+23 ([https://ui.adsabs.harvard.edu/abs/2023AJ....166...45L/abstract,)](https://ui.adsabs.harvard.edu/abs/2023AJ....166...45L/abstract,) the MIRI and NIRSpec IFU data cubes have significant covariance between adjacent spatial elements.  The amount depends on the type of cube built and the wavelength, but can easily result in a factor of 1.5-2 (for MRS) difference in the actual noise of an extracted spectrum vs the pipeline-reported ERR values in the 1d spectrum.

This can be accounted for via a simple scaling model as described in Law+23 above (Fig 7 in particular, attached here). While this article focused on the scaling factors appropriate for uniform extended sources, a similar exercise can be performed in the opposite limit of point sources whose variance is dominated by Poisson noise instead.  Doing such a simulation of injecting an artificial PSF into a scene, adding poisson-dominated noise into the cal.fits file, it's possible to similarly compare the nominal uncertainty reported in the extracted 1d spectrum to the bootstrapped uncertainty from multiple realizations of the injected noise compared to the noiseless source.  These simulations likewise point to a factor ~2 for point sources as well; this is rather more complicated than the extended source case, as it involves an annular background subtraction as well.

In Ch3B for instance the factor increases from 1.6 at r=0.5 FWHM, to 2.0 at r=2 FWHM, to 2.1 at r=3 FWHM.  This is in keeping with the asymptotic trend observed by Law+.

This broad consistency suggests that most of the necessary improvement would be achieved simply by multiplying all errors extracted from MRS data cubes by a factor of X = 1.8 (mid-way between values of about 1.6 found by Law+ for uniform sources, and values of 2.0 for a similar analysis of point sources).  The uncertainty about this correction factor for a given real observation is likely comparable to the difference between wavebands and apertures, and thus a single multiplicative correction factor is (for now) most warranted.  While it may be possible in future to refine this correction at the 20% level with a more complicated algorithm, it would be helpful to address the factor of 1.8 now as this would be a trivial change.

Question for [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) what the preferred way of doing this would be.  I can see two practical options right now:

1) Add the factor of X directly into the Extract1D code for MIRI MRS.

2) Add a new optional parameter ifu_covar_scale to Extract1D, code default to 1.0, and have MRS parameter reference file set X to the necessary value.

(1) is simpler, but (2) is probably more in keeping with best practice.  While we don't anticipate using different values, it allows users to do so if they wish.  Likewise, it would allow for NIRSpec to provide a non-unity scaling factor too at some point if that proves useful.  (I suspect it will, but I don't know what the value is).

The only downside that I can see is that (2) would be a little harder to unwind if, in some future year, there's a better algorithm for this than simply multiplying by a constant, but I don't see this as particularly problematic.

Also tagging [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) [Bethan James](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bjames)

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=697116#comment-697116):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) for clarification would this factor be different for the different bands of the MRS and likewise it could be different for different gratings/filters of NIRSpec

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=697124#comment-697124):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) For the time being at least, the same factor for all MRS bands, pt/extended sources, extraction radius, band/channel/multi cubes.  Generally, this is because the spaxel scales have all been chosen in about the same manner.  The factor would be different if users specify a custom spaxel scale, and they'd be on their own for now to figure out what it should be in that case.

For NIRSpec I can imagine that it could change between gratings/filters, but as far as I'm aware there's been no study of this as yet.

**Comment by jemorrison** [comment]
In my opinion option 2 would be the best way to do this - via a parameter reference file. If you later change it to different values per band that could be tricky if the s3d cube contains more than 1 band. Just something to keep in mind.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=697136#comment-697136):_

Yeah, that was one of the driving factors behind using a single constant- how to properly deal with 5-28 microns cubes more accurately than that is ill determined.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=697411#comment-697411):_

Fixed by #8457

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=697413#comment-697413):_

Adding a note from talking to [Bethan James](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bjames) that this capability would also be useful for NIRSpec as a placeholder for potential future use (pending a study of NIRSpec covariance).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=697649#comment-697649):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) I agree that the scaling factor set via a new step param is an appropriate approach. Also, given that you've already submitted a PR for the necessary code changes, I'm going to reassign this ticket to you.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=700253#comment-700253):_

Fixed by #8457

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3470?focusedCommentId=702227#comment-702227):_

Confirmed working, closing.
