### ISSUE TITLE
Create jwst DMS B10.1rc1 release

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8125]
_Issue [JP-3486](https://jira.stsci.edu/browse/JP-3486) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

We will need to create jwst release B10.1rc1 to deliver to SDP, once all necessary PR's have been merged and tested (wait for the signal from the jwst Product Owner [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) ). This will be jwst version 1.13.0 and will be the first release candidate for JWST DMS B10.1. It will use stdatamodels 1.9.0 and stcal 1.5.2 as dependencies.

**Comment by hbushouse** [comment]
Not sure why the bot closed this. Reopened.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3486?focusedCommentId=676596#comment-676596):_

B10.1rc1 (jwst 1.13.0) created and delivered on 15-Dec-2023.
