### ISSUE TITLE
Full paths to entries in association files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8129]
_Issue [JP-3489](https://jira.stsci.edu/browse/JP-3489) was created on JIRA by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert):_

In a previous question to SCSB, I was told that the files listed in association files could not contain any path information. 

However, I've seen examples recently (in notebooks used for Masterclass presentations), and spoken to people who have been told by SCSB that entries in association files can contain path information and the pipeline will still run successfully. The caveat is that the entries must contain full paths. If relative paths are used, the pipeline will not work. 

If it's not possible to update the pipeline to respect relative paths, it would be very helpful to update the documentation to explicitly state that full paths are allowed, and relative paths are not. Currently, I don't see any mention or examples in the documentation other than a case where all of the files are in the current working directory.

Given what I had been told in the past, I have always run the pipeline using a script that is in the same directory as the association file and all of the data listed in the association file. However, this can be inconvenient for cases where I'm working with a large number of files, or files from multiple observations/visits/detectors/etc that I would otherwise separate into a more organized directory structure.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3489?focusedCommentId=676062#comment-676062):_

I think that part of the confusion here maybe that while the infrastructure is capable of supporting paths in ASN files, it's a discouraged practice (kind of like using the .run() method).

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-3489?focusedCommentId=676072#comment-676072):_

If that's the case, then maybe that should be added to the documentation. Full paths have been used in examples in notebooks in the recent Masterclass, and most likely JWebbinars as well. So those will now serve as advertisements that having full paths is ok. Just for completeness, when you use relative paths, the pipeline crashes with statements that it can't find the files. That's also confusing from the user's standpoint, since the files do exist where the association file says they do.

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-3489?focusedCommentId=676085#comment-676085):_

I do it all the time, but get warnings in the log output that there should be no path information, that all of the files should be in the same directory. However, when I have one script that I'm using for multiple sets of files in different directories, I just change the directory name and re-run the notebook. It works, but complains.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3489?focusedCommentId=676207#comment-676207):_

I believe the history here is that the pipeline was originally designed around the notion that there would always be a completely flat filesystem.  That has its limitations though as you mentioned, and certainly I constantly use filepaths so that I can separate out stage1/2/3 products into their own directories, manage multiple versions of different product stages, etc.  A while back there was a push to explicitly disable all filepath use, which I recall negotiating down to just a warning instead.  Maybe it's time to document how to use filepaths and raise the warning on relative paths instead.

**Comment by jdavies-st** [comment]
Generally, associations should not contain paths.  They are then not portable.  Association files should live with the files they list as part of the association.  You _can_ use `input_dir` and `output_dir` to pull input and direct output, and the association follows that.

See #5950.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3489?focusedCommentId=719385#comment-719385):_

Fixed by #8789
