### ISSUE TITLE
Update association rules to handle NIRCam WFSS in pure parallel mode

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8167]
_Issue [JP-3500](https://jira.stsci.edu/browse/JP-3500) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Explore data produced by I&T with respect to JSOCINT-721 and develop rules to produce associations for NIRCam WFSS data taken in pure-parallel mode.

**Comment by stscijgbot-jp** [comment]
_Comment by [Katie Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=682868#comment-682868):_

I&T (Kaila) has provided the data needed for development in /ifs/int/jwstc/home/jwowlmgr/JSOCINT_721 , including the the asn_tables, pools, and level1b files.  ssh to any cshed machine to access this data on the ifs. This directory contains data generated using the OTB, and processed on the C-string using PPS version 16.2, PPS_V100 db, and DMS 10.1.1.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=684466#comment-684466):_

[Katie Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida) I've verified that the data provided in the C-string directory should be everything we need. The primary things we need are the pools and level1b files. The Cal side of the work here will be to come up with new ASN rules for WFSS observations taken in this mode that are able to associate the direct images and grism images with one another, as is already done for WFSS observations taken as prime. Once we've got properly constructed ASN files/tables coming out of the generator, the rest of the existing Cal code for WFSS should work as-is.

**Comment by stscijgbot-jp** [comment]
_Comment by [Katie Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=685046#comment-685046):_

Note that Target IDs and WCS issues need to be considered too.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=689403#comment-689403):_

Question – Is it still true that pure parallel data is not processed beyond level-2b (JWSTDMS-577)? I searched the docs high and low but wasn't able to find that info anywhere (sorry if I missed it!). I was chatting with [Mario Gennaro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=gennaro) about this at our team meeting, since we want to make sure we're ready to support this mode. We have 2 confirmed pure parallel WFSS programs for Cycle 3. Let us know if you need help/input for checking out data, or anything else.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=689433#comment-689433):_

[Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) Yes, Alicia, that's still correct. Because pure parallel exposures have a NULL target id set by APT/PPS, we can't build level-3 associations for them. And when you can't build a level-3 association for the direct images that go with WFSS observations, you don't have a source catalog available with which to do level-2b processing of the grism images. So direct images only go through level-2b processing (cal products), while grism exposures can't make it past level-2a (rate), currently.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=689500#comment-689500):_

Note: The bulk of the work has been done. The only open issue is what to use as the target field filler. This is being discussed in the JSOCINT issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=693555#comment-693555):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) I assume this is still in progress and did not make it into B10.2, right?

Linked tickets indicate that the consensus on the target field filler is to use the dummy value "t999". Is that still the plan?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=693577#comment-693577):_

No, this did not make 10.2; that target will be 11.0, unless that is missed also.

DMS-wide discussion in the jsocint issue still ongoing. Unclear as to what should go in the target spot. Since there is time, hopefully something a bit more sensible will be chosen than a magic number solution.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=702354#comment-702354):_

Fixed by #8528

**Comment by stscijgbot-jp** [comment]
_Comment by [Rachel Plesha](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rplesha) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=707037#comment-707037):_

Is there any test data for us to look at to confirm this works as expected? (Asking from the NIRISS side of this ticket)

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=707476#comment-707476):_

Yes there is. From a comment in jsocint-721:


> The test pool file generated from the OTB run, along with the newly generated associations, are located in
> 
> █████████████████████████████████████████████
> 
> for independent verification of correctness. The pool contains the WFSS parallel component of the observations, for both NIRISS and NIRcam. The pool does not contain the primary, presumably because that was not relevant.

**Comment by stscijgbot-jp** [comment]
_Comment by [Katie Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=709325#comment-709325):_

[Rachel Plesha](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rplesha) did the NIRISS team look at the data Jonathan provided above?  Does it look good or are there any changes needed?

**Comment by stscijgbot-jp** [comment]
_Comment by [Rachel Plesha](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rplesha) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=710335#comment-710335):_

Sorry for the delay in this. Here are my findings for NIRISS:

image2 associations
 - jw00025-o001_pool-034-wfss-parallel_image2_00001_asn
 - Everything looks as I would expect

image3 associations
 - jw00025-o001_pool-034-wfss-parallel_image3_00001_asn
 - Everything looks as I would expect.

spec2 associations
 - jw00025-c1000_pool-034-wfss-parallel_spec2_00001_asn — jw00025003001_05201_00001
 - jw00025-c1000_pool-034-wfss-parallel_spec2_00002_asn — jw00025002001_04201_00001
 - The "products" values look right. 
 - I think that the DMSAttrConstraint for “exp type” might be wrong? But I don’t understand this field or what it's used for, so I could be wrong. The first spec2 association has a value “nis_image|nrc_image” and the second has a value “nis_wfss|nrc_wfss”. I would have expected these both to be "nis_wfss".
 - I would have expected jw00025002001_04201_00001_nis_uncal.fits to be in the “00001_asn” and jw00025003001_05201_00001_nis_uncal.fits to be in the “00002_asn” based on the visit numbers in the csv in the directory. I don’t think this is a big deal, but I wanted to mention it still.

spec3 associations
 - jw00025-c1000_pool-034-wfss-parallel_spec3_00001_asn - jw00025003001_05201_00001
 - jw00025-c1000_pool-034-wfss-parallel_spec3_00002_asn — jw00025002001_04201_00001
 - I think these two should be combined into a single association file with two members from my understanding of the spec3 pipeline



Thanks so much for all of the work on these! This will be really helpful for future pure parallel WFSS programs and eventually reprocessing the existing programs. Currently, NIRISS doesn't have any Cycle 3 pure parallel WFSS programs if that helps decide the priority of fixing the spec2 and spec3 associations (assuming I'm correct that there's an issue of course, too).

[Paul Goudfrooij](https://jira.stsci.edu/secure/ViewProfile.jspa?name=goudfroo) please take a look, too when you return from vacation.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=710570#comment-710570):_

[Rachel Plesha](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rplesha) Thanks for the feedback. Here are the responses, from the technical viewpoint:

Concerning the spec2 comments:
* exp_type: One would expect that they would be the same, right. But not necessarily. For this case, there is another constraint, "image_exp_type" and one will note that the values are reversed: Where exp_type is the OR case, image_exp_type is the singular, and vice-versa. To not go on too much with details, but when matching constraints, note that 1) order of constraint matching is not deterministic (or esoteric reasons) and 2) depending on which constraint "hits first", a constraint may be fixed to its matching value, or just allowed to satisfy the OR condition.
* association file numbering: That number is purely a sequential number incremented for each association created and is not related to anything about the association itself.

Concerning the spec3 comments: Due to [JP-2984](https://jira.stsci.edu/browse/JP-2984), the cross-grisms are no longer combined.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rachel Plesha](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rplesha) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=710599#comment-710599):_

Thanks [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham)! I think that all makes sense, and is good from the NIRISS perspective. Paul might have some additional comments when he returns, but I don't think there is anything that should hold this up from our perspective. Thanks again, this is great!

**Comment by stscijgbot-jp** [comment]
_Comment by [Paul Goudfrooij](https://jira.stsci.edu/secure/ViewProfile.jspa?name=goudfroo) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=711405#comment-711405):_

Hi [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) - I agree this all looks good, but I have one more question about the "exp_type" and "image_exp_type" constraints in the spec2 case. Since both of these exposures (jw00025003001_05201_00001_nis_rate.fits and jw00025002001_04201_00001_nis_rate.fits) have the same exp_type, and the same direct image products going into the associations, I don't understand how the two asn json files can have different values of exp_type and image_exp_type. Things come out OK after constraint matching, so the result is OK, but I don't understand why the two json files don't have identical values of those two keywords.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=711658#comment-711658):_

I'll attempt to put together a detail trace for this situation. However, to expand a bit on the previous discussion, an additional key concept is that a particular exposure can match into many different associations, due to matching different rules which create new associations and matching against already created associations. After all the rules have been checked and the initial set of associations are created, a pass is done which weeds out associations. Associations are removed for a number of reasons, such as  associations having the same exact membership and product, incomplete associations, associations that are subsets of other associations, etc.

I am guessing that for this situation, during processing two pairs of associations were created, each with the complimentary values of the two constraints. Then, on the weeding pass, one was removed due to the duplication of membership/product. Due to ordering of matching/duplication checking, the association happen to be chosen with the one set of matches, whereas the other chose the complimentary one.

**Comment by stscijgbot-jp** [comment]
_Comment by [Paul Goudfrooij](https://jira.stsci.edu/secure/ViewProfile.jspa?name=goudfroo) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=711676#comment-711676):_

Thanks, [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham). While I'm interested to see that detailed trace at some point, the result was OK so I don't think this should delay the implementation of this ticket. Thanks!

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=795061#comment-795061):_

Based on discussion above it looks like this can be closed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3500?focusedCommentId=950251#comment-950251):_

Bugfix for NIRCam associations containing short-wavelength direct images here: #9277

**Comment by stscijirahub** [comment]
_This issue is tracked on JIRA as [JP-3500](https://jira.stsci.edu/browse/JP-3500)._
