### ISSUE TITLE
MRS 1d residual fringe correction sometimes fails to run

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8179]
_Issue [JP-3504](https://jira.stsci.edu/browse/JP-3504) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

The MRS 1d residual fringe correction (called from within extract_1d) is sometimes failing to be correctly applied when called, with the relevant call crashing with a singular matrix (this error is caught by the pipeline to prevent a complete pipeline crash, causing a simple skip of the correction).

Whether or not this occurs seems to be erratic; sometimes the error occurs and sometimes it does not when applied to the same input file by the same code run by the same user (when I try reducing 10 Lac spectra for band 2C).  Whenever the correction code is called directly though, it runs fine.

After some trial and error, I've narrowed this down to how the 'channel' parameter is being passed from extract_1d to the residual fringe code.  Residual fringe expects to be passed an integer, while extract_1d is passing a str-type character.  This changes the default set of fringes for which the code searches, and can sometimes (but not always) cause crashes when searching for incorrect fringe frequencies.

Fix is trivial, casting 'channel' as an integer before passing.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3504?focusedCommentId=678830#comment-678830):_

Addressed by #8180

**Comment by jemorrison** [comment]
Thank goodness you found that error. I was encountering it every once in a while.  It was annoying

**Comment by drlaw1558** [comment]
No kidding; obnoxious when things sometimes work fine and sometimes fail...

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3504?focusedCommentId=679398#comment-679398):_

Fixed by #8180

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3504?focusedCommentId=682748#comment-682748):_

Tested and working.
