### ISSUE TITLE
Add keyword NOD_PTS to core schema

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8243]
_Issue [JP-3522](https://jira.stsci.edu/browse/JP-3522) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

A new keyword "NOD_PTS" is being added to NIRSpec MOS observation headers, to better support association rules and their grouping of exposures. Need to define this new keyword in our core datamodels schema. See JWSTKD-555 for more info.

Datamodel name: nod_pts

Keyword title/comment: Number of points in nod pattern

Data type: integer

FITS keyword name: NOD_PTS

Insert into schema immediately following "NOD_TYPE".

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3522?focusedCommentId=684110#comment-684110):_

Setting this ticket back to "Open" status while waiting for the conclusion of DMS/INS discussions about whether we want to implement this new keyword for NIRSpec MOS mode, or use the existing keyword "PRIDTPTS", which stores the same info for NIRSpec fixed-slit exposures.

**Comment by hbushouse** [comment]
Closing, because this change is no longer needed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3522?focusedCommentId=686143#comment-686143):_

Closing, because the new keyword is no longer needed. The Keyword Dictionary review board has decided to use the existing "PRIDTPTS" keyword instead of adding "NOD_PTS".
