### ISSUE TITLE
Remove migrate_data.py and move_wcs.py from repository

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8284]
_Issue [JP-3540](https://jira.stsci.edu/browse/JP-3540) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

The scripts move_wcs.py and migrate_data.py were both used to make pre-flight data compatible with what is now the standard data structure.  These scripts may not be used anymore, which means they should no longer be maintained as part of the pipeline repository.  This came up during handling of JP-2090 but deserves its own ticket.

Please comment:
 * Are these scripts still being used? 
 * What potential reasons are there to keep these in the repository?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3540?focusedCommentId=684425#comment-684425):_

[Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) [Jo Taylor](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jotaylor) Any of you aware of anyone in any of the instrument teams who might be using these 2 scripts for anything? They were both used a long time ago when we made changes in the formats and/or organization of the jwst science data products (e.g. moving FITS WCS keywords from the primary header to the SCI header, additional table columns in extracted spectra, additional table columns in moving target position information, ...) so that folks could update old files to the new formats. I doubt anyone has had a need for them in a long long time.

<https://github.com/spacetelescope/jwst/blob/master/jwst/scripts/migrate_data.py>

<https://github.com/spacetelescope/jwst/blob/master/jwst/scripts/move_wcs.py>

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-3540?focusedCommentId=684428#comment-684428):_

I don't think anyone on the MIRI team is using these scripts.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3540?focusedCommentId=684432#comment-684432):_

I'm not aware of anyone using these scripts for NIRSpec.  It should be fine to remove them.  If a use case does surface later, we can retrieve them from the git history and support them locally.

**Comment by bhilbert4** [comment]
Same for NIRCam. I haven't heard of anyone using these.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3540?focusedCommentId=686520#comment-686520):_

Fixed by #8321
