### ISSUE TITLE
Outlier Detection in Calwebb_image3 fails for some MIRI imaging data 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8298]
_Issue [JP-3548](https://jira.stsci.edu/browse/JP-3548) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

For PID 1193 Obs 20 and 21 (Full frame F2550W data, 4 ditherer data). The outlier rejection step in climate 3 rejects for the 80% of the data.
The error does not occur in version 1.12.5. It was introduced in 1.13.0 or 1.13.1
I had some problems getting 1.13.0 to run. But the error is in 1.13.1 and higher versions. 

Here is a snipet of the log file showing the % of pixels rejected. 

2024-02-21 13:09:32,560 - stpipe.Image3Pipeline.outlier_detection - INFO - Flagging outliers

2024-02-21 13:09:32,638 - stpipe.Image3Pipeline.outlier_detection - INFO - New pixels 
flagged as outliers: 223890 (85.41%)

2024-02-21 13:09:32,763 - stpipe.Image3Pipeline.outlier_detection - INFO - New pixels flagged as outliers: 220650 (84.17%)

2024-02-21 13:09:32,831 - stpipe.Image3Pipeline.outlier_detection - INFO - New pixels flagged as outliers: 231252 (88.22%)

2024-02-21 13:09:32,908 - stpipe.Image3Pipeline.outlier_detection - INFO - New pixels flagged as outliers: 235894 (89.99%)

Attached is an image of the is2d files for Obs 21. In this image - the upper two are jwst 1.13.4 (left), current pipeline on master (right). The bottom one is with 1.12.5. 
!image-2024-02-21-13-12-40-681.png|width=690,height=441!

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=684924#comment-684924):_

Unclear why it's failing for this example, and also for PID 1193 Obs 21.  It is NOT failing though for subarray F2550W data from PID 1522 or 1536

Checking out different version histories, it looks like this got broken by PR <https://github.com/spacetelescope/jwst/pull/7894/files>

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=684938#comment-684938):_

Additional info: the only change that this PR seems to have made for PID 1536, SUB64 imaging in F770W through F2550W was to change the global flux calibration by 0.3%.  Seems to only be some cases in which it can cause a failure in outlier detection.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=685453#comment-685453):_

Looking at the changes in PR 7894 I found that in resample.py a 'iscale' parameter is determined and passed to gwcs_drizzle.py. 
For the 1193 program that is failing I printed out what the iscale value was for each image

 0.9945449150897284

0.9945445386059677

0.9945452915739167

0.9945445386059677

I set iscale to 1.0 in gwcs_drizzle.py. add_image  right before do drizzle is called - line 202 of gwcs_drizzle.py
Now the outliers rejected are more reasonable (4%) and match the number of outliers when JWST 1.12.5 is used.

iscale is  A scale factor to be applied to pixel intensities of the
            input image before resampling.

iscale  = np.sqrt(input_pixflux_area / input_pixel_area)
Printing ou tinput_pixflux_area = 2.84403609523084e-13
input_pixel_area = 2.875320769458513e-13

Any problem with those values ?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=697646#comment-697646):_

I find it surprising that rescaling all the images by ~0.9945 when resampling them, which means the median-combined image will be scaled down by that amount when it's subsequently compared to the original images to look for outliers, would cause that many more pixels to suddenly lie above the rejection threshold. That rescaling factor is barely half a precent. Could this indicate that the default rejection threshold is just too tight?  Alternatively, if images are getting rescaled by this amount when they get resampled to the output WCS grid, does that perhaps imply that when the median image gets blotted back to the original pixel space of the input images it should get descaled by the inverse amount? If it isn't, then maybe that's the problem here.

**Comment by braingram** [comment]
I believe the median image is not being un-scaled when blotted as the `pix_ratio` passed as the `scale` keyword argument to tblot is hard-coded to 1
https://github.com/spacetelescope/jwst/blob/e9d45e2a2d50eea20015f72229390e8b2f03d0a9/jwst/outlier_detection/outlier_detection.py#L502

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=700961#comment-700961):_

Even removing outlier detection from consideration for a moment, I'm puzzled by how resample is treating this case.  If I look at jw01193020001_02101_00001_mirimage_cal.fits then the median pixel value is 918 MJy/sr.  Pretty similar for the 3 other cal files; 919, 920, 921 MJy/sr respectively.  ERR array gives about 2 MJy/sr uncertainty on each pixel.

If I just do a simply strun resample jw01193020001_02101_00001_mirimage_cal.fits though, the corresponding resampled output has a median of 908 MJy/sr.  The entire image is about 1% fainter.  Why is that?  If it's mapping surface brightness to surface brightness shouldn't the value stay the same?

The reason for the rejection in outlier detection then seems pretty straight forward.  Blotted values are similar to the resampled values, and thus differ from the original cal file values by about 10 MJy/sr.  That's over 5 sigma according to the ERR array, and so the flag_cr routine is flagging nearly everything as a cosmic ray.

So, root cause seems likely to be why a simple call to resample is changing the values in the cal file by 1%?  Is it treating them as flux, even though they're in surface brightness units?

**Comment by stscijgbot-jp** [comment]
_Comment by [Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=702727#comment-702727):_

Updated photom and area files were just delivered to CRDS.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=703424#comment-703424):_

Closing ticket since the immediate problem has been fixed via a reference file update, and a separate ticket has been filed for the necessary code work.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=703437#comment-703437):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) What's the separate ticket for code work? Please link it here, for bookkeeping purposes.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3548?focusedCommentId=703438#comment-703438):_

Code work is in JP-3635
