### ISSUE TITLE
readthedocs stable build is out of date

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8299]
_Issue [JP-3549](https://jira.stsci.edu/browse/JP-3549) was created on JIRA by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke):_

It looks like the stable build for the pipeline readthedocs has not been updated in some time:

<https://jwst-pipeline.readthedocs.io/en/stable](https://jwst-pipeline.readthedocs.io/en/stable/jwst/pipeline/calwebb_spec2.html)>

is documentation for jwst v1.8.4, last built November 2022

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=684902#comment-684902):_

I think the "stable" version is built from:
<https://github.com/spacetelescope/jwst/tree/stable>
which hasn't been updated since 1.9.6 (based on the most recent commit message).
The release wiki page is a bit vague on when this branch should be updated:
<https://github.com/spacetelescope/jwst/wiki/Release-Procedures#&#x2060;5-maintain-the-stable-branch-if-necessary>
Some clarification there might help to keep it up-to-date (specifically when is it necessary/not-necessary to update the branch?).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=685641#comment-685641):_

[Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) Option 1 sounds fine to me. As soon as we make a release tag, it presumably means that the code is publicly available on pypi and hence it seems fine to then have "stable" be tied to that release, regardless of whether or not it's been installed into DMS operations yet.

**Comment by stscijgbot-jp** [comment]
_Comment by [Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=685649#comment-685649):_

```java
$ git log --oneline --decorate -n1 upstream/stable
88dfde99f (HEAD -> stable, tag: 1.13.4, upstream/stable, upstream/release/1.13.x, origin/stable, release/1.13.x) metadata for `1.13.4` (#8222)
```
No, I wasn't expecting it to generate a dev tag. The stable branch is aligned with the 1.13.4 tag.

**Comment by stscijgbot-jp** [comment]
_Comment by [Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=685694#comment-685694):_

 
```java
mkdir /tmp/jwst_docs
cd /tmp/jwst_docs
git clone --depth 1 https://github.com/spacetelescope/jwst .
git fetch origin --force --prune --prune-tags --depth 50 refs/heads/stable:refs/remotes/origin/stable
git checkout --force origin/stable

mamba env create --quiet --name stable --file docs/rtd_environment.yaml
mamba activate stable
python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir .[docs]

export READTHEDOCS_OUTPUT=`pwd`/docs_output
mkdir $READTHEDOCS_OUTPUT
cd docs
python -m sphinx -T -W --keep-going -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html```
Adapting the same commands RTD executes to a local run yields 1.13.4 in the docs, not 1.13.5.dev0. So this rules out the sequence being incorrect. RTD is doing the right things and getting the wrong answer.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=704274#comment-704274):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) [Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) when I go to the "stable" link for the JWST RTD it tells me I'm seeing "stable version (1.13.5.dev0+g88dfde9.d20240226)". We never had a 1.13.5 version. B10.1 is 1.13.4 and B10.2 (which was just installed in Ops last week) is 1.14.0. So this page should be build from 1.14.0, since that is now the official stable version of operational code.

**Comment by braingram** [comment]
The stable build failed due to numpy 2.0:
https://readthedocs.org/projects/jwst-pipeline/builds/24718360/
See:
https://github.com/spacetelescope/jwst/pull/8565

**Comment by braingram** [comment]
Oh, what @jhunkeler said :)

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=704338#comment-704338):_

I believe the 1.13.5.dev.0 tag is set automatically as the next development tag.

[Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) Is there a way to force the RTD build to use the release tag on the "stable" branch?

**Comment by jhunkeler** [comment]
Normally we `git reset --hard` the `stable` branch to point to the latest release tag and push it back up. This triggers a rebuild on the RTD side. If we want to it's also possible to activate automatic builds on our `release/x.y.z` branches. The benefit being, we don't have to touch anything for the lifetime of a release branch, but we _do_ need to activate builds as new release branches are created.

**Comment by jhunkeler** [comment]
We can use https://docs.readthedocs.io/en/stable/automation-rules.html to build our tags, or release branches automatically. Enabling this would (I feel like) remove the need for a "stable" branch altogether. If I'm reading this correctly we can configure it to build the latest release tag and set it as default documentation displayed on the site, instead of whatever comes out of `master/main`.

**Comment by stscijgbot-jp** [comment]
_Comment by [Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=708198#comment-708198):_

The following PR was merged yesterday afternoon to address the versioning issue.

#8633

 

The "jwst/stable" branch has been removed. Readthedocs will now automatically generate "stable" documentation using their default semantic versioning rules.

See: <https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working>

**Comment by stscijgbot-jp** [comment]
_Comment by [Joe Hunkeler](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jhunk) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=708421#comment-708421):_

This change will take effect after the *next* release. Readthedocs builds tags. The previous release did not provide the changes we merged the other day, so that's why the current stable documentation is still showing a "0.1" development tag.

I'm marking this resolved.

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-3549?focusedCommentId=708509#comment-708509):_

#8642
