### ISSUE TITLE
Ramp fit is not correctly assigning a rate = NaN for data with no valid segments

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8352]
_Issue [JP-3572](https://jira.stsci.edu/browse/JP-3572) was created on JIRA by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison):_

A bug was found in ramp fit with trying to determine the rate for 4 group NIRSpec data.
The jump step flagged the second and 4th group as a jump. The only good groups were

1 and 3. Since a jump was found between 1 and 3 no valid segment was found. The resulting rate should have been NaN.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3572?focusedCommentId=688420#comment-688420):_

Here is a plot of a pixel ramp. This bug was found on several pixels. I am just showing one example.
!image-2024-03-12-14-22-44-027.png|width=990,height=507!

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3572?focusedCommentId=689198#comment-689198):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) 

I wanted to raise this as an issue that should probably be fixed in the next release. Ramp fit is not working correctly and though this is just 4 groups data - the algorithm seems to have a bug since

it returned a rate value when it should have returned a Nan.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3572?focusedCommentId=689396#comment-689396):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) So this is being closed with no work needing to be done, right?  In other words, there was no actual bug that needed fixing?

**Comment by jemorrison** [comment]
Correct. No fixing in ramp fitting. The real issue is how the jump step flags jumps for coadd data (groups data). But there is an another ticket on that issue. So I closed this issue.
