### ISSUE TITLE
Wrapping detector1 with multiprocessing results in error (M1/M2 issue only?)

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8383]
_Issue [JP-3586](https://jira.stsci.edu/browse/JP-3586) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

From spacetelescope/stcal#247 , a user reports that running detector1 in a multiprocessing environment results in errors. The use case seems to be a decision on which of the following works better:
1) Running N files through detector1 serially, while setting num_cores > 1 for jump and ramp_fit.
2) Running N files through detector1 in parallel using mp, while setting num_cores == 1 for jump and ramp_fit. 

Currently, 1) is functional but perhaps slower than 2), when many files are involved and many threads/cores are available. But 2) appears to be incompatible with the current pipeline, likely due to a multiprocessing call inside a parent multiprocessing call.

**Comment by braingram** [comment]
This may be related to recent changes to the multiprocessing start method which a user reported may impact other code:
https://github.com/spacetelescope/jwst/issues/8306
Also see a PR that addresses start method issue:
https://github.com/spacetelescope/jwst/pull/8343

**Comment by stscijgbot-jp** [comment]
_Comment by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter) on [JIRA](https://jira.stsci.edu/browse/JP-3586?focusedCommentId=695811#comment-695811):_

Already fixed by the PR mentioned above, as well as the documentation updates in #8408
