### ISSUE TITLE
Separate pipeline from non-pipeline tools?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#84]
Are there plans to further separate out the non-pipeline tools from this pipeline repo?

**Comment by hbushouse** [comment]
Any particular tools that you had in mind? datamodels and transforms are now gone. Any others? Or can we close this very old issue?

**Comment by pllim** [comment]
No, I am happy with datamodels finally out of the pipeline package. Thanks! 🙇‍♀️

**Comment by pllim** [comment]
(7 years!)

**Comment by pllim** [comment]
Downstream packages thank you!
