### ISSUE TITLE
No spec2 associations created for NIRSPEC IFU data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8495]
_Issue [JP-3629](https://jira.stsci.edu/browse/JP-3629) was created on JIRA by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij):_

Recent fixes for JP-3151 and JP-3518 appear to have interacted in such a way as to no longer create spec2 associations for NIRSpec IFU data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3629?focusedCommentId=699812#comment-699812):_

[Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) Does this actually affect jwst 1.14.0, which was the version released for DMS B10.2 and will be installed in Ops in June? Or does it only affect the on-going B11.0 development version?

**Comment by stscirij** [comment]
It only affects the ongoing development, not 1.14.0.  The commits were make a few days after the 1.14.0 tag.

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-3629?focusedCommentId=699833#comment-699833):_

I changed the affects version label to "master"

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3629?focusedCommentId=701338#comment-701338):_

Since JP-3518 is still marked ready for testing, I'll follow up on the question about the MOSTILNO constraint on that ticket.  The fix for this ticket is unrelated.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3629?focusedCommentId=702566#comment-702566):_

Fixed by #8508

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3629?focusedCommentId=744457#comment-744457):_

[Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) [Christian Hayes](https://jira.stsci.edu/secure/ViewProfile.jspa?name=chayes) Can this ticket be closed now?
