### ISSUE TITLE
Investigate coron3 differences across systems

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8526]
_Issue [JP-3646](https://jira.stsci.edu/browse/JP-3646) was created on JIRA by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham):_

There are differences in some results for `test_nircam_coron3_sci_exp` when run on different machines (RHEL9 vs RHEL7). The differences look similar to what caused #8490 (leastsq producing slightly different results).

Loosening the tolerance of the regression test comparisons for coron3 results might be one option. However due to the nature of the errors (small differences in image shift) and the comparison (a pixel-to-pixel comparison) a very small difference can result in a large error (some pixels differ by >1E-2).

One source of the pixel differences is that the least squares fit used during align psf uses the default tolerances (xtol and ftol are 1.49012e-08). The algorithm terminates with different results on different machines (but within the default tolerance). However these solutions produce regression test failures due to the issues mentioned above (where a small shift error introduces large pixel differences). These fits are performed with double precision and appear to converge when the tolerances are tightened (up to 1E-15 was tested so far).

**Comment by braingram** [comment]
Cross referencing:
https://github.com/spacetelescope/jwst/issues/8492 and https://jira.stsci.edu/browse/JP-3628

Of particular note is the comment "The level 3 products here are largely used for quick look purposes". It seems likely that we should drastically relax the tolerances for these tests.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-3646?focusedCommentId=709568#comment-709568):_

The differences do seem indeed to be due to the libraries used by the machine the code is run in. The tolerances I am looking at in the current main have been lowered to 1e-5.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3646?focusedCommentId=713042#comment-713042):_

Current status on this is that the changes have been investigated and are fine as is.  The results just need to be okified when we switch over from Jenkins to GitHub Actions for regression tests.  I'll assign to Tyler to track this for closeout.

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3646?focusedCommentId=719451#comment-719451):_

Following merge of #8717 results for coron3 tests on jenkins and github actions pass.
