### ISSUE TITLE
Remove drizpars handling from resample steps

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8541]
_Issue [JP-3651](https://jira.stsci.edu/browse/JP-3651) was created on JIRA by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke):_

When JP-2682 is complete, the drizpars reference file will be deprecated in favor of using parameter reference files for the resample and resample_spec steps.

When it is confirmed that the resample parameters are in place and working well, we should remove all references to the drizpars file from the cal pipeline.

**Comment by braingram** [comment]
FWIW the drizpars use can be removed at any point. Although the file is fetched the contents are not used for the current pipeline. See https://github.com/spacetelescope/jwst/pull/8242 for more details (that PR contained a prototype for a different reference file so is likely not worth fully "reviving" but also removed drizpars with some discussion about why the values are currently ignored).

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3651?focusedCommentId=703085#comment-703085):_

Thanks [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham). I hadn't seen that discussion thread, and the context is useful. 

I think JP-2682 should settle the issues with setting resample parameters satisfactorily.  This ticket is just to track the final code clean up to remove all traces of the drizpars file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3651?focusedCommentId=703659#comment-703659):_

Closing this ticket as a duplicate, because removal of the drizpars ref file usage has been done under JP-2682.
