### ISSUE TITLE
asn_from_list wishlist

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#855]
Need make user happy. Try:

- [ ] documentation
- [ ] clean up defaults/error messages
- [ ] ability to update existing associations
- [ ] attached different types to new members
- [ ] Build more complicated products:
    - level2b with backgrounds & imprint
    - level3 ami/coron
- [ ] Allow the importable python function to be able to write out the association.  Currently, only the CLI can write out the association file.

**Comment by stscieisenhamer** [comment]
@jdavies-st add anything else you come across above.

**Comment by stscieisenhamer** [comment]
# Strawman
`ans_from_list` is based on a very low-level api. For an actual user-level routine, how about the following:

Basic command:
```
asn <command> <args>
```
The basic idea is similar to the `git` command: There would be a number of commands available to do various association operations. Such as:
```
asn create <type> <output> <--append> <--background=background> <--imprint=imprint> <--product-name=productname> <list>
```
The `<type>` would be the more user-obvious type such as `image2`, `spec2`, `image3`, `spec3`, etc.

Another command would be:
```
asn generate <pool> <other generate options>
```
We can then go crazy with extras such as
```
asn edit <existing asn>
```
to bring up a viewer/editor.

**Comment by hbushouse** [comment]
👍

**Comment by jdavies-st** [comment]
Add the wishlist above the ability to run it from within python (with a sane import) and produce a JSON output file.  Currently, only the command-line version can write out an output association.

**Comment by stscieisenhamer** [comment]
@jdavies-st `from jwst.assocations.asn_from_list import asn_from_list`

Now the sane part, well.....

**Comment by jdavies-st** [comment]
Currently `asn_from_list` produces an incorrect association if one tries to create an association with data not in the current working directory:
```
asn_from_list ../*cal.fits -o jw10002_level3_asn.json --product-name jw10002_short
```
The result:
```
{
    "asn_type": "None",
    "asn_rule": "DMS_Level3_Base",
    "version_id": null,
    "code_version": "0.10.1a.dev241",
    "degraded_status": "No known degraded exposures in association.",
    "program": "noprogram",
    "constraints": "No constraints",
    "asn_id": "a3001",
    "target": "none",
    "asn_pool": "none",
    "products": [
        {
            "name": "jw10002_short",
            "members": [
                {
                    "expname": "../*cal.fits",
                    "exptype": "science"
                }
            ]
        }
    ]
}
```
Since associations should **always** live with the input data, this should actually throw a useful error.

We should also at every available opportunity in our code, make it clear that associations need to live in the same directory as the data.  This is not necessarily clear to users.

**Comment by melanieclarke** [comment]
Closing - these issues don't look relevant to the current asn_from_list code, or else they are no longer desirable.  If there are still remaining issues or requests for asn_from_list, please file new tickets.
