### ISSUE TITLE
Remove "R_DRZPAR" definition from datamodels schema

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8558]
_Issue [JP-3656](https://jira.stsci.edu/browse/JP-3656) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

DMS B11.0 removes the use of the drizpars reference file from the resample and resample_spec steps, hence the keyword "R_DRZPAR" is no longer used to record the name of the drizpars ref file used during processing. Once B11.0 has been released and in use for a while the definition of R_DRZPAR can be removed from the datamodels core schema. Perhaps target this for inclusion in B11.1.

**Comment by braingram** [comment]
I opened an issue in stdatamodels for this removal (and other drizpars related items): https://github.com/spacetelescope/stdatamodels/issues/304

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3656?focusedCommentId=717787#comment-717787):_

Fixed by spacetelescope/stdatamodels#316

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3656?focusedCommentId=743956#comment-743956):_

This will require an update to the keyword dictionary as well. [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter) would you open a ticket?

**Comment by stscijgbot-jp** [comment]
_Comment by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter) on [JIRA](https://jira.stsci.edu/browse/JP-3656?focusedCommentId=744014#comment-744014):_

done, see linked ticket
