### ISSUE TITLE
Allow and mandate teams to link their paper(s) on their proposal

### ISSUE THREAD

**Issue by LifeIsStrange** [spacetelescope/jwst#8650]
I have read a ton of JWST proposals and let me tell you the basic truth, JWST proposals are a mess.
It is astonishingly unbelievable for a 20 billion dollars project of tax payers money to have such an opaque science results access. This is nearly obscurantist.

Proposals must have not only their status but also link to their associated papers once they are ready.
A very small percentage of proposals cope with an acronym name in their title that allows to find them on arxiv but for most proposals by far and therefore for most JWST proposals, finding the associated paper(s) can be extremely hard unless by mail spamming the proposal coordinator in the hope he answer.

This is not only primordial and urgent (given we are already cycle 3) but trivial to implement as adding a papers links field should take a few minutes of a developper time.

As for who has the links edit right, the information is already present on the proposal page under the program coordinator field
Might optionally add the investigators and instruments reviewers. Might also as a bonus add a crowdsourcing option (e.g. via automated pull requests to github).
But adding the right for the program coordinator is trivial and should be made as soon as possible.

E.g. What is the status of this 600 hours JWST survey? (largest ever)
It was in cycle 2 meaning it is completed, where is the paper?
https://www.stsci.edu/jwst/science-execution/program-information?id=3990
Even if cycle 2 is recent, most cycle 1 micro observations (less than 24h) should have their papers published by now.. But we have no way to find out, as currently JWST science is simply not browsable.

Teams should be informed that it is the guideline to edit the proposal to link to their paper(s) once they are published in the literature.
Note that there is already an edit mechanism that is provided to the proposal team, given that teams are already able to update the status field of the proposal.

**Comment by drlaw1558** [comment]
Thanks for your feedback- the JWST pipeline team can't address your questions, so I'd suggest that you submit them to the science policies group using the JWST Help Desk (https://stsci.service-now.com/jwst).  If you don't have a MyST account, you should also be able to contact help@stsci.edu
