### ISSUE TITLE
Report jwst software version in output log

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8749]
_Issue [JP-3729](https://jira.stsci.edu/browse/JP-3729) was created on JIRA by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw):_

For user support purposes, it would be helpful to report the version of the jwst pipeline software in use in the output log.  For consistency the best location may be the end of the log next to the existing report of the CRDS context used.

I can see arguments for both having this information at the start of the log (print it early before getting into details) and at the end (end of the log stays on screen for longer, while all of the other log info scrolls the start of the log offscreen instantly).  As such let's add to the end rather than changing existing behavior.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3729?focusedCommentId=716984#comment-716984):_

Related: Looks like the CRDS context is printed at the end of the log for detector1 and spec2, but not for spec3?

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-3729?focusedCommentId=716990#comment-716990):_

Just a guess - that's because spec3 does not use any reference files. However, now that it uses par files we should print it. We'll check all pipelines/steps.

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3729?focusedCommentId=717380#comment-717380):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) would you paste an example of the crds context log message? Is it something like "Results used CRDS context: ..."?

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3729?focusedCommentId=717381#comment-717381):_

2024-09-06 11:13:11,410 - stpipe.Detector1Pipeline - INFO - Results used CRDS context: jwst_1276.pmap

**Comment by stscijgbot-jp** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/JP-3729?focusedCommentId=717949#comment-717949):_

Re-opening as PR with the feature is going to be reverted due to a bug in stpipe that calls `Step.finalize_result` for every character in the input filename for skipped steps. spacetelescope/stpipe#188
A different approach will be needed.

**Comment by braingram** [comment]
New PR using working around the stpipe bug was merged: https://github.com/spacetelescope/jwst/pull/8769

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3729?focusedCommentId=719668#comment-719668):_

With the 1.16.0 tag I'm now seeing

2024-09-20 17:54:50,081 - stpipe - INFO - Results used jwst version: 1.16.0

Looks good, closing!
