### ISSUE TITLE
Intermediate files in outlier_detection clobber each other for MultiSlitModel inputs

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8829]
_Issue [JP-3762](https://jira.stsci.edu/browse/JP-3762) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

When outlier detection runs in during calwebb_spec3 with `save_intermediate_results=True` and the input to the pipeline is a MultiSlitModel, the filenames for the intermediate (`_median`, `_blot`, `_outlier_s2d`) files do not have any indication of the slit they came from, which means that they clobber one another and only the last slit that was processed is saved.

**Comment by stscijgbot-jp** [comment]
_Comment by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter) on [JIRA](https://jira.stsci.edu/browse/JP-3762?focusedCommentId=731415#comment-731415):_

Fixed by #8782

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3762?focusedCommentId=939741#comment-939741):_

Tested with 11.2 and confirmed that each source from NIRSpec MSA is now producing its own set of intermediate files.  Spec3 seems to be taking an enormously long time to run though; that's unrelated to this ticket but will file a new one.

Tagging [Christian Hayes](https://jira.stsci.edu/secure/ViewProfile.jspa?name=chayes) in case you want to test this too, though I don't think necessary.

**Comment by stscijgbot-jp** [comment]
_Comment by [Christian Hayes](https://jira.stsci.edu/secure/ViewProfile.jspa?name=chayes) on [JIRA](https://jira.stsci.edu/browse/JP-3762?focusedCommentId=939744#comment-939744):_

Closing it is fine with me, I had missed this ticket and thought the name collision issue was related to one of the other outlier detection output issues, but noticed that the naming was fixed when testing the other outlier detection improvements in 11.2.

**Comment by emolter** [comment]
@drlaw1558 how were you calling spec3 and on what data?  I'm happy to take a look if you link me the ticket you made

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3762?focusedCommentId=939822#comment-939822):_

[Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter) See <https://jira.stsci.edu/browse/JP-3849>  My guess is that it's part of a general refactor that spec3 may need for MSA efficiency.
