### ISSUE TITLE
Outlier detection with resample_data=False can set non-outlier input pixels to nan

### ISSUE THREAD

**Issue by braingram** [spacetelescope/jwst#8845]
https://github.com/spacetelescope/jwst/blob/72483584eebe7408bdf9f91f11a3690af136db6d/jwst/outlier_detection/utils.py#L121
modifies the input datamodel. This can be seen by modifying `test_outlier_step_no_outliers`:
https://github.com/spacetelescope/jwst/blob/72483584eebe7408bdf9f91f11a3690af136db6d/jwst/outlier_detection/tests/test_outlier_detection.py#L202-L212
Adding the following line after `container = ModelContainer...`:
```python
    container[0].var_rnoise[10,  10] = 1E9
```
to set the `var_rnoise` (used for the default weighting) to a value that will fail the check against the computed threshold. The test proceeds and does not detect any outliers (as expected) but then fails with the `uncorrected` model containing a `nan` for `data[10, 10]` and `DO_NOT_USE` (and not `OUTLIER`) marked for `dq[10, 10] == 1`.

**Comment by braingram** [comment]
@stscijgbot-jp

**Comment by melanieclarke** [comment]
@stscijgbot-jp

**Comment by melanieclarke** [comment]
It looks like there's also a weird file naming issue with saving intermediate files when resample_data=False.  The drizzled models are saved as intermediate files, and the code expects them to have suffix 'outlier_?2d', but they are actually just the same as the input models and shouldn't be saved as intermediate output at all.

I came across both of these while writing a unit test for JP-3347 and I have a fix to propose.  I'll send a PR in a bit.

**Comment by melanieclarke** [comment]
The bot doesn't seem to want to pick this up as a Jira ticket, but since it's really just a follow up to JP-3768, I'll just add a note to that ticket.

**Comment by braingram** [comment]
For future reference, was there anything different I should have done to get the bot to pick this up? It's the first time I tried the "add a comment here" method.

**Comment by melanieclarke** [comment]
I think it's a permissions issue - not everyone can activate the bot.  I should have permission, as a maintainer, but I haven't yet sorted it out for me, either.  I'll let you know when I do!
