### ISSUE TITLE
RSCD step for MIRI data in the Detector 1 Pipeline is not properly handeling segmented files

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8878]
_Issue [JP-3778](https://jira.stsci.edu/browse/JP-3778) was created on JIRA by [Jeroen Bouwman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bouwman):_

The RSCD step for MIRI data in the detector 1 pipeline flags the first few groups of the detector ramps as DO_NOT_USE. Only for the first integration not flagging should be done as the first integration has no RSCD effect. However, in case of segmented files, the RSCD step treats the first integration in each segmented file as if it was the real first integration. This means that every first integration of a segment does not get flagged causing a difference in the ramp fitting and thus a difference in the photometric signal.  The RSCD step should follow the same procedure as is implemented in the dark_current step of the detector 1 pipeline for MIRI data and check if the first integration in a segmented file is the true fist integration or not by checking the  INTSTART and INTEND keywords in the header.

**Comment by jemorrison** [comment]
I have a good idea how to fix this. I think it should be straight forward

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3778?focusedCommentId=742358#comment-742358):_

Thanks [Jeroen Bouwman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bouwman) .  Clarifying, this is a clear bugfix that impacts MIRI TSO data that gets split into multiple segments, and has no effect on other kinds of observations.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3778?focusedCommentId=746497#comment-746497):_

[Jeroen Bouwman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bouwman) I just want to confirm that when you ran this data through caldetector1 YOU set the RSCD step to run. I looked at the parameter reference file for caldetector1 for TSO data and it has RSCD set to skip. So by default it should never have run. 
I am hoping you turned it on or there might be another error some place.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jeroen Bouwman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bouwman) on [JIRA](https://jira.stsci.edu/browse/JP-3778?focusedCommentId=746502#comment-746502):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Yes I made sure the RSCD step was running. It flagged correctly the first 4 groups of  all integrations, apart from the first integration in a segment like it was the first actual integration of the timeseries.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3778?focusedCommentId=758362#comment-758362):_

Fixed by #8946

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3778?focusedCommentId=812251#comment-812251):_

LG2M in 1.17.0; confirmed in a test case that the first few groups are now being flagged by the RSCD step for 'integration 0' in the later segments.
