### ISSUE TITLE
CI appears to be pulling the wrong CRDS context

### ISSUE THREAD

**Issue by tapastro** [spacetelescope/jwst#8985]
From this CI run: https://github.com/spacetelescope/jwst/actions/runs/12040111216/job/33569351428

Under header "Run python -m pip install PyYAML", it appears as though the CRDS context being used is jwst_1293.pmap. Because the CI is running on dev, it should be using at minimum the latest context attached to a release (1298 per https://jwst-crds.stsci.edu/display_build_contexts/), or ideally the edit context because the tests should see an installed jwst version with `dev` in the version string.

Looking at the CI workflow with my limited knowledge, it appears as though the contexts workflow may get called prior to jwst installation. In the past this wasn't an issue, but with the new CRDS behavior that changes which context is returned based on the calibration software version, we may need to change the CI structure.

Thoughts @zacharyburnett ?

**Comment by melanieclarke** [comment]
In case it helps, the failure due to old CRDS context is a little clearer in this run:
https://github.com/spacetelescope/jwst/actions/runs/12039473565/job/33567372537
