### ISSUE TITLE
stage2 processed cal.fits's ERR extension is all nan value after version 1.16.0

### ISSUE THREAD

**Issue by Zijian-astro** [spacetelescope/jwst#9034]
I use the following code to do stage2:

from jwst.pipeline import calwebb_image2

def stage2_worker(args):
    stage2 = calwebb_image2.Image2Pipeline()
    #stage2.input_dir = args[2]  # this does not work; have to create new json2
    stage2.output_dir = args[1]
    stage2.save_bsub = True
    stage2.save_results = True
    stage2.resample.skip = True # No need to run resample since it won't be used anywhere.
    stage2.run(args[0])
    return 
    
   which work well for old jwst pipeline, recently I updated the version of jwst pipeline and found that when using version newer than 1.15.1, the resulted cal.fits files' ERR extension is all nan.
   Could anyone help me with this problem, I really want to use the latest pipeline in my code. Thanks.

**Comment by melanieclarke** [comment]
Hello, and thanks for reaching out! 

I have one quick suggestion: the way you are calling the pipeline via the `.run()` object method does not retrieve the latest recommended parameters for each step from CRDS.  We recommend you use the class method `Image2Pipeline.call()` instead.

For your example:
```
step_param = {'resample': {'skip': True}}
calwebb_image2.Image2Pipeline.call(args[0], output_dir=args[1], save_bsub=True, save_results=True, steps=step_param)
```

There's more information on how to run the pipeline, including some more explanation on how `run` and `call` differ, here:
https://jwst-pipeline.readthedocs.io/en/latest/jwst/user_documentation/running_pipeline_python.html

This may or may not solve your specific problem with all-NaN errors in your data.  If not, I recommend you contact the 
JWST Help Desk (https://stsci.service-now.com/jwst), and include details on which dataset you're looking at. They can help you track it down.
