### ISSUE TITLE
Outlier detection's model readnoise is over-estimated, probably

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#923]
The current code in `outlier_detection.flag_cr` uses a detector's read noise to model the difference between the noise in a blotted image and that in the detector image.  It gets this from the read noise reference file for that detector.

But the reference file gives the correlated double sampling (CDS) read noise for a detector. And JWST IR detectors have multiple reads which are combined to make up a final science exposure.  This ISR from Bryan Hilbert on the NIRCam team shows that the read noise is lower if there are multiple reads for an exposure:

http://www.stsci.edu/hst/wfc3/documents/ISRs/WFC3-2008-25.pdf

Our current algorithm in `flag_cr` is based on that used in `astrodrizzle`, which traces its origins back to `ocrrej` for STIS, described in this ISR:

http://www.stsci.edu/hst/stis/documents/isrs/199822.pdf

It would be good to revisit this and updated the algorithm where needed.

**Comment by jdavies-st** [comment]
Fixed by https://github.com/spacetelescope/jwst/pull/5822

**Comment by karllark** [comment]
So, should this issue be closed?  (Was checking my recent PR for another reason and saw this issue was referenced as being fixed, but not closed).

**Comment by jdavies-st** [comment]
Yes!  Closing.
