### ISSUE TITLE
Outlier detection background subtraction needs fixing

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#925]
Background subtraction is not currently handled correctly in `outlier_detection`.  The `skymatch` step in `Image3Pipeline` computes the background for each input detector exposure and writes them to metadata.  Currently, `outlier_detection` resamples those images without subtracting off the background first.  In cases where background varies significantly between exposures, the subsequent blotted median will have a pedestal offset compared the the detector exposures.

Instead, the background should be subtracted before the resampling in `outlier_detection`, and the background value needs to be taken into account for the noise model in `flag_cr`.

The final resampling in `Image3Pipeline` should be done after sky background has been subtracted.  Perhaps this can be an argument to resample?  Or it can be done in the pipeline itself.

**Comment by hbushouse** [comment]
#1761 is labeled as "initial corrections". What additional work, if any, still needs to be done for B7.3?

**Comment by hbushouse** [comment]
See https://jira.stsci.edu/browse/JP-477

**Comment by hbushouse** [comment]
Closing, because it's now superseded and duplicated by #2930.
