### ISSUE TITLE
stpipe.Step needs one location for spec defaults

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#965]
A pipeline can be run in two different ways with default behavior:
```
collect_pipeline_cfgs .
strun calwebb_spec2.cfg jw95115001001_02102_00001_nrs1_rate.fits
```
or
```
strun jwst.pipeline.Spec2Pipeline jw95115001001_02102_00001_nrs1_rate.fits
```
but the defaults for these are different, as the class doesn't know about the `.cfg` file in case 2 above.  Yet we've put much of our defaults into our example `.cfg` files in `jwst/pipeline/` to tell DMS how these pipelines and steps ought to be run in default mode.  Of course there are some other defaults in the class `spec` too, and these override anything in the default `.cfg` file, regardless of what we put in a default or custom `.cfg` file; the only way to override them is via a `--flag` on the command line or specifically setting the class attribute values from within python after the class is initialized.

I think the `.cfg` files are for customization, and default behavior should be accessible from running the the pipeline without a `.cfg` file.

We need to figure out

1) Where should the defaults be located?  Should they be in a `.cfg` for each pipeline and step, or in the `spec` attribute of a pipeline or step. If in the `spec` attribute, the code currently doesn't look at what any `.cfg` wants to set for anything in `spec`.
2) If we chose the `.cfg` then when a class is initialized, it needs to read the default `.cfg` and update its default `spec`.  `Step` and `Pipeline` classes currently do not do this.

Finally, overriding default precedence should be something like the following:

1) Run the class, get defaults (not currently the case)
2) Run the class, override defaults with `--flag` options (override currently works, but see 1)
3) Run an updated `.cfg` to override defaults (currently works, unless the default is set in the `spec` attribute, then it doesn't)
4) Run the updated `.cfg` with `--flag` options to override what is in the specified `.cfg`

Right now it is also difficult to find out what all the parameters are for a step.  `stspec` calls `Step.print_configspec`, but there are many attributes that are not printed here, such as `suffix`, `override_REFFILE`, etc.  The documentation for a specific step doesn't currently doesn't help here either - it doesn't tell us that `skip` and `save_results` and other general options for all steps are available parameters that can be changed.

Comments?

**Comment by melanieclarke** [comment]
Closing in favor of #5909, which will deprecate collect_pipeline_cfgs.
